### ISSUE TITLE
Clarification - Feature updates delay period

### ISSUE THREAD

**Issue by chookster** [ChrisTitusTech/winutil#1008]
On the main Github page it says...
Updates:
Security (Recommended) Settings: Offers recommended settings, including a slight delay of **feature updates by 2 days** and installation of security updates 4 days after release.

In version 2023-09-07 Updates tab it says...
It will delay **feature updates by 2 years** and will install security updates 4 days after release.

Can anyone clarify whether feature updates are delayed by 2 days or 2 years please?

**Comment by ChrisTitusTech** [comment]
2 years. Feature updates are terrible for reliability.

**Comment by ChrisTitusTech** [comment]
commited https://github.com/ChrisTitusTech/winutil/commit/5b3ae84fc26bc4ce052e6eb19c462bdcae79a674 
Will hit main branch on next update
