### ISSUE TITLE
Boost volume over 100% on Windows

### ISSUE THREAD

**Issue by Davidgithub1** [ChrisTitusTech/winutil#1011]
**Is your feature request related to a problem? Please describe.**
My laptop max volume is very low, I can't hear anything.
VLC allows you to increase the volume over 100%, which solves the problem for Audio played on VLC.
But doesn't solve the problem for Firefox and other Windows apps.

**Describe the solution you'd like**
Here is the solution:
I had a similar issue with watching quiet streaming videos in Windows 7 using my unamplified headphones. Here's my solution (Whether it works for you or not will depend on your hardware configuration, but Realtek audio is pretty common)

Go to "sound" in control panel (small icon view in Windows 7)

Click the "properties" button bottom right for the default output device (on my system it's Realtek High Definition Audio)

In the Enhancements tab make sure Loudness Equalisation and Environment are ticked. (They aren't by default)

That's it - quiet streaming videos now have a much louder sound range on my system using basic unamplified headphones.

Winutil should have an option to enable this!

**Comment by ChrisTitusTech** [comment]
It does, the old sound panel `mmsys.cpl` is built in. Here is a screenshot to do it. 
![image](https://github.com/ChrisTitusTech/winutil/assets/7896101/2fa547c0-2a67-412e-8cf4-ee4e15f23b20)
