### ISSUE TITLE
Bitdefender blocks action when trying to install a selected software.

### ISSUE THREAD

**Issue by mrego79** [ChrisTitusTech/winutil#1016]
First time I use it by following the instructions on One Tool for Everything page. Run via powershell. Checked Chrome only and hit install. Powershell said Winget failed to install while Bitdefender drops a message about a threat. Check screenshot. 

![Screenshot_1](https://github.com/ChrisTitusTech/winutil/assets/144621653/68a957e9-bfd2-47af-940a-c09c42ddafa9)

**Comment by ChrisTitusTech** [comment]
Bitdefender disables most powershell scripts from running or modifying the system either create an exception or disable bitdefender.

**Comment by mrego79** [comment]
Thanks. I just wanted to make sure its not a malware or something got through your defences somehow. Anyway, great tool you did mate!
