### ISSUE TITLE
Remove onedrive 

### ISSUE THREAD

**Issue by MrDisguised** [ChrisTitusTech/winutil#1017]
**Is your feature request related to a problem? Please describe.**
Most of the people who use windows don't need one drive. One drive is a bloatware. I think it would be awesome if there was an option to remove windows one drive in the `Tweaks` secton.
**Describe the solution you'd like**
There are many scripts that can be added to remove one drive from our pc like - 
1. https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/remove-onedrive.ps1
2. https://github.com/TERRAOperative/OneDrive-Uninstaller
3. https://github.com/Marco-Sap/OSDScripts/blob/master/V2/Remove-OneDrive.ps1
and many more

**Comment by ChrisTitusTech** [comment]
Yeah I have it on the to do list #385 
I'll probably just grab one of those scripts that stays mostly in powershell and maybe tweaks it a bit for the project.

**Comment by MrDisguised** [comment]
> Yeah I have it on the to do list #385 I'll probably just grab one of those scripts that stays mostly in powershell and maybe tweaks it a bit for the project.

Oh thanks a lot!! :D I am closing this issue then because there is no point in creating duplicate issues.
