### ISSUE TITLE
Golang installation is broken

### ISSUE THREAD

**Issue by wanjohiryan** [ChrisTitusTech/winutil#1019]
**Describe the bug**
When i try installing golang with the winutil script, i get 
![2023-09-12 10_35_51-Select Administrator_ Windows PowerShell](https://github.com/ChrisTitusTech/winutil/assets/71614375/936344c4-2220-4daa-9569-36346c1f45d4)

**To Reproduce**
1. Go to Install section
2. Click on Golang which is located under ``development``
3. Go back to the powershell window and check whether it was installed
![2023-09-12 10_41_59-New Issue · ChrisTitusTech_winutil - Brave](https://github.com/ChrisTitusTech/winutil/assets/71614375/a3b197ad-0d7b-42e4-9dba-ea22d34891f1)
![2023-09-12 10_42_58-New Issue · ChrisTitusTech_winutil - Brave](https://github.com/ChrisTitusTech/winutil/assets/71614375/a769e613-a7fe-48f0-8c8f-0887f3ef2c6c)

**Expected behavior**
When i click on install golang, golang should be installed. The command ``go version`` should work

**Screenshots**
See previous

**Additional context**

**Comment by ChrisTitusTech** [comment]
Thanks for the report looks like package name changed. I updated it on test and it will be merged to main in the coming weeks. 
commit db4f492
