### ISSUE TITLE
Add Viber for desktop to the app install page

### ISSUE THREAD

**Issue by smoothoperatorgr** [ChrisTitusTech/winutil#102]
**Is your feature request related to a problem? Please describe.**
it's an addition proposal.

**Describe the solution you'd like**
I would like there to be in the apps install Viber for desktop.

**Describe alternatives you've considered**
Downloading the Viber for desktop manually through the Viber website.

**Additional context**
Viber is really popular in Europe!

**Comment by ChrisTitusTech** [comment]
Added in #240 - Closing Issue
