### ISSUE TITLE
NEED HELP 

### ISSUE THREAD

**Issue by strunz983** [ChrisTitusTech/winutil#1021]
Hi i have problem with winutil.ps1
When i click on Run Tweaks i get this error
My OS is Windows 11

<img width="888" alt="Untitled" src="https://github.com/ChrisTitusTech/winutil/assets/42872580/b99d4926-e5dd-4560-b521-275f10d5a41a">

Checking if Chocolatey is Installed...
Chocolatey Already Installed
Changing system to allow multiple restore points per day
Exception calling "ShowDialog" with "0" argument(s): "The running command stopped because the preference variable "Erro
rActionPreference" or common parameter is set to Stop: Cannot find path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVer
sion\SystemRestore' because it does not exist."
At line:5976 char:1
+ $sync["Form"].ShowDialog() | out-null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ActionPreferenceStopException

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by adarshd07** [comment]
me too i also getting the same 
plz recomment when find the solution 
if i do i will comment here

**Comment by strunz983** [comment]
Hi i found the solution 
You need to enable Changing system to allow multiple restore points per day and this is command
REG ADD "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore" /V "SystemRestorePointCreationFrequency" /T REG_DWORD /D 0 /F
https://www.elevenforum.com/t/change-system-restore-point-creation-frequency-in-windows-11.3613/
