### ISSUE TITLE
Cannot install iTunes on Windows 11 Pro on ARM

### ISSUE THREAD

**Issue by alexeygridnev** [ChrisTitusTech/winutil#1022]
**Describe the bug**
Cannot install iTunes on Windows 11 Pro on Arm (tested in Mac Mini M2 in Parallels). With a regular installer (downloaded from Apple website), an x64 version installs and runs normally (under x64 emulation layer). 

**To Reproduce**
1. Go to "Install" tab
2. Click on "iTunes" checkbox and click "Install Selection"
3. Check the PowerShell output

**Expected behavior**
iTunes installs automatically

**Actual behavior**
The winget install fails with the error message: "Installer hash does not match; this cannot be overridden when running as admin", at the same time shown a window saying "done". 

**Additional context**
Tried to solve manually by running "winget settings --enable InstallerHashOverride", does not work. Installing with Chocolatey manually ("choco install iTunes") works fine but winuits tool does not offer such an option after a failed install with Winutils.

**Comment by AI1120** [comment]
I have installed macOS Tahoe using VMware Workstation Pro 25H2 and encountered an issue when attempting to sign in to my Apple ID: "Verification failed. An unknown error occurred."
How can I resolve this issue?
