### ISSUE TITLE
Windows 10: Script not applying tweaks and printing out some error

### ISSUE THREAD

**Issue by NelloKudo** [ChrisTitusTech/winutil#1025]
**Describe the bug**
Winutil won't apply any tweak from the dropdown menu on a clean Windows 10 install made with latest mediacreationtool.exe
After launching it from PowerShell, there's indeed some issue with `convertfrom-json`.
**To Reproduce**
1. Install Windows 10 (English ver.)
2. Open Powershell as admin
3. Run the script

**Expected behavior**
I just expected it to work as always xd

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/98063377/38df5585-7946-4101-8bc6-4c517552649d)

![image](https://github.com/ChrisTitusTech/winutil/assets/98063377/6cfeb09f-7bb5-4efa-b896-d4396aea35eb)

![image](https://github.com/ChrisTitusTech/winutil/assets/98063377/993a8a49-6986-4741-b5c4-7fd9fe28ebf6)

**Comment by StephanDaaboul** [comment]
I am having this issue and same error output in Windows 11 clean install.

**Comment by IVAN2527** [comment]
Thanks

**Comment by ChrisTitusTech** [comment]
Just did an update. Let me check

**Comment by ChrisTitusTech** [comment]
I see the issue with it. Using Windows Terminal (Admin) Work but old powershell 5 doesn't and spits out convert-json errors.

**Comment by ChrisTitusTech** [comment]
Found it! powershell 5.1 has a bug where if their is a trailing common on the last entry in JSON it errors like this. Really dumb, but then again it's Microsoft...
commit 1fb9f3e
