### ISSUE TITLE
Disabling Virtualization Based Security

### ISSUE THREAD

**Issue by XxShyW0lf** [ChrisTitusTech/winutil#1026]
Since VBS does reduce CPU performance by a noticeable amount. Could be a good idea to add that option to disable it.

**Comment by ChrisTitusTech** [comment]
From all my testing VBS didn't really do much in either direction. Did you test this?
I haven't seen any test where it harmed or helped a computer.

**Comment by XxShyW0lf** [comment]
Yes, I did some testing. I sadly do not have the results screenshotted. I did some benchmarks using Minecraft Java Edition. One with VBS enabled(running) and one without it. VBS enabled: Avg 500FPS with horrible stuttering. Without VBS: Avg 600 to 750FPS without any stuttering.

**Comment by ChrisTitusTech** [comment]
Good enough for me. I'll disable it. 

> Yes, I did some testing. I sadly do not have the results screenshotted. I did some benchmarks using Minecraft Java Edition. One with VBS enabled(running) and one without it. VBS enabled: Avg 500FPS with horrible stuttering. Without VBS: Avg 600 to 750FPS without any stuttering.
> 
> Both test captured using CapFrameX

**Comment by afzl-wtu** [comment]
How to turn off vbs only and not wsl2?
@ChrisTitusTech @XxShyW0lf
