### ISSUE TITLE
Widgets return after running recommended laptop tweaks.

### ISSUE THREAD

**Issue by xxheyhey** [ChrisTitusTech/winutil#1029]
**Describe the bug**
Everytime I run the recommended laptop tweaks (haven't tried other eecommended selections), the widgets pin reappears on the taskbar.

**To Reproduce**
1. Go to 'Tweaks'
2. Click on 'laptop' in the 'Recommended Selections' section
3. Press Run Tweaks
4. Widgets reappear next to the windows button in the taskbar.

**Expected behavior**
No reappearance of the widgets pin after running tweaks.

**Comment by crian** [comment]
Yes that's normal and if I remember correctly it is caused by ooshutup.

**Comment by nicogerber** [comment]
Could we disable Widgets again after running ooshutup?

```
$Path = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
Set-ItemProperty -Path $Path -Name "TaskbarDa" -Value 0
```

**Comment by jesjess243** [comment]
Same here on Windows 11 Home. 

@n8x0b7t offered a workaround https://github.com/ChrisTitusTech/winutil/issues/555#issuecomment-1568814334 that worked for me:

`winget uninstall "windows web experience pack"  --accept-source-agreements`

Gone without a trace:

![Screenshot 2024-01-27 140857](https://github.com/ChrisTitusTech/winutil/assets/123990927/065f8ab1-c1fd-4b3b-a11c-83aec81a945a)
