### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kiquenet** [ChrisTitusTech/winutil#103]
**Is your feature request related to a problem?.**

Only improvements like:

Unpin to taskbar Microsoft Store, Mail, ... apps
Pin to taskbar any apps like Remote Desktop

Set SearchProvider and SearchProviderUrl for Google in Edge navigator.

Pin to QuickAccess

Pin to Start Menu

Connect to network drive

Shortcuts

**Describe the solution you'd like**

Pin / Unpin to taskbar
https://stackoverflow.com/questions/9739772/how-to-pin-to-taskbar-using-powershell

Hidden Cortana button

Edge
https://stackoverflow.com/questions/60892120/edge-chromium-gp-how-to-set-google-as-default-bypass-first-run-dialog-and-ha

Pin to QuickAccess
https://stackoverflow.com/questions/30051634/is-it-possible-programmatically-add-folders-to-the-windows-10-quick-access-panel

Pin to Start Menu
https://stackoverflow.com/questions/9903847/how-to-pin-to-start-menu-using-powershell

Connect to network drive
https://www.itechguides.com/how-to-map-a-drive-in-powershell/

Create shortcut
https://stackoverflow.com/questions/9701840/how-to-create-a-shortcut-using-powershell

**Describe alternatives you've considered**
Using powershell

**Additional context**
Windows 10 20H2

**Comment by couleurm** [comment]
> Unpin to taskbar Microsoft Store, Mail, ... apps

A very fancy function for this [already exists](https://github.com/farag2/Sophia-Script-for-Windows/blob/ebfafd66c3eb9b6914d6251277060afe664b0d21/src/Sophia_Script_for_Windows_10/Module/Sophia.psm1#L3131), also MIT-licensed (as far as I've looked)

**Comment by dennyamarojr** [comment]
Another function that could be useful is the ability to export current state of windows services before applying tweaks, here's the issue I opened to review #673

**Comment by IJayJayI** [comment]
I see Kodi is already added to this and VLC player for programs. Another good program to add would be the media program called Stremio. Thanks!

**Comment by andreialecsandru** [comment]
please make "uninstall edge" to affect only the legacy edge. the chromium edge is useful sometimes. or maybe add a separate option to uninstall it. i mean one option for legacy and another option for chromium. thanks.

**Comment by dennyamarojr** [comment]
Hi @andreialecsandru  @ChrisTitusTech  already answer a similar question related to edge and not sure if this will be implemented due the fact Chris already warn the users that the script removes edge. About edge legacy is already removed from the system except for the files in SystemApps folder that microsoft just keep due the LTSC and LTSB versions that has support and maybe use edge legacy (not sure) or they just forget the folders right there. Anyway, all the edge chromium stays on C:\Program Files now and removing the folders from SystemApps needs a really deep scan of regedit and folders inside windows to find all related to edge legacy and for edge chromium I think that is more easy to find. 

But maybe this suggestion could be good to have in the list

**Comment by andreialecsandru** [comment]
> Hi @andreialecsandru @ChrisTitusTech already answer a similar question related to edge and not sure if this will be implemented due the fact Chris already warn the users that the script removes edge. About edge legacy is already removed from the system except for the files in SystemApps folder that microsoft just keep due the LTSC and LTSB versions that has support and maybe use edge legacy (not sure) or they just forget the folders right there. Anyway, all the edge chromium stays on C:\Program Files now and removing the folders from SystemApps needs a really deep scan of regedit and folders inside windows to find all related to edge legacy and for edge chromium I think that is more easy to find.
> 
> But maybe this suggestion could be good to have in the list

Yeah. The legacy is technicaly removed but some shortcuts are srill there. In the app list or in default browser choose settings.
