### ISSUE TITLE
.: Upgrade All :. Issue with this function

### ISSUE THREAD

**Issue by kAMENkitA** [ChrisTitusTech/winutil#1030]
**Describe the bug**
After pressing UpgradeAll under Installation Tab I get following error (screenshot) :
![image](https://github.com/ChrisTitusTech/winutil/assets/87366745/a49b38b9-157f-4140-9120-946218665b63)

**Expected behavior**
..nothing happens after that message..

**Additional context**
WIndows 11
![image](https://github.com/ChrisTitusTech/winutil/assets/87366745/20d17035-c4df-41ef-a4b9-12cf41595e3d)

p.s. 'please help'

**Comment by anonyao** [comment]
Becuse your have removed winget.cli or something | Run PowerShell As admin . try 1) Install-script -name  winget-install  -Force
2) Choco Install Winget.cli / winget -force | 3) Choco upgrade Winget -force

**Comment by kAMENkitA** [comment]
..than U for intervention .. i will try soon .. and report about results .. :)
