### ISSUE TITLE
Windows crashes to blue screen

### ISSUE THREAD

**Issue by Sh00t3rss** [ChrisTitusTech/winutil#1034]
![IMG_3750](https://github.com/ChrisTitusTech/winutil/assets/46882995/42d1a55e-16e6-466c-a6af-a09b5751363b)

![IMG_3748](https://github.com/ChrisTitusTech/winutil/assets/46882995/4a947c2d-5aef-4ce5-9b5b-fa2f1a2e73d7)
All I did was implement the tweaks that were recommended. Left everything else alone. See screenshots. 
![IMG_3749](https://github.com/ChrisTitusTech/winutil/assets/46882995/64476620-90b6-418f-bc7c-6f000ccdde4e)
Windows is up to date. My comp is running great besides that. Even my CPU which was pegged at 100% for no reason is now down to between 5% and 15% at idle.

**Comment by kelvinkad** [comment]
It happened the same to me. I don't know what caused it, but it was after applying tweaks. I tested formatting my windows and using for a week, everything fine. As soon as I applied tweaks again, blue screen came back. 
I already reported this same thing here, but it was marked as closed by dev.

**Comment by 8mpty** [comment]
Could be issues on your physical hardware as i've gotten these kinds of error before and all were because of some parts of my PC failing one by one.
