### ISSUE TITLE
IPv6 Xbox Party App

### ISSUE THREAD

**Issue by ThatLadLegend** [ChrisTitusTech/winutil#1039]
**Is your feature request related to a problem? Please describe.**
When disabling IPv6 it causes features related to Teredo and makes it so you cannot join parties via the Xbox app.

**Describe the solution you'd like**
Just include that disabling this could interfere with Xbox party chat on the PC App as most people do not know this.

**Comment by kAMENkitA** [comment]
just repeating my comment below Chris's YT ((https://www.youtube.com/channel/UCg6gPGh8HU2U01vaFCAsvmQ/community?lc=UgxtZ87GAeyy1NzQgHJ4AaABAg&lb=UgkxmolAmFRGjjGe4VBYd2OePyluyrRNAz2a)):

"..thank You Chris, wonderful work as always..huge shoutOut to U & buddies helping U in further evolution of the TOoL .. just digression..IPv6 is needed for the TEREDO Tunneling..isnt it.?. which is necessary for Forza Motosport, Forza Horizon and similar..

**Comment by ThatLadLegend** [comment]
> just repeating my comment below Chris's YT ((https://www.youtube.com/channel/UCg6gPGh8HU2U01vaFCAsvmQ/community?lc=UgxtZ87GAeyy1NzQgHJ4AaABAg&lb=UgkxmolAmFRGjjGe4VBYd2OePyluyrRNAz2a)):
> 
> 
> 
> "..thank You Chris, wonderful work as always..huge shoutOut to U & buddies helping U in further evolution of the TOoL .. just digression..IPv6 is needed for the TEREDO Tunneling..isnt it.?. which is necessary for Forza Motosport, Forza Horizon and similar..

ah, yes I forgot that this also affected games like Forza etc. Thanks for including it.

**Comment by francisuk1989** [comment]
I have tried this myself on Windows 10 Pro and seems to work fine if disabing IPv6.

Maybe a Windows 11 issue?

**Comment by ThatLadLegend** [comment]
> I have tried this myself on Windows 10 Pro and seems to work fine if disabing IPv6.
> 
> 
> 
> Maybe a Windows 11 issue?

I am on Windows 10 Pro as well. Disabling IPv6 and restarting your system will cause Teredo not to function in most cases and does for me.
