### ISSUE TITLE
cttwu update issues

### ISSUE THREAD

**Issue by rharvey3401** [ChrisTitusTech/winutil#104]
**Describe the bug**

ran ctt powershell program
clicked updates
clicked default out of box

this is what I get 
in shell window

Setting BITS StartupType to Automatic
Setting wuauserv StartupType to Automatic
Enabling driver offering through Windows Update...
Enabling Windows Update automatic restart...
Enabled driver offering through Windows Update
1. Stopping Windows Update Services...
2. Remove QMGR Data file...
3. Renaming the Software Distribution and CatRoot Folder...
4. Removing old Windows Update log...
5. Resetting the Windows Update Services to defualt settings...
6. Registering some DLLs...
7) Removing WSUS client settings...

ERROR: ERROR: The system was unable to find the specified registry key or value.
ERROR: at <ScriptBlock>, <No file>: line 1330 ERROR: at <ScriptBlock>, <No file>: line 1489 ERROR: at <ScriptBlock>, <No file>: line 1
ERROR EXCEPTION: System.Management.Automation.RemoteException: ERROR: The system was unable to find the specified registry key or value.

Sleeping for 60m to give you time to look around the virtual machine before self-destruction...
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ChrisTitusTech** [comment]
Fixed in commit 6905b04b003fa7c45139676d0b8c16031a79481c
