### ISSUE TITLE
mpv.net and MPC-BE

### ISSUE THREAD

**Issue by ColonelGerdauf** [ChrisTitusTech/winutil#1047]
These are the players I'd like to see included in the listings of apps to install.

The former is a (relatively) ease-of-use oriented build of MPV, which is a bleeding edge player that supports many of the modern features and mechanisms. Among them is floating window, layered UI and full Flip Model usage.

MPC-BE is a "skin" of standard Media Player Classic that alongside parity updates, supports a few other smaller things and sports a usable and customizable dark theme.

**Comment by francisuk1989** [comment]
+1 for mpv 

Also there needs to be an option for x86_64 or x86_64-v3 (for CPU with AVX2 support).

https://sourceforge.net/projects/mpv-player-windows/files/64bit - x86_64
https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/- x86_64-v3

**Comment by ColonelGerdauf** [comment]
This is the github repo of the MPV build I was talking about: https://github.com/mpvnet-player/mpv.net

**Comment by SandeMC** [comment]
+1 for mpv.net, why is this still not added?

**Comment by SandeMC** [comment]
what the fuck is that bot
