### ISSUE TITLE
DWORD values in hexadecimal result in error Cannot convert value _ to type "System.UInt32"

### ISSUE THREAD

**Issue by djust270** [ChrisTitusTech/winutil#105]
For example, at line 741

``Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "SystemResponsiveness" -Type DWord -Value 0000000a``

The DWORD value should be specified in base 10 decimal not hexadecimal.

![dword_error](https://user-images.githubusercontent.com/57944742/184611238-77b471c5-d589-433e-b363-fe81d8ce1eeb.PNG)

**Comment by ChrisTitusTech** [comment]
Fixed in commit f7b0d614192d5c3090d5ecb1dd1dc44b39fa80ee
