### ISSUE TITLE
Security Updates not working in Windows 11?

### ISSUE THREAD

**Issue by Manifold2** [ChrisTitusTech/winutil#1055]
When I was on Windows 10, the security update option was working. Then I switched recenlty to Windows 11 and I can see it doesn't work here

**Comment by ChrisTitusTech** [comment]
What version of Windows are you on Pro? 
Home editions revert most of these settings on big updates as they don't have group policy. I'm going to modify the script to enable group policy for home users, but haven't yet.
To check your verison just type `winver` into the run box `Win +R`

**Comment by Manifold2** [comment]
I am using Home, I have extra key for Pro and this may be the best option?

**Comment by Manifold2** [comment]
By the way, no rush and take your time

**Comment by ChrisTitusTech** [comment]
Yeah I'd switch to Pro. You end up missing out a few key features with home.

**Comment by Manifold2** [comment]
Just update, it worked on Pro edition
