### ISSUE TITLE
Exception calling "ShowDialog", Cannot find registry path

### ISSUE THREAD

**Issue by rikdol** [ChrisTitusTech/winutil#1069]
**Describe the bug**
Trying to run all tweaks for the ' desktop'  setting. 
First few commands work, then shows the following error:

====Chris Titus Tech=====
=====Windows Toolbox=====
Checking if Chocolatey is Installed...
Chocolatey Already Installed
Changing system to allow multiple restore points per day
Exception calling "ShowDialog" with "0" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore' because it
does not exist."
At line:6055 char:1
+ $sync["Form"].ShowDialog() | out-null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ActionPreferenceStopException

Transcript stopped, output file is C:\Users\PandaIOT\AppData\Local\Temp\Winutil.log

**Note**: The registry key does actually exist at (see screenshot): 
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore

**To Reproduce**
1. Run CTT package
2. Select Desktop
3. click on 'Run tweaks'

**Expected behavior**
On a similar windows version of IOT Enterprise no errors occured

**Screenshots**
Screenshots added

**Additional context**
![image](https://github.com/ChrisTitusTech/winutil/assets/4119401/b20d3c55-0197-4569-b5c1-e73b03f63426)
![image](https://github.com/ChrisTitusTech/winutil/assets/4119401/530eb256-bae7-4a79-beeb-b9dd203de6bb)
![image](https://github.com/ChrisTitusTech/winutil/assets/4119401/f52f65ff-af94-423b-9fe5-2d115928da09)

**Comment by rikdol** [comment]
Logfile: 
[Winutil.log](https://github.com/ChrisTitusTech/winutil/files/12747654/Winutil.log)

**Comment by Tsukasa117** [comment]
I have the exact same issue, I did a Windows 11 Repair install which cleared up the issue and let me run the script but then I did a Window Updates(These were the ones installed)
2023-09 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5030310)
2023-05 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5026372)
2023-09 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for x64 (KB5031217)
and the issue is happening again when I went to make sure that all the tweaks were still in place.

**Comment by rikdol** [comment]
After creating the desktop shortcut and running that for the util, No errors appeared. Same issue and solution on another system. 

So this could have to do with the version of powershell that's being run. I ran x86 on both systems when the error occured.

**Comment by Tsukasa117** [comment]
> After creating the desktop shortcut and running that for the util, No errors appeared. Same issue and solution on another system.
> 
> So this could have to do with the version of powershell that's being run. I ran x86 on both systems when the error occured.

Thanks had to disable antivirus but can confirm that solution worked for me.
