### ISSUE TITLE
offline support 

### ISSUE THREAD

**Issue by Rayyyy0** [ChrisTitusTech/winutil#107]
first thank you for this amazing tool 
i have a request  i hope if u can make the tool work offline , the old windows de-bloat tool was  able to work offline i download it as zip and run it with power-shell and i can use it offline but this on is not working ,  when i  run  winutil.ps1/winutil-test.ps1  power-shell screen flashes and nothing happens , i know some stuff need internet like installing apps ...etc ,  but i really only need the tool for ( Tweaks , Config , Updates )  .

**Comment by ChrisTitusTech** [comment]
I'd just copy the relevant tweaks you want and make your own PS1 file to do this. The reason it is failing is because of winget checks at launch.
