### ISSUE TITLE
Win 10 winget not installed

### ISSUE THREAD

**Issue by thirteenwings** [ChrisTitusTech/winutil#1070]
**Describe the bug**
When I tried to "Get Installed", I got a "winget not installed" message in the PowerShell window.
OS: Windows 10 IoT Enterprise LTSC 21H2 19044.3448
Ran Winutil in an admin PS window, on an admin user account.

**Expected behavior**
If winget isn't installed, winutil should install it before proceeding instead of throwing an error.

**Comment by KALIXHOSTING** [comment]
Its a known issue just open powershell install winget using `choco install winget` to install winget via Chocolatey then try the wintil tool again and it should work perfect after that to install tools its been a on going issue but thats the easiest way to fix it on all version of windows 10 11 server 2016 - 2022 ...

**Comment by anonyao** [comment]
Choco Install Winget ,
Choco install winget-Cli 
Install-script -name winget-Install -Force

**Comment by KALIXHOSTING** [comment]
@thirteenwings Also make sure you have all windows updates installed and it will work as shown on screenshots 

![winget](https://github.com/ChrisTitusTech/winutil/assets/93708739/1f555728-be7c-49d3-9e56-1cffef35d73f)
![wingetinstall successful](https://github.com/ChrisTitusTech/winutil/assets/93708739/0da8ccec-1259-455c-9bb3-d748990ce8c0)
![working](https://github.com/ChrisTitusTech/winutil/assets/93708739/c10f12eb-964b-4bcc-9e1c-630eba90f94b)

**Comment by thirteenwings** [comment]
Thank you all. Installing winget manually wasn't a hurdle, I was just reporting the bug because not everybody is as comfortable using a command line or navigating/resolving dependencies.
