### ISSUE TITLE
Bug due to edge removal

### ISSUE THREAD

**Issue by rinalds211** [ChrisTitusTech/winutil#1075]
hello chris titus tech ive experianced error when removed microsoft edge and its deppendencies after removal i wanned to play minecraft because i was bored and i downloaded minecraft java edition and it asked me to sign in and i couldnt sign in due to microsoft edge webview2 runtime missing so i proppose to bypass this issue to modify the script when removing microsoft edge to keep the runtime it self for login and authentification purposes it self.

(Non topic) Plus i commented on your video how to secure system it would be nice if you could read my comment my username is @rinaldslibeks1592

**Comment by SwankyDankyMickey** [comment]
Hey rinalds211,

I think I had the same issue as you after using Chris Titus Tech's Windows Utility to remove Microsoft Edge amongst other things.

I was trying to install Yuzu Emulator and ran into the following error message:
"Webview2 can't install on this device because it doesn't meet the minimum hardware requirements"

What ultimately helped me resolve this issue was to specifically download the "Evergreen Standalone Installer" from the following website: https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

I had tried the "Evergreen Bootstrapper" and "Fixed Version" beforehand to no avail.

This should work for you, but if not, the following points may or may not help you further:

1. Running your Webview2 installer as Admin
2. Uninstalling and reinstalling Edge
3. Rolling back the changes made on Chris Titus Tech's Windows Utility
4. Going into the Registry Editor to this Path location: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\EdgeUpdate
    and then setting the value named "Install" to 1

Hope this helps!

**Comment by zachsa999** [comment]
Same Issue here with autodesk login using Webview 2.

How do I go about rolling back the changes?

**Comment by zachsa999** [comment]
Yeah, that doesn't seem to work for me. I tried the install as administrator, it doesn't seem to work. Not sure where to go from here.

**Comment by zachsa999** [comment]
@SwankyDankyMickey 

<img width="525" alt="image" src="https://github.com/ChrisTitusTech/winutil/assets/56491639/5f85de66-35e9-4fc1-ade5-d85dbc34cafa">
Is this how my registry should look?

**Comment by SwankyDankyMickey** [comment]
@zachsa999 

Hey man,

So you firstly asked about rolling back changes and I think it is a matter of going back into Chris Titus Tech's Windows Utility and going into the Tweaks menu and then either clicking on "Default" or re-selecting your already applied tweaks and clicking "Undo Selected Tweaks". I don't know if it actually works but it might be worth a try.

As for your registry, you seem to have quite a few more values than me. I don't know anything about the Registry Editor but to me it almost seems like you have two different versions of Edge or two different updates installed or something. Maybe that creates a conflict when trying to install Webview2. Here's my registry:
![image](https://github.com/ChrisTitusTech/winutil/assets/146584159/767a5ca1-4160-435d-bd32-5b6260bda3cb)

The last thing I can think of that could work would be to try booting your computer into safe mode (with networking) and then trying to run the Webview2 installer.

**Comment by mansoorbarri** [comment]
Chris has said that removing edge might break some things and you cannot reinstall it unless u reinstall windows i think. So keep that in mind when removing edge.

**Comment by ChrisTitusTech** [comment]
I'm redoing the edge removal script and will push it live soon to leave webview2. That will make sure this doesn't happen on future installs.
Another bug from edge removal is people using VS Community and other microsoft products use it.

**Comment by connordw-sa** [comment]
@SwankyDankyMickey 
> What ultimately helped me resolve this issue was to specifically download the "Evergreen Standalone Installer" from the following website: https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
> 
> I had tried the "Evergreen Bootstrapper" and "Fixed Version" beforehand to no avail.

Thank you so so much, I had tried the bootstrapper and fixed version before and was about to give up before I saw your comment. Had forgotten to try the standalone!

**Comment by Rippleglen** [comment]
Had this problem as well.
For me I was trying to run Forza Motorsport 8, and had the runtime sign in dialogue, what worked for me is following what SwankyDankyMickey posted. However, I was still having issues as the game didn't realise that webview2 had been installed, so I went to apps and features and reset the app from the advanced options. Started working after that. Just incase anybody else has this same problem.

**Comment by zachsa999** [comment]
Weirdly how I fixed it was running the edge removal script again, and typing webview into the prompt after the uninstall completed, and it reinstalled and fixed everything. 

I thought I had shared this here, a couple of weeks ago, but looks like it was saved as draft. Don't know if it will be usefull if Chris is fixing it, but for posterity.

**Comment by orels1** [comment]
Would be awesome if this Util also removed the relevant edge registry entries that applications use to detect if WebView2 is installed per MS docs:

https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed

Without it - the apps basically crash outright when trying to instantiate a WebView

**Comment by thejapolo** [comment]
> Had this problem as well. For me I was trying to run Forza Motorsport 8, and had the runtime sign in dialogue, what worked for me is following what SwankyDankyMickey posted. However, I was still having issues as the game didn't realise that webview2 had been installed, so I went to apps and features and reset the Xbox app from the advanced options, also deleted the duplicate registry entries for edge so that there's only one copy of each. Started working after that. Just incase anybody else has this same problem.

Just to add to this, for me I had to reset the Xbox Live app and then I got it to work 😄 
Added instructions below for anyone searching, hopefully this helps.

1. Go to Settings > Apps > Installed apps.
2. From here, find the Xbox Live app and click the three dots then Advanced options.
3. Finally, under the Reset section click on Reset button.

**Comment by kAMENkitA** [comment]
..I was struggling with the EdgeRemoval issue on my Win1o/ Win11 computers, nd I could not found solution on Net after I removed Edge using Chris WInUtil.. 
..FInally today I saw this Thread..

**Comment by lostknight42** [comment]
> I'm redoing the edge removal script and will push it live soon to leave webview2. That will make sure this doesn't happen on future installs. Another bug from edge removal is people using VS Community and other microsoft products use it.

chris, check out privacy.sex's edge removal solution. been using it for a few weeks with no issue and doesn't remove webview. and its very simple code.

**Comment by rbourassaca** [comment]
Another solution that worked for me was 

1. Running `edgeremoval.bat` in the repository as an administrator
2. Once the script is executed, _do not close the window_ and write `webview` or `edge` depending on what you want to reinstall

**Comment by henriwasd** [comment]
Not reinstall edge ;-; pls help
![image](https://github.com/ChrisTitusTech/winutil/assets/38558536/e601966d-5b1d-4ae6-8779-cd3c7e594c4f)

**Comment by bullmoos211** [comment]
As for re-installing windows to use edge, fortunately just a repair will do the trick. Obviously it's not pleasant, but you don't have to install from scratch.

**Comment by Exoticinurs** [comment]
repair didnt help for me :/

**Comment by Exoticinurs** [comment]
fixed it by trying countless versions of the installer, removing everything etc 
I dunno how but I got it working after sometime.

**Comment by JonH130** [comment]
It must be nice to have enough money to completely ignore antitrust law when forcing customers to use your crappy browser.
