### ISSUE TITLE
Security Intelligence Updates for MS Defender AV no longer auto-install

### ISSUE THREAD

**Issue by Zixim** [ChrisTitusTech/winutil#1076]
After selecting Updates/Security (Recommended) Settings, the OS is prompting me daily to install a Security Intelligence Update.  
I always let it do the update, see image.

Toggling OOB updates, and back to Recommended doesn't change the daily prompt.

**Expected behavior**
Security updates should happen automatically after selecting Recommended...

**Screenshot**
![image](https://github.com/ChrisTitusTech/winutil/assets/7814664/648e2f9f-f4aa-4694-9a87-2e011e9e414f)

**Additional context**
W11 Pro, 22H2, build 22621.2283
This is happening on 1 device, a NUC8, other devices behave as expected.

**Comment by MikaFaure** [comment]
I had the same issue.
I fixed this by editing the registry, thanks to these instructions:

https://learn.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configuring-automatic-updates-by-editing-the-registry

I changed the AUOptions value to 4, that fixed the security definitions not updating automatically.
I hope this helps someone.
