### ISSUE TITLE
The Connection the the Remoteserver could not be established

### ISSUE THREAD

**Issue by GermanYoshi** [ChrisTitusTech/winutil#1077]
![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/0954b52a-3c00-4f5e-9f4d-f152323338cc)
 English: The Connection the the Remoteserver could not be established

**Comment by ChrisTitusTech** [comment]
This is from ISPs blocking raw github files. Update your DNS servers to 1.1.1.1 and try again.

**Comment by GermanYoshi** [comment]
> This is from ISPs blocking raw github files. Update your DNS servers to 1.1.1.1 and try again.

Well i already did that....

![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/b1e17e96-dbef-4894-849f-e25a87744896)

**Comment by GermanYoshi** [comment]
Also if my ISP was blocking the DNS i also cloud not visit the Site in Browser right?
![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/8afb4c5b-ee16-492a-9ff0-f5f964db4b02)

**Comment by GermanYoshi** [comment]
@ChrisTitusTech can you reopen this issue please, thanks
