### ISSUE TITLE
Add an option to disable creating restore point

### ISSUE THREAD

**Issue by Jordan231111** [ChrisTitusTech/winutil#1079]
I want to be able to use the util in test environments/when there is no system restore point functionality.
instead of crashing the program due to unable to create restore points

**Comment by ChrisTitusTech** [comment]
I'm working on this as many VM tests I don't like using a restore point.

**Comment by yianni54** [comment]
yes im actually unable to run the tool now for some reason because restore point just hangs forever at 99%. Any idea as to why? Was working fine.

**Comment by Jordan231111** [comment]
Yeah I hope this gets more of a priority, a pretty significant issue not being able to run this tool in my work environments

**Comment by shanestrife** [comment]
@Jordan231111 If you want to run the tweaks without the restore points, you can comment out/delete [Set-WinUtilRestorePoint in wintuil.ps1](https://github.com/ChrisTitusTech/winutil/blob/main/winutil.ps1#L1739), then run the script locally in PowerShell as admin.

**Comment by Xcaliburr101** [comment]
> @Jordan231111 If you want to run the tweaks without the restore points, you can comment out/delete [Set-WinUtilRestorePoint in wintuil.ps1](https://github.com/ChrisTitusTech/winutil/blob/main/winutil.ps1#L1739), then run the script locally in PowerShell as admin.

When I comment out the function or even remove the entire function, the entire script closes immediately.
