### ISSUE TITLE
SFC problem

### ISSUE THREAD

**Issue by carlosguridi** [ChrisTitusTech/winutil#108]

**Comment by carlosguridi** [comment]
After use for first time your utility my sfc /scannow found errors and cant repair it. I followed all the DISM commands downloaded win11 image and says all is well but sfc continue showing error. the CBS file shows this
2022-08-19 05:30:49, Info                  DEPLOY [Pnp] Corrupt file: C:\Windows\System32\drivers\storvsp.sys
2022-08-19 05:30:49, Error                 DEPLOY [Pnp] Failed repairing file: C:\Windows\System32\drivers\storvsp.sys: 
Tried everything I know that is not much
Also tried to do an Inplace upgrade but my hardware isnt supported so I tried the bypass registry method but Installer says It can't check if can be installed and have to close it.
Thanks

**Comment by ChrisTitusTech** [comment]
This is unrelated to the utility. SFC is notorious for not doing much other than telling you have system corruption.
