### ISSUE TITLE
Windows 10 20H2 - Explorer Task Killed

### ISSUE THREAD

**Issue by AshlynOrSomethin** [ChrisTitusTech/winutil#1080]
**Describe the bug**
Windows Explorer task killed when running tweaks on Windows 10 Pro 20H2. 

**To Reproduce**
In the tweaks section I used the following options
1. Default Tweaks from the desktop section
2. Add Ultimate Performance
3. Change DNS to Google

**Expected behavior**
Run all tweaks without killing the Windows shell completely

**Screenshots**
N/A

**Additional context**
It was an easy enough fix to just run explorer from powershell but some users may not know to do so.

**Comment by anonyao** [comment]
@AshlynOrSomethin //Yeah it "Restart explorer.exe when KIll EDGE " LOL ON YOU
