### ISSUE TITLE
iwr : Unable to connect to the remote server

### ISSUE THREAD

**Issue by ItzGreekyPlayz** [ChrisTitusTech/winutil#1083]
So, it shows that it is a DNS server issue, but when I add a specific DNS server (my router), the internet on my laptop stops working. I tried to change IPv4 and IPv6, but it was the same issue.

![Screenshot 2023-10-04 150613](https://github.com/ChrisTitusTech/winutil/assets/146936722/7f5bdcd5-aed5-46bc-b15c-ebb2d85000bf)

Pls help so I can continue using CTT.
Thanks!

**Comment by ChrisTitusTech** [comment]
Instead of using the redirect try to launch directly from the raw file:
```
irm https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1 | iex
```
If you can't render the online page it can't launch the script. This is always an internet issue. Some antivirus or dns servers will block the redirect or will not load github raw pages.

**Comment by nikkdrive18** [comment]
I found whats causing this problem. Its IPv6.
Disable IPv6 to fix it before running the script.
![Untick-IPv6](https://github.com/ChrisTitusTech/winutil/assets/131444909/153ae235-4780-4f60-90fd-6f522f4e4895)
