### ISSUE TITLE
Still fails if winget is not installed.  screen just flashes and says "Done"

### ISSUE THREAD

**Issue by mrg9999** [ChrisTitusTech/winutil#109]
If winget is not installed it says it has performed an action without checking.
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19043  0

Installed winget from github using 
iwr -useb https://christitus.com/win | iex

output
`If you need to reference this display again, run Get-FormVariables
Found the following interactable elements from our form

Name                           Value
----                           -----
WPFdesktop                     System.Windows.Controls.Button: Desktop
WPFEssTweaksAH                 System.Windows.Controls.CheckBox Content:Disable Activity History IsChecked:False
WPFEssTweaksDeBloat            System.Windows.Controls.CheckBox Content:Remove ALL MS Store Apps IsChecked:False
WPFEssTweaksDVR                System.Windows.Controls.CheckBox Content:Disable GameDVR IsChecked:False
WPFEssTweaksHiber              System.Windows.Controls.CheckBox Content:Disable Hibernation IsChecked:False
WPFEssTweaksHome               System.Windows.Controls.CheckBox Content:Disable Homegroup IsChecked:False
WPFEssTweaksLoc                System.Windows.Controls.CheckBox Content:Disable Location Tracking IsChecked:False
WPFEssTweaksOO                 System.Windows.Controls.CheckBox Content:Run O and O Shutup IsChecked:False
WPFEssTweaksRP                 System.Windows.Controls.CheckBox Content:Create Restore Point IsChecked:False
WPFEssTweaksServices           System.Windows.Controls.CheckBox Content:Set Services to Manual IsChecked:False
WPFEssTweaksStorage            System.Windows.Controls.CheckBox Content:Disable Storage Sense IsChecked:False
WPFEssTweaksTele               System.Windows.Controls.CheckBox Content:Disable Telemetry IsChecked:False
WPFEssTweaksWifi               System.Windows.Controls.CheckBox Content:Disable Wifi-Sense IsChecked:False
WPFFeatureInstall              System.Windows.Controls.Button: Install Features
WPFFeaturenfs                  System.Windows.Controls.CheckBox Content:NFS - Network File System IsChecked:False
WPFFeaturesdotnet              System.Windows.Controls.CheckBox Content:All .Net Framework (2,3,4) IsChecked:False
WPFFeatureshyperv              System.Windows.Controls.CheckBox Content:HyperV Virtualization IsChecked:False
WPFFeatureslegacymedia         System.Windows.Controls.CheckBox Content:Legacy Media (WMP, DirectPlay) IsChecked:False
WPFFeaturewsl                  System.Windows.Controls.CheckBox Content:Windows Subsystem for Linux IsChecked:False
WPFFixesUpdate                 System.Windows.Controls.Button: Reset Windows Update
WPFIcon                        System.Windows.Controls.Image
WPFinstall                     System.Windows.Controls.Button: Start Install
WPFInstalladobe                System.Windows.Controls.CheckBox Content:Adobe Reader DC IsChecked:False
WPFInstalladvancedip           System.Windows.Controls.CheckBox Content:Advanced IP Scanner IsChecked:False
WPFInstallanydesk              System.Windows.Controls.CheckBox Content:AnyDesk IsChecked:False
WPFInstallatom                 System.Windows.Controls.CheckBox Content:Atom IsChecked:False
WPFInstallaudacity             System.Windows.Controls.CheckBox Content:Audacity IsChecked:False
WPFInstallautohotkey           System.Windows.Controls.CheckBox Content:AutoHotkey IsChecked:False
WPFInstallbitwarden            System.Windows.Controls.CheckBox Content:Bitwarden IsChecked:False
WPFInstallblender              System.Windows.Controls.CheckBox Content:Blender (3D Graphics) IsChecked:False
WPFInstallbrave                System.Windows.Controls.CheckBox Content:Brave IsChecked:False
WPFInstallchrome               System.Windows.Controls.CheckBox Content:Google Chrome IsChecked:False
WPFInstallchromium             System.Windows.Controls.CheckBox Content:Un-Googled Chromium IsChecked:False
WPFInstallcpuz                 System.Windows.Controls.CheckBox Content:CPU-Z IsChecked:False
WPFInstalldiscord              System.Windows.Controls.CheckBox Content:Discord IsChecked:False
WPFInstalleartrumpet           System.Windows.Controls.CheckBox Content:Eartrumpet (Audio) IsChecked:False
WPFInstallepicgames            System.Windows.Controls.CheckBox Content:Epic Games Launcher IsChecked:False
WPFInstallesearch              System.Windows.Controls.CheckBox Content:Everything Search IsChecked:False
WPFInstalletcher               System.Windows.Controls.CheckBox Content:Etcher USB Creator IsChecked:False
WPFInstallfirefox              System.Windows.Controls.CheckBox Content:Firefox IsChecked:False
WPFInstallflameshot            System.Windows.Controls.CheckBox Content:Flameshot (Screenshots) IsChecked:False
WPFInstallfoobar               System.Windows.Controls.CheckBox Content:Foobar2000 (Music Player) IsChecked:False
WPFInstallgimp                 System.Windows.Controls.CheckBox Content:GIMP (Image Editor) IsChecked:False
WPFInstallgithubdesktop        System.Windows.Controls.CheckBox Content:GitHub Desktop IsChecked:False
WPFInstallgog                  System.Windows.Controls.CheckBox Content:GOG Galaxy IsChecked:False
WPFInstallgpuz                 System.Windows.Controls.CheckBox Content:GPU-Z IsChecked:False
WPFInstallgreenshot            System.Windows.Controls.CheckBox Content:Greenshot (Screenshots) IsChecked:False
WPFInstallhandbrake            System.Windows.Controls.CheckBox Content:HandBrake IsChecked:False
WPFInstallhexchat              System.Windows.Controls.CheckBox Content:Hexchat IsChecked:False
WPFInstallhwinfo               System.Windows.Controls.CheckBox Content:HWInfo IsChecked:False
WPFInstallimageglass           System.Windows.Controls.CheckBox Content:ImageGlass (Image Viewer) IsChecked:False
WPFInstallinkscape             System.Windows.Controls.CheckBox Content:Inkscape IsChecked:False
WPFInstalljava16               System.Windows.Controls.CheckBox Content:OpenJDK Java 16 IsChecked:False
WPFInstalljava18               System.Windows.Controls.CheckBox Content:Oracle Java 18 IsChecked:False
WPFInstalljava8                System.Windows.Controls.CheckBox Content:OpenJDK Java 8 IsChecked:False
WPFInstalljetbrains            System.Windows.Controls.CheckBox Content:Jetbrains Toolbox IsChecked:False
WPFInstallkeepass              System.Windows.Controls.CheckBox Content:KeePassXC IsChecked:False
WPFInstalllibreoffice          System.Windows.Controls.CheckBox Content:LibreOffice IsChecked:False
WPFInstalllibrewolf            System.Windows.Controls.CheckBox Content:LibreWolf IsChecked:False
WPFInstallmalwarebytes         System.Windows.Controls.CheckBox Content:MalwareBytes IsChecked:False
WPFInstallmatrix               System.Windows.Controls.CheckBox Content:Matrix IsChecked:False
WPFInstallmpc                  System.Windows.Controls.CheckBox Content:Media Player Classic (Video Player) IsChecke...
WPFInstallmremoteng            System.Windows.Controls.CheckBox Content:mRemoteNG IsChecked:False
WPFInstallnodejs               System.Windows.Controls.CheckBox Content:NodeJS IsChecked:False
WPFInstallnodejslts            System.Windows.Controls.CheckBox Content:NodeJS LTS IsChecked:False
WPFInstallnotepadplus          System.Windows.Controls.CheckBox Content:Notepad++ IsChecked:False
WPFInstallnvclean              System.Windows.Controls.CheckBox Content:NVCleanstall IsChecked:False
WPFInstallobs                  System.Windows.Controls.CheckBox Content:OBS Studio IsChecked:False
WPFInstallobsidian             System.Windows.Controls.CheckBox Content:Obsidian IsChecked:False
WPFInstallpowertoys            System.Windows.Controls.CheckBox Content:Microsoft Powertoys IsChecked:False
WPFInstallputty                System.Windows.Controls.CheckBox Content:Putty IsChecked:False
WPFInstallpython3              System.Windows.Controls.CheckBox Content:Python3 IsChecked:False
WPFInstallrevo                 System.Windows.Controls.CheckBox Content:RevoUninstaller IsChecked:False
WPFInstallrufus                System.Windows.Controls.CheckBox Content:Rufus Imager IsChecked:False
WPFInstallscp                  System.Windows.Controls.CheckBox Content:WinSCP IsChecked:False
WPFInstallsevenzip             System.Windows.Controls.CheckBox Content:7-Zip IsChecked:False
WPFInstallsharex               System.Windows.Controls.CheckBox Content:ShareX (Screenshots) IsChecked:False
WPFInstallsignal               System.Windows.Controls.CheckBox Content:Signal IsChecked:False
WPFInstallskype                System.Windows.Controls.CheckBox Content:Skype IsChecked:False
WPFInstallslack                System.Windows.Controls.CheckBox Content:Slack IsChecked:False
WPFInstallspotify              System.Windows.Controls.CheckBox Content:Spotify IsChecked:False
WPFInstallsteam                System.Windows.Controls.CheckBox Content:Steam IsChecked:False
WPFInstallsublime              System.Windows.Controls.CheckBox Content:Sublime IsChecked:False
WPFInstallsumatra              System.Windows.Controls.CheckBox Content:Sumatra PDF IsChecked:False
WPFInstallteams                System.Windows.Controls.CheckBox Content:Microsoft Teams IsChecked:False
WPFInstallteamviewer           System.Windows.Controls.CheckBox Content:TeamViewer IsChecked:False
WPFInstallterminal             System.Windows.Controls.CheckBox Content:Windows Terminal IsChecked:False
WPFInstalltreesize             System.Windows.Controls.CheckBox Content:TreeSize Free IsChecked:False
WPFInstallttaskbar             System.Windows.Controls.CheckBox Content:Translucent Taskbar IsChecked:False
WPFInstallUpgrade              System.Windows.Controls.Button: Upgrade Installs
WPFInstallvisualstudio         System.Windows.Controls.CheckBox Content:Visual Studio 2022 Community IsChecked:False
WPFInstallvivaldi              System.Windows.Controls.CheckBox Content:Vivaldi IsChecked:False
WPFInstallvlc                  System.Windows.Controls.CheckBox Content:VLC (Video Player) IsChecked:False
WPFInstallvoicemeeter          System.Windows.Controls.CheckBox Content:Voicemeeter (Audio) IsChecked:False
WPFInstallvscode               System.Windows.Controls.CheckBox Content:VS Code IsChecked:False
WPFInstallvscodium             System.Windows.Controls.CheckBox Content:VS Codium IsChecked:False
WPFInstallwindirstat           System.Windows.Controls.CheckBox Content:WinDirStat IsChecked:False
WPFInstallwireshark            System.Windows.Controls.CheckBox Content:WireShark IsChecked:False
WPFInstallzoom                 System.Windows.Controls.CheckBox Content:Zoom Video Conference IsChecked:False
WPFlaptop                      System.Windows.Controls.Button: Laptop
WPFMainGrid                    System.Windows.Controls.Grid
WPFminimal                     System.Windows.Controls.Button: Minimal
WPFMiscTweaksDisplay           System.Windows.Controls.CheckBox Content:Set Display for Performance IsChecked:False
WPFMiscTweaksExt               System.Windows.Controls.CheckBox Content:Show File Extensions IsChecked:False
WPFMiscTweaksLapNum            System.Windows.Controls.CheckBox Content:Disable Numlock on Startup IsChecked:False
WPFMiscTweaksLapPower          System.Windows.Controls.CheckBox Content:Enable Power Throttling IsChecked:False
WPFMiscTweaksNum               System.Windows.Controls.CheckBox Content:Enable NumLock on Startup IsChecked:False
WPFMiscTweaksPower             System.Windows.Controls.CheckBox Content:Disable Power Throttling IsChecked:False
WPFMiscTweaksUTC               System.Windows.Controls.CheckBox Content:Set Time to UTC (Dual Boot) IsChecked:False
WPFPanelcontrol                System.Windows.Controls.Button: Control Panel
WPFPanelnetwork                System.Windows.Controls.Button: Network Connections
WPFPanelpower                  System.Windows.Controls.Button: Power Panel
WPFPanelsound                  System.Windows.Controls.Button: Sound Settings
WPFPanelsystem                 System.Windows.Controls.Button: System Properties
WPFPaneluser                   System.Windows.Controls.Button: User Accounts
WPFTab1                        System.Windows.Controls.TabItem Header:Install Content:
WPFTab1BT                      System.Windows.Controls.Button: Install
WPFTab2                        System.Windows.Controls.TabItem Header:Tweaks Content:
WPFTab2BT                      System.Windows.Controls.Button: Tweaks
WPFTab3                        System.Windows.Controls.TabItem Header:Config Content:
WPFTab3BT                      System.Windows.Controls.Button: Config
WPFTab4                        System.Windows.Controls.TabItem Header:Updates Content:
WPFTab4BT                      System.Windows.Controls.Button: Updates
WPFTabNav                      System.Windows.Controls.TabControl Items.Count:4
WPFtweaksbutton                System.Windows.Controls.Button: Run Tweaks
WPFundoall                     System.Windows.Controls.Button: Undo All Tweaks
WPFUpdatesdefault              System.Windows.Controls.Button: Default (Out of Box) Settings
WPFUpdatesdisable              System.Windows.Controls.Button: Disable ALL Updates (NOT RECOMMENDED!)
WPFUpdatessecurity             System.Windows.Controls.Button: Security (Recommended) Settings
`
e.g.
PS C:\WINDOWS\system32> Get-WMIObject -Class Win32_Product  | grep -i chrome
Name              : Google Chrome
Caption           : Google Chrome
PS C:\WINDOWS\system32> Get-WMIObject -Class Win32_Product  | grep -i Brave
PS C:\WINDOWS\system32>

**Comment by ChrisTitusTech** [comment]
Should be fixed in new PR #94
