### ISSUE TITLE
New Win11 22621 Winget Installation Issues

### ISSUE THREAD

**Issue by ooFVenomous** [ChrisTitusTech/winutil#1090]
**Describe the bug**
When trying to use a the toolbox on a brand new laptop (Dell Inspiron 15) I can only use tweaks, configs, and updates. When trying to use the toolbox to install programs, it attempts to install them as proceeds to save "installs finished" but the programs do not install. When trying to use the installer, it gives the error message "Install process is currently running."

**To Reproduce**
1. Go to 'Install'
2. Click on 'Brave' (Using Brave as an example as it does not matter what program.)
3. Click 'Install Selection' 
4. See error: Programs do not install/appear anywhere even though the toolbox says they do

**Expected behavior**
Selected programs (Brave and Jellyfin Server)  are to be installed and appear. 

**Additional context**
Brand new Dell Inspiron 15 Laptop that came pre-installed with McAfee. I setup a local account and used RevoUninstaller to uninstall McAfee and it's bloatware. I also ran the Tron Script to see if that would fix anything. 
Windows 11 version: 22H2, 22621.2283

**Comment by spkyghzt** [comment]
+1 Also encountering this behavior on fresh install of Windows 11 on my Desktop. 
**Version : 22H2 22621.2361**

**Comment by Sam217** [comment]
This seems as a winget version issue - I updated the winget version with the one from MS Store and after that the checked programs install fine.

**Comment by spkyghzt** [comment]
Hell yeah that did the trick and now works :) thanks

**Comment by Sam217** [comment]
> Hell yeah that did the trick and now works :) thanks

Glad that it helped, another way could be to use directly the script that should install winget

`"irm https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winget.ps1 | iex"`

I suppose that the fix might be just adding a check for a winget version in `Test-WinUtilPackageManager` and not just that it exists on the system.
For some reason the latest win11 install got me winget 1.2.xxx version pre-installed (the version from "winget -v") but the latest version today is v1.6.2771.

**Comment by ooFVenomous** [comment]
Can confirm as the OP, WinGet needs to be updated to resolve this issue.
