### ISSUE TITLE
is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Strahilchu** [ChrisTitusTech/winutil#1096]
Microsoft Windows [Version 10.0.19045.3570]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>iwr -useb https://christitus.com/win | iex
'iwr' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>irm https://christitus.com/win | iex
'irm' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>iwr -useb https://christitus.com/win | iex
'iwr' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>

Help?

**Comment by ChrisTitusTech** [comment]
you are using command prompt not powershell as admin.
