### ISSUE TITLE
"Set Services to Manual" broke Windows Update Functionality

### ISSUE THREAD

**Issue by fr0stedfl4ke** [ChrisTitusTech/winutil#1098]
**Describe the bug**
I'm not quite sure why specific services are set to "manual" while others are set to "automatic". I'm assuming that there are specific services that can be turned off and are "unnecessary" in order to help improve ram and cpu utilization. 

In play, it broke Windows update on my end. I've never had an issue with Windows update before and the system had to roll back changes. The error code I receive was 0x800f0922, which, apparently is an issue with .NET functionality. 

Do these tweaks mess with .NET in any way? In general, I have a feeling that some key critical services are inadvertently turned off when they shouldn't be.

**To Reproduce**
Check the "Set Services to Manual" box and run. 

**Expected behavior**
Full Windows functionality, or at least, critical services/components.

**Additional context**
I tried checking for corruption and noticed that, while I didn't receive any issues via SFC, I did via DISM. In fact, DISM wasn't able to fix any of the issues with the image, for some odd reason. I believe it required me to download the iso and pass along DISM to repair key components off another iso.

Nonetheless,

I reverted "Set Services to Manual", rebooted, ran sfc and dism (ran just fine) and installed the update - which worked.

**Comment by TheyCallMeTojo** [comment]
That particular error is telling you that Windows firewall or Windows Defender has been removed.

**Comment by fr0stedfl4ke** [comment]
Has been removed? Both the firewall and defender were up and running when I encountered this error. In fact, after some research, a few articles mention disabling firewall and attempting to update. I also checked my system reserved partition and it had enough space to allow this update to proceed.
