### ISSUE TITLE
Tweaks: Ultimate Performance Profile - Add Use Profile

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1099]
Currently you have only 2 options regarding Performance Plans:
- [x] Add Ultimate Performance Profile
- [x] Remove Ultimate Performance Profile

My suggestion is to add a third option:
- [ ] Use Ultimate Performance Profile

Or a better solution would be to apply the Ultimate Performance Profile after adding it.

Edit: Could be also nice if that Ultimate Performance Profile could include `powercfg /change /monitor-timeout-ac 0` which won't turn off the screen after 15minutes

**Comment by ChrisTitusTech** [comment]
Fixed in latest commit db1acb0
