### ISSUE TITLE
Disable Automatic sample submission for Microsoft Defender

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1103]
I'm not sure why this tool doesn't disable this, I disabled it manually
![273672843-65da73c1-25e5-4deb-b4e9-000abf1232df](https://github.com/ChrisTitusTech/winutil/assets/13978119/c4bc9088-2593-43a2-a3a0-670253136cc6)
Users don't want to send files to Microsoft
``` 
Microsoft Defender > Virus & threat protection > Manage settings > Automatic sample submission
```
Powershell command: 
```
Set-MpPreference -SubmitSamplesConsent 2
```

**Comment by ChrisTitusTech** [comment]
Perfect, thank you here is the commit, will be push live soon. 
0dcc94f

**Comment by CheckYourFax** [comment]
Only annoying bit of this is that the warning comes back every time you reboot. Very annoying.
