### ISSUE TITLE
Remove Cortana

### ISSUE THREAD

**Issue by 0xC4aE1e5** [ChrisTitusTech/winutil#111]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**
Cortana would be gone after `Remove ALL UWP apps`

**Describe alternatives you've considered**

None

**Additional context**

This PowerShell command still works:

```powershell
Get-AppxPackage -allusers Microsoft.549981C3F5F10 | Remove-AppxPackage
```

**Comment by ChrisTitusTech** [comment]
Added in #240 - Closing Issue
