### ISSUE TITLE
Bing Search in Start Menu - Shows as On - Even if it's already disabled by prior scripts

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1111]
**Describe the bug**
"Bing Search in Start Menu" buttons "On" and "Off" don't reflect actual settings.

**To Reproduce**
1. Clean install of Windows 10
2. Run a different script that disables "Bing Search in Start Menu"
3. Run winutil and see "Bing Search in Start Menu" is "On"

**Expected behavior**
"Bing Search in Start Menu" will show up as "Off".

**Screenshots**
I don't think it's necessary for this case.

**Additional context**
I think this specific option should be checking if it's already disabled and reflect the actual settings.
A different solution could be the instead of showing "On" or "Off" it could be a separate option for each, something like
[] Disable Bing Search in Start Menu
[] Enable Bing Search in Start Menu
And you should mark V on the settings you want, 
if it is going to be like this then the disabled option should be added to "Desktop" preset.

**Comment by bondeabhijeet** [comment]
To successfully disable Bing search on Windows 10/11, use this link: [Windows-BingSearch-Disable](https://github.com/bondeabhijeet/Windows-BingSearch-Disable).
