### ISSUE TITLE
Hosts file

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1112]
To completely shut up windows 10, add hosts file that will block the following URLs:
```
www.bing.com
login.live.com
cxcs.microsoft.net
ecn.dev.virtualearth.net
client.wns.windows.com
```
Fresh installed windows 10 and only those URLs I couldn't stop, the only way I can is using hosts file

**Comment by anonyao** [comment]
Its way more servers to block if u that paranoid ;p

**Comment by anonyao** [comment]
Trust me its many more versions of windows / ms servers who can be used if some is blocked. I had a host file with around 3-400 servers who was connected as universal servers if orginal is blocked. But i dont know fo sure if u need to block all them ;p

**Comment by ChrisTitusTech** [comment]
I won't make modifications to the hosts, and blocking `login.live.com` will have big ramifications for O365 users and outlook.com users.
