### ISSUE TITLE
[Bug] Chocolatey automatically installs without user input.

### ISSUE THREAD

**Issue by ORIOLESFan02** [ChrisTitusTech/winutil#1118]
**Describe the bug**
Chocolatey immediately installs without specifying it to do so.

**To Reproduce**
1. Copy the WinUtil Link from the website
2. Paste it into powershell as admin
3. Move the powershell window around (that's what I did at the stage that chocolatey was being installed)
4. See if there was no option to install or not install chocolatey

**Expected behavior**
Asks if you want to download chocolatey or not

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/48143202/32e01ccc-24cc-47e1-a2a3-30819ca74729)

**Additional context**
This has never happened before on any other computer I've run the util on.

**Comment by ORIOLESFan02** [comment]
> Yes, I encounter this aswell, I don't want to install Chocolatey, I only use `Tweaks` section and I now `winutil` adds "bloat" to my machine which it's should get rid off, lol.

They also don't make Chocolatey as easy to remove either.

**Comment by pranshu-s18** [comment]
+1

**Comment by fabcard** [comment]
Hello. Please don't make it to install Chocolatey automatically. Make it like before, asking us if we want to install it or not.
Thanks in advance.

**Comment by Welding-Torch** [comment]
+1 I came to this repo to open a new issue just about this.

**Comment by honam18** [comment]
+1

**Comment by riomccloud** [comment]
+1

**Comment by ORIOLESFan02** [comment]
Now I have no idea how to code, but from what I'm seeing, this shows what was removed and how it was replaced. My question is why?
https://github.com/ChrisTitusTech/winutil/commit/d0bde83333730a4536497451af747daba11e5039?diff=unified#diff-314d3762959a8ba1bd840e2d59720276d6da92fe969bd23b195430db0aa5e66d

**Comment by couleurm** [comment]
> Now I have no idea how to code, but from what I'm seeing, this shows what was removed and how it was replaced. My question is why? [d0bde83?diff=unified#diff-314d3762959a8ba1bd840e2d59720276d6da92fe969bd23b195430db0aa5e66d](https://github.com/ChrisTitusTech/winutil/commit/d0bde83333730a4536497451af747daba11e5039?diff=unified#diff-314d3762959a8ba1bd840e2d59720276d6da92fe969bd23b195430db0aa5e66d)


From my understanding of the code, it should be as easy as adding the following line at the beginning of [this function](https://github.com/ChrisTitusTech/winutil/blob/main/functions/private/Install-WinUtilChoco.ps1)

```PowerShell
if ($env:WINUTIL_NOCHOCO){return}
```

You'd just need to declare that variable before running
```PowerShell
$env:WINUTIL_NOCHOCO = 1
iex(irm christitus.com/win);
```

I could make a fork of this repo if this persists

**Comment by Welding-Torch** [comment]
Honestly it would be really great if you made a fork of this repo for this.

**Comment by couleurm** [comment]
Made a [fork](https://github.com/couleurm/winutil-nochoco)

Please don't just take my word for it and look at [what I did](https://github.com/couleurm/winutil-nochoco/commits/couleurm-patch-1)

```
$env:WINUTIL_NOCHOCO=1
iex (irm https://github.com/couleurm/winutil-nochoco/raw/couleurm-patch-1/winutil.ps1)

```

![image](https://github.com/ChrisTitusTech/winutil/assets/82747632/fde204fd-f8b0-433a-a840-b7ed1f8011e2)

**Comment by Welding-Torch** [comment]
Awesome!

@ChrisTitusTech Will you merge @couleurm's fork? Since a lot of people are asking for this.

**Comment by ORIOLESFan02** [comment]
> Made a [fork](https://github.com/couleurm/winutil-nochoco)
> 
> Please don't just take my word for it and look at [what I did](https://github.com/couleurm/winutil-nochoco/commits/couleurm-patch-1)
> 
> ```
> $env:WINUTIL_NOCHOCO=1
> iex (irm https://github.com/couleurm/winutil-nochoco/raw/couleurm-patch-1/winutil.ps1)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/82747632/285261581-fde204fd-f8b0-433a-a840-b7ed1f8011e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODM5MjAsIm5iZiI6MTcwMDg4MzYyMCwicGF0aCI6Ii84Mjc0NzYzMi8yODUyNjE1ODEtZmRlMjA0ZmQtZjhiMC00MzNhLWE4NDAtYjdlZDFmODAxMWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAzNDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NTBjNjdiODg3NjI2ZDcwM2M1Mzg0YmYwZWNmYTM2NDE3ZjI0ODdlYmMxNTBjYThmODgxMjYxNjA2ZTFiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rklJ82yy7spEZFjlRBXRP_vFR9gSO8UVF3pbaNt2HXM)

amazing

**Comment by dreamsyntax** [comment]
Commenting to say I also would prefer this to return. If there is a reason its needed (specific tweaks requiring it?) then perhaps an uninstall option

**Comment by gandbg** [comment]
To avoid the forced installation of Chocolatey, launch WinUtil with the following command:
```powershell
(irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex
```

It's the same as the original, but it alters the downloaded script on-the-fly so that the function that checks for (and installs) Chocolatey always pretends that it's already installed.

Keep in mind that the Desktop shortcut created by a WinUtil started with this command will keep trying to install Chocolatey on your machine.

**Comment by couleurm** [comment]
very clever! consider using this approach instead of my branch

**Comment by ORIOLESFan02** [comment]
> To avoid the forced installation of Chocolatey, launch WinUtil with the following command:
> 
> ```powershell
> (irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex
> ```
> 
> It's the same as the original, but it alters the downloaded script on-the-fly so that the function that checks for (and installs) Chocolatey always pretends that it's already installed.
> 
> Keep in mind that the Desktop shortcut created by a WinUtil started with this command will keep trying to install Chocolatey on your machine.

Wow! I really appreciate this. I'm not PS savvy, but do you think there'd be a way to create said command as a desktop shortcut? I mean I'd believe it's pretty easy, but I'm not sure.

**Comment by ORIOLESFan02** [comment]
> > To avoid the forced installation of Chocolatey, launch WinUtil with the following command:
> > ```powershell
> > (irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's the same as the original, but it alters the downloaded script on-the-fly so that the function that checks for (and installs) Chocolatey always pretends that it's already installed.
> > Keep in mind that the Desktop shortcut created by a WinUtil started with this command will keep trying to install Chocolatey on your machine.
> 
> Wow! I really appreciate this. I'm not PS savvy, but do you think there'd be a way to create said command as a desktop shortcut? I mean I'd believe it's pretty easy, but I'm not sure.

I think  just figured it out.

**Comment by couleurm** [comment]
> Edit: I didn't. It's too long :(

 just put command in a batch file

**Comment by earendildev** [comment]
> To avoid the forced installation of Chocolatey, launch WinUtil with the following command:
> 
> ```powershell
> (irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex
> ```
> 
> It's the same as the original, but it alters the downloaded script on-the-fly so that the function that checks for (and installs) Chocolatey always pretends that it's already installed.
> 
> Keep in mind that the Desktop shortcut created by a WinUtil started with this command will keep trying to install Chocolatey on your machine.

Should be included in the ReadMe 👍🏼 🌟

**Comment by couleurm** [comment]
credit should be given to @granbg

**Comment by gandbg** [comment]
I'm not sure that it will ever be included. @ChrisTitusTech [explicitly removed this feature](https://github.com/ChrisTitusTech/winutil/pull/1117/commits/38ace30f92b45cac60ef2c2216d5e26bc537425f#diff-314d3762959a8ba1bd840e2d59720276d6da92fe969bd23b195430db0aa5e66d) so he has no interest in re-adding it

I pinged him so that hopefully he reads this issue and reverts this decision

**Comment by dreamsyntax** [comment]
> I'm not sure that my workaround will ever be included in the ReadMe. @ChrisTitusTech [explicitly removed this feature](https://github.com/ChrisTitusTech/winutil/pull/1117/commits/38ace30f92b45cac60ef2c2216d5e26bc537425f#diff-314d3762959a8ba1bd840e2d59720276d6da92fe969bd23b195430db0aa5e66d) so he has no interest in re-adding it
> 
> I pinged him so that hopefully he reads this issue and reverts this decision

It's likely because they plan to drop chocolatey completely in the future.

**Comment by ORIOLESFan02** [comment]
> Closed due to inactivity

Boooooooo

**Comment by Welding-Torch** [comment]
>Closed due to inactivity

Rude bot. This issue doesn't need to be closed, it needs a reply from @ChrisTitusTech.

**Comment by ORIOLESFan02** [comment]
I'm still mad this got closed.

@ChrisTitusTech, I'm still waiting for that reply btw.

**Comment by dreamsyntax** [comment]
> I'm still mad this got closed.
> 
> @ChrisTitusTech, I'm still waiting for that reply btw.

If you want the real answer, he's approaching his 60s and doesn't want to deal with supporting people who said 'N' during chocolatey and then ask why nothing installs.

**Comment by thesobercoder** [comment]
I think we should re-open this.

**Comment by thesobercoder** [comment]
@ChrisTitusTech Please re-open this issue as a lot of community members are asking for this.
