### ISSUE TITLE
Location not being restored despite undoing Location tweaks, and it doing the following tweaks.

### ISSUE THREAD

**Issue by BULLETVOMIT** [ChrisTitusTech/winutil#1124]
I have checked the registry, and according to a previous post which showed what the registry values should be for some of the stuff, which were: 
Set HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location\Value to Allow
Set HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Sensor\Overrides{BFA794E4-F964-4FDB-90F6-51056BFE4B44}\SensorPermissionState to 1
Set HKLM:\SYSTEM\CurrentControlSet\Services\lfsvc\Service\Configuration\Status to 1
Set HKLM:\SYSTEM\Maps\AutoUpdateEnabled to 1

Now, I checked the registry after using the undo tweaks option, and all the values matched the one above, but location still remains off because "Some of these settings are hidden or managed by your organization"

Idk how to undo this now, bit of help needed.

**Comment by keiz-7** [comment]
Having this exact same issue as well

**Comment by 0hip** [comment]
> Now, I checked the registry after using the undo tweaks option, and all the values matched the one above, but location still remains off because "Some of these settings are hidden or managed by your organization"
> 
> Idk how to undo this now, bit of help needed.

It may be that you have run "tweaks" with "Run OO Shutup" checkbox ticked.

Then you should toggling them to red, this time from "O&O Shutup" itself.

![image](https://github.com/ChrisTitusTech/winutil/assets/90657954/57355023-ec76-4bc1-841d-02ffd83aa80e)

**Comment by keiz-7** [comment]
That did it for me. I downloaded  O&O Shutup separately (didn't have downloaded before), and toggling fixed.
