### ISSUE TITLE
[Question] Ventoy only has a Chocolatey package

### ISSUE THREAD

**Issue by doggogit** [ChrisTitusTech/winutil#1128]
As I've read, the Windows Utility script currently doesn't have a fallback to `Chocolatey` if there's no `winget` package.

I'm confused as to why #1066 got merged when Ventoy doesn't have a `winget` package.

Is it because of the .NET Core Runtime packages?

**Comment by jstack01** [comment]
I recall from a past stream that Chris wants to add functionality to have the install rollover to Chocolatey if winget fails to install the package. I am unsure when this will be put in place. As of today (12/28/23) I still **could not** find a package for ventoy. Hopefully this will be addressed soon, so any applications that are not available on winget, but are on Chocolatey, can be installed using winutil.

**Comment by doggogit** [comment]
> I recall from a past stream that Chris wants to add functionality to have the install rollover to Chocolatey if winget fails to install the package. I am unsure when this will be put in place. As of today (12/28/23) I still **could not** find a package for ventoy. Hopefully this will be addressed soon, so any applications that are not available on winget, but are on Chocolatey, can be installed using winutil.

Yeah, I've read through previous issues here and I got the answer to my question.

Thanks for the comment, will be closin' this now. :)
