### ISSUE TITLE
Applications not getting installed

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [ChrisTitusTech/winutil#1133]
**Describe the bug**
Installing application are not actually installed.

**To Reproduce**
1. Select some applications to install
2. Click on "Install Selection"
3. Wait for the applications to be "installed"
4. No error is shown, but application are not installed, even though it claims they are.

**Expected behavior**
Actually having the applications.

- They are not in program files.
- They are not showing up when searching for them.
- There are no shortcuts on my desktop., 

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/7256303/efda429a-b244-48cb-92e7-f5b17af89b8b)
![image](https://github.com/ChrisTitusTech/winutil/assets/7256303/579953f2-9d08-4c89-80f1-05c07606365c)
![image](https://github.com/ChrisTitusTech/winutil/assets/7256303/fca7202b-181b-4edd-a110-1d982b0cba71)

**Additional context**
Am I doing something wrong?

**Comment by xuninc** [comment]
exact same thing happening to me.

**Comment by xuninc** [comment]
oh wow okay so to fix it all you do is open the microsoft store. there's an app on that list called App Installer.

update that app and then restart winutil and it'll work.

**Comment by krstep** [comment]
Thanks just tried the tool and i was scratching my head why it would not work.

**Comment by ershisan99** [comment]
Might be useful to document @xuninc's solution somewhere, had the same issue on a freshly installed system
