### ISSUE TITLE
Firefox runs really slow after using WinUtil

### ISSUE THREAD

**Issue by VanitasFR** [ChrisTitusTech/winutil#1138]
**Describe the bug**
After running the debloater with desktop preset firefox loads web pages really slow, unlike chromium based browsers.

**To Reproduce**
1. Run the debloater with desktop preset settings and cloudflare DNS
2. Restart PC
3. Launch firefox and try to load youtube (or any other website)
4. takes 10-20 seconds to load the page (where as before it was instant)

**Expected behavior**
Load the pages instantly like before.

**Comment by KonTy** [comment]
Change your DNS back to default.

**Comment by VanitasFR** [comment]
I was already on cloudflare DNS before using WinUtil and it was working
fine.

**Comment by sebastien5694** [comment]
Are you on Windows 10 or 11? I'm running W10 with firefox 119 my ISP DNS and everything works fine with almost all tweaks checked. Maybe try to use your ISP DNS and start a new firefox profile with no addons.
