### ISSUE TITLE
Windows Toolbox not Working in Windows 10 1607 ltsb

### ISSUE THREAD

**Issue by 064-Gamer** [ChrisTitusTech/winutil#114]
![image](https://user-images.githubusercontent.com/69930744/188021566-37e4f4b7-4042-43dc-ae81-e3fb054477e8.png)
the command just dosen't work
![image](https://user-images.githubusercontent.com/69930744/188021827-54a5a4fe-34d6-4959-b937-10128c6f7d94.png)

**Comment by ChrisTitusTech** [comment]
I don't support hacked versions of Windows. This specific version is stripped of many needed services and I will not support it.
