### ISSUE TITLE
A fix for winget without choc

### ISSUE THREAD

**Issue by 4eh5xitv6787h645ebv** [ChrisTitusTech/winutil#1141]
# Winget Update/Installation
Write-Host "Updating/Installing Winget..."
Add-AppxPackage -Path 'https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle'

This would install the latest version of winget and install it with its dependency's

**Comment by BourbonCrow** [comment]
link for documentation about this can be found and it looks good what 4eh5xitv6787h645ebv posted above: https://learn.microsoft.com/en-us/windows/package-manager/winget/

**Comment by BourbonCrow** [comment]
OH i would also like to mention that on a fresh windows enterprise install i could not get the install script to work to install anything. but once i ran the command manually he posted above then the install script in your tool started working just fine! @ChrisTitusTech
