### ISSUE TITLE
Script to set proper Language Settings - because Windows 11 by itself just cant.

### ISSUE THREAD

**Issue by Pleusch** [ChrisTitusTech/winutil#1144]
**Is your feature request related to a problem? Please describe.**
I tried to cleanly install en-DE Language package. Because i life in germany but want german keyboard layout and
english language. Its just not possible Windows 11 is completely dumb if i try that.
The problem is that programs like Solidworks dont have a language setting and just setups whatever Windows 11 is telling them to setup.

I already tried to fix that in regedit: Computer\HKEY_USERS\.DEFAULT where all the settings should be but not change at all.

**Describe the solution you'd like**
I like a script that completely rips out the Windows 11 settings and overrides it.

Here is a Screenshot of the Failure of Windows 11:

![image](https://github.com/ChrisTitusTech/winutil/assets/129837690/3d820c2f-a796-4597-a8c8-dca03aaa41eb)

Would be nice if you could fix that, with a script in your tool!

Thanks alot for your great work to everyone!

**Comment by eabase** [comment]
I have the same issue. Trying to get rid of Spanish.

```powershell
# Get-computerinfo | FL OsLanguage,OSMUIlanguages, OsLocale
	OsLanguage     : en-US
	OsMuiLanguages : {en-US, es-ES}
	OsLocale       : en-US


# Get-LocalGroup  |select SID, Name, Description |Sort SID
	S-1-5-32-544 Administradores
	S-1-5-32-545 Usuarios
	S-1-5-32-546 Invitados
	S-1-5-32-558 Usuarios del monitor de sistema
	S-1-5-32-559 Usuarios del registro de rendimiento
	S-1-5-32-562 Usuarios COM distribuidos
	S-1-5-32-568 IIS_IUSRS
	S-1-5-32-573 Lectores del registro de eventos
	S-1-5-32-578 Hyper-V Administrators
	S-1-5-32-580 Usuarios de administración remota
	S-1-5-32-581 System Managed Accounts Group
	S-1-5-32-583 Device Owners


```
