### ISSUE TITLE
Running Tweaks - nothing happens

### ISSUE THREAD

**Issue by justinaquinoGITB** [ChrisTitusTech/winutil#1145]
**Describe the bug**
I run windows utility on an old 2018 dual core laptop, and nothing happens. When I try to do it again, it says windows utility is already running. I left the PC running most of the day and i cannot see the progress. 

**To Reproduce**
1. Install it in a 2016 Laptop like an Intel Core i3-6006U 
2. apply the desktop Tweaks, click run Tweaks.
**Expected behavior**
It should show some of the scripts being run, and 

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/76767180/8a73730c-bbdc-46b4-ad2f-f3f24fc82734)
![image](https://github.com/ChrisTitusTech/winutil/assets/76767180/6b4dd7d2-8a43-4ed0-a996-ef4cadfd63a7)
![image](https://github.com/ChrisTitusTech/winutil/assets/76767180/c710699f-3ea8-4dbf-8ee3-e42f193a3d78)
![image](https://github.com/ChrisTitusTech/winutil/assets/76767180/45de2849-3256-4cf1-9926-ae5497bf9097)

**Additional context**
Its a really old laptop and it moves in the scale of time of 30mins to 1 hour. Not ideal for my 7 year old daughter who needs it for Home work.

**Comment by 8mpty** [comment]
Are you still facing this issue and if you are, try running the tweaks again. If it gets stuck like before, try pressing any key in the blue powershell prompt and see if the tweaks get shown. Or you could look at the logs in C:\Users\justi\AppData\Local\Temp\Winutil.log.

**Comment by justinaquinoGITB** [comment]
> Are you still facing this issue and if you are, try running the tweaks again. If it gets stuck like before, try pressing any key in the blue powershell prompt and see if the tweaks get shown. Or you could look at the logs in C:\Users\justi\AppData\Local\Temp\Winutil.log.

Thanks will try this out again. 
1) will see if powershell is active 
2) and check the logs (and have screen shots of it).

**Comment by justinaquinoGITB** [comment]
tried again. again nothing happens. Left the PC on to run overnight. nothing happened. 
Now with a X555Q ASsus, also a low end Laptop, ran it and it works fine. 
Suffice to say - its probably a PC has problems running the script. As to what they can be, i dont know.
