### ISSUE TITLE
OneDrive Removal Stuck

### ISSUE THREAD

**Issue by arandomusernam** [ChrisTitusTech/winutil#1154]
Whenever I try to use the "Remove OneDrive" option in the tool, it always gets stuck trying to copy files. The error is "ERROR 404 (0x00000194) Copying file *file*. The Cloud provider quit unexpectedly. Waiting 30 seconds". It just repeats this over and over again with the same file. 

1. Run the tool
2. Go to "tweaks" tab
3. Under advanced tweaks select "Remove OneDrive"
4. Click "Run Tweaks"
5. Get Error

I expected it to just back up my files to my PC and then remove OneDrive. 

I don't know if it is an issue with my OneDrive, or my internet connection, or any number of other things. If someone has a suggestion for fixing this, that would be great! For context, I have already manually backed up my files and then deleted them out of OneDrive myself, but it still throws an error.

**Comment by mateus3c** [comment]
thats happening with me too

**Comment by SVSQUVSH** [comment]
For me I try to remove OneDrive trough winutil, it wont work and I have to uninstall it in Windows.

**Comment by pwillard** [comment]
Same Here...  :(

**Comment by ChrisTitusTech** [comment]
This generally means a file is open in the one drive folder. This script is designed to copy it off OneDrive folders the delete them after the successful copy.

**Comment by SourceTweaks** [comment]
> This generally means a file is open in the one drive folder. This script is designed to copy it off OneDrive folders the delete them after the successful copy.

How do I fix it? Like I tried removing the file from one drive from my phone but that didn't fix it.

**Comment by SourceTweaks** [comment]
> > This generally means a file is open in the one drive folder. This script is designed to copy it off OneDrive folders the delete them after the successful copy.
> 
> How do I fix it? Like I tried removing the file from one drive from my phone but that didn't fix it.

PROBLEM SOLVED. Ctrl + Alt + Del > Go to startup programs and enable One Drive to startup with windows and then just open one drive through task manager and copy the files from your one drive folder to your desktop in a folder. And the tweaks will continue running. I think it just needs one drive to be open and most likely this issue occurs because you deactivate one drive and it's not running when your running the chris Titus tool. Therfore just make sure one drive is running so the chris Titus tool can use the one drive for the process. So just open the program through task manager if the rest of your screen is black etc.

**Comment by Bastigonzales** [comment]
> > > This generally means a file is open in the one drive folder. This script is designed to copy it off OneDrive folders the delete them after the successful copy.
> > 
> > How do I fix it? Like I tried removing the file from one drive from my phone but that didn't fix it.
> 
> PROBLEM SOLVED. Ctrl + Alt + Del > Go to startup programs and enable One Drive to startup with windows and then just open one drive through task manager and copy the files from your one drive folder to your desktop in a folder. And the tweaks will continue running. I think it just needs one drive to be open and most likely this issue occurs because you deactivate one drive and it's not running when your running the chris Titus tool. Therfore just make sure one drive is running so the chris Titus tool can use the one drive for the process. So just open the program through task manager if the rest of your screen is black etc. 

Thanks a lot man, works perfectly.

**Comment by anaohara12** [comment]
@ChrisTitusTech I have a terrible error, the "Remove OneDrive" thing failed and it got stuck, after I closed the program and rebooted the PC, it sucked up all my available storage space, I think it was doing the copy, ran out of storage and it failed, I need to delete the copy the thing did but I have no idea where it is, I've looked everywhere, any idea where it might be so I can delete it? Runing the thing back and also installing the recovery image it did didn't work.

**Comment by onisaibogu** [comment]
> @ChrisTitusTech I have a terrible error, the "Remove OneDrive" thing failed and it got stuck, after I closed the program and rebooted the PC, it sucked up all my available storage space, I think it was doing the copy, ran out of storage and it failed, I need to delete the copy the thing did but I have no idea where it is, I've looked everywhere, any idea where it might be so I can delete it? Runing the thing back and also installing the recovery image it did didn't work. 

For me the destination was my user folder, as in c:\users\xyz, however not in a single folder just kinda everywhere if that helps at all. Think it copies in the same structure they are on onedrive minus the root folder, sorting by date might help a bit but be cautious.
