### ISSUE TITLE
Add Mercury Browser to Install page

### ISSUE THREAD

**Issue by 0x70369** [ChrisTitusTech/winutil#1159]
Hello, Chris. Recently, you did a video on Thorium Browser and it was added to your utility's Install page. But Alex (Thorium's developer) also has a fork from Firefox called Mercury, and it would be nice to have it available as an option to install as well.

The winget ID is Alex313031.Mercury

![image](https://github.com/ChrisTitusTech/winutil/assets/142499149/81d1d62d-38cc-4d56-b4ab-2a255b0cefa5)

**Comment by jstack01** [comment]
Incase you haven't heard Chris has removed Thorium and Mercury from winutil. See commit: https://github.com/ChrisTitusTech/winutil/commit/6ef2ca7df8b603b678331464d12dd8fc14d6570b
