### ISSUE TITLE
Blank Screen after Using Desktop Tweaks

### ISSUE THREAD

**Issue by SVSQUVSH** [ChrisTitusTech/winutil#1161]
**Describe the bug**
When applying desktop tweaks and the script is starting, the desktop turns black (sometimes white).

**To Reproduce**
1. Go to 'Desktop Tweaks'
2. Click on 'untick Numlock at Startup, tick Remove Microsoft Store Apps, tick Remove OneDrive, then run tweaks'
3. Scroll down to 'No scrolling needed'
4. See Error Blank Screen

**Expected behavior**
All the desktop icons disappear including backround picture, taskbar etc.  But the script/winutil will still continue to run and end succesfully. 
I can then close the utility and powershell and have to use a restart shortcut, in order to restart the PC.

**Screenshots**
I don't have screenshots.

**Additional context**
Some side notes:
- Fresh Windows Home, Version 10.0.19045 Build 19045 installation.
- Drivers and Updates up to date
- Did a little tweak before running WinUtil. I disabled the visual effects in windows. How to disable visual effects: Type 'system properties' in search -> click 'advanced system settings' on the right -> under the advanced at 'performance', click 'settings' -> under 'visual effects' click 'adjust for best performance'. Finished!
Im not 100% sure if I used the tweak before or after using winutil, but usually when using winutil I do it before it. I think its still worth noting it, because maybe this caused the blank screen?

- Latest 64x and 86x visual c++ redist installed

Thanks for your attention!

**Comment by FanieVenter** [comment]
after this happens just press Ctrl+Shift+Esc and launch a new proccess called explorer

**Comment by SVSQUVSH** [comment]
Thanks for your tipp,. So did you experience the same issue? I guess explorer might freak out when using winutil and thats why I see a blank screen...

**Comment by FanieVenter** [comment]
yeah its because you are Microsoft and Onedrive, Onedrive utilizes Explorer

**Comment by SVSQUVSH** [comment]
Allright, thats good to know. When speaking about Onedrive, lately it doesnt actually remove onedrive... I still see it under Apps. Have to uninstall it manually then.

**Comment by lavavex** [comment]
> Allright, thats good to know. When speaking about Onedrive, lately it doesnt actually remove onedrive... I still see it under Apps. Have to uninstall it manually then.

yep, microsoft is being microsoft and preventing us from touching certain registry keys, as well as not removing certain artifacts of the program after uninstall. a fix is being thought of but its becoming more and more clear that microsoft is roadblocking a lot of tweaks
