### ISSUE TITLE
OneDrive removal doesn't fully remove OneDrive in 23h2

### ISSUE THREAD

**Issue by lavavex** [ChrisTitusTech/winutil#1170]
OneDrive does not get completely removed in 11 23H2 fresh install
Stays in side bar of explorer and in the "installed apps" section, but is unable to be removed due to the setup executable missing

![image](https://github.com/ChrisTitusTech/winutil/assets/27239435/afb87550-e38b-4095-9e2e-a6ccd7956568)
![image](https://github.com/ChrisTitusTech/winutil/assets/27239435/b29c3b13-89b4-4fb9-98ce-83d39e350bc4)

**Comment by lavavex** [comment]
Manually setting the registry key the script sets for removing from sidebar works, I wonder why the command in the script doesn't work...
Also removing that "Gallery" from the sidebar would be nice as well.

**Comment by lavavex** [comment]
Seems the command is broken, I feel like microsoft did something to specifically prevent us from changing certain keys using powershell now...
![image](https://github.com/ChrisTitusTech/winutil/assets/27239435/8ae40145-8739-4427-89f3-90640d60a770)

**Comment by ChrisTitusTech** [comment]
Ah, well time to adapt to the changes then. Technically, Microsoft should put the HKCR into HKLM\ SOFTWARE\Classes but they may omit this to force the program on it's users. Worst case we can modify using a DISM, but I'd like to avoid that.

**Comment by lavavex** [comment]
> Ah, well time to adapt to the changes then. Technically, Microsoft should put the HKCR into HKLM\ SOFTWARE\Classes but they may omit this to force the program on it's users. Worst case we can modify using a DISM, but I'd like to avoid that.

Saw the stream you had this morning, i think due to the fact you had onedrive removed on that vm before updating to 23h2, the sidebar didn't have it and it wasn't re added when undoing the tweak cause you cant write to HKCR. On clean installs or upgrades that never had one drive removed, that sidebar entry doesn't get removed.
