### ISSUE TITLE
Disabling Bing Search in Start Menu causes League of Legends Client to not work properly

### ISSUE THREAD

**Issue by sebastien5694** [ChrisTitusTech/winutil#1171]
When I disable Bing Search in Start Menu via the toolbox, I can get the League of Legends Client to run but I am unable to start a game. Also some functionalities such as the homepage of the client is not loading at all. 

I assume the League client relies on Bing and most likely Microsoft Internet Explorer / Edge Browser to run properly. I had experienced similar issues running League with on older Microsoft Internet Explorer on Win8 before. Right now I am using Win 10 LTSC with some tweaks enabled from the toolbox and it's working fine so far. I don't have Edge browser installed but I've got Internet Explorer installed, have not uninstalled it though. 

So this is not an issue related to the toolbox itself. It's just to let everyone who use League Client know that you need this Bing Search tweak off to get the League Client working properly. 

Finally I want to mention that I don't see the Bing Search in my start menu even though I have not disabled it from the toolbox, weird. But League Client is working great so is Windows. Went down from 156 processes to 60ish on a Pentium G860 dual core. I couldn't get Windows 10 to run smoothly before using Chris'toolbox. So thank you Chris and all the contributors ;)

**Comment by ChrisTitusTech** [comment]
I wonder if you uninstalled WebView2 with Edge. That tends to be a soft dependency in a TON of programs.
