### ISSUE TITLE
Redirect Search to Default Browser w/o removing Edge

### ISSUE THREAD

**Issue by jstack01** [ChrisTitusTech/winutil#1172]
I just had a small suggestion and was wondering if this could be implemented as a tweak into winutil. Would it be possible to have the windows search redirect to your default web browser without removing edge? I know Chris has cautioned against removing edge and I would like to avoid doing so to prevent potential system instability. That said, I still find it incredibly frustrating when I search for anything in windows search and edge decides to just launch itself with all the extra bloat on top of it. I understand if he would like to keep the tweaks to a minimum, just thought I'd ask. Thanks for your consideration. Keep up with the great content!

-Jonathan

**Comment by ChrisTitusTech** [comment]
Not a bad idea, the redirect is using a cmd file to push to the default browser instead of edge.exe via registry. I'm sure I can make this a tweak that would technically work with edge.
