### ISSUE TITLE
Windows 10 doesn't recognize commands to launch CTT

### ISSUE THREAD

**Issue by Nicogue** [ChrisTitusTech/winutil#118]
**Describe the bug**
I have the same issue on two windows, one pc and one laptop, both are updated

**To Reproduce**
I tried to use on powershell as a user and  admin, both has same response
iwr -useb https://christitus.com/win | iex

**Expected behavior**
Should launch CTT application

**Additional context**
"iwr" is not recognized as an internal or external command, executable program or batch file.

Also tried with curl command but needs an authentication data

**Comment by ChrisTitusTech** [comment]
Might be a really old version of powershell or are using the powershell app and not the system powershell. 

Are you launching from right clicking start button and launch powershell with admin?

**Comment by Nicogue** [comment]
> iwr -useb https://christitus.com/win | iex

Dear Chris please accept my apologies, I didn't know that windows has another terminal called powershell, thanks for your valuable work.

**Comment by ChrisTitusTech** [comment]
No worries! Microsoft logic is completely ridiculous sometimes...
Not the first time they named something the exact same with two different use cases lol.
