### ISSUE TITLE
Use neat feathures that EU enforced on Windows

### ISSUE THREAD

**Issue by mikolajlubiak** [ChrisTitusTech/winutil#1188]
**Is your feature request related to a problem? Please describe.**
Recently Windows made a lot of changes that allows you to for example: Remove ANY apps without having to use workarounds.

**Describe the solution you'd like**
Detect if the computers region is set to somewhere in EEA and then use those features instead of the workarounds (for example when removing Edge or Cortana).

**Describe alternatives you've considered**
N/A

**Additional context**
You have access to those features only if your region is set to somewhere in the EEA.
https://blogs.windows.com/windows-insider/2023/11/16/previewing-changes-in-windows-to-comply-with-the-digital-markets-act-in-the-european-economic-area/

**Comment by ivanodapice** [comment]
If you fresh install windows today and choose English(World) as regional input you get a barebone install. Wonder if it'll work similar with Europe unlocking various behaviors

**Comment by mikolajlubiak** [comment]
> If you fresh install windows today and choose English(World) as regional input you get a barebone install
Thanks. Does this English (World) install allow you to remove any apps like the EEA install does? Or maybe apps like Cortana and Edge aren't even installed on the English (World) install?

**Comment by BourbonCrow** [comment]
> > If you fresh install windows today and choose English(World) as regional input you get a barebone install
> 
> Thanks. Does this English (World) install allow you to remove any apps like the EEA install does? Or maybe apps like Cortana and Edge aren't even installed on the English (World) install?

no the world install only installs the bare minimum like it skips all sponsored apps and stuff since it doesnt know your region but edge and cortana still there since they are part of the operating system.

**Comment by KonTy** [comment]
> > If you fresh install windows today and choose English(World) as regional input you get a barebone install
> 
> Thanks. Does this English (World) install allow you to remove any apps like the EEA install does? Or maybe apps like Cortana and Edge aren't even installed on the English (World) install?

All this behavior is control by a file called C:\Windows\System32\IntegratedServicesRegionPolicySet.json. If you edit this file you can then control apps, delete then or whatever.

for example there is a section for Edge and you can clearly see that the default behavior is disabled (meaning you can't uninstall it) and you see the reguins where you can uninstall it. Take a look at the file there are many more magical things that you can twaek in there. :)

``` json

      "$comment": "Edge is uninstallable.",
      "guid": "{1bca278a-5d11-4acf-ad2f-f9ab6d7f93a6}",
      "defaultState": "disabled",
      "conditions": {
        "region": {
          "enabled": ["AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", "FR", "GF", "GP", "GR", "HR", "HU", "IE", "IS", "IT", "LI", "LT", "LU", "LV", "MT", "MQ", "NL", "NO", "PL", "PT", "RE", "RO", "SE", "SI", "SK", "YT"]
        }
      }
```

**Comment by cloudedaim** [comment]
Was about to suggest this. This would be major with Windows building in Edge remover tools & replacing the need of EdgeDeflector and any of it's forks. Highly important to bring these patches or enable them in Windows. Released a few days ago on release preview (22631.2787)

**Comment by rcmaehl** [comment]
There's two ways to go about this:

1. Set the following values to an EEA Country and Reboot. This is likely a permanent workaround,

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Control Panel\DeviceRegion\DeviceRegion
- HKEY_USERS\.DEFAULT\Control Panel\International\Geo\Name
- HKEY_USERS\.DEFAULT\Control Panel\International\Geo\Nation
- HKEY_CURRENT_USER\Control Panel\International\Geo\Nation
- HKEY_CURRENT_USER\Control Panel\International\Geo\Name

2. Add the 2 Character Nation ID to C:\Windows\System32\IntegratedServicesRegionPolicySet.json after adjusting the ACL Owner and adding Write permission for Administrators. This is probably going to be a temporary workaround as I'm sure Microsoft will update this file often

**Comment by raaomoka** [comment]
> There's two ways to go about this:
> 
> 1. Set the following values to an EEA Country and Reboot. This is likely a permanent workaround,
> 
> * HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Control Panel\DeviceRegion\DeviceRegion
> * HKEY_USERS.DEFAULT\Control Panel\International\Geo\Name
> * HKEY_USERS.DEFAULT\Control Panel\International\Geo\Nation
> * HKEY_CURRENT_USER\Control Panel\International\Geo\Nation
> * HKEY_CURRENT_USER\Control Panel\International\Geo\Name

Please where can I find the codes/settings for Ireland?

**Comment by ViktorVoloshko** [comment]
> Please where can I find the codes/settings for Ireland?

https://learn.microsoft.com/en-us/windows/win32/intl/table-of-geographical-locations
