### ISSUE TITLE
After run "Desktop" options in teaks (disk space is full)

### ISSUE THREAD

**Issue by andybc262** [ChrisTitusTech/winutil#119]
**Describe the bug**
After run "Desktop" options in teaks (disk space is full)

**Expected behavior**
I supposed it's because "restore point" but it was deleted and disk stays full.

![image](https://user-images.githubusercontent.com/41092562/189510928-125d6299-d186-4f44-b714-ba59a206e12d.png)

**Comment by andybc262** [comment]
![image](https://user-images.githubusercontent.com/41092562/189510935-7aee4023-17ee-45b1-b473-6c9b3f624a13.png)
it has 90gb free space before "run tweaks "

**Comment by ChrisTitusTech** [comment]
That is very odd, what is your system restore properties at? 

Look up "System Protection" in search

or Start -> Run -> `sysdm.cpl` and then click system protection.

Delete the restore points and see if the space comes back.
