### ISSUE TITLE
Too many options on the install page for some screens

### ISSUE THREAD

**Issue by RanceH** [ChrisTitusTech/winutil#1191]
On 13" laptops the size of the install page is larger than what can be shown on the page despite having the screen resolution set to 2560x1440

At this resolution and overall screen size the scale setting is set to 200% else the device is unusable.

At this resolution and scale not all the install page can be shown at a time.

Unsure how to suggest a solution, setting the screen scale back to 100 makes the app visible, but for those of us that are visually impaired it is unusable.  are scrollbars an option in the various panels?

**Comment by KonTy** [comment]
Please try this new version. Does it work better for you?

``` PowerShell
iwr -useb https://raw.githubusercontent.com/KonTy/winutil/Test-11-15/winutil.ps1 | iex
```

**Comment by syahrezank** [comment]
can confirm this method works

> Please try this new version. Does it work better for you?
> 
> ```powershell
> iwr -useb https://raw.githubusercontent.com/KonTy/winutil/Test-11-15/winutil.ps1 | iex
> ```

also there's another method if u have already used the default command
irm https://christitus.com/win | iex 

just press alt+space then click maximize. Then everything will be shown. Although the font gets smaller

**Comment by ChrisTitusTech** [comment]
Updated to include @KonTy fixes.
