### ISSUE TITLE
After using the script the taskbar icons disappearing or not responding

### ISSUE THREAD

**Issue by elazar4** [ChrisTitusTech/winutil#120]
I used the script and it worked great!
And suddenly I noticed that the taskbar icons are disappearing or not responding
I tried to reset the icons with the attached script
And after restart the problem returns.

I would appreciate a solution.
[reset icons.txt](https://github.com/ChrisTitusTech/winutil/files/9542368/reset.icons.txt)

**Comment by ChrisTitusTech** [comment]
Try this powershell command and reboot
`Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "HungAppTimeout" -ErrorAction SilentlyContinue`
This this property was messing with people and causing hangs and flickering.

**Comment by elazar4** [comment]
Wow that solved the problem!
Thank you very much, you helped me a lot!
