### ISSUE TITLE
Loop when UAC is Disabled and current user is not admin

### ISSUE THREAD

**Issue by zakary2841** [ChrisTitusTech/winutil#1207]
**Describe the bug**
When you launch the script with UAC disabled. 
![image](https://github.com/ChrisTitusTech/winutil/assets/26402356/397ab7bc-0fcd-4d64-ba87-c0675d1cca58)
and the user does not have admin permissions

**To Reproduce**
Steps to reproduce the behaviour:
1. Go on to a user with no admin permissions and UAC disabled
2. Run irm christitus.com/win | iex
3. Watch as PowerShell infinitely loops until closed

**Expected behaviour**
Attempted elevation maybe 1/2 times then pause.

**Comment by jstack01** [comment]
Works for me under those conditions listed on Win10 Pro 22H2. Is this still an issue for you? The script should self-elevate now. Not sure if that wasn't the case when you created this issue.
