### ISSUE TITLE
Debloat messing up valorant

### ISSUE THREAD

**Issue by xxxLepreChAUnSxxx** [ChrisTitusTech/winutil#121]
Yesterday I used the Debloat on windows 11 and realized afterward it wouldn't let me tab back into the game Valorant after I minimize it.  At the time I thought it was a problem with windows 11 so I just said fuck it and went back to windows 10 which fixed my problem. Today I realized that I haven't debloated windows so I used your tool again, after everything worked successfully I realized the problem with Valorant appeared again. After a lot of troubleshooting and research, I think the problem is with the tool and is related to the problem with the taskbar that others are having. 

Also, I had the tool create a restore point, how can I go back?

(more details of exactly what I ran)
- **Tweaks**: Desktop Recommendation
- **Config**: All .Net Framework
- **Updates**: Security Settings

**Comment by JustTakingNotes** [comment]
I had the same issue and posted the resolution in my issue thread: https://github.com/ChrisTitusTech/winutil/issues/122

**Comment by ChrisTitusTech** [comment]
Fixed in latest commit. 
If you don't want to run tweaks again just type this into powershell
`Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "HungAppTimeout" -ErrorAction SilentlyContinue`
