### ISSUE TITLE
Spelling correction

### ISSUE THREAD

**Issue by Dantasstic** [ChrisTitusTech/winutil#1211]
Spelling issues on the MicroWin section

**To Reproduce**
1. Go to the MicroWin section of the app

**Expected behavior**
The word "choose" should be used here instead of the word "chose".

**Screenshots**
![2023-11-28 - 2246-22](https://github.com/ChrisTitusTech/winutil/assets/48727187/fcb4825d-c8e1-42bd-8223-371f63a7cf6f)

**Comment by munkk01** [comment]
This issue can be closed as it was addressed in [https://github.com/ChrisTitusTech/winutil/pull/1217](url)
