### ISSUE TITLE
Installer failed with exit code: 0x80070002 : The system cannot find the file 

### ISSUE THREAD

**Issue by Dotdk** [ChrisTitusTech/winutil#1213]
Getting thise wile try upgrade all 
im running a win 11 full updated machine 
cant figur out why i get them thats why i write here. 
Sorry for my bad english. 
![image](https://github.com/ChrisTitusTech/winutil/assets/6298561/87481e06-1120-4390-9cbb-138c64e2fe04)

**Comment by munkk01** [comment]
Appears to be related to an issue being tracked under https://github.com/microsoft/winget-cli/issues/3166

A possible solution in that issue:
https://github.com/microsoft/winget-cli/issues/3166#issuecomment-1824116673

I don't guarantee this a solution, offering as a means to get an idea of where to look for possible solutions.

**Comment by Dotdk** [comment]
Seems it worked thx for the answare
