### ISSUE TITLE
Using with Virtualbox

### ISSUE THREAD

**Issue by AnonymousRonin** [ChrisTitusTech/winutil#1215]
So I have used this tool before but never with a virtual box.  I tried doing my normal installs and tweeks and as far as the installs go, I don't think anything actually installed.  Couldn't find Tor or Librewolf, so sublime text, no OBS studio.  Is there something  I am missing here.  Thanks.

**Comment by munkk01** [comment]
Any other details you can share?

Windows Version
Terminal used (Windows Terminal, cmd, Alacritty, etc)
PowerShell Version

Program(s) you attempted to install

Check your C:\Users<user>\AppData\Local\Temp folder for any references to Winutil.log, and a Winget folder (Should show the program(s) installed if successful.
