### ISSUE TITLE
netlogon service will be set to manual but it's needed by windows time sync service (in domain environment)

### ISSUE THREAD

**Issue by popy2k14** [ChrisTitusTech/winutil#1216]
**Describe the bug**
netlogon service will be set to manual but it's needed by windows time sync service (in domain environment)

**To Reproduce**
1. run tweaks (netlogon is set to manual)
2. Reboot
3. In windows settings under "Date/Time" you can see a source "CMOS clock" for timesync
4. time sync from DC is not working

**Expected behavior**
Not disable netlogon in domain environments

**Screenshots**

**Additional context**
It would be nice if there would be an detection, if the computer is joined to a domain and skip some parts of the tweaks.

PS.: i know that normally you do such tweaks with GPO on the DC, but hey i have local admin rights and want to tweak my PC like i would :-)

**Comment by lavavex** [comment]
Made a commit request to just remove netlogon from being touched by script, as according the script, it should already be manual on clean systems, so it seems redundant to touch it again especially if it may cause an issue...

**Comment by popy2k14** [comment]
In my case it was "manual" and not started, when needed by windows time sync service!
I think it was set to manual by the script (on other machines, where the script was not executed, it is on "auto").
After setting it manually to "auto" and started it manually, windows time sync service worked again, against the DC.

So yes, dont touch "netlogon" would be nice.

**Comment by lavavex** [comment]
> In my case it was "manual" and not started, when needed by windows time sync service! I think it was set to manual by the script (on other machines, where the script was not executed, it is on "auto"). After setting it manually to "auto" and started it manually, windows time sync service worked again, against the DC.
> 
> So yes, dont touch "netlogon" would be nice.
> 
> PS.: thx fot the pull request.

all good, it was something i could do with no knowledge of how to code... now to hope i dont get flamed for pulling to main as test branch is non existant

**Comment by munkk01** [comment]
> > In my case it was "manual" and not started, when needed by windows time sync service! I think it was set to manual by the script (on other machines, where the script was not executed, it is on "auto"). After setting it manually to "auto" and started it manually, windows time sync service worked again, against the DC.
> > So yes, dont touch "netlogon" would be nice.
> > PS.: thx fot the pull request.
> 
> all good, it was something i could do with no knowledge of how to code... now to hope i dont get flamed for pulling to main as test branch is non existant

That's what I did so we're in the same boat :)

**Comment by lavavex** [comment]
Netlogon has been changed to be set to Automatic in new test branch per PR #1220 being merged
