### ISSUE TITLE
Can't Open The Utility

### ISSUE THREAD

**Issue by MaxRageMX** [ChrisTitusTech/winutil#1227]
**Describe the bug**
It Always Shows The Following error:

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/139542698/2e72fcc1-649f-41be-848f-f90abb33168f)

**Comment by 0hip** [comment]
`irm https://christitus.com/win | iex`

**Comment by 0hip** [comment]
> **Describe the bug** It Always Shows The Following error:
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/139542698/287326717-2e72fcc1-649f-41be-848f-f90abb33168f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTM1ODIsIm5iZiI6MTcwMTQ1MzI4MiwicGF0aCI6Ii8xMzk1NDI2OTgvMjg3MzI2NzE3LTJlNzJmY2MxLTY0OWYtNDFiZS04NDhmLWY5MGFiYjMzMTY4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxNzU0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzkxYzVhZjRlOGVlZDcyMzFhNDY0OTRiZmMwNmU5OTE4YmQ3MzVjOThmOTIwZDU5YzU5YTMwYzI0ZGI5YWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ytfHwhMlmtJY9xBUj3rEaH4_yhGSGVxyYq8PWIz0aEI)

`irm https://christitus.com/win | iex`
