### ISSUE TITLE
Hide the PowerShell window in the background when launching the utility 

### ISSUE THREAD

**Issue by thesobercoder** [ChrisTitusTech/winutil#1229]
**Is your feature request related to a problem? Please describe.**
It would be great if the PowerShell window didn't show up when launching the utility from the desktop shortcut.

**Describe the solution you'd like**
The PowerShell window is not shown in the background when launching the utility.

**Describe alternatives you've considered**
Maybe distribute it as a single compiled executable.

**Additional context**
N/A

**Comment by jstack01** [comment]
To add to that. If it’s possible, would it be possible to add a parameter to show the script output? Maybe by default the script output can be hidden, and by calling the script with a certain parameter it will show the output. Or vice versa, whatever is best for everybody.

**Comment by omen124** [comment]
> @jstack01 If you update the desktop shortcut to something like this, then it does the job.
> 
> ```powershell
> C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -Command "Start-Process powershell.exe -WindowStyle hidden -verb runas -ArgumentList 'irm https://christitus.com/win | iex'
> ```

Unfortunately, this isn't quite what I was hoping for, my goal was to have the whole "update all"command (which does more than just winget) run behind the scenes without opening the CLI at all, is that possible to do with something in a desktop shortcut?
Right now you get 2/3 things open (the main command and its CLI, and then another one when you update) and the hope is to just have an icon trigger that one update all event without windows opening (just the UAC prompt).
