### ISSUE TITLE
After tweak windows broke

### ISSUE THREAD

**Issue by Rene0220** [ChrisTitusTech/winutil#123]
Winver 10 home 20h2 19042.1706
Videos: https://www.youtube.com/watch?v=JWGHKBuQadk , https://www.youtube.com/watch?v=7NvdTjo_-hI

**Comment by Rene0220** [comment]
And undo all tweaks dont help, help only restore to backup or reinstall windows.

**Comment by Rene0220** [comment]
> Chris just have fixed in the original code, but if dont work for you here a link on how to fix it [#122 (comment)](https://github.com/ChrisTitusTech/winutil/issues/122#issue-1369192100)

When update of exe file?

**Comment by ChrisTitusTech** [comment]
The online exe is auto updated. Let me update the offline one and reup load it. I'll have it done by 4 PM CST. Within an hour. 

Here is the command to fix it right now in powershell (reboot after running)
`Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "HungAppTimeout" -ErrorAction SilentlyContinue`

**Comment by ChrisTitusTech** [comment]
Offline exe has been redone. Go download it at <https://cttstore.com>
