### ISSUE TITLE
Windows10 still updated after setting "Disable all updates" 

### ISSUE THREAD

**Issue by nickr61** [ChrisTitusTech/winutil#1233]
**Describe the bug**
I used the util to set "Disable all updates" for Windows10 but I still find Windows auto-updating with both feature and security updates without my requesting it which I then have to uninstall if I can (some updates will not uninstall once installed ie KB:5031356 ) Also it keeps reinstalling Microsoft edge after I have removed it many times. Is there a way I can completely disable all windows updates with this util and permanently remove Edge

The  main reason I use this util is to stop windows update as I do not want Microsoft to update my PC without my permission ever.

**Comment by Jimputinfn** [comment]
What version of Windows 10 do you have, because as far as I know, the update thing doesn't work with Windows home version.

**Comment by nickr61** [comment]
yep Home edition, 

![image](https://github.com/ChrisTitusTech/winutil/assets/120713803/db6a2f81-c938-4629-95f2-9a7785f160cf)

**Comment by Jimputinfn** [comment]
It works only in windows Pro Edition both 10 and 11
