### ISSUE TITLE
VMware Install

### ISSUE THREAD

**Issue by EXXodos911** [ChrisTitusTech/winutil#1234]
Id Like to see a VMware Support in the install menu it will be very great and helpful and + if u can add the vmware os optimization somehow it will be amazing

**Comment by DigitalIQ** [comment]
I was creating now a couple of different ISOs with Win11_22H2_English_x64v1.iso and Win11_23H2_EnglishInternational_x64.iso.
Installation inside VMware Workstation 17.5 Pro.
I can approve, **Ethernet (Network) drivers are not installed**. Also very strange: The **File Explorer is chrashing**, when I try to open a folder. Even after a new, clean installation.
By mounting the VMware Tools DVD, Windows shows a popup - what to do with a DVD --> I was able to click on "run setup.exe" so I was able to install VMware Tools.
But also after that - Ethernet is not working and File Explorer crashes.

**Comment by KonTy** [comment]
Microwin doesn't remove any network drivers. What happens if you install vanial ISO does it have network drivers included?

**Comment by hpsxrb** [comment]
> Eu estava criando agora alguns ISOs diferentes com Win11_22H2_English_x64v1.iso e Win11_23H2_EnglishInternational_x64.iso. Instalação dentro do VMware Workstation 17.5 Pro. Posso aprovar, **os drivers Ethernet (rede) não estão instalados** . Também muito estranho: o **File Explorer está travando** quando tento abrir uma pasta. Mesmo depois de uma instalação nova e limpa. Ao montar o DVD do VMware Tools, o Windows mostra um pop-up - o que fazer com um DVD -> Consegui clicar em "executar setup.exe" para poder instalar o VMware Tools. Mas também depois disso - a Ethernet não funciona e o File Explorer trava.

I can confirm that the same thing happens to me.
