### ISSUE TITLE
Error when trying to create an ISO with MicroWIN

### ISSUE THREAD

**Issue by luciano1302** [ChrisTitusTech/winutil#1235]
[Erro_MicroWin.txt](https://github.com/ChrisTitusTech/winutil/files/13537125/Erro_MicroWin.txt)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
[Erro_MicroWin.txt](https://github.com/ChrisTitusTech/winutil/files/13537127/Erro_MicroWin.txt)

**Comment by KALIXHOSTING** [comment]
What ISO are u using and where did u get it from so we can take a look at it 

Thanks
