### ISSUE TITLE
[Feature Request:] Custom Folder Install

### ISSUE THREAD

**Issue by Jabe64** [ChrisTitusTech/winutil#1238]
Hi!

First of all, thanks a lot for your amazing tool 👏 I've seen the evolution of it and it's amazing. One of the 3 best Windows tools in my opinion with [TronScript](https://github.com/bmrf/tron/) and [WinGetUI](https://github.com/marticliment/WingetUI) in no particular order.

I have one suggestion to make it even better: adding the possibility to setup custom folders for program installation.

When I setup computers I always install software in customs folders, for example:
```
- Audacity in Program Files\#Audio\Audacity 
- Brave in Program Files\#Internet\#Web Browser\Brave 
- VLC in Program Files\#Video\VLC 
- etc.
```

The reason why I use this is first of course to sort out types of software but it's also to see faster in regular "Program Files" folder if someone else than me installed something that shouldn't be here.

I know it could be difficult to implement depending on the possibility of the software itself to install in a custom folder by command line but it would make this tool perfect especially with possibility to use the same configuration files for multiple setups.

I hope you will consider this idea 🤞🍀

**Comment by Gerotama** [comment]
+1 to this

**Comment by Jabe64** [comment]
Please reopen and reconsider 🙏
