### ISSUE TITLE
microwin windows 11 bluescreen

### ISSUE THREAD

**Issue by Khalylexe** [ChrisTitusTech/winutil#1239]
**Describe the bug**
well i tried installing windows 11 with microwin modifications applied but it blue screened when restarting to continue

**To Reproduce**
1. download windows 11 iso from official site
2. using microwin to debloat it
3. flashing the iso to a usb disk with rufus
4. booting it through the usb
5. installing it as normal
6. when it does its first restart it shows a blue screen

**Expected behavior**
no blue screen

**Screenshot**
![20231203_211805.jpg](https://github.com/ChrisTitusTech/winutil/assets/119526243/3be29a02-ee51-4365-b1e6-776ff295b13d)

**Comment by KALIXHOSTING** [comment]
Just Send it via Ventoy on Rufus make sure no other option is enabled if u need to bypass tpm or secureboot just use the shift f10 option on during install

**Comment by Khalylexe** [comment]
do you think the reason for that was the options of rufus?

**Comment by wms8688** [comment]
I have the same issue using Ventoy or Rufus

**Comment by KALIXHOSTING** [comment]
> do you think the reason for that was the options of rufus?

yes i do as Rufus auto adds options I have had success install using MircoWin.iso

**Comment by KALIXHOSTING** [comment]
> I have the same issue using Ventoy or Rufus

are u on the latest ventoy and did u check off the option to send it to ventoy as soon as its completed iso ?

**Comment by wms8688** [comment]
> > I have the same issue using Ventoy or Rufus
> 
> are u on the latest ventoy and did u check off the option to send it to ventoy as soon as its completed iso ?

I am on the latest version of Ventoy. I manually copied the iso to the Ventoy drive.

**Comment by KALIXHOSTING** [comment]
@wms8688  tick the option on microwin to copy to ventoy while its doing everything and retry
