### ISSUE TITLE
If WinGet is already installed, it will try to install it anyways or it will not detect it at all

### ISSUE THREAD

**Issue by DocSwitch** [ChrisTitusTech/winutil#1247]
**Describe the bug**
When installing listed programs with "Install Selection", the tool will try to install WinGet through "Alternative Installer and Direct Installing", but will fail if WinGet is already installed. On my machine it should be already at the latest release available (v1.6.3133).
If I try to "Upgrade All", the tool just says WinGet is not installed (when it is).
"Uninstall Selection" will just say WinGet has failed to install and "Get Installed" says WinGet is not installed.
WinGet IS installed and in PATH; same goes for Chocolatey

**To Reproduce**
1. Go to 'Install'
2. Select some programs you want to (un)install
3. Click one of the buttons to (un)install programs
4. See error in the PowerShell console

**Expected behavior**
If Chocolatey and/or WinGet are detected to be installed, proceed to (un)install the selected programs.

**Additional context**
I had installed WinGet through the .msixbundle on WinGet's official GitHub page.

**Comment by KALIXHOSTING** [comment]
@DocSwitch yes sometimes this can get annoying but all you have to do is close out and reopen winutil  it try to install a program and it should work like normal since u have a success winget install its been happing alot 

Sorry for the inconvenience

**Comment by dissyllabic** [comment]
I have the same issue: 
```
====Chris Titus Tech=====
=====Windows Toolbox=====
Checking if Chocolatey is Installed...
Chocolatey Already Installed
File already exists at: C:\Users\Daniel\AppData\Local\Temp\cttlogo.png
Checking if Winget is Installed...
Running Alternative Installer and Direct Installing
Winget Installed
===========================================
--      Winget failed to install        ---
===========================================
``` 
Whenever I try to install anything I get the above error, also, trying to re-install win-get via the utility doesn't work either, I get:

```
Chocolatey v2.2.2
Installing the following packages:
winget
By installing, you accept licenses for the packages.
winget v1.6.3421 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - winget - winget v1.6.3421 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
```

**Comment by majarman** [comment]
I have the same issue, on a brand new windows 10 install. I have tried manually uninstalling and reinstalling winget through chocolatey with no luck.
