### ISSUE TITLE
[Feature Request] Running stealth updates

### ISSUE THREAD

**Issue by omen124** [ChrisTitusTech/winutil#1249]
This program does a great job of updating applications from multiple sources and I frequently use it to update family computers.
It would be great to have a way to run this in the background without any windows appearing so it can be scheduled within Windows to update programs on a certain frequency and know that it isn't making them worry about what they are seeing.

**Comment by OmdevShastri** [comment]
Hey, I do that too! Its very handy to update family computers without waiting around too much.. Would love to have this scheduled!
