### ISSUE TITLE
Install Selection Doesn't Install Applications

### ISSUE THREAD

**Issue by viktailor** [ChrisTitusTech/winutil#1251]
**Describe the bug**
After selecting application(s) to install, the tool produces a 'Done' dialogue box indicating the application(s) has been installed but the application doesn't install

**To Reproduce**
1. Open Tool (via Terminal (admin))
2. In the Install tab, select application(s) to install (is an issue whether I attempt to install 1 or multiple applications)
3. Click 'Install Selection'
4. Get a 'Done' message and 'Installs Have Finished' on Terminal window
5. Application(s) have not been installed and cannot be found on OS

**Expected behavior**
Application(s) to have installed

**Screenshots**
Select applications
![image](https://github.com/ChrisTitusTech/winutil/assets/78094095/ca6d2da9-f4e3-422e-a307-c8cc86111fbc)

Install Selection
![image](https://github.com/ChrisTitusTech/winutil/assets/78094095/cf8e19b5-75fd-4590-b29a-8d916fc75183)

Terminal Success Message
![image](https://github.com/ChrisTitusTech/winutil/assets/78094095/348c350a-9672-474f-b83f-8a8f5eae695e)

**Additional context**
This is the first time I am using the tool so it's likely I'm missing something but I did a fresh Win 11 install and used the tool to debloat and uninstall OneDrive which worked fine. I then tried to use the tool to install applications and is where I ran in to issues

**Comment by munkk01** [comment]
> **Describe the bug** After selecting application(s) to install, the tool produces a 'Done' dialogue box indicating the application(s) has been installed but the application doesn't install
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open Tool (via Terminal (admin))
> 2. In the Install tab, select application(s) to install (is an issue whether I attempt to install 1 or multiple applications)
> 3. Click 'Install Selection'
> 4. Get a 'Done' message and 'Installs Have Finished' on Terminal window
> 5. Application(s) have not been installed and cannot be found on OS
> 
> **Expected behavior** Application(s) to have installed
> 
> **Screenshots** Select applications ![image](https://private-user-images.githubusercontent.com/78094095/288037706-ca6d2da9-f4e3-422e-a307-c8cc86111fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODc1MTcsIm5iZiI6MTcwMTc4NzIxNywicGF0aCI6Ii83ODA5NDA5NS8yODgwMzc3MDYtY2E2ZDJkYTktZjRlMy00MjJlLWEzMDctYzhjYzg2MTExZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0NDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NWMzNTM0N2M4NzljZjA1MzFjZGQxZjljYmI3N2U1NjQzYjYyMzY5ZmVmOWRmZDBiYmE3NDhmYWE0ZTYzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZeyZKs_9qH9tQncxSAsegbUEmvdCHR9ZkEY5EWP-9Q)
> 
> Install Selection ![image](https://private-user-images.githubusercontent.com/78094095/288038231-cf8e19b5-75fd-4590-b29a-8d916fc75183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODc1MTcsIm5iZiI6MTcwMTc4NzIxNywicGF0aCI6Ii83ODA5NDA5NS8yODgwMzgyMzEtY2Y4ZTE5YjUtNzVmZC00NTkwLWIyOWEtOGQ5MTZmYzc1MTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0NDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMmZiNGI4NWJiZjY2MWU2YjI5YTBkZjc2MmFlNjkxZTY1Y2ZkMTkwZDZlZmJiYWI5NjU3YzAzZGY2MDM3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J5hXi8JTvhK1SjzJvyWhHH-0FLMg7YPlxjuxBU369Ro)
> 
> Terminal Success Message ![image](https://private-user-images.githubusercontent.com/78094095/288038577-348c350a-9672-474f-b83f-8a8f5eae695e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODc1MTcsIm5iZiI6MTcwMTc4NzIxNywicGF0aCI6Ii83ODA5NDA5NS8yODgwMzg1NzctMzQ4YzM1MGEtOTY3Mi00NzRmLWI4M2YtOGE4ZjVlYWU2OTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0NDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDk2MTUwZTgyMWVjZTc1ODQwNzVkN2NkYzM2YTFkMzgxZjU3Mzg2OGZjMTkyOTk4M2UyZGQ4NDFjOTZmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zrk6YFvvgYjreva4ICBdW0dYd0JsSKl2dZqZ3rYA66E)
> 
> **Additional context** This is the first time I am using the tool so it's likely I'm missing something but I did a fresh Win 11 install and used the tool to debloat and uninstall OneDrive which worked fine. I then tried to use the tool to install applications and is where I ran in to issues

Assuming on the fresh install of Win11 that you're on 23H2.

If that's the case, you may try clicking on the `Config` tab and selecting `WinGet Reinstall`. This attempts to fix the oopsie that Microsoft created.

If that doesn't work (for whatever reason), you can attempt to reinstall WinGet manually.

**Comment by viktailor** [comment]
> > **Describe the bug** After selecting application(s) to install, the tool produces a 'Done' dialogue box indicating the application(s) has been installed but the application doesn't install
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Open Tool (via Terminal (admin))
> > 2. In the Install tab, select application(s) to install (is an issue whether I attempt to install 1 or multiple applications)
> > 3. Click 'Install Selection'
> > 4. Get a 'Done' message and 'Installs Have Finished' on Terminal window
> > 5. Application(s) have not been installed and cannot be found on OS
> > 
> > **Expected behavior** Application(s) to have installed
> > **Screenshots** Select applications ![image](https://private-user-images.githubusercontent.com/78094095/288037706-ca6d2da9-f4e3-422e-a307-c8cc86111fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODc1MTcsIm5iZiI6MTcwMTc4NzIxNywicGF0aCI6Ii83ODA5NDA5NS8yODgwMzc3MDYtY2E2ZDJkYTktZjRlMy00MjJlLWEzMDctYzhjYzg2MTExZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0NDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NWMzNTM0N2M4NzljZjA1MzFjZGQxZjljYmI3N2U1NjQzYjYyMzY5ZmVmOWRmZDBiYmE3NDhmYWE0ZTYzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZeyZKs_9qH9tQncxSAsegbUEmvdCHR9ZkEY5EWP-9Q)
> > Install Selection ![image](https://private-user-images.githubusercontent.com/78094095/288038231-cf8e19b5-75fd-4590-b29a-8d916fc75183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODc1MTcsIm5iZiI6MTcwMTc4NzIxNywicGF0aCI6Ii83ODA5NDA5NS8yODgwMzgyMzEtY2Y4ZTE5YjUtNzVmZC00NTkwLWIyOWEtOGQ5MTZmYzc1MTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0NDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMmZiNGI4NWJiZjY2MWU2YjI5YTBkZjc2MmFlNjkxZTY1Y2ZkMTkwZDZlZmJiYWI5NjU3YzAzZGY2MDM3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J5hXi8JTvhK1SjzJvyWhHH-0FLMg7YPlxjuxBU369Ro)
> > Terminal Success Message ![image](https://private-user-images.githubusercontent.com/78094095/288038577-348c350a-9672-474f-b83f-8a8f5eae695e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODc1MTcsIm5iZiI6MTcwMTc4NzIxNywicGF0aCI6Ii83ODA5NDA5NS8yODgwMzg1NzctMzQ4YzM1MGEtOTY3Mi00NzRmLWI4M2YtOGE4ZjVlYWU2OTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE0NDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDk2MTUwZTgyMWVjZTc1ODQwNzVkN2NkYzM2YTFkMzgxZjU3Mzg2OGZjMTkyOTk4M2UyZGQ4NDFjOTZmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zrk6YFvvgYjreva4ICBdW0dYd0JsSKl2dZqZ3rYA66E)
> > **Additional context** This is the first time I am using the tool so it's likely I'm missing something but I did a fresh Win 11 install and used the tool to debloat and uninstall OneDrive which worked fine. I then tried to use the tool to install applications and is where I ran in to issues
> 
> Assuming on the fresh install of Win11 that you're on 23H2.
> 
> If that's the case, you may try clicking on the `Config` tab and selecting `WinGet Reinstall`. This attempts to fix the oopsie that Microsoft created.
> 
> If that doesn't work (for whatever reason), you can attempt to reinstall WinGet manually.

Thank you so much for the quick reply. Re-installed WinGet from Config tab and that's fixed the issue. Really appreciate your help
