### ISSUE TITLE
error installing windows adk

### ISSUE THREAD

**Issue by eljaouharielmehdi** [ChrisTitusTech/winutil#1252]
every time i try to click on select Iso, a script launches to get the windows ADK but never succeed.
error displayed: 

ERROR: Unable to find 'C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\AMD64\Oscdimg\oscdimg.exe'
The install of windows-adk-oscdimg was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windows-adk-oscdimg\tools\chocolateyinstall.ps1'.
 See log for details

**Comment by riversde** [comment]
Same here... win11 22H2

**Comment by ty802** [comment]
As far as I can tell this does not seem to be an error with winutil.
if you still think it needs to be looked at I do not think you provided enough information to debug this issue.

**Comment by WiNiFiX** [comment]
Unable to find 'C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\AMD64\Oscdimg\oscdimg.exe'

Same issue here

**Comment by WiNiFiX** [comment]
Found the issue: its not looking in C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg\oscdimg.exe for oscdimg.exe, hence not finding it, when it is installed.

**Comment by WiNiFiX** [comment]
https://learn.microsoft.com/en-us/windows-hardware/get-started/adk-install
