### ISSUE TITLE
Remove Chocolatey for Winget Installation

### ISSUE THREAD

**Issue by thesobercoder** [ChrisTitusTech/winutil#1257]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, Chocolatey is used to only install Winget. I think this is not needed, as there are more elegant ways to install Winget, while also ensuring that all system environment variables are populated.

**Describe the solution you'd like**
- Download the latest Winget MSIX bundle from the GitHub release. `https://github.com/microsoft/winget-cli/releases/download/v1.6.3133/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`.
- Run the `Add-AppPackage -path Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle` command to install Winget.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GizmoTheGreen** [comment]
+1.

I kinda feel like installing chocolatey is "bloat".
I want to be able to tell the script to just use winget and not chocolatey but according to consoleoutput it -always- checks for chocolatey and installs it if missing. 

kind of backwards, rather if winget is missing, prompt user and ask if they want to use chocolatey.

**Comment by dreamsyntax** [comment]
You can run this instead to use winutil without installing chocolatey:
`(irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex`
credit: https://github.com/ChrisTitusTech/winutil/issues/1118#issuecomment-1850868015
