### ISSUE TITLE
Can't go can't back to the game after alt tabbing.

### ISSUE THREAD

**Issue by Desoo19** [ChrisTitusTech/winutil#126]
Hey, I appreciate all the work that you've put into this tool, i've been using this since the moment you introduced it and always use it in every new windows install but lately i've been having this issue where after i would run the tool any fullscreen exclusive game and alt+tab but going back to the game won't work as it will stay on the taskbar, the only workaround i've found so far is pressing lalt+enter after clicking the game on taskbar, i'd appreciate if there is any idea into fixing this :)

**Comment by snkdemon** [comment]
> Hey, I appreciate all the work that you've put into this tool, i've been using this since the moment you introduced it and always use it in every new windows install but lately i've been having this issue where after i would run the tool any fullscreen exclusive game and alt+tab but going back to the game won't work as it will stay on the taskbar, the only workaround i've found so far is pressing lalt+enter after clicking the game on taskbar, i'd appreciate if there is any idea into fixing this :)

i fix that by making a new user

**Comment by Desoo19** [comment]
After running the tool on another fresh windows 10 install the issue isn't happening anymore but i'll keep that in mind if the issue occurs again, thanks for the suggestion :)

**Comment by ChrisTitusTech** [comment]
Thanks for the issue, Feel free to reopen this one or make a new one if it pops back up.
