### ISSUE TITLE
Add and Activate Ultimate Performance Profile does not actually Activate

### ISSUE THREAD

**Issue by rand-hall** [ChrisTitusTech/winutil#1260]
**Describe the bug**
The Add and Activate Ultimate Performance Profile code creates the Ultimate Performance plan but does not activate it.  The -setactive command produces this error:

Attempted to write to unsupported setting

**To Reproduce**
Click Add and Activate Ultimate Performance Profile button

**Expected behavior**
The Ultimate Performance plan should be activated.

**Screenshots**

**Additional context**
The /duplicatescheme command duplicates the Ultimate Performance plan template. The GUID of the new duplicate is what you what you want to activate. The current code is attempting activate the plan template GUID.  I believe you are looking for something like this (tested) code:

```
     # Add and enable the power scheme, enable powercfg.cpl access to
     # System Unattended Sleep Timeout, and disable monitor sleep on AC

     powercfg /duplicatescheme $powerSchemeGuid
     $ultimateScheme = powercfg /list | Out-String -Stream | Where-Object { $_ -match $powerSchemeName }
     $newPowerSchemeGuid = ($ultimateScheme -split '\s+')[3]
     powercfg -setactive $newPowerSchemeGuid
     powercfg -attributes SUB_SLEEP 7bc4a2f9-d8fc-4469-b07b-33eb785aaca0 -ATTRIB_HIDE
     powercfg -change -monitor-timeout-ac 0
```

Also, I'm not sure if it's the intention or not, but the -attributes command merely exposes the System Unattended Sleep Timeout in the control panel UI. I.E., it doesn't change it from its 2 minute default.

Also, note that the "disable" Ultimate Performance code will break if you fix the above. It effectively deletes the plan now...but won't successfully delete it if it's currently active. You can't delete the active plan. You'll need to keep track of the prior plan somewhere.

For completeness only, if you want the "disable" function to truly backout changes, you'll want to put the CPL UI back to it's former state and let the monitor timeout.

If I was a young buck instead of someone who hasn't touched code for 25 years, I'd figure out how to use the code repository and rectify this myself. But, alas, I'm old and have better things to do before I die.

**Comment by prosponky** [comment]
here's the corrected code : 



# Predefined GUID for the Ultimate Performance power scheme template
$powerSchemeGuid = "e9a42b02-d5df-448d-aa00-03f14749eb61"

# Duplicate the Ultimate Performance power scheme
powercfg /duplicatescheme $powerSchemeGuid
if ($?) {
    Write-Output "Ultimate Performance power scheme duplicated successfully."
} else {
    Write-Output "Failed to duplicate Ultimate Performance power scheme."
    exit
}

# Get the GUID of the newly created power scheme
$ultimateScheme = powercfg /list | Out-String -Stream | Where-Object { $_ -match "Ultimate Performance" }
$newPowerSchemeGuid = ($ultimateScheme -split '\s+')[3]

# Activate the newly created power scheme
powercfg -setactive $newPowerSchemeGuid
if ($?) {
    Write-Output "Newly created Ultimate Performance power scheme activated successfully."
} else {
    Write-Output "Failed to activate the newly created Ultimate Performance power scheme."
    exit
}

# Make System Unattended Sleep Timeout setting visible in the power options control panel
powercfg -attributes SUB_SLEEP 7bc4a2f9-d8fc-4469-b07b-33eb785aaca0 -ATTRIB_HIDE

# Prevent monitor from sleeping on AC power
powercfg -change -monitor-timeout-ac 0
if ($?) {
    Write-Output "Monitor sleep on AC power disabled successfully."
} else {
    Write-Output "Failed to disable monitor sleep on AC power."
}
