### ISSUE TITLE
oscdimage not  found on the system

### ISSUE THREAD

**Issue by 13mhz** [ChrisTitusTech/winutil#1266]
**Describe the bug**

**To Reproduce**

**Expected behavior**
While running MicroWin, there is an errorr   saying oscdimage.exe not found
file  is pressent at:
c:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\Oscdimg\
![oscdimg](https://github.com/ChrisTitusTech/winutil/assets/51832182/3cd2bdc6-760e-404b-8c34-967817c1354a)

**Screenshots**

**Additional context**
this is 23h2,  upgraded from  w10 22h2

**Comment by 13mhz** [comment]
![Zrzut ekranu 2023-12-07 032925](https://github.com/ChrisTitusTech/winutil/assets/51832182/39fd8d35-4cb5-41a9-9cb8-2e3d1f24b90a)

**Comment by 13mhz** [comment]
![Zrzut ekranu 2023-12-07 033020](https://github.com/ChrisTitusTech/winutil/assets/51832182/227a0f3c-a014-48fa-afde-ad0707e3aece)

**Comment by munkk01** [comment]
What happens when you run this in your PowerShell prompt?
```powershell
Get-Command -Type Application oscdimg
```

As an example of what you should hope to see:
![image](https://github.com/ChrisTitusTech/winutil/assets/152475628/d4722a16-7b82-4082-acc9-c3dbf7179bbf)

**Comment by tezpadhye** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/50453172/2d115936-d786-40ea-9a00-0f3f8a7e18c8)
im getting this error while it installs ADK.

**Comment by 13mhz** [comment]
![Zrzut ekranu 2023-12-07 204227](https://github.com/ChrisTitusTech/winutil/assets/51832182/9c57be7d-0a79-4865-88ff-8a984bbdae27)
Not that lucky unfortunately...

**Comment by PowerCoder** [comment]
Basically the same as #1269.

> Not that lucky unfortunately...
Try `Get-Command -Type Application 'oscdimg.exe'`
That might work.

If it does, Mr. Munkk knows which line to edit. :)

**Comment by KonTy** [comment]
@PowerCoder did one of you guys raise a PR for this? Or do you want me to do it so you can also test it? 

@ChrisTitusTech I really think we should rethink this whole pulling down ADK, I know it is the safest from the perspective of "getting the legit binary" but it might be better to just check in that binary into the git repo with SHA256 and download it from there, or BASE64 it right into the winutil.ps1

**Comment by munkk01** [comment]
> @PowerCoder did one of you guys raise a PR for this? Or do you want me to do it so you can also test it?
> 
> @ChrisTitusTech I really think we should rethink this whole pulling down ADK, I know it is the safest from the perspective of "getting the legit binary" but it might be better to just check in that binary into the git repo with SHA256 and download it from there, or BASE64 it right into the winutil.ps1

I have not raised a PR for this. I have been AFK all weekend. I haven't dealt with this behavior myself so I still need to test it to ensure a proper PR to fix it. I won't be able to look until tomorrow sometime.

**Comment by rocobruno** [comment]
Not sure if I'm adding new information here but it seems that there is an obvious typo. The script calls for oscdimg**e** instead of oscdimg.
![Capture3](https://github.com/ChrisTitusTech/winutil/assets/69468830/64e692da-6f6b-4f06-8748-1ec04f84b7d5)
![Capture1](https://github.com/ChrisTitusTech/winutil/assets/69468830/963ec8f7-35c8-4e21-96b7-95cb8e92ba1d)
![Capture2](https://github.com/ChrisTitusTech/winutil/assets/69468830/c73514e8-9e4a-4010-abfc-d8e9c29e8533)
Therefore, the process abort. Should be an easy one to fix.

**Comment by munkk01** [comment]
> Not sure if I'm adding new information here but it seems that there is an obvious typo. The script calls for oscdimg**e** instead of oscdimg. ![Capture3](https://private-user-images.githubusercontent.com/69468830/289905854-64e692da-6f6b-4f06-8748-1ec04f84b7d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTQxMzksIm5iZiI6MTcwMjM5MzgzOSwicGF0aCI6Ii82OTQ2ODgzMC8yODk5MDU4NTQtNjRlNjkyZGEtNmY2Yi00ZjA2LTg3NDgtMWVjMDRmODRiN2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE1MTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ODZlZDBkNzczMzAzZWM3MGQwNzY1YTk1NjNkMmY2YTk1YjRmNmMwM2RjM2NmOWNkZjI4MTlkMGI5MTgzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ll-GcBHab5huZr2uVXyyWWrN_aS8e1GKMaPBm3Evv4) ![Capture1](https://private-user-images.githubusercontent.com/69468830/289906621-963ec8f7-35c8-4e21-96b7-95cb8e92ba1d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTQxMzksIm5iZiI6MTcwMjM5MzgzOSwicGF0aCI6Ii82OTQ2ODgzMC8yODk5MDY2MjEtOTYzZWM4ZjctMzVjOC00ZTIxLTk2YjctOTVjYjhlOTJiYTFkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE1MTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MzhmNzBiZGI4NDhjMmYwZWQ3M2ZjZDU2ZjFiY2M3MTlkM2E2ODBjMjA0ZDAxNjQyZTAyNTAxZmRhMDllNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vp7G58EWHx_96wYDtpjDrWTVr071JsdanwQbfawTcEM) ![Capture2](https://private-user-images.githubusercontent.com/69468830/289906651-c73514e8-9e4a-4010-abfc-d8e9c29e8533.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTQxMzksIm5iZiI6MTcwMjM5MzgzOSwicGF0aCI6Ii82OTQ2ODgzMC8yODk5MDY2NTEtYzczNTE0ZTgtOWU0YS00MDEwLWFiZmMtZDhlOWMyOWU4NTMzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE1MTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYzM1NTc2NGRjYWI5YTdjMzIxOWVlNDQ5M2E1YmYxMGIzYWVlZjA3ZGI4ZmQ1ZDk5NDUwNWMxODI3YTBkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Huk5cgcoKYIctpKdvFdLhQ79EN0CykR6Xez91eAylr0) Therefore, the process abort. Should be an easy one to fix.

Those are just print type messages. Shouldn't affect runtime code I don't think. Still should be updated. Thanks!

**Comment by PowerCoder** [comment]
I noticed that as well, figured I'd been complaining enough and probably shouldn't start talking about print typos as well. :)

Haven't been able to test anything, sorry. I'm in the middle of a reinstall of my home workstation. It's how I ended up here in the first place, looking for something to debloat a fresh install with. I need it for work so I haven't been able to test.

**Comment by rocobruno** [comment]
Could be a simple string issue with no impact but incidentally the process abort ritght there for me... ADK is installed and I have choco installed as well. Could it be a language issue ? I'm using a french-canadian Windows version.

**Comment by munkk01** [comment]
> Could be a simple string issue with no impact but incidentally the process abort ritght there for me... ADK is installed and I have choco installed as well. Could it be a language issue ? I'm using a french-canadian Windows version.

Question; does your username have a space in it? Like `C:\Users\roco bruno\`?

**Comment by rocobruno** [comment]
Nope, it is C:\Users\Tech
