### ISSUE TITLE
Install does not install any software despite saying "Installs have finished"

### ISSUE THREAD

**Issue by antirisk** [ChrisTitusTech/winutil#1267]
**Describe the bug**
A brand new Dell Inspiron with a completely clean install of Windows 11 Pro (from Microsoft to replace the OEM setup).  Ran all the windows update and also installed all the Dell Drivers (based on the laptop configuration).

Running CTT does not seem to install anything while giving out success message.  I tried to uninstall things like Edge or OneDrive and those worked fine.  So not sure what the real problem is.

**To Reproduce**
1. Open PowerShell as Adming
2. Running "irm christitus.com/win | iex" or "iwr -useb https://christitus.com/win | iex"
3. Select any program and click "Install"
4. Displays "Done" dialog while displaying "Installs have finished" on the shell

**Expected behavior**
Expect programs to be installed as selected

**Screenshots**

**Additional context**

**Comment by munkk01** [comment]
Assuming you may be on the newest Windows version 23H2.

If that's the case, you may try clicking on the `Config` tab and selecting `WinGet Reinstall`. This attempts to fix the oopsie that Microsoft created.

If that doesn't work (for whatever reason), you can attempt to reinstall WinGet manually.

**Comment by antirisk** [comment]
I did the "Reinstall Winget" and got a successful message. I tried the same steps after the reinstall and the output is exactly the same.  I just get "Winget Already Installed" and "Installs have finished" almost instantly.

**Comment by antirisk** [comment]
Oh well! I spoke too soon. After the reinstall of Winget, I needed to do a reboot.  Thanks for the help and I'm closing this issue now.

**Comment by munkk01** [comment]
> Oh well! I spoke too soon. After the reinstall of Winget, I needed to do a reboot. Thanks for the help and I'm closing this issue now.

The tried and true method for fixing anything, restarting!
