### ISSUE TITLE
Feature Request: Tron script setup & start

### ISSUE THREAD

**Issue by Redo11** [ChrisTitusTech/winutil#127]
So, a [tron script](https://old.reddit.com/r/TronScript/) is a tool to clean the computer from malware and to optimize some sectors of the system.
Would be nice for your tool to be able to download, configure and run tron with an easy GUI.

**Comment by ChrisTitusTech** [comment]
Agreed. I'll put this in for the October cycle to be implemented.

**Comment by Redo11** [comment]
@ChrisTitusTech was this ever added?

**Comment by ghost** [comment]
> [@ChrisTitusTech](https://github.com/ChrisTitusTech) was this ever added?

no we try to minimize the calls to external programs in winutil
