### ISSUE TITLE
microwin image - explorer crash

### ISSUE THREAD

**Issue by Avatarsia** [ChrisTitusTech/winutil#1276]
i used the microwin ti generate a new image for win11 pro
i only kept defender and add no drivers
after check the image on a vmware the installation run fine.
but when i try to open the disk in the explorer, the explorer keeps crashing
i tried to check the event manager, but the event manager ist not working ether, also not possible to start manually (wanted that way?)
edit: all driver were found from the beginning, also internet connection worked just fine

**Comment by cproie** [comment]
Confirming the same.  First time using and thought I was doing something wrong.  Explorer hangs, download a file and says it completes but not shown in the download folder.

**Comment by KonTy** [comment]
@Avatarsia @cproie could you guys please try this new version to see if it fixes your issues?

This PR includes:
1. Fix for explorer crash/hang. (I can't verify since I can't repro this)
2. Wifi fix  for laptops
3. First attempt at pure white theme (by popular demand)
4. Some other bug fixes for Microwin

Issues: #1276, #1272

``` powershell
iwr -useb https://raw.githubusercontent.com/KonTy/winutil/test-2023-11-30/winutil.ps1 | iex
```

**Comment by Avatarsia** [comment]
might be a stupid question.
![image](https://github.com/ChrisTitusTech/winutil/assets/43354003/baa34030-c91c-49e6-bbbc-3e3531685f35)
this should be we in a different direction to show thats its actually done no ? 

also during this test now i would have 2 FR request. 
to give the possibility to choose a target folder for the final iso and the possibility to give it a name (i accedently choose the home version and when i restart it during using the image in the vm the 2nd process of course failed so i needed to repeat it once more

Home version worked
Pro version also works
but funfact, the installation of the home version needs 20 times longer then the pro version :D

**Comment by etherwrangler** [comment]
@KonTy had the same issue today.  Resolved it by starting the EventLog service and setting it to Automatic.  I'd suggest removing that one from your script.

I got to looking deeper at the services that MicroWin-Helper.ps1 disables and there are several that the winutil script leave automatic that it disables.  Would it be better to make them match or add some sort of toggle to the page allowing the user to pick how stripped down they'd like to make the system?

**Comment by KonTy** [comment]
@etherwrangler thank you for debugging it and finding this issue. I'm not sure why you are still seeing this. I disabled "setting services to menual" 3 weeks ago or so, not sure if Chris pulled it in or not, I'm not following hie release time line. To your comment about matching to winutil, that's exactly what the plan is. Basically what I want to do is add a new capability to winutil to read config file and install all the tweaks and apps that people exported into the config file. We need several things for that to happen:
1. Introduce a command line switch to winutil that would run all the tweaks and apps from a config file that was passed to it
2. Make Export Config file to be global and not per page, right now tweak and apps create 2 separate configs
3. in tweaks page turn all the toggles into check boxes that you check and would take effect after you press apply tweaks (for example dark theme toggle would be a check box). This would allow that capability in the first point to work properly. 

I'm not sure when I will be able to get to this though, as winutil is not my priority atm :)

**Comment by tameous** [comment]
@KonTy I used microwin yesterday, EventLog was still disabled. I don't know if @ChrisTitusTech pulled your fix, but I thought that you may want to know it still doesn't work.

Anyway, keep up the good work! :)

**Comment by KonTy** [comment]
@tameous @CodingWonders maybe it got messed up during this complicated merge recently? We should probably disable this functionality until we make proper fixes.  let me see real quick

**Comment by tameous** [comment]
Here you are

> FirstStartup has worked
> Stopping service AudioEndpointBuilder
> Stopping service Audiosrv
> Stopping service BFE
> Stopping service BITS
> Stopping service BrokerInfrastructure
> Stopping service cbdhsvc_e3803
> Stopping service CDPSvc
> Stopping service CDPUserSvc_e3803
> Stopping service CoreMessagingRegistrar
> Stopping service CryptSvc
> Stopping service DcomLaunch
> Stopping service Dhcp
> Stopping service DiagTrack
> Stopping service DispBrokerDesktopSvc
> Stopping service Dnscache
> Stopping service DoSvc
> Stopping service DPS
> Stopping service DusmSvc
> Stopping service edgeupdate
> Stopping service EventLog
> Stopping service EventSystem
> Stopping service FontCache
> Stopping service gpsvc
> Stopping service iphlpsvc
> Stopping service LanmanServer
> Stopping service LanmanWorkstation
> Stopping service LSM
> Stopping service MapsBroker
> Stopping service mpssvc
> Stopping service nsi
> Stopping service OneSyncSvc_e3803
> Stopping service Power
> Stopping service ProfSvc
> Stopping service RpcEptMapper
> Stopping service RpcSs
> Stopping service RstMwService
> Stopping service SamSs
> Stopping service Schedule
> Stopping service SENS
> Stopping service ShellHWDetection
> Stopping service Spooler
> Stopping service sppsvc
> Stopping service StateRepository
> Stopping service StorSvc
> Stopping service SysMain
> Stopping service SystemEventsBroker
> Stopping service TextInputManagementService
> Stopping service Themes
> Stopping service TrkWks
> Stopping service UserManager
> Stopping service UsoSvc
> Stopping service Wcmsvc
> Stopping service webthreatdefusersvc_e3803
> Stopping service WinDefend
> Stopping service Winmgmt
> Stopping service WpnService
> Stopping service WpnUserService_e3803
> Stopping service wscsvc
> Stopping service WSearch

**Comment by KonTy** [comment]
@tameous ok I think I found the problem any change you could create a new Microwin with this new version to see if it kills EventLog? I can't test atm myself and too tired it's 3am here

``` PowerShell
iwr -useb https://raw.githubusercontent.com/KonTy/winutil/LinksAndPerf/winutil.ps1 | iex
```

**Comment by tameous** [comment]
I have another reinstall on my tasklist, so I will check it, not sure if it will be today, tommorow or in next week, but I will let you know.

**Comment by tameous** [comment]
@KonTy I've just did fresh install using microwin from your link
EventLog starts automatically, here you can see LogFirstRun.txt

> FirstStartup has worked
> Stopping service AarSvc_c1a44
> Stopping service AJRouter
> Stopping service ALG
> Stopping service AppIDSvc
> Stopping service Appinfo
> Stopping service AppReadiness
> Stopping service AppXSvc
> Stopping service autotimesvc
> Stopping service AxInstSV
> Stopping service BcastDVRUserService_c1a44
> Stopping service BDESVC
> Stopping service BluetoothUserService_c1a44
> Stopping service BTAGService
> Stopping service BthAvctpSvc
> Stopping service bthserv
> Stopping service camsvc
> Stopping service CaptureService_c1a44
> Stopping service cbdhsvc_c1a44
> Stopping service CDPUserSvc_c1a44
> Stopping service CertPropSvc
> Stopping service ClipSVC
> Stopping service CloudBackupRestoreSvc_c1a44
> Stopping service COMSysApp
> Stopping service ConsentUxUserSvc_c1a44
> Stopping service CredentialEnrollmentManagerUserSvc_c1a44
> Stopping service dcsvc
> Stopping service defragsvc
> Stopping service DeviceAssociationBrokerSvc_c1a44
> Stopping service DeviceAssociationService
> Stopping service DeviceInstall
> Stopping service DevicePickerUserSvc_c1a44
> Stopping service DevicesFlowUserSvc_c1a44
> Stopping service DevQueryBroker
> Stopping service diagnosticshub.standardcollector.service
> Stopping service diagsvc
> Stopping service DiagTrack
> Stopping service DisplayEnhancementService
> Stopping service DmEnrollmentSvc
> Stopping service dmwappushservice
> Stopping service dot3svc
> Stopping service DsmSvc
> Stopping service DsSvc
> Stopping service EapHost
> Stopping service edgeupdatem
> Stopping service EFS
> Stopping service embeddedmode
> Stopping service EntAppSvc
> Stopping service fdPHost
> Stopping service FDResPub
> Stopping service fhsvc
> Stopping service FrameServer
> Stopping service FrameServerMonitor
> Stopping service GameInputSvc
> Stopping service GraphicsPerfSvc
> Stopping service hidserv
> Stopping service HvHost
> Stopping service icssvc
> Stopping service IKEEXT
> Stopping service InstallService
> Stopping service InventorySvc
> Stopping service IpxlatCfgSvc
> Stopping service KeyIso
> Stopping service KtmRm
> Stopping service lfsvc
> Stopping service LicenseManager
> Stopping service lltdsvc
> Stopping service lmhosts
> Stopping service LxpSvc
> Stopping service McpManagementService
> Stopping service MessagingService_c1a44
> Stopping service MicrosoftEdgeElevationService
> Stopping service MixedRealityOpenXRSvc
> Stopping service MSDTC
> Stopping service MSiSCSI
> Stopping service msiserver
> Stopping service NaturalAuthentication
> Stopping service NcaSvc
> Stopping service NcbService
> Stopping service NcdAutoSetup
> Stopping service Netlogon
> Stopping service Netman
> Stopping service netprofm
> Stopping service NetSetupSvc
> Stopping service NetTcpPortSharing
> Stopping service NgcCtnrSvc
> Stopping service NgcSvc
> Stopping service NlaSvc
> Stopping service NPSMSvc_c1a44
> Stopping service OneSyncSvc_c1a44
> Stopping service p2pimsvc
> Stopping service p2psvc
> Stopping service P9RdrService_c1a44
> Stopping service PcaSvc
> Stopping service PenService_c1a44
> Stopping service perceptionsimulation
> Stopping service PerfHost
> Stopping service PhoneSvc
> Stopping service PimIndexMaintenanceSvc_c1a44
> Stopping service pla
> Stopping service PlugPlay
> Stopping service PNRPAutoReg
> Stopping service PNRPsvc
> Stopping service PolicyAgent
> Stopping service PrintWorkflowUserSvc_c1a44
> Stopping service PushToInstall
> Stopping service QWAVE
> Stopping service RasAuto
> Stopping service RasMan
> Stopping service RemoteAccess
> Stopping service RemoteRegistry
> Stopping service RetailDemo
> Stopping service RmSvc
> Stopping service RpcLocator
> Stopping service RstMwService
> Stopping service ScDeviceEnum
> Stopping service SCPolicySvc
> Stopping service SDRSVC
> Stopping service seclogon
> Stopping service SecurityHealthService
> Stopping service SEMgrSvc
> Stopping service SensorDataService
> Stopping service SensorService
> Stopping service SensrSvc
> Stopping service SessionEnv
> Stopping service SharedAccess
> Stopping service SharedRealitySvc
> Stopping service shpamsvc
> Stopping service smphost
> Stopping service SmsRouter
> Stopping service SNMPTrap
> Stopping service spectrum
> Stopping service SSDPSRV
> Stopping service SstpSvc
> Stopping service StateRepository
> Stopping service StiSvc
> Stopping service StorSvc
> Stopping service svsvc
> Stopping service swprv
> Stopping service TapiSrv
> Stopping service TermService
> Stopping service TieringEngineService
> Stopping service TimeBrokerSvc
> Stopping service TokenBroker
> Stopping service TroubleshootingSvc
> Stopping service TrustedInstaller
> Stopping service tzautoupdate
> Stopping service UdkUserSvc_c1a44
> Stopping service UmRdpService
> Stopping service UnistoreSvc_c1a44
> Stopping service upnphost
> Stopping service UserDataSvc_c1a44
> Stopping service UsoSvc
> Stopping service VacSvc
> Stopping service VaultSvc
> Stopping service vds
> Stopping service vmicguestinterface
> Stopping service vmicheartbeat
> Stopping service vmickvpexchange
> Stopping service vmicrdv
> Stopping service vmicshutdown
> Stopping service vmictimesync
> Stopping service vmicvmsession
> Stopping service vmicvss
> Stopping service VSS
> Stopping service W32Time
> Stopping service WaaSMedicSvc
> Stopping service WalletService
> Stopping service WarpJITSvc
> Stopping service wbengine
> Stopping service WbioSrvc
> Stopping service wcncsvc
> Stopping service WdiServiceHost
> Stopping service WdiSystemHost
> Stopping service WdNisSvc
> Stopping service WebClient
> Stopping service webthreatdefsvc
> Stopping service webthreatdefusersvc_c1a44
> Stopping service Wecsvc
> Stopping service WEPHOSTSVC
> Stopping service wercplsupport
> Stopping service WerSvc
> Stopping service WFDSConMgrSvc
> Stopping service WiaRpc
> Stopping service WinHttpAutoProxySvc
> Stopping service WinRM
> Stopping service wisvc
> Stopping service wlidsvc
> Stopping service wlpasvc
> Stopping service WManSvc
> Stopping service wmiApSrv
> Stopping service workfolderssvc
> Stopping service WpcMonSvc
> Stopping service WPDBusEnum
> Stopping service WpnUserService_c1a44
> Stopping service wuauserv
> Stopping service WwanSvc
> Stopping service XblAuthManager
> Stopping service XblGameSave
> Stopping service XboxGipSvc
> Stopping service XboxNetApiSvc

I've had another problem. While first login I had black desktop and opened file explorer. Starting explorer.exe didn't help, just opened another file explorer. I had to restart the PC and now it works normally. I will try to reinstall it again to check if it will occur again, but not sure if it will be today or tuesday.

**Comment by tameous** [comment]
I'm not sure if I should continue here or make a new threat.
So i reinstalled it. It was black again. Couldn't make a screenshot so here you can see a photo.
![IMG_20240105_140645](https://github.com/ChrisTitusTech/winutil/assets/62503094/ba0304f6-5dca-473b-a53f-c2fdf3716e7c)
I left it for a while and it loaded full desktop environment. But I couldn't open Task Manager or Services. I wanted to try if I can open any app and Edge was working normally.
After reboot I can open those apps.

**Comment by CodingWonders** [comment]
> I'm not sure if I should continue here or make a new threat. So i reinstalled it. It was black again. Couldn't make a screenshot so here you can see a photo. ![IMG_20240105_140645](https://private-user-images.githubusercontent.com/62503094/294503401-ba0304f6-5dca-473b-a53f-c2fdf3716e7c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Njg5NTYsIm5iZiI6MTcwNDQ2ODY1NiwicGF0aCI6Ii82MjUwMzA5NC8yOTQ1MDM0MDEtYmEwMzA0ZjYtNWRjYS00NzNiLWE1M2YtYzJmZGYzNzE2ZTdjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE1MzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MmNjYmNiM2VhZjNmMzBiYTk1OThiYWY2MWNjOTI5MmM0ZTViYTQzOTAwM2I2Mzk4ODRmMmNiNzAwNDJmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rsKoSgIlQW8lGhoaON2dV8N0i8lIFlJ10qsu49jejoQ) I left it for a while and it loaded full desktop environment. But I couldn't open Task Manager or Services. I wanted to try if I can open any app and Edge was working normally. After reboot I can open those apps.

This could be Windows acting up a bit. If you're able to open applications after some reboots, I guess it could be fine. I'll try this though to see if this is an isolated case or if it happens every time.

**Comment by CodingWonders** [comment]
@tameous, I couldn't get it to replicate on my test machine. After (manually) running the FirstRun script, I was greeted by a usable system. All applications ran on the first try.

I've used the latest version of Windows 11 (23H2, English International).

![Windows 11 x64-2024-01-05-19-11-25](https://github.com/ChrisTitusTech/winutil/assets/101426328/045e7bb0-23ca-4a5a-8142-ae08a8c0f5b6)

That doesn't mean it may not have problems though. Others might check that out.
