### ISSUE TITLE
MicroWin issue - Windows 11 - Media Creation Tool

### ISSUE THREAD

**Issue by bhatiak2050** [ChrisTitusTech/winutil#1277]
**Describe the bug**
Error: "install wim file doesn't exist in the image, are you sure you used Windows image??"

**To Reproduce**
1. Go to https://www.microsoft.com/en-in/software-download/windows11
2. Download "Media Creation Tool". File: MediaCreationTool_Win11_23H2.exe
3. Follow the steps to create a ISO image called Windows.iso, save somewhere.
4. Launch winutil in admin shell and load Windows.iso into MicroWin.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/20334649/813df9fa-7dc5-4043-9664-a4b3e5dbf8df)

**Additional context**
I cannot directly download an ISO from the link above due to the error below:
![image](https://github.com/ChrisTitusTech/winutil/assets/20334649/8e64046b-a43a-4a2b-bbed-c8152974d90e)

**Comment by KonTy** [comment]
@bhatiak2050 it seems that Media Creation tool create final image with install.wim in it. Not sure exectly but the structure of that Iso is different.

**Comment by bhatiak2050** [comment]
Okay, Thank you for your reply. That would mean that this method doesn't work currently.

On another note: I realised that the reason I couldn't directly download the iso was due to interference from my private DNS blocker. Upon removing it I could download the international win11 iso and successfully create a microwin.iso file.
