### ISSUE TITLE
script not installing programs.

### ISSUE THREAD

**Issue by lucid-codr** [ChrisTitusTech/winutil#1278]
**Describe the bug**
When trying to install selected programs with the "install selected" button in Winget's category, the program just checks if Winget is installed ("Checking if Winget is Installed..."), if it does it will say "Winget Already Installed". Then it will say installs are finished with nothing installed. I have a fresh Windows 11 home install.

**To Reproduce**
1. Go to the 'Install' tab
2. Select a few programs.
3. Click "Install selected"

**Expected behavior**
Programs get installed (displayed in the console ) and a dialog box appears saying installs are done.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/106444010/ce37aad4-16e7-4a78-9bb5-4d7ac72260eb)
![image](https://github.com/ChrisTitusTech/winutil/assets/106444010/efecc472-5261-4cda-b52d-1b4336cf7a5d)

**Additional context**
All the tweaks work just fine. I tried something other than "discord" as well but it still didn't work.

I apologize in advance if anything is not clear enough.

**Comment by munkk01** [comment]
Assuming you may be on the newest Windows version 23H2.

If that's the case, you may try clicking on the `Config` tab and selecting `WinGet Reinstall`. This attempts to fix the oopsie that Microsoft created.

If that doesn't work (for whatever reason), you can attempt to reinstall WinGet manually.
