### ISSUE TITLE
Feature Request : Tweaks - add a profile for VM ( additionally to Desktop, Laptop and Minimal )

### ISSUE THREAD

**Issue by NaejJao** [ChrisTitusTech/winutil#128]
**Is your feature request related to a problem? Please describe.**
When installing Windows 10/11 into a VM,
a lot of services are not needed,
it would be nice to have a predefined tweak for VMs as well

**Describe the solution you'd like**
Add profile for VM installations

**Comment by ChrisTitusTech** [comment]
I'll do this because I run Windows in VM more often than bare metal.

**Comment by postnick** [comment]
Any update on this? I see it's on your Nov 2022 roadmap. I also use windows in a VM more than on bare metal.
