### ISSUE TITLE
Unable to use micro win

### ISSUE THREAD

**Issue by Nitmaire** [ChrisTitusTech/winutil#1283]
![Screenshot (1)](https://github.com/ChrisTitusTech/winutil/assets/90955769/fba9ceee-7da5-4589-908c-4e37c5d4b3ca)
unable to figure out the issue

**Comment by munkk01** [comment]
> ![Screenshot (1)](https://private-user-images.githubusercontent.com/90955769/290461373-fba9ceee-7da5-4589-908c-4e37c5d4b3ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzA5NjMsIm5iZiI6MTcwMjU3MDY2MywicGF0aCI6Ii85MDk1NTc2OS8yOTA0NjEzNzMtZmJhOWNlZWUtN2RhNS00NTg5LTkwOGMtNGUzN2M1ZDRiM2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE2MTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOGRjNmVhODFmZGY4MDQwZDY4NzFiZjE2ODU5OTBkMzhlZDc3OTNhZDViZGEwMzE4YmIxYWYyMWI3YWQzZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UNWXyA7dz4lcoIdWb_GiWnmLP6KdFLQqGwo7B1h8Vqc) unable to figure out the issue

What ISO are you using?

**Comment by Nitmaire** [comment]
I got the iso from the windows media creation tool

**Comment by bhatiak2050** [comment]
https://github.com/ChrisTitusTech/winutil/issues/1277

**Comment by KonTy** [comment]
@Nitmaire as the guys mentioned above please do not use Media Create Tool. It creates a final image which is not modifiable by the tool. Also do not use shady images off the internet always use Microsoft official images. Mark, wrote up an awesome article how to get ISOs if you don't see the download button [Here](https://www.techrepublic.com/article/how-to-download-a-windows-10-iso-file-without-using-the-media-creation-tool/)
