### ISSUE TITLE
remove thorium

### ISSUE THREAD

**Issue by gurdio** [ChrisTitusTech/winutil#1284]
https://github.com/Alex313031/thorium/issues/463

https://github.com/Alex313031/thorium/issues/463#issuecomment-1854842392

https://github.com/Alex313031/thorium/issues/463#issuecomment-1852649768

**Comment by Avatarsia** [comment]
they already said they will remove that, so why remove it ?

**Comment by munkk01** [comment]
> they already said they will remove that, so why remove it ?

High level:
1. Chris may not want the association to it at this time but he certainly doesn't have to approve the request. 
2. If that existed, what else may exist that hasn't been identified?
3. Who's to say something else wouldn't be added later?
4. Of all things to make an "easter egg," that's what was seen as an "option?"

I just created the pull request to allow Chris the opportunity to just simply approve it and merge it if he sees fit. 

I can say personally, I wouldn't use this product or anything else from the developer for the reasons above.

**Comment by meenbeese** [comment]
> I can say personally, I wouldn't use this product or anything else from the developer for the reasons above. 

I completely agree, no sane person would like to associate themselves with this mess, and the people who try to dismiss it are highly dubious at best, and morally wrong at worst. I'm sure Chris would agree with this as well.

**Comment by NonVolatileHuman** [comment]
@munkk01 @gurdio All three links have been deleted, what was/were the issue/s?

**Comment by munkk01** [comment]
> @munkk01 @gurdio All three links have been deleted, what was/were the issue/s?

I won't go into detail but what I will do is provide a single link to a reddit post that contains various information around it.

https://www.reddit.com/r/browsers/comments/18ihls8/dont_use_thorium_browser_if_you_have_it_installed/
