### ISSUE TITLE
Feature Request: Remove Microsoft Edge and Internet Explorer

### ISSUE THREAD

**Issue by Fantom-Decepticon** [ChrisTitusTech/winutil#129]
**Is your feature request related to a problem? Please describe.**
Include an option to remove Microsoft Edge and Internet Explorer.

**Describe the solution you'd like**
I don't really know how to fully remove Microsoft Edge, but there's a running bug (at least in Windows 10 LTSC 2019), where removing Microsoft Edge via Control Panel leaves some stuff behind, for example the icon in the start menu. But you can fully remove Internet Explorer in Control Panel, and if was an option in the tool aswell that would be handy.

**Comment by Hellements** [comment]
you can use edge removal from here: https://github.com/AveYo/fox
i use it and works good :)

**Comment by ChrisTitusTech** [comment]
Added @Hellements referenced script to Tweaks page in #240
