### ISSUE TITLE
Requesting for a "toggle button" to disable System restore point

### ISSUE THREAD

**Issue by Ironfist69** [ChrisTitusTech/winutil#1292]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I run any Tweaks, it always creating a system restore point (Even if I don't want to create a restore point)

**Describe the solution you'd like**
It should have a **Toggle button** to enable/disable the creation of system restore point. By default, it should be ENABLED (toggled ON for normies), but there should be a button for a power user like me who don't want to create restore point each and every time after running tweaks. System restore points are annoying, like a cancer cell which grows rapidly, it just ruins my SSD's storage space & TBW.

**Describe alternatives you've considered**
NULL

**Additional context**
NULL

**Comment by user-take** [comment]
I also had this same issue. I disabled system restore using group policy and now the app works without creating restore point.
