### ISSUE TITLE
microwin dont detect oscdimge

### ISSUE THREAD

**Issue by ElPichiii** [ChrisTitusTech/winutil#1296]
I used the tool literally less than 2 hours ago, and now i try to use it but it say that i dont have oscdimge installed, i click install, but it does nothing

**Comment by EnterTech8** [comment]
download oscdimg.exe from winutil/releases and place it in your temp folder C:\Users\***\AppData\Local\Temp\
That solved the issue for me

**Comment by ElPichiii** [comment]
bro i love you, problem solved
