### ISSUE TITLE
Feature Request: Batch run or command line parameter

### ISSUE THREAD

**Issue by TGVirus** [ChrisTitusTech/winutil#130]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm lazy, so I would like a way to run your script with a specific config in one go. Either a config file as parameter, or even a set of command line arguments for fast one-click run.

**Describe alternatives you've considered**
Stripping the code and basically making a list of functions i want to run in sequence, but I'm no powershell expert.

**Additional context**
I work with a lot of systems that are set up in all sorts of ways and configs. Also a lot of brand new win installs for app testing purposes.
A lot of times i found out that running your script with a specific configuration like install notepad++ and google, running desktop mode and resetting updates to <recommended> saves me a lot of headache by restoring windows to at least some form of known configuration.
Plus, it might make it easier for deployments or domain policies as well :)

**Comment by ChrisTitusTech** [comment]
We actually have some variable implementation in #94 Merge. This isn't fully baked but something that we are working towards.

**Comment by ChrisTitusTech** [comment]
Closing this duplicate and keep earlier issue #51 referencing this.
