### ISSUE TITLE
Microwin ISO Mounting

### ISSUE THREAD

**Issue by Ou2seyne** [ChrisTitusTech/winutil#1302]
**Describe the bug**
Can able to create a custom windows 11 iso from MicroWin.

**To Reproduce**
1. Go to '.chris titus Winutil'
2. Click on 'MicroWin and check « Download oscdimg.exe from CTT GitHub repo »'
3. Wait for the copy of iso, go to UI and check 
-Keep Defender and -Keep Edge (uncheck all others)
5. See error

**Screenshots**

when I use this iso it just install me a normal windows 11 iso without any debloat or app pre installed delete
![IMG_1841](https://github.com/ChrisTitusTech/winutil/assets/154429876/7b8792f1-981d-412f-b1f7-f8f16f9a9c55)
![IMG_1842](https://github.com/ChrisTitusTech/winutil/assets/154429876/76561d96-9af0-4c40-81b9-9baa569b1d22)
![IMG_1843](https://github.com/ChrisTitusTech/winutil/assets/154429876/b510bea2-3b67-423c-8a61-df4c50b9c290)
![image](https://github.com/ChrisTitusTech/winutil/assets/154429876/8dc0ff9f-efad-4c03-b236-7db880ba467e)

**Comment by Be-Alexei** [comment]
I have the same problem

**Comment by kchoxs** [comment]
me too, i have the same problem :/
