### ISSUE TITLE
Scaling on Smaller Resolutions/Monitors.

### ISSUE THREAD

**Issue by NonVolatileHuman** [ChrisTitusTech/winutil#1303]
**Describe the bug**
The title bar is out of the bounds of my monitor, 19 inches, 1366*768.

**To Reproduce**
Opening the WinUtil interface

**Expected behavior**
The UI would scale down to fit into my monitor

**Screenshots**
![Screenshot (28)](https://github.com/ChrisTitusTech/winutil/assets/75540320/fb08fa6c-e872-4815-b701-0ea5636aafa6)

**Comment by MrDisguised** [comment]
+1 
I can confirm. I am facing the same issue here.

**Comment by NonVolatileHuman** [comment]
Issue still not fixed as of Version 24.01.03
