### ISSUE TITLE
MicroWin not mounting ISO

### ISSUE THREAD

**Issue by frogen1** [ChrisTitusTech/winutil#1304]
**Describe the bug**
MicroWin not mounting selected ISO file

**To Reproduce**
1. Go to 'MicroWin'
2. Click on 'Download oscdimg.exe from CTT Github repo'
3. Click on 'Select Windows ISO'
![MicroWin1](https://github.com/ChrisTitusTech/winutil/assets/98778762/8be593d8-ac1a-41bf-af01-1a0e361e7ffe)

![MicroWin3](https://github.com/ChrisTitusTech/winutil/assets/98778762/80898296-a90d-416d-b603-cc0f48d8ffa9)

But if I open a PS window, it mounts fine.

![MicroWin2](https://github.com/ChrisTitusTech/winutil/assets/98778762/8ad83ec6-6410-426a-94fa-66c248b9803f)

**Comment by Lymsleya** [comment]
I get the same error, before update, i couldn't even install Oscdimg but now i face the same error as you W11 without Media Creation Tool from Microsoft

**Comment by Lymsleya** [comment]
> **Describe the bug** MicroWin not mounting selected ISO file
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'MicroWin'
> 2. Click on 'Download oscdimg.exe from CTT Github repo'
> 3. Click on 'Select Windows ISO'
> 4. See error
>    ![MicroWin1](https://private-user-images.githubusercontent.com/98778762/292014986-8be593d8-ac1a-41bf-af01-1a0e361e7ffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDU1NDAsIm5iZiI6MTcwMzk0NTI0MCwicGF0aCI6Ii85ODc3ODc2Mi8yOTIwMTQ5ODYtOGJlNTkzZDgtYWMxYS00MWJmLWFmMDEtMWEwZTM2MWU3ZmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE0MDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYWNlYjg1MjBlMjU5MWM4NTkyNTk3ZjE1Y2I0OTlkNjA0NTA5M2Y3ZTc4ZGE1N2JiZDZjMzRjOTZjODUxZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ds0zbxDlQMtfwhqAzRXN0-N1Um9U7U9_v6WcOW-rwi4)
> 
> ![MicroWin3](https://private-user-images.githubusercontent.com/98778762/292015421-80898296-a90d-416d-b603-cc0f48d8ffa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDU1NDAsIm5iZiI6MTcwMzk0NTI0MCwicGF0aCI6Ii85ODc3ODc2Mi8yOTIwMTU0MjEtODA4OTgyOTYtYTkwZC00MTZkLWI2MDMtY2MwZjQ4ZDhmZmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE0MDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Y2I5NjAzZjI5OWUzNmY2MmU0NzZlNjZlMmU3YjcyNzViYWVkODg0ZTk5Y2U3NDgyNWNkMzFhODc2YTUxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JNLL2cLROKw4Hlxqx7QOqytlpKkeXKpZCjjhP_Gxdn4)
> 
> But if I open a PS window, it mounts fine.
> 
> ![MicroWin2](https://private-user-images.githubusercontent.com/98778762/292015443-8ad83ec6-6410-426a-94fa-66c248b9803f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDU1NDAsIm5iZiI6MTcwMzk0NTI0MCwicGF0aCI6Ii85ODc3ODc2Mi8yOTIwMTU0NDMtOGFkODNlYzYtNjQxMC00MjZhLTk0ZmEtNjZjMjQ4Yjk4MDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE0MDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OTExOTIzNWU3NDJmOTE4YzE4MGE2Zjk3M2U4MDYzYzg4YWQ4Y2U0MDY0NjhhZTIxMTIyZGNhMmJhNmQ3NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q4OYy140IN9k-nVSUWVV1d3Z8uObL8yQ34yPu5GsvWg)

I came back and I found a fix for me may be the same case for you, i had "Microsoft Virtual Drive Emulator" disabled in the device manager, i enabled it back and it fixed the problem and now i can mount it, by disabling this you can't run ISO files.
