### ISSUE TITLE
Microwin: remove hardware requierments from windows 11

### ISSUE THREAD

**Issue by godalming123** [ChrisTitusTech/winutil#1308]
**Is your feature request related to a problem? Please describe.**
The listed features (in the micowin page) do not mention disabling hardware requirements, and I want to be able to use Windows 11 on my old computer without having to trust an untrustworthy ISO

**Describe the solution you'd like**
If this is already implemented, add it to the listed features on winutil, if not, implement it and then add it to the listed features.

**Additional context**
I use arch BTW.

**Comment by NonVolatileHuman** [comment]
You can remove the hardware requirements by downloading the ISO from MS servers from their media creation tool page, then using Rufus to put said ISO on a USB.
There will be an option in the popup that can remove the hardware requirements, I use it myself.

**Comment by godalming123** [comment]
This is still an issue
