### ISSUE TITLE
Feature Request: Restore right click to classic layout

### ISSUE THREAD

**Issue by richardphi1618** [ChrisTitusTech/winutil#131]
**Is your feature request related to a problem? Please describe.**
the windows 11 right click menus for desktop/explorer/taskbar are garbage. I prefer the windows 10 style right click menus

**Describe the solution you'd like**
in the tweaks section have a check box to revert the windows 11 right click menus to the old/more detailed style

**Describe alternatives you've considered**
there are ways to do this manually (How I do it today) but having an option to do that with this tool would be super helpful 
https://www.thewindowsclub.com/get-old-right-click-context-menu-back-on-windows-11

**Additional context**
this is trash:
![image](https://user-images.githubusercontent.com/38547621/190192270-01924e41-75e0-4eaf-a35c-313fa9d19d3f.png)
![image](https://user-images.githubusercontent.com/38547621/190191788-f632b144-e241-498e-b89a-698819791741.png)

this is better:
![image](https://user-images.githubusercontent.com/38547621/190191325-db0b5cea-9fc8-4f63-8079-f7308b8f4f0c.png)
![image](https://user-images.githubusercontent.com/38547621/190191677-c2398a05-bf23-4727-b57b-ab93750064eb.png)

**Comment by Triplesweet** [comment]
https://www.wintips.org/how-to-restore-right-click-context-menu-in-windows-11/
this should do it

**Comment by ChrisTitusTech** [comment]
Oh I am definitely going to add this. I hate the windows 11 context menus. It has been on my list for a while now.

**Comment by ChrisTitusTech** [comment]
Done #240
