### ISSUE TITLE
It is not opening after i launched it once

### ISSUE THREAD

**Issue by Aternos924** [ChrisTitusTech/winutil#1312]
Hello , i have onced opened chris titus tool and now it is not opening again even tho i entered all different commands to open it . what should i do? when i type the command , nothing is happening

**Comment by ThePrinceofCopper** [comment]
I have the same problem. Power Shell and CMD is just blank when trying both .exe and official shortcut both with and without administrator privileges. Thank you in advance!

**Comment by jstack01** [comment]
Works for me now running "irm christitus.com/win | iex" in PowerShell. Maybe a temporary issue with the link or your DNS?

**Comment by ThePrinceofCopper** [comment]
> irm christitus.com/win | iex

You are 100% correct in my case. Tried with a VPN and it worked. So most probably a DNS issue on my side and it also makes sense since I have a new router. Thank you! I consider it solved!
