### ISSUE TITLE
Old File Explorer back on Windows 11

### ISSUE THREAD

**Issue by GabrielBR96** [ChrisTitusTech/winutil#1314]
**Describe the bug**

Hey Chris, Greetings from Brazil.

After using the tool with those options on the images, my File Explorer is back to his Windows 10 version, Without the Tabs e etc.
I've used this combination before but was able to revert the file explorer changes, but this time after trying to re-enable the new File Explorer only broke evertything and i had to reinstall.

**To Reproduce**

1. Use the Tool with those options on the images in Win 11.
2. Open File Explorer
3. Start missing your tabs

**Screenshots**

The options that i've used.

![Page1](https://github.com/ChrisTitusTech/winutil/assets/96817363/2e8d5592-16cd-4049-a65b-98f48c2b483d)
![Page2](https://github.com/ChrisTitusTech/winutil/assets/96817363/eff7836d-a9d2-4cb3-81a0-dc6b26661fc0)

**Additional context**
This time I used the tool and didn't try to re-enable, I'm just waiting 😁

**Comment by GabrielBR96** [comment]
I've selected all the options and tryed the "Undo Selected Tweaks" option. No Result.

And now my File Explorer looks like this

![image](https://github.com/ChrisTitusTech/winutil/assets/96817363/a1f58535-b5a6-4b18-a7ad-b5384763c143)

😁

**Comment by GabrielBR96** [comment]
Windows 10 File Explorer presenting another bug, sometimes if u are exploring your folders, he can just be stuck in one of then, if u try to go back or enter another folder, nothing happens and u have to restart file explorer.

**Comment by Beaverhoosen** [comment]
> Windows 10 File Explorer presenting another bug, sometimes if u are exploring your folders, he can just be stuck in one of then, if u try to go back or enter another folder, nothing happens and u have to restart file explorer.

There is another GitHub Project called Explorer Patcher. It is actively updated. Brings back the the Windows 10 toolbar, solid project and works very well. They are quick to update it with any Windows Updates.

**Comment by GabrielBR96** [comment]
At this point, I just want my Windows 11 Explorer back 😥
But I'll take a look in this Explorer Patcher that u mentioned @Beaverhoosen

**Comment by GabrielBR96** [comment]
@Beaverhoosen Openning this Explorer Patcher fixed my File Explorer, Thank you! The only thing is that I dont know how I remove it or close it, since it dindt install anything, just runs.

**Comment by GabrielBR96** [comment]
Let me re-write my text and now say everything at onde.

@Beaverhoosen Thank You!

For anyone with the same problem, the fix is very simple.
1. Download and Run the Latest Explorer Patcher -> https://github.com/valinet/ExplorerPatcher
2. Check if the File Explorer has been restored
3. Rename the downloaded file from ep_setup.exe to ep_uninstall.exe and run.
4. Accept the uninstaller
5. Restart when finished
