### ISSUE TITLE
Blinking curson on search box

### ISSUE THREAD

**Issue by DjGeNeSiSxx** [ChrisTitusTech/winutil#1319]
it would be very useful if on click on the searchbox on top, a cursor would be blinking to notify the user that the searchbox is activated.

**Comment by jstack01** [comment]
The blinking cursor shows correctly on Windows 10 22H2 with and without dark mode. I am also on PowerShell version 5.1.19041.3803  Maybe an issue with your version of Windows or PowerShell? Or maybe the color of your cursor?

**Comment by DjGeNeSiSxx** [comment]
Woa, maybe, never thought if that. 
 Replying now as a placeholder, will edit comment as soon as I test ,to provide versioning info.
