### ISSUE TITLE
i like to see those apps in winutil

### ISSUE THREAD

**Issue by PoepieFloepie** [ChrisTitusTech/winutil#1322]
speedyfox ,a optimizer for browsers  ----https://crystalidea.com

pdfgear ,a really good free pdf manager -----https://www.pdfgear.com

Easy Context Menu ,where good context menu manager ------https://www.sordum.org/7615/easy-context-menu-v1-6/
this is also the only one that sets it to other languages and not only english if adding a new thing in context menu.

and at last one

explorerpatcher --- windows 10 task in windows 11  the only on that has windows 10 live tiles working ---https://github.com/valinet/ExplorerPatcher

i buyed your app ,big thanks from the netherlands

**Comment by iavorovschi** [comment]
Also add Opera as browser =))))
