### ISSUE TITLE
Error with Invoke-WPFMicrowin

### ISSUE THREAD

**Issue by andreinoue** [ChrisTitusTech/winutil#1328]
**Describe the bug**
Error with Invoke-WPFMicrowin

**To Reproduce**
1. Download Win11_23H2_EnglishInternational_x64v2.iso from https://www.microsoft.com/en-us/software-download/windows11/.
2. Follow Microwin Instructions, selecting Windows 11 Pro as the SKU.
3. Start process.
4. See error.

**Expected behavior**
I expected the process to run with no errors.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/85354782/4024c92e-00c9-4990-ba3f-7a63dab948d2)
![image](https://github.com/ChrisTitusTech/winutil/assets/85354782/2041dee5-98ae-4814-a23f-701b66887f3b)

**Additional context**
I'm currently on a Windows 10 machine, Region is Brazil, User name is André. When the process finishes, I still get a microwin.iso file in my Temp folder, but I don't think it is correct, as its size is 11GB+. Also, when downloading oscdimg.exe from CTT Github repo, I got the same hash error as @DiegcD.

**Comment by juliocoliveira** [comment]
This seems to be fixed already in a Pull Request: https://github.com/ChrisTitusTech/winutil/pull/1313.
You could try to run his version by:
```
irm https://raw.githubusercontent.com/CodingWonders/winutil/CW-MicroWin-AppxFix/winutil.ps1 | iex
```

But you have to build the iso again.
I tested and is working fine with that version.

**Comment by juliocoliveira** [comment]
Or maybe the issue is the accent in your Windows User name account.
You could try create other user account without accents or any special character and try run the toolkit again.

**Comment by andreinoue** [comment]
I will try those out. Thanks a lot!

**Comment by CodingWonders** [comment]
> Or maybe the issue is the accent in your Windows User name account. You could try create other user account without accents or any special character and try run the toolkit again.

I guess that the image unmount process has failed. The process shown in the screenshot above is deleting the files in the Windows image.

We should **really** detect whether the unmount command has succeeded, and if it's not, try again until it succeeds.

**Comment by ChrisTitusTech** [comment]
Should work with main branch now.
