### ISSUE TITLE
cant make an iso

### ISSUE THREAD

**Issue by 1337sense** [ChrisTitusTech/winutil#1330]
**Describe the bug**
Error creating Win11 23h2 

**To Reproduce**
1. Go to 'Microwin'
2. Click on 'select windows iso'
3. Scroll down to 'Win11_23H2_English_x64v2.iso'
4. See error -- Install.wim file doesn't exist in the image, this could happen if you use unofficial Windows images, or a Media creation tool, which creates a final image that can not be modified. Please don't use shady images from the internet, use only official images. Here are instructions how to download ISO images if the Microsoft website is not showing the link to download and ISO. https://www.techrepublic.com/article/how-to-download-a-windows-10-iso-file-without-using-the-media-creation-tool/

**Expected behavior**
I expect to come to a menu to select what features i want

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/80576979/722a02cb-3fa5-4b30-9f0a-13df23ae9ff7)

**Comment by 1337sense** [comment]
in screenshot i was using windows iso from official site
and now i just tried to use it with an iso from https://uupdump.net/ but still i get the same error

**Comment by KonTy** [comment]
From the image above Winutil can not mount the ISO, error code 80070079 typically indicates an issue related to file or data corruption when trying to perform an operation in Windows. In the context of mounting an ISO file, this error might occur if the ISO file is corrupt, incomplete, or if there are issues with the file system.

Have you tried manually mounting it by right clicking it?

**Comment by 1337sense** [comment]
yes i tried to mount it but it also showed an error but i downloaded the iso multiple times to make sure it wasn’t corrupted but it still it didn't work Sent from my iPhoneOn 2 Jan 2024, at 6:50 AM, KonTy ***@***.***> wrote:﻿
From the image above Winutil can not mount the ISO, error code 80070079 typically indicates an issue related to file or data corruption when trying to perform an operation in Windows. In the context of mounting an ISO file, this error might occur if the ISO file is corrupt, incomplete, or if there are issues with the file system.
Have you tried manually mounting it by right clicking it?

**Comment by KonTy** [comment]
@1337sense thank you for confirming that it is not winutil issue. What I suggest is deleting all of the iso file that you are trying to use and try to redownload it with a different software. And before you use it in winutil try to mount and unmount it in Windows to see if it mounts.

**Comment by 1337sense** [comment]
i dont know any place other than official microsoft site and uup dump (both tested and dont work)Sent from my iPhoneOn 2 Jan 2024, at 8:40 PM, KonTy ***@***.***> wrote:﻿
@1337sense thank you for confirming that it is not winutil issue. What I suggest is deleting all of the iso file that you are trying to use and try to redownload it with a different software. And before you use it in winutil try to mount and unmount it in Windows to see if it mounts.
