### ISSUE TITLE
iwr : Unable to connect to the remote server

### ISSUE THREAD

**Issue by Whataressd** [ChrisTitusTech/winutil#1352]
When I try to execute the script, all I get is this:

```
iwr : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by munkk01** [comment]
> When I try to execute the script, all I get is this:
> 
> ```
> iwr : Unable to connect to the remote server
> At line:1 char:1
> + iwr -useb https://christitus.com/win | iex
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> ```

Are you in India by chance?

**Comment by Whataressd** [comment]
> > When I try to execute the script, all I get is this:
> > ```
> > iwr : Unable to connect to the remote server
> > At line:1 char:1
> > + iwr -useb https://christitus.com/win | iex
> > + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
> >    eption
> >     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> > ```
> 
> Are you in India by chance?

No, I'm not in india

**Comment by munkk01** [comment]
> > > When I try to execute the script, all I get is this:
> > > ```
> > > iwr : Unable to connect to the remote server
> > > At line:1 char:1
> > > + iwr -useb https://christitus.com/win | iex
> > > + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > >     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
> > >    eption
> > >     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> > > ```
> > 
> > 
> > Are you in India by chance?
> 
> No, I'm not in india

`irm christitus.com/win | iex`

Does this result in the same message?

**Comment by Whataressd** [comment]
> irm christitus.com/win | iex

Yes, it results in the same message

**Comment by munkk01** [comment]
> > irm christitus.com/win | iex
> 
> Yes, it results in the same message

Hmm you may try to do the same thing that users in India use.

Utilize a VPN to a different location (country more than likely) or attempt changing your DNS server to Google/CloudFlare/etc

**Comment by Whataressd** [comment]
> > > irm christitus.com/win | iex
> > 
> > 
> > Yes, it results in the same message
> 
> Hmm you may try to do the same thing that users in India use.
> 
> Utilize a VPN to a different location (country more than likely) or attempt changing your DNS server to Google/CloudFlare/etc

I used a VPN  but it still didn't fix the issue.
