### ISSUE TITLE
Micro win error but still creating the iso

### ISSUE THREAD

**Issue by lev0x1** [ChrisTitusTech/winutil#1353]
**Describe the bug**
I get a error massage after Microwin is trying to remove Appx Bloat
I have already created several iso and every time I got this error 

**To Reproduce**
1. Go to micro win and select win11 iso (23h2 german in my case)
2. Click on  windows SKU version 5 (Win 11 pro)
3. I did keep the default settings (keep edge and defender)

**Expected behavior**
No error idk what went wrong or if this error is normal.
More in Screenshots.

**Screenshots**

**Additional context**
Will the iso work fine just with the bloatware?

![Screenshot 2024-01-06 185252](https://github.com/ChrisTitusTech/winutil/assets/155789888/efccfa9f-817a-4ceb-bca5-b8a7238185a7)

**Comment by MichTheOcelot** [comment]
Using the regular non microwin iso will give you the bloatware but it will work... i used konty's latest fork of winutil and microwin has given me no issues for 23H2 english and spanish.

https://github.com/KonTy/winutil/blob/LinksAndPerf/winutil.ps1
`iwr -useb https://raw.githubusercontent.com/KonTy/winutil/LinksAndPerf/winutil.ps1 | iex`

**Comment by lev0x1** [comment]
i launched (iwr -useb https://raw.githubusercontent.com/KonTy/winutil/LinksAndPerf/winutil.ps1 | iex) in terminal and it worked without any error massage ty

**Comment by MichTheOcelot** [comment]
@esperx this solution wasnt a permanent fix, the main branch has somewhat caught up to all the vital PRs so you might want to try using this repos script instead.

**Comment by esperx** [comment]
> @esperx this solution wasnt a permanent fix, the main branch has somewhat caught up to all the vital PRs so you might want to try using this repos script instead.

I didn't think this was the end all fix, I've just been having this error for two weeks now.
