### ISSUE TITLE
Install Package: Okular install generates error 0x80190193

### ISSUE THREAD

**Issue by MichTheOcelot** [ChrisTitusTech/winutil#1354]
**Describe the bug**
Trying to install the okular package through winutil generates the error from the title 0x80190193, this issue remains on the latest version 2024/1/12

**To Reproduce**
1. Execute script on powershell as usual
2. Tick the program 'Okular'
3. Press "Install Selected"
4. See error: 
"An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403)."

**Expected behavior**
Okular is installed correctly.

**Screenshots**
![wgnOn8veNN](https://github.com/ChrisTitusTech/winutil/assets/154266029/816d8992-349b-4a14-b7d7-c5060f222ad3)

**Additional context**
On the okular install page it suggests to install through the microsoft store, however im not certain if that is relevant.
Running on Win 10 22H2, 19045.3803 Windows Feature Experience Pack 1000.19053.1000.0
I know the script prompts Okular is already installed, i uninstalled it and the error still appears.

**Comment by DatarkNZ** [comment]
-Winutil is trying to pull okular-23.08.4-1649-windows-cl- msvc2019-x86_64.exe and this is failing with the same error as above 0x80190193 : Forbidden (403). 
-The latest release on jenkins seems to fix this issue. 
https://binary-factory.kde.org/job/Okular_Release_win64/lastSuccessfulBuild/artifact/okular-23.08.4-1650-windows-cl-msvc2019-x86_64.exe

Tested on Windows 10 Pro 64bit Ver 22H2, OS Build 19045.3803
Hope this helps.
