### ISSUE TITLE
microwin disables WLAN Autoconfig service on laptop

### ISSUE THREAD

**Issue by tuono21** [ChrisTitusTech/winutil#1356]
After running the latest win11 iso through microwin on an HP Ryzen 3 laptop over the weekend, I noticed that wifi was disabled and the interface not even visible in settings even though the adapter was listed as working in device manager. I recalled the event log service needing to be set to automatic recently for file explorer issues so I looked through the list of services and found the WLAN Autoconfig service.. description from services app

"The WLANSVC service provides the logic required to configure, discover, connect to, and disconnect from a wireless local area network (WLAN) as defined by IEEE 802.11 standards. It also contains the logic to turn your computer into a software access point so that other devices or computers can connect to your computer wirelessly using a WLAN adapter that can support this. Stopping or disabling the WLANSVC service will make all WLAN adapters on your computer inaccessible from the Windows networking UI. It is strongly recommended that you have the WLANSVC service running if your computer has a WLAN adapter."

Also, with this service disabled, even the gigabit ethernet nic was not displayed in advanced network settings or anywhere that network adapters should be listed. Enabling the service restored the adapters to the settings pages immediately.

Hope this helps... thanks for all the work folks...

**Comment by MichTheOcelot** [comment]
id suggest from a previous post i made that you try [kontys latest fork](https://github.com/KonTy/winutil/blob/LinksAndPerf/winutil.ps1), since it doesnt disable vital services anymore afaik.
`iwr -useb https://raw.githubusercontent.com/KonTy/winutil/LinksAndPerf/winutil.ps1 | iex`
credits to konty and coding wonders for providing this version while it catches up to the main branch.

**Comment by ChrisTitusTech** [comment]
I've merged this into the test branch and will go live with this on Tuesday or Thursday after more testing.
