### ISSUE TITLE
MicroWin problems with Windows 10 + 11 (WinUtil 24.01.03)

### ISSUE THREAD

**Issue by Jmkrnet** [ChrisTitusTech/winutil#1362]
**Describe the bug**
Recently I was able to test MICROWIN with WINUTIL 24.01.03 and I eventually got Windows 11 Pro to work on Dell Latitude E6540 (4th gen. Core i7, TMP 1.2), but it was not without solving some problems along the way. Perhaps some of this info can help improve WINUTIL or help others who are getting stuck with explorer/network problems:

WINDOWS 10 PRO MICROWIN ISO:
- Unable to install - error(s) in unattend file:
  - Windows could not parse or process unattend answer file [C:\Windows\Panther\unattend.xml] for pass [specialize]. A component or setting specified in the answer file does not exist.
  - The computer restarted unexpectedly or encountered an unexpected error. Windows installation cannot proceed. To install Windows, click "OK" to restart the computer, and then restart the installation.

WINDOWS 11 PRO MICROWIN ISO:
- Able to install, but an error occurred when finishing the installation - it was on the OOBEREGION white screen with the ice cream cone fail animation. After I click "Skip" and select keyboard layouts etc. installation finishes.

- During initial attempts without any drivers added to the ISO I was unable to connect to the network (no wifi, no ethernet) and activate the system. I also experienced the file explorer error/freeze problem. All mentioned problems were repeatable (I tested clean install 3 times).

- After adding drivers for my LAN and WLAN adapters to the ISO I was able to connect to the network and activate the system (after setting region other than world). I also experienced the file explorer error/freeze problem again, but after running WINUTIL tweaks (selected according to attached [WINUTIL-TWEAKS.json](https://github.com/ChrisTitusTech/winutil/files/13878469/WINTOOL-TWEAKS.json)), config (only to Reset Windows Update + Network) and update (only to set Windows Update back to Security (Recommended) Settings) it was resolved (I am not sure which of those helped exactly).

**To Reproduce**
- Create MICROWIN ISO from official WINDOWS 10/11 ISO and try to install it.

**Expected behavior**
- Created MICROWIN ISO works for both WINDOWS 10 and 11.

**Additional context**
Getting the correct Windows 11 drivers for such older laptops was not so straight forward as clicking Windows Update in Windows 10. But eventually I found that you can usually reuse drivers for/from Windows 10 you find on device manufacturer website (e.g. Intel/AMD etc.) or computer manufacturer website (e.g. Dell/Lenovo etc.) if you fail to find new Windows 11 drivers. Still not as smooth as "all open source drivers in the Linux kernel" experience I have on these Dell E6540 laptops after changing/removing HW without open source drivers such as WLAN card, but at least it seems to work now.

Thanks to Chris et al. for making WINUTIL and thanks to Chris for his Windows/Linux tier-list videos (I watched during installation:). I completely agree with that Debian placement at the top and with many Debian clones at the bottom, because of the reasons Chris mentioned:).

**Comment by KonTy** [comment]
@Jmkrnet this has been fixed for a while but it is in Test branch still. Please try it after Chris pulls it into main branch.

**Comment by KonTy** [comment]
@Jmkrnet thank you for the information, do you think there is value in supporting win10? WinUtil strips win11 so much that it makes it essentially new version of win10, it removes all of hte limitations like TPM, WiFi, MS account etc. Personally I don't see a reason at this point to use Win10 that's why I'm curious why other people use it.
