### ISSUE TITLE
Only Tweak services when original type coincides with (or "better" than ) the expected one

### ISSUE THREAD

**Issue by AndrewSav** [ChrisTitusTech/winutil#1365]
**Is your feature request related to a problem? Please describe.**
When using tweak services, the service start type is set to the configured one no matter what. If I have a service that I disabled, winutil will set it to manual, which may cause it to start later. In those cases the service need to be disabled manually again.

**Describe the solution you'd like**
I suggest having a hierarchy similar to: disabled < manual < automatic and let winutil service tweak only work in the down direction and never up. 

**Describe alternatives you've considered**
Alternatively, since we we already have "Original State" in our configs, so we can compare the service state with original one, and skip the action if it is not in the original state.

**Comment by KonTy** [comment]
Agreed that's a good feature to implement.

**Comment by AndrewSav** [comment]
@ChrisTitusTech what kind of activity would you like?

**Comment by AndrewSav** [comment]
@ChrisTitusTech is there a point for me to open a new issue for this, or will it just be summarily closed without any feedback from you?

**Comment by AndrewSav** [comment]
@ChrisTitusTech I understand we all have busy lives and it is often impractical to answer all comments in timely manner. I have suggested an improvement which seems useful and reasonable, and yet it was closed without any comments from you. This could have been unintentional, so I tried to contact you twice so far (above) to get this sorted out. I can see recent commits from you in the repo so I hope all is well for you. 

Could you please confirm that you are not interested or otherwise? Thank you in advance!
