### ISSUE TITLE
Feature Request: Restore Point Functionality

### ISSUE THREAD

**Issue by saharankamal** [ChrisTitusTech/winutil#1367]
I would like to suggest the implementation of a restore point feature in your developed by Chris Titus. This feature would allow users to revert any changes made by the tool to a previous state, providing a safety net in case something goes wrong.

Benefits
- Adds an extra layer of security for users experimenting with the tool.
- Enables quick and easy rollback in case of unintended changes.

**Comment by munkk01** [comment]
I didn't realize this was already in there. Ignore the closed PR.

**Comment by munkk01** [comment]
This was addressed and merged. Can be closed.
