### ISSUE TITLE
[Remove Features Request] Windows Update + Defender Removal

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1370]
[winutil](https://github.com/ChrisTitusTech/winutil) has been very helpful for me, but it's only one of the tools I use on Windows,
the other tool I use is [Sophia Script](https://github.com/farag2/Sophia-Script-for-Windows).

[Sophia Script](https://github.com/farag2/Sophia-Script-for-Windows) is a good tool that takes pride in the fact that it doesn't break Windows, and it has a list of harmful tweakers in which those tools listed there are recognized (by the developer) as breaking Windows.

Latest commit on [Sophia Script](https://github.com/farag2/Sophia-Script-for-Windows) added [winutil](https://github.com/ChrisTitusTech/winutil) to the list of harmful tweakers: https://github.com/farag2/Sophia-Script-for-Windows/commit/e0f2b1f02592e35fc5083b81c7037de78c322bce
There are two reasons behind this:
1) [winutil](https://github.com/ChrisTitusTech/winutil) has a feature that gives the user the option to delete Defender (on MicroWin).
2) [winutil](https://github.com/ChrisTitusTech/winutil) has a feature that gives the user the option to disable Windows Updates.

According to the [Sophia Script](https://github.com/farag2/Sophia-Script-for-Windows) developer those options breaks Windows and such options should not be offered to the user.
For [winutil](https://github.com/ChrisTitusTech/winutil) to be removed from the list of harmful tweakers of [Sophia Script](https://github.com/farag2/Sophia-Script-for-Windows) those two features are to be removed.

Related issue: https://github.com/farag2/Sophia-Script-for-Windows/issues/550

**Comment by KonTy** [comment]
@Obegg interesting, who's to say that removing Defender is harmful? This is completely arbitrary lots of people might not want Defender for many valid reason for example offline gaming pc where every cpu cycle is important, or if they have some other antivirus. We are giving power back to the user and it is a good thing.
