### ISSUE TITLE
MicroWin doesn't open Windows 11 ISO

### ISSUE THREAD

**Issue by System32ita** [ChrisTitusTech/winutil#1373]
When I try to select Windows' ISO, MicroWin gives me the following error:
"Install.wim file doesn't exist in the image".
I've just downloaded the ISO from microsoft website (from here https://www.microsoft.com/software-download/windows11). The same error appears if I try to use Win10 ISO or an ISO from the media creation tool

![1](https://github.com/ChrisTitusTech/winutil/assets/42810443/33c031f0-e399-414c-bbe6-ec2fa9c87765)
![2](https://github.com/ChrisTitusTech/winutil/assets/42810443/a060bb1e-4931-4245-aa77-f01b8f4305bd)

**Comment by System32ita** [comment]
> As described in the error dialog window on your screenshot:
> 
>     * One cannot use Windows ISO downloaded by Media Creation Tool or downloaded using any browser with the Windows user agent string, because Microsoft serves in such cases ISO with more compressed install.esd (instead of install.wim) file that is not editable by Winutil.
> 
>     * You must change the user agent string your browser uses when downloading the Windows ISO = change the user agent to some other OS - Chrome OS, Linux, etc. or download the ISO using a device with some other OS.

I know I cannot use a ISO from MCT but I've had no idea about the user agent, it is not specified anywhere. Thanks for the answer, I'll try

**Comment by nassimna** [comment]
i have the same issues you can extract the iso and convert install.esd to install.wim using powershell check this solution 
https://www.itechguides.com/convert-esd-to-wim/
