### ISSUE TITLE
Feature Request: Larger font size for 1440p and 4k res (Scaling)

### ISSUE THREAD

**Issue by Harlockin** [ChrisTitusTech/winutil#138]
**Is your feature request related to a problem? Please describe.**
When using your tool on hi-res monitor the font is really small

**Describe the solution you'd like**
Let us adjust the font size or automatically set it to a higher number if the res is higher than 1080p

Thank you for all the works ! Always a pleasure to see a new video on the channel :)

**Comment by ChrisTitusTech** [comment]
Good point, I'll see what kind of scaling I can do. It is tricky when drawing the XAML through powershell, but I think it can be done.

**Comment by ChrisTitusTech** [comment]
The current scaling is a bit funky, but I am maxing it more uniform and you can then just maximize or manually resize it and the window will scale properly now. 

Currently on test 6ab999e7d375dc21dd206de5a07fd55c604b3700
