### ISSUE TITLE
Blurry fonts since new UI update (Win 10/11 Pro)

### ISSUE THREAD

**Issue by undeadbanana** [ChrisTitusTech/winutil#1383]
**Describe the bug**
![image](https://github.com/ChrisTitusTech/winutil/assets/4379427/73efd6c1-a867-479f-a3fa-e269b708322c)
Unsure if this screenshot embed is correct but I'll fix if it isn't.
It seems like on maybe a 15-30s interval the fonts on the screen blur and then sharpen, it also happens when you hover over the fonts and move the mouse away as shown in the screenshot.

**To Reproduce**
1. Load WinUtil and look at fonts or mouse over a selection.

**Expected behavior**
No blur

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/4379427/a5588497-b694-49fc-8723-a195b77adef7)

**Additional context**
None, but I do have something that might be important as you have a tweak to disable GameDVR and I don't recall if that touches GameBar settings or not. 

Microsoft decided to make Game Bar more ingrained into Windows 10 and 11 in the October update. The old methods of removing Game Bar don't seem to work anymore, if you do end up forcing a removal using methods available last year be ready for errors and crash to desktops in games. I've been toying with it a lot the past few months trying to get it removed or turned off on Win 10 Pro and no bueno. Eventually decided to go back to Windows 11 Pro, wiped storage, formatted, reinstalled, didn't bring any files or settings over, etc. 

Eventually decided to see test removals/turning it off but still get the same errors in Event Viewer during a few different games, non-store games stuff like OW or steam games. Sometimes it'll completely crash the game, sometimes it will just give you a hard freeze for about 20s then go back. I didn't try removing Xbox apps yet, but I did try to at least turn off Background Permissions for GameBar, all that does is make the errors in event viewer does not appear but the freeze/CTDs still occur. Turned GameBar background permissions off and then tried turning Xbox app's background permissions off and it creates the same issues even though it allows you to uninstall it. I'm guessing since it has integration with GameBar, the gamebar is trying to access it. Again, not sure if you do touch anything related to those settings but Game Bar irritated me so much with the crashing and not allowing me to remove I'm sort of just ranting now because there's no real place to report this since MS thinks it's beneficial for us to have it running in the background.

**Comment by System32ita** [comment]
I've noticed it too

**Comment by bonaccolto90** [comment]
I think this is a problem with windows, more specific with the scale of windows. Try setting the scale to 100% and see if it shows up blurry again, if not, it's definitelly is the scale.
Some programs, not only winutil, have problems with windows scale's function...

**Comment by undeadbanana** [comment]
Apologies, I should've mentioned the troubleshooting steps I did. I initially blamed PowerShell and tried various steps like setting the scale, which didn't work so I came here but thinking more on it I realize my assumptions might've been correct and it might just be a bug with PowerShell. 

I've been messing around with reinstalling the OS because of what ended up being a hardware fault and got tired of reinstalling all my software, so I started using the default version of PS, which I think is version 5. Going to update to latest release and retry.

**Comment by KonTy** [comment]
@undeadbanana strange I can't reproduce this issue, the fonts look nice and crisp. Is it possible to capture a short video and give us more details, like Video card, screen size, scale.

**Comment by K-Saikrishnan** [comment]
The blurriness is happening in both of my monitors: 24" 1920x1080 & 27" 2560x1440 with 100% scale.

24":
![image](https://github.com/ChrisTitusTech/winutil/assets/53394202/27e232e5-2f37-4d92-a16e-a891b7e5ac0c)

27":
![image](https://github.com/ChrisTitusTech/winutil/assets/53394202/f54caa4a-2983-4825-a5ff-08d61240f01e)

Full PC Specs: [PCPartPicker](https://pcpartpicker.com/list/ymfFHG)

**Comment by K-Saikrishnan** [comment]
@KonTy The blurriness is happening in both of my monitors: 24" 1920x1080 & 27" 2560x1440 with 100% scale.

24":
![image](https://github.com/ChrisTitusTech/winutil/assets/53394202/27e232e5-2f37-4d92-a16e-a891b7e5ac0c)

27":
![image](https://github.com/ChrisTitusTech/winutil/assets/53394202/f54caa4a-2983-4825-a5ff-08d61240f01e)

Full PC Specs: [PCPartPicker](https://pcpartpicker.com/list/ymfFHG)

**Comment by KonTy** [comment]
Please try the latest version of Winutil, the fonts have been reset to default windows fonts, see if this fixes your issue

```iwr -useb https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1 | iex```

**Comment by Jack-Punter** [comment]
I also have this issue, with 100% scaling in windows and on the latest version @KonTy provided.  Although interestingly seams inconsistent, in the install panel, some columns are worse than others.
Another interesting thing, that may or may not be related is that when windowed the `install selected` and related buttons have their text seemingly bounce as if between two pixel locations (the buttons themselves don't move, just the text within them). I wonder if there is some form of sub-pixel rendering going on for the text that has some issues?

**Comment by KonTy** [comment]
I wonder if it is monitor refresh rate related? What is your refresh rate? Can you bump it up to see if the issue goes away?

**Comment by undeadbanana** [comment]
> @undeadbanana strange I can't reproduce this issue, the fonts look nice and crisp. Is it possible to capture a short video and give us more details, like Video card, screen size, scale.


Oops, sorry got a little side tracked. Through messing around with settinsg, I was able to reduce it a lot. It's still _slightly_ noticeable but not enough to cause eye fatigue like it was for me before. TBH, I didn't go through and use troubleshooting techniques find a workaround, I mean not entirely positive which setting fixes it as I was trying combos of settings and not switching one at a time but this is what I've found that cuts makes it easier to use the program.

**Settings applied (Using Windows Terminal in Win 11)**
**Settings Menu**
Rendering: Turned top 2 settings on, Use new text renderer ("AtlasEngine"), and Redraw entire screen when display updates. (Haven't tried software rendering)

The rest was basicallying doing the following to all the profiles, I know it's redundant but I was irritated.

->Profiles -> Default Profile
Changed: 
1. Textantialiasing to ClearType ( Cant remember exactly what I read, but it was something like ClearType is Windows method of keeping fonts clear and legible )
2. Use the new text renderer ("AtlasEngine") - On

You probably don't need to but I did this to all the profiles, also I think I chose ClearType because Windows has a calibration tool for ClearType fonts and I used it before finding the option to see if it'd help (it didn't, Windows Terminal defaults to Grayscale).


I'll insert a gif to show difference in settings, just need to set up some capture software or learn how to use what I've got.

Things I've tried/settings:
OS: Win 10/11 Pro - Tried after soft resets, completely fresh re-installs
GPU: GTX 3090 - Tried on monitors with 60hz and 144hz, Gsync enabled/disabled - settings at Fullscreen only, Full and Windowed Screens produce same results as being disabled, Vsync enabled/disabled
Newest Versions of PowerShell, the ISE version of PowerShell, Dev version of PowerShell, and bundled OS PowerShell

Nothing except adjusting these settings I mentioned prior reduced it, so it might just be the new text Renderer setting. I'll try and find out which setting is fixing it or if it's a few working together, or if it occurs on my surface pro (only other computer I have), but I have limited time these days. I'll try and get this done quickly though

**Comment by undeadbanana** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/4379427/5ea50ec0-c91c-4e89-aa21-c4256c00b75e)

Not sure of the quality, this is on my older non G-sync, 60hz 1920x1080 monitor. It still does it but it's not _that_ blurry anymore. I noticed just now while trying to record it that it's actually on some sort of interval and the bottom row of categories is affected by the blur more than the top ones.
