### ISSUE TITLE
after tweaks i cant play rdr2

### ISSUE THREAD

**Issue by BananaCatt** [ChrisTitusTech/winutil#1386]
after i used tweaks (laptop) i cant play red dead redemption 2 as it gives me an error that says: "Out of memory" a few minutes before this issue was posted, i tried again and it worked, but i'd like to ask, where can i find the saved restore point? 

Thanks. BananaCatt

**Comment by munkk01** [comment]
> after i used tweaks (laptop) i cant play red dead redemption 2 as it gives me an error that says: "Out of memory" a few minutes before this issue was posted, i tried again and it worked, but i'd like to ask, where can i find the saved restore point?
> 
> Thanks. BananaCatt

You can access the restore points by:
* Open your `run` prompt
* Type `rstrui.exe` and hit `Enter`
* Check the `Description` and `Time` of the `Recommended restore` to determine if it was created by WinUtil
    * The name should be `System Restore Point created by WinUtil`
* If that is not the correct restore point, select `Choose a different restore point` to determine the restore point you'd like to revert to
