### ISSUE TITLE
MicroWin iso error while installing

### ISSUE THREAD

**Issue by nassimna** [ChrisTitusTech/winutil#1391]
**Describe the bug**
i got this error after installing MicroWin windows 10 

![Capture](https://github.com/ChrisTitusTech/winutil/assets/25207132/8ed11ec7-256e-4e82-8441-5bb229a9c909)

after searching I found the probable cause is windows traying to create computer name based on serial number and it's too long

the solution that worked for me is in this article 

https://techglimpse.com/solve-windows-parse-process-unattend-answer-file/#google_vignette

**Comment by CodingWonders** [comment]
@KonTy We may need to check the resulting answer file in Windows SIM to verify it

**Comment by KonTy** [comment]
@CodingWonders @nassimna hey guys this is a known issue for Win10, it doesn't have specialize section, i just was not prioritizing this, since not many people use win10. Let me look at it today.

**Comment by CodingWonders** [comment]
> @CodingWonders @nassimna hey guys this is a known issue for Win10, it doesn't have specialize section, i just was not prioritizing this, since not many people use win10. Let me look at it today.

We can detect this when we begin processing by detecting the version of the index of the WIM file, specifically the Build area. For example:

```powershell
PS C:\WINDOWS\system32> Get-WindowsImage -ImagePath C:\wims\boot.wim -Index 1


ImageIndex       : 1
ImageName        : Microsoft Windows PE (amd64)
ImageDescription : Microsoft Windows PE (amd64)
ImageSize        : 1.910.022.115 bytes
WIMBoot          : False
Architecture     : x64
Hal              : 
Version          : 10.0.22000.194
SPBuild          : 194
SPLevel          : 0
EditionId        : WindowsPE
InstallationType : WindowsPE
ProductType      : WinNT
ProductSuite     : 
SystemRoot       : WINDOWS
DirectoryCount   : 3935
FileCount        : 16228
CreatedTime      : 05/06/2021 13:43:02
ModifiedTime     : 23/11/2022 20:52:52
Languages        : en-US (Default)

PS C:\WINDOWS\system32> [Version](Get-WindowsImage -ImagePath C:\wims\boot.wim -Index 1).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22000  194     

PS C:\WINDOWS\system32> ([Version](Get-WindowsImage -ImagePath C:\wims\boot.wim -Index 1).Version).Build
22000

PS C:\WINDOWS\system32> ([Version](Get-WindowsImage -ImagePath C:\wims\boot.wim -Index 1).Version).Build -ge 21380
True
```
