### ISSUE TITLE
Battery Drain of Laptops when off

### ISSUE THREAD

**Issue by Zeehel** [ChrisTitusTech/winutil#1399]
**Describe the bug**
After doing the tweaks/debloating with the tool I got the problem with multiple laptops that they drain power when off, and are always on low battery when I'm turning them on.

**Expected behavior**
No battery drain at all when windows is shut down as it supposed to be.

**Comment by KonTy** [comment]
Please check out this wiki for troubleshooting and let us know what you find
https://github.com/KonTy/winutil/blob/main/wiki/Battery.md

**Comment by DasIstSpark** [comment]
Battery drain when “off” does not make any sense. If you were referring to battery drain during “sleep”, thats how its going to be since microsoft enforced have S0 sleep rather than S3 sleep state. Google windows modern standby.

**Comment by KonTy** [comment]
@DasIstSpark we should add a tweak to allow S3 sleep. I think Linus had qa video about this where they said they will not recommend windows until this is fixed. That was an older video and I thought that was fixed by now.

**Comment by DasIstSpark** [comment]
@KonTy its not that simple. There is no fix for S0 sleep state, it is literally ultra power save mode, meaning it is actually not in sleep. Even if lowest power consumption mode, mobile game laptop and workstation are power hunger, my Thinkpad p16’s fan kicks in even in “modern standby”. Most of modern laptop does not support S3 out of box I don’t really think make enabling s3 as option is good decision. Best thing you can do is use hibernate or don’t use any form of “sleep”.
I disabled sleep, hibernation and power off when lid close. I know its really inconvenient, but I rather not risk it until Microsoft replace windows dev teams machines to windows laptop and realize how stupid their idea was.

**Comment by DasIstSpark** [comment]
@KonTy and what Linus was covering was laptops that randomly breaks the sleep state due to unknown reason not s0 itself. Like I said even if you don’t have random wake up issue, S0 will not going into “actual sleep state” period.

**Comment by Zeehel** [comment]
No I really mean power drain when turned off, at windows was shutting down properly. The problem exist on three different laptops. And I noticed that all of them are taking especially long for shutting down before the screen goes off...

**Comment by DasIstSpark** [comment]
@Zeehel well then one thing I can think of is fast startup. Would you disable that and see if it still drains?

**Comment by Zeehel** [comment]
The bios or windows one? In Windows it's already deactivated

**Comment by 0hip** [comment]
> The bios or windows one? In Windows it's already deactivated

Try:
Win+R >> shutdown.exe /s /f /t 0
That should power off (no fast start) your laptop. In my case it doesnt take more than 10 seconds (Win10 on my side).

**Comment by KonTy** [comment]
@Zeehel can you please try a new tweak in Winutil this should set your laptop to hibernate and disable S0

<img width="623" alt="image" src="https://github.com/ChrisTitusTech/winutil/assets/9524513/8a6084be-944d-4ea8-bcf4-8e3dc8399d9d">



``irm https://raw.githubusercontent.com/KonTy/winutil/test-2024-01-15/winutil.ps1 | iex``
