### ISSUE TITLE
Reset Windows Update button not doing anything

### ISSUE THREAD

**Issue by JUGADOR123** [ChrisTitusTech/winutil#14]
**Describe the bug**
Reset Windows Update button not doing anything, does not display anything on console and the program is still responsive

**To Reproduce**
1. Open the tool
2. Click on Config
3. Click on Reset Windows Update

**Expected behavior**
The console logs everything that is happening and "fixes" the windows updates

**Screenshots**

**Additional context**
Ran on windows terminal 1.12.10983
Windows 11 Pro 22000.588

**Comment by Rasinzz** [comment]
The same thing was happening to me. 

**FYI:** I'm on Windows 10.

**Comment by Goten87** [comment]
i think the same happened to me im in windows 10 all the console game me was a last line of something about self destruct in 60 min

**Comment by Carterpersall** [comment]
It looks like Chris forgot to include a call for it in the script and instead accidentally included it in the Default Update Settings button.

**Comment by Carterpersall** [comment]
This should be fixed in #20

**Comment by Goten87** [comment]
ty for the fix lets hope chris will include it soon

**Comment by jalsarraf0** [comment]
Hopefully. Here's a screenshot of the error I get when I try it.

Love the new UI though!

![settoresult](https://user-images.githubusercontent.com/19882582/168482094-324cca5a-167d-4306-baf3-a2397045725b.PNG)

**Comment by Goten87** [comment]
yeah thats what i get as well

**Comment by Carterpersall** [comment]
Is your computer company managed? If not, what other scripts (if any) have you run in the past?

**Comment by Goten87** [comment]
For me it’s a clean home install for windows 10 pro all I run befor was the older script of Chris

**Comment by Carterpersall** [comment]
I cannot seem to be able to replicate this issue. It does seem to be something happening to multiple people so I'm going to have to figure it out.
Are you running a script in an administrator PowerShell instance?

**Comment by Goten87** [comment]
yeah admin powershell

**Comment by Carterpersall** [comment]
When I get the time later, I'll try the script on a base install of Windows 10 and 11 in a VM

**Comment by Carterpersall** [comment]
> also i dont know if the reset update realy needs to reset it but i keep the group permissions even when i reset windows update with the tool

- @Goten87 Do you have the services state set by group policy? That would cause this issue.

**Comment by Goten87** [comment]
i dont know what i did i did the essencial tweaks from the old script and then it all borked up

**Comment by jalsarraf0** [comment]
> i dont know what i did i did the essencial tweaks from the old script and then it all borked up
> 
> i need to setup a new VM for win10 as well again so i can see what i did to explain it more

I think this might be my case too.
