### ISSUE TITLE
Feature Request: Auto Login script addition

### ISSUE THREAD

**Issue by N3EOP** [ChrisTitusTech/winutil#140]
Back in the "good old days", when you fired up netplwiz, there was a check box to enable automatic login.  There is a registry tweak to re-enable it; it should be a simple thing to add.

Alternatively, you can have the tool install the Microsoft Autologin utility.

Thanks.

**Comment by bradlymcconnell** [comment]
Just scanning through and are you retarded?   An application that auto logins?  What the fuck?

--
Brad McConnell

**Comment by ChrisTitusTech** [comment]
This is actually a registry entry and I still use it today in certain scenarios where it is a dumb terminal that just needs to run a windows app. 
I can't do a checkbox, but I can make a script that will prompt for questions like user name, domain, password then put those in registry for autologin.

**Comment by ChrisTitusTech** [comment]
Added to test branch using Microsoft's sysinternals method.

commit 8becf46bbd2c975f7df3c7482c19534f969fdf18
