### ISSUE TITLE
Customisation behave in opposite manner if you import a tweak json

### ISSUE THREAD

**Issue by Manish-757** [ChrisTitusTech/winutil#1404]
**Describe the bug**
Once you import a tweaks JSON, the visual button in preferences shows the opposite  behavior i.e when dark theme is enabled UI shows disabled and vice versa, its there  for other tweaks that were mentioned in the JSON as well

**To Reproduce**
1. Export a JSON from the tweaks page
2. Import the same JSON
3. Check the button's behavior 

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/154927739/633dc380-4732-4c50-86a3-e6fc52d11297)
![image](https://github.com/ChrisTitusTech/winutil/assets/154927739/ef8bcd1a-25cb-4648-9036-c9c8bd8182f7)

**Comment by KonTy** [comment]
Customize preferences in tweaks is not supported by Import/Export functionally as of today, please see notes for the PR under **next** section

https://github.com/ChrisTitusTech/winutil/pull/1398
