### ISSUE TITLE
Files file manager Package not found and script exits all installs without continuing to remaining.

### ISSUE THREAD

**Issue by tuono21** [ChrisTitusTech/winutil#1407]
Using version from Jan 15...

Tried out a new win install on a laptop using a microwin modified iso and all went well. Got back into winutil after all MS updates ran and tried installing some apps. I selected 30 and let it start but the Files file manager had an issue and everything just quits. I guess Files file manager just happened to be the first app in the list?

...
No package found matching input criteria.
Package not found: YairAichenbaum.Files
No package found matching input criteria.
===========================================
--      Installs have finished          ---
===========================================

I looked up that package name and then just unchecked Files file manager and tried again and everything installed without error.

second run...
...
(29/29) Found Wireshark [WiresharkFoundation.Wireshark] Version 4.2.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://2.na.dl.wireshark.org/win64/Wireshark-4.2.2-x64.msi
  ██████████████████████████████  59.9 MB / 59.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed

No package found matching input criteria.
===========================================
--      Installs have finished          ---
===========================================

So, looks like an install file is missing somewhere for the file manager but also the script just exits instead of continuing on to the other app installs.

Also, that final message on the successful installs "No package found matching input criteria." seems to imply the script is falling out to error handling code even when successful. The list of 29 successfully installed apps included visual studio and the runtime lib dependencies also and all showed successful with no hint of error.

**Comment by munkk01** [comment]
This is related to:
https://github.com/ChrisTitusTech/winutil/issues/1315

I think we'll just have to remove `Files` from the utility for now.

Next thing to look into is; if an application fails to install.. The script should continue and only warn of the failed install. Shouldn't prevent the rest from completion.
