### ISSUE TITLE
Application installs adding SilentlyContinue as a package name

### ISSUE THREAD

**Issue by munkk01** [ChrisTitusTech/winutil#1409]
**Describe the bug**
All application installs and uninstalls are calling both the package name and "SilentlyContinue."

In `Install-WinUtilProgramWinget.ps1`, I added some debug `Write-Host` statements to track what's causing this unnecessary output to the PS console. It appears that somewhere in the calls, a rogue `SilentlyContinue` is being passed as the application name for ALL installations.

**To Reproduce**
1. Go to the `Install` tab
2. Select any of the applications to install. (Used `Sublime Text` under `Development` for testing)
3. Click on `Install Selected` monitor the `Write-Progress/Write-Host` output in the PS console.
4. Monitor the `Write-Progress/Write-Host` output in the PS console.
5. Successful installations always end up outputting `No package found matching input criteria`.

**Expected behavior**
Single or multiple packages are installed (Provided they are available in Winget or Choco) or uninstalled with output relevant to the successful or unsuccessful installation. `SilentlyContinue` should not be passed as one of the packages.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/152475628/f2b61641-8bd6-484a-b981-445eea48eed4)
![image](https://github.com/ChrisTitusTech/winutil/assets/152475628/5aac1f41-fb5c-4011-af29-1dfab4e85c1d)

**Comment by TheLinuxGuy** [comment]
I am also having this issue.

**Comment by munkk01** [comment]
@KonTy I'm not sure if you have the time or ability to look into this but it's affecting anyone using the utility. In some cases, it isn't problematic and in others, it is. 

I haven't been able to identify what's causing this.

**Comment by KonTy** [comment]
@munkk01 are you using the test branch or main? Could you please try my test branch?

``irm https://raw.githubusercontent.com/KonTy/winutil/test-2024-01-15/winutil.ps1 | iex``

**Comment by munkk01** [comment]
> @munkk01 are you using the test branch or main? Could you please try my test branch?
> 
> `irm https://raw.githubusercontent.com/KonTy/winutil/test-2024-01-15/winutil.ps1 | iex`

It's affecting both the main branch and test branch through this repo, yours did not appear to replicate this issue.

**Comment by TheLinuxGuy** [comment]
> @munkk01 are you using the test branch or main? Could you please try my test branch?
> 
> `irm https://raw.githubusercontent.com/KonTy/winutil/test-2024-01-15/winutil.ps1 | iex`

Yours works and fixes this bug.

**Comment by one-mb-rai** [comment]
Try installing winget from main tool and retry installing applications. For me it works
