### ISSUE TITLE
tweaks -> set services to manual - don't disable NTP service

### ISSUE THREAD

**Issue by charger89** [ChrisTitusTech/winutil#1412]
**Is your feature request related to a problem? Please describe.**
Enabling `set services to manual` under Tweaks causes The Windows Time service also to be shut down, resulting in certain cases the system time to deviate from expected value at boot.

**Describe the solution you'd like**
When `set services to manual` is enabled, do not disable the NTP service.

**Comment by KonTy** [comment]
We should probably do inventory of all services that we turn off.

**Comment by fr0stedfl4ke** [comment]
> We should probably do inventory of all services that we turn off.

I agree with this. We should definitely document all of the services that are affected by this utility and ensure they get reviewed on on occasion.
