### ISSUE TITLE
MicroWin Windows 11 23H2 with keep defender, SecurityHealthSystray.exe is removed

### ISSUE THREAD

**Issue by allebon00** [ChrisTitusTech/winutil#1417]
Hi,

When using MicroWin with keeping defender the SecurityHealthSystray.exe file is not installed.

The regkey for startup for SecurityHealthSystray.exe is present but the file is not.

So when installing Windows, Windows security is there functioning properly but the system tray is not present because the file SecurityHealthSystray.exe is not in system32.

Apparently the MicroWin process has removed the file somehow.

**Comment by Zaf9670** [comment]
Looks like this was auto closed but do you have more info on how you made your ISO? That information is probably useful.

Which ISO, what packages were toggled to keep, etc.?
