### ISSUE TITLE
Extractnow - free tool to be added if possible 

### ISSUE THREAD

**Issue by ia2115** [ChrisTitusTech/winutil#1418]
love the project, and so i suggest to add this very usefull toolk who can extract a lot of archives in one batch.

very usefull

https://extractnow.com

thanks, hope its can be usefull to more people.

regards
jan

**Comment by v-Kaefer** [comment]
I could only find the `choco install extractnow`, but it was submitted and approved, before it's auto virus scan.
Not a good sign. @ChrisTitusTech 
https://community.chocolatey.org/packages/extractnow#virus
