### ISSUE TITLE
Set-ItemProperty : Requested registry access is not allowed.

### ISSUE THREAD

**Issue by Iamanaws** [ChrisTitusTech/winutil#142]
**Describe the bug**
When I run Tweaks I get just errors in the terminal: `Set-ItemProperty : Requested registry access is not allowed.`

**To Reproduce**
1. I open Powershell with admin rights
2. Run `iwr -useb https://christitus.com/win | iex`
3. Go to Tweaks section, and select the ones I want, in this case, the Desktop recommended ones.
4. Click `Run Tweaks`

**Expected behavior**
Make the Tweaks without errors

**Screenshots**
Just a lot of this error
![image](https://user-images.githubusercontent.com/78835633/190282663-109c2f24-246d-4209-851f-192cbdd3dd2e.png)

**Additional context**
I'm using Windows 11 Pro 22000.978

**Comment by Kitsunejasutin** [comment]
Run Powershell or Terminal as administrator

**Comment by Iamanaws** [comment]
I did it, that's why I'm not sure why it throws that error

**Comment by ChrisTitusTech** [comment]
I've seen this when running Windows terminal from search. Right click the start button and run Windows Terminal as Admin.

**Comment by Iamanaws** [comment]
Good advice, I did it from that menu the first times, but now I tried the opposite, to run it from the search, and worked well, thanks for helping.

**Comment by SkyFoxCoder** [comment]
@ChrisTitusTech This issue can be closed.
