### ISSUE TITLE
Dark Theme Bug

### ISSUE THREAD

**Issue by hl2guide** [ChrisTitusTech/winutil#1420]
**Describe the bug**
Toggling the dark theme under the "Tweaks" tab results in the opposite of the intended result.

**To Reproduce**
1. Go to the `Tweaks` tab
2. Toggle the `dark theme` toggle control
3. View the theme change in `Windows 11` being opposite

**Screenshots**
![ex1](https://github.com/ChrisTitusTech/winutil/assets/17044982/2d5a9a57-b3f3-4c70-a24a-5fd6df7fc145)

**Comment by KonTy** [comment]
@hl2guide I thin we are going to back global import/export functionality out because it doesn't work with real time knobs well.
