### ISSUE TITLE
winutil load is never the latest version

### ISSUE THREAD

**Issue by hpsxrb** [ChrisTitusTech/winutil#1437]
Either through the Winutil shortcut on dekstop, or online via the address  irm christitus.com/win | iex
I never upload the latest version of Winutil, as it does not have the date in the upper right part of the version.

**Comment by 0hip** [comment]
> Either through the Winutil shortcut on dekstop, or online via the address irm christitus.com/win | iex I never upload the latest version of Winutil, as it does not have the date in the upper right part of the version.

![image](https://github.com/ChrisTitusTech/winutil/assets/90657954/4886b75f-c977-4dcd-9206-a8219a0d7348)

**Comment by hpsxrb** [comment]
Thank you !!
