### ISSUE TITLE
Invoke-RestMethod instead of Invoke-WebRequest -UseBasicParsing

### ISSUE THREAD

**Issue by couleurm** [ChrisTitusTech/winutil#144]
**Is your feature request related to a problem? Please describe.**
I like nitpicking on making one-liners as small as possible

**Describe what you'd suggest**

The current command to run the tool is
```powershell
iwr -useb https://christitus.com/win | iex
```
but you can also do
```powershell
irm https://christitus.com/win | iex
```
or even
```powershell
iex(irm https://christitus.com/win)
```
or if you live on the edge
```powershell
iex(irm christitus.com/win)
```
Depending on how reliable Invoke-RestMethod (irm) is compared to Invoke-WebRequest (iwr), feel free to replace them in the README

**Comment by ChrisTitusTech** [comment]
This is pretty damn awesome. Thanks for this.

**Comment by ChrisTitusTech** [comment]
added to readme Thanks @couleurm
