### ISSUE TITLE
【Optimization】The Project is too resource intensive on low powered PC.

### ISSUE THREAD

**Issue by blusewill** [ChrisTitusTech/winutil#1441]
**Is your feature request related to a problem? Please describe.**
So I am installing Windows 10 LTSC into a QEMU VM which is 2 cores 2 thread (Very low powered PC) and found out that Toolbox in the dark mode have a very intensive resource usage (Might because of glowing effect). Makes CPU goes up to 80% makes the entire PC slow down.

**Describe the solution you'd like**
Maybe what you can do is making the glowing color not resource intensive? or disable it completely in some low-powered machine when detected. Or back to classic using CLI interface.

**Additional context**
Image of Showcasing VM is being resource intensive.
![image](https://github.com/ChrisTitusTech/winutil/assets/62820836/6fa14e7f-50b8-4d70-bf5d-1fe20401ecc9)

**Comment by martin-braun** [comment]
Same problem. I try to setup a Windows VM with sane defaults and this tool is quite a hog. I assume the cool looking design is at fault. Last time I checked this project, it looked like a Windows XP app, but it was much faster. Sadly unusable right now.

Please revert those design changes or allow to provide a flag to launch it without fancy UI.

**Comment by berlintay** [comment]
Could possibly pass a config.json file option with the util.

example

```
pwsh.exe -Command "irm https://christitus.com/win | iex" -ConfigFile ~\config.json -NonInteractive"

```


i dont think it will work just like that you might have to create a script but it could help.

**Comment by martin-braun** [comment]
Just because the issue is inactive doesn't mean the issue doesn't exist.

**Comment by v-Kaefer** [comment]
I'm so glad Chris set up a bot to close issues, finally. @martin-braun feel free to open another issue, but i'm pretty sure, it's because of the big list being loaded, right from the start. I'm working on sub-lists, that may end up solving that aswell.

**Comment by blusewill** [comment]
Alright this issue is closed due to inactivity it's an optimization issue that still haven't done yet
