### ISSUE TITLE
Apps that are worth adding

### ISSUE THREAD

**Issue by BlobIsBack** [ChrisTitusTech/winutil#1443]
Hi ! I thinks that these apps are really cool and I would like to have them in winutil :

- BloatyNosy (debloat win11)
- Motrix Download Manager
- x360ce (makes the computer thinks a Xbox controller is connected even when it's not a Xbox controller)
- Op Auto Clicker
- ATLauncher (NOT TLAUNCHER)
- Bloxstrap (open source Roblox bootstrap (I don't like Roblox tbh but this software is good)
- Vencord/OpenAsar (1st one is a discord modification and 2nd one is to optimise discord. OpenAsar can be installed with vencord setup)

Maybe a way to automatically add uBlock origin with best parameter automatically

**Comment by v-Kaefer** [comment]
**I made a PR with these features:**
- ATLauncher
- Op Auto Clicker
- Motrix Download Manager

But there are somethings that need attenttion, and could bring the denial of this and future PRs for the features you want:

You need to request a `winget manifest` for:
- BloatyNosy
- Bloxstrap
- Motrix Download Manager
- Universal-Android-Debloater
- Ultimate Windows Tweaker
- x360ce

You need to request a `choco install` for:
- ATLauncher
- BloatyNosy
- Bloxstrap
- x360ce

Then you can request these features/apps without a doubt that they will be implemented, if approved by chris, lol
