### ISSUE TITLE
snappy driver installer link not existing 

### ISSUE THREAD

**Issue by Dotdk** [ChrisTitusTech/winutil#1444]
Snappy driver github is not exixsting 
![firefox_vqenhTn7r6](https://github.com/ChrisTitusTech/winutil/assets/6298561/cd60d2b9-632a-41ce-af3c-53c10a4539b7)

![firefox_qkVuIXbu2r](https://github.com/ChrisTitusTech/winutil/assets/6298561/81228d9b-f5c0-48f6-98d8-c76a05117111)

![explorer_LDiyWDBKia](https://github.com/ChrisTitusTech/winutil/assets/6298561/2990314a-243f-44b0-8c63-e229e5de697e)

**Comment by v-Kaefer** [comment]
Fixed #1476
