### ISSUE TITLE
Feature Request: Please add Google Drive for Desktop (Google Drive File Sync)

### ISSUE THREAD

**Issue by themooleman** [ChrisTitusTech/winutil#1449]
I'd love if Google Drive for Desktop (https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe) was added to this utility. It's something which I commonly install and it is available through Ninite, however this tool is otherwise far better than Ninite and also quicker to use!

**Describe the solution you'd like**
I'd like Google Drive for Desktop to be available to install using winutil.

**Describe alternatives you've considered**
An alternative solution is just to download Google drive from Google and install it manually.

**Additional context**
I don't think additional context is required.

**Comment by v-Kaefer** [comment]
- Done, can be closed.
#1427

**Comment by themooleman** [comment]
Fantastic!
