### ISSUE TITLE
Feature Request: Add Twinkle Tray

### ISSUE THREAD

**Issue by omar-njie** [ChrisTitusTech/winutil#145]
**Is your feature request related to a problem? Please describe.**
Adjust monitor brightness from the taskbar quicly and easly rather than using the buttons on the monitor to adjust the brightness.

**Describe the solution you'd like**
There is an app called **[Twinkle Tray](https://twinkletray.com/)** that allows you to adjust your monitor brightness right from the taskbar.
You can install the app using **winget:** `winget install -e --id xanderfrangos.twinkletray`

**Describe alternatives you've considered**
The alternative solution to this is just to use the built in buttons on your monitor to adjust the brightness.

**Additional context**
![twinkle_tray](https://user-images.githubusercontent.com/66810439/190385044-c1eb430d-f80e-49fa-bf8a-cb3e5f0ac6a0.png)

**Comment by ChrisTitusTech** [comment]
Will add in next update

**Comment by omar-njie** [comment]
I am actually working on it, I already added the program to the .xaml file, json file & the powershell file I will submit a pull request later.
