### ISSUE TITLE
Feature Request: Requesting Some Cool Programs to Add :)

### ISSUE THREAD

**Issue by Garou7** [ChrisTitusTech/winutil#1451]
**Requesting Some Cool Programs to Add.**

1) BleachBit: https://www.bleachbit.org/
2) Lively Wallpaper: https://www.rocksdanister.com/lively/
https://github.com/rocksdanister/lively
3) LocalSend: https://localsend.org/
4) OpenHashTab: https://github.com/namazso/OpenHashTab
5) Safing Portmaster: https://safing.io/
6) TcNo-Acc-Switcher: https://github.com/TCNOco/TcNo-Acc-Switcher
7) Ultimate Windows Tweaker: https://www.thewindowsclub.com/ultimate-windows-tweaker-5-for-windows-11
8) Universal-Android-Debloater: https://github.com/0x192/universal-android-debloater
9) Vencord:  https://vencord.dev/
https://github.com/Vendicated/Vencord

**Comment by BlobIsBack** [comment]
Maybe instead of doing this we should make one big feature request with issue #1443 and other ones

**Comment by v-Kaefer** [comment]
There is already a pr for BleachBit (couldn't find it to mention it).

But, there are no manifests for **Universal-Android-Debloater** & **Ultimate Windows Tweaker**.
So for now, there are no way to implement them, but you can request in their repo for a winget manifest!

**Comment by BlobIsBack** [comment]
Add thonny please ! It's a python lightweight and yet friendly python ide
