### ISSUE TITLE
Fullscreen Issue

### ISSUE THREAD

**Issue by jstack01** [ChrisTitusTech/winutil#1455]
Does anyone know how to minimize or scale back Winutil if you bring it to fullscreen? F11 and ESC dont seem to work and there is no minimize or window button. The only way i've been able to get out of it is by closing winutil entirely.

**Comment by munkk01** [comment]
Should be able to just double click anywhere in the app to revert it back to window

**Comment by jstack01** [comment]
Nice. That was it. Adding F11 or ESC as a shortcut to exit fullscreen would be nice but double-clicking works good enough. Thanks @munkk01 !
