### ISSUE TITLE
scope=machine flag breaks some package installs

### ISSUE THREAD

**Issue by lakub-muravlov** [ChrisTitusTech/winutil#1457]
**Bug description:** 
after latest release there was --scope=machine added to winget install script, which leads to some packages failing to get installed

**To Reproduce**
1. Go to app
2. Select application(s) - can be reproduced with discord, onlyoffice, rust, teams, viber
3. Install selection
4. Install fails with error "No applicable installer found; see logs for more details."

**Expected behavior**
Package should be installed

**Screenshots**
![Screenshot 2024-01-26 024203](https://github.com/ChrisTitusTech/winutil/assets/85365426/d130b234-bc34-43b3-8f28-f7d26077a6dd)

**Additional context**
Removing this flag resolves the issue
![Example](https://github.com/ChrisTitusTech/winutil/assets/85365426/f7ff94b2-8f38-402a-99a2-499cb7129352)

**Comment by Nathan-Shea** [comment]
I'm also having this problem for pretty much every app. Removing the flag resolved the issue for me as well.

https://github.com/ChrisTitusTech/winutil/issues/1494#issuecomment-1916145351

**Comment by KonTy** [comment]
I think this is the issue if you already have apps installed as a local scope and try to install it again as a machine scope? I just tried installing all these apps without any problems with the machine scope. 

I wonder if there is a way in winget to automatically detect installation and thier scope and do the appropriate thing.

**Comment by KonTy** [comment]
Hmm so strange I'm still getting this error on load, it then loads just fine. We should probably ask more people to test it. I wonder why you are not seeing this can you run this command? This seems to be busted:

`` irm https://raw.githubusercontent.com/ogfrm/winutil/test-2024-01-30/winutil.ps1 | iex``




``` powershell

convertfrom-json : Invalid JSON primitive: .
At line:7876 char:6
+ }' | convertfrom-json                                                                                                                              +      ~~~~~~~~~~~~~~~~                                                                                                                                  + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException                                                                    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```
