### ISSUE TITLE
Improved README.md Usage Instructions

### ISSUE THREAD

**Issue by hl2guide** [ChrisTitusTech/winutil#147]
**Is your feature request related to a problem? Please describe.**
* The `README.md` file does not mention if PowerShell should be run as an Administrator or not
* The `Launch Command:` section does not mention PowerShell at all
* The minimum required PowerShell version is not detailed

**Describe the solution you'd like**
A clear and concise usage section in the `README.md` file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ChrisTitusTech** [comment]
Commited to Test
297cf678fbc89d070f92fd32b912f2ad3c8a4c9d
