### ISSUE TITLE
Replace Synctrayzor with Syncthing Tray

### ISSUE THREAD

**Issue by TehMightyPotato** [ChrisTitusTech/winutil#1478]
The toolbox includes [Synctrayzor](https://github.com/canton7/SyncTrayzor), but that appears to be abandonware (last commit 3+ years ago). I've used this before and it works fine, but it will probably break with a syncthing update in the future.

[Syncthing Tray](https://github.com/Martchus/syncthingtray) is a alternative that, afaik, supports all the features Synctrayzor does and is also actively developed on. I'm currently using this and had no issues whatsoever. Might be a better alternative to future proof?

**Comment by RocGod** [comment]
#1495 should be good to close this issue.

**Comment by RocGod** [comment]
Please close this issue as the PR is merged.
