### ISSUE TITLE
Can't install discord or EA app

### ISSUE THREAD

**Issue by Thedinotamer** [ChrisTitusTech/winutil#1482]
**Describe the bug**
When I try to install Discord and EA app it tells me it can't find an applicable installer for Discord and then it doesn't even start installing the EA app.

**To Reproduce**
1. Go to 'Install'
2. Click on Discord and EA app and then 'Install selected'
3. See error

**Screenshots**
![Skärmbild 2024-01-27 121213](https://github.com/ChrisTitusTech/winutil/assets/20649872/e1a16b5f-0e28-40d3-944e-442181b453ab)

**Comment by ValuableTEA** [comment]
> **Describe the bug**
> When I try to install Discord and EA app it tells me it can't find an applicable installer for Discord and then it doesn't even start installing the EA app.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to 'Install'
> 2. Click on Discord and EA app and then 'Install selected'
> 3. See error
> 
> **Screenshots**
> ![Skärmbild 2024-01-27 121213](https://github.com/ChrisTitusTech/winutil/assets/20649872/e1a16b5f-0e28-40d3-944e-442181b453ab)

Experiencing the same issue with attempting to install Python, Rust, Total Commander, via the Winutil. I think this issue may be wider spread.

**Comment by RocGod** [comment]
Checked the issue from winget, looks they have a [ticket](https://github.com/microsoft/winget-cli/issues/2176) on their side as well. They are discussing --scope=machine or --scope=user or some other fixes that can resolve this issue.

**Comment by definedfate** [comment]
Discord should work but EA App is hit or miss. Not sure if it's a problem with Winget or EA / maintainer.

**Comment by raphcool12** [comment]
can't either
