### ISSUE TITLE
The list is starting to grow, really fast.

### ISSUE THREAD

**Issue by v-Kaefer** [ChrisTitusTech/winutil#1489]
**Is your feature request related to a problem? Please describe.**
Yes, i believe the apps/features list is starting to grow really fast, and getting kinda messy and tiring to look at the description of each program, if you want to try something new.

**Describe the solution you'd like**
I'm new to Powershell, so i don't know too much to make a pr for that, but what about, making sub-sections?

**Describe alternatives you've considered**
Like in the **Games** section, we could have "_launchers_", "_multi-launchers_", "_base-games_", etc. But for each section, **when needed**.
What you guys think?

**Comment by Yuuh15** [comment]
I agree, would make discovering new software a lot easier. And in conjuction with this suggestion the sub-headers should be collapsible

**Comment by Nathan-Shea** [comment]
Agreed, it's starting to get a bit overwhelming now. I think collapsible subsections are a necessity at this point.

**Comment by v-Kaefer** [comment]
> Agreed, it's starting to get a bit overwhelming now. I think collapsible subsections are a necessity at this point.

I have no experience with ps, but i believe i learned how to implement that, i'm still testing it. Once it's working properly, i'll submit a pr.
