### ISSUE TITLE
Help text / Tooltips

### ISSUE THREAD

**Issue by simsrw73** [ChrisTitusTech/winutil#149]
I've learned a lot from watching your channel. Huge respect for you and your work. But I'm extremely reluctant to run this because it doesn't give any information on what it is doing. Probably more a character flaw in me, but I'm reluctant to click an option without knowing what it is changing and in what way. Some kind of help text or tooltips with a brief description of what each item does, preferably followed by a slightly more detailed description of how it is doing it would make me feel more comfortable. I've scanned through the code and manually applied a few mods, but I'm reluctant to use the UI without more details upfront so I can make an informed choice.

Also, it would be nice if it detected and displayed the current state of any tweaks or apps already applied before the tool has been run.

Again huge respect. Probably more a character flaw in me, but I wanna feel really secure when I'm clicking options that are messing around deep in the guts of my systems.

**Comment by ChrisTitusTech** [comment]
Agreed about expanding the readme and tooltips. I'll will definitely expand these in the future.

**Comment by ChrisTitusTech** [comment]
Consolidating this issue with #147
