### ISSUE TITLE
Nano URL invalid

### ISSUE THREAD

**Issue by RudiKlein** [ChrisTitusTech/winutil#1490]
When installing Nano, the following issue occurs:

Checking if Winget is Installed...
Winget Already Installed
Found GNU Nano [GNU.Nano] Version 2.7.5
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.nano-editor.org/dist/win32-support/nano-git-0d9a7347243.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
No package found matching input criteria.

Reason:
The URL is not correct, it is missing a trailing "9" in the filename:
Current one: https://www.nano-editor.org/dist/win32-support/nano-git-0d9a7347243.exe
Should read: https://www.nano-editor.org/dist/win32-support/nano-git-0d9a73472439.exe

**Comment by Yuuh15** [comment]
It might be a problem with winget itself, so it's out of the scope of the script. Trying to install through winget also fails.

**Comment by RudiKlein** [comment]
Will do

**Comment by jesjess243** [comment]
The choco package works, try that.

Maybe just a notice message that Chocolatey is required to install?

**Comment by RudiKlein** [comment]
I have had another look at it. The invalid reference is in Winget. No Winutil issue.

Sorry for the inconvenience.

Rudi
