### ISSUE TITLE
Windows Features from Config tab not geting installed

### ISSUE THREAD

**Issue by zzarac** [ChrisTitusTech/winutil#1496]
**Describe the bug**
Clean installation of Windows 11 ("world" setup) OS build 22631.3007 (January 2024), installed drivers and all updates.
Uninstalled most remaining bloat before starting winutil.
In winutil, first fixed winget, then ran "Desktop" recommended tweaks which all finished succesfully.
But when selecting any of the Features from "Config" tab and clicking "Install Features", I get this text in powershell window and nothing happens. Everything worked fine in previous OS build (December 2023).

===================================
---   Features are Installed    ---
---  A Reboot may be required   ---
===================================

**To Reproduce**
1. Install WIndows 11 OS build 22631.3007 (January 2024)
2. Start winutil
3. Click "Config" tab
4. Select any of the features
5. Click "Install Features"

**Expected behavior**
Selected windows features install and the world is fine.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/6088246/088d9c0e-aa26-4755-b657-d6ea8fc21946)

**Additional context**
When I try clicking "Install Features" again, the info text "features being installed, a reboot may be required" is printed again, as the screenshot shows.

**Comment by zzarac** [comment]
Maybe I should have added that I used OS.click website (https://os.click/en) to download the latest Windows build ISO (currently 22631.3007).

**Comment by DansNewLegs** [comment]
Same issue here, downloaded windows 11 from official site and used microwim too on it.

**Comment by zzarac** [comment]
I just tried installing some windws features with winutil on a separate machine that is still on Windows 11 21H2, and it didn't work there either.

I guess there must have been some pull request that misbehaved because I used winutil in the past on that machine with no problems, and windows there has not been updated for ages.

**Comment by Yuuh15** [comment]
After some testing the issue seems to have started at the  commit to main branch made by Chris in 2024-01-12. The logic of checking if the checkboxes are selected changed a lot in that commit, and it seems to be causing it.

**Comment by Garou7** [comment]
Same here on Windows 11 Pro 22H2 (official iso not MicroWin):
![fe](https://github.com/ChrisTitusTech/winutil/assets/113905482/c038e85b-b364-4f0c-beea-b511aeaa8901)

**Comment by zzarac** [comment]
Fixed in last update.
