### ISSUE TITLE
allow user to not install chocolatey

### ISSUE THREAD

**Issue by moeishome** [ChrisTitusTech/winutil#1498]
entirely understandable if this is rather low priority but id appreciate a prompt before installing chocolatey. i love this tool but i typically dont install other programs using it and id like if it didnt require me to install chocolatey (to then install winget), is all. offering an option to use scoop instead would also be appreciated if more of the program rests on having programs installed by chocolatey than just the application installers. thanks!

**Comment by definedfate** [comment]
Ask Microsoft to make Winget easy to deploy.

**Comment by moeishome** [comment]
> Ask Microsoft to make Winget easy to deploy.

fair enough. ultimately i dont know what goes on behind the scenes and if this way is significantly easier or less broken then i wouldnt have any objection to that.

**Comment by dreamsyntax** [comment]
You can run this instead to use winutil without installing chocolatey:
`(irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex`
credit: https://github.com/ChrisTitusTech/winutil/issues/1118#issuecomment-1850868015

**Comment by moeishome** [comment]
sweet. appreciated.
