### ISSUE TITLE
Install issues, WinGet and failed apps

### ISSUE THREAD

**Issue by iiTranquility** [ChrisTitusTech/winutil#1502]
**Describe the bug**

Hi!

First off, I had issues where nothing would install, there was more "command parameters" than needed.
I searched the issue on GitHub and found that I had to reinstall WinGet.

I wish this issue was posted inside of the installer, it would save time and stress.

My 2nd issue, there were 3 apps that didn't install.
Discord, Samsung Magician and ImageGlass.

**To Reproduce**

Have an entirely new Windows 11 install, try and install some apps, it'll fail first time due to WinGet not getting installed properly.

Try to install your desired apps as well as the 3 listed above.

**Expected behavior**
The installer should either automatically reinstall WinGet upon failure, or inform the user to do this.

The installer should install the above 3 apps without issues.

**Screenshots**
```
No applicable installer found; see logs for more details.
Search failed for: Discord.Discord
No applicable installer found; see logs for more details.
Search failed for: Samsung.SamsungMagician

(2/16) Found ImageGlass [DuongDieuPhap.ImageGlass] Version 9.0.9.1230
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
No suitable installer found for manifest: Microsoft.DotNet.DesktopRuntime.8 8.0.1
Error processing package dependencies, exiting...
```

**Additional context**

**Comment by RocGod** [comment]
I think the problem is from the winget itself... not from this utility...

**Comment by Yuuh15** [comment]
> I think the problem is from the winget itself... not from this utility...

Yeah... Recently had to reinstall Windows and winget came preinstalled totally borked. Should the default behavior be a reinstall of winget so to avoid this kind of issue?

**Comment by RocGod** [comment]
> > I think the problem is from the winget itself... not from this utility...
> 
> 
> 
> Yeah... Recently had to reinstall Windows and winget came preinstalled totally borked. Should the default behavior be a reinstall of winget so to avoid this kind of issue?

You can try to reinstall and see the issue is resolved or not... But not guaranteed, as the winget official is discussing this issue.

**Comment by iiTranquility** [comment]
> I think the problem is from the winget itself... not from this utility...


The first issue was down to winget entirely, but the failed app installations I have a feeling will be from this.

**Comment by theriverlethe** [comment]
Not sure about the others, but the version of Magician in the winget repo is absolutely ancient. So is Heroic Games Launcher. The winget repo just isn’t very good at this point, frankly.
