### ISSUE TITLE
winget failed to install

### ISSUE THREAD

**Issue by Grimmrp2** [ChrisTitusTech/winutil#1517]
When i run the tool i get winget failed to install

running powershell as admin  on win 11 

![image](https://github.com/ChrisTitusTech/winutil/assets/78448741/34c9ef37-0efd-43de-989b-df40fdb0f17c)

**Comment by Garou7** [comment]
Did U try WinGet reinstall?
![fix](https://github.com/ChrisTitusTech/winutil/assets/113905482/73896131-fadd-472f-aeaf-e598d1ca91ce)

**Comment by petterssonjonas** [comment]
install winget from microsoft/winget-cli repo,

**Comment by possumdoe** [comment]
Seems related to issues #1557 and #1571

I link the response from the other issue:
https://github.com/ChrisTitusTech/winutil/issues/1571#issuecomment-1928638539

Maybe next time include a bit more informations, like the version of `winget` and some logs :wink:

**Comment by maxy3d** [comment]
![winget failed](https://github.com/ChrisTitusTech/winutil/assets/22043941/2dd3aa58-7c7d-4a72-a6bb-e31011171838)
updating to latest winget. but when installing anyapp. Winget failed to install.

**Comment by TheAnonymousXAlt** [comment]
I think winget is just broken.(See image below)

![image](https://github.com/ChrisTitusTech/winutil/assets/127212152/f67c60e9-a418-45ca-b705-26559961a83d)
It won't install a package by microsoft.

**Comment by possumdoe** [comment]
@Grimmrp2 try attaching more informations like:
- the output of `winget --info` 
- the logs of the script failed run

@TheAnonymousXAlt try reporting directly to `winget-cli`

Seems like there is an existing open issue related to your error https://github.com/microsoft/winget-cli/issues/4099

**Comment by ithinkmax** [comment]
Same for me, I get error with every app I try to install. I tried to reinstall winget but nothing changed

<img width="862" alt="Screenshot 2024-02-07 080431" src="https://github.com/ChrisTitusTech/winutil/assets/44212536/59d884bb-53fd-4699-9824-e2bf73c24738">

**Comment by ubrider** [comment]
Same, Get installed works, but trying to install package no, either win 10 or win 11 (latest updates)

**Comment by nkap90** [comment]
I have exactly the same Winget version and failed to install error as the people above and no solution yet. The Winget reinstall does not fix it. I use Window 11 Pro (fresh install, latest updates).

Some extra info:

**- The output of winget --info:**
PS C:\Windows\system32> winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3085
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled

**- The logs of the script failed run**
2024-02-07 13:09:54.403 [CORE] WinGet, version [1.6.3482], activity [{3122D7E7-CA9F-4089-991D-D8826A1B5017}]
2024-02-07 13:09:54.403 [CORE] OS: Windows.Desktop v10.0.22631.3085
2024-02-07 13:09:54.403 [CORE] Command line Args: "C:\Users\Niels\AppData\Local\Microsoft\WindowsApps\winget.exe" --version
2024-02-07 13:09:54.403 [CORE] Package: Microsoft.DesktopAppInstaller v1.21.3482.0
2024-02-07 13:09:54.403 [CORE] IsCOMCall:0; Caller: winget-cli
2024-02-07 13:09:54.410 [CLI ] WinGet invoked with arguments: '--version'
2024-02-07 13:09:54.410 [CLI ] Leaf command to execute: root
2024-02-07 13:09:54.410 [CLI ] Executing command: root
2024-02-07 13:09:54.410 [CLI ] Leaf command succeeded: root

Hope someone can help, if there is any other information needed, please let me know. 
![chris-titus-tech-install](https://github.com/ChrisTitusTech/winutil/assets/159257691/3f208876-b6e8-4140-97f0-fcdfce56b4a6)

**Comment by clfmoher** [comment]
I ran chris titus utility  and has the following config > winget reinstall:

Start-Process : This command cannot be run due to the error: %1 is not a valid Win32 application.
At line:5506 char:5
+     Start-Process -FilePath "choco" -ArgumentList "install winget -y  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

keep getting 0x80072efd
when I run:
winget source add --name winget https://winget.azureedge.net/cache
error 0x80072ee7
