### ISSUE TITLE
Official ISO from Microsoft not accepted by MicroWin (not Media Creation Tool or Installation Assistant version)

### ISSUE THREAD

**Issue by mygitl2022** [ChrisTitusTech/winutil#1523]
Seems like Windows 11 ISO can be freely downloaded, without the media creation tool, I tried both, with regular User Agent in my browser, and after changing it  (tried iPadOS, ChromeOS, etc., gettting same options.

The highlighted ISO in screenshot (which says it is for VMs) is still giving me the same error.

![111](https://github.com/ChrisTitusTech/winutil/assets/105385292/bdaab48e-95e4-4a2d-a9c9-2bc33954c666)
![222](https://github.com/ChrisTitusTech/winutil/assets/105385292/79bc2943-d3fd-4610-9e24-7741b23c2bbf)

unable to download the official ISO any other way, this seems to be the latest official way to do this. Please help!

**Comment by ChrisTitusTech** [comment]
Interesting let me try this out.
