### ISSUE TITLE
can you add Straberry perl from perl.org please?

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#1524]
I see python on the list, but not perl. I am thinking of Strawberry perl from perl.org.  Could you add Strawberry perl please? This is a feature request.

**Comment by billytwotone** [comment]
I see in the YouTube videos that Chris' version of WinUtils has coloured boxes and they flash when you click on them.  I only have grey colours on my version of WinUtils. The grey buttons turn a bit greyer when I click on the buttons, but not coloured. Is your version a special demonstration version, or it is just that my system does not show the colours? I would like to have the colours appear.  I do not know if this is a bug or not.

**Comment by RocGod** [comment]
PR https://github.com/ChrisTitusTech/winutil/pull/1560 created

**Comment by billytwotone** [comment]
I do not know how to add a link to Strawberry perl.
