### ISSUE TITLE
Is Winutils black, grey, and white or coloured. (UK spelling)

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#1525]
I see in the YouTube videos that Chris' version of WinUtils has coloured boxes and they flash when he clicks on them. I only have grey colours on my version of WinUtils. The grey buttons turn a bit greyer when I click on the buttons, but not coloured. Is Chris's version a special demonstration version? I would like to have the colours appear. I do not know if this is a bug or not. I am using latest version of Windows 10 with WinUtil's laptop tweaks.

**Comment by Yuuh15** [comment]
Have you enabled dark mode? The light mode does not have any colors

**Comment by billytwotone** [comment]
What dark mode is this? I have not seen a facility on WinUtil to enable dark mode.

**Comment by Yuuh15** [comment]
Check the tweaks section, there should be a toggle for it

**Comment by billytwotone** [comment]
I see a button to enable or disable dark mode.  I thought that was something to do with the tweaks the Winutil does to Windows 10 or 11.  I tried to toggle it and it did not make any difference, anyway.

**Comment by ChrisTitusTech** [comment]
We are working to add a few more themes but right now it is only light and dark mode.

**Comment by billytwotone** [comment]
Wow
