### ISSUE TITLE
Completely broken.

### ISSUE THREAD

**Issue by TheAnonymousXAlt** [ChrisTitusTech/winutil#1531]
No modules work.

Demo:
![image](https://github.com/ChrisTitusTech/winutil/assets/127212152/c40de942-edd7-4cc2-8fef-5a1ac3eaccc7)
![image](https://github.com/ChrisTitusTech/winutil/assets/127212152/65d9f378-9f49-461b-a3f9-0e0680ba7a52)
![image](https://github.com/ChrisTitusTech/winutil/assets/127212152/65441f91-bef3-45bb-912a-1b42ec2a6642)

And that is for all modules and every setting.

**Comment by TheAnonymousXAlt** [comment]
Ok thanks!

**Comment by Grimmrp2** [comment]
> @TheAnonymousXAlt from what I understand, there is a bug in windows' winget app. The first step you need to do is go to config and click the 'force reinstall winget' button. This should be pretty obvious if you look at your error message there in red.

theres no force option
![image](https://github.com/ChrisTitusTech/winutil/assets/78448741/3785a25c-4299-40f2-8f38-d90e68c3c496)

**Comment by Grimmrp2** [comment]
> @Grimmrp2 🙄 the box you want to click is 'winget reinstall'. This will force the app to be installed again.

it fails

![image](https://github.com/ChrisTitusTech/winutil/assets/78448741/ce061e25-a313-453c-9b91-271f5f32b0b9)

**Comment by SbMan1** [comment]
I get the same. Still not working for me. I think it's my firewall. Can't seem to install new some new software now. Planning on a new clean Win11 OS sometime soon anyways.

**Comment by Yuuh15** [comment]
@SbMan1 try running this command in a terminal as administrator: `choco install winget -y --force`

**Comment by berlintay** [comment]
https://github.com/microsoft/winget-cli/releases/tag/v1.6.3482

try downloading the desktop installer, it might give it the fix needed, also you could be facing issues with tls

please let me know if this helps!

**Comment by LP-DSS** [comment]
I have the same problem. Cannot seem to get winget  and cannot find powershell command to force reinstall.  Any help would be appreciated.

**Comment by LP-DSS** [comment]
Also tried the following:

Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>choco install winget -y --force
Chocolatey v2.2.2
Installing the following packages:
winget
By installing, you accept licenses for the packages.
winget v1.6.3482 already installed. Forcing reinstall of version '1.6.3482'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading microsoft-vclibs-140-00 14.0.30704.0... 100%

microsoft-vclibs-140-00 v14.0.30704 (forced)
microsoft-vclibs-140-00 package files install completed. Performing other installation steps.
Downloading microsoft-vclibs-140-00
  from 'https://aka.ms/Microsoft.VCLibs.x86.14.00.Desktop.appx'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\Microsoft.VCLibs.x86.14.00.Desktop.appx (5.79 MB).
Download of Microsoft.VCLibs.x86.14.00.Desktop.appx (5.79 MB) completed.
Error - hashes do not match. Actual value was 'A7FB9D76E07B36D868179EB53FFD13740C25242176FA363F154798CF34EDD4A9'.
ERROR: Checksum for 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\Microsoft.VCLibs.x86.14.00.Desktop.appx' did not meet '3195DB914BEA1534EE73582CD483C548A929AED2799D305B3BBF7411BA7A6C7D' for checksum type 'SHA256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of microsoft-vclibs-140-00 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Progress: Downloading winget 1.6.3482... 100%

winget v1.6.3482 (forced) [Approved]
winget package files install completed. Performing other installation steps.
 The install of winget was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\winget'

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-vclibs-140-00 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.

C:\Windows\system32

Not sure if this helps or not. Just an FYI in case it does.

**Comment by berlintay** [comment]
Check this out


https://github.com/microsoft/terminal/issues/2369#issuecomment-535763987

if you have browser acess, go ahead and download it via the website
and install it



i think you need the x64 version https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by petterssonjonas** [comment]
I've tried installing the exe, no go, tried installing via choco with --ignore-checksum --force, no go. Winget is not found as a command.

**Comment by petterssonjonas** [comment]
Solved it, install winget from the microsoft/winget-cli repo.

**Comment by berlintay** [comment]
sometimes directly from source is best, search online, Microsoft has tons of documentation etc

**Comment by v-Kaefer** [comment]
> Solved it, install winget from the microsoft/winget-cli repo.

**Before anyone comes asking for it.**
https://github.com/microsoft/winget-cli/releases

**Comment by LP-DSS** [comment]
I am still unable to get it to work as well.  I did notice when I try to install anything from WinUtil. it is running a second copy of Powershell and then immediately closes and says winget install failed on the initial PS screen.

Thanks

**Comment by LP-DSS** [comment]
I've solved my issues. Thanks

**Comment by berlintay** [comment]
what solved the issue?

**Comment by ChrisTitusTech** [comment]
I made this easier with a force in winget reinstall.
