### ISSUE TITLE
Wizard to disable services

### ISSUE THREAD

**Issue by Parideboy** [ChrisTitusTech/winutil#1540]
Hey, everyone! I just stumbled upon this program with a pretty neat feature, in my opinion.

It prompts a few questions and then recommends which services to either disable entirely or set to manual, all based on your answers to the questionnaire.

It's especially handy if you're crystal clear about what your machine is up to:

Is it going to be hooked up to a printer?
Will it be using Bluetooth?
Are you planning to use biometric authentication?

Here are some screenshots:

![image](https://github.com/ChrisTitusTech/winutil/assets/8842736/ec33ca62-dc17-44a6-9ae1-a8e2c4a07a1a)
![image](https://github.com/ChrisTitusTech/winutil/assets/8842736/ec5d28e6-0dd2-433b-b52e-111f1eb3f6f3)

Is maintaining and compiling such a "list" doable?

Thanks in advance for your time, love the project!

**Comment by ChrisTitusTech** [comment]
I like this idea. I actually manually do this with the tweaks.json file in the project now, but a GUI for powerusers like this would be nice.
