### ISSUE TITLE
Config page missing after latest commit

### ISSUE THREAD

**Issue by Yuuh15** [ChrisTitusTech/winutil#1545]
**Describe the bug**
Everything located in the config is missing after the last merge to main

**To Reproduce**
1. Go to iwr -useb https://christitus.com/win | iex
2. Click on the config tab
3. Nothings loads

**Expected behavior**
All the settings should be there

**Screenshots**
![powershell_ec7UM0P5le](https://github.com/ChrisTitusTech/winutil/assets/97139700/bbf6dd83-8ce5-4167-b8ad-a70227220284)

**Additional context**
It may have to do with the panels change.

**Comment by samdh90** [comment]
I am also showing the same issue after today's commit. If this is helpful, here is the output in PowerShell, looks like a JSON issue;

![image](https://github.com/ChrisTitusTech/winutil/assets/61171359/66de3eec-ce58-46e8-a5aa-e40be018214f)

**Comment by nWestie** [comment]
I am also having this error, shows the same message as above and does not load config page.
Seems like the error would be from some issue in the changes to [config/feature.json](https://github.com/ChrisTitusTech/winutil/pull/1541/files#diff-16d68b55441d60ee6760c93613bbd082dedf6fe7155858bdad88a63b417ccde8) but I don't have the time to dig in further then that right now

**Comment by Yuuh15** [comment]
@nWestie I opened a pull request with some changes to the JSON file and they seem to be working, but I would appreciate testing the changes in another PC.

**Comment by L0stTitan** [comment]
Just started using this utility. This is the only issue I have identified so far.  Same as noted above.  This is on a fresh install of W10 22H2. Not sure if this is a problem with the app or I missed some prereq in configuring my system.  Please advise.

**Comment by Yuuh15** [comment]
@L0stTitan Nah, it's just a problem with the script, the only thing that can be done is wait for the fix

**Comment by whatcorey** [comment]
Don't bother trying to install any apps from the main thing, because that doesn't work either. I guess we just have to wait for a fix

**Comment by exciar** [comment]
it works somehow when using Powershell 7

**Comment by zeonos** [comment]
I have the same and when i tried to run the tweaks listed here, it also killed explorer without reopening it, it was around the time it killed the onedrive process.

Windows version 22H2 (19045.3803), only thing done after install is running the following two powershell commands

- set-executionPolicy unrestricted
- irm https://christitus.com/win | iex
![1](https://github.com/ChrisTitusTech/winutil/assets/6930544/b02d4e6a-fad8-4d9a-a831-17d662caa618)
![2](https://github.com/ChrisTitusTech/winutil/assets/6930544/a8f3bba5-5643-4264-9c25-22a94f62e013)
![3](https://github.com/ChrisTitusTech/winutil/assets/6930544/c6a3a35d-80d8-4665-bd2d-cc5c82d463dc)

**Comment by S0litaire** [comment]
Yup. have the same issue in latest build : 

 - JSON conversion error at start
- Empty "config" tab 
- explorer being killed when running "get installed" then "Upgrade All" routines. 


Running Windows11 insider Preview (Canary Channel) build : 26040.1000 rs_PreRelease

**Comment by nWestie** [comment]
Can confirm #1547 fixes the issue I was having with the config tab: The Error code at startup is cleared and the config tab works.
#1554 Also seems to fix the JSON issue, it does roughly the same thing: (formats InvokeScript option by squashing to single line whereas #1547 puts each item as an array item)

I'm not getting the error with explorer crashing, so not sure if that's cleared up.

I'm Running : 
Edition	Windows 11 Home
Version	22H2
OS build	22621.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by ChrisTitusTech** [comment]
should be fixed in #1556 let me know if that works for you guys

**Comment by nWestie** [comment]
Yup, the main branch appears to be working now 👍
