### ISSUE TITLE
Micrown and windows 10  

### ISSUE THREAD

**Issue by ttx99** [ChrisTitusTech/winutil#1551]
Microwin has been able to make a windows 10 iso without error should I proceed with this ISO install? Anyone tried?
I have alot of apps so I wanna ask first if its ready to use.

**Comment by ChrisTitusTech** [comment]
Yes it can be hit and miss. Some version of Win10 use install.esd instead of install.wim which is a higher compression microsoft sometimes uses that will cause the installer to fail.
