### ISSUE TITLE
Include this in winutil 

### ISSUE THREAD

**Issue by Galamooth** [ChrisTitusTech/winutil#1552]
Add this tool that does a phenomenal job. Or include these settings in winutil 

It is open source. It is constantly updated and it is wonderful

https://github.com/RedDot-3ND7355/MPO-GPU-FIX

Please review the tool, it has many functions that fix various problems. 
![IMG_20240203_043114267](https://github.com/ChrisTitusTech/winutil/assets/90434643/b61a0a21-600d-470a-83ec-70078e96becc)

**Comment by definedfate** [comment]
These are just registry keys but would be nice to have its own tab under "gaming" you can select.

**Comment by RedDot-3ND7355** [comment]
Thanks for reffering my project, Would be a very nice inclusion for the community! 💯

**Comment by RedDot-3ND7355** [comment]
@og-mrk some functions will not work by default if no gpu is detected and will lock the features that requires them, It's safe to add to the program list unless a different requirement is needed. Don't be shy to holla at me if a different requirement is needed, I might be able to adjust :)

Have a nice day!

**Comment by og-mrk** [comment]
> @og-mrk some functions will not work by default if no gpu is detected and will lock the features that requires them, It's safe to add to the program list unless a different requirement is needed. Don't be shy to holla at me if a different requirement is needed, I might be able to adjust :)
> 
> Have a nice day!

@RedDot-3ND7355 After looking into MPO-GPU-FIX App, I wasn't able to find it on neither Choco nor Winget (the package managers used as backend for installing/uninstalling/updating programs on WinUtil), so I'm afraid I can't add your app without it being in one of the aforementioned package managers.

Another approach of adding apps that aren't found in any "mainstream" package managers (e.g. choco, winget, scoop, etc...), is to make a special script for each app that's ran by WinUtil to install said app (this approach is similar to Choco if the interested in learning more).

This approach is not favorable as it'll add extra maintenance and would render this "special install script for XYZ app" useless if something changes, like URLs, install parameters, and so on... Not to mention possible security problems that may arise from this approach. Therefore, I recommend adding your app to WinGet and/or Choco packages repo so we can add it to the list.

Hope you understand why we haven't added it earlier, and if you've any questions, feel free to send them here 😄 Have a nice day as well!
