### ISSUE TITLE
Json Script

### ISSUE THREAD

**Issue by FalconStrike** [ChrisTitusTech/winutil#1553]
When trying to Open the application theirs a Json Script error and the config page is not showing up anymore? 
![Screenshot 2024-02-03 061718](https://github.com/ChrisTitusTech/winutil/assets/59585508/5fb07ecf-854f-49f1-9427-f8da3c677003)
![Screenshot 2024-02-03 062020](https://github.com/ChrisTitusTech/winutil/assets/59585508/7d7eb383-ce58-498a-9b85-d5fe8e5ebff8)

Plz Let me know if you are also getting the error message or if It gets fixed.

**Comment by Fejby** [comment]
I have the same problem

**Comment by alcio1** [comment]
Same problem here

**Comment by nguyendoan15082006** [comment]
I got same problem too

**Comment by enigma072485** [comment]
Yep same issue, with the exception of the config page not showing. The page is showing but not installing any programs. The tweaks page is working just fine tho. I'm on windows 10 x64.

**Comment by zeonos** [comment]
Same issue as reported here: #1545

**Comment by ChrisTitusTech** [comment]
should be fixed in #1556 try relaunching now.
