### ISSUE TITLE
Kaspersky standard is blocking the tool.

### ISSUE THREAD

**Issue by Hellements** [ChrisTitusTech/winutil#156]
**Describe the bug**
I have Kaspersky Standard and when I try to load the tool from my PowerShell(admin) it will not open, and I get a red text wall. When I disable Kaspersky, it works fine.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/88634350/190506991-2b8739f0-6009-4d38-ba1d-169194cc8167.jpg)

**Additional context**
I'm on win10pro 21h2 build 190441889

**Comment by gustavoxxgg** [comment]
The same thing is happening to me (I use Karspersky Security Cloud)
winver: W11Pro 21H2 build 22000978
Looks like it was flagged as malware by Kaspersky Servers
![image](https://user-images.githubusercontent.com/69378132/192045111-848c48a5-cdb1-449c-8b53-ad7075de632b.png)

**Comment by ChrisTitusTech** [comment]
Known issue with many antiviruses. Short of converting it all to C# program there isn't much I can do.
