### ISSUE TITLE
Remove Adobe Creative Cloud Bug

### ISSUE THREAD

**Issue by LunaryX** [ChrisTitusTech/winutil#1563]
**Describe the bug**
"Remove Adobe Cloud" from the "Config" section is making the tool unresponsive and crash.
I launched the tool, disabled few stuff and when i went to the "Config" section, i clicked on "Remove Adobe Cloud" and the tool basically became unresponsive, it crashed.

**To Reproduce**
1. Go to "Config" section
2. Click on "Remove Adobe Cloud"
3. See error ( the application just crashes )

**Expected behavior**
I expect to remove every single bloatware from Adobe Creative Cloud and disable it fully.

**Screenshots**
https://imgur.com/a/IALPXRM

**Comment by LunaryX** [comment]
Yes, I did. Sometimes it works, sometimes it just crashes the program
for some reason.

**Comment by mrkenhoo** [comment]
I can't seem to reproduce your issue.

Could you please upload the transcript file?

In the Windows Explorer address bar type `%TEMP%` and you should be in your user's temp folder. In that directory there should be a `Winutil.log` file, after launching winutil.

**Comment by LunaryX** [comment]
I tried something else. I fully uninstalled Chocolatey, deleted every entry
this script has made, and then ran the program again. It seems like now it
works. Maybe it was an unforeseen issue with my Windows. Although, you can
possibly implement a try-catch block in case of an error so that the
program won't crash anymore, and it can still run just fine.

**Comment by mrkenhoo** [comment]
I'm glad you got to sort it out.

Will keep that in mind for the next PR, thanks for the info.
