### ISSUE TITLE
Microwin oscdimg was not found how to solve?

### ISSUE THREAD

**Issue by stunner999** [ChrisTitusTech/winutil#1564]
oscdimg was not downloaded can not proceed

[INFO] oscdimg.exe SHA-256 Hash:
Hashes do not match. File may be corrupted or tampered with.

**Comment by GuillemFo** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/132559287/a391a0a5-fb27-4e64-8cfd-9cc65047215a)
![image](https://github.com/ChrisTitusTech/winutil/assets/132559287/954cf053-1636-4b03-8c9d-87671b17d07f)
The path error is understandable but i dont get why is not able to download the tool even forcing to download from github.

**Comment by GuillemFo** [comment]
Fixed it downloading the proper tool, creating a folder named releases and pasting the tool inside.

**Comment by ttx99** [comment]
Sorry for late reply, but mine actually worked after some tries, weird.

**Comment by ttx99** [comment]
how to close this thread?
