### ISSUE TITLE
Winget failed to install

### ISSUE THREAD

**Issue by santhosh110599** [ChrisTitusTech/winutil#1571]
After I try to install an app from Windows utility tool, it says Winget failed to install despite installing it.

**Comment by santhosh110599** [comment]
Thank you for your suggestion. 

I tried what you said, but apparently I have the latest version of winget. When I tried using the utility in another system (which also has the same version of winget), I was able to install applications. 

What is going on here?

**Comment by possumdoe** [comment]
Maybe include the version of `winget`, seems like version `v1.2.10691` **isn't working properly** (there are a lot of issues about winget not installing and I have experienced myself problems on a fresh install of Windows 23H2)

Seems like a solution to a similar issue ( #1557 ) as been already committed by @ChrisTitusTech and the problem may be fixed when merged into `main`

In the meantime you could try to reinstall `winget` yourself
Here some options:
- using the official release on Github: https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
- choco: `choco install winget --force`

**Comment by ChrisTitusTech** [comment]
This is now fixed in the latest update today.

**Comment by TheAnonymousXAlt** [comment]
I think winget is just broken.(See image below)

![image](https://github.com/ChrisTitusTech/winutil/assets/127212152/f67c60e9-a418-45ca-b705-26559961a83d)
It won't install a package by microsoft.

**Comment by Yuuh15** [comment]
Guys, is anyone else having problems to install any of the applications? I can't install any applications after the latest commit: 
![WindowsTerminal_bz49CSSVAB](https://github.com/ChrisTitusTech/winutil/assets/97139700/cf808e16-278a-48db-9335-577673fad630)

**Comment by ubrider** [comment]
> Guys, is anyone else having problems to install any of the applications? I can't install any applications after the latest commit: ![WindowsTerminal_bz49CSSVAB](https://private-user-images.githubusercontent.com/97139700/302802346-cf808e16-278a-48db-9335-577673fad630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjU0MDAsIm5iZiI6MTcwNzI2NTEwMCwicGF0aCI6Ii85NzEzOTcwMC8zMDI4MDIzNDYtY2Y4MDhlMTYtMjc4YS00OGRiLTkzMzUtNTc3NjczZmFkNjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDAwMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMDljNzY3MTJlODc4MWMzNjdjNTBmYTFlZDhkZDlhZWY0N2Q4OWNlZWMxOTJjOWJiNTkxOTU1YTY0NjI1OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q-8-F-9aItoBbRYzlHcWTLoSQ1EpJg6pSEbLEYcjIlg)

Got this too i thought it was my windows 11, as i just installed it first time on my laptop hours ago.

**Comment by prakhar64** [comment]
> Guys, is anyone else having problems to install any of the applications? I can't install any applications after the latest commit: ![WindowsTerminal_bz49CSSVAB](https://private-user-images.githubusercontent.com/97139700/302802346-cf808e16-278a-48db-9335-577673fad630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODMxMzEsIm5iZiI6MTcwNzI4MjgzMSwicGF0aCI6Ii85NzEzOTcwMC8zMDI4MDIzNDYtY2Y4MDhlMTYtMjc4YS00OGRiLTkzMzUtNTc3NjczZmFkNjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA1MTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNjA1Y2Y5MWRiZGZhNzBhOTU4MDE4ZWZmZDRkODllZGY4MzRhZTQzY2UxOTA0NWRmMmJiYjBjYTI2YzcyZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-CoadQy2NBrc2rkbNAv6SwvdIwbwgeIALIyQYwU9_A)

Facing the same issue since today. I forced a Winget reinstall with `choco install winget --force` just in case that was the issue, but it didn't help. I'm guessing that something broke with the new commit, as installations worked fine for me until yesterday on three other PCs. Happy to assist in any way to help fix this.

**Comment by bca009** [comment]
I have the same error message Sent from my iPadOn Feb 6, 2024, at 10:23 PM, Prakhar Srivastava ***@***.***> wrote:﻿

Guys, is anyone else having problems to install any of the applications? I can't install any applications after the latest commit: 

Facing the same issue since today. I forced a Winget reinstall with choco install winget --force just in case that was the issue, but it didn't help. I'm guessing that something broke with the new commit, as installations worked fine for me until yesterday on three other PCs. Happy to assist in any way to help fix this.

**Comment by nepumax** [comment]
Got the same error. Did this from [here](https://github.com/ChrisTitusTech/winutil/issues/826#issuecomment-1592032180), but it didn't help.

> You can bypass the store with the following commands to get winget installed:
> 
> ```
> Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
> Install-Script -Name winget-install -Force
> winget-install.ps1
> ```

**Comment by nkap90** [comment]
Got this same error; this error is also discussed [here](https://github.com/ChrisTitusTech/winutil/issues/1517), but no solution yet.

**Comment by Kupie** [comment]
I've ran into the same issue on two HyperV VM's I spun up today/yesterday, and this worked from above:

> Got the same error. Did this from [here](https://github.com/ChrisTitusTech/winutil/issues/826#issuecomment-1592032180), but it didn't help.
> 
> > You can bypass the store with the following commands to get winget installed:
> > ```
> > Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
> > Install-Script -Name winget-install -Force
> > winget-install.ps1
> > ```

**Comment by prakhar64** [comment]
An update from my side -- I'm no longer facing this issue. Things seem to have resolved themselves. Is that the case with everyone else, too?

**Comment by SmartInteractiveGroup** [comment]
Having the same problem - new windows 11 pro on lenovo

<img width="339" alt="image" src="https://github.com/ChrisTitusTech/winutil/assets/16972436/209d54a8-58c0-4f05-8fa7-44b4cd22196a">


<img width="245" alt="image" src="https://github.com/ChrisTitusTech/winutil/assets/16972436/487b89ae-6163-4835-8c41-b67ff63de467">


the same on msi laptop works fine

**Comment by 4budab1** [comment]
Solution
https://github.com/microsoft/winget-cli/issues/725#issuecomment-835394620

**Comment by anthonyrpitts** [comment]
Hi All, I was having the same issues today, November 5, 2024. i was doing a fresh install on Windows 11 23H2 22631.2861.

I discovered I needed to upgrade the terminal interface. For some unknown reason, as soon as I installed Windows Terminal directly through winget. Winget showed there where two apps that needing upgrading for me and Microsoft.WindowsTerminal was one of them. Once I installed the upgrade, opened Windows Terminal Version: 1.21.2911.0. 

I went to `irm christitus.com/win | iex` I was then able to see winget was installed and it finally started installing apps from the WinUtil. I feel the WinUtil will be broken, if you try to use the powershell terminal straight from a fresh install right out of the box.

**Comment by Nyyhaus** [comment]
> Got the same error. Did this from [here](https://github.com/ChrisTitusTech/winutil/issues/826#issuecomment-1592032180), but it didn't help.
> 
> > You can bypass the store with the following commands to get winget installed:
> > ```
> > Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
> > Install-Script -Name winget-install -Force
> > winget-install.ps1
> > ```

This did the trick for me! Thank you!
