### ISSUE TITLE
Snappy Driver Installer Origin not installing

### ISSUE THREAD

**Issue by Cyberbeast93** [ChrisTitusTech/winutil#1576]
i tried installing snappy driver installer origin a few times now but keep getting the same error, 

"Installer hash does not match; this cannot be overridden when running as admin"
![powershell_C4PjlAryiB](https://github.com/ChrisTitusTech/winutil/assets/159113530/8270bdfa-23e7-43b2-876e-db00adca3cbc)

**Comment by stunner999** [comment]
question where is the location of the file after downloaded?

**Comment by Cyberbeast93** [comment]
> question where is the location of the file after downloaded?

"C:\Users\Ernest\AppData\Local\Temp\WinGet\GlennDelahoy.SnappyDriverInstallerOrigin.1.12.18"

**Comment by definedfate** [comment]
Winget issue. 
Happens with EA App as well.

**Comment by Yuuh15** [comment]
New commits on test branch might fix the issue. For now the way is to go to the official site.

**Comment by ChrisTitusTech** [comment]
Just commited this to main, should work now.

**Comment by bca009** [comment]
Thanks Sent from my iPadOn Feb 6, 2024, at 1:39 PM, Chris Titus ***@***.***> wrote:﻿
Closed #1576 as completed.
