### ISSUE TITLE
MicroWin does not create iso

### ISSUE THREAD

**Issue by DRYN07** [ChrisTitusTech/winutil#1577]
Does the program modify the original iso, or create a new one? Because it asks for a save location when creating, but there's nothing there after it's finished.

**Comment by tajinder400** [comment]
So, I looked into this. I found on the last step where it's actually trying to create the ISO file, it'll throw an error. I expect looking at the logs (Which I'll post below), that even specifying a scratch directory, it attempts to reference oscdimg.exe from your users home folder. This does not exist in most cases. I'll see if I can find a work around, if not, if time allows, I'll see if I can update the code.

Error shown here:

`MethodInvocationException:
Line |
3629 |          $oscdimgProc.Start()
     |          ~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'oscdimg.exe' with working directory 'C:\Users\MyUser'. The system cannot find the file specified."
MethodInvocationException:
Line |
3630 |          $oscdimgProc.WaitForExit()
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."`

**Comment by tajinder400** [comment]
Okay, so I made this work on my end. You should make sure oscdimg.exe is in the following locations:

C:\Users\{YourUser}\releases\oscdimg.exe
&&
C:\Users\{YourUser}\oscdimg.exe

It's likely not meant to be like this, but if you do this it SHOULD work for you. If you're still running into issues even after that, make sure to check your Powershell/CMD/Terminal app you used to run winutil for error information. It's usually pretty informative.

**Comment by DRYN07** [comment]
Thank you for the fast answer!

I tried this but unfortunately, i got a similar error but without path :D

![image](https://github.com/ChrisTitusTech/winutil/assets/29770761/5b1757ee-36b8-4f1d-9106-a70e8dcc9688)

**Comment by ChrisTitusTech** [comment]
couple solutions... 
1. Check the box to copy the oscdimg from github
2. install windows adk `choco install windows-adk`

**Comment by DRYN07** [comment]
I installed adk, pasted releases folder / exe file in users folder, system32 folder, root folder, checked the mentioned box but I get the same error only on another line :/

Any other idea what should I try by any chance?

Thank you

![image](https://github.com/ChrisTitusTech/winutil/assets/29770761/f675826a-010d-437a-a5c1-16e1204d3625)

**Comment by DRYN07** [comment]
Yes, that was one of the issues, thanks :)

This solved the error messages although the created ISO does not exist anywhere on the machine, the folder is always empty, no matter what destination I give. Any idea about this by any chance?

![image](https://github.com/ChrisTitusTech/winutil/assets/29770761/0218d8f6-dc05-4c26-9762-82edf9f6ae8d)

**Comment by DRYN07** [comment]
I would appreciate any suggestion about this :)

**Comment by CodingWonders** [comment]
> I would appreciate any suggestion about this :)

Maybe OSCDIMG is failing and the script doesn't tell anything about the error. I'll check the code of the OSCDIMG procedure later for error code detection and will work on one if there isn't said check.

**Comment by ChefPanda34** [comment]
Hi i try to many times make microwin but always get this issue

<img width="1175" height="610" alt="Image" src="https://github.com/user-attachments/assets/baa707c2-2d7a-4247-aac3-2b5bfa6cdd2c" />
