### ISSUE TITLE
Bug: Some tweak ends up disabling all background applications causing things like my VPN client to fail

### ISSUE THREAD

**Issue by richardphi1618** [ChrisTitusTech/winutil#158]
**Describe the bug**
something in the utility disables background applications and it has unintended side effects

in my case it caused RasClient to have issues causing my VPN to fail

**To Reproduce**
1. run tweaks with desktop settings

**Expected behavior**
uh maybe not that?

**Screenshots**
![image](https://user-images.githubusercontent.com/38547621/190748784-d5c1842e-9791-43a1-8fa3-3f3d03e29903.png)

**Additional context**
was using the azure vpn client and when it was able to get my credentials but unable to connect I knew I had issues. 

after some google searching I found this:
https://answers.microsoft.com/en-us/windows/forum/all/azure-vpn-problem/7592ee0b-e2e9-4f77-815c-f7ebd8d3588a

after being unable to find any settings to re-enable background tasks I had to do the following:
https://www.elevenforum.com/t/enable-or-disable-background-apps-in-windows-11.923/

**Comment by ChrisTitusTech** [comment]
A long time ago I used to mess with background apps, but these days I leave it on stock settings.

This could be tied to ipv6 as some vpns need that. I adjusted the ip helper service from manual to automatic just incase.
