### ISSUE TITLE
The Raspberry Pi Imager is not installing

### ISSUE THREAD

**Issue by AlexMayne5** [ChrisTitusTech/winutil#1580]
**Describe the bug**
The Raspberry Pi Imager is not installing with error and got the same results after reinstall of winget
**To Reproduce**
1. reinstall winget using button
2. on verstion 24.02.03 of the script click the check box for Raspberry Pi Imager
3. click install Selected
4. see the error 

**Expected behavior**
uses WinGet to install Raspberry Pi Imager

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/46424598/7af18d36-e900-4d5c-ab98-4258469ed822)

**Additional context**
N/A

**Comment by ubrider** [comment]
Hi i got the same on win 11 23h2 for whatever package...

**Comment by possumdoe** [comment]
In the `winget-pkgs` [repository](https://github.com/microsoft/winget-pkgs) the package `RaspberryPiFoundation.RaspberryPiImager`'s [manifest](https://github.com/microsoft/winget-pkgs/blob/5a46638be8db55e8224593afc21526d0a1aba0d8/manifests/r/RaspberryPiFoundation/RaspberryPiImager/1.8.3/RaspberryPiFoundation.RaspberryPiImager.installer.yaml) doesn't specify the installation scope.

In the script the line that installs the packages is the following:
```powershell
winget install -e --accept-source-agreements --accept-package-agreements --scope=machine --silent RaspberryPiFoundation.RaspberryPiImager
```

So maybe the restriction to `--scope=machine` cause `RaspberryPiFoundation.RaspberryPiImager` installation to fail.

The same error occurs in the issue #1494  with [`TorProject.TorBrowser`](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+path%3A%2F%5Emanifests%5C%2F.*installer.yaml%2F+%22Scope%3A+machine%22+TorProject.TorBrowser&type=code), [`SomePythonThings.WingetUIStore`](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+path%3A%2F%5Emanifests%5C%2F.*installer.yaml%2F+%22Scope%3A+machine%22+SomePythonThings.WingetUIStore&type=code), [`Nvidia.GeForceNow`](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+path%3A%2F%5Emanifests%5C%2F.*installer.yaml%2F+%22Scope%3A+machine%22+Nvidia.GeForceNow&type=code) which do NOT specify the installer for the machine scope.

Other apps, like [`Google.Chrome`](https://github.com/microsoft/winget-pkgs/blob/5a46638be8db55e8224593afc21526d0a1aba0d8/manifests/g/Google/Chrome/121.0.6167.140/Google.Chrome.installer.yaml#L4) or [`Mozilla.Firefox`](https://github.com/microsoft/winget-pkgs/blob/5a46638be8db55e8224593afc21526d0a1aba0d8/manifests/m/Mozilla/Firefox/97.0/Mozilla.Firefox.installer.yaml#L4), specify the installer for the machine scope.

You can see which packages contains this by using the Github's search functionality:
![image](https://github.com/ChrisTitusTech/winutil/assets/81775758/9ff91a8d-c21a-4e25-bf2e-7d5197009ac6)
![image](https://github.com/ChrisTitusTech/winutil/assets/81775758/5862c495-c583-4a1e-b8cd-46d1151256ee)


This is the search string I used:
`repo:microsoft/winget-pkgs path:/^manifests\/.*installer.yaml/ "Scope: machine" Package.Name`

Imho this is the reason why the package will fail to install through the script.

**Comment by shrimp332** [comment]
nepnep.neofetch-win also has this problem
