### ISSUE TITLE
Program Requests

### ISSUE THREAD

**Issue by BackinService** [ChrisTitusTech/winutil#160]
I would like to suggest the additional installs if possible:

FoxPDF, it has a Typewriter function that is easy to use for those who don't pay for DocuSign, etc.

And to add OnlyOffice   it is compatible with Microsoft office and is way lighter on resources for older laptops.    I think libre office has been leapfrogged, at least for my use of it.

another utility request is f.lux for those of us with night jobs to keep our eyesight.

Thank you!

**Comment by ChrisTitusTech** [comment]
Putting in #250
