### ISSUE TITLE
Winutil not working

### ISSUE THREAD

**Issue by santhosh110599** [ChrisTitusTech/winutil#1608]
<img width="679" alt="Screenshot 2024-02-12 205412" src="https://github.com/ChrisTitusTech/winutil/assets/159008012/1ced204d-69e8-40f2-abde-eeb1a11b8747">

This appears everytime I try to install a package. Can anyone help with the issue?

**Comment by v-Kaefer** [comment]
Can you provide a screenshot of the **whole** CLI, when trying to download an application? And try to install a single application at a time.

**Comment by ChrisTitusTech** [comment]
you might also run reinstall winget from config tab.

**Comment by santhosh110599** [comment]
<img width="871" alt="Screenshot 2024-02-22 092425" src="https://github.com/ChrisTitusTech/winutil/assets/159008012/94c12306-a7b1-4772-a6fb-f21969d8d4f7">

This is what I get.

**Comment by santhosh110599** [comment]
@v-Kaefer I install one application at a time. Still not working :(

**Comment by santhosh110599** [comment]
@ChrisTitusTech I tried that as well. Not helping..

**Comment by zouzounos3** [comment]
I can't download Tor browser from the utility only from their site.

**Comment by Lassebq** [comment]
Cant get it working either, reinstalling winget leads to an error, seems like a dependency called microsoft-vclibvs fails to install

**Comment by v-Kaefer** [comment]
Yeah guys, now im having the same problems, is something with winget itself.

**Comment by pbesysadmin** [comment]
I've used the util for months now.  But recently (as of 3/3/2024), I get the same error. 
I've run it from a fresh install of windows 11 22H2 and windows 11 23H2.  Same thing.
On a PC that it ran from a few months ago, it still runs fine.
Anyone have a fix or idea what might be happening?
