### ISSUE TITLE
Can't install any application or upgrade anything, broken tool

### ISSUE THREAD

**Issue by whatcorey** [ChrisTitusTech/winutil#1610]
**Describe the bug**
Can't install or upgrade anything.

**To Reproduce**
1. Run tool
2. Click on upgrade or install anything
3. Scroll down to error page
5. No applicable installer found, please see logs

**Expected behavior**
I try to install anything or upgrade anything and it gives me issues, usually have no trouble with this

**Screenshots**
<img width="807" alt="Screenshot 2024-02-12 161148" src="https://github.com/ChrisTitusTech/winutil/assets/35015068/fdd2afd1-440c-4f51-9349-3417d2ecf1a8">

**Additional context**
[WinGet-2024-02-07-15-04-54.313.log](https://github.com/ChrisTitusTech/winutil/files/14253923/WinGet-2024-02-07-15-04-54.313.log)

**Comment by hbilbo** [comment]
This is happening to me when trying to install Discord. I tested it with MSI Afterburner and it worked fine so it may just be certain packages.

**Comment by OutOfThisPlanet** [comment]
These programs I have noticed do not install:

Discord
WinGetUI
(There was another one, but I cannot remember what it was)

Also, Signal installs broken (No QR-Code to login)
