### ISSUE TITLE
update all ==> program downgrade

### ISSUE THREAD

**Issue by hpsxrb** [ChrisTitusTech/winutil#1627]
When using the Upgrade All option in the Install tab, it downgrades AOMEI Backupper Professional to AOMEI Backupper Standard.

Thank you very much for your excellent efforts.

**Comment by v-Kaefer** [comment]
Actually, this has nothing to do with winutil. (it's not even in winutil...)
`winget` uses 'manifests', to install everything, and the only manifest for AOMEI is the Standard version.
- AOMEI Manifest:  https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/AOMEI

Which means, everytime you use `upgrade all` or even `winget upgrade`, it will install the Standard version.

**Comment by hpsxrb** [comment]
Thank you very much for the clarification.

**Comment by v-Kaefer** [comment]
**Issue solved, can be closed.**
