### ISSUE TITLE
Laptop fans are loud and Poweshell CPU usage is high in VM when running winutil

### ISSUE THREAD

**Issue by MaZED-UP** [ChrisTitusTech/winutil#1628]
Running the script via `irm https://christitus.com/win | iex` results in high CPU usage inside my Windows Sever 2022 VM but not is other Windows VMs.

## Details
In my Void Linux system I have a Windows Server 2022 (w/ Desktop Experience) KVM in which I ran the script which makes my CPU fans spin at full speed due to Powershell high CPU usage (more than 70%) even when I don't execute software or tweaks tasks.
I have another Windows 10 VM and tried two other old Windows Sever 2022 and 2025 (Core, w/o desktop) VMs that ran the script without any high load issues.

The only difference is that I [modified the VM configuration](https://forum.proxmox.com/threads/alder-lake-i5-12400-windows-11-guest-with-wsl-nested-virtualization-not-working.125987/#post-581185) to fix a compatibility issue related to running WSL or nested VMs in general. My host CPU is i5-1235U.

**Comment by v-Kaefer** [comment]
I think you answered yourself...
