### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by neo2049** [ChrisTitusTech/winutil#1636]
**Describe the bug**
1. I select an app to install from the UI
2. I click on the Install button
3.

<img width="854" alt="image" src="https://github.com/ChrisTitusTech/winutil/assets/63357/e85bc9af-cdd7-4ecc-b82d-f71bc83df4ee">

4. Nothing is installed.

Other functionality works as expected.

**Comment by ChrisTitusTech** [comment]
Go to config tab and click reinstall winget.
