### ISSUE TITLE
Error with trying to install applications

### ISSUE THREAD

**Issue by Vlinxy** [ChrisTitusTech/winutil#1639]
Whenever I try to install any applications, for example, "WinSCP" or "windirstat" I am just met with (see image) . Reinstalled winget in config, restarted pc to make sure, it is there in the files, not sure how to fix it. 
![image](https://github.com/ChrisTitusTech/winutil/assets/138946899/7a06b6bc-91d9-454a-bb68-8f948da3fa14)

**Comment by marcoodignoti** [comment]
same issue here

**Comment by zouzounos3** [comment]
Confirm same isue

**Comment by mrchillington** [comment]
Same issue.

**Comment by mrchillington** [comment]
so after installing wingetui manually i was able to install items through the util... so maybe you need to manually install winget on your pc before it starts working?

**Comment by mrchillington** [comment]
> so after installing wingetui manually i was able to install items through the util... so maybe you need to manually install winget on your pc before it starts working?

Okay so I realize that when you go to install something through the util it installs winget but on a fresh installed I saw it needed an update and after said update I was able to install through the util.

**Comment by Vlinxy** [comment]
> > so after installing wingetui manually i was able to install items through the util... so maybe you need to manually install winget on your pc before it starts working?
> 
> Okay so I realize that when you go to install something through the util it installs winget but on a fresh installed I saw it needed an update and after said update I was able to install through the util. So maybe the version the script installs in just old?

Hey! Thank you for figuring some of this out and reporting back, really appreciated!

**Comment by mrchillington** [comment]
> > > so after installing wingetui manually i was able to install items through the util... so maybe you need to manually install winget on your pc before it starts working?
> > 
> > 
> > Okay so I realize that when you go to install something through the util it installs winget but on a fresh installed I saw it needed an update and after said update I was able to install through the util. So maybe the version the script installs in just old?
> 
> Hey! Thank you for figuring some of this out and reporting back, really appreciated!

Just hope it actually helps. 😄
