### ISSUE TITLE
Forced installation of winget and chocolatey

### ISSUE THREAD

**Issue by obsvndz** [ChrisTitusTech/winutil#1641]
Hello,

On a clean install of W10 or W11, when I execute this program via the terminal command in admin mode, it automatically installs winget and chocolatey without giving me the option to refuse or cancel. Before, a few releases back, it used to prompt the user before installing any 3rd party software. Please look into it. It's still happening on the current release of the winutil. I want to use this tool without installing any extra 3rd party software I didn't ask for.

Thank you.

**Comment by v-Kaefer** [comment]
winutil uses winget and chocolatey as "installers bypassers" or "EXEs wrappers". Which means that, you can't use winutil without them. Cause it would kill the purpose of winutil pretty much. Which then would lead you to go through each program website, to download the installer, etc. And winutil solves precisely that.

But, you CAN uninstall them, **after** using winutil. But everytime you run it, it will install again, since it needs them to work.
Chocolatey https://docs.chocolatey.org/en-us/choco/uninstallation
Windows Package Manager Client (winget) https://github.com/microsoft/winget-cli/discussions/844

**Comment by Dani3I** [comment]
> ...Cause it would kill the purpose of winutil pretty much. Which then would lead you to go through each program website, to download the installer, etc. And winutil solves precisely that.

Some people may use winutil only for debloating scripts or only for setting updates policy or only to use microwin

**Comment by wizsaint** [comment]
Forced installation of Chocolatey is the only thing keeping me from using this script. I'm fine with winget but I don't like choco being installed on my system. I don't use the app install feature at all. I just want the debloating functionality.

**Comment by SkylerWallace** [comment]
I understand the sentiment of the original post.

Would it be possible to only run the Winget and Chocolatey install functions (Install-WinUtilWinget & Install-WinUtilChoco) when using one of the Install buttons on the main tab of Winget?

**Comment by Mukul1127** [comment]
Agreed, never used the app install feature but now I can't use the tool without downloading bloat software

**Comment by stopspazzing** [comment]
Same issue here, I just found this and cancelled the script once it tried installing chocolatey. I was never warned or asked if this was going to happen and there is no information in the readme regarding chocolatey. Oh well. On to next script.

**Comment by SkylerWallace** [comment]
I have a similar script that accomplishes this. It allows you to install programs with Winget, Chocolatey, Scoop, and direct URLs. You can select which method you want to install the program with; if Winget or Chocolatey are selected then those will be installed, else the script will not install them.

This is just a snippet of what is required for it to function, but this is the main script necessary for this functionality. Feel free to take any bit(s) of this for WinUtil.
https://github.com/SkylerWallace/ATOM/blob/main/ATOM/Dependencies/Neutron/Functions/Install-Programs.ps1

Attached is what this looks like in action.
![Screenshot 2024-03-17 023810](https://github.com/ChrisTitusTech/winutil/assets/12767222/07c90390-8a90-4e91-b6f7-3af54bd15edf)

**Comment by dreamsyntax** [comment]
You can run this instead to use winutil without installing chocolatey:
`(irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex`
credit: https://github.com/ChrisTitusTech/winutil/issues/1118#issuecomment-1850868015
