### ISSUE TITLE
Slow boot of windows after executing this tool on a clean install

### ISSUE THREAD

**Issue by obsvndz** [ChrisTitusTech/winutil#1642]
Hello,

This is an ongoing bug I noticed for a few months. Maybe someone with powershell skills can look into the code of this tool for me to fix this annoying issue.
I like to test Windows 11 and debloating it. I reinstalled it multiple times from scratch just to test this tool alone and confirm the following bug and I did this for a few months. I noticed that my laptop (Lenovo Legion) would take an extra 1-2 seconds before booting the OS after using this tool. In other words, after executing this script on a clean install of W11 or W10 (the "tweaks" section to be exact), I would reboot the computer, the computer would POST, then display the windows 11 logo and it would get stuck on that windows logo for a few extra seconds, the keyboard numlock blinking a few times, before spinning the loading gif and booting the OS. Before executing this tool, this problem didn't exist. Immediately after the POST, the spinning gif would appear and boot the OS immediately.
I believe that changes within the winutil code did something to the boot instructions of the OS because I only use the "Tweaks" section of this tool and nothing else. If someone can look into it and find a fix I would greatly appreciate it. This "lag" only occurs when I reboot the computer, not when I shut it down.

Thank you.

**Comment by hpsxrb** [comment]
same problem here

**Comment by clashwb** [comment]
I had the same problem, found a fix!!!

See this:
https://github.com/henrypp/simplewall/issues/1695

Run the reset_explorer_tray.zip bat shared there. It fixed the slow boot after I debloated.

No ideia why but it works.

**Comment by hpsxrb** [comment]
> I had the same problem, found a fix!!!
> 
> See this: [henrypp/simplewall#1695](https://github.com/henrypp/simplewall/issues/1695)
> 
> Run the reset_explorer_tray.zip bat shared there. It fixed the slow boot after I debloated.
> 
> No ideia why but it works.

Thank you @clashwb

**Comment by Hibburt** [comment]
Same issue here, hanging in main windows as well. Sometimes 10 to 15 seconds to open right click menu

**Comment by raihanadf** [comment]
> I had the same problem, found a fix!!!
> 
> See this: [henrypp/simplewall#1695](https://github.com/henrypp/simplewall/issues/1695)
> 
> Run the reset_explorer_tray.zip bat shared there. It fixed the slow boot after I debloated.
> 
> No ideia why but it works.

what the hell, why resetting the explorer tray makes the windows boot faster? this isse should not be closed. i tried it and it sure does work.
