### ISSUE TITLE
Winget is completely gone from my laptop

### ISSUE THREAD

**Issue by Desynqe** [ChrisTitusTech/winutil#1645]
**Describe the bug**
After using winutil to tweak my laptop, Winget is gone.
![image](https://github.com/ChrisTitusTech/winutil/assets/48497188/033941fd-3b09-4890-99a7-1d574209ca6f)

Using the "Reinstall winget" button does not help.
![image](https://github.com/ChrisTitusTech/winutil/assets/48497188/1001a46e-36ef-4f1a-8253-6241b9d0cee3)
Adding C:\ProgramData\chocolatey\lib\winget to my PATH does not help.

**To Reproduce**
I'm not going to risk doing this on any other computer I own. I don't remember what exact tweaks I used but they all came from the Tweaks tab. I did not use any of the "NOT RECOMMENDED" tweaks.

**Expected behavior**
I expect winget to be a recognized command in cmd like it was before using winutil.

**Screenshots**

**Additional context**
App Installer from the MS store is installed.

**Comment by blusewill** [comment]
Kinda Lack of information.
At least your winget is back

**Comment by og-mrk** [comment]
Try adding the following File Path to your Environment Variable `PATH`:
`C:\Users\YOUR-USERNAME\AppData\Local\Microsoft\WindowsApps`
\*\* Make Sure to replace `YOUR-USERNAME` with your Local Account username (the one you're logged-in as)

**Comment by Desynqe** [comment]
This fixed the problem. Thank you very much.

**Comment by og-mrk** [comment]
No problems, glad I could help
