### ISSUE TITLE
-Config not found

### ISSUE THREAD

**Issue by landtree** [ChrisTitusTech/winutil#1650]
**Describe the bug**
When running (in admin)  "irm https://christitus.com/win -Config [D:\setup\CTT_Program_Preset.json] -Run | iex"

I get a  the error "Invoke-RestMethod : A positional parameter cannot be found that accepts argument 'Config'"

**To Reproduce**
Copy and paste the commend I used I suppose!

**Expected behavior**
Load of the WinUtil Script and automation of installed apps & tweaks based on JSON file

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/10757459/13e87009-53fe-4d80-9e58-a8620d65cc34)

**Comment by blusewill** [comment]
You format it wrong.
This is how you should format it
`irm https://christitus.com/win | iex -Config "D:\setup\CTT_Program_Preset.json" -Run `

**Comment by Yuuh15** [comment]
![WindowsTerminal_TmdAbCiL2G](https://github.com/ChrisTitusTech/winutil/assets/97139700/41aae046-c072-4f5f-b969-906e8b29e925)
Command is still not found, there might be something messed up when declaring the argument in some function

**Comment by blusewill** [comment]
Can you give out your config file?
