### ISSUE TITLE
Failed in attempting to update the source: winget

### ISSUE THREAD

**Issue by ChrisKinUK** [ChrisTitusTech/winutil#1652]
Firstly I would like to say how impressed I have been, & appreciative too, of all your efforts with WinUtil & all the videos over many years. :)

I have had the following error on my Win 10 Pro PC when running WinUtil in powershell. It's been like this for at least a month. I had hoped that a 'fix' might have magically appeared & cured the problem, but alas not, hence this message to you, in case this is a new issue.

Obviously if you need me to supply further info then I would be more than happy to provide it.

Best regards,
Chris

Error message is:
"Failed in attempting to update the source: winget"

Here's the log file output:

**********************
Windows PowerShell transcript start
Start time: 20240224103022
Username: DESKTOP-4L10HE6\HP
RunAs User: DESKTOP-4L10HE6\HP
Configuration Name: 
Machine: DESKTOP-4L10HE6 (Microsoft Windows NT 10.0.19045.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command invoke-command -scriptblock {

 $host.ui.RawUI.WindowTitle = "Winget Install"

 Start-Transcript $ENV:TEMP\winget-update.log -Append
 winget upgrade --all

 } -argumentlist ''
Process ID: 5088
PSVersion: 5.1.19041.3930
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3930
BuildVersion: 10.0.19041.3930
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\HP\AppData\Local\Temp\winget-update.log
Failed in attempting to update the source: winget
Name           Id             Version       Available     Source
----------------------------------------------------------------
Microsoft Edge Microsoft.Edge 112.0.1722.68 116.0.1938.76 winget
1 upgrades available.
2 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
166 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
PS>$global:?
True
**********************
Windows PowerShell transcript end
End time: 20240224103039
**********************
**********************
Windows PowerShell transcript start
Start time: 20240224103054
Username: DESKTOP-4L10HE6\HP
RunAs User: DESKTOP-4L10HE6\HP
Configuration Name: 
Machine: DESKTOP-4L10HE6 (Microsoft Windows NT 10.0.19045.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command invoke-command -scriptblock {

 $host.ui.RawUI.WindowTitle = "Winget Install"

 Start-Transcript $ENV:TEMP\winget-update.log -Append
 winget upgrade --all

 } -argumentlist ''
Process ID: 11904
PSVersion: 5.1.19041.3930
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3930
BuildVersion: 10.0.19041.3930
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\HP\AppData\Local\Temp\winget-update.log
Failed in attempting to update the source: winget
Name           Id             Version       Available     Source
----------------------------------------------------------------
Microsoft Edge Microsoft.Edge 112.0.1722.68 116.0.1938.76 winget
1 upgrades available.
2 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
166 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
PS>$global:?
True
**********************
Windows PowerShell transcript end
End time: 20240224103105
**********************
**********************
Windows PowerShell transcript start
Start time: 20240224103152
Username: DESKTOP-4L10HE6\HP
RunAs User: DESKTOP-4L10HE6\HP
Configuration Name: 
Machine: DESKTOP-4L10HE6 (Microsoft Windows NT 10.0.19045.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command invoke-command -scriptblock {

 $host.ui.RawUI.WindowTitle = "Winget Install"

 Start-Transcript $ENV:TEMP\winget-update.log -Append
 winget upgrade --all

 } -argumentlist ''
Process ID: 6856
PSVersion: 5.1.19041.3930
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3930
BuildVersion: 10.0.19041.3930
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\HP\AppData\Local\Temp\winget-update.log
Failed in attempting to update the source: winget
Name           Id             Version       Available     Source
----------------------------------------------------------------
Microsoft Edge Microsoft.Edge 112.0.1722.68 116.0.1938.76 winget
1 upgrades available.
2 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
166 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
PS>$global:?
True
**********************
Windows PowerShell transcript end
End time: 20240224103203
**********************
**********************
Windows PowerShell transcript start
Start time: 20240224103213
Username: DESKTOP-4L10HE6\HP
RunAs User: DESKTOP-4L10HE6\HP
Configuration Name: 
Machine: DESKTOP-4L10HE6 (Microsoft Windows NT 10.0.19045.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command invoke-command -scriptblock {

 $host.ui.RawUI.WindowTitle = "Winget Install"

 Start-Transcript $ENV:TEMP\winget-update.log -Append
 winget upgrade --all

 } -argumentlist ''
Process ID: 7084
PSVersion: 5.1.19041.3930
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3930
BuildVersion: 10.0.19041.3930
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\HP\AppData\Local\Temp\winget-update.log
Failed in attempting to update the source: winget
Name           Id             Version       Available     Source
----------------------------------------------------------------
Microsoft Edge Microsoft.Edge 112.0.1722.68 116.0.1938.76 winget
1 upgrades available.
2 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
166 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
PS>$global:?
True
**********************
Windows PowerShell transcript end
End time: 20240224103226
**********************

**Comment by blusewill** [comment]
This is a problem in the file `Update-WinUtilProgramWinget.ps1` in the repo.
Will fixes this problem in the future update

**Comment by ChrisKinUK** [comment]
More info, I checked the winget info, see the following:

------------------------
C:\WINDOWS\system32>winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4046
Package: Microsoft.DesktopAppInstaller v1.16.13405.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
-----------------------

I removed Winget & then downloaded it from the MS Store, which seems to newer, see the following:

----------------------------
C:\WINDOWS\system32>winget --info
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4046
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
----------------------------

Now executin "winget upgrade --all" causes the installed apps to be updated. Partial success.

However running the attempting to run "irm https://christitus.com/win | iex" gives another set of errors, see following:

=====================
PS C:\WINDOWS\system32> irm https://christitus.com/win | iex
iex : At line:10766 char:5
+     class WingetFailedInstall : Exception {
+     ~~~~~
Class keyword is not allowed in ConstrainedLanguage mode.
At line:10766 char:11
+     class WingetFailedInstall : Exception {
+           ~~~~~~~~~~~~~~~~~~~
Unexpected token 'WingetFailedInstall' in expression or statement.
At line:10772 char:5
+     class ChocoFailedInstall : Exception {
+     ~~~~~
Class keyword is not allowed in ConstrainedLanguage mode.
At line:10772 char:11
+     class ChocoFailedInstall : Exception {
+           ~~~~~~~~~~~~~~~~~~
Unexpected token 'ChocoFailedInstall' in expression or statement.
At line:10778 char:5
+     class GenericException : Exception {
+     ~~~~~
Class keyword is not allowed in ConstrainedLanguage mode.
At line:10778 char:11
+     class GenericException : Exception {
+           ~~~~~~~~~~~~~~~~
Unexpected token 'GenericException' in expression or statement.
At line:1 char:34
+ irm https://christitus.com/win | iex
+                                  ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : ClassesNotAllowedInConstrainedLanguage,Microsoft.PowerShell.Commands.InvokeExpressionCom
   mand
===================

So, two steps forward, one backwards...

Does anyone have any ideas?
Cheers

**Comment by ChrisKinUK** [comment]
![powershell_uEIb84PBNC](https://github.com/ChrisTitusTech/winutil/assets/161125134/8e4c6ae6-a6fb-47c3-9714-7ec27fb3cbb7)
