### ISSUE TITLE
Getting an error when trying to install apps

### ISSUE THREAD

**Issue by PsyGab** [ChrisTitusTech/winutil#1657]
**Describe the bug**
The program is trying to install the apps that i selected however the apps says winget not detected proceeds to install it but then ends
the installation process saying winget is not installed. Also tried to use the reinstall winget fix however i also get a bug where it "installs" winget however can not install  microsoft-vclibs.

**To Reproduce**
1. Go to install tab 
2. Click on any app
3. Click on install selected

**Expected behavior**
It should install the selected apps

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/74661054/b5e1b7e5-82b4-44d0-9004-b02ba0191d13)

**Comment by blusewill** [comment]
Well that looks like a checksum problem in chocolatey.
I suggested you to install winget manually via their (Github)[https://github.com/microsoft/winget-cli/releases/tag/v1.6.3482]
Sorry for the inconvenience but this will solve the issue.

**Comment by PsyGab** [comment]
Ok thanks for the explanation.

**Comment by og-mrk** [comment]
No problem, happy to help
