### ISSUE TITLE
Please do not update software automatically, more user control is required

### ISSUE THREAD

**Issue by colepcsx2** [ChrisTitusTech/winutil#1658]
Please change the update function for software that is already installed so that you have more control.

The reason is that for some programs, let's say Foobar2000, I would like to stay on version 2.1.X and not update to the latest available version.

**Comment by blusewill** [comment]
Try Get Installed and Deselect the Package you doesn't want to upgrade. 
Thought this will not update the package that is not in the Toolbox but I think it will get the most of the packages updated.
![winget issue-min](https://github.com/ChrisTitusTech/winutil/assets/62820836/0cf507a3-74f4-4a1a-9db2-71f25c4719be)

**Comment by colepcsx2** [comment]
Whether I select the programs or not, it still tries to update them all.

I also don't want that MSI Afterburner to be updated or a DS4Windows component in the case ViGEmBus which isn't even in the list.

**Comment by og-mrk** [comment]
Now I do agree on some level with what've been previously sent, about Getting all installed packages, then De-selecting the apps you don't want to upgrade.
But I would like to have a Config file that WinUtil uses for next times when I run on my system, which contains Apps to Exclude from upgrading when I hit the `Install Selected` button, because I won't need to remember to De-select specific app(s) everytime I want to upgrade them.
\+ this config file can be used to store more User Preferences, like the position of the PowerShell Window on last run, how big it was, and what were the applied tweaks of the previous `Tweaks Run`, and so on...

This's just a suggestion of mine.

**Comment by v-Kaefer** [comment]
When you click on "Upgrade All", it's **winget**/**chocolatey**, that's going through your files, and updating them. 
Winutil is **NOT** a program guys. Sometimes, winget will get the "best of" winutil and update everything, but if you have certain programs that you wish to keep in X version, the best you can do to prevent an update, is to install it separatedly from winutil.

**Comment by og-mrk** [comment]
Yes, I do agree that WinUtil is not an Installed Program, it's a Script.
Now quick story, before using WinUtil and Winget as a whole, I was using Chocolatey, and chocolatey had a feature to "Pin" one or more apps to a Specific Version, a quick google search later, and winget has this feature as well.

It would be cool if WinUtil has a way to Pin Selected Packages, but for now @colepcsx2, Install the App + The Specific Version you want it to be, after successfully installing said app, run the following command inside a Terminal (PowerShell or CMD) running as admin: `winget pin add --id AppPublisher.AppName`
**Note**: Replace `AppPublisher.AppName` with the App ID.

**Comment by v-Kaefer** [comment]
> Yes, I do agree that WinUtil is not an Installed Program, it's a Script.
> 
> Now quick story, before using WinUtil and Winget as a whole, I was using Chocolatey, and chocolatey had a feature to "Pin" one or more apps to a Specific Version, a quick google search later, and winget has this feature as well.
> 
> 
> 
> It would be cool if WinUtil has a way to Pin Selected Packages, but for now @colepcsx2, Install the App + The Specific Version you want it to be, after successfully installing said app, run the following command inside a Terminal (PowerShell or CMD) running as admin: `winget pin add --id AppPublisher.AppName`
> 
> **Note**: Replace `AppPublisher.AppName` with the App ID.

I wasnt aware of that, will take a look at it later. Maybe its possible with a UI change, because i believe making a "config.txt", would be worst than that. Wont promose anything, but ill take a look
