### ISSUE TITLE
Rename development branch to `test` or `dev`

### ISSUE THREAD

**Issue by obfuscated-loop** [ChrisTitusTech/winutil#1660]
**Is your feature request related to a problem? Please describe.**
The current development branch name is `test-2024-02-07-refactor-noapps`. Even to experienced developers, this isn't clear that it's the branch where PRs should be made to.

**Describe the solution you'd like**
Common practice is to use a branch named `dev` - in this instance, it could be called `test`. Although it seems like a trivial change at first, it makes the development experience much more simple for both experienced developers and newbies.

**Comment by obfuscated-loop** [comment]
I understand that you still want to mention the test date/test features but this is not necesarry in the branch name. You can add a branch description with `git branch --edit-description`.

**Comment by blusewill** [comment]
Well this is just personal preference. I think it's not very important?

**Comment by obfuscated-loop** [comment]
> Well this is just personal preference. I think it's not very important?

https://hackernoon.com/git-branch-naming-convention-7-best-practices-to-follow-1c2l33g2
