### ISSUE TITLE
updating wrong app while trying to get other app

### ISSUE THREAD

**Issue by sharif221** [ChrisTitusTech/winutil#1661]
**Describe the bug**
trying to get .net framework 7 just update win-get not actually installing .net

**To Reproduce**
1. Go to 'main page'
2. Click on '.net desktop runtime 7'
3. click on 'install selected'

**output**

```Checking if Chocolatey is Installed...
Chocolatey Already Installed
Checking if Winget is Installed...
Winget v1.6.3482
- Winget up-to-date
Winget Already Installed
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
===========================================
--      Installs have finished          ---
===========================================
```

**Comment by blusewill** [comment]
Well that means you already have this package installed.
So it's not necessary to install it again.

**Comment by og-mrk** [comment]
This issue should be fixed when PR #1662 is reviewed & merged to the project, if you're curious about the solution, then I suggest reading the Description of that PR, our apologies for the inconvenience, and hope you've a nice day.

**Comment by sharif221** [comment]
@blueswill

I also thought that the *.NET Runtime 7* was installed previously, but after double-checking, it was not installed. 

I installed it manually using winget.

Thanks.

**Comment by sharif221** [comment]
@og-mrk 

It seems that your commit will fix this issue.

I'm curious to know if there's an extra log file rather than terminal output that is more verbose and helps us fix these types of problems.

If that's not the case, I think we can at least add package name(s) to the terminal log, resulting in something like this:

*.NET Runtime* is already installed.
No upgrade available for *.NET Runtime*.

Instead of:

Found an existing package already installed.
No available upgrade found.

**Comment by og-mrk** [comment]
> @og-mrk
> 
> It seems that your commit will fix this issue.
> 
> I'm curious to know if there's an extra log file rather than terminal output that is more verbose and helps us fix these types of problems.
> 
> If that's not the case, I think we can at least add package name(s) to the terminal log, resulting in something like this:
> 
> _.NET Runtime_ is already installed. No upgrade available for _.NET Runtime_.
> 
> Instead of:
> 
> Found an existing package already installed. No available upgrade found.

Hello @sharif221,
my bad for the late respond, and this feature you're suggesting is possible to do with a few modification to the one or more script files in the repo.
I personally am not very good at PowerShell, so I won't be working on this feature, maybe one of the Main Contributors or anyone for the task can do this.

> [!NOTE]
> The project is currently under a Major Re-write, so any new features or ideas will be looked into, but won't be added at the time been...
