### ISSUE TITLE
Speed up Windows Explorer

### ISSUE THREAD

**Issue by jnpl95** [ChrisTitusTech/winutil#1666]
**Is your feature request related to a problem? Please describe.**
This feature request is related to a problem with windows itself and not winutil. Windows Explorer is noticeably slower in Windows 11 since windows tries to assign each folder a folder type. 

**Describe the solution you'd like**
[Youtube Solution](https://www.youtube.com/watch?v=A2WDrLurGRY)

**Steps to fix:**
1. Delete the following Bags and BagMRU folders under Shell:
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags 
HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\BagMRU

2. Restart Windows (not sure if this step can be avoided)

3. Create new key under HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell called Bags (replacing the one we deleted), then create new key within Bags called AllFolders. Then create a new key called Shell within AllFolders. Then within Shell, create a new String Value with Name: "FolderType" and Data: "NotSpecified". 

If restart is not required, then this powershell script could possibly work: 
```powershell
& {
    # Define base path
    $BasePath = 'HKCU:\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell'
    
    # Remove Bags and BagMRU keys
    Remove-Item -Path "$BasePath\Bags" -Recurse -Force
    Remove-Item -Path "$BasePath\BagMRU" -Recurse -Force
    
    # Create new keys
    $Bags = New-Item -Path $BasePath -Name 'Bags' -Force
    $AllFolders = New-Item -Path $Bags.PSPath -Name 'AllFolders' -Force
    $Shell = New-Item -Path $AllFolders.PSPath -Name 'Shell' -Force
    
    # Create new value under Shell key
    New-ItemProperty -Path $Shell.PSPath -Name 'FolderType' -Value 'NotSpecified' -PropertyType String -Force
}
```

Might be useful for others who have noticed performance hits using windows explorer since windows becomes sluggish while trying to guess folder types

**Comment by picklepopper1** [comment]
Holy crap, I was so close to reinstalling Windows. Thank you so much for this. It should definitely be added to the tweaks section!
