### ISSUE TITLE
upgrade all returns nothing

### ISSUE THREAD

**Issue by sharif221** [ChrisTitusTech/winutil#1672]
**Describe the bug**
I think there is a bug in the current version of Winget that if you have some packages that cant be upgraded the whole upgrade possess closes and nothing returns in terminal

**To Reproduce**
1. Go to 'main page'
2. Click on 'upgrade all'

**terminal output**
```cmd
3. See errorPS C:\> winget upgrade --all
Name                                             Id                                Version        Available     Source
----------------------------------------------------------------------------------------------------------------------
Microsoft Edge                                   Microsoft.Edge                    120.0.2210.133 122.0.2365.59 winget
PowerToys (Preview) x64                          XP89DCGQ3K6VLD                    0.77.0         0.78.0        winget
Microsoft Visual Studio Code (User)              Microsoft.VisualStudioCode        1.86.2         1.87.0        winget
Python 3.12.1 (64-bit)                           Python.Python.3.12                3.12.1         3.12.2        winget
Nilesoft Shell                                   Nilesoft.Shell                    1.9.10         1.9.15        winget
Google Chrome                                    Google.Chrome                     122.0.6261.70  122.0.6261.95 winget
Microsoft Windows Desktop Runtime - 6.0.26 (x64) Microsoft.DotNet.DesktopRuntime.6 6.0.26         6.0.27        winget
Microsoft .NET Runtime - 6.0.26 (x64)            Microsoft.DotNet.Runtime.6        6.0.26         6.0.27        winget
8 upgrades available.
PS C:\>
```
**reason**

this is because some packages fail during installation, in this case, Winget aborts others that might be able to upgrade.

some fails:
```cmd
PS C:\> winget upgrade Microsoft.Edge
A newer version was found, but the install technology is different from the current version installed.
Please uninstall the package and install the newer version.
```
```cmd
PS C:\> winget upgrade XP89DCGQ3K6VLD
No available upgrade found.
No newer package versions are available from the configured sources.
```

**How to FIX**

there are some options 
1. wait for Winget to fix this issue themselves ://
2. multi-stage upgrade

in 2 we can make upgrade multi-stage means that we don't let Winget manage multiple upgrades by passing `--all`
so it needs a script that at first runs `winget upgrade` then the output is converted to list of package names that need to be upgraded.
then the FOR loop runs `winget upgrade {pakage name}` for all packages inside the list.

**Comment by og-mrk** [comment]
We can achieve the second solution of yours by polling all installed packages (like when you press `Get Installed`l and then run Winget Install on each one (Without the `--force` switch), and as described in `winget install` own help output, it'll try and perform an upgrade if possible for provided package.
