### ISSUE TITLE
Windows Search No longer functioning

### ISSUE THREAD

**Issue by Finale8713** [ChrisTitusTech/winutil#1676]
**Describe the bug**
After running the tweaks below on a VM running windows 10, the search bar no longer works. Meaning, I see the search bar and after restarting the device there is no response when I click inside the search box field. 
(Create Restore Point, Disable Telemetry, Disable Wifi-Sense, Disable Activity History, Disable Location Tracking, Disable Homegroup, Disable Storage Sense, Disable Hibernation, Disable Game DVR, Set Services, to Manual, Set Display for Performance, Disable Notification Tray).  

**To Reproduce**
I have tried to rebuild the index, and restart the machine. I have also tried to follow these steps - https://answers.microsoft.com/en-us/windows/forum/all/windows-10-search-bar-not-working-correctly-keeps/8b76b755-6e51-4d9c-bd28-9b1edcaedc02 

**Expected behavior**
I expect to be able to search for my programs in the windows search bar. 

![Chris Titus issue 01](https://github.com/ChrisTitusTech/winutil/assets/128086451/d143ae94-b6c5-4bbd-ad2f-a2a4e6368c5a)

**Comment by Finale8713** [comment]
It started working as expected. I suspect that there is a different under lying issue causing this. Thank you for the tool!!

**Comment by Geckoonair** [comment]
how to fix?
