### ISSUE TITLE
PURCHASE PROBLEM

### ISSUE THREAD

**Issue by ARLINND1** [ChrisTitusTech/winutil#1681]
HELLO, when I want to buy your software, this problem appears

![Untitled](https://github.com/ChrisTitusTech/winutil/assets/162381343/a4bc58bb-083a-45a0-b17c-3d29088c7cb3)

**Comment by ChrisTitusTech** [comment]
Sign out by clicking the AK in top right, and close and reopen your browser. Go to cttstore.com and sign back in. Let me know if this doesn't work for you by emailing me at contact@christitus.com
