### ISSUE TITLE
No applicable installer found

### ISSUE THREAD

**Issue by whatcorey** [ChrisTitusTech/winutil#1684]
**Describe the bug**
Can't install anything, been trying to install DDU off the script and keep getting errors

**To Reproduce**
Run the script, click install packages, select anything, click install, see the error

**Expected behavior**
Expected it to install a program like before but it did not

**Screenshots**

**Additional context**
Have had this problem for over a month now, reinstalling winget does nothing as i've done that already several times with no success.
<img width="802" alt="Screenshot 2024-03-07 183703" src="https://github.com/ChrisTitusTech/winutil/assets/35015068/2b3430d2-db84-40d3-8181-74784510321b">

**Comment by LinuxFurry** [comment]
Yep can confirm, getting the same results.

**Comment by markusradl** [comment]
I have the same issue.
Maybe its a problem with winget and the scope attribute. In winutil every package installs with scope "machine" (= install for all users). If the selected package is not approbriate for scope machine, then winget exits with this error "APPINSTALLER_CLI_ERROR_NO_APPLICABLE_INSTALLER". E.q. installing "HWInfo" works.

**Comment by ruxunderscore** [comment]
> I have the same issue. Maybe its a problem with winget and the scope attribute. In winutil every package installs with scope "machine" (= install for all users). If the selected package is not approbriate for scope machine, then winget exits with this error "APPINSTALLER_CLI_ERROR_NO_APPLICABLE_INSTALLER". E.q. installing "HWInfo" works.

I can confirm that it's a scope issue: https://github.com/microsoft/winget-cli/issues/3936. I had to make changes and remove the scope when testing my changes in #1738.
