### ISSUE TITLE
No Package Found - Devtoys

### ISSUE THREAD

**Issue by KaiserDMC** [ChrisTitusTech/winutil#1685]
**Describe the bug**
I was browsing the WinUtil for new tools I might want to try out and something caught my eye.
That being the *Devtoys* application under the *Utilities* tag.
However, upon trying to install it I was met with an error: "No package found matching input criteria."

**To Reproduce**
1. Go to *Install* section of the winutil
2. Scroll down to *Utilities* > *Devtoys*
3. Select the *Devtoys* checkbox and then click *Install Selected*
4. See error in PS

**Expected behavior**
After a brief download the application should be installed and a "Successfully installed" message should be presented to the user.

**Screenshots**
Package in question:
![image](https://github.com/ChrisTitusTech/winutil/assets/63681999/d75ab7f9-9a9f-47a6-8f4f-8db13a5f99b0)
Error:
![image](https://github.com/ChrisTitusTech/winutil/assets/63681999/663e196b-d495-4d36-846c-b024c2e68cff)

**Additional context**
If it helps the package in WinGet is this one:
![image](https://github.com/ChrisTitusTech/winutil/assets/63681999/f1e737af-9579-4ada-83ca-fa46136b5b59)

Manual installation using WinGet was successful. Before the installation started I was prompted to agree to the developers ToS, not certain if this is somehow related to the package not installing via the winutil.

**Comment by K-Saikrishnan** [comment]
@KaiserDMC I think it's because of the way winget is getting installed by the script.


![image](https://github.com/ChrisTitusTech/winutil/assets/53394202/f1f21597-29e6-4ecb-bc31-932558f0e5d5)
AFAIK, winutil is using the id of the program to install. So, something like: `winget install -e --id Ventoy.Ventoy`

But since the `Id` of `DevToys` is `9PGCV4V3BK4W` and not `devtoys`  as present in applications.json, it's throwing the error.
https://github.com/ChrisTitusTech/winutil/blob/dd2e4fb337ba00be2ddeaeb60db42754cf652fe2/config/applications.json#L322-L329

**Comment by KaiserDMC** [comment]
Thank you for the quick fix! I assumed it has something to do with how the package is being called by the script, but ever since the change from win10script I am not that versed in the project layout to be able to apply a fix myself. 

I see that your fix is already being merged onto the test branch so when that gets merged onto main I will close this issue.

Once again thank you for the swift response! <3

**Comment by K-Saikrishnan** [comment]
I'm not seeing the PR being merged onto the test branch. You might want to wait until it's merged into the test branch :)

I forgot to mention this, but we do have the `--accept-source-agreements --accept-package-agreements` flags set up. It should take care of agreeing to the ToS automatically.

**Comment by KaiserDMC** [comment]
Closing this issue as the fix was pulled into [main] with (https://github.com/ChrisTitusTech/winutil/pull/1717) "Test 2024 02 07 refactor noapps"
