### ISSUE TITLE
Error reported by Powershell when executing WinUtil

### ISSUE THREAD

**Issue by ChrisKinUK** [ChrisTitusTech/winutil#1687]
![powershell_uEIb84PBNC](https://github.com/ChrisTitusTech/winutil/assets/161125134/cd0324c5-b726-4113-a396-64a5eb4c48ec)

**Comment by CodingWonders** [comment]
You are using PowerShell in constrained language mode, which does block several things ([more info](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/)).

You can try to change the language mode to Full for that session by typing:

```powershell
$ExecutionContext.SessionState.LanguageMode = "FullLanguage"
```

**Comment by ChrisKinUK** [comment]
Thanks for the suggestion. Unfortunately this command produces the following error.

![powershell_IglZmLIHAp](https://github.com/ChrisTitusTech/winutil/assets/161125134/3e464cec-d0d9-48e7-aca0-cab827f3d35e)

**Comment by ChrisKinUK** [comment]
My "work around" is to run the following command in PS is:

winget update --all

This seems to update all the apps currently configured, but obviously I can't add / change anything...
