### ISSUE TITLE
Win10_Right_Click_Classic_Menu

### ISSUE THREAD

**Issue by HerShpenza** [ChrisTitusTech/winutil#169]
Hello Chris,

Many of us "Old school" people might like to go back the classic W10 menu when right clicking on a file, desktop, etc... within W11.

Do you think its possible to add this feature to the tool?

Im sure you know this already but, this is achieved by doing the following:

**1 - Adding a registry key:**

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}]

[HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]
@=""

**2 - Restarting Windows explorer process:**

taskkill /f /im explorer.exe
Start explorer.exe

Many thanks for your great work on this tool!

**Comment by KptnKMan** [comment]
This feature is available in the ThisIsW11 repo, would be awesome if it was added here.
Super useful, and I personally find it to be essential.

**Comment by ChrisTitusTech** [comment]
Agreed, adding in next update
