### ISSUE TITLE
WinGet error on fresh win10 IoT LTSC install

### ISSUE THREAD

**Issue by VooDisss** [ChrisTitusTech/winutil#1693]
**Describe the bug**
No program gets installed when using winutil because of error regarding "winget-cli" or "Microsoft.UI.Xaml.2.8" installation.
I tried this on 2 separate computers with fresh new windows 10 2021 LTSC IoT x64 install 
**To Reproduce**
1. Install fresh windows 10 LTSC IoT 2021
2. Launch winutil via powershell in the normal way
3. Try to install any app which requires winget

**Expected behavior**
Apps should install without problem of extra messing around with my provided solution. Please incorporate my solution to your software somehow...

**SOLUTION:
1. Download these in one folder:
https://sourceforge.net/projects/windows-ui-library.mirror/files/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx/download
https://github.com/microsoft/winget-cli/releases/download/v1.7.10582/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
2. Hold shift and right-click on empty space inside that folder, select "open powershell here" in context menu that popped up
3. execute these 2 commands to "install" those missing things properly:
Add-AppxPackage .\Microsoft.UI.Xaml.2.8.x64.appx
Add-AppxPackage .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
4. Done! Continue using winutil like normal

**Comment by DxDEddy** [comment]
I had the same problem today on Windows 10 Pro - 22H2 - 19045.4123

The solution above fixed it, thanks!

**Comment by jnihil** [comment]
This fixed it for me as well. Cheers.

**Comment by og-mrk** [comment]
@VooDisss 
WinUtil has a Fix for this, which should normally work, which's going to `Config` Tab, then Under `Fixes` you'll find `WinGet Reinstall`, which does exactly what it states.

### Screenshots for reference
<div align="center">
<img src=https://github.com/ChrisTitusTech/winutil/assets/70659536/b9b36a96-e2eb-4144-8daa-07ae136ee625>
<p><i>Showcasing where to find the 'WinGet Reinstall' Fix.</i></p>
</div>

</br>

<div align="center">
<img src=https://github.com/ChrisTitusTech/winutil/assets/70659536/4af80a6f-498e-4410-8f97-642e7e94f5c7>
<p><i>What exactly this fix does, which basically runs 'choco install winget -y --force' in a new PowerShell Process.

The '-y' is short for 'yes'
The '--force' will 'force' install the 'winget' package.
</i></p>
</div>

**Comment by aut0-m8** [comment]
Alter script to check for winget before running the menu? Albeit winget is pretty bloated

**Comment by SGHphoto** [comment]
The first post helped me fix the issue I was having on fresh windows 11, so that was good.

But it's a bit embarassing to miss the fix in the util but now I know so thank you very much for your input @og-mrk .

**Comment by UbioZur** [comment]
Same here, Win10 Pro 22H2 Build 19045.4170 Windows Feature Experience Pack 1000.19054.1000.0

Just Installed and up to date, Nothing else installed.

Winget is deteted as installed by choco, but can't install apps because winget is not insalled.

The Fix does not work, manually reinstalling winget does not work

![WingetError](https://github.com/ChrisTitusTech/winutil/assets/13650202/66fca2f3-ba49-4d1e-8358-d69598599e10)

And the chocolatery.log 

> 2024-03-22 02:56:36,825 3544 [DEBUG] - XmlConfiguration is now operational
> 2024-03-22 02:56:36,870 3544 [DEBUG] - Adding new type 'CygwinService' for type 'IAlternativeSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,871 3544 [DEBUG] - Adding new type 'CygwinService' for type 'IInstallSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,872 3544 [DEBUG] - Adding new type 'PythonService' for type 'IAlternativeSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,872 3544 [DEBUG] - Adding new type 'PythonService' for type 'IListSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,873 3544 [DEBUG] - Adding new type 'PythonService' for type 'IInstallSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,873 3544 [DEBUG] - Adding new type 'PythonService' for type 'IUninstallSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,874 3544 [DEBUG] - Adding new type 'RubyGemsService' for type 'IAlternativeSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,874 3544 [DEBUG] - Adding new type 'RubyGemsService' for type 'IListSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,874 3544 [DEBUG] - Adding new type 'RubyGemsService' for type 'IInstallSourceRunner' from assembly 'choco'
> 2024-03-22 02:56:36,875 3544 [DEBUG] - Adding new type 'SystemStateValidation' for type 'IValidation' from assembly 'choco'
> 2024-03-22 02:56:36,876 3544 [DEBUG] - Adding new type 'CacheFolderLockdownValidation' for type 'IValidation' from assembly 'choco'
> 2024-03-22 02:56:37,115 3544 [DEBUG] - Adding new type 'EmptyOrInvalidUrlMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,116 3544 [DEBUG] - Adding new type 'FrameWorkReferencesMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,116 3544 [DEBUG] - Adding new type 'IconMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,117 3544 [DEBUG] - Adding new type 'LicenseMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,121 3544 [DEBUG] - Adding new type 'PackageTypesMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,125 3544 [DEBUG] - Adding new type 'ReadmeMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,129 3544 [DEBUG] - Adding new type 'RepositoryMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,131 3544 [DEBUG] - Adding new type 'RequireLicenseAcceptanceMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,131 3544 [DEBUG] - Adding new type 'ServicableMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,132 3544 [DEBUG] - Adding new type 'VersionMetadataRule' for type 'IMetadataRule' from assembly 'choco'
> 2024-03-22 02:56:37,140 3544 [DEBUG] - Registering new command 'cache' in assembly 'choco'
> 2024-03-22 02:56:37,140 3544 [DEBUG] - Registering new command 'list' in assembly 'choco'
> 2024-03-22 02:56:37,141 3544 [DEBUG] - Registering new command 'template' in assembly 'choco'
> 2024-03-22 02:56:37,141 3544 [DEBUG] - Registering new command 'export' in assembly 'choco'
> 2024-03-22 02:56:37,142 3544 [DEBUG] - Registering new command 'info' in assembly 'choco'
> 2024-03-22 02:56:37,142 3544 [DEBUG] - Registering new command 'help' in assembly 'choco'
> 2024-03-22 02:56:37,143 3544 [DEBUG] - Registering new command 'config' in assembly 'choco'
> 2024-03-22 02:56:37,143 3544 [DEBUG] - Registering new command 'feature' in assembly 'choco'
> 2024-03-22 02:56:37,143 3544 [DEBUG] - Registering new command 'new' in assembly 'choco'
> 2024-03-22 02:56:37,144 3544 [DEBUG] - Registering new command 'outdated' in assembly 'choco'
> 2024-03-22 02:56:37,144 3544 [DEBUG] - Registering new command 'pack' in assembly 'choco'
> 2024-03-22 02:56:37,144 3544 [DEBUG] - Registering new command 'pin' in assembly 'choco'
> 2024-03-22 02:56:37,145 3544 [DEBUG] - Registering new command 'push' in assembly 'choco'
> 2024-03-22 02:56:37,145 3544 [DEBUG] - Registering new command 'apikey' in assembly 'choco'
> 2024-03-22 02:56:37,146 3544 [DEBUG] - Registering new command 'source' in assembly 'choco'
> 2024-03-22 02:56:37,146 3544 [DEBUG] - Registering new command 'uninstall' in assembly 'choco'
> 2024-03-22 02:56:37,147 3544 [DEBUG] - Registering new command 'upgrade' in assembly 'choco'
> 2024-03-22 02:56:37,147 3544 [DEBUG] - Registering new command 'search' in assembly 'choco'
> 2024-03-22 02:56:37,147 3544 [DEBUG] - Registering new command 'unpackself' in assembly 'choco'
> 2024-03-22 02:56:37,148 3544 [DEBUG] - Registering new command 'install' in assembly 'choco'
> 2024-03-22 02:56:37,504 3544 [INFO ] - ============================================================
> 2024-03-22 02:56:37,823 3544 [INFO ] - Chocolatey v2.2.2
> 2024-03-22 02:56:37,827 3544 [DEBUG] - Chocolatey is running on Windows v 10.0.19045.0
> 2024-03-22 02:56:37,828 3544 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
> 2024-03-22 02:56:37,829 3544 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
> 2024-03-22 02:56:37,835 3544 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install winget -y --force 
> 2024-03-22 02:56:37,835 3544 [DEBUG] - Received arguments: install winget -y --force
> 2024-03-22 02:56:37,864 3544 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
> 2024-03-22 02:56:37,883 3544 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
> 2024-03-22 02:56:37,887 3544 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
> 2024-03-22 02:56:37,911 3544 [DEBUG] - Performing validation checks.
> 2024-03-22 02:56:37,914 3544 [DEBUG] - Global Configuration Validation Checks:
> 2024-03-22 02:56:37,914 3544 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
> 2024-03-22 02:56:37,915 3544 [DEBUG] - System State Validation Checks:
> 2024-03-22 02:56:37,916 3544 [DEBUG] -  Reboot Requirement Checks:
> 2024-03-22 02:56:37,918 3544 [DEBUG] -  - Pending Computer Rename = Checked
> 2024-03-22 02:56:37,918 3544 [DEBUG] -  - Pending Component Based Servicing = Checked
> 2024-03-22 02:56:37,919 3544 [DEBUG] -  - Pending Windows Auto Update = Checked
> 2024-03-22 02:56:37,920 3544 [DEBUG] -  - Pending File Rename Operations = Checked
> 2024-03-22 02:56:37,920 3544 [DEBUG] -  - Pending Windows Package Installer = Checked
> 2024-03-22 02:56:37,921 3544 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
> 2024-03-22 02:56:37,922 3544 [DEBUG] - Cache Folder Lockdown Checks:
> 2024-03-22 02:56:37,922 3544 [DEBUG] -  - Elevated State = Checked
> 2024-03-22 02:56:37,922 3544 [DEBUG] -  - Folder Exists = Checked
> 2024-03-22 02:56:37,924 3544 [DEBUG] -  - Folder lockdown = Checked
> 2024-03-22 02:56:37,926 3544 [INFO ] - 3 validations performed. 3 success(es), 0 warning(s), and 0 error(s).
> 2024-03-22 02:56:37,933 3544 [DEBUG] - The source 'https://community.chocolatey.org/api/v2/' evaluated to a 'normal' source type
> 2024-03-22 02:56:37,934 3544 [DEBUG] - 
> NOTE: Hiding sensitive configuration data! Please double and triple
>  check to be sure no sensitive data is shown, especially if copying
>  output to a gist for review.
> 2024-03-22 02:56:37,939 3544 [DEBUG] - Configuration: CommandName='install'|
> CacheLocation='C:\Users\Quentin\AppData\Local\Temp\chocolatey'|
> CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
> Sources='https://community.chocolatey.org/api/v2/'|SourceType='normal'|
> ShowOnlineHelp='False'|Debug='False'|Verbose='False'|Trace='False'|
> Force='True'|Noop='False'|HelpRequested='False'|
> UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
> PromptForConfirmation='False'|DisableCompatibilityChecks='False'|
> AcceptLicense='True'|AllowUnofficialBuild='False'|Input='winget'|
> AllVersions='False'|SkipPackageInstallProvider='False'|
> SkipHookScripts='False'|PackageNames='winget'|Prerelease='False'|
> ForceX86='False'|OverrideArguments='False'|NotSilent='False'|
> ApplyPackageParametersToDependencies='False'|
> ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
> CacheExpirationInMinutes='30'|AllowDowngrade='False'|
> ForceDependencies='False'|PinPackage='False'|
> Information.PlatformType='Windows'|
> Information.PlatformVersion='10.0.19045.0'|
> Information.PlatformName='Windows 10'|
> Information.ChocolateyVersion='2.2.2.0'|
> Information.ChocolateyProductVersion='2.2.2'|
> Information.FullName='choco, Version=2.2.2.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|
> 
> Information.Is64BitOperatingSystem='True'|
> Information.Is64BitProcess='True'|Information.IsInteractive='True'|
> Information.UserName='Quentin'|
> Information.UserDomainName='DESKTOP-D8DKDTR'|
> Information.IsUserAdministrator='True'|
> Information.IsUserSystemAccount='False'|
> Information.IsUserRemoteDesktop='False'|
> Information.IsUserRemote='True'|
> Information.IsProcessElevated='True'|
> Information.IsLicensedVersion='False'|
> Information.IsLicensedAssemblyLoaded='False'|
> Information.LicenseType='Foss'|
> Information.CurrentDirectory='C:\Windows\system32'|
> Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
> Features.AllowEmptyChecksums='False'|
> Features.AllowEmptyChecksumsSecure='True'|
> Features.FailOnAutoUninstaller='False'|
> Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
> Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
> Features.VirusCheck='False'|
> Features.FailOnInvalidOrMissingLicense='False'|
> Features.IgnoreInvalidOptionsSwitches='True'|
> Features.UsePackageExitCodes='True'|
> Features.UseEnhancedExitCodes='False'|
> Features.UseFipsCompliantChecksums='False'|
> Features.ShowNonElevatedWarnings='True'|
> Features.ShowDownloadProgress='True'|
> Features.StopOnFirstPackageFailure='False'|
> Features.UseRememberedArgumentsForUpgrades='False'|
> Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
> Features.SkipPackageUpgradesWhenNotInstalled='False'|
> Features.RemovePackageInformationOnUninstall='False'|
> Features.ExitOnRebootDetected='False'|
> Features.LogValidationResultsOnWarnings='True'|
> Features.UsePackageRepositoryOptimizations='True'|
> ListCommand.LocalOnly='False'|ListCommand.IdOnly='False'|
> ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
> ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
> ListCommand.ByTagOnly='False'|ListCommand.IdStartsWith='False'|
> ListCommand.OrderByPopularity='False'|ListCommand.ApprovedOnly='False'|
> ListCommand.DownloadCacheAvailable='False'|
> ListCommand.NotBroken='False'|
> ListCommand.IncludeVersionOverrides='False'|
> ListCommand.ExplicitPageSize='False'|
> ListCommand.ExplicitSource='False'|
> UpgradeCommand.FailOnUnfound='False'|
> UpgradeCommand.FailOnNotInstalled='False'|
> UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
> UpgradeCommand.ExcludePrerelease='False'|
> NewCommand.AutomaticPackage='False'|
> NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
> SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
> SourceCommand.AllowSelfService='False'|
> SourceCommand.VisibleToAdminsOnly='False'|
> FeatureCommand.Command='unknown'|ConfigCommand.Command='Unknown'|
> ApiKeyCommand.Command='Unknown'|PinCommand.Command='Unknown'|
> OutdatedCommand.IgnorePinned='False'|
> ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
> TemplateCommand.Command='unknown'|CacheCommand.Command='Unknown'|
> CacheCommand.RemoveExpiredItemsOnly='False'|
> 2024-03-22 02:56:37,940 3544 [DEBUG] - _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
> 2024-03-22 02:56:37,942 3544 [INFO ] - Installing the following packages:
> 2024-03-22 02:56:37,943 3544 [INFO ] - winget
> 2024-03-22 02:56:37,944 3544 [INFO ] - By installing, you accept licenses for the packages.
> 2024-03-22 02:56:38,069 3544 [DEBUG] - Running list with the following filter = ''
> 2024-03-22 02:56:38,070 3544 [DEBUG] - --- Start of List ---
> 2024-03-22 02:56:38,080 3544 [DEBUG] - Resolving resource PackageSearchResource for source C:\ProgramData\chocolatey\lib
> 2024-03-22 02:56:38,194 3544 [DEBUG] - chocolatey 2.2.2
> 2024-03-22 02:56:38,212 3544 [DEBUG] - microsoft-ui-xaml-2-7 2.7.3
> 2024-03-22 02:56:38,214 3544 [DEBUG] - microsoft-vclibs-140-00 14.0.33321
> 2024-03-22 02:56:38,216 3544 [DEBUG] - winget 1.7.10661
> 2024-03-22 02:56:38,217 3544 [DEBUG] - winget-cli 1.7.10661
> 2024-03-22 02:56:38,217 3544 [DEBUG] - --- End of List ---
> 2024-03-22 02:56:38,218 3544 [WARN ] - winget v1.7.10661 already installed. Forcing reinstall of version '1.7.10661'.
>  Please use upgrade if you meant to upgrade to a new version.
> 2024-03-22 02:56:38,220 3544 [DEBUG] - Resolving resource PackageMetadataResource for source https://community.chocolatey.org/api/v2/
> 2024-03-22 02:56:38,646 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/Packages(Id='winget',Version='1.7.10661')
> 2024-03-22 02:56:38,664 3544 [DEBUG] - Resolving resource DependencyInfoResource for source https://community.chocolatey.org/api/v2/
> 2024-03-22 02:56:38,669 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/Packages(Id='winget',Version='1.7.10661')
> 2024-03-22 02:56:38,682 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/$metadata
> 2024-03-22 02:56:38,689 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='winget-cli'&semVerLevel=2.0.0
> 2024-03-22 02:56:38,697 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='microsoft-ui-xaml-2-7'&semVerLevel=2.0.0
> 2024-03-22 02:56:38,698 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='microsoft-vclibs-140-00'&semVerLevel=2.0.0
> 2024-03-22 02:56:38,701 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='microsoft-ui-xaml'&semVerLevel=2.0.0
> 2024-03-22 02:56:38,702 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='microsoft-ui-xaml-2-7'&semVerLevel=2.0.0
> 2024-03-22 02:56:38,703 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='microsoft-vclibs'&semVerLevel=2.0.0
> 2024-03-22 02:56:38,704 3544 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/FindPackagesById()?id='microsoft-vclibs-140-00'&semVerLevel=2.0.0
> 2024-03-22 02:56:38,752 3544 [INFO ] - [NuGet] Resolving dependency information took 0 ms
> 2024-03-22 02:56:38,757 3544 [DEBUG] - Running beforeModify step for 'winget'
> 2024-03-22 02:56:38,761 3544 [DEBUG] - Backing up package files for 'winget'
> 2024-03-22 02:56:38,803 3544 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib-bkp\winget".
> 2024-03-22 02:56:38,804 3544 [DEBUG] - Moving C:\ProgramData\chocolatey\lib\winget to C:\ProgramData\chocolatey\lib-bkp\winget\1.7.10661
> 2024-03-22 02:56:38,805 3544 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\winget'
>  to 'C:\ProgramData\chocolatey\lib-bkp\winget\1.7.10661'
> 2024-03-22 02:56:40,811 3544 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\winget".
> 2024-03-22 02:56:40,813 3544 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\winget\1.7.10661\winget.nupkg"
>  to "C:\ProgramData\chocolatey\lib\winget\winget.nupkg".
> 2024-03-22 02:56:40,814 3544 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\winget\1.7.10661\winget.nuspec"
>  to "C:\ProgramData\chocolatey\lib\winget\winget.nuspec".
> 2024-03-22 02:56:42,327 3544 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\winget'
> 2024-03-22 02:56:42,328 3544 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\winget\winget.nupkg'
>   with checksum '8A32F3AE81B1B946D4855050B6BC7632'
> 2024-03-22 02:56:42,329 3544 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\winget\winget.nuspec'
>   with checksum 'CADB8750138E268C0B3D1322C14BBFE6'
> 2024-03-22 02:56:42,355 3544 [DEBUG] - [NuGet] Removed file 'winget.nupkg' from folder 'C:\ProgramData\chocolatey\lib\winget'.
> 2024-03-22 02:56:42,358 3544 [DEBUG] - Ensuring removal of package cache files.
> 2024-03-22 02:56:42,359 3544 [DEBUG] - Resolving resource DownloadResource for source https://community.chocolatey.org/api/v2/
> 2024-03-22 02:56:42,368 3544 [DEBUG] - Attempting to delete file "".
> 2024-03-22 02:56:42,376 3544 [INFO ] - [NuGet]   GET https://community.chocolatey.org/api/v2/package/winget/1.7.10661
> 2024-03-22 02:56:43,279 3544 [INFO ] - [NuGet]   OK https://community.chocolatey.org/api/v2/package/winget/1.7.10661 902ms
> 2024-03-22 02:56:43,293 3544 [INFO ] - [NuGet] Acquiring lock for the installation of winget 1.7.10661
> 2024-03-22 02:56:43,306 3544 [INFO ] - [NuGet] Acquired lock for the installation of winget 1.7.10661
> 2024-03-22 02:56:43,386 3544 [INFO ] - [NuGet] Installed winget 1.7.10661 from https://community.chocolatey.org/api/v2/ with content hash xjSXNuoebs7sCo0ej7QtV4XWF73rKhjxRZDhnPF69UBqCWo0N8RgeZMbM04ZPsuiP6m4URJiKhgBgWzmPTjCog==.
> 2024-03-22 02:56:43,398 3544 [INFO ] - [NuGet] Adding package 'winget.1.7.10661 : winget-cli [1.7.10661, )' to folder 'C:\ProgramData\chocolatey\lib'
> 2024-03-22 02:56:43,417 3544 [INFO ] - [NuGet] Added package 'winget.1.7.10661 : winget-cli [1.7.10661, )' to folder 'C:\ProgramData\chocolatey\lib'
> 2024-03-22 02:56:43,419 3544 [DEBUG] - Attempting to delete file "C:\Users\Quentin\AppData\Local\Temp\chocolatey\ChocolateyScratch\winget/1.7.10661\winget.1.7.10661.nupkg".
> 2024-03-22 02:56:43,420 3544 [DEBUG] - Attempting to delete file "C:\Users\Quentin\AppData\Local\Temp\chocolatey\ChocolateyScratch\winget/1.7.10661\.nupkg.metadata".
> 2024-03-22 02:56:43,420 3544 [DEBUG] - Attempting to delete file "C:\Users\Quentin\AppData\Local\Temp\chocolatey\ChocolateyScratch\winget/1.7.10661\winget.1.7.10661.nupkg.sha512".
> 2024-03-22 02:56:43,422 3544 [INFO ] - 
> winget v1.7.10661 (forced) [Approved]
> 2024-03-22 02:56:43,437 3544 [INFO ] - winget package files install completed. Performing other installation steps.
> 2024-03-22 02:56:43,457 3544 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\winget'
> 2024-03-22 02:56:43,458 3544 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\winget\winget.nupkg'
>   with checksum '8A32F3AE81B1B946D4855050B6BC7632'
> 2024-03-22 02:56:43,458 3544 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\winget\winget.nuspec'
>   with checksum 'CADB8750138E268C0B3D1322C14BBFE6'
> 2024-03-22 02:56:43,475 3544 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\winget.1.7.10661\.arguments".
> 2024-03-22 02:56:43,475 3544 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\winget.1.7.10661\.extra".
> 2024-03-22 02:56:43,476 3544 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\winget.1.7.10661\.version".
> 2024-03-22 02:56:43,476 3544 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\winget.1.7.10661\.sxs".
> 2024-03-22 02:56:43,477 3544 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\winget.1.7.10661\.pin".
> 2024-03-22 02:56:43,478 3544 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
> 2024-03-22 02:56:43,478 3544 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\winget\.chocolateyPending".
> 2024-03-22 02:56:43,479 3544 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bkp\winget".
> 2024-03-22 02:56:43,480 3544 [INFO ] -  The install of winget was successful.
> 2024-03-22 02:56:43,480 3544 [INFO ] -   Software installed to 'C:\ProgramData\chocolatey\lib\winget'
> 2024-03-22 02:56:43,490 3544 [WARN ] - 
> Chocolatey installed 1/1 packages. 
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 2024-03-22 02:56:43,491 3544 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
> 2024-03-22 02:56:43,492 3544 [DEBUG] - Exiting with 0
>

**Comment by og-mrk** [comment]
Hello @UbioZur
The logs for Chocolatey looks fine to me, if the problem still occurs with WinUtil (not winget, because it should now be installed), even after a System Restart, _which isn't needed normally, but just to make sure_... then I'm clueless like you're as to Why WinUtil doesn't find winget.

feel free to post an update of the issue you're facing, to let everyone else know if the issue was fixed, and if so, sharing how you fixed it will be appreciated 😄

**Comment by UbioZur** [comment]
So I did a Full reinstall of windows, Then full Update, reboot.

Run winutil, And no winget. Use WinUtil fix. No winget (I mean also as cli `winget - v), reboot, no winget.

![winget](https://github.com/ChrisTitusTech/winutil/assets/13650202/913daed8-2f80-4f08-be1f-6aba5556b4f9)


I double and tripple check on microsoft store, App installer is installed.

I run this command: `Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe`

Now winget works. and so does winutil. 

I am not good enough to know where is the issue from (internet disconnected during install, No Microsoft account, Windows not yet activated etc...)

Hopefully it help people and better mind than me to fix that bug.

**Comment by ruxunderscore** [comment]
#1738 Should have fixed this issue, as it's a new install method created. I have a further pull request to change the order of things.

**Comment by ModernTTY** [comment]
@VooDisss  since this is fixed you should close the issue.
