### ISSUE TITLE
Option to remove apps that are bloatware

### ISSUE THREAD

**Issue by crazycheetah42** [ChrisTitusTech/winutil#1695]
**Is your feature request related to a problem? Please describe.**
I wish that there was a feature where we could remove Microsoft and third-party bloatware that shows up on the Start Menu. I use this tool for everything but I am constantly digging through my start menu removing apps myself.

**Describe the solution you'd like**
Perhaps a little checkbox in the Tweaks section that would remove any apps deemed bloatware, such as these:
        'Get-AppxPackage Microsoft.Microsoft3DViewer | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.BingWeather | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.GetHelp | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.WindowsMaps | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.XboxApp | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.XboxGamingOverlay | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.MixedReality.Portal | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.SkypeApp | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.WindowsFeedbackHub | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage',
        'Get-AppxPackage SpotifyAB.SpotifyMusic | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.Getstarted | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.People | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.Todos | Remove-AppxPackage',
        'Get-AppxPackage Microsoft.BingNews | Remove-AppxPackage',

**Describe alternatives you've considered**
I did build my own script to do so in Python, but since I have no knowledge of how to implement this in the toolbox, I was unable to make a pull request myself.

**Additional context**
![image](https://github.com/ChrisTitusTech/winutil/assets/76403763/0230636d-62f9-497c-b296-1e4a11e1c350)
This is the code I made in Python to remove the bloatware.

**Comment by aawadeus** [comment]
I would love to see something like this idea get implemented, great suggestion

**Comment by xe1st** [comment]
Yes, a GUI that lists the system applications with their description and lets you choose which ones to uninstall would be nice.
