### ISSUE TITLE
Error: This command cannot be run due to this error: The system cannot find the file specified

### ISSUE THREAD

**Issue by EloToJaa** [ChrisTitusTech/winutil#1697]
**Describe the bug**
`Error: This command cannot be run due to this error: The system cannot find the file specified.` while installing browsers after running tweaks after fresh Windows 10 install.

**To Reproduce**
1. Install tweaks
2. Set updates to Security
3. Try to install browsers

**Expected behavior**
I expected the 3 browsers i selected to install and installation is stuck.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/22549550/b28006f3-bcf1-4cc1-965d-6a5aafd34503)
![vmware_fOHagQ6u0d](https://github.com/ChrisTitusTech/winutil/assets/22549550/321d596b-0a3e-4b7f-9a8a-d590c18256b7)
![vmware_rBko4XTBGi](https://github.com/ChrisTitusTech/winutil/assets/22549550/e41c1bc7-d226-40ef-9c20-4228fecabd17)
![vmware_ik7uFHFyIY](https://github.com/ChrisTitusTech/winutil/assets/22549550/b0fce084-5ecb-4c1a-8285-feb7bd537e49)

**Additional context**
Windows 10 22H2 Pro more info on the picture

**Comment by aaroncolon** [comment]
I am experiencing the same issue on a brand new Windows 10 install.

**Comment by Roverp1** [comment]
Just installed windows on the virtual machine, default iso, no tweaks yet applied, having the same error

**Comment by Panke2000** [comment]
> Just installed windows on the virtual machine, default iso, no tweaks yet applied, having the same error
> 
> 
> 
> fixed: looks like winutil wasn't able to install winget, the button _reinstall winget_ did nothing.
> 
> fixed by installing winget manually 

There are 2 options. I can only do  it with GitHub method, but when I run the downloaded bundle it throws error: "Package failed updates, dependency or conflict validation.". Have you experienced it?

**Comment by Roverp1** [comment]
> There are 2 options. I can only do it with GitHub method, but when I run the downloaded bundle it throws error: "Package failed updates, dependency or conflict validation.". Have you experienced it?

oh yes))) I've spent ~4 hours trying to resolve it. 
this two commands from chat-gpt worked for me: 

`Invoke-WebRequest -Uri "https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -OutFile "$env:TEMP\winget_installer.msixbundle"
`
`Add-AppxPackage -Path "$env:TEMP\winget_installer.msixbundle" -ForceApplicationShutdown
`

The second command was giving me an error, which i resolved by installing the _Microsoft.UI.Xaml.2.7_, i found an article with good instruction on how to do it: [What is Microsoft.UI.Xaml.2.7 and How to Install it](https://www.winhelponline.com/blog/install-microsoft-ui-xaml-2-7-package/)

**Comment by Panke2000** [comment]
It worked very smoothly without throwing any errors. Thanks a lot! Much appreciated! 😃 

> > There are 2 options. I can only do it with GitHub method, but when I run the downloaded bundle it throws error: "Package failed updates, dependency or conflict validation.". Have you experienced it?
> 
> oh yes))) I've spent ~4 hours trying to resolve it. this two commands from chat-gpt worked for me:
> 
> `Invoke-WebRequest -Uri "https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -OutFile "$env:TEMP\winget_installer.msixbundle" `
> 
> `Add-AppxPackage -Path "$env:TEMP\winget_installer.msixbundle" -ForceApplicationShutdown `
> 
> The second command was giving me an error, which i resolved by installing _Microsoft.UI.Xaml.2.7_, i found an article with good instruction on how to do it: [What is Microsoft.UI.Xaml.2.7 and How to Install it](https://www.winhelponline.com/blog/install-microsoft-ui-xaml-2-7-package/)

It worked very smoothly without throwing any errors. Thanks a lot! Much appreciated! 😃

**Comment by jlr2000** [comment]
Same situation here but I needed **Micorosoft.UI.Xaml.2.8** per the errors I was getting.

I found the download ([](https://www.nuget.org/packages/Microsoft.UI.Xaml/)) and used the instructions above, changing the details from "2.7.x" to "2.8" accordingly to install via powershell command line and then it worked for me.  

New install of Windows 10 64 bit using Rufus 3.20.1929 (portable) choosing to customize (Skip privacy questions, set local account the same name as this users and set regiaol options using same as this users).

**Comment by Panke2000** [comment]
> Same situation here but I needed **Micorosoft.UI.Xaml.2.8** per the errors I was getting.
> 
> 
> 
> I found the download at https://www.nuget.org/packages/Microsoft.UI.Xaml/ and used the instructions above, changing the details from "2.7.x" to "2.8" accordingly to install via powershell command line and then it worked for me.  
> 
> 
> 
> New install of Windows 10 64 bit using Rufus 3.20.1929 (portable) choosing to customize (Skip privacy questions, set local account the same name as this users and set regiaol options using same as this users). 

I've also used Rufus with the same options checked. It could be the reason why we have this problem.

**Comment by Today20092** [comment]
> It worked very smoothly without throwing any errors. Thanks a lot! Much appreciated! 😃
> 
> > > There are 2 options. I can only do it with GitHub method, but when I run the downloaded bundle it throws error: "Package failed updates, dependency or conflict validation.". Have you experienced it?
> > 
> > 
> > oh yes))) I've spent ~4 hours trying to resolve it. this two commands from chat-gpt worked for me:
> > `Invoke-WebRequest -Uri "https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -OutFile "$env:TEMP\winget_installer.msixbundle" `
> > `Add-AppxPackage -Path "$env:TEMP\winget_installer.msixbundle" -ForceApplicationShutdown `
> > The second command was giving me an error, which i resolved by installing _Microsoft.UI.Xaml.2.7_, i found an article with good instruction on how to do it: [What is Microsoft.UI.Xaml.2.7 and How to Install it](https://www.winhelponline.com/blog/install-microsoft-ui-xaml-2-7-package/)
> 
> It worked very smoothly without throwing any errors. Thanks a lot! Much appreciated! 😃

I had the same issue, but this did not work for me.

Following step 5 on this guide fixed it. 
https://www.maketecheasier.com/fix-winget-not-recognized-windows/

**Comment by ruxunderscore** [comment]
#1738 I made a pull request that changes the installation of method of Winget if choco failed to install. Also refreshes Environment Variables. Another change was to remove the machine scope from winget program install script, as it fails with non-UWP apps: https://github.com/microsoft/winget-cli/issues/3936 I was seeing the same error (`Error: This command cannot be run due to this error: The system cannot find the file specified.`) when testing until I made these changes.

**Comment by ruxunderscore** [comment]
This was merged in and should be fixed. Can someone close this Issue?

**Comment by og-mrk** [comment]
> This was merged in and should be fixed. Can someone close this Issue?

Even if the Author is offline and currently can't close this issue, Github actions should close it after a period of inactivity, so all should be good.
