### ISSUE TITLE
MicroWin Wrong Parameter Error

### ISSUE THREAD

**Issue by xpl01ter** [ChrisTitusTech/winutil#1699]
**Describe the bug**
During the process of making a MicroWin ISO, at a certain moment, I am present with a bunch of wrong parameter errors. I have tried with my already NTLite Custom ISO and with the Official Microsoft ISO and the result is always the same.

**To Reproduce**
1. Just following the UI steps

**Expected behavior**
Create a ISO without the telemetry and all the features included in MicroWin funcionality.

**Screenshots**
Custom ISO
![image](https://github.com/ChrisTitusTech/winutil/assets/94334573/4ba6c54c-e634-49a2-997c-00852bbb6bc0)

Official ISO
![image](https://github.com/ChrisTitusTech/winutil/assets/94334573/e0717e46-7aa7-4cd8-9f81-4e4982a87761)

**Comment by CodingWonders** [comment]
I'm seeing your user folder on both a C and a D drive. Where do you have your user files stored?

**Comment by xpl01ter** [comment]
> I'm seeing your user folder on both a C and a D drive. Where do you have your user files stored?

On the C drive
