### ISSUE TITLE
Few apps not installing

### ISSUE THREAD

**Issue by adamkagdi** [ChrisTitusTech/winutil#17]
**Describe the bug**
Anydesk and Windows Terminal are not installing Windows 10 Version 21H1 (OS Build 19044.1706)
**To Reproduce**
1. Run the script
2. Select Anydesk and Windows Terminal
3. Click Start Install
4. See error (sometimes there is a PowerShell windows opening named as 'select')

**Comment by tselovalnikov** [comment]
Do you have WINGET installed?

**Comment by adamkagdi** [comment]
> Do you have WINGET installed?

Yes I have, other apps install properly, these two particular I get a problem.
