### ISSUE TITLE
Add Firefox ESR under Firefox

### ISSUE THREAD

**Issue by aut0-m8** [ChrisTitusTech/winutil#1705]
Feature request to add Firefox ESR under Firefox checkbox. Possibly use United Kingdom exe for eu privacy laws out of the gate. Mozilla permalinks their exes so you don't need to rely on chocolatey.

**Comment by aut0-m8** [comment]
en_GB ESR 64bit EXE binary:
https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=win64&lang=en-GB

**Comment by ModernTTY** [comment]
Has been implemented in PR #1720, but using the EU version would be challenging because it installs through WinGet and doesn’t download an EXE, so massive code changes would be required just for this one app, so probably not going to happen.

**Comment by og-mrk** [comment]
> Has been implemented in PR #1720, but using the EU version would be challenging because it installs through WinGet and doesn’t download an EXE, so massive code changes would be required just for this one app, so probably not going to happen.

WinUtil uses WinGet package manager, as far as I know, I don't think installing a Specific Locale/Region  Installer of a Program is possible.

**Comment by ModernTTY** [comment]
@aut0-m8 Since this has been implemented you should now close this issue.
