### ISSUE TITLE
New application: Flameshot

### ISSUE THREAD

**Issue by thomasfinstad** [ChrisTitusTech/winutil#1706]
Flameshot is a screen-shotting application much like greenshot but I find it preferable.

Package manager installs are available: https://flameshot.org/docs/installation/installation-windows/

**Comment by og-mrk** [comment]
Hello @thomasfinstad,
Flameshot is available in WinUtil's App List, see the screenshot below for more context/evidence.

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/c5b3f107-2087-4c21-91ac-0e197ae14aa7)

**Comment by thomasfinstad** [comment]
Hmm I can swear I tripple checked and didn't see it. Thanks :)

**Comment by og-mrk** [comment]
Can confirm with what @ModernTTY has said, Flameshot should be available in the Main Branch/Release of WinUtil, _**see screenshot below**_.

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/7c03dc9e-8d4f-4719-afe2-8cd351b1ff7d)

</br>

If this is all good news to you @thomasfinstad, please consider closing this issue.
