### ISSUE TITLE
where to find the action of these tweaks: WPFMiscTweaksPower

### ISSUE THREAD

**Issue by dummys** [ChrisTitusTech/winutil#1711]
I'm searching the code and I can't find the WPFMiscTweaksPower inside the tweaks.json.
Why it is not here ? I think perhaps you forgot to remove it from the preset ?

**Comment by og-mrk** [comment]
Hello @dummys
Didn't find 'WPFMiscTweaksPower' as well, I've done a recursive search on the Repo using `grep -r`, but with no luck, so I've removed it in PR #1763

Thanks for pointing this out 😄

**Comment by og-mrk** [comment]
Hello @dummys 
This issue should be fixed, as PR https://github.com/ChrisTitusTech/winutil/pull/1763 was merged into the test branch, and later on to the main branch. Please consider closing this issue, and hope you've a nice day 😄
