### ISSUE TITLE
Paint.net not installing

### ISSUE THREAD

**Issue by DiegcD** [ChrisTitusTech/winutil#1712]
**Describe the bug**
When I open Winutil with iwr -useb https://christitus.com/win | iex with powershell as admin, then select Paint.net box and then click Install Selected, the powershell shows Installs have finished but nothing occurs, Paint.net doesn't get installed. Tried force reinstall winget but the issue is not that because it keeps happening.

**To Reproduce**
1. Open winutil with iwr -useb https://christitus.com/win | iex
2. Click on Paint.net box
3. Click Install Selected
4. Powershell says Install have finished but the program doesn't get installed

**Expected behavior**
Paint.net should be installed

**Screenshots**
![Captura de pantalla (34)](https://github.com/ChrisTitusTech/winutil/assets/102642718/9bb384af-d04c-4de0-a7c9-7a83b2d69af1)

**Additional context**
Windows 11 Pro 23H2 22631.3296 Windows Feature Experience Pack 1000.22687.1000.0
Winutil 24.02.20

**Comment by ruxunderscore** [comment]
Pull request (#1758) in to fix #1712 and #1756.
