### ISSUE TITLE
add rectify 11 support

### ISSUE THREAD

**Issue by GamerKing122** [ChrisTitusTech/winutil#1713]
Add an option in tweaks to use rectify 11 tweaks for other features their github page can be found at [https://github.com/Rectify11/Installer](https://github.com/Rectify11/Installer)

**Comment by RocGod** [comment]
Not recommended to use this Rectify 11
i was use this plugin for beautify the theme, etc.. but cause many issues like broken explorer.

**Comment by Husky-Devel** [comment]
Agreed i used it and had to reinstall windows due to broken explorer and other bugs
