### ISSUE TITLE
Add support for installing remote desktop/support apps?

### ISSUE THREAD

**Issue by pdwalker** [ChrisTitusTech/winutil#1718]
For your consideration:
- [TightVNC](https://www.tightvnc.com)
- [RustDesk](https://rustdesk.com)

**Comment by PRTaz3** [comment]
uVNC as well if possible.

**Comment by Husky-Devel** [comment]
From looking rustdesk is already in the utility 
![image](https://github.com/ChrisTitusTech/winutil/assets/75509373/4a26e8b8-d55d-42a0-acfc-3c93e1478d47)
TightVNC has also been added

**Comment by PRTaz3** [comment]
> From looking rustdesk is already in the utility ![image](https://private-user-images.githubusercontent.com/75509373/316278422-4a26e8b8-d55d-42a0-acfc-3c93e1478d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTcwNzYsIm5iZiI6MTcxMTI5Njc3NiwicGF0aCI6Ii83NTUwOTM3My8zMTYyNzg0MjItNGEyNmU4YjgtZDU1ZC00MmEwLWFjZmMtM2M5M2UxNDc4ZDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE2MTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMjU4N2M2NWJkZmFlMTQyOTQxNTIyZjZjMjMyZTQ1YTc1NjBhMjE4ZTQzMWQ2NTY5NDg5Zjc0M2NjZjNmZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OnPd2ureVToqabYQ4-bDRpWmHb2t1mD_pRKoWnmlgbM) TightVNC has also been added

No TightVNC or uVNC that I can see.

**Comment by Husky-Devel** [comment]
Currently it's in the dev branch but should be in the main branch soon
________________________________

**Comment by PRTaz3** [comment]
Is it possible to also get UltraVNC as an option?
