### ISSUE TITLE
O&O Shutup 10 error on tweaks page

### ISSUE THREAD

**Issue by SavannahHoward** [ChrisTitusTech/winutil#1723]
**Describe the bug**
When running tweaks and having run OO Shutup it errors out with attached screenshot
**To Reproduce**
1. Go to 'your tool'
2. Click on 'tweaks'
3. Scroll down to 'OO shutup'
4. Send it, and see error

**Expected behavior**
Clearly, its supposed to work. lol
**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/163698180/4853f23a-c246-4696-9ca1-dedbe69384a8)
![image](https://github.com/ChrisTitusTech/winutil/assets/163698180/66f3905d-0277-4ba6-a7bb-e552a90b81c4)

**Additional context**
Shoutout to all the youtube people!

**Comment by hwalker928** [comment]
Was able to reproduce, but running the tweak again seems to work.

**Comment by J-eremy** [comment]
When I got the error message it happened repeatedly even running the tweaks again. Maybe the location of the config file has some availability issues, or something has changed upstream and isn't reflected in the script.
