### ISSUE TITLE
missing char?

### ISSUE THREAD

**Issue by JoKopii** [ChrisTitusTech/winutil#1735]
winutil 823, in the function Remove-Packages,
probably missing w character while comparing strings

$_ -NotLike "*Windows-Client-LanguagePack*" -AND

https://github.com/ChrisTitusTech/winutil/blob/5cd75c0ed6ee9663f0cd98b96cdb6e2956c35107/winutil.ps1#L823

**Comment by og-mrk** [comment]
Hello @JoKopii
Down Below is a full explanation on what these lines of code do, and all of these lines can be put on a Single Line... but it'll be very difficult to read without word-wrapping.

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/1b5daf0d-27b5-4895-b494-c62e4196713f)

</br>

If my answer was satisfies your question, then you can go ahead and close this issue.

**Comment by JoKopii** [comment]
Hello,
if i got that right, case insensitve string comparison helps only with differences between lower and uppercase characters in a string of equal length, like "Hello" and "heLlO" 
but will it find with this method "Windows-Client-LanguegePack" with the search for "indows-Client-LanguegePack" ? or for example "pplicationModel" instead of "ApplicationModel"

**Comment by og-mrk** [comment]
> Hello, if i got that right, case insensitve string comparison helps only with differences between lower and uppercase characters in a string of equal length, like "Hello" and "heLlO" but will it find with this method "Windows-Client-LanguegePack" with the search for "indows-Client-LanguegePack" ? or for example "pplicationModel" instead of "ApplicationModel"

Well besides the being Case In-Sensitive (I believe, please correct me if I'm wrong), you can use -Like (and it's opposite -NotLike) when you want to find a Sub-String within a String, By using what's called a WildCard, for example, the string "Windows-Client-LanguegePack" has the "Client" Sub-String in it

#### Example
```powershell
$myString = "Windows-Client-LanguegePack"
$isStringsAlike = $myString -Like "*Client*"`
$isStringsAlike
```

#### Output
```powershell
True
```

Link for more info: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.4
