### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by trandinhgiabao2612** [ChrisTitusTech/winutil#1737]
![image](https://github.com/ChrisTitusTech/winutil/assets/108709755/9260943e-f048-4b4e-bf00-fc1b6a0a7b75)
how to fix this error?
thank!

**Comment by ruxunderscore** [comment]
Do you have a full list of the applications you were trying to install? In Pull Request #1738, I implemented a new install method for Winget, and ended up running into a similar error as well as one other until I made the changes there. 

If the application you are trying to install doesn't have a choco package in the repo, it will try to install and use Winget instead. There is an issue with Winget installed non-UWP apps if scope is set to machine as it is in the main branch of winutil. https://github.com/microsoft/winget-cli/issues/3936

**Comment by trandinhgiabao2612** [comment]
------------------------------
Hi Rux,

Thank you so much for your quick response and help in fixing this error. I
really appreciate it!

Best regards,
Tran Dinh Gia Bao
