### ISSUE TITLE
Microwin returns unrelated error message when there's not enough space in C:

### ISSUE THREAD

**Issue by acgzr** [ChrisTitusTech/winutil#1740]
**Describe the bug**

This is a simple one. If there's not enough space in the C: drive, the install.wim/install.esd file doesn't (can't) get unpacked from the selected ISO during normal operation. Microwin interprets this as there being no install.wim/install.esd file in the first place, and returns an error message warning the user that the ISO probably is from a shady source because there's no install.wim/install.esd file.

**To Reproduce**

Make sure there's not enough space in C: to fit the ISO
Go to 'MicroWin'
Click on 'Select Windows ISO'
Select .iso file
Winutil Microwin error: install.wim/install.esd file doesn't exist in the image, this can happen when using modified ISOs. Please don't download images from shady sources, but only from Microsoft instead.

**Comment by blusewill** [comment]
Well it's hard to tell that having enough resources or not.
But making a warning should be working for this.

**Comment by acgzr** [comment]
Thank you for working on this one. I haven't had other noteworthy issues using Microwin, but it would be nice if it deleted its leftover files in the Temp folder automatically. I actually ran out of space in my C: drive (and found this bug) because I was processing a bunch of ISOs in a row and that Temp file got big quickly.

Anyways, just some extra info related to this issue. Thanks again for all your help putting this tool together and improving it continuously.

**Comment by CodingWonders** [comment]
That change has also been added. Since the test branch was merged so quickly (due to AVs), you can now experience these changes in the main branch

**Comment by YusufKhalifadev** [comment]
@acgzr 
it has been fixed now in #1766 
You should close the issue
