### ISSUE TITLE
Broken installers

### ISSUE THREAD

**Issue by mews-se** [ChrisTitusTech/winutil#1745]
I just thought I might add that "Neofetch" fails to install due:

![image](https://github.com/ChrisTitusTech/winutil/assets/58894405/ccf05290-5f89-49a8-9d47-5ab9eca416a3)

However a simple "winget install neofetch" works manually:

![image](https://github.com/ChrisTitusTech/winutil/assets/58894405/3fcaebcf-e5a9-4ae3-ade6-ccca4bd356e8)

**Comment by RocGod** [comment]
I think neofetch can be installed by scoop, not winget

**Comment by ChrisTitusTech** [comment]
Should be fixed now with #1748
