### ISSUE TITLE
 The term 'Get-WmiObject' is not recognized

### ISSUE THREAD

**Issue by YusufKhalifadev** [ChrisTitusTech/winutil#1749]
The Term "Get-WmiObject" is not recognized as the name of a cmdlet
$gpuinfo =  Get-WmiObject  Win32_VideoController

start Winutil by running: "irm christitus.com/win | iex" Then the error happens

I think it's a problem with my PC maybe it's too old for winutil to detect the GPU i don't know though 
it didn't happen before the testing branch being merged into main branch

![winutil issue](https://github.com/ChrisTitusTech/winutil/assets/154465051/f97875af-6a98-40d1-8b4c-d3ab78627f04)

**Comment by ruxunderscore** [comment]
#1736 I mentioned the issue here, and have a fix suggested. I might even look at it soon, if someone else doesn't fix it first.
