### ISSUE TITLE
Paint.NET still not installing, 24.03.28

### ISSUE THREAD

**Issue by DiegcD** [ChrisTitusTech/winutil#1756]
**Describe the bug**
When I try to install Paint.NET through Winutil it doesn't work, I suspect it's because my Windows 11 system is in spanish and the powershell window throws an error in spanish.

**To Reproduce**
1. Open winutil though powershell as admin
2. Click on Paint.NET box
3. Click on Install/Upgrade Selected
4. See No se encontró ningún paquete coincidente con los criterios de busqueda. on the powershell window
5. Paint.NET doesn't get installed

**Expected behavior**
Paint.NET should be installed

**Screenshots**
![Captura de pantalla (47)](https://github.com/ChrisTitusTech/winutil/assets/102642718/ba1f7068-6318-449d-9787-23848ec32366)

**Additional context**
Windows 11 latest update, Winutil 28 march 2024

**Comment by ruxunderscore** [comment]
The name changed for it on winget. I'll have a Pull Request put in for it soon.

**Comment by ruxunderscore** [comment]
#1758 Has been suggested as a pull request. Will have to wait until that fixed. Until then: `winget install dotPDN.PaintDotNet`
