### ISSUE TITLE
Troubles adding new programs

### ISSUE THREAD

**Issue by RodrigoTR04** [ChrisTitusTech/winutil#1764]
**Problem**
I've made a fork of the project because I wish to customize it with programs that I use regularly, done via removing unwanted ones and adding new one that most likely wouldn't be added to the main repo due to their niche. I have added them to the `config/applications.json` file in the correct format but when running the command via Powershell the changes aren't happening.

\
**To Reproduce**
`https://github.com/RodrigoTR04/winutil/blob/main/config/applications.json` this is where I'm storing my personal changes. They were all added at bottom of the file.

`irm https://raw.githubusercontent.com/RodrigoTR04/winutil/main/winutil.ps1 | iex` this is the command being used in Powershell, changed the account name to redirect to my own.

\
**Expected behavior**
As far as I know the applications should have become visible in the tool, but they have not. 

\
**Additional context**
I'm not a developer, so I might have missed something, this is just something I'm doing to make things more convenient to myself while installing programs that I normally do. I go through this process once every couple of months when doing a Windows re-install and since I was already using the tool for some changes like the feature/security update tweak I thought it would be fun to tackle making changes myself.

**Comment by blusewill** [comment]
Have you tried to run Compile.ps1 before running winutil.ps1?

**Comment by og-mrk** [comment]
@RodrigoTR04 try running `Compile.ps1` and you'll see that one or more files have been edited, after that commit and push your changes to your GitHub Repo, and try running your WinUtil again.

**Comment by RodrigoTR04** [comment]
How would I go about running `Compile.ps1`?

**Comment by og-mrk** [comment]
@RodrigoTR04 ⬇️⬇️

<div align="center">
<img src="https://github.com/ChrisTitusTech/winutil/assets/70659536/6f680a53-8a97-4830-bb4d-eb87c4f45a36">
</p><i>A screenshot showcasing how to Compile and run winutil locally, or after compiling, adding & pushing your new compiled files to your GitHub Repo.</i></p>
</div>

**Comment by RodrigoTR04** [comment]
Thanks for all the help, managed to get it running. I'll close this issue now since it is resolved.

**Comment by og-mrk** [comment]
> Thanks for all the help, managed to get it running. I'll close this issue now since it is resolved.

No problem @RodrigoTR04, glad I could help 😄
