### ISSUE TITLE
Failed when opening source(s); try the 'source reset' command if the problem persists.

### ISSUE THREAD

**Issue by Xenod666** [ChrisTitusTech/winutil#1771]
**Describe the bug**

**To Reproduce**
1. Go to '...' Select App to install 
2. Click on '....' Install/ Upgrade Selected

**Expected behavior**

**Screenshots**

**Additional context**

![2024-03-31 02_21_12-irm christitus com_win _ iex(Admin)](https://github.com/ChrisTitusTech/winutil/assets/156726932/e55cdfa4-84db-4b0e-a337-d2de319220f0)

**Comment by Xenod666** [comment]
Always having this issues first i was thinking it was a windows update issue but tried many other version of windows cannot get rid of this message when trying to install any app from the winutil :(

**Comment by ruxunderscore** [comment]
What apps are they? I can try to look into this more on Monday evening, if someone doesn't get to it first.

**Comment by ruxunderscore** [comment]
If you would like to fix this yourself, try this: `Add-AppxPackage -Path https://cdn.winget.microsoft.com/cache/source.msix`

**Comment by Xenod666** [comment]
It's working, is this "command" work everytime i got this error ? It's kinda weird to get this on a fresh install of W10 or W11. 

Let me know :)

**Comment by ruxunderscore** [comment]
> It's working, is this "command" work everytime i got this error ? It's kinda weird to get this on a fresh install of W10 or W11.
> 
> Let me know :)

Seems like some manual installs of Winget, specifically ones run as user and not as admin, installs the repo source file, but Admin doesn't see it like it is supposed to. The fix won't be retro active, but once you install the source, it shouldn't need to be installed again in the future, unless a future update breaks the source. 

Here is where I found out about the issue:
https://github.com/microsoft/winget-cli/discussions/3258#discussioncomment-5951658

**Comment by Xenod666** [comment]
Thx vrm for the info Rux have a good one :)
