### ISSUE TITLE
Microsoft Edge is back

### ISSUE THREAD

**Issue by thapa-sabin98** [ChrisTitusTech/winutil#1772]
**Describe the bug**
I had installed Windows 11 using winutil's microwin utility, and had removed edge, because I don't want it to plague my system. For some reason, it is back on my system after almost 2 weeks I installed Windows 11 using the iso microwin modified. Also, one important information I would like to add is that I have received windows updates after I installed Windows 11 using microwin, so although I do remember Edge not being in my system right after I updated, I have a high reason to believe that the update had something to do with it.

**To Reproduce**
1. Get your iso from Microsoft 
2. Go to Microwin tab in CTT's winutil
3. Install Windows using the new ISO
4. Select the option to remove Edge
5. Update your system after Windows 11 shows "Critical updates" or until the notification in the taskbar lights up red.
6. After a few days/weeks Edge just decided to show up

**Expected behavior**
Microsoft Edge should no longer be on my system.

**Additional context**
I would also like to add that I had fiddled around Microsoft Defender (Security) to see if I could get winutil running to update some packages (And it did after I disabled Defender). And I am 100% sure that Edge did not reappear immediately after the update, and it took ~ a week to reappear on my system after the update. I hope there is a good solution to this that does not require me to reinstall Windows again :'(

Also, thank you very much for your awesome work Chris!

**Comment by ruxunderscore** [comment]
Microsoft will reinstall Edge during updates, there is a tooltip when you hover over `Remove Microsoft Edge - NOT RECOMMENDED` that states that Edge reinstalls with updates. 

![image](https://github.com/ChrisTitusTech/winutil/assets/16318553/dfe0528a-d70a-49df-8fb7-f3c6c20f404a)

Windows runs a lot of small updates in the background. There really isn't a way to permanently remove Edge without completely disabling Windows Updates. This isn't recommended for security reasons. Also, Edge comes with a lot of libraries that Windows uses everyone else, like WebView2, which is a webapp library used by a lot of software, including WPF, WinForms, and Win32 C/C++ applications.

**Comment by thapa-sabin98** [comment]
Thank you for letting me know. I should have looked into it a bit more before I opened up an issue here. I was able to remove Edge again, I just didn't know I had to do it after every update. Thanks again!
