### ISSUE TITLE
Add UltraVNC (uVNC) to apps list

### ISSUE THREAD

**Issue by PRTaz3** [ChrisTitusTech/winutil#1780]
Thanks for adding TightVNC. Any chance that UltraVNC (uVNC) can be added as well?

**Comment by og-mrk** [comment]
Hello @PRTaz3
Once PR #1781 is merged, it'll be available in the test branch for sometime and then to the general public.

**Comment by og-mrk** [comment]
This Program Request Issue will be moved to ThetTracking List Issue #1782
Thanks for your request @PRTaz3 😄
