### ISSUE TITLE
WinUtil not working

### ISSUE THREAD

**Issue by santhosh110599** [ChrisTitusTech/winutil#1784]
Whenever I use the utility tool. I get an error like this (Screenshot added). Can anyone help with this issue?
<img width="857" alt="Screenshot 2024-04-01 085908" src="https://github.com/ChrisTitusTech/winutil/assets/159008012/48dac217-1feb-47f6-ab70-6a5a71261f62">

**Comment by YusufKhalifadev** [comment]
@santhosh110599 
Could you provide more information? What version of Windows are you using and what changes have you made?

**Comment by santhosh110599** [comment]
@YusufKhalifadev I'm using Windows 11 version 22H2. I haven't made any changes as such. 
I've been using the tool for about a year. I'm facing this issue only recently.

**Comment by YusufKhalifadev** [comment]
@santhosh110599 
Did you try updating to 23H2 Maybe this is the problem

**Comment by YusufKhalifadev** [comment]
@santhosh110599 
I found a temporary solution until I make a PR and fix this try closing the terminal reopening it and running the toolbox this should work fine.
as the first time the toolbox gets run, it installs Winget. Still, it doesn't install the selected application after installation so reopening the terminal and rerunning the toolbox should be a fix.

**Comment by santhosh110599** [comment]
@YusufKhalifadev I tried your temporary solution. Not helping..

**Comment by santhosh110599** [comment]
Hi @YusufKhalifadev ! Updating the WIndows worked! Thanks for the help..
