### ISSUE TITLE
How do I revert the Set Display For Performance back to Best Appearance?

### ISSUE THREAD

**Issue by BMP5000** [ChrisTitusTech/winutil#1785]
The control panel settings are not working

**Comment by ModernTTY** [comment]
@BMP5000 can you provide more details about what tweaks you did and what you tried in control panel?

**Comment by YusufKhalifadev** [comment]
@BMP5000 
To revert the set Display for performance to best appearance you need to follow these steps:
- go to the tweaks section
- select Set Display for Performance 
-  and click on Undo Tweaks Button 
and this should revert it back

**Comment by fahadshahbaz** [comment]
@BMP5000 If you find it difficult, you can do it manually by searching for 'adjust the appearance and performance of Windows,' then select 'Adjust for best appearance.'

**Comment by fahadshahbaz** [comment]
Hi @BMP5000, if the issue you raised has been resolved, would you mind closing it? Thanks!
