### ISSUE TITLE
If I use the command, its saying "Invoke-WebRequest: No such host is known."

### ISSUE THREAD

**Issue by kaustubhowmick** [ChrisTitusTech/winutil#179]
PS C:\Windows\System32> iwr -useb https://christitus.com/win | iex
Invoke-WebRequest: No such host is known.

**Comment by ChrisTitusTech** [comment]
Generally a DNS issue with your networking environment. 

You need to be able to resolve https://christitus.com/win

Or you can manually download the winutil.ps1 file and run it that way.
