### ISSUE TITLE
bootmenupolicy being set to legacy without selecting the option to

### ISSUE THREAD

**Issue by handsomefox** [ChrisTitusTech/winutil#1796]
**Describe the bug**
The tweak (WPFFeatureEnableLegacyRecovery) that does 'bcdedit /set bootmenupolicy legacy' is ran without the 'Enable Legacy F8 Boot Recovery' checkbox selected.

**To Reproduce**
_No options from the 'Features' sections were selected_
1. Go to 'Tweaks'
2. Click on 'Recommended selections: Desktop'
3. Click on 'Run Tweaks'
4. Type bcdedit in console and see 'bootmenupolicy: Legacy'

**Expected behavior**
This should only happen if user enables the checkbox 'Enable Legacy F8 Boot Recovery'.

**Additional Information**
Here's a log (for some reason it didn't capture the whole output, but whatever), where you can see me running bcdedit after doing the steps described and seeing it being set to legacy: [Winutil.log](https://github.com/ChrisTitusTech/winutil/files/14835442/Winutil.log).

**Comment by og-mrk** [comment]
> Here's a log (for some reason it didn't capture the whole output, but whatever), where you can see me running bcdedit after doing the steps described and seeing it being set to legacy: [Winutil.log](https://github.com/ChrisTitusTech/winutil/files/14835442/Winutil.log).

Run the script with `-Debug` Switch, command: `iex "& { $(irm christitus.com/win) } -Debug"`
