### ISSUE TITLE
Apps not installing

### ISSUE THREAD

**Issue by PRTaz3** [ChrisTitusTech/winutil#1797]
Tried installing Rufus and Ventoy and neither seems to properly install. They are found in Programs and features but not when you search in start menu.

**Comment by blusewill** [comment]
Can you give the output of the file?
It should be at `%TEMP%\Winutil.log`

**Comment by PRTaz3** [comment]
[Winutil.log](https://github.com/ChrisTitusTech/winutil/files/14852798/Winutil.log)

**Comment by blusewill** [comment]
So far I didn't see any issues.
How about the output of the install powershell?

**Comment by PRTaz3** [comment]
CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T                                                         CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T                                                        C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T                                                       C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT                                                      C:::::C                     T:::::T                T:::::T                                                              C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
Checking if Chocolatey is Installed...
===========================================
--       Chocolatey is installed        ---
===========================================
Version: v2.2.2
===========================================
--         Winget is installed          ---
===========================================
Version: v1.7.10861
    - Winget is a release version.
    - Winget is Up to Date

Winget is already installed.
Found Ventoy [Ventoy.Ventoy] Version 1.0.97
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/ventoy/Ventoy/releases/download/v1.0.97/ventoy-1.0.97-windows.zip
  ██████████████████████████████  15.9 MB / 15.9 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "Ventoy2Disk"
Command line alias added: "VentoyPlugson"
Command line alias added: "VentoyVlnk"
Successfully installed
===========================================
--      Installs have finished          ---
===========================================

**Comment by blusewill** [comment]
Looks like this is Ventoy Cli.
You should be able to use it in PowerShell by typing Ventoy2Disk

**Comment by PRTaz3** [comment]
Ok, thank you. Did not understand that. Thought it would be an application with GUI interface. Appreciate the quick responses.

**Comment by ModernTTY** [comment]
@PRTaz3 If running Ventoy2Disk works please close this issue.
