### ISSUE TITLE
Trying to Undo the "Disable hibernation" doesnt reenable it

### ISSUE THREAD

**Issue by guitehub** [ChrisTitusTech/winutil#1798]
https://github.com/ChrisTitusTech/winutil/blob/4a7c8a35bf2e874579504fb81d5b3589823da7a0/config/tweaks.json#L55C10-L55C18

Run "Undo Selected Tweaks" with "Disable Hibernation" ticked (getted from "Get Installed") doesnt seems to reenable Hibernation, after doing it and reboot I still didnt have the option available.

It seems to have properly put the Reg keys back to original values but only after I manualy runned "powercfg.exe /hibernate on" I got the option back.

I'm on laptop btw ✌️😉

**Comment by og-mrk** [comment]
I've made a PR addressing this problem.
Thanks for pointing this issue out @guitehub 😄
