### ISSUE TITLE
Making the scripts more modular 

### ISSUE THREAD

**Issue by Triplesweet** [ChrisTitusTech/winutil#180]
I feel since the scripts are becoming more populated, a script might do changes that the user didn't want, and will have to spend time reversing the changes needed.

I believe making the scripts more modular in a way that you can decided with to turn off or on, can be helpful later on. Something like o&o shut up, it makes all the changes in one button buy it let's you change on thing if you for what ever reason needed it

I know it will need a big rewrite and a lot of UI changes to do, but I feel in the future it will be much easier for the end user, and I know we can change the scripts manually, but after a year or so there might be like 300 different thing that the scripts can do combined, we can't spend huge amount of time to read them to see what that line does to delete then or something. 

And best of luck to everyone 

Edit, I know we can choose with scripts to run, I am talking about individual changes in one script file

**Comment by ChrisTitusTech** [comment]
Have a couple things in mind for this, but in a long term roadmap.
