### ISSUE TITLE
Add `magic-wormhole`

### ISSUE THREAD

**Issue by tobiabocchi** [ChrisTitusTech/winutil#1803]
Hey chris! First of all a HUGE thank you and kudos to you! This tool made windows usable for me and a lot of other people.

I was wondering if you already considered adding to the available packages [magic-wormhole](https://github.com/magic-wormhole/magic-wormhole), I use it a lot to quickly transfer files between machines.

Since it's not present in `winutil` I just install it using `winget`, but I think this tool might be worthy of being added as a utility.

Again thank you for all this!

**Comment by og-mrk** [comment]
This will be tracked in https://github.com/ChrisTitusTech/winutil/issues/1782 Issue Tracking List, and I've added this program in a recent commit ( https://github.com/ChrisTitusTech/winutil/pull/1795/commits/6f784e2c72e9c3294d5237b0b72ce5c8552ad1e4 ) in [this PR](https://github.com/ChrisTitusTech/winutil/pull/1795)

And as always, Thanks for requesting more cool apps 😎 👍

**Comment by og-mrk** [comment]
Quick Note: Magic Wormhole is currently outdated in both Chocolatey and WinGet Repos, for the next few days it should be updated in WinGet, See [The Update PR](https://github.com/microsoft/winget-pkgs/pull/147814) in winget-pkgs repo for more info.

**Comment by koppor** [comment]
winget install -e --id magic-wormhole.magic-wormhole
