### ISSUE TITLE
Disable Telemetry Doesn't Only Disable Telemetry

### ISSUE THREAD

**Issue by Weaselcake** [ChrisTitusTech/winutil#1811]
**Describe the bug**
When used, it also messes with the GPU Scheduling and Priority settings.

**To Reproduce**
1. Simply run the Disable Telemetry options.

**Expected behavior**
It should be disabling things related to telemetry, not touching unrelated performance tweaks.

**Additional context**
I know changing GPU scheduling and other related settings in that specific part of the registry is supposed to help with performance, but it makes things work worse in my setup. I only want to be able to use all the telemetry related tweaks when I press that button.

**Comment by SkylerWallace** [comment]
I agree that some tweaks in 'Disable telemetry' should be moved to a separate toggle.

**Comment by Weaselcake** [comment]
This is still a thing

**Comment by Weaselcake** [comment]
Literally only thing that I dislike about the tool, otherwise the Disable Telemetry option would be so useful :'3 Should i make a new issue since this auto closed?
