### ISSUE TITLE
Running OO Shutup doesn't work

### ISSUE THREAD

**Issue by ZongMan** [ChrisTitusTech/winutil#1812]
**Describe the bug**
Running OO shutup doesnt work. 

**To Reproduce**
1. Load CTT.exe, go to tweek tab, check :Run OO shutup, Click run tweeks.
2. CMD prompt for CTT states its running script for the OO but it never loads a window for selecting what options to use. 
3. CMD then says tweaks are finished.

**Expected behavior**
Am i not supposed to get a windows to select what options to choose? does this part of the tweak do everything on its own?

**Screenshots**

**Additional context**

**Comment by tchjeff** [comment]
The script checks if the necessary files to run OO Shutup are already downloaded. If not, it downloads them automatically. It then runs the program in a silent mode using a configuration file. This applies the tweaks in the background without any user interaction.

https://github.com/ChrisTitusTech/winutil/blob/4a7c8a35bf2e874579504fb81d5b3589823da7a0/config/tweaks.json#L2237

**Comment by Marterich** [comment]
In #1828 I overhauled the logic of what policies are applied (or reverted) by OO Shutup and also added a Button under the advanced tweaks section to open the OOSU GUI and modify the options manually
