### ISSUE TITLE
Re-enable location services

### ISSUE THREAD

**Issue by MrGamerDoesGames** [ChrisTitusTech/winutil#1813]
**Is your feature request related to a problem? Please describe.**
It'd be nice to have a button or toggle to reenable the location services. There are legitimate uses for this kind of telemetry, such as having night mode go based on your current location, or having the system clock work based on your location.

**Describe the solution you'd like**
Put a checkbox or button in the GUI, maybe next to the one that disables location tracking, to enable it.

**Comment by Marterich** [comment]
In PR #1828 I revamped how OO Shutup is applied, updated the config file to reflect the recommendations by oo-software, and thereby removed the settings that disable location services completely by default. 
I also added the functionality to completely remove any changes by OO Shutup and added a button to start the GUI to modify the policy changes

**Comment by MrGamerDoesGames** [comment]
> In PR #1828 I revamped how OO Shutup is applied, updated the config file to reflect the recommendations by oo-software, and thereby removed the settings that disable location services completely by default. 
> 
> I also added the functionality to completely remove any changes by OO Shutup and added a button to start the GUI to modify the policy changes  

Wow, perfect! Thank you! Has this already been merged or can I not do it now?

**Comment by Marterich** [comment]
The PR hast not been merged yet. 
If you want to apply the changes manually, please follow the steps i outlined in issue #1810
The Procedere ist identical
