### ISSUE TITLE
After executing the script, (WOL does not work anymore), re-activate Hibernate does not work?!

### ISSUE THREAD

**Issue by JuRo1971** [ChrisTitusTech/winutil#1814]
**Describe the bug**
WOL does not work anymore, re-activate Hybernate does not work

**To Reproduce**
I have a small homeserver Dell T20, running Win 10 pro for years (all up to date) with lights out (power management software). After running the desktop tweak settings, I unfortunately disabled Hibernate. Enabling Hibernate does not work. I had to enable this manual. 
Unfortunately, WOL does also not work anymore. I checked all common instructions in the internet, Whatever I do, WOL does not work anymore.

**Expected behavior**
Hybernate can be reactivated , WOL works

**Screenshots**

**Additional context**
Hi @ChrisTitusTech , is there maybe a service, disabled by the script, who is required for WOL. Wahtever I do, WOL will not functions anymore. I already did an inplace update but this also did not work. The only thing I can do now to restore an (very) old system backup .
Thanks JuRo

Edit: 

I just double checked the BIOS Settings and I identified that WOL was disabled. I was wondering how bios settings can be changed when I did not run the bios setup for years?!

**Comment by ModernTTY** [comment]
Can confirm that hibernation doesn’t have an undo, but there is a PR (#1799) that adds it, when it will be merged there will be an undo for hibernation.

**Comment by JuRo1971** [comment]
Yeah, please do so. Sounds good. Thanks!

**Comment by Matt-uSk** [comment]
I know it’s old, but I think I have a similar issue.
Just reinstall win11 with a modified iso with your new tool
Try and retry for two days to activate WOL but nothing works 
Checked 10 times in bios, activate/deactivate options
Checked all I can in network card settings 
Use Claude and ChatGPT to try « things » and nothing seems to work

**Comment by Matt-uSk** [comment]
Ok i found out why. And totally my fault with bad config.

Just in case, on a USW-Aggregation with 10gb sfp+, it cant negociate a 10mbps.... so i have to force in ma network card advanced settings the "low WOL speed" to 100mbs and it's working again.
