### ISSUE TITLE
How to only run `tweaks,json` (Desktop profile) using command line?

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1817]
Instead of using
```
irm https://christitus.com/win | iex
```
and waiting the GUI to load, waiting for winutil to install chocolatey, manually going to `Tweaks`, manually selecting `Desktop`, manually selecting `Run Tweaks`

I'm looking for a simple way to automate it using command line (CMD/PowerShell).
I want a short line that I can execute that will do `Tweaks` > `Desktop` > `Run Tweaks`,
I don't want to even load the GUI if possible.

**Comment by blusewill** [comment]
According to README.md.
You should be able to export the configuration file and run it using the following command
`irm https://christitus.com/win -Config [path-to-your-config] -Run | iex`

**Comment by blusewill** [comment]
So I have this code **DIDN'T TEST IT**
```
DownloadURL=https://blusewill.us.to/tweaks.json

Invoke-WebRequest $DownloadURL -OutFile $env:TEMP/tweaks.json

Invoke-WebRequest https://christitus.com/win -Config $env:TEMP/tweaks.json -Run | iex
```

which it should grab the file from the any hosting provider. I am using my website such as example here.
And Download it to %temp% folder and executive the toolbox
