### ISSUE TITLE
Microwin has no internet access 

### ISSUE THREAD

**Issue by UltraCenterHQ** [ChrisTitusTech/winutil#1819]
**Describe the bug**
There's no eternet/wifi conenction when I run the windows iso through vmware. even though I installed vmtools

**To Reproduce**
1. the only change I did to the Microwin settings was to disable "Keep Edge"
2. Use Windows 23H2 ISO from the Microsoft website

**Expected behavior**
For the eternet to work, just like on any other iso on my vmware

**Comment by ModernTTY** [comment]
Yes, this is a known issue, the VMware drivers might not work on Microwin, Chris has started working on it.
