### ISSUE TITLE
Clearing the Blur: Enhancing Image Clarity in Chris Titus Tech's Utility

### ISSUE THREAD

**Issue by djoudx** [ChrisTitusTech/winutil#1823]
![powershell_VXFFFEBqcq](https://github.com/ChrisTitusTech/winutil/assets/166333962/925ed43a-698c-4c7b-acf0-a5137e758122)

Problem: I encounter frustration when using Chris Titus Tech's utility due to blurry software images. The blurriness persists until I scroll or interact with the content, causing inconvenience and visual discomfort.

Desired Outcome: I seek a solution where the software images within Chris Titus Tech's utility remain clear and sharp without requiring user interaction to fix blurriness.

Alternative Solutions or Features Considered:

-1 Image Rendering Optimization: Implementing optimizations to ensure that software images within the utility are rendered clearly and sharply upon initial display, eliminating the need for manual intervention.

-2 Resolution Adjustment: Allowing users to adjust the resolution settings within the utility to better suit their display devices and prevent blurry images.

-3 Dynamic Image Loading: Introducing a feature where software images are dynamically loaded or preloaded to ensure optimal clarity and eliminate blurriness issues.

-4 Enhanced Image Compression: Utilizing advanced image compression techniques to reduce file sizes without sacrificing image quality, thereby preventing blurriness during display.
sorry guys but this message was written by chat gpt because of bad english but a summary is the windows utility in the software section when i scroll way up the down below softwares are blurry

**Comment by ruxunderscore** [comment]
This might be related to DPI scaling. I can't find anything in the winutil.ps1 that suggests that there is DPI Awareness set, but I am also not too familiar with the core code of the project, so I am not sure where to make the change myself.

**Comment by SkylerWallace** [comment]
I'm not sure I understand what you mean by "blurry software images" and unfortunately your screenshot doesn't seem to add any clarification.

WinUtil could also benefit from adding this to the XAML under Window to improve sharpness of icons. I don't think this would necessarily resolve the issue you're seeing though.
`RenderOptions.BitmapScalingMode="HighQuality"`

**Comment by ruxunderscore** [comment]
I think something like https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process could provide the fix being sought after. Again, I am not sure where to implement this.

**Comment by SkylerWallace** [comment]
Not sure if there's a way to implement that into this project.
Wonder if adding either of these to the XAML could help?
`SnapToDevicePixels="True"`
`UseLayoutRounding="True"`

https://learn.microsoft.com/en-us/dotnet/api/system.windows.uielement.snapstodevicepixels?view=windowsdesktop-8.0&redirectedfrom=MSDN#System_Windows_UIElement_SnapsToDevicePixels

https://learn.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=windowsdesktop-8.0&redirectedfrom=MSDN#System_Windows_FrameworkElement_UseLayoutRounding

**Comment by djoudx** [comment]
> I'm not sure I understand what you mean by "blurry software images" and unfortunately your screenshot doesn't seem to add any clarification.
> 
> WinUtil could also benefit from adding this to the XAML under Window to improve sharpness of icons. I don't think this would necessarily resolve the issue you're seeing though. `RenderOptions.BitmapScalingMode="HighQuality"`

its not blurry images its the font it looks blurry and annoying that's it

**Comment by djoudx** [comment]
look i really don't now anything about programing i just want to share this issue with you so maybe it will got solve soon and i don't think its from my dpi settings or pc i  use 21h1 windows 10

**Comment by djoudx** [comment]
![Uploading powershell_Itfnc14Ukf.png…]()

**Comment by djoudx** [comment]
its a bit laggy too when i scroll

https://github.com/ChrisTitusTech/winutil/assets/166333962/1cfa89c8-0d2c-41d9-9e08-5791dc56dc85

**Comment by Kingproone** [comment]
it may not come across that well through screenshots, but text on these pages is especially blurry

![Screenshot (375)](https://github.com/ChrisTitusTech/winutil/assets/118820223/f3a5be48-8192-4255-a17a-d9da23cebb4d)
![Screenshot (376)](https://github.com/ChrisTitusTech/winutil/assets/118820223/93d3ce20-060b-4467-8112-bc0f19005ee5)

**Comment by ruxunderscore** [comment]
#1845 Will fix most cases of blurry application, once testing is merged.
