### ISSUE TITLE
[processo terminato con codice 3489660927 (0xcfffffff)]

### ISSUE THREAD

**Issue by SJK9906** [ChrisTitusTech/winutil#1831]
**Describe the bug**

**To Reproduce**
1. Go to ' on main page of this repository copy: irm https://christitus.com/win | iex'
2. Click on 'open windows terminal as admin not powershell'
3. Scroll down to 'paste and run.'
4. wait a few seconds while interacting with program
5. See error

**Expected behavior**
i can start to use it
**Screenshots**

**Additional context**
if you try to re paste the string the program run correctly
error code is: 
[processo terminato con codice 3489660927 (0xcfffffff)]

**Comment by ChrisTitusTech** [comment]
Sometimes this happens and you just need to press enter to relaunch and up arrow and it will launch. I have never run into this error twice in a row.
