### ISSUE TITLE
This won't turn off updates in a tablet.

### ISSUE THREAD

**Issue by rdonnelly2** [ChrisTitusTech/winutil#1835]
**Describe the bug**
It won't turn off updates on my Chuwi Tablet

**To Reproduce**
1. Run the program
2. Turn off updates
3. Reboot
4. Windows update remain active, with no warning that your organization has turned them off.

**Expected behavior**
Updates off, with a message about the organization turning them off.

**Screenshots**

**Additional context**
I am using windows 10 for tablet.

**Comment by brrock** [comment]
Well written

**Comment by rdonnelly2** [comment]
> Well written

**Comment by rdonnelly2** [comment]
> Well written

Without input, what else can I tell him? Maybe it only works on desktop? It worked fine for me on vanilla and VM.

**Comment by brrock** [comment]
Out of Tablet mode?

**Comment by rdonnelly2** [comment]
For now I installed WUB 1.8 Windows update blocker. Not sure how you can run a tablet out of tablet mode? I just want to stop MS from trashing my systems and forcing W11. I use Linux for online stuff anyways.

winutil worked fine on desktop, and VM on PC. Maybe that is what you meant? "Out of Tablet mode?"
