### ISSUE TITLE
"Disable Storage-Sense" only enables feature.

### ISSUE THREAD

**Issue by Squtzy** [ChrisTitusTech/winutil#1838]
**Describe the bug**
When running the "Disable Storage-Sense" script it enables storage sense instead of disabling it. Tried manually enabling storage-sense and rebooting PC to see if that would fix it but it still stays enabled when running the script to disable it.

**To Reproduce**
When running the script like I did first time I had already disabled Storage-Sense, running the script again does not disable storage-sense despite it being enabled by the script first time.

**Expected behavior**
Running the script I expect it to disable this feature and not only enabling it.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/132845312/de3d3771-65f3-4a0e-a161-4f2e4aca65fa)
![image](https://github.com/ChrisTitusTech/winutil/assets/132845312/259c3633-24b6-4380-9e5d-551c35a3b62c)

**Comment by og-mrk** [comment]
PR https://github.com/ChrisTitusTech/winutil/pull/1843 should fix this issue once it has been merged into test branch, then inevitably into the main branch, thanks for pointing this out @Squtzy 😄
