### ISSUE TITLE
ImageGlass

### ISSUE THREAD

**Issue by felon1337** [ChrisTitusTech/winutil#1839]
**Describe the bug**
You have a link to an image viewer known as ImageGlass which is no longer around anymore and apparently the devs put malware in their software.

https://www.reddit.com/r/Windows10/comments/sa7bys/popular_image_viewer_imageglass_quietly_added/

**To Reproduce**
1. Go to Installs
2. Click on Image Glass

**Additional context**
Reconsider the recommendation of this software IMO.

**Comment by RisPNG** [comment]
That is such an old thread. ImageGlass no longer have 'SpiderService' as per commit 2 years ago. https://github.com/d2phap/ImageGlass/commit/3eb1079aea4599ade80720dc33f9f617f41a8ff7

**Comment by ruxunderscore** [comment]
Yeah. This was two years ago, this is no longer an issue.
