### ISSUE TITLE
Request for some more useful Open-Source apps .

### ISSUE THREAD

**Issue by Wingzzzzy** [ChrisTitusTech/winutil#184]
I think it would be good under Utility's to add an open-source alternative some programs.

The programs that I am talking about are:

RustDesk is an open-source Alternative to TeamViewer that dose a good job on what it needs
Winget Command
> winget install -e --id RustDesk.RustDesk

Website : [https://rustdesk.com/](https://rustdesk.com/)

Jami is a very good looking alternative to stuff like Skype and a bit of Discord. Its all private and open-Source
Winget Command
> winget install -e --id SFLinux.Jami

Website : [https://jami.net/](https://jami.net/)

JDownloader 2 a good way to download multiple stuff from the internet at a way faster speed then using Browsers (Usefull with archive.org too)
Winget Command
> winget install -e --id AppWork.JDownloader

Website : [https://jdownloader.org/](https://jdownloader.org/)

**Comment by Megamezzomixer** [comment]
I totally agree with RustDesk.
