### ISSUE TITLE
[BUG] Robocopy of OneDrive folder during OneDrive removal fails if username contains a space

### ISSUE THREAD

**Issue by jwin74** [ChrisTitusTech/winutil#1848]
**Describe the bug**
In "Advanced Tweaks", when choosing "Remove OneDrive", the script performs a RoboCopy of the OneDrive folder content to the root user profile directory. If the username is in two or more words, like "Firstname Lastname", the Robocopy fails, with an "ERROR : Invalid Parameter #3".

The full message from Robocopy is as follows (Anonymized for Privacy)

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Friday, 19 April 2024 14.31.28
   Source - C:\Users\FirstName\
     Dest - C:\WINDOWS\system32\LastName\OneDrive\

    Files :
  Options : /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

ERROR : Invalid Parameter #3 : "C:\Users\FirstName"

       Simple Usage :: ROBOCOPY source destination /MIR

             source :: Source Directory (drive:\path or \\server\share\path).
        destination :: Destination Dir  (drive:\path or \\server\share\path).
               /MIR :: Mirror a complete directory tree.

    For more usage information run ROBOCOPY /?

**To Reproduce**
1. Create a Windows User with a space character in the username, ex. "Chris Titus"
2. Log in as the newly created user.
3. Install or ensure OneDrive is installed for the current user
4. Open the WinUtil program
5. Select "Tweaks"
6. Select "Remove OneDrive" from "Advanced Tweaks" section
7. Click "Run Tweaks"
9. Examine Script Window, and look for where the copy prior to removal of OneDrive takes place

**Expected behavior**
What was expected was that the content of the OneDrive Folder was copied to a directory called OneDrive in the Users directory.

**Screenshots**
![WinUtil-OneDrive-Removal-Bug](https://github.com/ChrisTitusTech/winutil/assets/18344600/9962061f-0fa7-4f44-ada5-38268f420cb1)

**Additional context**

**Comment by og-mrk** [comment]
This was fixed in a [Recent PR](https://github.com/ChrisTitusTech/winutil/pull/1851), if you want/have the time to test out [the Test Branch of WinUtil](https://github.com/ChrisTitusTech/winutil/tree/test-2024-03-30), then please go ahead 😄. If not, then it's completely understandable.
