### ISSUE TITLE
Error in:  Invoke-WPFMicrowin

### ISSUE THREAD

**Issue by Mandyregenboog** [ChrisTitusTech/winutil#1849]
Calling the Wintool from powershell to generate Microwin failed, this is the outcome:

====Chris Titus Tech=====
=====Windows Toolbox=====
Checking if Chocolatey is Installed...
===========================================
--       Chocolatey is installed        ---
===========================================                                                         Version: v2.2.2                                                                                     Invoking WPFGetIso                                                                                           _                     __    __  _                                                            /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __                                                     /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \                                                   / /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |
\/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|
oscdimg.exe on system: True
File path C:\Win_CTT\Windows11_23H2_22631-2715.ISO
You have enough space for this operation.
Mounting Iso. Please wait.
Done mounting Iso MSFT_DiskImage (ImagePath = "C:\Win_CTT\Windows11_23H2_22631-2715.IS..., StorageType = 1)                                                                                             Iso mounted to 'K'                                                                                  Setting up mount dir and scratch dirs                                                               Mounting Iso. Please wait.                                                                          Done setting up mount dir and scratch dirs
Scratch dir is R:\Scratch\Scrach
Image dir is R:\Scratch\micro
Copying Windows image. This will take awhile, please don't use UI or cancel this step!
Copy 1030(s) from K: to R:\Scratch\micro
Copy complete! Total Time: 0m33s
Getting image information R:\Scratch\micro\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '1 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************
Check the UI for further steps!!!
Target ISO location: R:\Win11_CTT_1.iso
Index chosen: '1' from 1 : Windows 11 Pro                                                           Mounting Windows image. This may take a while.                                                      Mounting complete! Performing removal of applications...                                            Remove Features from the image                                                                      Removing features complete!                                                                         Removing Appx Bloat
Invoke-WPFMicrowin : An unexpected error occurred: The request is not supported.
At line:2718 char:24
+         "WPFMicrowin" {Invoke-WPFMicrowin}                                                        +                        ~~~~~~~~~~~~~~~~~~                                                             + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                      + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin                                                                                                      Unmounting Registry...                                                                              ERROR: The parameter is incorrect.                                                                  ERROR: The parameter is incorrect.                                                                  ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.
Unmounting image...
Dismount-WindowsImage : The system cannot find the path specified.
At line:3887 char:9
+         Dismount-WindowsImage -Path $scratchDir -Save
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Dismount-WindowsImage], COMException                   + FullyQualifiedErrorId : Microsoft.Dism.Commands.DismountWindowsImageCommand                                                                                                                       Exporting image into R:\Scratch\micro\sources\install2.wim                                          Remove old 'R:\Scratch\micro\sources\install.wim' and rename R:\Scratch\micro\sources\install2.wim  Windows image completed. Continuing with boot.wim.
Mounting boot image R:\Scratch\micro\sources\boot.wim into R:\Scratch\Scrach
Invoke-WPFMicrowin : An unexpected error occurred: The user attempted to mount to a directory that
is not empty.  This is not supported.
At line:2718 char:24
+         "WPFMicrowin" {Invoke-WPFMicrowin}
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin

Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Unmounting image...
Dismount-WindowsImage : The specified mounted image cannot be committed back into the WIM.  This
occurs when an image has been through a partial unmount or when an image is still being mounted.
If this image was unmounted with commit earlier, then the commit probably succeeded.  Please
validate that this is the case and then unmount without commit.
At line:3953 char:9
+         Dismount-WindowsImage -Path $scratchDir -Save
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Dismount-WindowsImage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.DismountWindowsImageCommand

Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\Admin\AppData\Local\Temp\oscdimg.exe
Exception calling "Start" with "0" argument(s): "The specified executable is not a valid
application for this OS platform."
At line:3976 char:9
+         $oscdimgProc.Start()
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception

Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."
At line:3977 char:9
+         $oscdimgProc.WaitForExit()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)
ISO creation failed. The  R:\Scratch\micro  directory has not been removed.

**Comment by hpsxrb** [comment]
the same thing happens to me

**Comment by Amueller36** [comment]
Same problem here.

**Comment by regym48** [comment]
i have same issue, is there any solution to fix this?
