### ISSUE TITLE
How can I reset everything to normal 

### ISSUE THREAD

**Issue by DEGGAXTREME** [ChrisTitusTech/winutil#185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WaterMelon4938** [comment]
Hit "Undo All Tweaks" in the Tweaks section.

**Comment by bonniesimon** [comment]
Hey if I change my update setting to Security updates only, then can I undo this in the future?

**Comment by WaterMelon4938** [comment]
Yes

**Comment by ChrisTitusTech** [comment]
> Hey if I change my update setting to Security updates only, then can I undo this in the future?

Just click Default Settings in Update Section to reset those back to stock
