### ISSUE TITLE
Error: The term 'Install-WinGetPackage' is not recognized...

### ISSUE THREAD

**Issue by wddoan** [ChrisTitusTech/winutil#1855]
When I try to install any applications with WinUtil, I get the following error:

Error: The term 'Install-WinGetPackage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

This occurs on all of my systems, all running win10 or win11

I can install apps manually with winget

WinUtil version is 24.04.21

**Comment by toe7685** [comment]
same here

**Comment by ChrisTitusTech** [comment]
Thanks guys, I'm doing a merge to fix this right now.

**Comment by ChrisTitusTech** [comment]
Merged in #1856 relaunch and it should all be fixed.
