### ISSUE TITLE
Changing the location of programs in Chocolatey/Winget

### ISSUE THREAD

**Issue by GitesHubisz** [ChrisTitusTech/winutil#1858]
**Describe the bug**
The error is that when changing the folder to which it wants to have applications from this program installed, through the setx command, the winutil program inteprets that chocolatey is not installed. When I try to install through winutil, it pops up an error that the program is installed and will not install further.

When trying to install a program (such as git):

After pressing enter, winutil installs winget (which I had not planned to do) and installs the program in the drive with the operating system (C:\Program Files)

**To Reproduce**
1. Have fresh installed Windows
2. Install chocolatey throught this command from the CL docs: ```Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))```
3. on powershell/cmd (admin) type: ```setx ChocolateyInstall "F:\Choco"```
4. open WinUtil ```irm https://christitus.com/win | iex```
5. Reset computer (because I have made changes in tweaks)
6. After reset, open WinUtil
7. The errors about chocolatey 
```

    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T                                                         CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T                                                        C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T                                                       C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT                                                      C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
Checking if Chocolatey is Installed...
===========================================
---    Chocolatey is not installed      ---
===========================================
Seems Chocolatey is not installed, installing now.
WARNING: 'choco' was found at 'C:\ProgramData\chocolatey\bin\choco.exe'.
WARNING: An existing Chocolatey installation was detected. Installation will not continue. This script will not
overwrite existing installations.
If there is no Chocolatey installation at 'F:\Choco', delete the folder and attempt the installation again.

Please use choco upgrade chocolatey to handle upgrades of Chocolatey itself.
If the existing installation is not functional or a prior installation did not complete, follow these steps:
 - Backup the files at the path listed above so you can restore your previous installation if needed.
 - Remove the existing installation manually.
 - Rerun this installation script.
 - Reinstall any packages previously installed, if needed (refer to the lib folder in the backup).

Once installation is completed, the backup folder is no longer needed and can be deleted.
Chocolatey v2.2.2
Directory 'F:\Choco\lib' does not exist.
Nothing to change. Config already set.
```
8. (Optional) Install some program (for example, git)

**Expected behavior**
I would like to install the programs in the Folder "F:\Choco" and not on "C:\Program Files

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/122703810/3b74b85b-f2e0-4d06-b87d-64fec1400d2d)

**Additional context**
It will looks the same with winget and ```setx WINGET_ROOT "F:\WinGet"```

Thanks in advance.

**Comment by Marterich** [comment]
According to the documentation of Chocolatey, you have to set the ChocolateyInstall environment Variable BEFORE you run the install Script, so Chocolatey will be installed in the right location from the start. 
Winutil *should* be able to handle a different install location from what I can tell from a glance at the installation procedure.

https://docs.chocolatey.org/en-us/choco/setup#installing-to-a-different-location

If I misunderstood your problem please let me know.

**Comment by ruxunderscore** [comment]
Also, keep in mind that programs installed from the winutil Install Tab will use Winget to install the program. Some of the software isn't on Chocolatey so Winget is the best, if we want all the software to installable through winutil. Winget does have a `--location|-l` but it would probably take some time to implement in the future, if we want that to be customizable by the user. 

I'll let @ChrisTitusTech decide if that is a direction we should go, but I don't have any UI experience with PowerShell, so I couldn't tell you how it would be implemented.

**Comment by GitesHubisz** [comment]
> According to the documentation of Chocolatey, you have to set the ChocolateyInstall environment Variable BEFORE you run the install Script, so Chocolatey will be installed in the right location from the start. Winutil _should_ be able to handle a different install location from what I can tell from a glance at the installation procedure.
> 
> https://docs.chocolatey.org/en-us/choco/setup#installing-to-a-different-location
> 
> If I misunderstood your problem please let me know.

I reinstalled chocolatey, but when I try to install a program (such as vlc) it is downloaded using winget. Probably what you said can work correctly, but at this point I can not verify it


> Also, keep in mind that programs installed from the winutil Install Tab will use Winget to install the program. Some of the software isn't on Chocolatey so Winget is the best, if we want all the software to installable through winutil. Winget does have a `--location|-l` but it would probably take some time to implement in the future, if we want that to be customizable by the user.
> 
> I'll let @ChrisTitusTech decide if that is a direction we should go, but I don't have any UI experience with PowerShell, so I couldn't tell you how it would be implemented.

Understood.

Also as of now, thank you for your answers. I am closing the thread and will wait for the program updates
