### ISSUE TITLE
Brave install has a virus?

### ISSUE THREAD

**Issue by Turgo82** [ChrisTitusTech/winutil#1860]
Windows Defender is reporting a virus after Brave is installed then lunched.
This is what the command line says its installing from "https://updates-cdn.bravesoftware.com/build/Brave-Release/x64-rel/win/124.1.65.114/brave_installer-x64.exe"

![image](https://github.com/ChrisTitusTech/winutil/assets/141803920/949ad5aa-3e61-4c19-8f24-70d131268e22)

**Comment by S3curityPlu5** [comment]
RUN Virustotal on that its could be falsetto positivo?

**Comment by og-mrk** [comment]
Interesting scan result you got there @Turgo82, could it be outdated Definition Updates for Windows Defender?

Tried scanning the installer on my system (Windows 11 23H2, Build Number 22631.3447), and it should it as a clean file (without any viruses)

and did a Virus Total Scan just to make sure, and the results shows that it's a clean file as well, link to the scan: https://www.virustotal.com/gui/file/7625d0e3a61cabedb3b29dd4a46a1fdeee4def2899e666c744279f239f611e87

**Comment by Turgo82** [comment]
The installer looks clean as well on my end. Brave appears to generate a file that defender detects when brave is opened. Installing Brave from there main site doesn't have this issue.

**Comment by ModernTTY** [comment]
@Turgo82 I see that it flagged a .crx file wich is a Chromium extension file this might be a built in extension not sure. Could you submit the specific extension file to Virustotal and send a link to results.
