### ISSUE TITLE
Config file with only tweaks is trying to install features and applications.

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1866]
**Describe the bug**
Config file with only tweaks is trying to install features and applications.

**To Reproduce**
1. Export config file `tweaks.json` and save in %temp%.
```
{
    "WPFTweaks":  [
                      "WPFTweaksWifi",
                      "WPFTweaksHome",
                      "WPFTweaksStorage",
                      "WPFTweaksHiber",
                      "WPFTweaksDVR",
                      "WPFTweaksTele",
                      "WPFTweaksAH",
                      "WPFTweaksLoc",
                      "WPFTweaksOO",
                      "WPFTweaksServices"
                  ]
}
```
2. Run `tweaks.json` with `winutil`.
```
iex "& { $(irm christitus.com/win) } -Config $env:TEMP\tweaks.json -Run"
```

**Expected behavior**
`winutil` will only apply tweaks.

**Actual behavior**
`winutil` is trying to install features and applications.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/13978119/0b1c53b5-d060-41bf-a03d-54fd13d5fe1c)
![image](https://github.com/ChrisTitusTech/winutil/assets/13978119/8e554c8d-82c1-4041-8ec8-deb646631760)
![image](https://github.com/ChrisTitusTech/winutil/assets/13978119/972ed4d3-7a41-419b-b6fa-c799e7ab8d43)

**Comment by lotusflowr** [comment]
> Temporary solution:
> 
> ```
> $winutilRegex1='(?ms)(?<=^\s*Write-Host "Installing features..."\s*).*?(?=\s*Write-Host "Done.")'
> (Get-Content -raw $env:TEMP\winutil.ps1) -replace $winutilRegex1, '' | Set-Content $env:TEMP\winutil.ps1
> ```

Thank you so much! This was very helpful.
