### ISSUE TITLE
Group Policy Tweaks (Minimalism - Win11 22H2)

### ISSUE THREAD

**Issue by kklouzal** [ChrisTitusTech/winutil#187]
Windows 11 Pro 22H2 OS Build 22621.521

I just reinstalled the OS, pulled all updates, and painstakingly went through ALL the available options inside gpedit.msc

Here are changes I make to _every_ computer I touch.
```
[User Configuration]
	[Administrative Templates]
		[Start Menu and Taskbar]
		-Remove Notifications and Action Center - Enabled
		[Windows Components]
			[Cloud Content]
			-Configure Windows spotlight on lock screen - Dsabled
			-Turn off Spotlight collection on Desktop - Enabled
			-Do not use diagnostic data for tailored experiences - Enabled
			-Do not suggest third-party content in Windows Spotlight - Enabled
			-Turn off all Windows spotlight features - Enabled

[Computer Configuration]
	[Administrative Templates]
		[Control Panel]
		-Allow Online Tips - Disabled
			[Regional and Language Options]
				[Handwriting personalization]
				-Turn off automatic learning - Enabled
		[Start Menu and Taskbar]
		-Remove Recommended section from Start Menu - Enabled
		[System]
		-Download missing COM components - Enabled
			[Filesystem]
				[NTFS]
				-Enable NTFS non-paged pool usage - Enabled
			[Power Management]
				[Power Throttling Settings]
				-Turn off Power Throttling - Enabled
			[User Profiles]
			-Turn off the advertising ID - Enabled
		[Windows Components]
			[Application Compatibility]
			-Prevent access to 16-bit applications - Enabled
			-Turn off Application Telemetry - Enabled
			-Turn off Application Compatibility Engine - Enabled
			-Turn off Program Compatibility Assistant - Enabled
			-Turn off Inventory Collector - Enabled
			-Turn off SwitchBack Compatibility Engine - Enabled
			-Turn off Steps Recorder - Enabled
			[Cloud Content]
			-Turn off cloud optimized content - Enabled
			-Turn off cloud consumer account state content - Enabled
			-Do not show Windows tips - Enabled
			-Turn off Microsoft consumer experiences - Enabled
			[Data Collection and Preview Builds]
			-Allow device name to be sent in Windows diagnosticdata - Disabled
			-Allow Diagnostic Data - Enabled: Send required diagnostic data
			-Do not show feedback notifications - Enabled
			-Configure collection of browsing data for Desktop Analytics - Disabled
			[Delivery Optimization]
			-Download Mode - Enabled: Group (2)
			[Desktop Gadgets]
			-Turn off desktop gadgets - Enabled
			[Edge UI]
			-Disable help tips - Enabled
			[Maps]
			-Turn off Automatic Download and Update of Map Data - Enabled
			[Messaging]
			-Allow Message Service Cloud Sync - Disabled
			[Microsoft Defender Antivirus]
			-Allow antimalware service to startup with normal priority - Disabled
				[Scan]
				-Configure low CPU priority for scheduled scans - Enabled
			[Microsoft Edge]
			-Allow Microsoft Edge to pre-launch at... - Enabled: Allow pre-launching
			-Allow Microsoft Edge to start and load... - Enabled: Allow tab preloading
			[One Drive]
			-Prevent the usage of OneDrive for file storage - Enabled
			[Online Assistance]
			-Turn off Active Help
			[Push To Install]
			-Turn off Push To Install service - Enabled
			[Speech]
			-Allow Automatic Update of Speech Data - Disabled
			[Widgets]
			-Allow widgets - Disabled
			[Windows Ink Workspace]
			-Allow Windows Ink Workspace - Disabled
			[Windows Mobility Center]
			-Turn off Windows Mobility Center - Enabled
			[Windows Remote Shell]
			-Allow Remote Shell Access - Disabled
			[Windows Security]
				[Systray]
				-Hide Windows Security Systray - Enabled
```
Would love to see these adopted. Need to put a script together myself to quickly make these changes.

Combined with running your tool and nothing else installed on the system:
![image](https://user-images.githubusercontent.com/2928845/192108712-39cdfa8c-a109-4aa1-b2ef-2699131af7ba.png)

**Comment by Triplesweet** [comment]
if I am correct the O&O shut up script does most stuff in here, maybe you can look thro them and see with ones you mentioned the O&O doesn't have?

**Comment by jcolley** [comment]
I would imagine requests like this one, that target a very specific subset of users, might be better off having new a menu option whereby custom scripts could be assigned their own button(s).

**Comment by Triplesweet** [comment]
@jcolley i say otherwise, since most tweaks that people do are stuff that maybe less than 1% users are using, like who actually opens the start page to see what windows think should be you next app be, so just disable it,  or the fact that you WILL open the browser of your choice to do the search you want, so disable the start internet search, i say there should be a specific tab for tweaks that change something that most users would use, something like disabling notification center and you have to do it yourself, or there will be 100 different scripts for different people and no one will know what is the correct one

**Comment by kklouzal** [comment]
Some of these group policy changes have performance implications like:
-Enable NTFS non-paged pool usage - Enabled
-Allow antimalware service to startup with normal priority - Disabled
-Configure low CPU priority for scheduled scans - Enabled
-Prevent access to 16-bit applications - Enabled
-Turn off Application Compatibility Engine - Enabled
-Turn off SwitchBack Compatibility Engine - Enabled
There were others. Some of these turn off components in windows which only exist to provide support for legacy applications. Disabling these components free up system resources and increase overall responsiveness of the system.

Again, these are settings I change for *every* computer I touch. I manage hundreds of computers as an IT Administrator, never has a client complained of any missing features or application incompatibilities.

There are some additional registry tweaks I apply to systems, I don't have the list available right now but will post them here tomorrow.

**Comment by ChrisTitusTech** [comment]
I'm going to close this issue as setting a lot of policies will make the project hard to manage and they can be done through registry a bit easier.
