### ISSUE TITLE
Clipboard disabled managed by organization

### ISSUE THREAD

**Issue by genesis224** [ChrisTitusTech/winutil#1871]
![Screenshot 2024-04-24 182823](https://github.com/ChrisTitusTech/winutil/assets/63331205/9697c8ad-1a14-4989-a49f-1131717eaa64)
after applying the tweaks it seems now I cant enable my clipboard now can somebody help?

**Comment by Marterich** [comment]
Two Options: 
- undo the recommended tweak oo shutup (all the contained tweaks) 
- Open oo shutup under advanced tweaks, search for the Option regarding the Clipboard History in the gui and disable the option
