### ISSUE TITLE
Add a few telemetry scheduled tasks to disable

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1877]
```
		# This task shows various Map related toasts
		"MapsToastTask",
```
```
		# Initializes Family Safety monitoring and enforcement
		"FamilySafetyMonitor",
```
```
		# Synchronizes the latest settings with the Microsoft family features service
		"FamilySafetyRefreshTask",
```
```
		# XblGameSave Standby Task
		"XblGameSaveTask"
```

**Comment by ahscolan2** [comment]
> ```
> Disable-ScheduledTask -TaskName MapsToastTask -TaskPath "\Microsoft\Windows\Maps\"
> ```
> 
> ```
> Disable-ScheduledTask -TaskName FamilySafetyMonitor -TaskPath "\Microsoft\Windows\Shell\"
> ```
> 
> ```
> Disable-ScheduledTask -TaskName FamilySafetyRefreshTask -TaskPath "\Microsoft\Windows\Shell\"
> ```
> 
> ```
> Disable-ScheduledTask -TaskName XblGameSaveTask -TaskPath "\Microsoft\XblGameSave\"
> ```

should be able to be done with oo shutup, no?

**Comment by ahscolan2** [comment]
I was kind of high when I typed that. I meant 'Revo' but mixed it up with 'oo shutup' and I thought you needed help to change it and that you didn't know how to do it manually, so I told you to use Revo Uninstaller. My bad.
