### ISSUE TITLE
Get Installed does not check any of the boxes

### ISSUE THREAD

**Issue by ceramicv** [ChrisTitusTech/winutil#1880]
**Describe the bug**
Clicking on the "Get Installed" button does not check any boxes even though I know many of the displayed apps are installed

**To Reproduce**
As above

**Expected behavior**
Checks to appear next to installed software

**Screenshots**
N/A

**Additional context**
Not to be confused with issues I have on another machine (Windows 10) I will submit separately

**Comment by Marterich** [comment]
Winutil relies heavily on winget so if winget isn't able to query your programs, winutil won't be able to show them as installed. If you run the command `winget list` manually in the terminal or Powershell, does it produce any output?

**Comment by ceramicv** [comment]
After multiple attempts at reinstall winget, trying other updates it is finally working
