### ISSUE TITLE
can these features be added?

### ISSUE THREAD

**Issue by GHOSTS15** [ChrisTitusTech/winutil#1893]
**Is your feature request related to a problem? Please describe**

 **Describe the solution you'd like**

- [ ] **Ability to download firefox developer edition**
      https://www.mozilla.org/en-US/firefox/developer/

- [ ] **Adding translations**
      I could maybe translate it into Italian

- [ ] **Add subcategory “Antivirus”**

- [ ] **Add the ability to choose where to install the various apps**
    (except for some apps that may not work corectually if installed otherwise)
    
- [ ] **Ability to download kaspersky anitivurs, kaspersky password manager and kaspersky vpn**
     

**Describe alternatives you've considered**
//

**Additional Question**
Is it possible to make an open source program ,which keeps track of where you install the various software and once uninstalled (via control panel) you can check through the program if it has been uninstalled completely (because unnecessary files remain that just take up space)?

**Comment by v-Kaefer** [comment]
For your additional question, you can install Revo Uninstaller, which is already on winutil!

**Comment by GHOSTS15** [comment]
I could use revo, I also used it and the pro version, but it did not convince me and I did not like it, I would like something free and done better

**Comment by ModernTTY** [comment]
> * [ ]  **Ability to download firefox developer edition**
>   https://www.mozilla.org/en-US/firefox/developer/

I’m not sure if we should add a ton of beta versions of all apps it will just pollute Winutil.
> * [ ]  **Adding translations**

Could possibly do I don’t think it will be easy to translate to a bunch of languages also PowerShell is an interpreted language so we have to watch the speed of Winutil but possibly could be done.
> * [ ]  **Add subcategory “Antivirus”**

Probably not going to happen because I’m not sure if @ChrisTitusTech will allow that.
> * [ ]  **Add the ability to choose where to install the various apps**

Probably could be implemented I will try to start implementing that.
> * [ ]  **Ability to download kaspersky anitivurs, kaspersky password manager and kaspersky vpn**

Same issue as antivirus.

**Comment by ahscolan2** [comment]
> I could use revo, I also used it and the pro version, but it did not convince me and I did not like it, I would like something free and done better

it is free? and by far the best in the market (in my opinion)

**Comment by Yuuh15** [comment]
He could also try [Bulk Crap Uninstaller (BCU)](https://www.bcuninstaller.com/). Might not be as feature complete, but it is open source and totally free.
