### ISSUE TITLE
add software

### ISSUE THREAD

**Issue by aut0-m8** [ChrisTitusTech/winutil#1897]
The program installer seems to be missing a few things, such as matrix clients.

Please add:
KeePassXC
SchildiChat
Element
RustDesk

Also, with the growing list of programs it might be better to make dropdowns.

https://keepassxc.org/
https://schildi.chat/
https://element.io/
https://rustdesk.com/

**Comment by og-mrk** [comment]
Hello @aut0-m8
These requests of yours will be Tracked in Issue https://github.com/ChrisTitusTech/winutil/issues/1782

Thanks for your suggestions, will look into them as soon as I can 👍

**Comment by aut0-m8** [comment]
Apparently not...
![image](https://github.com/ChrisTitusTech/winutil/assets/144866024/b3d3b7ec-5312-4930-9bf0-e35f6ee77e72)

**Comment by aut0-m8** [comment]
Oh, I see, it says "Matrix", however matrix is a protocol and not a client, would help to rename element and add context saying what it runs on

**Comment by ruxunderscore** [comment]
> Oh, I see, it says "Matrix", however matrix is a protocol and not a client, would help to rename element and add context saying what it runs on

Agreed. I think I had noticed this recently when writing the winget fixes. If no one else does, I can push a PR later.

**Comment by og-mrk** [comment]
> > Oh, I see, it says "Matrix", however matrix is a protocol and not a client, would help to rename element and add context saying what it runs on
> 
> Agreed. I think I had noticed this recently when writing the winget fixes. If no one else does, I can push a PR later.
> 
> Edit: I created a PR using Github in the browser since it was simple enough.

Thanks @ruxunderscore , wanted to do this once it was brought up by @aut0-m8 , but never found the appropriate time to do so.

**Comment by og-mrk** [comment]
@aut0-m8 The Additions you've requested are all found in WinUtil's App List.
After PR https://github.com/ChrisTitusTech/winutil/pull/1930 is merged, the problem behind the naming should be resolved.

if there's anything else related to this Issue Ticket, then please go ahead and share/point them out with us.

**Comment by aut0-m8** [comment]
Hello, 
Looks like I didn't notice them, looking back on older versions and it just looks like naming issues, you're correct
