### ISSUE TITLE
Choosing a default install/storage directory

### ISSUE THREAD

**Issue by DJMoffinz** [ChrisTitusTech/winutil#190]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the default install and storage directory for everything is the C drive, which is my boot drive and isn’t able to hold much.

**Describe the solution you'd like**
Having a drop down menu with all installed drives somewhere in winutil, and being able to change the default locations for everything over to that drive.

**Describe alternatives you've considered**
Doing it manually. It’s a long and cumbersome process.

**Additional context**
I’m thinking of doing a fresh install of Windows soon, and don’t want to go through the horror of changing everything over again.

**Comment by DeveloperDurp** [comment]
Looks like winget has that ability but I assume depending on the application could introduce bugs so additional testing would be required. 
https://github.com/microsoft/winget-cli/issues/489

**Comment by ChrisTitusTech** [comment]
This is outside the scope of this tool. Adds a layer of complexity and not something I want to tackle for something that is meant to install multiple programs at once.

**Comment by DJMoffinz** [comment]
> This is outside the scope of this tool. Adds a layer of complexity and not something I want to tackle for something that is meant to install multiple programs at once.

fair enough i suppose. keep up the good work ^^
