### ISSUE TITLE
OO Shutup not allowing customization 

### ISSUE THREAD

**Issue by TheShadowed** [ChrisTitusTech/winutil#1905]
**Describe the bug**
OO Shutup disables Clipboard History and can not be re-enabled without modifying the registry 
**To Reproduce**
1. Go to 'Tweaks'
2. Click on 'Desktop'
3. Click 'Run Tweaks'
5. Click "Custimize OO Shutup Tweaks"
6. Search "Activity History and Clipboard"
7. Turn off "disable storage of clipboard history [...]
8. Run Tweaks again
9. Restart PC
10. No change

**Expected behavior**

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/31214103/8a9640ac-4d71-4c36-a67c-9a7b02f95d23)

**Additional context**

**Comment by Marterich** [comment]
Answered in https://github.com/ChrisTitusTech/winutil/issues/1871#issuecomment-2074847855
