### ISSUE TITLE
"Disable GameDVR" tweak causes Color Management to not get applied in Exclusive Fullscreen

### ISSUE THREAD

**Issue by Luadih** [ChrisTitusTech/winutil#1907]
**Describe the bug**
Disabling GameDVR basically makes ICC Profiles or any Color Management done through Windows to not get applied while in Exclusive Fullscreen in games.

This can be kind of confusing with some games because when you start them it seems to get applied but if you alt tab and go inside the game again it doesn't.

**To Reproduce**
1. Have some kind of Color Management applied through Windows (Different Brightness or Gamma is more noticeable)
2. Disable GameDVR
3. Open a Game
4. Switch between window/borderless window and fullscreen modes
5. Compare

Note: Alt+Tab also works but comparison its easier by switching display modes

**Expected behavior**
I won't say that disabling GameDVR should keep the colors applied while in Fullscreen (since I think it may be something with the way GameDVR does what it does), but I'm reporting it in case someone goes through the same pain of trying to troubleshoot why is it happening after using Winutil and not knowing that GameDVR is the cause.

For Winutil I would just say to add a note that it may cause this, or if it's just one of the registry keys that causes it to not change it if possible.

**Comment by Luadih** [comment]
I can try it yeah, but I will only be able to notice the color problem

**Comment by Luadih** [comment]
Restoring **"GameDVR_DXGIHonorFSEWindowsCompatible"** to its original value after the tweak is applied seems to fix the color management issue, but I believe I cannot test if it causes more problems when trying to open overlays

I tested with Counter Strike 2 (with and without vulkan just in case) and Rocket League. I think this is worth saying since there is "GameDVR_HonorUserFSEBehaviorMode" which has a really close name? though it may be for something completely different

Something I missed to note in the original issue, is that this doesn't apply to just color management but it also affects to how quickly alt+tab and changing display modes switch, which is really noticeable by me switching from borderless to exclusive fullscreen in Rocket League

**Comment by Luadih** [comment]
> So what solves the alt+tab issue?

Sorry, I didn't make it really that clear. Both the alt+tab and Color Management problems are fixed with **"GameDVR_DXGIHonorFSEWindowsCompatible"** set to 0.

While setting **"GameDVR_DXGIHonorFSEWindowsCompatible"** to 0, fullscreen has the correct colors and the alt+tab speed is normal, it is possible to break it again just by going to each game and in its compatibility tab simply "disabling fullscreen optimizations" there.

So:
- DXGIHonor Registry Key = 0 & Disable Fullscreen Optimizations (per program) = Unticked | **Colors and alt+tab are fine**
- DXGIHonor Registry Key = 1 & Disable Fullscreen Optimizations (per program) = Unticked | **Colors and alt+tab are broken**
- DXGIHonor Registry Key = 0 & Disable Fullscreen Optimizations (per program) = Ticked | **Colors and alt+tab are broken**

I also saw that last table but I don't know if another combination of registry keys would change anything for the better, so I didn't test further

**Comment by Luadih** [comment]
No, that doesn't give any issues. In fact I think I was already trying with "AllowGameDVR" set to 0.

I did play some games recently and didn't have any issues having it set up like this image:
![image](https://github.com/ChrisTitusTech/winutil/assets/50816896/026ce642-4dda-49dc-bdbf-2b195aa390a6)

**Comment by Luadih** [comment]
I close this now, since the fix made for it in #1934 was merged in

**Comment by mirh** [comment]
Idk how to break you the news, but disabling FSO doesn't break FSE.. it's actually how you get the real thing to begin with.
Its whole point is about just letting the application control the screen (with some games just once [resetting](https://forums.guru3d.com/threads/application-color-sustainer-icc-profile-enforcer.386325/) the color profile, while some others constantly trying to [override](https://colorclutch.sourceforge.net/) it).

EDIT: there might [be more](https://github.com/shoober420/windows11-scripts/blob/main/EnableFullscreenOptimizations.bat#L248) to it

**Comment by Luadih** [comment]
This is a really old issue you are replying to, so I will not remember my exact thought process at the time, but basically, my reasoning now is that the Color Management that you decide to use in Windows, just stops working if you disable FSO. I don't actually care about the full technical explanation of, if it is just because games are actually overriding it, resetting it or what, is just that it introduces weird behavior with Color Management that warrants there being a warning or it being a separate setting altogether.

I also know that when a game says Fullscreen Exclusive, on Windows, it isn't real FSE unless you disable FSO.

I still appreciate the information, but is not a fix or something that is worth replying to a nearly 2 year old issue on imo
