### ISSUE TITLE
Clipboard History Disabled

### ISSUE THREAD

**Issue by remotemango1689** [ChrisTitusTech/winutil#1918]
**Clipboard History Disabled**

**To Reproduce**
1. Enable "Disable Activity History"
2. Clipboard History now disabled under Organization policy as per Windows Settings
3. Tried to check "Disable Activity History" and activated "Undo Selected Tweaks"
4. Still the same.

**Expected behavior**
Clipboard history should be available

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/144886341/f4b192c9-3673-43ab-8374-2a60da70f050)

**Comment by krxvv** [comment]
How to get it back, any workaround? I really need the clipboard history :c

**Comment by krxvv** [comment]
@Obegg Thanks :)

**Comment by remotemango1689** [comment]
> Download O&O Shutup10++ and change it back

I tried using this and it didn't work: https://www.oo-software.com/en/shutup10

The clipboard history still doesn't work.

**Comment by remotemango1689** [comment]
I was able to make it work. For some reason, the software alone does not do the job.

I went to CTT Windows Utility and undo OO Shutup. Then, I performed the necessary tweaks using [oo-shutup10](https://www.oo-software.com/en/shutup10) besides the Clipboard History feature. Now it works just fine.

**Comment by platima** [comment]
Same issue here -_-
