### ISSUE TITLE
WPFTweaksServices

### ISSUE THREAD

**Issue by Obegg** [ChrisTitusTech/winutil#1922]
Why would this tweak needs to change services from original value (example: automatic) to automatic?
So much bloat with those lines
https://github.com/ChrisTitusTech/winutil/blob/2354645b479b9ca7bcf377ea4e199b262f4b6bb4/config/tweaks.json#L117-L1540

Simply do
```powershell
Set-Service AJRouter -StartupType Disabled
Set-Service AssignedAccessManagerSvc -StartupType Disabled
Set-Service CDPSvc -StartupType Manual
Set-Service StorSvc -StartupType Manual
Set-Service UsoSvc -StartupType Manual
Set-Service WpnService -StartupType Manual
Set-Service edgeupdate -StartupType Manual
Set-Service vm3dservice -StartupType Manual
```

**Comment by Marterich** [comment]
The only reason I can think of why there are some services defined where the original and the target Startup Type are the same is, that like this you can be sure that if someone broke some functionality by changing stuff they don't know about, winutil would be able to reset and pretty much fix the problem, but for the sake of bloat I actually wouldn't be against removing the settings that effectively do not get changed from default.

Regarding your recommendation, I did write an answer outlining why it is smart to keep the object structure for registry keys in https://github.com/ChrisTitusTech/winutil/issues/1920#issuecomment-2093437488  This applies as well for services.
