### ISSUE TITLE
End Task Tweak & WinRAR issue on Windows 11 Machine

### ISSUE THREAD

**Issue by OfficialExalted** [ChrisTitusTech/winutil#1936]
**Describe the bug**
The "End Task" on taskbar tweak does appear to work on my system & the WinRAR installation did not appear to work correctly.

**To Reproduce**
Use the tool as expected

**Expected behaviour**
I expected an "End Task" button to appear when right clicking an application from the task bar and also for WinRAR to appear in "installed Apps" or through typing "WinRAR" in the search box in the bottom left.

**Screenshots**
Can provide if needed but is self explanatory via description.

**Additional context**
N/A

**Comment by ModernTTY** [comment]
@OfficialExalted Please you provide the logs.

**Comment by ModernTTY** [comment]
@OfficialExalted The end task via taskbar

**Comment by ModernTTY** [comment]
@OfficialExalted The end task on taskbar got introduced very recently you need to update your computer.
