### ISSUE TITLE
No Support for Windows 10

### ISSUE THREAD

**Issue by Geckoonair** [ChrisTitusTech/winutil#1937]
**Describe the bug**
Windows 10 Search is not working. Not able to type in

**To Reproduce**
Creating an ISO without appx packages with microwin

**Expected behavior**
The search bar should work.

**Screenshots**

**Additional context**
CTF loader and windows search is running in task manager. But I found that I can't click on Indexing Options Control Panel.

**Comment by Geckoonair** [comment]
I found out that creating an iso with microwin is causing this issue. I have created another iso without removing any packages and keeping both edge and defender. Somehow microwin was still able to brick the function.

**Comment by Geckoonair** [comment]
https://www.reddit.com/r/ChrisTitusTech/comments/1bx41wl/used_microwin_with_windows_10_search_doesnt_work/

**Comment by DrasticT** [comment]
Any update?

**Comment by Geckoonair** [comment]
> Any update?

it still dosent work. I think he does not give a shit about it.
