### ISSUE TITLE
Program Requests

### ISSUE THREAD

**Issue by Mrman1093** [ChrisTitusTech/winutil#194]
iTunes, Cider, Joplin, OpenOffice, and Tor Browser

These are a few applications that I use quite frequently and are available through Winget. Their Winget commands are:

winget install --id=Apple.iTunes  -e
winget install --id=CiderCollective.Cider  -e
winget install --id=Joplin.Joplin  -e
winget install --id=Apache.OpenOffice  -e
winget install --id=TorProject.TorBrowser  -e

**Comment by ChrisTitusTech** [comment]
Putting in #250
