### ISSUE TITLE
Old VirtualBox was installed

### ISSUE THREAD

**Issue by thetick1234567890** [ChrisTitusTech/winutil#1950]
**Describe the bug**
Oracle VirtualBox installed old 6.1.30 version and not the latest 7.0.18

**To Reproduce**
1. irm https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1 | iex
2. Pick  Oracle VirtualBox 
3. Click Install/Upgrade Selected

**Expected behavior**
Oracle VirtualBox 7.0.18 installed

**Screenshots**
Not needed

**Additional context**
Manually had to install Oracle VirtualBox  7.0.18 from https://download.virtualbox.org/virtualbox/7.0.18/VirtualBox-7.0.18-162988-Win.exe.  winutil available if requested.

**Comment by Yuuh15** [comment]
Couldn't reproduce, install went successfully here: 
![winget_OLGbOt4sVZ](https://github.com/ChrisTitusTech/winutil/assets/97139700/da751a2d-3dfa-45d6-9575-61a8be2fcd53)

**Comment by blusewill** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/62820836/891e1ef4-626f-48ff-bb9f-c926dcac4909)

Two Things might occur.
Your winget is having some issues that is not grabbing the latest version.
Second is VirtualBox Developer haven't push the update into the winget repo
