### ISSUE TITLE
How can I re-enable the clipboard history feature?

### ISSUE THREAD

**Issue by MCUxDaredevil** [ChrisTitusTech/winutil#1969]
**Describe the bug**
I applied the basic tweaks for laptop, of which one was the activity privacy that disables all kinds of activity history including clipboard history. I want to keep my clipboard history on, so I went and ran the remove tweak option. But now in the settings, it shows that the option is controlled by my organization and so I cannot change it.

**Expected behavior**
Re-enable the clipboard history feature

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/59441946/eb202da3-5e27-4138-9831-c5bc729d9c5a)

**Comment by Marterich** [comment]
Answered in: 
https://github.com/ChrisTitusTech/winutil/issues/1871#issuecomment-2074847855

**Comment by MCUxDaredevil** [comment]
Ohh thanks
