### ISSUE TITLE
Please add shell

### ISSUE THREAD

**Issue by shafschwd** [ChrisTitusTech/winutil#197]
### please add [shell](https://github.com/moudey/Shell)

when i switched to win 11 i hated the context menu then i found this program.
not only it replaces the context menu it also lets you customize the ui and much more.

**Comment by ChrisTitusTech** [comment]
Ok that is a pretty badass tool you found. Will definitely add it.

**Comment by FeedTheChunk** [comment]
It would be nice if there was a tool tip or a link to application page in the Install section.  Searching the web for ambiguous words, such as Shell, Signal, Slack, etc, makes it nearly impossible to determine what the app is / does.
