### ISSUE TITLE
DENY Any Windows attempt on restarting

### ISSUE THREAD

**Issue by ia2115** [ChrisTitusTech/winutil#1970]
I HATE auto restarts, and active hours here can be 24/7, so could be nice to have option to complete deny windows ability to restart.

afaik this can only be done this way:

 1. Press Windows key + R keyboard shortcut to open the Run command.
 2. Type the following path and click "OK":
    %windir%\System32\Tasks\Microsoft\Windows\UpdateOrchestrator
 3. Select the Reboot ) (it does not have an extension)
    file right-click it and select "Rename".
 4. Rename the Reboot file to "Reboot.old".
 5. Right-click inside the folder, select "New," and click on "Folder".
 6. Name the New Folder "Reboot".
 7. Now restart your computer.

i really want this tweak inside winutil also ;)
thanks for great app, love it ..

**Comment by blusewill** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/62820836/019cb4a1-9b65-4d03-af11-8ea937f34df4)

There is no Reboot File? Don't know how to implement this lol

**Comment by ia2115** [comment]
setting anything in windows, will not disable, this is tried. its needed to create a reboot dir inside that %windir%\System32\Tasks\Microsoft\Windows\UpdateOrchestrator
![Uploading featutre.png…]()

**Comment by blusewill** [comment]
So how can I implement this? I still didn't get the idea.

**Comment by ia2115** [comment]
my idea if i could program, check if @reboot is there, if so rename to @reboot.old, create directory "reboot" if none found create the reboot directory, if disabled, just remove the reboot dir, and rename .old to @reboot if found.
