### ISSUE TITLE
winget crashing on windows 10

### ISSUE THREAD

**Issue by harry8227** [ChrisTitusTech/winutil#1972]
**Describe the bug**
==========================================
Error: Program 'winget.exe' failed to run: The process has no package identityAt line:28 char:35
+             $wingetVersionFull = (winget --version) # Full Version wi ...
+                                   ~~~~~~~~~~~~~~~~.
===========================================

**To Reproduce**

simply trying to install it from the Windows ToolBox

**Expected behavior**
I just expect it to load

**Screenshots**

**Additional context**
running rysen 4700, 64 gigs memory 30 TB of drive spave with (Nvidia gtx 1600  super

**Comment by harry8227** [comment]
Everything was fine yesterday, no changes were made to the computer, unless MS messed it up somewhere

**Comment by Marterich** [comment]
Can you please try opening a Powershell/Terminal and run `winget --version` manually and copy the output.
It seems to me, that winget itself might be the problem in your case
