### ISSUE TITLE
Xbox networking still fails the test after "undo all tweaks"

### ISSUE THREAD

**Issue by veritronx** [ChrisTitusTech/winutil#198]
**Describe the bug**
After applying the desktop recommended tweaks Xbox live multiplayer is stuck at "teredo is unable to qualify" and server connectivity is "blocked".. after running "undo all tweaks" and rebooting it's still unable to qualify and blocked. before running the script it was working properly. microsoft's "fix it" function no longer works even after I supposedly undid all the tweaks.

**To Reproduce**
1. run script to get ui
2. Click "tweaks" then "desktop" then " run tweaks" then "ok"
3. reboot
4. check xbox networking connectivity
5. try "fix it" and then "check again", still doesn't pass the test
6. run script to get ui again
7. Click "tweaks" then "undo all tweaks" then "ok"
8. reboot again
9. check xbox networking connectivity again
10. try "fix it" and then "check again", still doesn't pass the test

**Expected behavior**
I expected my xbox networking to be restored and pass the test again after undoing the tweaks and rebooting, possibly requiring "fix it" button to be used

**Additional context**
windows 10 21H2. after a fresh install of windows I have to use "fix it" button once for nat type test to pass on my pc, server connectivity test always passes.. until I applied the desktop recommended tweaks.

**Comment by d0x360** [comment]
Do you happen to use Adguard?

**Comment by ChrisTitusTech** [comment]
I don't change any Teredo settings, but xbox live rely on ipv6 and will need ip helper service. Set that to automatic in `services.msc` 

I'll change the essential tweaks to leave the helper service alone.

**Comment by vozellad** [comment]
I have the same issue when trying to use the Minecraft Launcher. Has this ever been fixed? I need to reinstall the OS to fix it.

**Comment by GabiNun2** [comment]
> I have the same issue when trying to use the Minecraft Launcher. Has this ever been fixed? I need to reinstall the OS to fix it.

dont use the new minecraft launcher use the legacy one https://aka.ms/minecraftClientWindows

**Comment by vozellad** [comment]
This file seems to just install the Minecraft Launcher. I already have it. I am having trouble using the launcher to install Minecraft because the Xbox app doesn't have internet to log in.

**Comment by GabiNun2** [comment]
> This file seems to just install the Minecraft Launcher. I already have it. I am having trouble using the launcher to install Minecraft because the Xbox app doesn't have internet to log in.

if you use the minecraft launcher i linked it will handle it's own xbox sign in without opening the xbox app

**Comment by vozellad** [comment]
The launcher installed successfully. I uninstalled the non-legacy launcher and reinstalled this one. It still says "Unable to update the Minecraft Native Launcher." I have an issue with games that go through the Epic Games software not working either, so I need to reinstall Win11 anyways to remove the main issue.

**Comment by GabiNun2** [comment]
> The launcher installed successfully. I uninstalled the non-legacy launcher and reinstalled this one. It still says "Unable to update the Minecraft Native Launcher." I have an issue with games that go through the Epic Games software not working either, so I need to reinstall Win11 anyways to remove the main issue.

can you screenshot it?

**Comment by vozellad** [comment]
<img width="1062" height="671" alt="Image" src="https://github.com/user-attachments/assets/d6efbd5c-ed28-40dc-bfe5-79907d04a7cf" />
Like this?

**Comment by GabiNun2** [comment]
> <img alt="Image" width="1062" height="671" src="https://private-user-images.githubusercontent.com/57552104/580961727-d6efbd5c-ed28-40dc-bfe5-79907d04a7cf.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY3MTA1NjksIm5iZiI6MTc3NjcxMDI2OSwicGF0aCI6Ii81NzU1MjEwNC81ODA5NjE3MjctZDZlZmJkNWMtZWQyOC00MGRjLWJmZTUtNzk5MDdkMDRhN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDIwVDE4Mzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDRjMDBiMzI2OWYxZjk4NzI0YTNiM2U4YTg3OTBlZGJmY2E1YjViOTYyZmNhMGNjN2I1ZjcyNzVjOTc0NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.U_DTXdI9IewuzNeg1TGoMj7cNRgiBXHwC_b9yeKQ5JE"> Like this?

try uninstalling both of them and install the legacy launcher
