### ISSUE TITLE
Add PowerISO to the list of utilities

### ISSUE THREAD

**Issue by B1GBOOM420** [ChrisTitusTech/winutil#1984]
Its not really an issue at all - it is just something that is installed since a lot of newer units do not have disc drives.

I love this repo, and am always happy to try and provide decent ideas for what _could_ be an option

best regards

**Comment by blusewill** [comment]
Why don't use the mount feature already integrated in Windows?

**Comment by B1GBOOM420** [comment]
ngl I did not know I had an option for that, I will look into that - Thank you so much!
