### ISSUE TITLE
not installing winget, scoop and chocolatey upon start

### ISSUE THREAD

**Issue by mizu-048** [ChrisTitusTech/winutil#1987]
**Description**
this is more of a question than a request. 

So is it really necessary to install all three package managers on startup?
and why all three? why not just one or two?
shouldn't the package managers only be needed to install the software? they are basically useless for anyone who just wants tweaks

**Solution I would like**
Maybe ask upon startup if we want to install x package manager(s)? 
or just install them first, when an application has been requested to be installed?

and on the startup explain that they/it will be automatically installed when you choose to install a software

**Comment by blusewill** [comment]
Fixed in PR #1943 
But haven't merge into the main branch

**Comment by mizu-048** [comment]
thanks and i must have related choco to scoop somewhere as they are often compared
