### ISSUE TITLE
brave icon not showing on taskbar

### ISSUE THREAD

**Issue by samueltre2** [ChrisTitusTech/winutil#1999]
![Sem título](https://github.com/ChrisTitusTech/winutil/assets/170678288/25e38446-8fe7-472b-8f43-14ea64703f83)
brave icon black on taskbar

**Comment by blusewill** [comment]
You can pin it. Manually I think?

**Comment by samueltre2** [comment]
when i install brave from the website it dosen't happen

**Comment by Marterich** [comment]
Still a Brave issue. 

Winutil uses Winget (Microsoft CLI Tool) to install Programs. 
Winget in turn uses the manifests from https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/Brave to install the program silently. If there is a problem with the silent, Commandline install of Brave this can only be solved by either Brave fixing their installer or by someone fixing the install manifest in the Microsoft Github Repo, so there's nothing that winutil can really do here.

**Comment by samueltre2** [comment]
ok thanks
