### ISSUE TITLE
Power Throttling doesn't turn back on

### ISSUE THREAD

**Issue by leonn22** [ChrisTitusTech/winutil#2]
**Describe the bug**
Cannot find path ??

**To Reproduce**
1. run `iwr -useb https://t.co/7wU8SkpUXY | iex` on elevated prompt
2. Checked  Enable Power Throttling on..
3. See error..
```
Set-ItemProperty : Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling' because it does not
exist.
At line:1039 char:9
+         Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Contro ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\SYSTEM\Cu...PowerThrottling:String) [Set-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand

```

**Expected behavior**
Turn PowerThrottling on.

**Screenshots**
Registry Editor
<img src="https://files.catbox.moe/7gmnhl.png"
     alt="Registry Editor Screenshot"
     style="float: left; margin-right: 50px;" />

**Additional context**
- I used your old utility a few months back
-  sometimes i run [wise registry cleaner](https://www.wisecleaner.com/wise-registry-cleaner.html) first used it to remove [WPS Office](https://www.wps.com/)
- On a Laptop running Windows 10 21H1

**Comment by Carterpersall** [comment]
It seems that the issue is that the PowerThrottling registry directory does not exist in a default install.

The solution would be to add an if-statement before the line that errors that checks for the PowerThrottling registry directory and creates it if missing.

**Comment by leonn22** [comment]
i fixed mine by mannually adding it to the registry.
