### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Aman1337g** [ChrisTitusTech/winutil#200]
Hello,
I have programs that I would like to have on the Install section, please:
Only Office, NextDns, tor browser, [O&O ShutUp10++](https://www.oo-software.com/en/shutup10) and [O&O AppBuster](https://www.oo-software.com/en/ooappbuster) for debloating windows in the installs section.

**Comment by ChrisTitusTech** [comment]
This uses o and o shutup 10 at the start of essential tweaks. 

The rest of the software might get added in the future.
