### ISSUE TITLE
MicroWin error

### ISSUE THREAD

**Issue by hpsxrb** [ChrisTitusTech/winutil#2001]
File path G:\SOFTW PROGRAMS\OS Images\Win11_23H2_English_x64v2.iso 

Could not remove OS package Package_for_RollupFix~31bf3856ad364e35~amd64~~22621.2861.1.6
Invoke-WPFMicrowin : An unexpected error occurred: Removal failed. Please contact your software vendor.
At line:2805 char:24
+         "WPFMicrowin" {Invoke-WPFMicrowin}
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin

Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.

**Comment by dehylton** [comment]
Are you also attempting to inject drivers? If so, which? I see this also when attempting to inject the latest virtio drivers to the latest win11 iso.

**Comment by hpsxrb** [comment]
I haven't tried to inject any drivers.
The options were: no Provisioned packages, no Appx packages, no Defender, no Edge.
Thank you very much for your interest.

**Comment by KonTy** [comment]
@hpsxrb does it still create an image? The errors you listed above are not crytical and can be ignored. See Microsoft is adding more and more packages that can't be deleted and keeping up with them is a tough task. As long as your image was generated you are good.

**Comment by hpsxrb** [comment]
Yes, it always creates the iso. 
I tried with keep Defender and keep Edge and it ended without errors.
Thank you for your interest.

**Comment by Doraemon309** [comment]
> Yes, it always creates the iso. I tried with keep Defender and keep Edge and it ended without errors. Thank you for your interest.

It's a shame that we can't get rid of both defender and edge packages without errors?

**Comment by kcking098** [comment]
> Yes, it always creates the iso. 
> 
> I tried with keep Defender and keep Edge and it ended without errors.
> 
> Thank you for your interest.

I tried with just defender and I got no errors

**Comment by hpsxrb** [comment]
> > Yes, it always creates the iso.
> > I tried with keep Defender and keep Edge and it ended without errors.
> > Thank you for your interest.
> 
> I tried with just defender and I got no errors

Thank you very much. You're absolutely right, I just tried defending and it ended without error.

**Comment by Doraemon309** [comment]
> > > Yes, it always creates the iso.
> > > I tried with keep Defender and keep Edge and it ended without errors.
> > > Thank you for your interest.
> > 
> > 
> > I tried with just defender and I got no errors
> 
> Thank you very much. You're absolutely right, I just tried with defender and it ended without errors.

I tried building on revios and everything works fine! You can test that! I tried rebuilding the iso on Microsoft's original windows and failed like you and succeeded in rebuilding on Revios!

**Comment by hpsxrb** [comment]
Thank you.


------ Mensagem original ------
De "Doraemon309" ***@***.***>
Para "ChrisTitusTech/winutil" ***@***.***>
Cc "hpsxrb" ***@***.***>; "Mention" ***@***.***>
Data 30/05/2024 02:38:01
Assunto Re: [ChrisTitusTech/winutil] MicroWin error (Issue #2001)

**Comment by CodingWonders** [comment]
A try-catch block has been added with #2192, which may fix this issue

**Comment by hpsxrb** [comment]
Thank you very much @CodingWonders.
I can testify that it no longer gives the previous errors.

**Comment by CodingWonders** [comment]
@hpsxrb, I did a test run using those options and found no problems

**Comment by hpsxrb** [comment]
Thank you very much @CodingWonders.
I repeated the process (without Edge and without Defender) and this time I didn't have any errors!

**Comment by Real-MullaC** [comment]
@hpsxrb Please could you close this Issue if the issue is fixed.
