### ISSUE TITLE
Add an option to disable the new Copilot Recall feature (You made a video on this yourself, its basically Spyware).

### ISSUE THREAD

**Issue by MagmaBro123** [ChrisTitusTech/winutil#2002]
**Is your feature request related to a problem? Please describe.**
Microsoft is being dumb. Simple as that, lol.

**Describe the solution you'd like**
Remove the Recall Copilot feature. (Again, basically spyware.)

This may be possible by doing these steps
![image](https://github.com/ChrisTitusTech/winutil/assets/51277766/c37f99bb-f33a-4d2b-83b3-390cd8d3f609)
but there's probably a way of fully removing Copilot in some other way.

**Describe alternatives you've considered**
N/A?

**Additional context**
N/A.

**Comment by sigma2017** [comment]
Windows can not be used anymore having this crap enabled. This is mandatory!

**Comment by 4yman-el** [comment]
The issue is now fixed in [Tweaks page overhaul](https://github.com/ChrisTitusTech/winutil/pull/2003). Is there anything else to solve?

**Comment by MagmaBro123** [comment]
> The issue is now fixed in [Tweaks page overhaul](https://github.com/ChrisTitusTech/winutil/pull/2003). Is there anything else to solve?

It appears that this, Edge, and OneDrive aren't fully removed.
https://github.com/ChrisTitusTech/winutil/issues/2089

**Comment by MagmaBro123** [comment]
Ugh.
