### ISSUE TITLE
Can't access Startup Menu

### ISSUE THREAD

**Issue by Sanified** [ChrisTitusTech/winutil#2005]
I ran the tweak script as usual, however, I noticed that the Startup Menu is nowhere to be seen, and changing things in Task Manager doesn't work.

![image](https://github.com/ChrisTitusTech/winutil/assets/125764224/6e98dcf9-0266-49a2-853e-9e795285eff0)

Does anyone have any solutions?

**Comment by blusewill** [comment]
Have you run any tweaks or it's just Explorer Crashing?

If not. Please try repair the operating system.

**Comment by Sanified** [comment]
I ran the powershell script with the laptop preset a while ago, ever since my clipboard history and startup menu disappeared. I'll repair windows to see if it fixes anything, I've seen someone else report the issue here but I haven't seen a concrete solution.

**Comment by blusewill** [comment]
What version of Windows you are running on? Ex: 21H2
Sometimes that will occur?

**Comment by Sanified** [comment]
I ran a repair and all worked out well, thank you very much!
