### ISSUE TITLE
Enable Power Throttling tweak not working.

### ISSUE THREAD

**Issue by Nishant561994** [ChrisTitusTech/winutil#201]
I have Win 11 Home Basic Intel core i3. Security was disabled. Does Power throttling works on all cpu's? 

![Untitled 2](https://user-images.githubusercontent.com/113617198/192594746-d11fc0dc-aaa4-40b2-a463-cd93325256f5.png)

Only msedgewebview2.exe is Enabled. 

![Untitled](https://user-images.githubusercontent.com/113617198/192588535-c7387ade-b639-44e4-904e-8d187f6a8eb3.png)

**Comment by ChrisTitusTech** [comment]
Power Throttling is a laptop feature and really should only be used to help conserve battery.

**Comment by 101lols** [comment]
I'm on a laptop, and the power throttling tweak doesn't seem to be working.
