### ISSUE TITLE
unable to re-enable clipboard history 

### ISSUE THREAD

**Issue by freaked1234** [ChrisTitusTech/winutil#2012]
Hey!
First off, I really love your tool and it is great help setting up new installs.
On one of my Win11 pro installs I have an issue though I can't seem to fix myself:
On accident I disabled clipboard history and even after undoing the corresponding changes in the tool it won't work.
I tried adding the registry keys manually but no success either. When trying to enable it via windows settings it says "this setting is not available because of your organisations guidelines", even though this machine is not part of an Organisation.
Any help would be appreciated!

**Comment by og-mrk** [comment]
@freaked1234 
This has been answered in [this comment](https://github.com/ChrisTitusTech/winutil/issues/1871#issuecomment-2074847855).

which is done by undoing the **OO Shutup tweak** and restarting, then going into the settings app to re-enable the Clipboard History feature (if it hasn't been enabled).

**_Or_** by clicking **OO Shutup advanced tweak** button, where WinUtil will launch the GUI of OO Shutup so you can enable Clipboard History for _both_ the current user and the machine (all users),  exit out of OO Shutup and WinUtil and restart your computer, then it should work just fine 👍

**Comment by freaked1234** [comment]
@og-mrk 
ofc this is the typical answer of people who dont want to admit fault but I tried that before in all honesty and it did not work. 
Somehow I just applied what you suggested, rebooted and the setting did not apply. Doing it again finally worked. 
Thank you very much for taking the time!

**Comment by og-mrk** [comment]
I'm glad this fix worked for you @freaked1234 😄

it's for now a temporary one. This issue shouldn't typically happen.. or at least inform the user of what to expect after applying OO Shutup tweak, so they (the user) don't get surprised by certain features of windows not working anymore.

@freaked1234, If you have any more questions in mind, feel free to post them here, and if you don't have any, then make sure to close this issue as completed, thanks in advance 😄
