### ISSUE TITLE
program addition requests + SYSMAIN

### ISSUE THREAD

**Issue by n8spl8** [ChrisTitusTech/winutil#2015]
A Sysmain toggle would be cool.

And:

A few useful things: None of these are trial ware but may ask for donation  when first run.

    Wise Program Uninstaller (WiseCleaner.WiseProgramUninstaller, no choco)
https://www.wisecleaner.com/wise-program-uninstaller.html
    

Not as many tools as Revo, BUT, it will uninstall EDGE and COPILOT regardless of installation state.

    Joytokey (JTKsoftware.JoyToKey, joytokey)
https://joytokey.net/en/download
  

Very handy for mapping any controller/joystick

These next two aren't in winget, etc. BUT are so useful.

    MSI_util_v3
   https://www.mediafire.com/file/ewpy1p0rr132thk/MSI_util_v3.zip/file
    havn't tried the github file:
  https://github.com/Sathango/Msi-Utility-v3/blob/main/Msi%20Utility%20v3.exe

This is a clean MSI mode utility that allows the user to change IRQ/MSI and affinity states.

    InSpectre
    
https://www.grc.com/inspectre.htm
This tool checks for spectre/meltdown unicode status and will allow for disabling/enabling these for extra performance especially on older PCs.

These would be great tools to have available as a 'configure' or 'tweak'???

Thanks for all you do.

I would just make a pull request but have never done said and wasn't sure how Id go about asking about the last 2 requests.

**Comment by og-mrk** [comment]
@n8spl8 I've made a PR ([link to it](https://github.com/ChrisTitusTech/winutil/pull/2069)) that adds two of your request (`Wise Program Uninstaller` and `JoyToKey` Programs to be exact), the other two (`MSI Util v3` and `InSpectre`) are sadly un-available in the winget packages repo, nor it's available in choco community packages, so I could add it to the list, plus the fact that one of these two programs (`MSI Util v3`) is shared via un-trust worthy ways, _**even if**_ the binary is 100% legit and safe, the fact it's shared via File Sharing service (like MediaFire) and also in a "random GitHub Repo" by someone on the internet.. not to mention there's no Source Code to speak of.. all of these are red flags that makes the accepting of such addition _really_ difficult.

I hope you can understand the concerns above, and if the software suggestions/requests are from Trust Worthy sources, _and even better_, completely Free & Open Source, then the chances of accepting it into WinUtil's List of applications is much higher then other wise.. with that being said, the two apps I've added in that PR might not get accepted for one reason or another, with that being said, there're always other ways to install the apps you want on your system(s), like using WinGet (or any other Package Manager) to easily install programs not found in WinUtil 😄
