### ISSUE TITLE
Auto Update feature for Pip and Auto pull for Git + windows update (if required not neccesary)

### ISSUE THREAD

**Issue by TheGamingWinner** [ChrisTitusTech/winutil#2016]
A cool and simple addition to winutil could be a Script which auto pulls any git update and auto update Pip or Npm packages

To implement this feature, we could use a simple add-on to the already existing Upgrade-all function in winutil and add git and pip to it.

I am not able to find any good alternative to this specially for git because you have to go in the specific directory and do ```git fetch &  git pull ``` from it instead winutil could have a feature that auto pull any changes made to the repos.

same goes for pip i have a simple script that can be implemented for winutil.

also i have same script which could be used for linutil.

**Comment by TheGamingWinner** [comment]
Hey @ChrisTitusTech , I also want to know if you want to have reference script like these (that run off other repos) or do you want to include the scripts with the project, It self

**Comment by Real-MullaC** [comment]
Hello @TheGamingWinner,

We won't add this currently as it will be to much work to implament and maintain over the long run. I am sorry if this is not what you wanted to hear.

Due to this could you please close this issue.

**Comment by TheGamingWinner** [comment]
Hey @ChrisTitusTech , I also want to know if you want to have reference script like these (that run off other repos) or do you want to include the scripts with the project, It self

**Comment by TheGamingWinner** [comment]
You are right although, I am thinking to create a pull request based on that i have a script which does all that just need some speed improvement then i will give a implementation of that script, as a developer i do think this kind of feature will help a lot of developers 

if you want to check my under development script you can look at this repo 
https://github.com/thegamingwinner/update_script

as soon as i figure out a way to increase it's search speed it will work preaty good
