### ISSUE TITLE
Huge GPU utilization 

### ISSUE THREAD

**Issue by monoterne** [ChrisTitusTech/winutil#2023]
**Describe the bug**
Huge GPU utilization for no reason.

**Screenshots**
[Task Manager](https://i.imgur.com/oSAEGnz.png)

**Additional context**
It's on integrated graphics on a laptop, but, as you see, my browser is taking less while playing YouTube. 

I don't know if is it possible to do anything regarding UI performance optimization on PowerShell, but here is the fact. :D

**Comment by v-Kaefer** [comment]
Is that a spike when launching, loading the interface or downloading?
Or is it persistant, it stays like that while the interface is open?

**Comment by blusewill** [comment]
What is your integrated GPU called.
It's probably not on the whitelist of optimization script

**Comment by monoterne** [comment]
> Is that a spike when launching, loading the interface or downloading? Or is it persistant, it stays like that while the interface is open?

persistant

**Comment by monoterne** [comment]
> What is your integrated GPU called. It's probably not on the whitelist of optimization script
> 
> Yes, we use list of integrated GPU to launch into optimized mode (X

It's an integrated GPU into AMD Ryzen 5 5600H

**Comment by Marterich** [comment]
@monoterne 
Could you please run the following Command in a Powershell Window and post the output so the appropriate mapping can be added :) 
`(Get-CimInstance Win32_VideoController).Name`

**Comment by monoterne** [comment]
> @monoterne Could you please run the following Command in a Powershell Window and post the output so the appropriate mapping can be added :) `(Get-CimInstance Win32_VideoController).Name`

![image](https://github.com/ChrisTitusTech/winutil/assets/85072834/253da693-b741-4cb3-bbbb-4f9a203259d9)

**Comment by blusewill** [comment]
Alright. The problem is it detected the 3050 Ti and decided to launch in the Matrix Mode.
