### ISSUE TITLE
Issue with clipboard history

### ISSUE THREAD

**Issue by Chappycpuequalszero** [ChrisTitusTech/winutil#2027]
**Describe the bug**
When using tweaks to disable Essential Tweaks even if I don't select it, it sometimes just disables clipboard history and if I try to undo the tweak it doesn't do anything. Windows settings just says "This setting is managed by your organization" 

**To Reproduce**
1. Go to 'Tweaks'
2. Click on 'Disable activity history'
3. Click on 'Undo Selected tweaks'
4. Check if it did anything.

**Expected behavior**
I expect it to allow activity history but it doesn't seem to change any of the settings surrounding it especially not clipboard history.

**Screenshots**
<img width="796" alt="ErROR" src="https://github.com/ChrisTitusTech/winutil/assets/64427403/c95b02a2-8b52-474c-bc7a-e6360f81f438">

**Additional context**
I have no organization or other setting management software (Besides this one)

**Comment by Marterich** [comment]
This has been answered in https://github.com/ChrisTitusTech/winutil/issues/1871#issuecomment-2074847855.
