### ISSUE TITLE
Crashing My GPU

### ISSUE THREAD

**Issue by Aashu9912** [ChrisTitusTech/winutil#2029]
I started using Wiuntil like 10 days ago and now all of a sudden my GPU drivers keeps disabling and going back to Microsoft driver which is very annoying as soon as i start playing game it just crashes.
i tried benchmarking for 10 mins not crashed as soon as i play game it crashed.
before using WinUtil everything was fine how do i revert back to the original settings.
thank you

**Comment by Marterich** [comment]
Without knowing what exactly you did or why this could be happening, a first good step to reset any changes by winutil would be to select all tweaks and then clicking the undo button.
