### ISSUE TITLE
WingetUI (with Scoop) to avoid infinite app request

### ISSUE THREAD

**Issue by ianalexis** [ChrisTitusTech/winutil#203]
One of the most requested thing in WinUtil are apps but i think one inclusion could get all happy.

https://github.com/martinet101/WingetUI and https://github.com/ScoopInstaller/scoopinstaller.github.io

Its a really good WinGet GUI with Scoop (maybe chocolatey in the future) support to add even more package options.
When i first install any Windows i run WinUtil and add WingetUI to add any app required.
Been included in WinUtil makes even easier any setup.

**Comment by ChrisTitusTech** [comment]
I dig it! Might take some inspiration from this. I always liked scoop a bit better than choco anyhow. 

For now I'm going to stick with winget since it comes baked in to win11.

**Comment by ianalexis** [comment]
My point was to add the WingetUI app in WinUtil because it helps to install any Winget package and even scoop ones. 
Thanks
