### ISSUE TITLE
MicroWin image will fail with old PowerShell version

### ISSUE THREAD

**Issue by Connexiumlabs** [ChrisTitusTech/winutil#2034]
**Describe the bug**
The MicroWin ISO creation process will never be complete and will crash when running on an older Powershell version.

I am in no way a Powershell or CLI expert (or even a novice). But MicroWin would always crash until I realized that I was running the "default" Powershell version that comes with Windows, not the new installed one.

I would suggest we add some version checks in the script to ensure a compatible version of Powershell is being used.

Thank you for your great work!

**Comment by Traudien415** [comment]
Thanks @Connexiumlabs I was stuck rerunning over and over until I found this.
