### ISSUE TITLE
Add an option to hide the Recommended section in the Start menu.

### ISSUE THREAD

**Issue by MagmaBro123** [ChrisTitusTech/winutil#2037]
**Is your feature request related to a problem? Please describe.**
Title. Windows shouldn't be recommending stuff. It's annoying IMO.

**Describe the solution you'd like**
Title. All the Start menu replacements I know of (Start11, StartAllBack, etc.) are all paid, a Start menu that isn't recommending stuff would be nice.

**Describe alternatives you've considered**
N/A.
 
**Additional context**
N/A.

**Comment by MagmaBro123** [comment]
Ugh...

**Comment by Real-MullaC** [comment]
@MagmaBro123 It sadly isn't one "simple thing". If you have the Windows Education edition (SE) you can follow [this](https://www.thewindowsclub.com/remove-recommended-section-from-start-menu-in-windows) article.
If not and you prefer not to use a 3rd party application, you are most likely out of luck...

**Comment by Real-MullaC** [comment]
If this helps please close this issue.
