### ISSUE TITLE
Winget Auto Install

### ISSUE THREAD

**Issue by SquareOwl** [ChrisTitusTech/winutil#2039]
**Describe the bug**
Winget gets installed automatically. Its considered a bug not a feature as its impossible to remove/uninstall

**To Reproduce**
Run the latest version of winutil

**Expected behavior**
Only portable chocolaty gets installed. (It can be removed very easily by deleting the file). Ask user if they want to install winget (yes/no)

**Screenshots**
N/A

**Additional context**
Users should be made aware before software gets auto installed and should be able to choose whether they want to install or not. This tool gets used by a very diverse group of users with different needs and perhaps it shouldn't force install software with out user consent.

**Comment by ModernTTY** [comment]
@SquareOwl WinGet is completely critical to the function of Winutil specifically the app installation. And you should be able to uninstall it from the MS store.

**Comment by SquareOwl** [comment]
I setup clean and locked down enterprise systems without MS store (Windows LTSC). Winget doesn't even work on Windows LTSC. Its considered bloat. I use winutil to automate part of system deployment. All I request is for the tool to ask before installing winget. Allows users to choose.

**Comment by Marterich** [comment]
I'm torn about this request.
On the one hand, I can see the reason behind wanting a lean and simple tool to apply some tweaks without the _bloat_ of additional software installation, on the other hand, winutil is based quite heavily on winget and only uses chocolatey in some quite specific situations as a Fallback. To be able to let the user chose the package manager, quite a lot of work would need to be done to make sure that no function relies on it.

The only other way I can think of would be, to check if it would be possible to create a version of winget that completely removes the app install feature (which would also require quite a lot of work)

Keeping this in mind, maybe winutil simply isn't the right tool for your use case. 
Have you taken a look at the following GitHub project.
Maybe this could fit your use case better :)
https://github.com/farag2/Sophia-Script-for-Windows
