### ISSUE TITLE
Feature Request: Allow you to install Glary Utilities and Opera GX

### ISSUE THREAD

**Issue by ChivalKnight** [ChrisTitusTech/winutil#204]
Glary Utilities is a useful tool (similar to CCleaner) that allows you to clean your disk, repair your registry, fix shortcuts, uninstall programs, manage startup programs, analyze disk space, run the SFC command, make backups, optimize memory, securely delete files, and more. 

Opera GX is a browser that has a very clean UI and some very useful time saving and battery saving features. It also has a nice ad and tracker blocker, like Brave does. I mostly use it when Brave refuses to work.

**Comment by Redo11** [comment]
Disagree. Glary and CCleaner are both proprietary and untrustworthy. You can clean all of that with alternative software already in the tool.
Opera GX however may be a good idea, as it seems a lot of people use it, tho it is still kinda weird.

**Comment by ChrisTitusTech** [comment]
I absolutely hate Opera as a company and refuse to put any of their products in. Glary is fine, even though I don't use any of those tools.
