### ISSUE TITLE
Big search box in task bar keeps appearing when running tweaks

### ISSUE THREAD

**Issue by jonesy-b-dev** [ChrisTitusTech/winutil#2047]
**Describe the bug**
I have the big search box in the task always set to always hide but when I run the tweaks (always run standard profile) the big search bar appears again and is really annoying. winutil shouldnt be changing this setting

**To Reproduce**
1. Run the OO Shutup tweak

**Expected behavior**
Taskbar search box setting should be preserved and kept on the same setting as it was.

**Comment by 4yman-el** [comment]
What version of Windows are you using?

**Comment by p0ll3** [comment]
Just Experienced the same issue. 
Windows 10 Pro 22H2

**Comment by jonesy-b-dev** [comment]
> What version of Windows are you using?

Windows 11 23h1 I belive , I'll get my exact version tomorrow

**Comment by 4yman-el** [comment]
I found a setting in OOSU10 called "Disable search box in task bar" turned OFF in the OOSU configuration file that the script uses. You can run OOSU yourself and change it.

**Comment by 4yman-el** [comment]
OOShutUp enables the search bar, not winutil itself.

**Comment by p0ll3** [comment]
> > winutil shouldnt be changing this setting
> 
> OOShutUp enables the search bar, not winutil itself.

If I apply the default ooshutup settings with the ooshutup program, it does not enable the Searchbar. 

Running the ooshutup settings via winutil does.

**Comment by 4yman-el** [comment]
>If I apply the default ooshutup settings with the ooshutup program, it does not enable the Searchbar.

My copy of OOSU has "disable search box" set to "limited". if you configure it yourself without a config file, it will import settings from Windows but if you only apply recommended settings it enables the search box.

>Running the ooshutup settings via winutil does.

Yes, OOSU overwrites all settings when run with a config file.

**Comment by jonesy-b-dev** [comment]
How do i edit the OOSU?

**Comment by 4yman-el** [comment]
It's inside [winutil.ps1](https://github.com/ChrisTitusTech/winutil/blob/2b80e14bf954e2cba07903e0c6822677fb97c3d9/winutil.ps1#L11927) and [ooshutup10_recommended.cfg](https://github.com/ChrisTitusTech/winutil/blob/main/config/ooshutup10_recommended.cfg)

**Comment by 4yman-el** [comment]
Here is a config file that include only recommended settings and remove the search bar: [ooshutup10.cfg](https://github.com/user-attachments/files/15791575/ooshutup10.cfg.txt)

**Comment by Marterich** [comment]
> Here is a config file that include only recommended settings and remove the search bar: [ooshutup10.cfg.txt](https://github.com/user-attachments/files/15791621/ooshutup10.cfg)
> 

There is actually a reason behind the madness of including a _unmodified_ version of the **recommended** changes of OO in winutil. 

Let me explain, 
Seeing that OO-Software maintains and updates the recommendations constantly, it becomes quite cumbersome to keep up with manually updating the file and modifying some settings to differ from the oo recommendations. This was the reason why we opted to include a simple, unmodified version of the recommended tweaks that can be simply replaced each time a new version is released. If you want to change the default settings that get applied by OO Shutup, there's still the Button under advanced tweaks that let you chose to modify any OO tweak manually
