### ISSUE TITLE
Arc Browser failed to install 

### ISSUE THREAD

**Issue by trenton4k** [ChrisTitusTech/winutil#2048]
**Describe the bug**

**To Reproduce**
install Arc Browser

**Expected behavior**

**Screenshots**
![Screenshot 2024-06-07 220133](https://github.com/ChrisTitusTech/winutil/assets/23434931/c7bade82-b06b-45c4-9ad2-9c045e703267)

No suitable installer found for manifest: Microsoft.WindowsAppRuntime.1.5 version 1.5.3

**Comment by MyDrift-user** [comment]
The first error seems to be from the installation of the dependency (Windows App Runtime 1.5).
I cant reproduce the error neither on win11 nor on win10. Therefore i think it has something to do with the package itself.

Try instaling the listed dependency manually and then installing arc with following commands & order in powershell:

Dependency 1:
`winget install Microsoft.VCLibs.Desktop.14`
Dependency 2:
`winget install Microsoft.WindowsAppRuntime.1.5`
Application:
`winget install TheBrowserCompany.Arc`

**Comment by blusewill** [comment]
This should be the Arc Browser lack of setting dependency on the winget side
