### ISSUE TITLE
micro win scratch in temp

### ISSUE THREAD

**Issue by sw15621hhhh** [ChrisTitusTech/winutil#2049]
I cannot delete the microwinscratch folder in temp that is over 11 GB, because I have no access even on admin
![obraz](https://github.com/ChrisTitusTech/winutil/assets/172050653/b6f01b2e-ba41-491e-9c26-984731ac0dcc)
![obraz](https://github.com/ChrisTitusTech/winutil/assets/172050653/494e8e4a-25f4-4077-8aab-ae85cd4b5dea)
"Odmowa dostępu" - access denied

**Comment by CodingWonders** [comment]
You have an image mounted on that folder. Run this command as an administrator and try again:

`dism /unmount-image /mountdir="<directory>" /discard`

**Comment by sw15621hhhh** [comment]
i fixed it changing the owner of all folders and then giving admin account all power to the folder

**Comment by ham1tcagdas** [comment]
Magically, file in it disappeared @CodingWonders

**Comment by themooleman** [comment]
> You have an image mounted on that folder. Run this command as an administrator and try again:
> 
> `dism /unmount-image /mountdir="<directory>" /discard`

Thank you!
