### ISSUE TITLE
How do i uninstall the app

### ISSUE THREAD

**Issue by Coder-bots** [ChrisTitusTech/winutil#2059]
i would like to uninstall the app after i used creating it by powershell

**Comment by MagmaBro123** [comment]
The app isn't installed. It's all ran from this GitHub.

**Comment by KonTy** [comment]
> i would like to uninstall the app after i used creating it by powershell

Which app are you tlaking about? If it is winutil, @MagmaBro123  is correct, once you close winutil it goes poof, it is not installed. If you are talking about other apps that winutil installs. You can check an app that you want to uninstall and click uninstall button.

<img width="709" alt="image" src="https://github.com/ChrisTitusTech/winutil/assets/9524513/7bb13212-6397-47d2-b68b-1c3da2e6da1c">

**Comment by seba2282** [comment]
Back up app, get started (windows 11), widgets (windows 11) 
Something can remove that 3 bloatware without destroy system?

**Comment by og-mrk** [comment]
By looking at the conversation for this issue ticket, there hasn't been any info provided by the Author of the Issue for some time now.. and the best answer is provided in @KonTy 's [Comment](https://github.com/ChrisTitusTech/winutil/issues/2059#issuecomment-2159568738), therefore I'll be closing this issue...

/close
