### ISSUE TITLE
Idea Proposal: Have multiple endpoints (Routes) to get WinUtil from 'christitus.com' website

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#2060]
### The Main Idea "in a nutshell"

The idea this issue ticket is proposing is to have multiple routes in `Christitus.com` website, where `christitus.com/win` will be pointing to the latest GitHub release, and (for example) `christitus.com/windev` points to the latest `winutil.ps1` over on the main branch (what it's currently at with `/win` route).

### But why we might need this? (Justifying the added complexity)

This will introduce two lanes for users to choose from, a Stable branch (`/win`), which's based on the GitHub releases as explained previously, and a Test/Dev branch (`/windev`), allow for users (testers and contributors) to see the new changes and report back bugs and even provide ideas before releasing the changes in the next monthly release cycle.

This would add two major benefits:

1. weird and un-expected behaviors _should hopefully_ be caught soon with the help of other contributors and testers.
2. adds a Stable and "Bleeding-Edge" release model, which come with its ups and downs.

### The technical difficult(ies) we might face _**while**_ implementing this, if it gets accepted

The main one I've noticed (and have been thinking about) is **How do we point to the Latest GitHub release/tag?** surely it isn't as easy as replacing the version number (the release title, or git tag) to be `latest`.. and indeed it isn't this simple, although I've been stuck trying to figure out a simple system which will make this possible.. I couldn't come up with a good solution. I know I'm not the first person to ever encounter such problem, but I would like it be as simple as possible, like the principle/idea of `KISS` (an acronym for "Keep it simple, stupid!").

With that being said, any suggestions are welcomed, and give it a 👍 if you like the idea, that would be much appreciated 😄.

**Comment by Marterich** [comment]
First of all, love the Idea of providing an easy way to use the dev/testing branch. 

My proposal (thanks to ChatGPT) for how to overcome the changing release titles would be adding an action to compile pre-release versions like Microsoft does for winget (used in the example). This way @ChrisTitusTech could host the following page on his webserver to automatically redirect to the latest pre-release version.

```html
<!DOCTYPE html>
<html>
<head>
    <script>
        // Function to fetch the latest release tag from the GitHub API
        async function getLatestRelease() {
            try {
                const response = await fetch('https://api.github.com/repos/Microsoft/winget-cli/releases');
                const releases = await response.json();
                const preRelease = releases.find(release => release.prerelease);
                return preRelease.tag_name;
            } catch (error) {
                console.error('Error fetching release data:', error);
                return null;
            }
        }

        // Function to redirect to the latest pre-release version
        async function redirectToLatestPreRelease() {
            const latestRelease = await getLatestRelease();
            if (latestRelease) {
                const url = `https://raw.githubusercontent.com/microsoft/winget-cli/${latestRelease}/NOTICE`;
                window.location.href = url;
            } else {
                console.error('Unable to determine latest pre-release version.');
            }
        }

        // Call the redirect function when the page loads
        window.onload = redirectToLatestPreRelease;
    </script>
</head>
<body>
    Redirecting to the latest pre-release version...
</body>
</html>
```

**Comment by Marterich** [comment]
Also taking the new changes regarding contributions and merging directly to the main branch into account, https://christitus.com/win should probably be referencing the winutil file from the latest release and not the winutil file directly in the repo as this will be the actual "stable" release version in the future.

**Comment by og-mrk** [comment]
I'm adding this comment so GitHub Actions doesn't close this issue... please ignore it.
