### ISSUE TITLE
FreeFileSync does not install with Winutil Version 24.06.11

### ISSUE THREAD

**Issue by 0-dot** [ChrisTitusTech/winutil#2066]
**Describe the bug**
FreeFileSync does not install with Winutil Version 24.06.11

**To Reproduce**
1. Open Winutil terminal as Administrator (irm https://christitus.com/win | iex)
2. Check FreeFileSync in Install > Utilities
3. Click on Install/Upgrade Selected
4. See error in attached screenshot

**Screenshots**
Screenshots with error message is attached.
![2024-06-11-347](https://github.com/ChrisTitusTech/winutil/assets/80411374/e3fe5ece-38ed-46f8-b029-4fe029fe95c4)

**Comment by Marterich** [comment]
Chocolatey Flagged this app as a Virus. The Package will be removed from winutil and (potentially) can later be readded if it turns out to be a False Positive
https://community.chocolatey.org/packages/FreeFileSync#virus
