### ISSUE TITLE
croc

### ISSUE THREAD

**Issue by markifi** [ChrisTitusTech/winutil#2067]
**Is your feature request related to a problem? Please describe.**
while it serves the exact same function the exact same way, magic wormhole, as nice as it is, is not as well maintained as croc, therefore i've decided to become an unpaid croc lobbyist. it is constantly being updated with any newly discovered issues solved.

**Describe the solution you'd like**
swap magic wormhole to croc, or simply have both in.

**Describe alternatives you've considered**
manual installs

**Additional context**
[https://github.com/schollz/croc](url)

**Comment by og-mrk** [comment]
Once PR [#2070](https://github.com/ChrisTitusTech/winutil/pull/2070) gets merged, then it'll be available in the next GitHub release of WinUtil, the progress of this addition will be available over on PR [#2070](https://github.com/ChrisTitusTech/winutil/pull/2070) replies/events, and over on Tracking Issue [#1782](https://github.com/ChrisTitusTech/winutil/issues/1782).

Thanks for the cool app request @markifi 😄
