### ISSUE TITLE
Remove winget and chocolately

### ISSUE THREAD

**Issue by anthonyabbasi** [ChrisTitusTech/winutil#2068]
I recently bought the .exe wrapper of this software because I thought that would remove the requirement of download both winget and chocolately but it still did install it. Can there please be a separate version without winget or chocolately, I don't use the download section, I only use the tweaks scripts. I already bought the program so I hope this can happen.

**Comment by MagmaBro123** [comment]
Winget and Chocolately are required for Winutil's program installs to function.
