### ISSUE TITLE
error using  microwin to make an iso

### ISSUE THREAD

**Issue by sw15621hhhh** [ChrisTitusTech/winutil#2072]
![obraz](https://github.com/ChrisTitusTech/winutil/assets/172050653/1a4bced1-c2da-44cd-9784-9a5ace5c24b7)
I just got this error i didnt touch anything and download didnt finish ;c

**Comment by blusewill** [comment]
Try using Powershell 7 I guess?

**Comment by CodingWonders** [comment]
It should be fixed with #2192

**Comment by Real-MullaC** [comment]
Hello,

If this is fixed please could you close this issue?
