### ISSUE TITLE
Program Feature Request - Figma

### ISSUE THREAD

**Issue by YoshiroMaximus** [ChrisTitusTech/winutil#2073]
Figma is a program for designers and a great way to make SVGs.

I would like Figma to be included in the list of programs for installation in the Document section.

The app is free for personal use and for students.

The Winget command for it and the package is here:
https://winget.run/pkg/Figma/Figma

winget install -e --id Figma.Figma

![image](https://github.com/ChrisTitusTech/winutil/assets/76180677/24de93fe-4ff3-4a7d-acf1-3ae9b906e0ff)

**Comment by og-mrk** [comment]
Hello @YoshiroMaximus
The progress of this request will be tracked in Tracking List [#1782](https://github.com/ChrisTitusTech/winutil/issues/1782), thanks for your suggestion 😄

**Comment by Real-MullaC** [comment]
Hello @YoshiroMaximus,

Please could you close this Issue as this was added in a PR and the maintainer (Chris) decided not to add this feature.

I am sorry if this is not what you wanted.
