### ISSUE TITLE
How to use WinUtil on Linux? 

### ISSUE THREAD

**Issue by foss-enjoyer** [ChrisTitusTech/winutil#2075]
Do I need windows in the first place to use WinUtil? Can I use it natively on Linux?

**Comment by MagmaBro123** [comment]
This is for Windows only.

**Comment by og-mrk** [comment]
@foss-enjoyer
WinUtil (short for `Windows Utilities`, also known as `Windows Tool Box`) is a PowerShell script designed and created for Windows only, as all of its Tweaks and Configuration is Windows related ones, the App Installation Section of WinUtil uses Package Managers (at the time of writing, only `Chocolatey` and `WinGet` Package Managers), which are designed for Windows.

Which concludes an answer to your question, that being.. No, WinUtil can not run without Windows, as WinUtil requires the system to be Windows 10 or 11, and WinUtil can't be ran natively on Linux.
