### ISSUE TITLE
The tool did not run at all

### ISSUE THREAD

**Issue by rbnaik** [ChrisTitusTech/winutil#2077]
[**Describe]([Winutil.log](https://github.com/user-attachments/files/15801006/Winutil.log)) the bug**
The tool did not run at all. I am attaching log file for your ready reference

**Comment by ModernTTY** [comment]
> **Describe the bug** The tool did not run at all. I am attaching log file for your ready reference

Please provide more details.

**Comment by blusewill** [comment]
It's because I am working on GitHub Mobile that I can't see the attached file?
