### ISSUE TITLE
VSCodium isn't installing

### ISSUE THREAD

**Issue by bckelley** [ChrisTitusTech/winutil#2079]
**Describe the bug**
VSCodium isn't installing despite proper params given, don't know why git is listed git is already installed.
![image](https://github.com/ChrisTitusTech/winutil/assets/15696431/44a9c85c-4336-40fd-ba25-39afb30c7e1a)
![image](https://github.com/ChrisTitusTech/winutil/assets/15696431/0715fb11-38a2-4c6c-965b-5c07a51d3d35)

**To Reproduce**
1. double click WinUtil shortcut
2. check VS Codium
3. click Install/Upgrade Selected

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by blusewill** [comment]
![Screenshot_20240615_110603_GitHub.jpg](https://github.com/ChrisTitusTech/winutil/assets/62820836/e9b9fe4f-e649-4bc4-963d-d98a7fa00b5f)

Who the hell named the packages like this....

**Comment by Owen-3456** [comment]
This will be fixed in the next release
PR: #2172

**Comment by bckelley** [comment]
I worked thank you don't understand why the user credentials box when my pc's user wasn't even listed??
