### ISSUE TITLE
Feature Removal Discussion: Simple OO Shutup Tweak

### ISSUE THREAD

**Issue by Marterich** [ChrisTitusTech/winutil#2085]
Hey All,

I know there is a Discussion Tab but I think here, more People will see the Discussion and have the ability to chime in. 
Here it goes. 
### The Proposal
I'm considering if the time has come to remove the simple "Run OO Shutup" Tweak from the Essential Tweaks section of winutil and only keep the "Customize OO Shutup Tweaks" Button.

### The Reason
Over the last few months, OO-Software (the company behind OO-Shutup) has become way more lax regarding its "Recommended" Settings. Thereby I mean, they seem to have started to include tweaks as recommended which disable functionality of Windows that a bunch of people want to use. (For example The Clipboard History or RDP Access to the Computer) This year alone more than 15 issues were opened on how to reenable the clipboard history on this repo.

### Pro/Cons of having the "Essential Tweak" Checkbox
[+]It's nice to apply all the recommended tweaks with just one click (instead of 4 via the Customize Button)
[-] It's not clear to the user which settings are being changed
[-] It takes time to keep the config files up to date

I'm not sure if the "Ease of Use" argument is enough to justify the ongoing "support" for the feature considering the time of all the community members who are involved in answering and resolving issues (not only regarding this issue) 

I'm interested in hearing what you all think about this :)

**Comment by stuckydev** [comment]
My opinion: since winutil should be used by more experienced windows-users anyway I think only having the "customize button" is a good decision.
