### ISSUE TITLE
Update to PowerShell 7 tweak doesn't work

### ISSUE THREAD

**Issue by DiegcD** [ChrisTitusTech/winutil#2087]
**Describe the bug**
Running Script for WPFTweaksPowershell7
Powershell 7 is already installed.
Settings file not found at C:\Users\DiegcD\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
However when running $PSVersionTable command it still shows PowerShell 5.

**To Reproduce**
1. Go to Tweaks Tab
2. Click on Replace PowerShell 5 with 7
3. Run Tweaks
4. PowerShell is still 5

**Expected behavior**
Running **$PSVersionTable** command should show PowerShell 7

**Additional context**
Windows 11 23h2 64 bits

**Comment by devCKVargas** [comment]
+1 on Win10 22H2 Build 19045.4412

**Comment by Marterich** [comment]
Have you restarted the Terminal afterwards? The tweak doesn't uninstall Powershell 5 (mainly because it's not really possible to my knowledge), installs Powershell 7 in parallel and changes the default of the Terminal to load up a Powershell 7 profile on startup.
At least that's the intended function

**Comment by blusewill** [comment]
Can you check if the folder path is working?
If it's working. Please send me the correct path and I will working on a patch

**Comment by DiegcD** [comment]
> Can you check if the folder path of the Windows Terminal? Please send me the correct path and I will working on a patch if possible

Old PowerShell 5 path is: 
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

And the new installed PowerShell 7 path is: 
C:\Program Files\PowerShell\7\pwsh.exe

**Comment by blusewill** [comment]
No what I mean is **Windows Terminal**'s Path

No the PowerShell Path

**Comment by DiegcD** [comment]
> No what I mean is **Windows Terminal**'s Path
> 
> No the PowerShell Path

C:\Windows\System32\cmd.exe

**Comment by blusewill** [comment]
Are you using Windows 10?

**Comment by DiegcD** [comment]
> Are you using Windows 10?

Windows 11, PowerShell 5 is my default terminal

**Comment by Real-MullaC** [comment]
Hello @DiegcD,

Please could you check if this is fixed your end and if it is could you please close this issue.

Thanks.
