### ISSUE TITLE
This script contains malicious content and has been blocked by your antivirus software.

### ISSUE THREAD

**Issue by Firecat2203** [ChrisTitusTech/winutil#2088]
**Describe the bug**
This script contains malicious content and has been blocked by your antivirus software.

**To Reproduce**

running the script : and got this 
Running Script for WPFTweaksEndTaskOnTaskbar
Running Script for WPFTweaksBlockAdobeNet
WARNING: A runtime exception occurred.
WARNING: At line:1 char:1
+
This script contains malicious content and has been blocked by your antivirus software.
**Expected behavior**
remove part of script or rectify the problem 

**Screenshots**

![Untitled](https://github.com/ChrisTitusTech/winutil/assets/138616160/73d65576-2b9e-4c54-ac05-17fc0f857555)

**Comment by MagmaBro123** [comment]
Then disable your antivirus.

**Comment by Firecat2203** [comment]
> Then disable your antivirus.

Thank you for your reply 

I have used this script successfully without issue in different pc and helped me alot. 
thank you  Chris for your effort and the wonderful work you are doing.  I just want to improve and rectify the script more or remove the source or the feature causing the the issue .

**Comment by Marterich** [comment]
@Firecat2203 seems to be the Adobe tweak (WPFTweaksBlockAdobeNet) that's causing the issue. Maybe Microsoft flagged the GitHub link to the blocklist repo. Will take a look at this when in find the time and no one else beats me to it :)

**Comment by Firecat2203** [comment]
The script run flaws regardless of the antivirus warning ⚠️  by the way i am using Bitdefender 
Thank you so much 

> @Firecat2203 seems to be the Adobe tweak (WPFTweaksBlockAdobeNet) that's causing the issue. Maybe Microsoft flagged the GitHub link to the blocklist repo. Will take a look at this when in find the time and no one else beats me to it :)

**Comment by blusewill** [comment]
Oh no. Here we go again XDD

**Comment by Marterich** [comment]
@Firecat2203 Sadly (or thankfully) I don't seem to be able to reproduce the malware warning on my device. 
Neither with Windows Defender nor with Bitdefender Free installed, so I'm not able to build a workaround for your specific scenario.

**Comment by SHR1SHAK** [comment]
I have avast free antivirus and its not flagged by mine either.

**Comment by iamnitingrover** [comment]
Hi, I tried the tool today and I have installed Bitdefender as my antivirus tool. Bitdefender is still detecting the script as malicious.

Here is the screenshot of powershell and bitdefender.

![image](https://github.com/ChrisTitusTech/winutil/assets/74922348/60fbe366-657c-4d8d-a639-b3e69f632681)

**Comment by SHR1SHAK** [comment]
I think the URL for github is flagged

**Comment by Marterich** [comment]
> I think the URL for github is flagged

Might very well be true, but it's also possible, that the heuristic engine of bitdefender has seen similar logic in malware before (which is very likely) 

1. Download file/entries
2. Overwrite or modify host file
3. Flush the cache

This would be a simple way for malware to implement DNS spoofing when you have admin access to the device.

Keeping this in mind, this requires a bit more investigation and fiddling to get "around" the detection and it is also quite possible that We (in accordance with @ChrisTitusTech) decide it would be best to completely remove the tweak, as virus alerts drastically impact the trustworthiness of an application
