### ISSUE TITLE
take a look at this program and one issue

### ISSUE THREAD

**Issue by ebh5e4bh5** [ChrisTitusTech/winutil#2098]
**Is your feature request related to a problem?no

**Describe the solution you'd like**
add whatever is in blackbird  and missing in winutil + add spooler services to manual

https://www.getblackbird.net/

**Comment by ebh5e4bh5** [comment]
it would also be cool to add a driver updater feature

**Comment by Marterich** [comment]
> Add spooler services to manual

I'm not quite sure how I feel about modifying the default for the Print Spooler Service, because printing in Windows is already flaky enough. 
Even though it _shoudntn't_ introduce any problem, I'm not sure if it's smart to play around with the defaults in this case because the potential problems and issues that this _could_ entail will be annoying to fix for the layman and reflect badly on the reputation of winutil like "Winutil broke my printer"

**Comment by ebh5e4bh5** [comment]
Create a separarate option to set the printer to manual with a pop-up warning,

**Comment by ebh5e4bh5** [comment]
and one more option to reset it to automatic, do this with any other services you are in doubt too.

**Comment by ebh5e4bh5** [comment]
just one correction: Only add if it is viable, for example I was taking a look at one of the services that could be set to disabled by blackbird and one of them was the notification push, that one is actually necessary, I mean it could be set to manual, but I´d say it needs to be running all the time in order to detect the notifications.

**Comment by ebh5e4bh5** [comment]
Almost no one uses the printer service
and it's highly unlikely to cause any
issues just from merely setting it to manual(if it does, then it's window's fault), you could put a pop-up checkbox asking if I want to set the printer service to
manual at my own risk then.

**Comment by ebh5e4bh5** [comment]
I'm not asking you to introduce the ability to download the program inside winutil but rather to add whatever useful features that program has that could be missing in winutil, winutil is supposed to be the ultimate program for Windows optimization and setup.

**Comment by blusewill** [comment]
In my research. HP and Samsung does use Printer Service.

And I think O&O Shutup already in the toolbox will also work that way the BlackTweaks Does.
