### ISSUE TITLE
[abnormal shutdown]  CTT-Windows-Utilities .exe wrapper ... caussing PC to shutdown (emergencyshutdown!!!)

### ISSUE THREAD

**Issue by TerryMartinez** [ChrisTitusTech/winutil#2108]
Description:
Simple! This Script/Software run nice and well! Love the Software (.exe wrapper) and all
But It is the cause of my Windows 10 or most likely the PC(sensor trigger)
to shutdown the device which is for me Not acceptable at all!

It does shutdown the same way the PC would, for exemple, overheating/other emergency trigger.
Mabye, mabye not physical trigger, Mabye, mabye not related to heat!
And NOTE, My windowsOS(Not the pc) is also Fully broken on Purpous !!!! xD
(PLS dont mind this. Even tho it could be my fault and there might be nothingg to do for me in particular ...
I would want someone to Look Into This Anyways as it is still NOT NORMAL that My PC is Buggy in general.
WindowsOS is broken on purpous but not the PC (Recent machine / not beat-up if ican put it that way)
All the thing I need and use do work fine and well, ALL of thems)

I Cant find 0 log from anywhere as its Probably an emergency protection comming from a sensor of MY PC.
No screen error no blue-screen, NOTHING! Straight shutdown! (no error or even checks at restart also) Litterally nothing.

(Hope this is a clue if heat is the cause)
If its a Heat Problem: its NOT Normal that this simple Script/.exe wrapper Cause Heat to RAISE
as Im still able to run heavy computing softwares and play heavy computing games even in hot days!
GPU / CPU : GeForceGTX1070Mobile (laptopVersion) / Intel Core i7-6820HK
__________
Reproduce / expected behavior:
I found out It does it EVERYTIME an OTHER SOFWARE is RUNNING too!!!
(most likely Firefox! ... I remember this browser was running 2 time out of 3
of the pc shutdown FROM this Problem. (used the wrapper around 15 time)
Each time it appened the Script was running [Installing/Updating] for a few things and/or was downloading stuff.

I have no way to lean someone to reproduce that problem in other ways right now.
It might be related to My windows itself (my fault, broked it on purpous ... and PLS DONT MIND THIS ! ITS Absolutly Not Normal for the script to trigger an Emergency Shutdown! Thats Shouldnt be the case and Thats Unacceptable :P )

On my PC, 752ROG laptop, heat can easely get close to its maximum in Normal use/gaming! Even in hot days but thats Ok, always have been.
As I said earlyer theres also 0 log I could find as its most likely a physical protection getting triggered.
Same behavior as overheating !!! (Closest cause and effect I can think of)
I didnt monitor the PC yet while doing the things I discribed in the first paragraph of this section.
It just appened 3 time(3 EmergencyShutdown) out of 10 or 15 uses of CTT-Winutil .exe wrapper!!!
(Monitoring while using CTT-WinUtil .exe wrapper and firefox was my next idea after starting this report. If you need I might help for more info)
__________
Screenshot:
Well Imagine A Pc Being Off   ;P
__________
I Might add some edit to this in the near future like a report of monitoring my windows hardware while doing the reproduction methode

**Comment by blusewill** [comment]
That currently sounds like a hardware fault.
Though you already bought the exe wrapper. Have you tired to execute using PowerShell Command?

**Comment by TerryMartinez** [comment]
Yeah Probably something related to My windows Honestly I should have wait a little more befor doing that report. 👍🏽 I did some test today and It Actualy only happen on my windowsOs when other software are open at the same time probably the browser.
I cant pin point what and why but At this point Im 80% sur its the WinOS, For my other Systems, Its all fine and working!!!
But Im erasing Windows of my life so Its actually dosnt matter anymore You all can IGNORE THIS Im sorry for your time :P
