### ISSUE TITLE
Copilot forced removed even without getting ticked in tweaks 

### ISSUE THREAD

**Issue by MoodyAbed** [ChrisTitusTech/winutil#2112]
**Describe the bug**
when choosing standard in tweaks even when disabling copilot is not ticked it gets tweaked and removed 

**To Reproduce**
1. Go to tweaks
2. Click on Standard
3. run tweaks 

**Expected behavior**
copilot shouldn't get removed as it is not ticked .
even when pressing get installed it shows that removing copilt is ticked 
![Screenshot 2024-06-19 095113](https://github.com/ChrisTitusTech/winutil/assets/92605640/593f04b7-01c9-433c-9000-b1ae8de43176)

**Screenshots**
![Screenshot 2024-06-19 095029](https://github.com/ChrisTitusTech/winutil/assets/92605640/79d7d2df-8290-47a0-a974-c3546bc1a575)

**Comment by Harry-B-Smith** [comment]
This happened to me, too.

**Comment by MoodyAbed** [comment]
> This happened to me, too.

It was because of oo shut up.
Just open customize  oo and re-enable it ( also re enable clipboard if you wanna use it ) and restart

**Comment by Harry-B-Smith** [comment]
Awesome. That was it for me, too. Thanks for your help.
