### ISSUE TITLE
REQUEST: Add `CONTRIBUTING.md` and `STYLEGUIDE.md` to this repo

### ISSUE THREAD

**Issue by RobSeder** [ChrisTitusTech/winutil#2115]
**Is your feature request related to a problem? Please describe.**

You [just made a video](https://www.youtube.com/watch?v=JF8F7uaGfV8) about contributing to open source, but not liking the quality or style of pull requests. 

**Describe the solution you'd like**

The GitHub answer to that is to create a `CONTRIBUTING.md` file that describes how to properly and ideally contribute to your repo. This might include things like "don't make huge changes", "do make a small, specific changes", "Include a cover lever with your PR to describe what you've done", etc.

Also, consider creating a `STYLEGUIDE.md` file, also in the root of the repo. This will include things like: tabs vs spaces, PascalCase vs camelCase, file naming standards, comment style (e.g. "#" vs "/* */", etc). There is not a formal spec for what is in a repo style guide, so just include the formatting and styling things that you care about.

- For `CONTRIBUTING.md` see:
  - [Setting Guidelines for Repository Contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) and [example](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

- For `STYLEGUIDE.md` see:
  - [Writing on GitHub](https://docs.github.com/en/get-started/writing-on-github)
  - [GitHub Docs Style Guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide)
  - Example: [Google Deepmind](https://github.com/google-deepmind/mujoco/blob/main/STYLEGUIDE.md)
  - Example: [Twitter Archive](https://github.com/twitter-archive/commons/blob/master/src/java/com/twitter/common/styleguide.md)

**Describe alternatives you've considered**

None. This is for everyone's benefit and it is the industry standard.

**Additional context**

Adding this communication is a way that you can clearly convey how you would like to see pull requests. Or, if you get a low quality pull request, then you can point the contributor to these files for correction.

**Comment by ChrisTitusTech** [comment]
Thanks for pointing this out Rob, I'll add it to the project!
