### ISSUE TITLE
Pop-Up notification when Tweaks are finished

### ISSUE THREAD

**Issue by LoopTJ** [ChrisTitusTech/winutil#2116]
**Is your feature request related to a problem? Please describe.**
I would prefer to have a pop-up window open when "Installs have Finished" and when "Tweaks are Finished" so that I know I can continue with the next process in the utility.

**Describe the solution you'd like**
Once the Installs and Tweaks are finished present a pop-up window letting me know they've completed. Similar to the pop-up when the "Updates are Finished".

**Describe alternatives you've considered**
Currently I have to switch back to the terminal window to see when the process is finished. I find the pop-up easier as it is a notification that the process completed, this is especially helpful when running the utility on a remote computer since I'm not actively using the computer, just running setup scripts.

**Additional context**
Since some people won't want pop-ups, if possible have a toggle to turn on / off pop-ups for Installs, Tweaks, and Updates.

**Comment by Real-MullaC** [comment]
Will be fixed in PR #2133 and #2134
