### ISSUE TITLE
Windows update is not working properly after creating a MicroWin image

### ISSUE THREAD

**Issue by Keshekot** [ChrisTitusTech/winutil#2118]
**Describe the bug**
Windows update is not working properly after creating a MicroWin image - it does not install cumulative updates with the error 800f0983. Tested on latest builds of Windows 11 ARM and Windows 10, the issue is identical. 
Repair (sfc, dism restore health) does not help. Sfc finds a lot of damaged components though. Happens on both VM and real hardware.

**To Reproduce**
Create an image de-selecting options "Keep Defender" and "Keep Edge" (essentially removing everything). It also breaks WinUpdate if you de-select only "Keep Edge". 
So resulting image will be broken and will not install cumulative updates once installed. Other updates install fine though.

**Screenshots**
<img width="690" alt="Screenshot 2024-06-19 at 15 53 43" src="https://github.com/ChrisTitusTech/winutil/assets/173281441/ec433a36-d262-49c0-b9c2-6188aae378cc">

**Additional context**
Happy to assist in testing.

**Comment by blusewill** [comment]
Probably because of setting security update by default? I have no idea how does MicroWin works but I guess that's the issue

**Comment by Keshekot** [comment]
Amazing, you are correct!. Indeed if I switch the update options in the script, they install fine. 

I believe this must be documented properly as it is very unclear - also why run the tool after installation if the image was supposed to be pre-configured.

**Comment by blusewill** [comment]
Alright. I think someone should make a switch to switch between update mode before getting configured.
But I am too out of touch with Microwin having no idea how to add it. But I can try my best adding it.

**Comment by Real-MullaC** [comment]
@CodingWonders

**Comment by CodingWonders** [comment]
Sadly, I don't have a powerful ARM-based device (the only thing I have with such a chip is a Raspberry PI 3B)

**Comment by Keshekot** [comment]
This is also applicable to a regular x86-64 image. I can assist in testing on ARM if required 

⁣Get BlueMail for Android ​

**Comment by Keshekot** [comment]
Hi, 
Sorry for the lack of response. It looks like that current versions of the script do not have this problem anymore: I've checked ARM version 2 weeks ago and a regular x64 one now, and haven't encountered any problems with windows update.

**Comment by cars11** [comment]
I just ran a fresh MicroWin install and now have this issue with Windows Update.
Any ideas what can be done? Also tried sfc scan and DSIM restore

**Comment by costykyo** [comment]
does anybody know if this is gonna ever be fixed?
