### ISSUE TITLE
Add kicad to the installer

### ISSUE THREAD

**Issue by Sergiogd112** [ChrisTitusTech/winutil#2119]
Kicad is an open-source EDA tool. It's a good starting point for those who want to do electrical design and is even used by professionals in the industry.

[https://www.kicad.org/](https://www.kicad.org/)

The project is on winget under the ID KiCad.KiCad.
![image](https://github.com/ChrisTitusTech/winutil/assets/34186354/ff1e8752-7ae5-45d9-97bb-5969efc0e67b)

**Comment by Real-MullaC** [comment]
Will be fixed in PR #2131
