### ISSUE TITLE
Run Tweaks and UndoTweaks OR Enable and Disable But not Both Ways

### ISSUE THREAD

**Issue by mattvisa** [ChrisTitusTech/winutil#2132]
**Describe the bug**
Consider going either with running tweaks and undo tweaks or going with checkmarks to enable or disable tweaks, but doing it both ways is somewhat confusing and inconsistent in places. 

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/130477370/d8fa6b2d-6a0f-4e80-816f-013c7c1bac2d)

![image](https://github.com/ChrisTitusTech/winutil/assets/130477370/2f079cd2-e0db-411e-840b-cd6e905779f2)

**Comment by crazycheetah42** [comment]
Yeah I think there should just be one IPv6 checkbox and running it will disable it and undoing it should enable it.

**Comment by mattvisa** [comment]
Agreed. If you were to use that same logic for all the tweaks, I think it would be much more consistent and user-friendly.

**Comment by Marterich** [comment]
Interesting Idea but a bit tricky to implement. 

Getting an action to trigger at state change of the checkbox is easy enough, the tricky part will be keeping the interface responsive while a tweak is running and maintaining a queue of all the tweaks/checkboxes that still need to be applied. 
I will be playing around with this idea but I cannot promise anything.
