### ISSUE TITLE
Slow Internet after Tweaks

### ISSUE THREAD

**Issue by svn-josh** [ChrisTitusTech/winutil#2146]
After running the Tweaks my Internet seamed kinda slow. Even i got 900 down and 540up but it takes at least 5-10second to load a normal website. I undid DNS and reset my Network interface, but still not better.

**Comment by svn-josh** [comment]
PS: It took 20 Seconds to get to the Website, but the Speedtest is fine: 
![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/d70cdb8f-750e-4945-ac52-ab2c05e78e06)

**Comment by svn-josh** [comment]
other Devices in the Network are fine to

**Comment by og-mrk** [comment]
Hello @svn-josh , thanks for reporting this issue. May I ask what Tweaks did you run?

**Comment by svn-josh** [comment]
i think it was the desktop one

**Comment by ChrisTitusTech** [comment]
@svn-josh did you disable teredo tunneling? might click that and select undo.

**Comment by SHR1SHAK** [comment]
I had the same issue. I just changed DNS to Cloudflare nothing more. Mine was not even loading. Had to manually ipconfig /release, /renew, and flushdns with a quick restart then it worked fine.

**Comment by svn-josh** [comment]
somehow it was the DNS (cloudflare) i changed it back in Windows 11 UI to Default but it was still set to cloudflare in the background. Change it with cmd and it works normal again. Windows is weird lol
