### ISSUE TITLE
Change NewLine Character to be CRLF instead of LF for 'winutil.ps1' File

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#2148]
### Main Issue

The `CRLF` New Line Character is the default one used by git on windows (even when using Git Bash), where Windows is obviously the Platform of choice when developing & debugging WinUtil, changing it to `CRLF` from what's currently set as, which's UNIX New Line `LF` (**L**ine **F**eed) is for the better.

This is even shown when compiling WinUtil on GitHub Actions, indicating that the reason behind this odd switch isn't related to workflow files (this is my own guess, further investigation might be needed).

> [!NOTE]
> This issue wasn't present before removing `winutil.ps1` from Git Tracking List, I'm guessing something happened when creating `winutil.ps1` file in commit 009ab5066cc80f59d12b5385cb27ec5841796be3 ?

### Why would someone care about it?

Even though PowerShell handles New Line Characters without any problems (Powershell 5 & 7).. but when viewing The Git Diff Output, because I edit all my changes through CLI, using Git & GitHub CLI Tools, as well as CLI Editors like Vim & NeoVim.. it displays `warning: in the working copy of 'winutil.ps1', LF will be replaced by CRLF the next time Git touches it`.. which doesn't have to be the case!

When there's common rules to follow across project's files.. then all of the files should follow said rules.

### Final Thought

Although this's a minor issue to nitpick.. and it may/may not affect about 1-2% of devs who contribute to the project, and even less when considering that viewing and committing compiled files isn't needed at all.. _most of the time_, I still wanted to point this out to document it.. and in the hopes that someone might find a solution for it.

Thanks for taking your time reading through this Issue Ticket, and have a nice day 😄

**Comment by Marterich** [comment]
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows

Might be as simple as editing the .gitattributes file. Will check later when I'm at my desk. This will however result in quite a big initial PR because all line endings will be replaced

**Comment by og-mrk** [comment]
> https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows
> 
> Might be as simple as editing the .gitattributes file. Will check later when I'm at my desk. This will however result in quite a big initial PR because all line endings will be replaced 

Thanks for the info/link @Marterich 😄
Didn't know you could configure git settings across contributors like this.

And after reading it.. the commit will be kind of massive, every line in every text file will be changed (may be even the ones that are Already using `CRLF`).. I' try testing as well on my side to see how we could manage it. Thanks again for the help 👍

**Comment by Marterich** [comment]
You're welcome @og-mrk 

If this works as expected, be sure to thoroughly document your reasoning in a PR so it has any chance at all or being merged xD 

IMHO, when developing a script for Windows on Windows you should adhere to the conventions and quirks that exist on the platform, so I'm all for it

**Comment by og-mrk** [comment]
@Marterich 
Made a PR which tries to resolve this issue, here's [a link to it](https://github.com/ChrisTitusTech/winutil/pull/2150).

It turns out that the generated XAML content from json files is actually causing this issue.. a bit weird, because I haven't seen this Git Warning before (may I have and didn't pay much attention).. either way, this issue should be done once that PR is merged 👍
