### ISSUE TITLE
Typo in the description of Element.

### ISSUE THREAD

**Issue by SaqinNoor** [ChrisTitusTech/winutil#2151]
**Describe the bug**
Exactly as the title says. There is a "?" in place of ","

**To Reproduce**
1. Go to 'Install'
2. Hover on 'Element'
3. See error

**Expected behavior**
No typos.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/89857833/de65d4fd-e6f5-4440-858d-2557ea905d4b)

**Additional context**
Nothing else.

**Comment by og-mrk** [comment]
Made a new PR addressing this problem (here's [a link to it](https://github.com/ChrisTitusTech/winutil/pull/2153)), thanks for reporting this issue @SaqinNoor 👍

**Comment by SHR1SHAK** [comment]
issued a PR for that
