### ISSUE TITLE
[Bug] Get Installed does not detect Chrome

### ISSUE THREAD

**Issue by vavavr00m** [ChrisTitusTech/winutil#2156]
**Describe the bug**
- Pressing the Get Installed does not detect Chrome installation.

**To Reproduce**
1. Steps to reproduce the behavior:
2. Download and install Chrome from the [website](https://www.google.com/chrome/)
3. Launch PowerShell as an admin
4. Run 
```
iwr -useb https://christitus.com/win | iex
```
or
```
irm "https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1" | iex
```
5. Press `Get Installed` button
6. Wait for it to add check mark to installed programs
7. See Chrome does not have a check mark

**Expected behavior**
- Chrome will have its box marked with a check

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/4675132/190f9f6d-5e36-429d-b7f5-ef5102b77cec)

**Comment by Real-MullaC** [comment]
Hello @vavavr00m,

Thank you for reporting this issue. But I have just attempted to replicate the issue and I seem to not be able to replicate it.

Please could you do the following steps to make sure it is installed and that you are using latest WinUtil release.

- Check you have Google Chrome installed by launching it.
- Launch WinUtil by launching PowerShell as Admin and use command `iwr christitus.com/win | iex` or `irm "https://github.com/ChrisTitusTech/winutil/releases/download/v24.06.20/winutil.ps1" | iex`
- If you still encounter the issue please let us know and we will invetigate further.

Thank you.

**Comment by MyDrift-user** [comment]
how did you install google chrome?
Winget won't detect portable packages and I also think that it does not get applications with a custom directory (out of norm)

What happens if you try to install google chrome with winget?

**Comment by MyDrift-user** [comment]
I looked into it and i now see the problem we are having.

When installing Chrome from the installer downloaded from their website WinGet reads the application under the ID `Google.Chrome.EXE`, WinUtil uses `Google.Chrome`.

Here is an Image of the installations of both as reference:
![image](https://github.com/ChrisTitusTech/winutil/assets/121827219/0ded7641-1827-421e-bcda-bbbdc03686c0)


The difference:
- Google.Chrome > MSI Installer
- Google.Chrome.EXE > EXE Installer

To install the MSI package from their website you need to go to their [chromeenterprise subdomain](https://chromeenterprise.google/download/?utm_source=adwords&utm_medium=cpc&utm_campaign=2024-H1-chromebrowser-paidmed-paiddisplay-other-chromebrowserent&utm_term=downloadnow-chrome-browser-enterprise-download&utm_content=GCHB&brand=GCHB&gad_source=1&gclid=EAIaIQobChMIiMiOi-P4hgMVsICDBx109zbqEAAYASAAEgIm6PD_BwE&gclsrc=aw.ds&modal-id=download-chrome) and choose msi installer.

A simple fix for that is just to change the package from WinUtil to use the more common installer (.exe).

I can make a pull request but i'll look if there are any key differences in the packages first.

**Comment by MyDrift-user** [comment]
Not the way we manage packages right now. 
We could let the parameter winget have multiple entries that could be helpfull for all of the actions.

That would not minimize/eliminate similar issues in the future (with all application in mind) because not every package defferinciates itself using a .exe at the end. We would have to look into diffrent installers for every application for that statement to be true.
