### ISSUE TITLE
Dns

### ISSUE THREAD

**Issue by Uraclee** [ChrisTitusTech/winutil#2161]
I was change my DNS with this tool to OpenDNS. At this time OpenDNS is down. How to change my dns to default if the simple set dns to 8.8.8.8 didn't work? Because of the OpenDNS is down i can't open this tool.

**Comment by og-mrk** [comment]
Hello @Uraclee
I'll be typing the steps that will work on Windows 11 & 10 (and all the way back to Windows 7 & Vista), but if you find my explanation to be un-clear, you can find tutorials online on how to change your DNS Server on Windows, found [this video](https://www.youtube.com/watch?v=WctuCifAw4g) after a quick search, but you can use other tutorials as well.

And you could find tutorials on how to change DNS through PowerShell:
1. [a guide to change DNS - The Windows Club](https://www.thewindowsclub.com/change-dns-server-using-command-prompt-and-powershell)
2. [An Example on how to reset DNS back to default one - Microsoft Docs](https://learn.microsoft.com/en-us/powershell/module/dnsclient/set-dnsclientserveraddress?view=windowsserver2022-ps#example-2-reset-a-dns-client-to-use-the-default-dns-server-addresses)
  That is.. if you know the Interface Index, you can find out by running `Get-DnsClientServerAddress` in PowerShell running as Admin. (see explanation in Point No. 1)

### The steps to change DNS back to default

1. Open up the Start Menu by pressing the Windows Logo on commonly found on the left of Task Bar.
2. type `Control Panel` in the Search Bar, and press on the first option that come up.
3. change the view into Category View (if it wasn't already).
4. go to Network and Internet -> Network and Sharing Center -> choose the Device that's used to connect to your router / modem (and thereby, the internet).
5. then a window will pop-up, click on the `Properties` button, then choose `Internet Protocol Version 6. (TCP/IPv4)` option, and click `properties` button to see and change its properties.
7. change the DNS option back to `Obtain DNS server address automatically`, then click `OK`.

**Comment by Real-MullaC** [comment]
Hello @Uraclee,

If this issue is now fixed please could this issue get closed?

**Comment by og-mrk** [comment]
This issue looks to be resolved, closing this issue...

/close
