### ISSUE TITLE
Window11 22H2 install

### ISSUE THREAD

**Issue by mselv1970** [ChrisTitusTech/winutil#217]
After install of windows 11 22H2 and  running Windows utility and receive a number denied in the process
Removing AutoLogger file and restricting directory...
C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger: Access is denied.
Stopping and disabling Diagnostics Tracking Service...
Stop-Service : Service 'Connected User Experiences and Telemetry (DiagTrack)' cannot be stopped due to the following
error: Cannot open DiagTrack service on computer '.'.
At line:924 char:13
+             Stop-Service "DiagTrack"
+             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Stop-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.StopServiceCommand

Set-Service : Service 'Connected User Experiences and Telemetry (DiagTrack)' cannot be configured due to the following
error: Access is denied
At line:925 char:13
+             Set-Service "DiagTrack" -StartupType Disabled
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (System.ServiceProcess.ServiceController:ServiceController) [Set-Servi
   ce], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotSetService,Microsoft.PowerShell.Commands.SetServiceCommand

Disabling Wi-Fi Sense...
Set-ItemProperty : Requested registry access is not allowed.
At line:933 char:13
+             Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\PolicyMa ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...otSpotReporting:String) [Set-ItemProperty], Securit
   yException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

Set-ItemProperty : Requested registry access is not allowed.
At line:937 char:13
+             Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\PolicyMa ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...FiSenseHotspots:String) [Set-ItemProperty], Securit     yException                                                                                                               + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand
Set-ItemProperty : Requested registry access is not allowed.
At line:959 char:13
+             Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Co ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...n Manager\Power:String) [Set-ItemProperty], Securit
   yException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

Enabling NumLock after startup...
Set-ItemProperty : Requested registry access is not allowed.
At line:967 char:13
+             Set-ItemProperty -Path "HKU:\.DEFAULT\Control Panel\Keybo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_USERS\.DEF... Panel\Keyboard:String) [Set-ItemProperty], Securit
   yException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

Doing Security checks for Administrator Account and Group Policy
System error 5 has occurred.

Access is denied.

**Comment by stalkward** [comment]
I had the same issue! Honestly not sure, at all, if this is the right way to do things but,

What I did was head to Registry Editor and under HKEY_LOCAL_MACHINE, went to PERMISSIONS of the SYSTEM folder and added full permission to my account and tweaks seem to be going through! 

Again, not sure if its the right way to do it, but yeah.

**Comment by mselv1970** [comment]
Found the the .exe doesn't run in admin.  Windows terminal. Copy and paste the script in admin Windows terminal worked went from 287 prosses to 130.Sent from Samsung Galaxy smartphone.
-------- Original message --------From: stalkward ***@***.***> Date: 10/3/22  13:39  (GMT-05:00) To: ChrisTitusTech/winutil ***@***.***> Cc: Mark Selvenis ***@***.***>, Author ***@***.***> Subject: Re: [ChrisTitusTech/winutil] Window11 22H2 install (Issue #217) 
I had the same issue! Honestly not sure, at all, if this is the right way to do things but,
What I did was head to Registry Editor and under HKEY_LOCAL_MACHINE, went to PERMISSIONS of the SYSTEM folder and added full permission to my account and tweaks seem to be going through!
Again, not sure if its the right way to do it, but yeah.

**Comment by ChrisTitusTech** [comment]
You needed to run it from an elevated powershell prompt or Win Terminal with Admin.
