### ISSUE TITLE
Tool is now stuttering while scrolling on install panel.

### ISSUE THREAD

**Issue by SHR1SHAK** [ChrisTitusTech/winutil#2170]

**Comment by MyDrift-user** [comment]
Hello, I was not able to recreate the issue using multiple machines with diffrent kind of specs.
could you please provide more info?

Possible Infomations:
- Video/Image of issue
- Is this a Potatoe device or a usually good performing device? (maybe give specs)
- Explain what you mean with "now"
- Further explanation.

If you didn't have had this issue on the same device before try out an older version of winutil from the Releases and report if it works again.

**Comment by blusewill** [comment]
Probably because of the Matrix Theme issue.
Since when you are scrolling it will use more GPU Performance.

This can be seem by opening Task Manager and scroll the install section.

**Comment by MyDrift-user** [comment]
Yes that is most likely true but with his specs and fresh Win11 installation it is still strange that it struggles only from scrolling the installation page. With the same amount of RAM i usually only got around 400-500MBs used from WinUtil.

**Comment by og-mrk** [comment]
> Yes that is most likely true but with his specs and fresh Win11 installation it is still strange that it struggles only from scrolling the installation page. With the same amount of RAM i usually only got around 400-500MBs used from WinUtil.

Same thing on my end, the RAM usage isn't a lot (it could be optimized further.. but it's ok for now), and I can't recall scrolling to be an issue (only noticed it when WinUtil starts up, takes 5 seconds or so after GUI pops up to start being usable)

Just for reference, my specs are somewhat below an average computer now adays, it's a laptop with 16 Gb of RAM, MX110 Nvidia GPU with 2 Gb VRAM.

**Comment by blusewill** [comment]
> > Yes that is most likely true but with his specs and fresh Win11 installation it is still strange that it struggles only from scrolling the installation page. With the same amount of RAM i usually only got around 400-500MBs used from WinUtil.
> 
> Same thing on my end, the RAM usage isn't a lot (it could be optimized further.. but it's ok for now), and I can't recall scrolling to be an issue (only noticed it when WinUtil starts up, takes 5 seconds or so after GUI pops up to become usable/responsive)
> 
> Just for reference, my specs are somewhat below an average computer now adays, it's a laptop with 16 Gb of RAM, MX110 Nvidia GPU with 2 Gb VRAM.

I should make MX and Laptop GPU into the optimized mode. Let me Edit the whitelist very quick.

**Comment by blusewill** [comment]
@og-mrk Can you test on your MX110 Laptop?
To check if it boots into Dark Mode instead of Matrix
[winutil.zip](https://github.com/user-attachments/files/15993418/winutil.zip)

**Comment by og-mrk** [comment]
> @og-mrk Can you test on your MX110 Laptop? To check if it boots into Dark Mode instead of Matrix [winutil.zip](https://github.com/user-attachments/files/15993418/winutil.zip)

@blusewill It choose the Matrix theme like always.

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/d2f70770-3c31-415c-8bc6-89b76091631f)

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/ef223927-f24b-4b46-964f-70402fe5ea11)

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/b7111863-38dc-4d5c-886d-6e2dde0d22a3)

**Comment by blusewill** [comment]
Alright. It boots into Dark Mode. By Checking the Search Box I can verify that.
Let me submit the PR.

**Comment by blusewill** [comment]
> Alright. It boots into Dark Mode. By Checking the Search Box I can verify that. Before I submit the PR. Can you makes sure the Search Box looks like the following Picture?
> 
> ![image](https://private-user-images.githubusercontent.com/62820836/343398294-d2a3e3d6-1fe3-4032-b005-17000b86acd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDI3NDAsIm5iZiI6MTcxOTQ0MjQ0MCwicGF0aCI6Ii82MjgyMDgzNi8zNDMzOTgyOTQtZDJhM2UzZDYtMWZlMy00MDMyLWIwMDUtMTcwMDBiODZhY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIyNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzY2FkMmE5Y2RjOTQ5Y2E5YTY5OWY5NWQyNTgzYzNhMzIxZDg1N2Y5MjI2ZjFhNzE4ZjAyNzI4NjBlMjU2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCRC07zUFV30Zk2Q2YRjAWS50XUG-WoLR_GK-zn5Obo)
> 
> This one is the Matrix Search Box. If it still looks like this let me know!
> 
> Yes there are barely any difference between dark mode and Matrix Mode lol

The Problem of Matrix is it stays consistent high resource mode.
And the Dark Mode removes the ShadowPulse Search Box. And the Resource will be not as intense as Matrix

Here is a compare video between Matrix and Dark Mode. As you can see it only spikes the resource when scrolling like that.
But most of the user won't scroll like that. So I count that as not as resource intensive?

https://github.com/ChrisTitusTech/winutil/assets/62820836/09d38f2d-0716-4fe9-9119-9895eb687fff

**Comment by og-mrk** [comment]
@blusewill After further testing (adding some print statements), it turned out be working as expected.
Will send an attachment that includes your changes + my quite simple debug code.

[winutil.zip](https://github.com/user-attachments/files/15997689/winutil.zip)
