### ISSUE TITLE
Internet Adapter properties change every time tool is ran

### ISSUE THREAD

**Issue by goddessskynsfw** [ChrisTitusTech/winutil#218]
**Describe the bug**
Every time I run the tool and check my Internet Adapter settings, They are gone and need to be re-added else I can't access any website/

**To Reproduce**
1. Run the tool
2. Go to 'tweaks'
3. Select 'Run O and O Shutup'
4. Run tweaks
5. Restart
6. Try and access any website
7. See error

**Comment by ChrisTitusTech** [comment]
I'm unable to replicate this error.
