### ISSUE TITLE
Set Up Autologin - autologin.exe missing

### ISSUE THREAD

**Issue by tychoid** [ChrisTitusTech/winutil#2180]
Set Up Autologin not downloading/launching autologin.exe?

1. Go to 'Config Tab'
2. Click on 'Set Up Autologin'
3. Button & window freezes for a minute
4. Error in PowerShell: 
```
'C:\Users\x\AppData\Local\Temp\autologin.exe' is not recognized as an internal or external command,
operable program or batch file.
```

Windows 11 Pro 23H2 build 22531.3737
Microsoft account was very recently passwordless.
Was trying to fix a bugged duplicate account at login throwing up an "incorrect password" error that might have been caused by winutil or 00 Shutup.  Only some essential/recommended tweaks used.

**Comment by og-mrk** [comment]
@tychoid Created a PR which tries to fix this Autologin not being found in `TEMP` Folder.
Thanks for reporting this issue 😄
