### ISSUE TITLE
Fix print management which uses mmc.

### ISSUE THREAD

**Issue by krystofkrticka** [ChrisTitusTech/winutil#2185]
**Is your feature request related to a problem? Please describe.**
If you clean install windows 11 and try to find print management management console, you wont find it util you uninstall print management using DISM and install it back using DISM, because when you are installing it using optional features in settings it'll fail every time you try.

**Describe the solution you'd like**
Fix print management automatically when either starting WinUtil or as one of the optional tweaks.

**Describe alternatives you've considered**
Doing it manually but that will start to get annoying quite fast when you have to install OS on multiple computers.

**Additional context**
I found solution in this article https://answers.microsoft.com/en-us/windows/forum/all/print-management-for-windows-11/e7fd45f0-ab9a-4b68-9142-ec18d7fd0da3 in response from RobinsonSilvestre

**Comment by Marterich** [comment]
Interesting. Do you know what version you installed? I just checked in my 23H2 VM where I definitely never touched anything regarding Print Management but the console opens without any problems using Win+R >  printmanagement.msc

**Comment by krystofkrticka** [comment]
I'll have a look in standard ISO from Microsoft instead of ISO built using a UUPDump.

**Comment by Marterich** [comment]
As this seems not to be directly related to winutil, I'm going to close the issue. If you manage to isolate the issue and link it to winutil, please reopen the issue and we will be happy to help you :) 
/close
