### ISSUE TITLE
Option to disable windows defender

### ISSUE THREAD

**Issue by Aadniz** [ChrisTitusTech/winutil#219]
Windows keeps deleting files I need, and it has become harder and harder to disable windows defender.
I was wondering if you would like to add an option for disabling windows defender?

This can be done by adding some registry keys and modifying gpedit.msc:

### Registry
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender` → `DisableAntiSpyware` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender` → `DisableRealtimeMonitoring` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender` → `DisableRoutinelyTakingAction` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender` → `DisableAntiVirus` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender` → `DisableSpecialRunningModes` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender` → `ServiceKeepAlive` (DWORD, value `0`)

Create new key `Signature Updates`
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Signature Updates` → `ForceUpdateFromMU` (DWORD, value `0`)

Create new key `Real-Time Protection`
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection` → `DisableRealtimeMonitoring` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection` → `DisableOnAccessProtection` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection` → `DisableBehaviorMonitoring` (DWORD, value `1`)
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection` → `DisableScanOnRealtimeEnable` (DWORD, value `1`)

Create new key `Spynet`
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet` → `DisableBlockAtFirstSeen` (DWORD, value `1`)

### gpedit.msc

`Computer Configuration` → `Administrative Templates` → `Windows Components` → `Windows Defender`, and enable `Turn off Windows Defender`

Reference: https://www.maketecheasier.com/permanently-disable-windows-defender-windows-10/

---

Maybe some of the challanges for adding this button would be that windows defender itself would start seeing the winutil as a virus

**Comment by padsalatushal** [comment]
I am working on this. I found that System needs to be in safe mode to uninstall Windows Defender. chris if it is okay then I will work on this. Please give me confirmation for me to work on these features and provide some suggestions if you have any.

**Comment by ChrisTitusTech** [comment]
@padsalatushal wait on this. I'm about to revamp the entire code from @DeveloperDurp to runspaces. 

I'm about to do a massive commit and grab PR #67

**Comment by za-87** [comment]
is it similar to this?
https://github.com/qtkite/defender-control

**Comment by couleurm** [comment]
Would be preferable to have it locked behind a few "Are you sure?!" `MessageBox.Show`'s .. 🤣🤣

**Comment by DeveloperDurp** [comment]
Maybe something like this lol
![image](https://user-images.githubusercontent.com/74198206/204097410-c54d6890-d72b-4cd8-84c1-231b2a601886.png)
![image](https://user-images.githubusercontent.com/74198206/204097439-31232cb9-7250-4c43-ad48-9cc6514fb1b0.png)

**Comment by ChrisTitusTech** [comment]
@DeveloperDurp LOL Love this!
