### ISSUE TITLE
contradictory option hibernation

### ISSUE THREAD

**Issue by schlusy** [ChrisTitusTech/winutil#2198]
**Describe the solution you'd like**
imho, those 2 options should exclude each other. Both activated seems "wrong" for me

**Describe alternatives you've considered**
auto-deactivate contradictory option

![grafik](https://github.com/ChrisTitusTech/winutil/assets/147703815/f9ad387f-3ab7-46b8-a0b9-dabc2c9aebc4)

**Comment by schlusy** [comment]
if you choose to "Disable Hibernation" after choosing "Set Hibernation as default", it might not do things as users intend to do.

**Comment by MyDrift-user** [comment]
If I looked at it correctly it does following things:
- They do not do the same thing, they both edit a registry element, but not the same.
- The script attached alwell does not do the same thing.
- The enable/disable hybernation "overrides" the functionality of the "set as default" tweak.

The two tweaks are not both set for the standard preset, which is good.

But i understand that it looks and feels wrong.

Additional logics outside the executing script to manage that only one of them can be checked at the time would not make sense.

What we could do is making the "set as default" tweak a toggle under preferences.
That would not remove the functionality would stay predefinable, confustion could still be there tho..

**Comment by Real-MullaC** [comment]
Hello, It will be sorted in #2226.
