### ISSUE TITLE
Leftover entries in "Installed apps" section after Edge removal via Microwin

### ISSUE THREAD

**Issue by George-Markas** [ChrisTitusTech/winutil#2202]
**Describe the bug**
Removing Edge via Microwin when making an ISO leaves edge-related entries in the "Installed apps" section of settings.

**To Reproduce**
1. In Microwin, select an ISO file to modify
2. Have the "Keep Edge" option unchecked
3. Proceed normally with generating the new ISO file.

**Expected behavior**
When installing Windows from the generated ISO file, no traces of edge are left.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/76913822/21c67262-43aa-4869-a9ce-46146ad73181)

**Additional context**
I found this visual discrepancy can be resolved by deleting the following registry entries:
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge Update
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\MicrosoftEdgeWebview

While I am not confident enough to make a PR, maybe something like the following could work:

```powershell
# delete problematic registry keys
try {
	Remove-ItemProperty -Path "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge" -Recurse -Force
} catch {
	Write-Host "Error while deleting the following key: $_"
}

try {
	Remove-ItemProperty -Path "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge Update" -Recurse -Force
} catch {
	Write-Host "Error while deleting the following key: $_"
} 

try {
	Remove-ItemProperty -Path "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\MicrosoftEdgeWebview" -Recurse -Force
} catch {
	Write-Host "Error while deleting the following key: $_"
}
```

**Comment by Real-MullaC** [comment]
@CodingWonders
