### ISSUE TITLE
Win 11: Keep `WLAN Autoconfig` set to autostart

### ISSUE THREAD

**Issue by tukusejssirs** [ChrisTitusTech/winutil#2228]
**Describe the bug**

I have used your script and set the service to `manual` mode. However, after a system reboot, the built-in WiFi adapter (and possibly also the LAN adapter) was disconnected.

I have solved this by starting the `WLAN AutoConfog` service and setting it to auto-start.

While I haven’t tested it (as the laptop does not have an ethernet connector), I presume the LAN network was disconnected too which presumably is started by `Wired AutoConfig`.

**To Reproduce**

1. Run your tool
2. Enable the option to set all services to manual start.
3. Reboot.
4. In the systray, you cannot find the WiFi toggle.

**Expected behavior**

**Screenshots**

WiFi/LAN adapters to be available, thus `WLAN Autoconfig`/`Wired Autoconfig` need to be auto started.

**Additional context**

This happened after a fresh installation of Win 11 Home.

**Comment by tukusejssirs** [comment]
This is a bug.

/cc @ChrisTitusTech

**Comment by Real-MullaC** [comment]
Hello @tukusejssirs,

WinUtil does not change anything to do with internet. This project is open-source so feel free to look in the file [here](./config/tweaks.json) between lines 164 and 1582 it keeps the original value of the services for the internet. As it only changes services that are set as Automatic to Manual (if they are safe to be changed).

If this helps please close this issue if not then please let me know.

**Comment by MyDrift-user** [comment]
Since there is no mention of "AutoConfig" in the entire repo we can't say that it is because of WinUtil, since noone else seemed to have the issue and you could solve it for yourself I am going to close this issue now :)

/close
