### ISSUE TITLE
Adding Cursor to WinUtil

### ISSUE THREAD

**Issue by AllanM84** [ChrisTitusTech/winutil#2234]
You seem to use Cursor in most of your streams for coding WinUtil and Linux Toolbox on YouTube videos I watch on either Titus Tech Talk or Chris Titus Tech, so it might be good to include this in the package.

I'm referring to the GitHub link below
https://github.com/getcursor/cursor or https://www.cursor.com/ or https://cursor.sh/.

**Comment by MyDrift-user** [comment]
Hey @AllanM84, Thanks for the Suggestion.
As far as I've seen, there sadly isn't a working Winget-, nor a available Chocolatey package for the Cursor editor, meaning it can't be installed the way WinUtil installs applications.

**Comment by AllanM84** [comment]
@MyDrift-user Thanks for the heads up.

**Comment by AllanM84** [comment]
I just looked at UniGETUI (formerly WinGetUI), and it shows it could be installed via Winget. (See screenshot below)
![image](https://github.com/ChrisTitusTech/winutil/assets/118641007/42d9825e-37c0-444f-bbd8-5958f6e7f84e)

**Comment by MyDrift-user** [comment]
I tried installing it, thats why I wrote "sadly isn't a working Wingetpackage". I tried it on multiple machines on multiple networks, so I thaught It was a broken package. Does it work for you if you install it like that?

**Comment by AllanM84** [comment]
@MyDrift-user I tried doing the following command "winget.exe install --id CursorAI,Inc.Cursor --exact --source winget --accept-source-agreements --version "latest" --silent --disable-interactivity  --accept-package-agreements"
![image](https://github.com/ChrisTitusTech/winutil/assets/118641007/ab084e45-3920-44d2-a30b-ed5616382c9d)

**Comment by MyDrift-user** [comment]
Ya it is the Issue of the package, nothing we can do here.
I will close this issue but keep Cursor on lookout to add when it works :)
