### ISSUE TITLE
Blank CMD windows After Booting - MicroWin

### ISSUE THREAD

**Issue by gpstarman** [ChrisTitusTech/winutil#2236]
Whenever I boot Windows, after around a minute three cmd promt windows open and close immediately. Then found out it was **sc.exe**. Which I found as sevice control. I suspect that it happens because, I imported drivers, maybe it did an half complete job IDK.

Please skip to **00:46** on the below video: 
https://github.com/ChrisTitusTech/winutil/assets/143441092/b721e749-3836-4a80-906b-6c0d982e9b89

![Screenshot from 2024-06-30 22-54-52](https://github.com/ChrisTitusTech/winutil/assets/143441092/bd633569-2d6b-43ce-bed5-ddfa9b95ddf2)

I don't know if this is any useful, but just in case:
![Screenshot 2024-06-30 194450](https://github.com/ChrisTitusTech/winutil/assets/143441092/b9311655-1175-4058-9955-ef9e6185b3f5)

 Created Using : MicroWIn - Winutil **( [Release 24.06.18](https://github.com/ChrisTitusTech/winutil/releases/tag/24.06.18) )** 
 
 Based on         :  **Win 11 22H2**
 
 Kept                 : provisioned packages, Appx packages, Defender
 
 Removed         : Edge.
 
 **Imported drivers** from my current Windows ✅ 
 
 Installed Apps : OBS, VLC, Brave, Peazip
 
 **NEVER CONNECTED THIS WINDOWS TO INTERNET. ( MAYBE THAT'S THE CAUSE DUE TO THE NEED OF INITIAL UPDATES )
 DOWNLOADED THOSE APPS AND POSTING THIS fROM LINUX.**

**Comment by SHR1SHAK** [comment]
Can confirm i have the same 2 black CMD screenhttps://github.com/ChrisTitusTech/winutil/assets/55125587/fae7236e-d6af-4cf0-893d-20e876c686b2

**Comment by SHR1SHAK** [comment]
I can confirm this. I also got 2 Blank CMD screen on startup 

https://github.com/ChrisTitusTech/winutil/assets/55125587/39eb1036-fda5-441d-9cbe-700f0b67641e

**Comment by gpstarman** [comment]
@og-mrk Sorry to bug you man. But I'm still not started using my Windows machine because I'm paranoid. I fear that I have to reinstall the OS and install all the applications again and set them up. This is not an issue right? I am clear to go?

**Comment by CodingWonders** [comment]
MicroWin images set some services automatically to Manual. I will try this in a VM to see if I reproduce these issues.

@gpstarman, you can try to do the following to see what is run:

1. **As soon as you see the SC windows**, immediately make a selection in the window. This typically pauses execution until you finished with the selection
2. Open Task Manager and check the "Command line" column ([add it](https://winaero.com/customize-windows-11-task-manager-columns-and-settings/#Add_the_Command_Line_column_to_Task_Manager) if you don't have it)

Once you have the command-line, reply with that.

**Comment by gpstarman** [comment]
> Immediately make a selection in the window.

I'm sorry, can you explain more please. Am I supposed to click the window that appear?

**Comment by gpstarman** [comment]
![Screenshot 2024-07-11 015308](https://github.com/ChrisTitusTech/winutil/assets/143441092/7a9a1f19-253a-47da-af3b-c472a39c0320)
![Screenshot 2024-07-11 020446](https://github.com/ChrisTitusTech/winutil/assets/143441092/3a073c40-6441-4412-bf88-4293e1381a18)

I can only get two of three. It's all overlapping each other and vanishes within a second.

>I suspect that it happens because, I imported drivers
>NEVER CONNECTED THIS WINDOWS TO INTERNET. ( MAYBE THAT'S THE CAUSE DUE TO THE NEED OF INITIAL UPDATES )

May be this is the reason. Because, the OS I used to make the ISO had certain Acer apps (prominently Acer Care Center). And I imported drivers from it. 

![Screenshot from 2024-07-11 02-19-53](https://github.com/ChrisTitusTech/winutil/assets/143441092/ceb19b16-8aef-4fe0-96cd-f3c9706153f2)

So I guess my new OS expects Acer Care Center (because it has drivers) and it does not exist ?

But a driver can start a service?

Also I have also imported NVIDIA Drivers (not by choice). In case, I installed the latest drivers, it will simply rewrite the existing one right? So no problem on that?

**Comment by CodingWonders** [comment]
@gpstarman, it should not, as INF files don't add/start any services (they're just drivers). This may be that Windows is detecting the drivers and adding stuff automatically. Can you check out the setting shown in the screenshot below?

![SystemPropertiesComputerName_sId1NfTCJC](https://github.com/ChrisTitusTech/winutil/assets/101426328/cef025dd-543e-4135-856b-f8801888bbfe)

1. Open `sysdm.cpl`
2. Go to the Hardware tab and click Device Installation Settings

As per the updated drivers, I think it should just work, but I'm not sure.

**Comment by gpstarman** [comment]
![Screenshot 2024-07-11 062008](https://github.com/ChrisTitusTech/winutil/assets/143441092/c4579cd6-9c0e-4eb7-a1f0-ccc46d366fae)
Also apparently, `AcerCCAgentSvis` is Acer **C**are **C**enter and `AcerQAAgentSvis` is Acer **Q**uick **A**ccess. (talking about task manager screenshots). [ so Svis is Service ? ]

**Comment by SHR1SHAK** [comment]
> ![Screenshot 2024-07-11 015308](https://github.com/ChrisTitusTech/winutil/assets/143441092/7a9a1f19-253a-47da-af3b-c472a39c0320)
> ![Screenshot 2024-07-11 020446](https://github.com/ChrisTitusTech/winutil/assets/143441092/3a073c40-6441-4412-bf88-4293e1381a18)
> 
> I can only get two of three. It's all overlapping each other and vanishes within a second.
> 
> >I suspect that it happens because, I imported drivers
> >NEVER CONNECTED THIS WINDOWS TO INTERNET. ( MAYBE THAT'S THE CAUSE DUE TO THE NEED OF INITIAL UPDATES )
> 
> May be this is the reason. Because, the OS I used to make the ISO had certain Acer apps (prominently Acer Care Center). And I imported drivers from it. From the keyborad it looks like @SHR1SHAK also uses an Acer laptop.
> 
> ![Screenshot from 2024-07-11 02-19-53](https://github.com/ChrisTitusTech/winutil/assets/143441092/ceb19b16-8aef-4fe0-96cd-f3c9706153f2)
> 
> So I guess my new OS expects Acer Care Center (because it has drivers) and it does not exist ? 
> 
> But a driver can start a service?
> 
> Also I have also imported NVIDIA Drivers (not by choice) (in 3rd screenshot). In case, I installed the latest drivers, it will simply rewrite the existing one right? So no problem on that?

Yes it is an acer laptop. But i still get these on my desktop as well.

**Comment by CodingWonders** [comment]
@SHR1SHAK, verify the setting shown in [this comment](https://github.com/ChrisTitusTech/winutil/issues/2236#issuecomment-2221590679) and make sure it is set to **No**

**Comment by SHR1SHAK** [comment]
> @SHR1SHAK, verify the setting shown in [this comment](https://github.com/ChrisTitusTech/winutil/issues/2236#issuecomment-2221590679) and make sure it is set to **No**

I always set this to no also I have razer mouse and for some reason razer software (Bloat) will auto download I this is set to yes.

**Comment by gpstarman** [comment]
> @SHR1SHAK, verify the setting shown in [this comment](https://github.com/ChrisTitusTech/winutil/issues/2236#issuecomment-2221590679) and make sure it is set to **No**

So, I have to set ir to **No**?

**Comment by CodingWonders** [comment]
@gpstarman, to avoid that behavior, yes. The driver will still do the basic communication with your hardware

**Comment by SHR1SHAK** [comment]
> > @SHR1SHAK, verify the setting shown in [this comment](https://github.com/ChrisTitusTech/winutil/issues/2236#issuecomment-2221590679) and make sure it is set to **No**
> 
> So, I have to set it to **No**?

Set it to **no**. Because if the setting is on yes, Crosshair, Razer, Logitech, or anything that uses software it will download it when you connect and your PC gets bloated. You can download it manually afterward.

**Comment by gpstarman** [comment]
> @gpstarman, to avoid that behavior, yes. The driver will still do the basic communication with your hardware

@CodingWonders Thank You man. I guess I'm good to go then.

Also I saw in your profile that you contribute to Microwin. So, I have a UX improvement request.

1. It will be really cool to select that what packages are removed, instead of removing everything. (like an option to select)
2. Same thing for Appx packages and provisioned packages. (it removes basic things like codecs)

Sorry If this is an inappropriate place to ask a request, but it's totally up to you guys, in the end of the day you are the one doing the work. So, thanks for that too.

**Comment by gpstarman** [comment]
> > > @SHR1SHAK, verify the setting shown in [this comment](https://github.com/ChrisTitusTech/winutil/issues/2236#issuecomment-2221590679) and make sure it is set to **No**
> > 
> > 
> > So, I have to set it to **No**?
> 
> Set it to **no**. Because if the setting is on yes, Crosshair, Razer, Logitech, or anything that uses software it will download it when you connect and your PC gets bloated. You can download it manually afterward.

Thank you.

**Comment by CodingWonders** [comment]
@gpstarman, you're welcome. Regarding the requests though, I'm more of a WinForms guy and I know next to nothing about WPF and XAML

**Comment by gpstarman** [comment]
> @gpstarman, you're welcome. Regarding the requests though, I'm more of a WinForms guy and I know next to nothing about WPF and XAML, so I can't work on that unfortunately

Fine, I'll raise this as a seperate feature request then.
