### ISSUE TITLE
Icon for WinUtil shortcut

### ISSUE THREAD

**Issue by RuiNtD** [ChrisTitusTech/winutil#2241]
**Is your feature request related to a problem? Please describe.**
The shortcut created by the "Create WinUtil Shortcut" button under Tweaks doesn't have an icon, defaulting to the generic PowerShell icon.

**Describe the solution you'd like**
I've noticed that [there is code to add an icon](https://github.com/ChrisTitusTech/winutil/blob/b47036630c817c07291c1e69a1ea979785a807e6/functions/public/Invoke-WPFShortcut.ps1#L30-L33) if `%TEMP%\cttlogo.png` present, but that path is never written to anywhere in the code, leaving it to default. I'd assume this file path is meant to be written to at some point, but the developers may have forgotten to do so, since they may already have the logo file at that path.

**Describe alternatives you've considered**

**Additional context**

**Comment by og-mrk** [comment]
Thanks for reporting this issue @RuiNtD
Created a PR which fixes this problem, it'll be available in the next stable release once the PR gets merged 👍
