### ISSUE TITLE
MicroWindows error when selecting iso

### ISSUE THREAD

**Issue by gabeminion** [ChrisTitusTech/winutil#2244]
Hi I dont know why but when i select the windows iso i always get this error and it wont initialize 
![image](https://github.com/ChrisTitusTech/winutil/assets/113368421/f090aadb-1638-408a-a296-f15e9aafea18)

**Comment by MyDrift-user** [comment]
"This is NOW winutil's problem, your ISO might be corrupted, or there is a problem on the system"

Did you download a new ISO from Microsoft's Website or use an old one? I would suggest trying to download a new one if not done already and try again with the newest official one available.

**Comment by Real-MullaC** [comment]
#2226

**Comment by gabeminion** [comment]
> "This is NOW winutil's problem, your ISO might be corrupted, or there is a problem on the system"
> 
> Did you download a new ISO from Microsoft's Website or use an old one? I would suggest trying to download a new one if not done already and try again with the newest official one available.

It somehow fixed itself after restarting windows fully I dont know? Different usbs gave same error? Now currently running on MicroWin! Will end thread aswell thanks
