### ISSUE TITLE
Typo in Invoke-WinUtilTaskbarSearch.ps1 script 

### ISSUE THREAD

**Issue by matheustsa** [ChrisTitusTech/winutil#2245]
**Describe the bug**
_.SYNOPSIS_ text is "Enable/Disable Taskbar Widgets"

**Expected behavior**
_.SYNOPSIS_ text should be "Enable/Disable Taskbar Search Button"

**Comment by og-mrk** [comment]
Hello @matheustsa 
I've created a PR ([link to it](https://github.com/ChrisTitusTech/winutil/pull/2275)) which address this issue. Thanks for reporting this issue 😄
