### ISSUE TITLE
opt-out PowerShell telemetry data to Microsoft 

### ISSUE THREAD

**Issue by jorgnord** [ChrisTitusTech/winutil#2248]
PowerShell sends basic telemetry data to Microsoft using Application Insights!

The below URL describes the telemetry collected in PowerShell and how to opt-out:

https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_telemetry?view=powershell-7.4

SOLUTION: 

Create persistent environment variables

https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4#powershell-environment-variables

about_Telemetry

    Open the System Control Panel. ( appwiz.cpl )
    Select System.
    Select Advanced System Settings.
    Go to the Advanced tab.
    Select Environment Variables....

POWERSHELL_TELEMETRY_OPTOUT  = 1

    Make your changes.

**Comment by og-mrk** [comment]
@jorgnord Created a new PR which does this ([here's a link to it](https://github.com/ChrisTitusTech/winutil/pull/2273)). Thanks for suggestion 😄
