### ISSUE TITLE
Need option on Tweaks to remove Nahimic and Avolute from computer please

### ISSUE THREAD

**Issue by betonel** [ChrisTitusTech/winutil#2250]
Please, if there is an option to remove Avolute and Nahimic from the computer. There are some programs that are automatically installed by the armory crate software from asus and even by windows update. From what I've heard, this problem is with Asus and MSI motherboards.
I use DriverStoreExplorer to remove it but it comes back.
![Screenshot_1](https://github.com/ChrisTitusTech/winutil/assets/58993815/2a510a8b-7f7a-4c35-be6b-9803147549fa)

Thank you!

**Comment by og-mrk** [comment]
> Hey @betonel 
> I would suggest the Application "Bulk Crap Uninstaller". (Available in WinUtil)
> With it I was able to uninstall everything I needed. I can't promise that it will uninstall or stay uninstalled but I think it is worth trying out.

@betonel
What've @MyDrift-user suggested, and to make Windows Update only install Security Updates, you can do this by going to the Updates tab in WinUtil, select `Security (Recommended) Settings`.

> [!NOTE]
> The Updates tab currently doesn't work (It's a known problem by now), as Windows ignores _almost_ every change the tweaks make.. meaning you'll have to change the Update Settings on your own by searching online, as the WinUtil contributors try and solve it in the near future.
