### ISSUE TITLE
Low res screen issue

### ISSUE THREAD

**Issue by dragon2611** [ChrisTitusTech/winutil#2252]
Winutil goes off the screen on a low res screen (E.g Steamdeck running windows) making it difficult to use (ended up RDP to the deck) 

**Expected behavior**
Sized approprately for screen and options to scroll, tried right clicking in taskbar to see if there was a maximise option but didn't appear to be

**Comment by dragon2611** [comment]
In that case the top was the bit that was off the screen, did also think to try right-clicking on the taskbar but didn't seem to offer any useful options.

**Comment by blusewill** [comment]
Sorry. It's Not only the top. You can double click everywhere to maximize.
Second the default res for the Winutil is 1280x800.
And I have tried multiple res and it's looks weird and doesn't work greatly.

**Comment by og-mrk** [comment]
Linking this issue to #2226
