### ISSUE TITLE
gpsvc failed  to sign in

### ISSUE THREAD

**Issue by madebyvalco** [ChrisTitusTech/winutil#2254]
I used this tool some time ago and now when I go to log in pc loads and will sit there for around 20 minutes then pop up

![image](https://github.com/ChrisTitusTech/winutil/assets/80554644/f12adbae-35e4-431f-bb1a-50bd5cb6bf4c)

then it signs out and makes me re login and then it loads within minutes. Please tell me a fix its so annoying have to wait 20 minutes for your pc to login.

and no I didn't select something random. I followed one of his guides on how to use it and what you should enable and I did what he said.

**Comment by MyDrift-user** [comment]
### Check Group Policy Client Service
- Press Win + R to open the Run dialog box.
- Type services.msc and press Enter.
- Locate "Group Policy Client" in the list.
- Right-click and select Properties.
- Ensure the Startup type is set to Automatic.
- Click on Start if the service is not running, then Apply and OK.

### UUID
To chech the UUID run following script in **PowerShell** as **Admin**:
```
wmic csproduct get uuid
```

If it is empty or even invalid that might be the issue.

**Comment by madebyvalco** [comment]
I've tried everything the internet, AI, people have said. I've tried even what you said before and also It is on automatic but I can not change the service status and yeah my uuid is good.

**Comment by MyDrift-user** [comment]
Hard to tell what might be causing the issues without knowig what you've done exactly.
It is also not clear if the issues are comming from a Tweak done by Winutil because of the delay that the issue started.

I would try out:
```
sfc /scannow
```
If that does not work:
```
DISM /Online /Cleanup-Image /RestoreHealth
```
If nothing worked:
- Press Win + X and select Event Viewer.
- Look through it and search for something that looks like the Issue you are having.

**Comment by madebyvalco** [comment]
I've already tried all of that. it didn't work.

**Comment by madebyvalco** [comment]
I ran the options the guy suggested on youtube. the real owner of it.
