### ISSUE TITLE
Exe wrapper from christitustech.com is flagged by MS Defender for TrojanDownloader:PowerShell/Ploprolo.gen!A

### ISSUE THREAD

**Issue by kilroywashere17** [ChrisTitusTech/winutil#2255]
Hello,

I downloaded the exe wrapper from christitustech.com to show my support for the utility. Upon downloading the zip, MS Defender flagged the file for the following reason "TrojanDownloader:PowerShell/Ploprolo.gen!A" I'm not knowledgeable enough to understand whether this is a false flag or not, but it's not the most confidence inspiring when downloading software you just paid to show your support for.

Found the same issue referenced here: https://github.com/ChrisTitusTech/website/issues/84 by wolferrine on Jan 21.

Microsoft provided the additional documentation/help link here: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=TrojanDownloader%3APowerShell%2FPloprolo.gen!A&threatid=2147719730

Would be good to hear back or get some official response to this for less experienced users of the utility.

Thanks!

**Comment by kilroywashere17** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/134578021/af075817-3bd1-4abe-9e1d-9d7efe9b1c47)

attached photo to show whats popping up.

**Comment by kilroywashere17** [comment]
I also ran the zip through virustotal.com and got the following results if that's of any use:
![image](https://github.com/ChrisTitusTech/winutil/assets/134578021/1df20053-75cd-4151-a76a-7b9eb1d1bf87)

**Comment by Real-MullaC** [comment]
@ChrisTitusTech

**Comment by Marterich** [comment]
Winutil gets flagged by some security vendors as malware off and on because it contains scripts that modify Windows and also because of the nature of downloading invoking and running the script in memory. Which looks similar to some multi stage malware attacks. 
This is a False Positive
/close
