### ISSUE TITLE
Add a way to remove bloat on the Nvidia drivers and telemetry same as amd drivers

### ISSUE THREAD

**Issue by Nikoskampourakis** [ChrisTitusTech/winutil#2256]
Title: Add Option to Remove Bloatware and Telemetry from Nvidia Drivers Description Currently, Nvidia drivers come bundled with various components and telemetry services that many users may find unnecessary or intrusive. This additional bloat can impact system performance and compromise user privacy. In contrast, AMD drivers provide users with options to remove unwanted features and telemetry, offering a cleaner and more customizable installation process.Feature Request propose adding a feature to the Nvidia driver installation process that allows users to:Selectively Install Components: Provide checkboxes or options during the installation process to choose which components to install, similar to AMD's driver installer.Opt-out of Telemetry: Include a clear and straightforward way to disable all telemetry and data collection, respecting user privacy and complying with privacy regulations.BenefitsImproved System Performance: Reducing unnecessary bloat can lead to better system performance and reduced resource usage.Enhanced Privacy: Allowing users to opt-out of telemetry respects their privacy preferences and enhances trust in Nvidia products.User Control: Providing these options empowers users to customize their installations according to their specific needs and preferences.Examples from AMD drivers offer a streamlined installation experience where users can choose to install only the essential components and have the ability to opt-out of telemetry. This flexibility is highly appreciated by the community and is a valuable feature that Nvidia users would greatly benefit from.ConclusionBy adding these features, Nvidia can improve user satisfaction, performance, and privacy, aligning with industry best practices and user expectations. Thank you for considering this request.

**Comment by MyDrift-user** [comment]
WinUtil offers "NVCleaninstall" under the applications tab. It is an Installer for Nvidia Drivers.

NVCleanstall lets you customize the NVIDIA GeForce Driver package by removing components that you don't need (or want). This not only keeps things tidy, but also lowers disk usage and memory footprint.

Unlike the NVIDIA custom installation, you can unselect packages like "Stereo 3D Glasses", "USB-C", Notebook Optimizations or Telemetry and more from the NVIDIA drivers.

**Comment by Nikoskampourakis** [comment]
Thanks for message but i wish it wasn't a installer i wanted kind of like tweak or something without installing it but thanks

**Comment by TakenMC** [comment]
I recommend using ddu to get rid of anything nvidia then use NVCleaninstall forward

**Comment by MyDrift-user** [comment]
Since the request was resolved i will close this issue now:

/close
