### ISSUE TITLE
nilesoftShel not showing in Install Section

### ISSUE THREAD

**Issue by SHR1SHAK** [ChrisTitusTech/winutil#2260]
**Describe the bug**
App existed inside application.json not found on GUI

**To Reproduce**
1. Go to 'Install'
2. Click on 'Search and search **nilesoft**'
3. Not found

**Expected behavior**
I was looking for nilesoftshel a right-click alternative. Searched on  winutil not found. So I was going to create a PR. But found out Its already listed inside application.json but not showing on GUI.

**Screenshots**
![Screenshot (5)](https://github.com/ChrisTitusTech/winutil/assets/55125587/670f3d1f-14b6-47e1-9cc6-83a6d8003acd)

**Comment by MyDrift-user** [comment]
Thanks @SHR1SHAK 
This is because the "content" is the name used to display it in the utility, in this case "Shell (Expanded Context Menu)".
I will make a PR to make it use it's actual Name.

**Comment by SHR1SHAK** [comment]
Sure
