### ISSUE TITLE
Error while disabling Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater

### ISSUE THREAD

**Issue by jcrmatos** [ChrisTitusTech/winutil#2264]
**Describe the bug**
winutil 24.06.28 shows the following error while trying to disable Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater (part of the error message is in Portuguese because I'm running it in a portuguese Win 11 Pro and you have the translation in the below "Additional context" section):

```
Disabling Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater
WARNING: Unable to set Microsoft\Windows\Application Experience\ProgramDataUpdater due to unhandled exception
WARNING: O sistema não conseguiu localizar o ficheiro especificado.
```

**Additional context**
I run it on a portuguese Windows 11 Pro 23H2 (compilation 22631.3737).
The translation of the portuguese part of the error message is
The system was unable to locate the specified file.

**Comment by og-mrk** [comment]
Hello @jcrmatos & thanks for reporting this issue
I've the exact Windows 11 version (23H2 , Build Number 22631.3737), and this scheduled task is there by default in most newer versions of Windows.. but it looks like it recently got removed.

Further investigation might be needed...

If anyone has the same version (Build Number 22631.3737), or have older ones as well, please comment if you can see or not the `ProgramDataUpdater` task under `\Microsoft\Windows\Application Experience\`. Thanks in advance.

### Screenshots

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/37a4a9e3-2b1b-4352-90e9-2faf7b473647)

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/f5680688-7408-45fa-8151-881b5663af23)

**Comment by 4yman-0** [comment]
>I only have one warning left (that was present in my original message, I didn't notice, line 3 in the full log):

```
Disabling Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater
WARNING: Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater was not Found
```
>But somehow, Disable telemetry shows as enabled when I click Get Installed.

@ArtFlag from #2742

**Comment by ArtFlag** [comment]
Hello everyone,

Any update on this?
