### ISSUE TITLE
Winutil error

### ISSUE THREAD

**Issue by gbaxter1** [ChrisTitusTech/winutil#2268]
I open Terminal as Admin and launch Winutil via irm christitus.com/win | iex(Admin)
Select Get Installed
Select Update All
Receive the following error.
=====Windows Toolbox=====
===========================================
---        Winget is installed          ---
===========================================
Version: v1.8.1791
    - Winget is a release version.
    - Winget is Up to Date
===========================================
---        Winget is installed          ---
===========================================
Version: v1.8.1791
    - Winget is a release version.
    - Winget is Up to Date
PS>TerminatingError(Start-Process): "This command cannot be run due to the error: Unknown error (0xffffffff)."
Start-Process : This command cannot be run due to the error: Unknown error (0xffffffff).
At line:3032 char:29
+ ... etInstall = Start-Process -Verb runas powershell -ArgumentList "-comm ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
Start-Process : This command cannot be run due to the error: Unknown error (0xffffffff).
At line:3032 char:29
+ ... etInstall = Start-Process -Verb runas powershell -ArgumentList "-comm ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

===========================================
--           Updates started            ---
-- You can close this window if desired ---
===========================================
![Winutil](https://github.com/ChrisTitusTech/winutil/assets/174735775/d6a7d21d-8ce0-4216-a571-d6b2890e0c67)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ChrisTitusTech** [comment]
This could be a windows 10 machine running PowerShell 5. I'd go to tweaks and run the switch to Powershell 7 Tweak and relaunch as admin.

**Comment by gbaxter1** [comment]
Hello.
No, I'm still having that same issue.
![Error](https://github.com/user-attachments/assets/ea4241db-7d67-4b9d-a67b-3a682945e195)
