### ISSUE TITLE
IDEA: Discord server

### ISSUE THREAD

**Issue by Real-MullaC** [ChrisTitusTech/winutil#2269]
So the discord server can be used by people to get support for the project and for the contributors and users to be able to talk to each other and give suggestions if they are not sure how to on GitHub. We can also push updates about the project on there. Some downsides to it we will have some trolls on there server but we can easily stop that by having bots and mods in to help keep the server active and safe.

I can also make a custom bot with special commands to allow us to have some fun things in the server.

**Comment by og-mrk** [comment]
Even though there'll be some challenges along the way.. I think this idea could help grow the community and provide instant feedback to users who might be need help.

Also, the downside of using Discord like a Support Service is Searchability, this can be less of a problem with the introduction of Threads inside a Channel and, if we really want to have new questions pop into GitHub Discussions, then we could make a Custom Discord Bot that handle this feature, alongside other commands as well.

In general, I think this's worth a try, and if things go south with no hope at the end.. then we could terminate the Discord Server, and hoping the community will understand the concerns behind such termination.

**Comment by Real-MullaC** [comment]
I will also be more than happy to help set up the discord server with the correct permissions to make sure it is as safe as possible. To make sure nothing bad will happen.

**Comment by MyDrift-user** [comment]
@ChrisTitusTech had a Discord server once, look [here](https://www.reddit.com/r/ChrisTitusTech/comments/1an0wb0/what_happened_to_the_discord_server/)

There was a lot of drama, so it got closed down.

If some people really want it, I think proposing a Server with the right setup, authentication, autorisation, permissions and mods it would have the possibility of gaining Chris's attention, but he wasn't really into it the last time I've heard him talking about it so idk..

**Comment by Real-MullaC** [comment]
> @ChrisTitusTech had a Discord server once, look [here](https://www.reddit.com/r/ChrisTitusTech/comments/1an0wb0/what_happened_to_the_discord_server/)
> 
> 
> 
> There was a lot of drama, so it got closed down.
> 
> 
> 
> I would personally prefer to keep issues on github, to keep track of everything, but I do see advantages of  a discord server.
> 
> 
> 
> If some people really want it, I think proposing a Server with the right setup, authentication, autorisation, permissions, moderators and at first may restrict the possibilities for users, it would have the possibility of gaining Chris's approval, but he wasn't really into it the last time I've heard him talking about it so idk..

I know how to make it properly but have some of the contributors be mods to help the server until we can get actual mods in. Most people struggle to set up their discord server and that is fine. Like I have learnt how to set them up properly now so I can do it for Chris.

**Comment by Marterich** [comment]
Naive idea:
@Real-MullaC 
Simply start setting up a Community Discord as best as you can and make it clear that it isn't officially sanctioned by Chris himself. If it works and Chris decides he wants to take ownership you still can transfer it and if the decides that there shall be none at all, you always have the possibility to pull it down. 
This way the initial burden isn't on Chris himself and I think if it's done well and works well, there won't be any backlash

**Comment by Real-MullaC** [comment]
> Naive idea:
> @Real-MullaC 
> Simply start setting up a Community Discord as best as you can and make it clear that it isn't (yet) officially sanctioned by Chris himself. If it works and Chris decides he wants to take ownership you still can transfer it and if the decides that there shall be none at all, you always have the possibility to pull it down. 
> This way the initial burden isn't on Chris himself and I think if it's done well and works well, there won't be any backlash 

Ok. Do you have discord as I can invite you to the server whilst I am setting it up.

**Comment by Real-MullaC** [comment]
If you are a Contributor to this project feel free to join this server and dm me with proof that you are a contributor then I will give you your role.

**Comment by Real-MullaC** [comment]
@ChrisTitusTech The server is made could you have a look and if possible for it to be official?

**Comment by ChrisTitusTech** [comment]
@Real-MullaC I hate discord. I've tried two servers in the past, but it ends up being drama and I hate it. I'll never make an official one, but if you all want to run it that is cool with me. I don't want mod or admin roles, but just a normal user.

**Comment by ChrisTitusTech** [comment]
Also, when it comes to issues and such be prepared if you want normal users to join they will ping you and that can get annoying. I know GitHub can be annoying to login and verify, but the barrier of entry seems to get rid of a lot of the riff raff... where Discord is full of crazy people in my experience. 
Discord is very much a HELP ME NOW type experience. I don't like it and if the server does become really big I will drop. I don't mind if all the contributors here join, I just don't want to be getting a ping every hour about a bug someone has only for me to copy and paste "Run as Administrator" type solutions.

**Comment by Real-MullaC** [comment]
> Also, when it comes to issues and such be prepared if you want normal users to join they will ping you and that can get annoying. I know GitHub can be annoying to login and verify, but the barrier of entry seems to get rid of a lot of the riff raff... where Discord is full of crazy people in my experience. 
> 
> Discord is very much a HELP ME NOW type experience. I don't like it and if the server does become really big I will drop. I don't mind if all the contributors here join, I just don't want to be getting a ping every hour about a bug someone has only for me to copy and paste "Run as Administrator" type solutions.

If you would like I can make a rule of no pinging Chris Titus or you will be banned. That will stop people from doing it and later today when I get home I will make a custom bot that if someone does ping you they get automatically banned. Or whatever.

**Comment by og-mrk** [comment]
> > Also, when it comes to issues and such be prepared if you want normal users to join they will ping you and that can get annoying. I know GitHub can be annoying to login and verify, but the barrier of entry seems to get rid of a lot of the riff raff... where Discord is full of crazy people in my experience. 
> > 
> > Discord is very much a HELP ME NOW type experience. I don't like it and if the server does become really big I will drop. I don't mind if all the contributors here join, I just don't want to be getting a ping every hour about a bug someone has only for me to copy and paste "Run as Administrator" type solutions.
> 
> If you would like I can make a rule of no pinging Chris Titus or you will be banned. That will stop people from doing it and later today when I get home I will make a custom bot that if someone does ping you they get automatically banned. Or whatever. 

Instead of a rule in a custom role to ban someone for pinging another person, it's better to have a role **_to allow_** for a person to ping someone, like Chris & people with Moderators roles.

This'll force a Ticket System, where people can ping/use the server bot instead to send support tickets to moderators, or to ask for something urgent like in the event of reporting someone who violated the rules of the server.

It'll be a more sensible solution for achieving this goal of, **Do Not ping specific people**, or we'll automatically take action to..

1. Delete the message in question which did the ping, and send a warning to their DM.
2. Suspend your Discord Account for WinUtil Server (can't send any messages) for a X amount of Hours/days/weeks, or get a ban, when a specific amount of warnings have been collected (for example, 3 warnings wi result in a suspension of 2 days, and will be "remembered" by the bot, and if this account does it again.. then they deserve a ban for not).
3. No need to tell people **_Again_** that this server is not made to have Drama in it. It's a place to have good and fun conversations. Each side of the conversion respects one another, and with the goal of growing the community.
  As telling them not to do A thing in multiple places will probably (in my opinion) result in some people going to great lengths to do the disallowed/forbidden things (.. _for whatever reason_), and you could make an argument of 
"Well, if we didn't tell the community not to have drama.. isn't the outcome will be the same if we did tell them? .. so we could mention it the rules this drama thing, right?".. and I guess it's true, some people who'll try to make drama (may be unintentionally) have the excuse of "well.. you didn't tell me _not to_ do this. How would I know this isn't allowed?".. yahh, like it isn't obvious/common sense that drama hurts the community's overall enjoyment, and the use of the server, but it's better to leave them with no silly excuses,  so that backlash from their side won't happen against Moderators being "Too Strict".

Anyhow, @ChrisTitusTech the point I'm making with all of this ( which's the same as, or similar point of @Real-MullaC ), is that this problem of Drama & annoying pinging _can be_ solved, and it's already solved in different discord servers.. we just need to put the time & effort to make it happen.

**Comment by Real-MullaC** [comment]
> > > Also, when it comes to issues and such be prepared if you want normal users to join they will ping you and that can get annoying. I know GitHub can be annoying to login and verify, but the barrier of entry seems to get rid of a lot of the riff raff... where Discord is full of crazy people in my experience. 
> > > 
> > > Discord is very much a HELP ME NOW type experience. I don't like it and if the server does become really big I will drop. I don't mind if all the contributors here join, I just don't want to be getting a ping every hour about a bug someone has only for me to copy and paste "Run as Administrator" type solutions.
> > 
> > If you would like I can make a rule of no pinging Chris Titus or you will be banned. That will stop people from doing it and later today when I get home I will make a custom bot that if someone does ping you they get automatically banned. Or whatever. 
> 
> Instead of a rule in a custom role to ban someone for pinging another person, it's better to have a role **_to allow_** for a person to ping someone, like Chris & people with Moderators roles.
> 
> This'll force a Ticket System, where people can ping/use the server bot instead to send support tickets to moderators, or to ask for something urgent like in the event of reporting someone who violated the rules of the server.
> 
> It'll be a more sensible solution for achieving this goal of, **Do Not ping specific people**, or we'll automatically take action to..
> 
> 1. Delete the message in question which did the ping, and send a warning to their DM.
> 2. Suspend their Discord Account for WinUtil Server (e.g. can't send any messages) for a X amount of Hours/days/weeks, or get a ban when a specific amount of warnings have accumulated (for example, after getting 3 warnings, it'll result in a suspension of 2 days, and will be "remembered" by the bot, and if this account does it again.. then they deserve a ban for not following the rules).
> 
> 
> Also, there is no need to tell people **_Again_** that this server is not made to have drama in it. It's a place to have good and fun conversations. Each side of the conversion respects one another, and with the goal of growing the community.
> 
> As telling them not to do A thing in multiple places will probably (in my opinion) result in some people going to great lengths to do the disallowed/forbidden things (.. _for whatever reason_), and you could make an argument of 
> "Well, if we didn't tell the community not to have drama.. isn't the outcome will be the same if we did tell them? .. so we could mention it the rules this drama thing, right?".. and I guess it's true, some people who'll try to make drama (may be unintentionally) have the excuse of "well.. you didn't tell me _not to_ do this. How would I know this isn't allowed?".. yahh, like it isn't obvious/common sense that drama hurts the community's overall enjoyment, and the use of the server, but it's better to leave them with no silly excuses,  so that backlash from their side won't happen against Moderators being "Too Strict".
> 
> Anyhow, @ChrisTitusTech the point I'm making with all of this ( which's the same as, or similar point of @Real-MullaC ), is that this problem of Drama & annoying pinging _can be_ solved, and it's already solved in different discord servers.. we just need to put the time & effort to make it happen.

I am flying home today but when I am home do us and @MyDrift-user sort things like that out with a ticket system and etc.

**Comment by ChrisTitusTech** [comment]
@og-mrk and @Real-MullaC if you all want to take point and run it that is cool with me. I just don't want to be involved or have any ownership of it. It never ends up well and its best if it is run by the community imo. I can pin the discord server in issues tab if you want WinUtil Discord to be advertised or if you want it contributors only that is up to you. More People = More Time to moderate, so I want to make sure you all understand what you are getting into. 
I really love collaborating with you all and don't want this to burn anyone out.

**Comment by Real-MullaC** [comment]
@og-mrk Can you dm me so we can talk about puishments for the server.

**Comment by Real-MullaC** [comment]
> @og-mrk and @Real-MullaC if you all want to take point and run it that is cool with me. I just don't want to be involved or have any ownership of it. It never ends up well and its best if it is run by the community imo. I can pin the discord server in issues tab if you want WinUtil Discord to be advertised or if you want it contributors only that is up to you. More People = More Time to moderate, so I want to make sure you all understand what you are getting into. I really love collaborating with you all and don't want this to burn anyone out.

Most of it will be done as auto mod.
