### ISSUE TITLE
KDE apps to be listed

### ISSUE THREAD

**Issue by rodrigopedra** [ChrisTitusTech/winutil#227]
- **Okular:** PDF and documents viewer
- **Kate:** text editor
- **Kdenlive:** Video editor
- **KDEConnect:** connect Android, iOS and other computers for file sharing, clipboard sharing, and more
- **digikam:** professional photo management
- **Krita:** digital painting

~~~powershell
winget install --id=KDE.Okular -e
winget install --id=KDE.Kate -e
winget install --id=KDE.Kdenlive -e
winget install --id=KDE.KDEConnect -e
winget install --id=KDE.digikam -e
winget install --id=KDE.Krita -e
~~~

I would also add Kile (LaTeX editor), KDevelop (C/C++ IDE), KDiff3 (file differ), falkon (web browser), and Dolphin (file browser) -- all available as winget packages -- but I guess these are less mainstream. 

**EDIT** Added Krita, as I thought it was already available.

**Comment by ChrisTitusTech** [comment]
Not really a fan of many of these packages even in Linux, but in Windows there is far better alternatives and I'm going to close this request.

**Comment by rodrigopedra** [comment]
@ChrisTitusTech 

Okular recently receiveid an eco friendly certification, due to low energy consumption.

And I am yet to see a better document reader than it.

If I could ask to you to reconsider just one from the list, it would be it.

Thanks in advance

**Comment by rodrigopedra** [comment]
Link to KDE blog post about Okular's energy efficiency certification:

https://eco.kde.org/blog/2022-03-16-press-release-okular-blue-angel/

**Comment by ChrisTitusTech** [comment]
I'll add Okular thanks for the input.

**Comment by rodrigopedra** [comment]
No worries, thanks for revisiting this, and thanks for this tool =)

**Comment by AutomateMyLifee** [comment]
I second adding Okular and KDEConnect. I have yet to see any alternatives to KDEConnect. It is extremely useful for file, clipboard sharing and more. Gives you the Apple-like device continuity but locally and with great device compatibility.

**Comment by ChrisTitusTech** [comment]
Consolidating this to single issue #374
