### ISSUE TITLE
SUGGESTION: Control Menu without Mouse

### ISSUE THREAD

**Issue by MyDrift-user** [ChrisTitusTech/winutil#2276]
**Describe the solution you'd like**
I would like to use WinUtil Without a mouse, meaning using only the keyboard.

It is already kinf of possible, like in following screen recording. 
- you can move thrught the checkboxes with arrow keys, but u can't check them
- The DNS works fine, but u can't escape it without a mouse.
- You can move through some parts of the WinUtil, but some elements keep you there where you are
- Buttons already work fine, but u don't see if you are on it or not, I was able to open the O&O Menu as seen in the vid.
- Tabs work fine using alt + First letter of tab, but u get a Windows sound that would be cool if it could be disabled

Things that have to be done:
- enable/fix moving through entire WinUtil (idk how)
- visualizing better where the user currently is
- Add ability to trigger some stuff that can't be triggered

**Comment by Marterich** [comment]
That's quite a task, especially in the .net WPF world xD
I think selecting the tabs is already possible using alt+I or alt+t for example

Regarding the visual representation of when a field is focused, maybe @og-mrk can add this to his backlog of UI changes (if he's up for it) :D

**Comment by MyDrift-user** [comment]
> Regarding the visual representation of when a field is focused, maybe @og-mrk can add this to his backlog of UI changes (if he's up for it) :D

Thanks @Marterich, learned alot about moving through WPF with keyboard today. It is totally possible to move everywhere and anywhere and check/uncheck anything. I was just to dumb to find out how. The only thing missing now would be a better way of indicating it. 

I will close this issue and mention the visual aspect in #2226

**Comment by og-mrk** [comment]
Linking this issue to #2226 Progress Tracking Issue.
