### ISSUE TITLE
Consider correcting the DNS to a dropdown list. Having the look of a button is misleading.

### ISSUE THREAD

**Issue by jcrmatos** [ChrisTitusTech/winutil#2279]
**Describe the bug**
Consider correcting the DNS to a dropdown list.
Having the look of a button is misleading.
If for any reason a dropdown list is not possible/easy to implement, at least add a tooltip (like there are in the checkboxes of the other options) explaining that it is indeed a list and not a button.
Using winutil 24.06.28.

**Comment by MyDrift-user** [comment]
Hello @jcrmatos , thanks for pointing this out.
We are currently working on redoing the UI for WinUtil. This will be fixed at time.

**Comment by jcrmatos** [comment]
Ok, thanks. Should I close this feature request?
