### ISSUE TITLE
Consider changing some Tweaks from checkboxes to toggles

### ISSUE THREAD

**Issue by jcrmatos** [ChrisTitusTech/winutil#2280]
**Describe the solution you'd like**
Using winutil 24.06.28.
Consider changing some Tweaks from checkboxes to toggles.
It would be great if the options below would allow a toggle:
ConsumerFeatures
Hibernation
Homegroup
Location Tracking
Storage Sense
Teredo
Wifi-Sense
Fullscreen Optimizations
Microsoft Copilot
Intel MM (vPro LMS)
Notification Tray/Calendar

**Comment by MyDrift-user** [comment]
Hey @jcrmatos 

They can all be undone by checking them and pressing the button "Undo Selected Tweaks" If that is what you're conserned with.

**Comment by jcrmatos** [comment]
OK, thanks.

The UI needs some love but I know you're working on it.

Should I close this issue?

**Comment by MyDrift-user** [comment]
I already suggested fixed du/undo buttons that always get shown no matter if how many tweaks/how big the window. A rework is on the way so you may close the issue now if that was the source of the issue.

**Comment by jcrmatos** [comment]
Yes it was. Thanks.
