### ISSUE TITLE
Consider changing "Set Services to Manual" from checkbox to toggle, so that unsetting it, would restore the default startup for the involved services

### ISSUE THREAD

**Issue by jcrmatos** [ChrisTitusTech/winutil#2281]
**Describe the solution you'd like**
Using winutil 24.06.28.
Consider changing "Set Services to Manual" from a checkbox to a toggle, so that unsetting it, would restore the default startup for the involved services.

**Comment by og-mrk** [comment]
@jcrmatos, you can restore the changes made by this tweak by selecting it and clicking the `Undo Tweaks` button.

**Comment by og-mrk** [comment]
> OK, thanks. Does it work the same way for all the Tweaks?

@jcrmatos Yes, it is.

The UI is a bit odd right now (buttons are unclear for new users).. so I'm currently working on changing the UI. You can follow the progress in Progress Tracking Issue https://github.com/ChrisTitusTech/winutil/issues/2226

**Comment by jcrmatos** [comment]
OK, thanks.

Yes, the UI needs some love.
Should I close this issue?

**Comment by og-mrk** [comment]
> OK, thanks.

No problem, I'm glad I could help 😄

> Yes, the UI needs some love.
> Should I close this issue?

I'll keep this suggestion og your into consideration, maybe make WinUtil Tweaks Tab be like O&O Shutup Program, but this isn't really finalized yet.

In general, thanks for sharing these suggestions of yours, @jcrmatos 👍

**Comment by jcrmatos** [comment]
Thanks.
