### ISSUE TITLE
Consider adding the option to activate DoH on the DNS Tweak

### ISSUE THREAD

**Issue by jcrmatos** [ChrisTitusTech/winutil#2283]
**Describe the solution you'd like**
Consider adding the option to activate DoH on the DNS Tweak (at least for those that are recognized by Windows in automatic model, like Google or Cloudflare).

**Comment by Squtzy** [comment]
Was going to add this as a feature request and found this so I am "upvoting" this to hopefully see it added. Sadly my DNS settings in the "regular" settings app is broken and won't let me set DOH or many other things. Tried with some help to make it enable DOH via Powershell but it keeps saying "unencrypted" in the settings app :/

**Comment by Squtzy** [comment]
Bumping this as I'd love to see this be added if possible. Especially with how the DoH/DNS settings page seems to always be bugged for me on W11

**Comment by Squtzy** [comment]
Any info on if this would be possible to add to WinUtil?
