### ISSUE TITLE
(UI/UX QOL Feature) Terminal Output Window/Progress Bar in GUI

### ISSUE THREAD

**Issue by DakotaCodes00** [ChrisTitusTech/winutil#2288]
**Is your feature request related to a problem? Please describe.**
Sometimes it's annoying or cumbersom to switch between the gui of the winutil script and then the powershell window to check on the progress of the operation selected especially on lower resolution monitors where the gui takes over and you have to alt-tab to switch. This is a really minor thing so I don't really see this being incorportated anytime soon, it's just an idea :)

**Describe the solution you'd like**
It would be nice to have an integrated powershell window as part of the gui to track the output of the utility. I am no Powershell expert so I do not have any idea if this is even feasable in any way, just thought it might be an elegant solution or even a progress bar instead of a powershell console window. Because the average user won't care to read the output logs but they do care that the script is working.

**Additional context**
I couldn't find a good image for what i was looking for but something like this but obviously not taking over the whole ui just a separate little box or bar at the bottom of the window?
![Untitled](https://github.com/ChrisTitusTech/winutil/assets/42800223/1dcd6806-d720-4683-9a0a-935a76073b2f)

Hope what I am saying makes sense, really appriciate all the work you guys do, love you all and have a great day <3 :D

**Comment by Real-MullaC** [comment]
Hello, We are currently working on redoing the UI for WinUtil. So we will try and get this added to the new UI.

**Comment by SHR1SHAK** [comment]
> Hello, We are currently working on redoing the UI for WinUtil. So we will try and get this added to the new UI.

Hey, @Real-MullaC if you are working on the redesign. You can check my redesign here at discussion: https://github.com/ChrisTitusTech/winutil/discussions/1872 If you like anything fell free take it.

**Comment by DakotaCodes00** [comment]
> > Hello, We are currently working on redoing the UI for WinUtil. So we will try and get this added to the new UI.
> 
> Hey, @Real-MullaC if you are working on the redesign. You can check my redesign here at discussion: https://github.com/ChrisTitusTech/winutil/discussions/1872 If you like anything fell free take it.

looks really nice :)
I haven't used figma personally but is it possible to export your design into xml or is that not how figma works XD
