### ISSUE TITLE
Add a Tweak to Make Windows Photo Viewer the Default Photo Viewer for Windows 10/11

### ISSUE THREAD

**Issue by ahmednasser293** [ChrisTitusTech/winutil#2294]
Restore the good old Windows Photo Viewer as the default app to open images.
You can refer to this: https://www.tenforums.com/tutorials/14312-restore-windows-photo-viewer-windows-10-a.html
Please add a tweak in the utility to automate the Windows Photo Viewer restoration process explained in the link above.

**Comment by meenbeese** [comment]
Why would you want to make an app that was deprecated 10 years ago with the release of Windows 10 as the default app to open images? Yes, you can add it using a registry tweak, but I don't see any value in adding this to WinUtil as an official tweak alongside things that _actually_ debloat and improve your PC. Just do the tweak on your own machine or use a FOSS application if you don't like the new Photos application.

**Comment by ahmednasser293** [comment]
> Why would you want to make an app that was deprecated 10 years ago with the release of Windows 10 as the default app to open images? Yes, you can add it using a registry tweak, but I don't see any value in adding this to WinUtil as an official tweak alongside things that _actually_ debloat and improve your PC. Just do the tweak on your own machine or use a FOSS application if you don't like the new Photos application.

I already did it on my PC. I just think it would be cool if it was included in the utility for others to use if they want.

**Comment by TakenMC** [comment]
I mean if you want a usable image viewer I use image glass personally and it automatically sets all file associations if you want to
