### ISSUE TITLE
Possible Typo in Install-WinUtilProgramChoco.ps1

### ISSUE THREAD

**Issue by marsanthe** [ChrisTitusTech/winutil#2296]
## Possible Typo
In Line 88
`[86]    # Cleanup leftovers files`
`[87]    if(Test-Path -Path $installOutputFilePath){ Remove-Item -Path $installOutputFilePath }`
`[88]    if(Test-Path -Path $installOutputFilePath){ Remove-Item -Path $uninstallOutputFilePath }`

## Expected
`[86]    # Cleanup leftovers files`
`[87]    if(Test-Path -Path $installOutputFilePath){ Remove-Item -Path $installOutputFilePath }`
`[88]    if(Test-Path -Path $uninstallOutputFilePath){ Remove-Item -Path $uninstallOutputFilePath }`

**Comment by Real-MullaC** [comment]
There is no difference. Could you please let us know what you think the typo is.

**Comment by marsanthe** [comment]
Line 88 should be

if(Test-Path -Path $**UN**installOutputFilePath){ Remove-Item -Path $uninstallOutputFilePath }

and not

if(Test-Path -Path $**in**stallOutputFilePath){ Remove-Item -Path $uninstallOutputFilePath }

**Comment by Real-MullaC** [comment]
Ok I will get this fixed. Thanks for reporting this issue. 

@og-mrk @MyDrift-user @Marterich
