### ISSUE TITLE
[FR] Add option to Disable All Notifications

### ISSUE THREAD

**Issue by stavros-k** [ChrisTitusTech/winutil#23]
**Is your feature request related to a problem? Please describe.**
I deploy some machines that boot up to only play a video.
Sometimes I forget to disable notifications, and they pop up from time to time.

**Describe the solution you'd like**
It would be good to have an option to disable them all easily 

**Describe alternatives you've considered**

**Additional context**

**Comment by UdaySriHarsha** [comment]
![gpedit.msc](https://user-images.githubusercontent.com/104245375/176875111-7786cc92-eb52-4d28-8b51-dc530b863c80.png)
Enable the policy ''Remove Notifications and Action Center''

Hope it helps

**Comment by UdaySriHarsha** [comment]
> > ![gpedit.msc](https://user-images.githubusercontent.com/104245375/176875111-7786cc92-eb52-4d28-8b51-dc530b863c80.png) Enable the policy ''Remove Notifications and Action Center''
> > Hope it helps
> 
> Hey, Thanks for the reply.
> 
> Is it supposed to still show as enabled in the settings menu? ![image](https://user-images.githubusercontent.com/47820033/179493546-f8147981-8c9a-4e64-8625-e3bd111ac731.png)
> 
> ![image](https://user-images.githubusercontent.com/47820033/179493610-647fa867-ada3-4e5d-8f47-19e48f531c98.png)

I think that stays like that, and it's only a workaround, because some apps will use their own notification system, so can't stop them via gpedit,

2nd option is to use regedit[Warning] it's not usually recommended method but just in case
![IMG_20220724_080445](https://user-images.githubusercontent.com/104245375/180629742-eefbaffa-1b46-4865-815c-d9eb6757f992.jpg)

**Comment by stavros-k** [comment]
@UdaySriHarsha  Thanks. I'll give it a try on couple tests machines, see how it goes!

**Comment by ChrisTitusTech** [comment]
I love this functionality. I'll definitely look at adding it.

**Comment by ChrisTitusTech** [comment]
Added in #240 - Closing Issue
