### ISSUE TITLE
'Updates' tab changes

### ISSUE THREAD

**Issue by Yros** [ChrisTitusTech/winutil#230]
Hello,

The 'Updates' tab allows only [Default] [Security] [Disabled] options but it feels a bit restrictive and the [Security] option is quite a matter of personal preference. Instead of it, wouldn't it be possible to just plainly add the following possibility? :

"Delaying feature updates by:" [x] [days/weeks/month] _(0 = default | -1 = disable feature updates entirely)_
"Delaying security updates by:" [x] [days/weeks/month] _(0 = default | -1 = disable security updates entirely)_

That way, each user can just set it up according to their own preferences. _(Personally, 2 years delay for features update is too long, I'd rather make it 6 or 12 months at which point it is relatively stable for example)._

Thanks.

**Comment by VioletGiraffe** [comment]
I second this, and I would also like the option to disable automatic download and installation, but allow updating manually without restrictions (there's a group policy for that).

**Comment by ChrisTitusTech** [comment]
Agreed, thanks for the feedback
