### ISSUE TITLE
white frame when moving window

### ISSUE THREAD

**Issue by konascape** [ChrisTitusTech/winutil#2306]
**Describe the bug**
When I try to move a window, a white frame appears, I looked in the settings but did not find the item responsible for disabling it

**To Reproduce**
1. Go to Windows 11 24H2 26100.1000
2. Click on window header
3. Move it

**Expected behavior**
the window just moves, no frames or anything else

**Screenshots**
![Снимок экрана 2024-07-09 050355](https://github.com/ChrisTitusTech/winutil/assets/86124328/53b5044c-4d45-4ec4-8f08-881662cd37fe)

**Comment by Marterich** [comment]
The responsible tweak is "Set Display for Performance". Simply undo it and all will be back to normal.
If you want to selectively enable this feature follow the following guide to re enable it manually but keep the rest of the settings of this tweak active. https://www.tenforums.com/tutorials/27449-turn-off-show-window-contents-while-dragging-windows-10-a.html
