### ISSUE TITLE
Powershell 7 shortcut

### ISSUE THREAD

**Issue by ooFVenomous** [ChrisTitusTech/winutil#2308]
**Describe the bug**
When using the "Create WinUtil shortcut tweak, creates a Powershell 5 shortcut instead of Powershell 7
**To Reproduce**
1. Go to 'Tweaks'
2. Click on 'Create WinUtil shortcut'
3. Save shortcut
4. Run shortcut
5. See error

**Expected behavior**
Powershell 7 shortcut created instead of Powershell 5

**Additional context**
Recently installed Powershell 7.4.3
Win 10 Home, 22H2, 19045.4529
Probably important but when running the "Replace the default Powershell 5 to Powershell 7" tweak, I get the error of "Settings file not found"

**Comment by ooFVenomous** [comment]
Hey @Marterich thank you for fixing this so quickly. I was wondering if you have the correct shortcut property because I tried going to your changes and copying it but that didn't work for me.

**Comment by Marterich** [comment]
Maybe you missed a quote or something...
If you want to fix your shortcut manually, open the properties and copy and paste the following content into the "Target" field of the shortcut or create a new one. 
```
pwsh.exe -ExecutionPolicy Bypass -Command "Start-Process pwsh.exe -verb runas -ArgumentList '-Command "irm https://christitus.com/win | iex"'
```

**Comment by ooFVenomous** [comment]
Thank you. It was odd because it was some error about **-ExecutionPolicy** not being recognized or something.
