### ISSUE TITLE
'Tweaks' informations

### ISSUE THREAD

**Issue by Yros** [ChrisTitusTech/winutil#231]
Hello,

The tweaks offered can be quite 'foreign' for most users who won't understand what each of them is for. Perhaps adding a description or a tooltip to fix that and properly explain what things like 'Wifi-sense' or 'Storage Sense' are for example might be helpful?

Thanks.

**Comment by ChrisTitusTech** [comment]
Added Tooltips to all Tweaks. Live on test after commit e0700bda0394c892e2b29558dac2c35cbc758ac4
