### ISSUE TITLE
Running Desktop Tweaks - Windows search not searching

### ISSUE THREAD

**Issue by Tjiffels** [ChrisTitusTech/winutil#232]
When running the scripts on the tweaks screen, my windows search does not search apps anymore. Like searching for Steam, Discord, etc. brings back no results i.r.t the searched criteria Results does appear, but it seems to only be folders etc. I have not yet established if this happens with new apps installed after the script was ran or before.

I tried by reindexing the search items but did not solve the issue. I tried setting the windows search service back to automatic startup but this did not solve it either.

**Comment by flauschxger** [comment]
But how to fix it? Do I just reinstall Cortana? I tried to undo tweaks, but that didn't work.
