### ISSUE TITLE
Prelease Button Theme bug

### ISSUE THREAD

**Issue by SHR1SHAK** [ChrisTitusTech/winutil#2323]
I was checking the new Pre-release 24.07.08 with new GUI updates by @og-mrk and found this GUI issues. Hope you will look into it
![image](https://github.com/ChrisTitusTech/winutil/assets/55125587/d5be2ee2-9034-48ec-8b58-6af043a9b046)
![image](https://github.com/ChrisTitusTech/winutil/assets/55125587/53d98662-176a-4697-9119-67aef6e2119c)
![image](https://github.com/ChrisTitusTech/winutil/assets/55125587/b8861a54-d2d1-44c5-bbd7-662e94a6ddfc)

**Comment by SHR1SHAK** [comment]
Borders are not defined or being clipped by others

**Comment by Real-MullaC** [comment]
Hello @SHR1SHAK,

Thank you for reporting this bug. This will be fixed in the next UI release in a couple of days.

**Comment by SHR1SHAK** [comment]
Glad to be of any help.
