### ISSUE TITLE
Microwin couldn't remove some packages

### ISSUE THREAD

**Issue by quan1232004** [ChrisTitusTech/winutil#2333]
**Describe the bug**
I see there is some packages that couldn't be removed, I don't know if that's bad or not

**To Reproduce**
Untick all options in Microwin, include drivers from this computer

**Expected behavior**
Works normally

**Screenshots**
Full log here

    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T
C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
Invoking WPFGetIso
         _                     __    __  _
  /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __
 /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \
/ /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |
\/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|
oscdimg.exe on system: False
[INFO] oscdimg.exe SHA-256 Hash: AB9E161049D293B544961BFDF2D61244ADE79376D6423DF4F60BF9B147D3C78D
Hashes match. File is verified.
oscdimg.exe was successfully downloaded from github
File path D:\Win11_23H2_English_x64v2.iso
You have enough space for this operation.
Mounting Iso. Please wait.
Done mounting Iso MSFT_DiskImage (ImagePath = "D:\Win11_23H2_English_x64v2.iso", StorageType = 1)
Iso mounted to 'G'
Setting up mount dir and scratch dirs
Mounting Iso. Please wait.
Done setting up mount dir and scratch dirs
Scratch dir is C:\Users\CONQUE~1\AppData\Local\Temp\MicrowinScratch_20240711_195143_9441
Image dir is C:\Users\CONQUE~1\AppData\Local\Temp\Microwin_20240711_195143_9441
Copying Windows image. This will take awhile, please don't use UI or cancel this step!
Copy 1031(s) from G: to C:\Users\CONQUE~1\AppData\Local\Temp\Microwin_20240711_195143_9441
Copy complete! Total Time: 0m22s
Getting image information C:\Users\CONQUE~1\AppData\Local\Temp\Microwin_20240711_195143_9441\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '6 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************
Check the UI for further steps!!!
Target ISO location: D:\w11x64debloated.iso
Index chosen: '6' from 6 : Windows 11 Pro
Mounting Windows image. This may take a while.
Mounting complete! Performing removal of applications...
Exporting drivers from active installation...

Deployment Image Servicing and Management tool
Version: 10.0.22621.2792

Image Version: 10.0.22631.3737

Exporting 1 of 35 - oem0.inf: The driver package successfully exported.
Exporting 2 of 35 - oem1.inf: The driver package successfully exported.
Exporting 3 of 35 - oem11.inf: The driver package successfully exported.
Exporting 4 of 35 - oem12.inf: The driver package successfully exported.
Exporting 5 of 35 - oem13.inf: The driver package successfully exported.
Exporting 6 of 35 - oem14.inf: The driver package successfully exported.
Exporting 7 of 35 - oem15.inf: The driver package successfully exported.
Exporting 8 of 35 - oem16.inf: The driver package successfully exported.
Exporting 9 of 35 - oem17.inf: The driver package successfully exported.
Exporting 10 of 35 - oem18.inf: The driver package successfully exported.
Exporting 11 of 35 - oem19.inf: The driver package successfully exported.
Exporting 12 of 35 - oem2.inf: The driver package successfully exported.
Exporting 13 of 35 - oem20.inf: The driver package successfully exported.
Exporting 14 of 35 - oem21.inf: The driver package successfully exported.
Exporting 15 of 35 - oem22.inf: The driver package successfully exported.
Exporting 16 of 35 - oem23.inf: The driver package successfully exported.
Exporting 17 of 35 - oem24.inf: The driver package successfully exported.
Exporting 18 of 35 - oem25.inf: The driver package successfully exported.
Exporting 19 of 35 - oem26.inf: The driver package successfully exported.
Exporting 20 of 35 - oem27.inf: The driver package successfully exported.
Exporting 21 of 35 - oem28.inf: The driver package successfully exported.
Exporting 22 of 35 - oem29.inf: The driver package successfully exported.
Exporting 23 of 35 - oem3.inf: The driver package successfully exported.
Exporting 24 of 35 - oem30.inf: The driver package successfully exported.
Exporting 25 of 35 - oem31.inf: The driver package successfully exported.
Exporting 26 of 35 - oem32.inf: The driver package successfully exported.
Exporting 27 of 35 - oem33.inf: The driver package successfully exported.
Exporting 28 of 35 - oem34.inf: The driver package successfully exported.
Exporting 29 of 35 - oem35.inf: The driver package successfully exported.
Exporting 30 of 35 - oem4.inf: The driver package successfully exported.
Exporting 31 of 35 - oem5.inf: The driver package successfully exported.
Exporting 32 of 35 - oem6.inf: The driver package successfully exported.
Exporting 33 of 35 - oem7.inf: The driver package successfully exported.
Exporting 34 of 35 - oem8.inf: The driver package successfully exported.
Exporting 35 of 35 - oem9.inf: The driver package successfully exported.
The operation completed successfully.
Adding exported drivers...

Deployment Image Servicing and Management tool
Version: 10.0.22621.2792

Image Version: 10.0.22631.2861

Searching for driver packages to install...
Found 35 driver package(s) to install.
Installing 1 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdacpafd.inf_amd64_3b0bcbf4407d2228\amdacpafd.INF: The driver package was successfully installed.
Installing 2 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdacpbt.inf_amd64_f1f6f1d9e5d2f217\amdacpbt.INF: The driver package was successfully installed.
Installing 3 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdacpbus.inf_amd64_2b6b716f5c7b7ae8\amdacpbus.INF: The driver package was successfully installed.
Installing 4 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdacpbusext.inf_amd64_b9fb22437c40358a\amdacpbusext.inf: The driver package was successfully installed.
Installing 5 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdafd.inf_amd64_98939332ba1b458a\amdafd.inf: The driver package was successfully installed.
Installing 6 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdafd.inf_amd64_d3c85f9ffc8f27e3\amdafd.inf: The driver package was successfully installed.
Installing 7 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdfendr.inf_amd64_5f2cd636dbc40dd2\amdfendr.inf: The driver package was successfully installed.
Installing 8 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdgpio2.inf_amd64_222780daa3df6776\amdgpio2.inf: The driver package was successfully installed.
Installing 9 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdgpio2.inf_amd64_b91c87cc025906f2\amdgpio2.inf: The driver package was successfully installed.
Installing 10 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdi2c.inf_amd64_706bbbcbcac4c6b9\amdi2c.inf: The driver package was successfully installed.
Installing 11 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdi2c.inf_amd64_f6502633f1335e76\amdi2c.inf: The driver package was successfully installed.
Installing 12 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdi2stdmafd.inf_amd64_391a0ae2cddac052\amdi2stdmafd.INF: The driver package was successfully installed.
Installing 13 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdmicropep.inf_amd64_0063ba3efd77500b\AmdMicroPEP.inf: The driver package was successfully installed.
Installing 14 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdmicropep.inf_amd64_ba7beaf14fe915f5\amdmicropep.inf: The driver package was successfully installed.
Installing 15 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdocl.inf_amd64_04b22f43fa2af655\amdocl.inf: The driver package was successfully installed.
Installing 16 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdpsp.inf_amd64_9d23ff82facf58a9\amdpsp.inf: The driver package was successfully installed.
Installing 17 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdpsp.inf_amd64_db1b2556e686c32f\amdpsp.inf: The driver package was successfully installed.
Installing 18 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdsafd.inf_amd64_960126269e89c62e\amdsafd.INF: The driver package was successfully installed.
Installing 19 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\amdwin-u0403852.inf_amd64_b5292935f88a8e40\amdwin-u0403852.inf: The driver package was successfully installed.
Installing 20 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\atihdwt6.inf_amd64_5bf3de4243c61001\AtihdWT6.INF: The driver package was successfully installed.
Installing 21 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\hdx_msiext_rtkgen3p1_kd.inf_amd64_45ee9ecebe49dfea\HDX_MsiExt_RTKGen3p1_KD.inf: The driver package was successfully installed.
Installing 22 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\hdxacpmsi.inf_amd64_054956e30ed38ced\HDXACPMSI.inf: The driver package was successfully installed.
Installing 23 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\mtkbtfilter.inf_amd64_7e3b1a172ae227a5\mtkbtfilter.inf: The driver package was successfully installed.
Installing 24 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\mtkwl6ex.inf_amd64_053fbf4ba108f155\mtkwl6ex.inf: The driver package was successfully installed.
Installing 25 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\mtkwl6ex.inf_amd64_d2f12899e1f97662\mtkwl6ex.inf: The driver package was successfully installed.
Installing 26 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\prnms006.inf_amd64_c3bdcb6fc975b614\prnms006.inf: The driver package was successfully installed.
Installing 27 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\prnms009.inf_amd64_3107874c7db0aa5a\prnms009.Inf: The driver package was successfully installed.
Installing 28 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\realtekhsa.inf_amd64_2bcc4a8f6b1e043b\RealtekHSA.inf: The driver package was successfully installed.
Installing 29 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\realtekservice.inf_amd64_0def78d8fd7b6e2b\RealtekService.inf: The driver package was successfully installed.
Installing 30 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\realtekuapo2.inf_amd64_6cd75fc95d49cc2d\RealtekUAPO2.inf: The driver package was successfully installed.
Installing 31 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\rtsuer.inf_amd64_c30a544a83e79288\RtsUer.inf: The driver package was successfully installed.
Installing 32 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\smbusamd.inf_amd64_ce7952c627b44c80\smbusamd.inf: The driver package was successfully installed.
Installing 33 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\smbusamd.inf_amd64_e470528883cc6bc5\SMBUSamd.inf: The driver package was successfully installed.
Installing 34 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\u0403852.inf_amd64_63c1d613d771eff0\U0403852.INF: The driver package was successfully installed.
Installing 35 of 35 - C:\Users\CONQUE~1\AppData\Local\Temp\DRV_EXPORT\wireguard.inf_amd64_bd22474b85ad1b6f\wireguard.inf: The driver package was successfully installed.
The operation completed successfully.
You can re-enable the disabled features at any time, using either Windows Update or the SxS folder in <installation media>\Sources.
Removing features complete!
Removing Appx BloatonalFeature: MSRDC-Infrastructure [Running                                                        ]
Could not remove OS package Microsoft-Windows-FodMetadata-Package~31bf3856ad364e35~amd64~~10.0.22621.1
Could not remove OS package Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.22621.1
Could not remove OS package Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~en-US~11.0.22621.1
Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.2792
Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Microsoft-Windows-Printing-PMCPPC-FoD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Package_for_DotNetRollup_481~31bf3856ad364e35~amd64~~10.0.9206.1
Could not remove OS package Package_for_KB5027397~31bf3856ad364e35~amd64~~22621.2355.1.1
Could not remove OS package Package_for_RollupFix~31bf3856ad364e35~amd64~~22621.2861.1.6
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
Removing Defender
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
Removing Edge
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
Removal complete!
Create unattend.xml
Done Create unattend.xml
Copy unattend.xml file into the ISO
Done Copy unattend.xml
Create FirstRun
Done create FirstRun
Copy FirstRun.ps1 into the ISO
Done copy FirstRun.ps1
Copy link to winutil.ps1 into the ISO
Copy checkinstall.cmd into the ISO
Done copy checkinstall.cmd
Creating a directory that allows to bypass Wifi setup
Loading registry
Disabling Teams
Done disabling Teams
Bypassing system requirements (system image)
Removing Edge icon from taskbar
Edge icon removed from taskbar
Setting all services to start manually
Enabling Local Accounts on OOBE
Disabling Sponsored Apps
Done removing Sponsored Apps
Disabling Reserved Storage
Changing theme to dark. This only works on Activated Windows
Unmounting Registry...
Cleaning up image...
Cleanup complete.
Unmounting image...
Exporting image into C:\Users\CONQUE~1\AppData\Local\Temp\Microwin_20240711_195143_9441\sources\install2.wim
Remove old 'C:\Users\CONQUE~1\AppData\Local\Temp\Microwin_20240711_195143_9441\sources\install.wim' and rename C:\Users\CONQUE~1\AppData\Local\Temp\Microwin_20240711_195143_9441\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image C:\Users\CONQUE~1\AppData\Local\Temp\Microwin_20240711_195143_9441\sources\boot.wim into C:\Users\CONQUE~1\AppData\Local\Temp\MicrowinScratch_20240711_195143_9441
Loading registry...
Bypassing system requirements on the setup image
Unmounting Registry...
Unmounting image...
Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\CONQUE~1\AppData\Local\Temp\oscdimg.exe
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)

Performing Cleanup...
Done. ISO image is located here: D:\w11x64debloated.iso

**Comment by Real-MullaC** [comment]
@CodingWonders

**Comment by CodingWonders** [comment]
This is normal, as they can be permanent (like `FodMetadata`) or superseded by newer versions. The amount of packages that can't be removed is minimal though, as the majority are still removed.
