### ISSUE TITLE
Option to select which package to remove - MicroWin

### ISSUE THREAD

**Issue by gpstarman** [ChrisTitusTech/winutil#2337]
**Is your feature request related to a problem? Please describe.**
1. I can't get to decide which packages to remove when using MicroWin, it just removes what it's programmed to do.
2. This also applies when removing Provision packages and Appx packages, it removes essential items like codecs.

**Describe the solution you'd like**
1. Maybe like a checkbox to select which packages the user want to remove or keep.
2. The number of packages might be a lot to lot of users. So, I propose the idea of having profiles like "Titus' Selection", "Only Remove Telemetry and Keep all Pacakges", "Minimal", "**Custom**".

**Describe alternatives you've considered**
As far as I know, I don't know any other ISO creators that let's do this. So, I don't know.

**Comment by Real-MullaC** [comment]
#2226

**Comment by gpstarman** [comment]
So, this feature got added to 'to-do list' ?
