### ISSUE TITLE
Clicking on "Upgrade Installs" opens a full screen PowerShell window

### ISSUE THREAD

**Issue by cyberjunkie-android** [ChrisTitusTech/winutil#235]
On the install tab, when you click on the "Upgrade Installs" button it opens a full screen PowerShell window. The window doesn't need to be full screen, it can mimic the size of the the Windows Utility screen.

I'm always having to resize the window.

**Comment by ChrisTitusTech** [comment]
Agreed. After looking at the run process I am going to push it all back into the console window. I find it annoying that it is pulling up new windows everytime. 
Commit 7ac8be910ec6d63743d193adbed4ac5219eab81c
