### ISSUE TITLE
ERROR: The parameter is incorrect. - MicroWin

### ISSUE THREAD

**Issue by e1ysion** [ChrisTitusTech/winutil#2351]
**Describe the bug**
I get the following errors when trying to create the ISO

Invoke-WPFMicrowin : An unexpected error occurred: The request is not supported.                                        At line:3117 char:24                                                                                                    +         "WPFMicrowin" {Invoke-WPFMicrowin}
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin

Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.

**To Reproduce**
Downloaded the latest available ISO from Microsoft
Left everything on default and created 2 folders in C: - "microwin" for ISO and "scratchdir" for scratch.

**Here the log (error in lower section). Should I be worried?**

  /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __
 /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \
/ /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |
\/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|                                                                      oscdimg.exe on system: True                                                                                             File path C:\Win11_23H2_EnglishInternational_x64v2.iso                                                                  You have enough space for this operation.                                                                               Mounting Iso. Please wait.                                                                                              Done mounting Iso MSFT_DiskImage (ImagePath = "C:\Win11_23H2_EnglishInternational_x64v..., StorageType = 1)             Iso mounted to 'F'                                                                                                      Deleting temporary files from previous run. Please wait...                                                              Setting up mount dir and scratch dirs                                                                                   Mounting Iso. Please wait.                                                                                              Done setting up mount dir and scratch dirs
Scratch dir is C:\scratchdir\Scrach
Image dir is C:\scratchdir\micro
Copying Windows image. This will take awhile, please don't use UI or cancel this step!
Copy 1030(s) from F: to C:\scratchdir\micro
Copy complete! Total Time: 0m8s
Getting image information C:\scratchdir\micro\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '6 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************                                                                                       Check the UI for further steps!!!                                                                                       Target ISO location: C:\microwin\microwin.iso                                                                           Index chosen: '6' from 6 : Windows 11 Pro                                                                               Mounting Windows image. This may take a while.                                                                          Mounting complete! Performing removal of applications...                                                                Remove Features from the image                                                                                          You can re-enable the disabled features at any time, using either Windows Update or the SxS folder in <installation media>\Sources.                                                                                                             Removing features complete!                                                                                             Removing Appx Bloat                                                                                                     Invoke-WPFMicrowin : An unexpected error occurred: The request is not supported.                                        At line:3117 char:24                                                                                                    +         "WPFMicrowin" {Invoke-WPFMicrowin}
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin

Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.
Unmounting image...
Exporting image into C:\scratchdir\micro\sources\install2.wim
Remove old 'C:\scratchdir\micro\sources\install.wim' and rename C:\scratchdir\micro\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image C:\scratchdir\micro\sources\boot.wim into C:\scratchdir\Scrach
Loading registry...
Bypassing system requirements on the setup image
Unmounting Registry...
Unmounting image...
Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\Ereny\AppData\Local\Temp\oscdimg.exe
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)

Performing Cleanup...
Done. ISO image is located here: C:\microwin\microwin.iso

**Comment by CodingWonders** [comment]
Can you try doing these operations with the dev version (`irm https://christitus.com/windev | iex`) so that the exact issue can be revealed?

I think that it is a problem while getting the OS packages

**Comment by e1ysion** [comment]
> Can you try doing these operations with the dev version (`irm https://christitus.com/windev | iex`) so that the exact issue can be revealed?
> 
> I think that it is a problem while getting the OS packages

Hey, so I used the dev version, as requested and here is the output:

         _                     __    __  _
  /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __
 /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \
/ /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |                                                                      \/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|                                                                      oscdimg.exe on system: True                                                                                             File path C:\Win11_23H2_EnglishInternational_x64v2.iso                                                                  You have enough space for this operation.                                                                               Mounting Iso. Please wait.                                                                                              Done mounting Iso MSFT_DiskImage (ImagePath = "C:\Win11_23H2_EnglishInternational_x64v..., StorageType = 1)             Iso mounted to 'E'                                                                                                      Setting up mount dir and scratch dirs                                                                                   Mounting Iso. Please wait.                                                                                              Done setting up mount dir and scratch dirs
Scratch dir is C:\scratchdir\Scrach
Image dir is C:\scratchdir\micro
Copying Windows image. This will take awhile, please don't use UI or cancel this step!
Copy 1030(s) from E: to C:\scratchdir\micro
Copy complete! Total Time: 0m8s
Getting image information C:\scratchdir\micro\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '6 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************                                                                                       Check the UI for further steps!!!                                                                                       Target ISO location: C:\microwin\microwin.iso                                                                           Index chosen: '6' from 6 : Windows 11 Pro                                                                               Mounting Windows image. This may take a while.                                                                          Mounting complete! Performing removal of applications...                                                                Remove Features from the image                                                                                          You can re-enable the disabled features at any time, using either Windows Update or the SxS folder in <installation media>\Sources.                                                                                                             Removing features complete!                                                                                             Removing OS packages                                                                                                    Invoke-WPFMicrowin : An unexpected error occurred: The request is not supported.                                        At line:3290 char:24                                                                                                    +         "WPFMicrowin" {Invoke-WPFMicrowin}
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin

Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.
Unmounting image...
Exporting image into C:\scratchdir\micro\sources\install2.wim
Remove old 'C:\scratchdir\micro\sources\install.wim' and rename C:\scratchdir\micro\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image C:\scratchdir\micro\sources\boot.wim into C:\scratchdir\Scrach
Loading registry...
Bypassing system requirements on the setup image
Unmounting Registry...
Unmounting image...
Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\Ereny\AppData\Local\Temp\oscdimg.exe
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)


Performing Cleanup...
Done. ISO image is located here: C:\microwin\microwin.iso

**Comment by CodingWonders** [comment]
@e1ysion, either wait for the aforementioned pull request to be merged or try again with [my fork](https://github.com/CodingWonders/winutil/tree/microwin-fix-240715) (if you go with the latter, you'll need to compile it)
