### ISSUE TITLE
How can we go back to the restore point we got?

### ISSUE THREAD

**Issue by ErenYanic** [ChrisTitusTech/winutil#2357]
I don't have a problem for now, I just made all the settings and I don't understand how to go back to the restore point if I'm not satisfied. Can you help me with this?

**Comment by Real-MullaC** [comment]
Hello @ErenYanic,

In the search box on the taskbar, type control panel, and then choose it from the list of results

In the Control Panel search box, type recovery.

Select Recovery > Open System Restore.

In the Restore system files and setting box, select Next.

Select the restore point that you want to use in the list of results, and then select Scan for affected programs.

You'll see a list of items that will be deleted if you remove this restore point. If you're OK with the deletions, select Close > Next > Finish.

**Comment by ErenYanic** [comment]
Thanks for reply and for quick response
