### ISSUE TITLE
Windows 11 constantly requesting restart for updates

### ISSUE THREAD

**Issue by initiumx** [ChrisTitusTech/winutil#2358]
![Windows Update image](https://github.com/user-attachments/assets/468b614a-cb4e-4ba0-9177-b34b3a6c1513)

Windows 11 constantly asking for a restart to update after each restart

**To Reproduce**
Start pc, wait for Windows update message.
Run update.
Run Winutil.
Select to uninstall all MS - Edge, Store, OneDrive
Select to disable Copilot
'Restart to install updates' request appears after a minute or so with an update prompt.

**Expected behavior**
That a single restart would update and Winutil would not require a follow up restart.

**Screenshots**
Pic has been added. Screenshot would not appear in the pictures/screenshot folder so a png has been created and added.

**Additional context**
This is the fifth time asking for a restart. I get this issue even if I do not add additional software, update software or choose legacy apps.
I have never had this issue before. This is a new pc build (11 months) and have used Winutil from the start. Prior to the latest MS update the frequency of updates seemed usual, they now appear to be monthly. I do not know if the Winutil Updates option for security settings is working as expected as I have updated MS monthly for the last 3 months.

**Comment by Real-MullaC** [comment]
> ![Windows Update image](https://private-user-images.githubusercontent.com/147930486/348559384-468b614a-cb4e-4ba0-9177-b34b3a6c1513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NzkzNjEsIm5iZiI6MTcyMDk3OTA2MSwicGF0aCI6Ii8xNDc5MzA0ODYvMzQ4NTU5Mzg0LTQ2OGI2MTRhLWNiNGUtNGJhMC05MTc3LWIzNGIzYTZjMTUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxNzQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q0OTI2OWJlOGUwYWQ0OWZkOWU2YzE5N2ZhNzU5NDAzNGYxNzg4MGY3ZWI5MWM0YTEyZDU4YmFhOTU3YjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7QzppS07NiJZcObkdX2KBZOvG2ZMfh82lOFt6PtHXWA)
> 
> Windows 11 constantly asking for a restart to update after each restart
> 
> **To Reproduce** Start pc, wait for Windows update message. Run update. Run Winutil. Select to uninstall all MS - Edge, Store, OneDrive Select to disable Copilot 'Restart to install updates' request appears after a minute or so with an update prompt.
> 
> **Expected behavior** That a single restart would update and Winutil would not require a follow up restart.
> 
> **Screenshots** Pic has been added. Screenshot would not appear in the pictures/screenshot folder so a png has been created and added.
> 
> **Additional context** This is the fifth time asking for a restart. I get this issue even if I do not add additional software, update software or choose legacy apps. I have never had this issue before. This is a new pc build (11 months) and have used Winutil from the start. Prior to the latest MS update the frequency of updates seemed usual, they now appear to be monthly. I do not know if the Winutil Updates option for security settings is working as expected as I have updated MS monthly for the last 3 months.

Currently the Security settings ion WinUtil do not work. We are getting it looked into.

**Comment by Real-MullaC** [comment]
> > ![Windows Update image](https://private-user-images.githubusercontent.com/147930486/348559384-468b614a-cb4e-4ba0-9177-b34b3a6c1513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NzkzNjEsIm5iZiI6MTcyMDk3OTA2MSwicGF0aCI6Ii8xNDc5MzA0ODYvMzQ4NTU5Mzg0LTQ2OGI2MTRhLWNiNGUtNGJhMC05MTc3LWIzNGIzYTZjMTUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxNzQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q0OTI2OWJlOGUwYWQ0OWZkOWU2YzE5N2ZhNzU5NDAzNGYxNzg4MGY3ZWI5MWM0YTEyZDU4YmFhOTU3YjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7QzppS07NiJZcObkdX2KBZOvG2ZMfh82lOFt6PtHXWA)
> > Windows 11 constantly asking for a restart to update after each restart
> > **To Reproduce** Start pc, wait for Windows update message. Run update. Run Winutil. Select to uninstall all MS - Edge, Store, OneDrive Select to disable Copilot 'Restart to install updates' request appears after a minute or so with an update prompt.
> > **Expected behavior** That a single restart would update and Winutil would not require a follow up restart.
> > **Screenshots** Pic has been added. Screenshot would not appear in the pictures/screenshot folder so a png has been created and added.
> > **Additional context** This is the fifth time asking for a restart. I get this issue even if I do not add additional software, update software or choose legacy apps. I have never had this issue before. This is a new pc build (11 months) and have used Winutil from the start. Prior to the latest MS update the frequency of updates seemed usual, they now appear to be monthly. I do not know if the Winutil Updates option for security settings is working as expected as I have updated MS monthly for the last 3 months.
> 
> Currently the Security settings in WinUtil do not work. We are getting it looked into.

**Comment by initiumx** [comment]
Follow up

I have restarted and **not opened/run** Winutil. After approx 3 mins the same restart message has appeared. 

Is there a fix for this as it appears that MS wants to download something in the Cumulative Update and what ever that is seems to be related to my denying them either or all of Edge, Store, OneDrive and Copilot?

**Comment by rlovell3** [comment]
This issue should not be listed as stale. I've experienced this ever since I began using the Win Util tool several months ago.  I am only using the basic tweaks and the middle, "recommended" security settings.  The only fix is to completely open up the Windows updater in Settings, and let it have its way with the machine.  Then, once the restart message stops appearing, go back into the Win Util and reset the security settings to the middle one "Security (Recommended) Settings" and run the tweaks again.  The restart message will not stop appearing without letting windows completely infect the machine once again.
