### ISSUE TITLE
New page for recommended or popular apps

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#2362]
There are over 300 apps on the install page. I can be a bit bewildered about what apps to try out.

I wonder if it is worth adding a new page to indicate which are the top 50 most popular apps, or a list of about 50 recommended apps (if it is appropriate for the programme to express opinions), or maybe both a list of popular apps and a list of recommended apps. These "best" apps can appear both on the long list and the list of "best" apps. 

It may be possible to achieve this on the long list of 300 apps by using highlighting.

**Comment by MyDrift-user** [comment]
Hello @billytwotone 
We are currently reworking the UI/UX of WinUtil, an overhaul of the installation page is planned and somewhat in the designing process, hope that helps :)

**Comment by og-mrk** [comment]
Thanks for the suggestions/ideas @billytwotone
As @MyDrift-user have mentioned, the UI/UX of WinUtil will change for the better, and in the next few months, _the current estimations are_, trying to finish it before October 2024, or at the very least before end of this year.

Linking this issue to #2226
