### ISSUE TITLE
`Remove Microsoft Edge` Is Not Removing Anything

### ISSUE THREAD

**Issue by AvazRakhimov** [ChrisTitusTech/winutil#2368]
Remove Microsoft Edge tweak is **not working** and **doesn't doing anything**.

**Comment by Real-MullaC** [comment]
Hello @AvazRakhimov,

What do you mean by this?

**Comment by AvazRakhimov** [comment]
Hello @Real-MullaC!

I tried removing **Edge** multiple times using **winutil** but it doesn't remove nothing, not even **Edge**.

**Comment by Real-MullaC** [comment]
> Hello @Real-MullaC!
> 
> I tried removing **Edge** multiple times using **winutil** but it doesn't remove nothing, not even **Edge**.

Ok thanks for reporting. I will take a look now for you.

**Comment by AvazRakhimov** [comment]
Hello again, @Real-MullaC.

Did you tested yet?

**Comment by AvazRakhimov** [comment]
Hello again, **@Real-MullaC**!

Any news regarding that script?
