### ISSUE TITLE
Request for the clean manager tool / Demande de l'outil clean manager

### ISSUE THREAD

**Issue by Falcom77** [ChrisTitusTech/winutil#237]
[EN]

Hello,
I tested "winutils" I was very surprised of the efficiency and of the interface and of the speed to which it launches.

In the "Config" interface there are fixed ⇒ "System Corruption Scan" very useful in the critical moments of Windows 
on the other hand, I have not seen the "clean manager" that would be very useful to delete all the temporary files/folders and to save disk space.

============================================

[FR]

Bonjour,
J'ai testé "winutils" j'ai été très surpris de l'efficacité et de l'interface et de la rapidité à laquelle il se lance.

Dans l'interface "Config" sont fixés ⇒ "System Corruption Scan" très utile dans les moments critiques de Windows.
par contre, je n'ai pas vu le "clean manager" qui serait très utile pour supprimer tous les fichiers/dossiers temporaires et gagner de l'espace disque.

**Comment by ChrisTitusTech** [comment]
I'll be expanding this in an upcoming patch.
