### ISSUE TITLE
Acknowledgment of anonymous sponsors

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#2374]
I've tried out at the latest dev version of winutil, and I've seen the new feature that lists usernames of sponsors, but I did not see any anonymous sponsors acknowledged. Are there really no anonymous sponsors? 

Potential new sponsors might wish to be anonymous, and they might not know how use anonymized usernames.  They might be anxious or unwilling to have there usernames published

I suggest that sponsors have a clear option to remain anonymous right from the start of the process of donating, if this is not already in place.

Acknowledging anonymous sponsors in the published list of sponsors would most likely reassure potential sponsors, who wish to remain anonymous. 

The acknowledgment could be very simple by just listing "Anonymous sponsors" or "15 anonymous sponsors" or "anonymous x15"

**Comment by MyDrift-user** [comment]
Hey @billytwotone 

The `JamesIves/github-sponsors-readme-action` does respect the privacy settings of GitHub sponsors. 
If a user sponsors your project anonymously, their information will not be included in the generated README.md file. 

This action retrieves sponsor data from the GitHub API, which adheres to the privacy preferences set by the sponsors themselves. Therefore, any anonymous sponsors should remain undisclosed as intended.

**Comment by ChrisTitusTech** [comment]
Thanks for the feedback @billytwotone. Also any API calls will respect anon sponsors as I do a non-auth read of the sponsors page and parse the sponsors without logging in. So it will only grab public sponsors.

**Comment by billytwotone** [comment]
In which case, it would be truthful to add "Anonymous sponsors are not listed". 
Maybe, at the top or bottom of the list.
