### ISSUE TITLE
`Remove Microsoft Edge` Is Not Removing Anything

### ISSUE THREAD

**Issue by AvazRakhimov** [ChrisTitusTech/winutil#2392]
I tried several times but still nothing was deleted

**Comment by Real-MullaC** [comment]
The maintainer is aware of this and is currently thinking of a solution. This could be fixing it or removing it entirely. Please keep this open and as soon as a release is done to fix this. I will link it here.

**Comment by AvazRakhimov** [comment]
**@Real-MullaC** 
Still no updates?

**Comment by zoicware** [comment]
the original creator @AveYo doesnt seem to be active anymore however ive fixed the edge removal script in this pr
https://github.com/AveYo/fox/pull/51

**Comment by AvazRakhimov** [comment]
Hi, **@zoicware**
Thank you a lot, that script works for me.
