### ISSUE TITLE
Official Windows 11 ISO recognized as "modified" by MicroWin and cannot debloat

### ISSUE THREAD

**Issue by lostprophet** [ChrisTitusTech/winutil#2397]
**Describe the bug**

I have downloaded the official Windows 11 version from Microsoft a few minutes ago. When trying to load it into winutil's Microwin, it says "neither install.wim, nor install.esd exists", and it's "possibly because it's modified".

ISO was downloaded from [Microsoft.com](https://www.microsoft.com/software-download/windows11) (chose Hungarian language). The downloaded ISO is called "Win11_23H2_Hungarian_x64v2.iso", and I'm also using the latest .EXE wrapper of winutil.

I also put the ISO file to a short path (D:).

**Steps to reproduce the behavior:**
1. Go to [Microsoft.com](https://www.microsoft.com/software-download/windows11)
2. Download the latest Windows 11 with Hungarian language.
3. Try to open it in MicroWin by clicking on "Select Windows ISO"

**Expected behavior**
Not see any errors, and would be able to debloat Windows ISO

**Screenshots**
https://github.com/user-attachments/assets/86e37e00-27b1-413e-8863-7f2c5fc149a3

**Comment by CodingWonders** [comment]
I can't reproduce this issue. Can you share the contents of the PowerShell window?

**Comment by lostprophet** [comment]
Just to update you on this:

It seems my antivirus (**Dr. Web Security Space**) was the culprit, even though I thoroughly made sure every security feature was turned off, before even opening up winutil.

After removing it (and moving back to basic Windows Defender), MicroWin works great.
