### ISSUE TITLE
Remove explorer bloat

### ISSUE THREAD

**Issue by litLizard69** [ChrisTitusTech/winutil#2398]
**Is your feature request related to a problem? Please describe.**
A few Windows 11 updates ago Microsoft added "Start" and "Gallery" in the file explorer sidebar. They aren't really useful and waste space. It would be nice to be able to hide them.

**Describe the solution you'd like**
Maybe some registry tweak? As revertable as possible, so no destructive tweak.
I found this on the Microsoft forum (https://answers.microsoft.com/en-us/windows/forum/all/how-to-remove-gallery-folder-from-file-explorer/e065f58f-c752-4acd-a2a5-46438c5b7996): 

> reg delete HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace_41040327\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}

Although deleting is pretty destructive.
I'm not too familiar with developing solutions to these kinds of problems so that's how much I can say.

**Additional context**
![Screenshot 2024-07-18 030541](https://github.com/user-attachments/assets/93eed03a-a7ae-4d31-822d-eeb363b93cc6)

**Comment by MyDrift-user** [comment]
For the gallery this one is a revertable option, by setting it to 1/0:

```
reg add HKEY_CURRENT_USER\Software\Classes\CLSID\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c} /f /v "System.IsPinnedToNameSpaceTree" /t REG_DWORD /d 0x00000000 
```

For the home I found this way (.reg file):

Remove:
```
Windows Registry Editor Version 5.00

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}]
```

Add:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}]
@="CLSID_MSGraphHomeFolder"
```

**Comment by litLizard69** [comment]
@MyDrift-user
Now the question is, if those tweaks are worth it to add into winutil.

**Comment by MyDrift-user** [comment]
Worth adding for sure (my thoughts).

The question is add it as new or add it to an existing one?

**Comment by Marterich** [comment]
I would lean towards creating a new tweak and not adding it into something already there, because the tweaks are already convoluted and unclear enough in regards to what they actually do.
I think we should in general lean towards a 1:1 mapping for tweaks and changes so the user can have granular and simple control which tweaks should be applied or reverted.

**Comment by litLizard69** [comment]
@Marterich I agree with you. Also I would put it in the "Advanced Tweaks" section.

**Comment by MyDrift-user** [comment]
> I would lean towards creating a new tweak and not adding it into something already there, because the tweaks are already convoluted and unclear enough in regards to what they actually do. I think we should in general lean towards a 1:1 mapping for tweaks and changes so the user can have granular and simple control which tweaks should be applied or reverted.

I generally agree, but winutil is currently not designed to have that many tweaks as seen that the applications tab is a bit bloated rn.

**Comment by Marterich** [comment]
Fair, but seeing that winutil will likely only grow in the future, I think we should rather fix or rework the UI like @og-mrk is doing right now instead of compromising the functionality itself.
