### ISSUE TITLE
Delay/Pause Windows Update by Setting Maximum Days Possible. 

### ISSUE THREAD

**Issue by adrianteri** [ChrisTitusTech/winutil#24]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add an option to the Updates section that delays windows update by setting the maximum days possible(Usually a month ~35 days). Add also an undo option next to it that resumes updates immediately(Default behaviour after resuming updates).

This option is currently under **Settings** > **Windows Update** > **Advanced options** > **Pause Updates**. Also documented on this [support page]( https://support.microsoft.com/en-us/windows/manage-updates-in-windows-643e9ea7-3cf6-7da6-a25c-95d4f7f099fe#WindowsVersion=Windows_10) for both Win10 and Win11.

![windows_update_pause_update_options](https://user-images.githubusercontent.com/10687877/168582370-094a5552-e436-4d01-9f26-1e58eb2d0101.PNG)
![windows_update_pause_update_choose_day_pause_until](https://user-images.githubusercontent.com/10687877/168582385-eb1dd520-f157-4de5-92e3-61ff55be94a5.PNG)

### Describe alternatives you've considered

N/A or Don't currently know any other solution.

### Additional context

In the previous [Windows Toolbox](https://github.com/ChrisTitusTech/win10script) and also in this tool there is an option to delay feature updates (Up to 365 days) and only install ones related to security, However, there is **NO** option to delay all windows update for a time frame.

![windows_toolbox_windows_update_options](https://user-images.githubusercontent.com/10687877/168582332-9f8f0f2c-98ec-43c3-99af-1e91b3539328.PNG)

I visualize the option being added below the *Security (Recommended) Settings* and above the *Disable ALL Updates (NOT RECOMMENDED)* options.  
![winutil_updates_section](https://user-images.githubusercontent.com/10687877/168585179-7c4540dd-9bda-47de-b592-c7bf80992d72.PNG)

**Comment by ChrisTitusTech** [comment]
The recommended settings actually do this. I'll relabel it so it makes more sense.

**Comment by adrianteri** [comment]
Sorry @ChrisTitusTech this simply doesn't happen. I'm currently updating several machines after **Patch Tuesday** today and after this I usually run your tool to debloat the system.

Clicking on **Security (Recommended) Settings** does not apply **Pause Updates** under **Advanced Options**. Today is the 18th and I have to manually the maximum day which is  **23rd Oct** ~ 35 days of #Windows not seeking out updates.

**Comment by adrianteri** [comment]
Well that was my original request. I **deliberately** want to avoid auto-updates by **delay-ing** them.

I follow security happenings closely and If there's an emergency before the ~35 days are up I will step in and ensure they are installed.

**Comment by ChrisTitusTech** [comment]
> Well that was my original request. I **deliberately** want to avoid auto-updates by **delay-ing** them.
> 
> I follow security happenings closely and If there's an emergency before the ~35 days are up I will step in and ensure they are installed.

Then just disable all updates and you won't get any. Pause updates is just a bullshit, poorly designed Microsoft feature that shouldn't exist.
