### ISSUE TITLE
Replace Default Powershell 5 to Powershell 7 doesn't work

### ISSUE THREAD

**Issue by DiegcD** [ChrisTitusTech/winutil#2406]
## Describe the bug
Today I tried with dev branch and stable branch, neither works.
I used the tweak to change powershell and it doesn't work, Windows still uses powershell 5 as default. When executing the tweak the powershell status displays:
```
Running Script for WPFTweaksPowershell7
Powershell 7 is already installed.
Settings file not found at C:\Users\Diego\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json
=================================
--     Tweaks are Finished    ---
=================================
```

Dev branch shows
```
Running Script for WPFTweaksPowershell7Tele
Running Script for WPFTweaksPowershell7
Powershell 7 is already installed.
Windows Terminal not installed. Skipping Terminal preference
=================================
--     Tweaks are Finished    ---
=================================

```

## To Reproduce
1. Go to Tweaks Tab
2. Click on Replace Default Powershell 5 to Powershell 7
3. Click on Run Tweaks
4. See Tweaks are Finished message
5. Run powershell again and type $PSVersionTable
6. Shows powershell 5

## Expected behavior
Executing $PSVersionTable should show Powershell 7

## Screenshots
![Captura de pantalla (163)](https://github.com/user-attachments/assets/b1ff904c-1d64-4675-9c2e-81758926eb83)
![Captura de pantalla (164)](https://github.com/user-attachments/assets/e6183457-eaeb-4f22-9765-56aebe29acf5)

## Additional context
Windows 11 23h2 64bits

**Comment by MyDrift-user** [comment]
May I suggest looking if the settings.json exists in one of following directories:

Terminal (stable / general release):
- `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`
Terminal (preview release): - `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json`
Terminal (unpackaged: Scoop, Chocolately, etc): 
- `%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json`

**Comment by DiegcD** [comment]
> The error (from stable) indicates that your settings file is not in the directory the script expects it to be.
> 
> May I suggest looking if the settings.json exists in one of following directories:
> 
> Terminal (stable / general release):
> 
>     * `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json`
>       Terminal (preview release): - `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json`
>       Terminal (unpackaged: Scoop, Chocolately, etc):
> 
>     * `%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json`
> 
> 
> according to [stackoverflow](https://superuser.com/questions/1817570/where-is-windows-terminal-setting-location-json-file-in-windows-10) and [microsoft learn](https://learn.microsoft.com/en-us/windows/terminal/install#settings-json-file)

The file is not there in any of those locations, I don't have those folders.

**Comment by MyDrift-user** [comment]
You seem to have the standard terminal application set to windows console host. Have you uninstalled the terminal?
 Terminal in question: 
![image](https://github.com/user-attachments/assets/fce4cb58-6709-4d50-a87e-17e1b55fb6ce)

**Comment by Marterich** [comment]
The default/required Win11 a Terminal app can be installed via winutil and is called "Windows Terminal" on the application page. Alternatively you have to start "pwsh" instead of "Powershell" to use the Powershell 7.

**Comment by DiegcD** [comment]
> You seem to have the standard terminal application set to windows console host. Have you uninstalled the terminal? Terminal in question: ![image](https://private-user-images.githubusercontent.com/121827219/350294318-fce4cb58-6709-4d50-a87e-17e1b55fb6ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTEyNjUsIm5iZiI6MTcyMTQxMDk2NSwicGF0aCI6Ii8xMjE4MjcyMTkvMzUwMjk0MzE4LWZjZTRjYjU4LTY3MDktNGQ1MC1hODdlLTE3ZTFiNTVmYjZjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNzQyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTA1ZDM5YmU3NWEwNDM4YjFmMmI1OGM0MzIwNmU2OWY0NGFmMmM0NTBhMTBkYjU4ODY1MDZiYTY5NTE1ZTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PQ0egw6SPaF_hzDdRk6kkUTvJYIpYNyBAQsBs6-v6QU)

I did not delete it. My windows iso was created by microwin and i have windows terminal on system32 folder



> The default/required Win11 a Terminal app can be installed via winutil and is called "Windows Terminal" on the application page. Alternatively you have to start "pwsh" instead of "Powershell" to use the Powershell 7.

I have the default terminal on system32

**Comment by Marterich** [comment]
Interesting, I think microwin is the culprit again. Nevertheless, could you try uninstalling, reinstalling the windows terminal app and then rerunning the tweak :) 
Would be nice to know if a clean terminal app installation fixes the problem
