### ISSUE TITLE
NOT Working in INTERNET RESTRICTED COUNTRY :'(

### ISSUE THREAD

**Issue by ZinK0** [ChrisTitusTech/winutil#2408]
This is real good project and I've been using this over 3 years I think. My country has been blocked the internet and can't access the christitus.com domain. Before update I can use with the github project link I think. But don't have that option in this new update. Can you make that happen with the new update or please provide the link for the restricted countries. Thanks.

**Comment by MyDrift-user** [comment]
Hey @ZinK0.

When you go to Known Issues in the ReadMe you will get redirected to the new documentation of WinUtil. There you will find an execution command that should suit your needs. [here](https://christitustech.github.io/winutil/KnownIssues/#:~:text=If%20you%20are%20having%20TLS%201.2%20issues%2C%20or%20are%20having%20trouble%20resolving%20christitus.com/win%20then%20run%20with%20the%20following%20command%3A) the direct link to the section I am referencing.

Hope that helps!

**Comment by ZinK0** [comment]
@MyDrift-user ,

Thanks. It really help me. I forget to check the documentation and only check from the website. That's why I haven't seen. 

Thank you.
