### ISSUE TITLE
Error when trying to execute in PowerShell (Null Value)

### ISSUE THREAD

**Issue by Shinusagi** [ChrisTitusTech/winutil#241]
**Describe the bug**
Error and Warning when executing the script on PowerShell (as Admin and standard user as well)

**To Reproduce**
Only got this in one computer, it simply failed from the start either opening PowerShell as Admin or as a Standard User

**Expected behavior**
PowerShell should download and run the script

**_No program should be needed beforehand, this tool works (or it is supposed to) flawlessly after a fresh clean install
I've already used it before in new installed windows and never got this error.
Please don't spread missinformation, making people to install stuff like Visual Studio or any other stuff_**

**Screenshots**
![image](https://user-images.githubusercontent.com/6443772/194731100-873999b6-b721-42de-939c-da06de65ed49.png)

**Additional context**
Tried on Win10 x64 Bits V21H2 Comp 19044.2075

**Comment by nOmnomNOM3** [comment]
I am having the same issue
W10 21H2 19044.2006

**Comment by Experimento0001** [comment]
This happens because you do not have visual studio installed

**Comment by nOmnomNOM3** [comment]
> This happens because you do not have visual studio installed
I have multiple versions of VS installed

**Comment by liberninja** [comment]
Got the same exact errors over here.

**Comment by Shinusagi** [comment]
No program should be needed beforehand, this tool works (or it is supposed to) flawlessly after a fresh clean install
I've already used it before in new installed windows and never got this error.
Please don't spread missinformation, making people to install stuff like Visual Studio or any other stuff

**Comment by Azzuray** [comment]
Ive just tried it, admin and non admin, , PS Core from Terminal, PSWindows same error as OP . 
W10 21H2 19044.1889

**Comment by Hellements** [comment]
I'm having the same issue here.

**Comment by vadgama-nikz** [comment]
Same error is experienced by me. 

One more query i had, if anybody could help - i previously ran the LAPTOP tweaks for this toolbox and it creates a restore point before it executes any commands, so how do i restore from that restore point ? when i try to restore it for windows, it says No system restore point created.

**Comment by ChrisTitusTech** [comment]
Sorry about that pushed a big commit and had to switch the xaml out of dev mode. 

This is now fixed.

**Comment by liberninja** [comment]
Works great now, thanks Chris!
