### ISSUE TITLE
How do i undo the creative cloud block? [Question]

### ISSUE THREAD

**Issue by Kat-02** [ChrisTitusTech/winutil#2429]
This isn't a bug but more of a question, how do you undo the adobe creative cloud block, i did the block and now i just realised i can't install creative cloud (i'm stupid lol💀)

**Comment by MyDrift-user** [comment]
Hey @Kat-02 
You can select the desired tweak and press on the button "Undo Selected Tweaks" to undo them. 
If you encounter any Issues don't hesitate to report and we will try to help further :)

**Comment by og-mrk** [comment]
@Kat-02 You can reference the docs on how to do this, [here's a link to it](https://christitustech.github.io/winutil/userguide/#tweaks-removal).

**Comment by Kat-02** [comment]
Thx👍
