### ISSUE TITLE
translucentTB won't install

### ISSUE THREAD

**Issue by Hellements** [ChrisTitusTech/winutil#246]
**Describe the bug**
As in the title, translucentTB is not being installed when I click on installation.

**To Reproduce**
1. Go to Install
2. Click on TranslucentTB under Utilities
3. Click on Start Install.
4. Nothing happens

**Expected behavior**
Successful installation.

**Screenshots**

**Additional context**
I guess the package name is wrong, or it doesn't exist on winget.

**Comment by ChrisTitusTech** [comment]
This was fixed in PR #240
