### ISSUE TITLE
Unable to get information about the packages

### ISSUE THREAD

**Issue by e1ysion** [ChrisTitusTech/winutil#2461]
## Describe the bug
Unable to get information about the packages. MicroWin processing will continue, but packages will not be processed  

## To Reproduce
Ran irm "https://christitus.com/windev" | iex as admin in powershell
I leave everything on default on the MicroWin page
Chose a ScratchDir Directory on C:
Downloaded the latest Windows ISO as of today

I get this error:

Check the UI for further steps!!!                                                                                       No ISO is chosen+  C:\scratchdir                                                                                        Target ISO location: C:\Users\Ereny\OneDrive\Desktop\mnicro.iso                                                         Index chosen: '6' from 6 : Windows 11 Pro                                                                               Mounting Windows image. This may take a while.                                                                          Mounting complete! Performing removal of applications...                                                                Remove Features from the image                                                                                          You can re-enable the disabled features at any time, using either Windows Update or the SxS folder in <installation media>\Sources.                                                                                                             Removing features complete!                                                                                             Removing OS packages                                                                                                    Unable to get information about the packages. MicroWin processing will continue, but packages will not be processed     Removing Appx Bloat                           
![Screenshot 2024-07-26 121109](https://github.com/user-attachments/assets/83ce2068-9882-415a-9336-a89af6bf3a7a)

**Comment by e1ysion** [comment]
I assume that this is not a fatal issue, may I proceed with the installation? But would be cool to know which packages got skipped. Any way I can check?

**Comment by e1ysion** [comment]
@CodingWonders Sorry for disturbing you, could you please take a look when you have a minute, many thanks

**Comment by CodingWonders** [comment]
This should not be a bad thing. I added that in as a way to prevent processing from failing, but you should still have a functional image.

**Comment by e1ysion** [comment]
> This should not be a bad thing. I added that in as a way to prevent processing from failing, but you should still have a functional image.

Thank you very much
