### ISSUE TITLE
Disabling widgets function is broken

### ISSUE THREAD

**Issue by AgentPhoenix7** [ChrisTitusTech/winutil#2475]
## Describe the bug
In 'Tweaks' section, if the 'widgets button in taskbar' is disabled, it fails 

## To Reproduce
1. Go to 'Tweaks'
2. Go to 'Customize preferences'
3. Scroll down to 'Widgets Button in Taskbar'
4. Disable this option
5. See error
```
Disabling Taskbar Widgets
Set-ItemProperty:
Line |
2549 |          Set-ItemProperty -Path $Path -Name TaskbarDa -Value $value
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempted to perform an unauthorized operation.
```

## Expected behavior
Should not show any error

## Screenshots
![Screenshot 2024-07-28 195928](https://github.com/user-attachments/assets/98628519-1b36-4471-b8db-6a9a48af89d1)

**Comment by KrazeyKami** [comment]
Reopen this issue? I'm also running into this now when deploying through automation

**Comment by KrazeyKami** [comment]
This works to disable it altogether:
New-Item -Path HKLM:\SOFTWARE\Policies\Microsoft\Dsh -Force
New-itemproperty -Path HKLM:\Software\Policies\Microsoft\Dsh -Name AllowNewsAndInterests -Value "0" -PropertyType Dword -force

**Comment by KrazeyKami** [comment]
> This works to disable it altogether:
> New-Item -Path HKLM:\SOFTWARE\Policies\Microsoft\Dsh -Force
> New-itemproperty -Path HKLM:\Software\Policies\Microsoft\Dsh -Name AllowNewsAndInterests -Value "0" -PropertyType Dword -force

**Comment by KrazeyKami** [comment]
> ## Describe the bug
> In 'Tweaks' section, if the 'widgets button in taskbar' is disabled, it fails
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to 'Tweaks'
> 2. Go to 'Customize preferences'
> 3. Scroll down to 'Widgets Button in Taskbar'
> 4. Disable this option
> 5. See error
> 
> ```
> Disabling Taskbar Widgets
> Set-ItemProperty:
> Line |
> 2549 |          Set-ItemProperty -Path $Path -Name TaskbarDa -Value $value
>      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Attempted to perform an unauthorized operation.
> ```
> 
> ## Expected behavior
> Should not show any error
> 
> ## Screenshots
> ![Screenshot 2024-07-28 195928](https://private-user-images.githubusercontent.com/83820979/352823323-98628519-1b36-4471-b8db-6a9a48af89d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTUxOTAsIm5iZiI6MTcyNDE1NDg5MCwicGF0aCI6Ii84MzgyMDk3OS8zNTI4MjMzMjMtOTg2Mjg1MTktMWIzNi00NDcxLWI4ZGItNmE5YTQ4YWY4OWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExNTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTliMWQxOGIzZGFmOWYwMWU3YzM0Zjg0ZTU4MGI3NzE3OGYyNWIwMWIyZGUyODJmYzRhMjRmYTk5Yzc5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-00GLcYqLVf9CYDeGhzN3y104eyaZfCKcu7u6wOARM)

This works to disable it altogether:
New-Item -Path HKLM:\SOFTWARE\Policies\Microsoft\Dsh -Force
New-itemproperty -Path HKLM:\Software\Policies\Microsoft\Dsh -Name AllowNewsAndInterests -Value "0" -PropertyType Dword -force
