### ISSUE TITLE
I noticed that very few people have used the development version of winutil. 

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#2476]
You may or may not want to encourage more users to use the development version.  If you do, then add feature to download a link to the Dev version, making sure that the icon looks a bit different. Winutil already has a link to download the stable version, so the link for the dev version could be under that one with a warning.

**Comment by Real-MullaC** [comment]
Linking with #2226 for UI

**Comment by billytwotone** [comment]
You may or may not want to encourage more users to use the development version.  If you do, then add feature to download a link to the Dev version, making sure that the icon looks a bit different. Winutil already has a link to download the stable version, so the link for the dev version could be under that one with a warning.
