### ISSUE TITLE
It would be great to have a "My computer" page on winutil

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#2477]
I think that it would make the winutil a lot easier to use if it had a "My computer" page.

The "My computer" page could list only the programs that are on the uses computer, and indicate if they are up to date or not.  Buttons could be selected to update the desired programs. That would be brill, wouldn't it?

The long page of over 300 apps would still be useful for installing extra apps.

I guess that there are also inventive ways to feature the tweaks and settings on the My computer page, but lets see the "My computer" page started first.

**Comment by Real-MullaC** [comment]
Linking to #2226 for UI
