### ISSUE TITLE
Enhance Search Functionality in "Install" Section to Include App Descriptions

### ISSUE THREAD

**Issue by stuckydev** [ChrisTitusTech/winutil#2478]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I search for specific functionalities or keywords related to app descriptions in the "Install" section's search bar, but only get results based on app names. For instance, searching for "firewall" does not show the app "Simplewall," even though its description includes the word.

**Describe the solution you'd like**
I would like the search bar in the "Install" section to display results not only from app names but also from app-description texts. This way, searching for keywords like "firewall" would include apps such as "Simplewall" in the results, making it easier to find relevant applications based on their descriptions.

**Describe alternatives you've considered**
An alternative solution could be to have an advanced search option where users can specifically choose to search within app descriptions. However, integrating the description search into the main search bar would provide a more seamless user experience.

**Additional context**
This feature would greatly enhance the usability of the search function, making it more comprehensive and helpful for users looking for specific functionalities.

**Comment by og-mrk** [comment]
I do like this idea @stuckydev
we could do this (but will need a lot more testing, and a way to index the data.. so the search won't take forever to finish).. plus the use of Tags, as currently the only way to separate apps into "groups" is through App Category (Development, Utilities, etc...), it would be nice to have tags for apps, and additional main category, this way.. users can search apps in different ways and WinUtil will find the results, and display them nicely (this's the goal, which of course isn't implemented yet).

Linking this issue to #2226, Thanks again for the suggestion 😄

**Comment by stuckydev** [comment]
Great idea with Tags, since the number of apps is growing 👍

**Comment by stuckydev** [comment]
@og-mrk i dont see the point of making further feature requests since, if no one has time, its buried in the stale closed issues after 7d.

**Comment by og-mrk** [comment]
> @og-mrk i dont see the point of making further feature requests since, if no one has time, its buried in the stale closed issues after 7d.

Not at all @stuckydev , I personally go over and review issues marked as stale & try to make a solution for some, and the ones linked to UI/UX Issue Ticket I'll be going over and handling each issue(s) on the upcoming Refactoring PRs.

Now.. this gives a good question, which's why do we have such a short duration before closing an issue? (Which's 2 weeks)... before WinUtil had a few frequent contributors, there was really only Chris handling Issues and reviewing PRs, so the GitHub action for closing Issues automatically is made to help maintain the repo, but right now it only acts like a "Hide Issues" thing, which can make some contributors forget about reported issues (as few review these staled issues), and it gives off a "Hay, thanks for reporting, but we won't fix it." Kind of vibe to the community.. so maybe this GitHub action should be reconsidered...

In any case, thanks for pointing this out, mentioning @ChrisTitusTech to see & agree on a good fix. Maybe we could keep it.. but increase its duration to a more reasonable amount (like 3 months or so).
