### ISSUE TITLE
Installed Program box pop up before installing program 

### ISSUE THREAD

**Issue by padsalatushal** [ChrisTitusTech/winutil#248]
**Describe the bug**
Installed program box pop up before completing installting program and also in console output it show installed done before installing

**To Reproduce**
1. Go to Install
2. Select few program to install
3. Click on start install
4. See the pop up before completing install

**Expected behavior**
Box pop up after completing install

**Comment by ChrisTitusTech** [comment]
Fix added to Test.
commit: da6a9e3254f0766b2e633bdbba1e074fda64d4cc
