### ISSUE TITLE
script is being blocked by windows antivirus

### ISSUE THREAD

**Issue by ziadrrr** [ChrisTitusTech/winutil#2484]
## To Reproduce
simply tried to run the script from both the shortcut and command in github

## Expected behavior
the utility would run 

# Screenshots
![image](https://github.com/user-attachments/assets/599f8fcf-0732-4460-9d3e-072e68e012e6)
![image](https://github.com/user-attachments/assets/0eeb30ba-ee38-49b4-950c-62961ba0f063)

## Additional context
i can't restore it the AV simply blocked it with no way to restore it

**Comment by JustHereForUpdates** [comment]
I actually managed to execute the script despite also encountering this error. You just need to be quick enough to allow this false positive Trojan on your device. After that, I was able to load the script without any issues. However, I didn't activate or change anything, but it should work as intended. You could do it the same way I did until the error is fixed. 👍

**Comment by NotYourAverageGamer** [comment]
Interesting... I've run WinUtil on fresh installs on both Win10 Pro & Win11 Pro (admittedly, with modified iso's) in the last 12hrs and have not encountered this.

I'm not sure, but; Is it possible this is something to do with `Set-ExecutionPolicy`? [LINK](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.4)
You can run `Get-ExecutionPolicy` from powershell to check what yours is currently set to. (I use `RemoteSigned` on most of my PC's FWIW)

Also found many reports of McAfee causing this error with other utils, do you have any of their software installed?
(i do see you've mentioned defender, but it doesn't hurt to ask :P )

It looks (to me) like it doesn't like something about `iex`/`Invoke-Expression` (?)

If all else fails, Igor's comment should be a viable workaround in the meantime.

**Comment by tsoruu** [comment]
Yeah, It seems that it's fixed already as I've tried it just now. I've encountered this error and commented on YouTube on Chris's updated winutil video around 2. p.m. UTC about this, which is think someone has deleted the comment. It makes me wonder and concern whether the warning is true or not...

**Comment by Chiramisu** [comment]
I ran this using the `LAUNCH-CTT-WINUTIL.lnk` shortcut created by a clean Windows Install using the [autounattend.xml](https://github.com/memstechtips/UnattendedWinstall/blob/ed150d82d77fc8ecc9e751a0159062d66ce87371/Standard/autounattend.xml#L488C15-L488C112) from @memstechtips, which just executes the same command as this repo documents; i.e. `powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'irm https://christitus.com/win | iex'`.

The odd thing is that when I copy that `.lnk` file to a thumbdrive and plug it into other Windows machines, Windows Security eats it, but when I download the `winutil.ps1` file that the shortcut points to directly from https://christitus.com/win, and scan that, it finds nothing. Same, when I execute the command directly from PowerShell; no warning, just runs. Strange false positive.
