### ISSUE TITLE
Current Development (New Programs, bugs, etc.)

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/winutil#249]
Moving All Issues in development into <https://github.com/users/ChrisTitusTech/projects/1/views/1> Project View! 

See what is currently being worked on and contribute.

**Comment by padsalatushal** [comment]
I really love to contribute more and more in this project. Add as many as possible features and bug. So i can work on it and contribute

**Comment by ostarch** [comment]
![16838195021665026769364382624755](https://github.com/ChrisTitusTech/winutil/assets/92668436/fd66b4e6-7f72-42fe-ab2c-d7339f942a3a)
Updated after running tweaks, stuck in loop, Updating, Undoing and restarting.
