### ISSUE TITLE
Winget Install broken

### ISSUE THREAD

**Issue by MyDrift-user** [ChrisTitusTech/winutil#2492]
## Describe the bug
The winget installation on a new system won't work for me, will always error out and if tried out won't work

## To Reproduce
1. Go to "Install"
2. Click on "install anything"

## Expected behavior
should install winget correctly

## Screenshots
![image](https://github.com/user-attachments/assets/51d93e5c-256c-482e-a7bd-c7d51354f665)

## My Suggestion

I would install choco using:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

then using choco i would do a `choco install winget`, after successfull installation I would uninstall choco and cleanup the stuff it left behind

**Comment by Marterich** [comment]
The chocolatey method is already included in install-winutilchoco.ps1 and _should_ run automatically of the direct approach fails. 
The chocolatey way in the past also produced some errors for me.
