### ISSUE TITLE
Close Discussion Action is Broken

### ISSUE THREAD

**Issue by Marterich** [ChrisTitusTech/winutil#2497]
## The Close Discussion Action seems to be broken. 
There are a few successful action runs in between, but these are mostly PRs that were closed by the owner but not merged correctly. 

Could have something to do with ${{ github.event.pull_request.body }} being replaced by a multiline string 

---
![image](https://github.com/user-attachments/assets/797e73ae-2474-44a6-bcd3-d080974b43bb)
ets/c90981f8-97d7-44a4-a68e-50ec6366bdf3)

**Comment by og-mrk** [comment]
I've looked into this, and temporarily disabled it under a branch in my fork ( [see the commit & full explanation](https://github.com/ChrisTitusTech/winutil/pull/2471/commits/03b21a756ea136320a81064e7c2513a2f7177f91) )
Should be fixed when PR #2471 is finalized. Thanks for reporting/documenting this @Marterich 😄
