### ISSUE TITLE
Improvement to 'Change Windows Terminal default: powershell 5 -> powershell 7'

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#2498]
### Main Idea
Change the Start Menu Button Right Click from PowerShell to Windows Terminal (by default on windows 10, it'll be CMD and you can change it to PowerShell (version 5), but not Windows Terminal through settings app).

So "in a nutshell", have the Right Click Context Menu behave like Windows 11.

### Screenshots
![image](https://github.com/user-attachments/assets/47f23d8f-9e22-4bf5-9468-32fe5e0e166b)
_Windows 11 Start Menu Button_

### Credits
This idea was provided by @Marterich

**Comment by monoterne** [comment]
You just need a 22H2 build of Windows 10 and Windows Terminal installed, huh? 🤔

**Comment by Marterich** [comment]
Seems to be a bit more complicated than anticipated. 
https://github.com/PowerShell/PowerShell/issues/12872

An idea to try to find out how the implementation differs from win10 to win11 would probably be a quite tedious comparison of the registry

**Comment by Kingproone** [comment]
I have used this feature, and my right click menu link is broken for it. win 10 ltsc 21h2.

![Screenshot (1209)](https://github.com/user-attachments/assets/53337e92-0c40-4b3a-944c-88a197236524)

**Comment by fau-zi** [comment]
check this out

https://stackoverflow.com/questions/66447566/how-to-set-powershell-7-as-default-and-remove-other-versions
