### ISSUE TITLE
Programs to Add (Comment Here)

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/winutil#250]
Must be available with WINGET! Check compatibility here: <https://winget.run/>

Currently on List to Add
---
**Processing last list in test branch from all comments below before Nov 9th**

Programs that will NOT be added
---
- Spotify (Issues with installation, because of admin mode needed for elevation.)

**Comment by ChrisTitusTech** [comment]
Added ALL programs through Jdownloader - Test commit 70da725768b1e2e593dc21a9d78fbcbf3a3d2eb9

**Comment by ChrisTitusTech** [comment]
Staged for next update

**Comment by Wingzzzzy** [comment]
Some more list of good Open Source/freeware Software usefull for creative people i dont suspect that all the apps will be added. It just some ideas.

Krita - Art program that is open source. Like Photoshop but for artist.
>winget install -e --id KDE.Krita 

nGlide - 3Dfx Wrapper to make old games run
>winget install -e --id ZeusSoftware.nGlide

Kodi - Frontend for all types of media
>winget install -e --id XBMCFoundation.Kodi

Telegram - A chat app like Signal and WhatsApp
>winget install -e --id Telegram.TelegramDesktop

Unity Hub - A program to help you get any version of Unity.
>winget install -e --id UnityTechnologies.UnityHub

qBittorrent - The best alternative to BitTorrent or uTorrent as its open source and no ads.
>winget install -e --id qBittorrent.qBittorrent

EA app - The new generation of Origin to play EA games that you don't have on steam.
>winget install -e --id ElectronicArts.EADesktop

**Comment by Braastos** [comment]
Classic style Start Menu for Windows 7, 8, 8.1, 10 (it works under win 11 but there are some issues)
> winget install -e --id Open-Shell.Open-Shell-Menu

**Comment by jonfairbanks** [comment]
Can you include WizTree? It is a modern WinDirStat.

> winget install -e --id AntibodySoftware.WizTree

**Comment by ThisNekoGuy** [comment]
Can you please add Bluestacks? (Is available with winget)

**Comment by charettepa** [comment]
SQL Management Studio
`winget install -e --id Microsoft.SQLServerManagementStudio`

Java Runtimes 
`winget install -e --id EclipseAdoptium.Temurin.8.JRE`
`winget install -e --id EclipseAdoptium.Temurin.11.JRE`
`winget install -e --id EclipseAdoptium.Temurin.16.JRE`
`winget install -e --id EclipseAdoptium.Temurin.17.JRE`
`winget install -e --id EclipseAdoptium.Temurin.18.JRE`
`winget install -e --id EclipseAdoptium.Temurin.19.JRE`

**Comment by Dispatch9001** [comment]
What if you just a GUI front end for Winget like [WingetUI](https://github.com/martinet101/WinGetUI) instead of adding every app that people use?

**Comment by ChrisTitusTech** [comment]
Winget UI is on my to do list. See #203  @Dispatch9001 

> What if you just a GUI front end for Winget like [WingetUI](https://github.com/martinet101/WinGetUI) instead of adding every app that people use?

**Comment by Dispatch9001** [comment]
I didn't see that, sorry. It's cool to see that someone had the exact same thought that I did.

**Comment by charettepa** [comment]
Azure Management Studio
`winget install -e --id Microsoft.AzureDataStudio`

**Comment by 555wolfman** [comment]
**mobaXterm** (free) more conveniant than putty

**Comment by charettepa** [comment]
> **mobaXterm** (free) more conveniant than putty
Does  not appear to be available from winget

**Comment by ChrisTitusTech** [comment]
I'm going to expand the tool to include chocolatey as this will expand package seletion

**Comment by charettepa** [comment]
> I'm going to expand the tool to include chocolatey as this will expand package seletion

Since you are adding Chocolatey
I would like to also request 

Spybot
`choco install spybot`

**Comment by HCCIT** [comment]
https://github.com/Romanitho/Winget-AutoUpdate

**Comment by IntoTheVoid-900** [comment]
> https://github.com/Romanitho/Winget-AutoUpdate

This functionality is also in WingetUI.

**Comment by Chimmy2302** [comment]
Maybe something to help with the sound issue in for Kali linux in hyper-v. I've been browsing the web but none seems to work haha, still no sound, even enhanced session is acting weird.
