### ISSUE TITLE
Edge Removal refactoring

### ISSUE THREAD

**Issue by YusufKhalifadev** [ChrisTitusTech/winutil#2502]
**Is your feature request related to a problem? Please describe.**
There have been a lot of users who are not happy with the current edge removal script which is Aveyo's script.
It doesn't fully remove Edge and sometimes it works and sometimes it doesn't.

**Describe the solution you'd like**
As in this issue #2485 a user suggested another solution to remove Edge and here are the steps to do it:
1- In the Windows/System32 Microsoft created a file called IntegratedServicesRegionPolicySet.json open this file
2 - At line 6 there's a comment that says "Edge is uninstallable" Under this comment is the defaultState section change it to enabled.
3 - Now move to the conditions section and region section where Microsoft has put specific countries' locales to uninstall edge (which is most of Europe to be honest) we need to add the "US" locale.
4 - Go to this Registry Key "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Microsoft Edge" and change the value NoRemove to 0 
5 - Now we can remove Edge with a simple Remove-AppxPackage or from the app's settings GUI.
source video: https://www.youtube.com/watch?v=_utrsNxQiR0

**Describe alternatives you've considered**
I've tried to tweak Aveyo's script but it just kept crashing so I looked for alternatives and I found this method

**Additional context**
Hear me out on this,
I don't want to use any external sources to make winutil functional I want to make everything internal like I wanna remove O&O shutup and Oscdimg too I'm not too fond of this because it makes winutil so slow. 
so I think this is doable as a script we can do it, I'm still learning Powershell so in a few days I'll try to add this initially,
thanks for the good work @ChrisTitusTech

**Comment by zoicware** [comment]
ive created a pull request a while back for aveyo but hes not active anymore https://github.com/ChrisTitusTech/winutil/issues/2392#issuecomment-2248194478

**Comment by YusufKhalifadev** [comment]
so i think we should create our own in a better way

**Comment by YusufKhalifadev** [comment]
closing this as it's already fixed by @psyirius
