### ISSUE TITLE
Win11: Text not correctly aligned in search box under `Install -> Search`

### ISSUE THREAD

**Issue by NotYourAverageGamer** [ChrisTitusTech/winutil#2507]
## Describe the bug
Text for the `Search` box in `Install` tab is not correctly aligned with the search box on Windows 11 (Pro) 23H2

## Screenshot
![what-the-search-doin](https://github.com/user-attachments/assets/33a43f4a-74cd-4220-82bf-16f587c0cafc)

**Comment by Real-MullaC** [comment]
Linking with issue - #2226
