### ISSUE TITLE
XboxGipSvc freezes on 'Starting' status

### ISSUE THREAD

**Issue by adolfo-cia** [ChrisTitusTech/winutil#2511]
original closed ticket: https://github.com/ChrisTitusTech/winutil/issues/1733

## Describe the bug
When running the tweaks (desktop), the service XboxGipSvc is set to manual, but the status remains in 'Starting'.
Windows 11.

## To Reproduce
1. Run the tweaks (desktop)
2. Go to Windows Services app
3. Look at 'Xbox Accesory Management Service'

## Expected behavior
The service should be in 'Stopped'

## Additional context
I think the issue is related to the tweaks option 'Disable Telemetry'.
If you revert the changes, that won't work. Only works if you restore with the system restore point.
It also breaks the Xbox app.

**Comment by YusufKhalifadev** [comment]
@adolfo-cia did you restart after the tweaks are done

**Comment by adolfo-cia** [comment]
@YusufKhalifadev yeah man, basic stuff.

**Comment by MyDrift-user** [comment]
@adolfo-cia, thanks for the report, do you use xbox products on your machine?

**Comment by adolfo-cia** [comment]
I see this was closed, but the issue still exists.

@MyDrift-user yes, Xbox app doesn't work. I'm not sure if what's casuing it is XboxGipSvc haning on 'startup' or because of any of the tweaks of the tool.

**Comment by jacket430** [comment]
Can confirm this is very much still an issue, only way to fix it is to do a Windows restore.

**Comment by lostaccesstomygithub** [comment]
bump, same issue here.

**Comment by Barzobius** [comment]
Well, this issue just happened to me. Specifically after using the “Set services to Manual” option on CCT. I tried repairing, resetting all Xbox apps, doing a system restore but the issue stays. The “xboxgipsvc stuck on starting” google search brought me here. I haven’t found a way to fix this :(
