### ISSUE TITLE
cant open the tool

### ISSUE THREAD

**Issue by randomsdsdsk** [ChrisTitusTech/winutil#2519]
When i open the debloater normally it just closes,.
When i open it with powershell there is texts but again it closes.
When i open it as administrator then this happens.
![image](https://github.com/user-attachments/assets/78ac74c1-16d9-4fe0-9bc5-68fad087607e)

**Comment by Real-MullaC** [comment]
Could you send that error in English please?

**Comment by ahmet499** [comment]
![6ad574d8-114a-4e94-9cfb-1e8e11328bcb](https://github.com/user-attachments/assets/8e80abf5-9cf0-442f-b7de-3e7edc56a9da)
this is the related issue

**Comment by NotYourAverageGamer** [comment]
are you trying to directly run `winutil.ps1`? (directory shows ~/Downloads/winutil.ps1)
to run winutil you should:
- Open Terminal or Powershell (as admin)

 then run:

```ps1
irm https://christitus.com/win | iex
```
