### ISSUE TITLE
Edge search bar policies should  be true default. 

### ISSUE THREAD

**Issue by myagizmaktav** [ChrisTitusTech/winutil#2523]
![image](https://github.com/user-attachments/assets/ff33f32e-cfaa-49ad-8f7d-f051564f6d9a)

Ass you see this search  feature is  [SearchSuggestEnabled](https://docs.microsoft.com/DeployEdge/microsoft-edge-policies#searchsuggestenabled) policy and should be true when applying default win util settings.

**Comment by MyDrift-user** [comment]
Hello @myagizmaktav 

I did not understand what you are implying here..

Do you mean that "SearchSuggestEnabled" gets deactivated when applying default selection of winutil tweaks?

**Comment by myagizmaktav** [comment]
> Hello @myagizmaktav, thanks for the report.
> 
> I did not understand what you are trying to suggest. Do you mean that "SearchSuggestEnabled" gets deactivated when applying default selection of winutil tweaks?

Hello yes.
