### ISSUE TITLE
winutil shortcut doesn't open in 24H2

### ISSUE THREAD

**Issue by Jaredy899** [ChrisTitusTech/winutil#2528]
The shortcut opens This PC instead of the winutil in 24H2

**Comment by Real-MullaC** [comment]
> The shortcut opens This PC instead of the winutil in 24H2

This has been fixed in PR #2488. What has been mreged but will take a bit of time to be fully released. But when the pre release comes out you will be able to update your shortcut then.

**Comment by michaeldun123** [comment]
This will probably be done in the

```
irm christitus.com/windev | iex 
```
version when it releases
