### ISSUE TITLE
Unable to run the script 

### ISSUE THREAD

**Issue by AhmadHakmi** [ChrisTitusTech/winutil#2529]
I made sure to open Terminal as admin, copied and pasted the script, but it just doesn't seem to work at all. I have no idea what is wrong exactly.

![Screenshot 2024-08-07 001515](https://github.com/user-attachments/assets/345c61ed-2170-4d20-87fe-8f1509b3e2a5)

**Comment by MyDrift-user** [comment]
same issue as in #1994 

You would probably have to run this before executing the script:

```
$ExecutionContext.SessionState.LanguageMode = "FullLanguage"
```

**Comment by ChrisTitusTech** [comment]
We can probably detect the language and enable this on run in the future. I'm going to add a keep this issue tag to it.

**Comment by ChrisTitusTech** [comment]
Using #1994 for this issue
