### ISSUE TITLE
Restore Microsoft Edge after Removal

### ISSUE THREAD

**Issue by avn2000** [ChrisTitusTech/winutil#253]
**Is your feature request related to a problem? Please describe.**
I've been using the script and is great. I uninstalled Edge from the script that the program has, it uninstalled it and everything was fine, but because of a proyect I need to get it back, I tried reinstalling it form .exe on the official site but it didn't work, it install but it doesn't open

**Describe the solution you'd like**
I would like to have an option to reinstall edge correctly with in the script, because I have no clue and I haven't found a solution on doing it after the removal script

**Describe alternatives you've considered**
Just give a solution on how to return the edge browser

**Comment by elazar4** [comment]
It happened to me too.
I haven't uninstalled Edge, but when I try to open it, it won't open.
Is there a solution?

**Comment by ChrisTitusTech** [comment]
Once uninstall edge is done, you'd have to do a complete system integrity check to get it back. This will install a ton of other stuff too though. 
Go to the config tab and run system corruption scan. This will take a long time to complete and will install any modified system files. 
Only uninstall edge if you are absolutely certain you never want it back.
