### ISSUE TITLE
Unable to find Application

### ISSUE THREAD

**Issue by andrewcollier-com-au** [ChrisTitusTech/winutil#2534]
**Is your feature request related to a problem? Please describe.**
Love the app, went to install an FTP client, searched for 'FTP' and 'ftp', none, I can't believe with all the programs in the winutil not one FTP client exists.

**Describe the solution you'd like**
Keyword search, or search/filter for what the application does and not just its name. 

**Describe alternatives you've considered**
I'll need to figure out how to use ftp in terminal.  

**Additional context**
Thanks for reading post from a ranting noob

**Comment by og-mrk** [comment]
Hello @andrewcollier-com-au 
Thanks for reporting this issue. This issue is similar to issue #2478, where in the previously reference issue ticket, it gives suggestions and details this problem of searching through apps in the `Install` tab.

Linking this issue to #2226
