### ISSUE TITLE
Windows search stopped working after performing the tweaks

### ISSUE THREAD

**Issue by Souchikjoardar1** [ChrisTitusTech/winutil#2541]
Describe the Bug

After applying system tweaks using the Chris Titus Tech Windows 11 Utility Tool, Windows Search has stopped functioning properly. The search bar in the taskbar does not return results, and no items are displayed when searching within File Explorer or the Start menu.
To Reproduce

    Download and run the Chris Titus Tech Windows 11 Utility Tool.
    Select and apply system tweaks from the tool (e.g., disabling telemetry, Cortana, etc.).
    Restart the computer if prompted or necessary.
    Attempt to use the Windows Search function by clicking the search bar on the taskbar or searching within File Explorer.
    Observe that no results are displayed, and the search function appears to be broken.

Expected Behavior

Windows Search should function normally, displaying relevant search results for files, applications, and system settings when a search query is entered.
Screenshots

Additional Context

    The issue began immediately after running the Chris Titus Tech Windows 11 Utility Tool.
    The specific tweaks applied may have included disabling Cortana, telemetry, and/or other privacy-related features.
    Attempts to restart the Windows Search service or rebuild the search index did not resolve the issue.
    This issue may affect other system functionalities that rely on search.

**Comment by MyDrift-user** [comment]
Hello @Souchikjoardar1 

I did just run every tweak available in WinUtil on a Win10 & Win11 Machine to make sure that that is not an usual result of using tweaks on WinUtil.

You may have disabled "Bing Search in Startmenu", which would only disable web results from showing up in the search, but there is currently no tweak that should break the entire search.

To make sure you could try checking the tweaks you ran and clicking on "undo selected" to revert the changes.

**Comment by Souchikjoardar1** [comment]
NO NO I disabled bing search for good (not by mistake) because it was displaying relevant stuff and serving ads and re-enabling it won't fix the windows search function for that I had to perform a windows restore operation to get things up and running once again , I have been a huge follower of Mr Chris but dude this issue needs to be fixed

**Comment by wdebie** [comment]
I'm having the same issue, has a fix for this been found?

**Comment by litaws** [comment]
> I'm having the same issue, has a fix for this been found?
> 
> Edit: I fixed it. Turns out disabling "Let apps run in the background" breaks Windows Search. See [this Stack Exchange comment](https://superuser.com/a/1208858).

me2, cannot locate the fix that was suggested in stack exchange

**Comment by lalishansh** [comment]
I restarted `Windows Search` service (in 'services.msc') and it started working

**Comment by constantine2003** [comment]
Same thing happened to me...

**Comment by francisalcala-accuity** [comment]
This too happened to me

**Comment by BlueStarBRS** [comment]
i have the exatc same issue everytime i use this tool it fucks up my windows search im very anoyed from it i used this tweaks:

<img width="1429" height="901" alt="Image" src="https://github.com/user-attachments/assets/f2d4ed1e-9567-4bb9-9987-c5f611715d47" />

pls fix im blessed by this tool but THIS sucks hard to be real im on windows 10 pro

**Comment by ghost** [comment]
@BlueStarBRS if i run every single tweak in winutil and restart my system ever than my search still works you must be using something like ooshutup to make your search not work

**Comment by BlueStarBRS** [comment]
No I didn't my windows search is completely ripped and I testet it also in
my VM with the same results

It breaks it and also can break it in some case it so hard that I need to
rebuild almost everything from it bc even my settings app cant search
anymore. My guess is the "disable background apps tweak" but I'm not to
100% shurte but it guarantee this tool is causing this problems and I'm not
alone I'm on Windows 10 pro

Gabi ***@***.***> schrieb am Fr., 6. Feb. 2026, 09:29:

**Comment by ghost** [comment]
> No I didn't my windows search is completely ripped and I testet it also in
> my VM with the same results
> 
> It breaks it and also can break it in some case it so hard that I need to
> rebuild almost everything from it bc even my settings app cant search
> anymore. My guess is the "disable background apps tweak" but I'm not to
> 100% shurte but it guarantee this tool is causing this problems and I'm not
> alone I'm on Windows 10 pro
> 
> Gabi ***@***.***> schrieb am Fr., 6. Feb. 2026, 09:29:
> […](#)

well i can't reproduce the problem so it could be user error or windows 10

**Comment by rendition36** [comment]
GPT helped me fixed mine! Hope this helps ppl facing the same problem.
You can access PowerShell by scrolling in the app menu and finding "windows tool" tab. Remember to run PowerShell in admin mode.

🔧 Step 1: Restart key processes

1. Press Ctrl + Shift + Esc to open Task Manager
2. End these tasks:

   * StartMenuExperienceHost.exe
   * SearchHost.exe
   * Windows Explorer
3. Restart Explorer:

   * Click “Run new task” → type explorer.exe

---

🔧 Step 2: Reset Start Menu and Search (most important)
Open PowerShell as Administrator, then run:

Get-AppxPackage Microsoft.Windows.StartMenuExperienceHost | Reset-AppxPackage
Get-AppxPackage Microsoft.Windows.Search | Reset-AppxPackage

---

🔧 Step 3: Rebuild all system apps
Run:

Get-AppxPackage -AllUsers | Foreach {
Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"
}

---

🔧 Step 4: Repair system files
Run:

sfc /scannow

**Comment by nahid6970** [comment]
@rendition36 thanks a lot my startmenu also got broken by using christitus windows utility but ur solution fixed it 😍 i really like ctt tool but dont know why it keeps breaking startmenu!!
