### ISSUE TITLE
"Winutil /tweaks/ create winutil shortcut "   link are not working

### ISSUE THREAD

**Issue by Thundra74** [ChrisTitusTech/winutil#2545]
## Describe the bug
With the latest version of winutil  the function " create  winutil shortcut " in tweak section  dont work as before! The created shortcut do not launch winutil

**Comment by retrojesus** [comment]
I AM HAVING THE SAME ISSUES CANNOT DO THE LINK ANYMORE. FEELS LIKE THEY ARE TRYING TO GET US TO BUY THE EXE

**Comment by ChrisTitusTech** [comment]
> I AM HAVING THE SAME ISSUES CANNOT DO THE LINK ANYMORE. FEELS LIKE THEY ARE TRYING TO GET US TO BUY THE EXE

It's a conspiracy. Those dirty developers always trying to  get our money... 

In all seriousness, this might get removed if it becomes problematic with AntiVirus programs. I've had a lot of false flags and noticed anytime I share a lnk file with people all AV flag the program. 

Either way you can always run the program with powershell, so there is no need to buy the EXE if you don't want to. You can also make your own shortcut with powershell 7 and adding the run command "irm christitus.com/win | iex".

**Comment by genesis224** [comment]
> I AM HAVING THE SAME ISSUES CANNOT DO THE LINK ANYMORE. FEELS LIKE THEY ARE TRYING TO GET US TO BUY THE EXE

weird enough that it works for me until as of now.
![image](https://github.com/user-attachments/assets/e590e310-709c-42eb-978f-cef2d2ff7d04)

**Comment by Thundra74** [comment]
I have already buyed the .exe  (as a Donor because its worth! ) but always use terminal/Pshell because is more easy than searching for damned usb key always lost in the lab
