### ISSUE TITLE
Double clicking in search input passed to window title bar, causes maximise window

### ISSUE THREAD

**Issue by romanr** [ChrisTitusTech/winutil#2547]
## Describe the bug

- [ ] double clicking in search box is interpreted as double clicking on title bar and maximises the window.
- [ ] the search icon obscures text input

**Comment by og-mrk** [comment]
Hello @romanr, and thanks for reporting these issues.

The first one requires more involved work, and it'll be handled when the PRs series for UI Refactoring is done (so far, there hasn't been an official due date.. but my hopes are before the end of this year), you can follow the progress and see other UI related issues in #2226 Issue Ticket.

The second issue on the search icon obstructing text should hopefully be handled by @MyDrift-user 's #2465 PR. If not, then by next UI Refactoring PR.

Linking this issue to #2226 Progress Tracking Issue.
