### ISSUE TITLE
Won't remove Edge

### ISSUE THREAD

**Issue by AstridC42** [ChrisTitusTech/winutil#2548]
## Describe the bug
after choosing the remove edge option, and trying to lunch it, edge come up like nothing, terminal say "A runtime exception occured." and " The remote server returend an error: (202) not found.

## To Reproduce
1. Go to 'tweeks.'
2. Choose  'remove edge'
3. Click apply
5. See error in terminal 

## Expected behavior
I expected that edge no longer be installed on my vm

## Screenshots
![Screenshot_20240807_143603](https://github.com/user-attachments/assets/64c73de0-d74b-468d-b942-fdf425d7260f)

## Additional context
even after reboot, trying the dev branch, make a new install of the vm i'm still unable to remove edge.
i tested this on 3 clean Win10 (last ver) VM and i get this error for the last week (I tried after the last release)

**Comment by TommyCowley101** [comment]
Hello, i had this issue as well and i fixed it by just running the release version of the winutil, you will notice when you just run the release version that the "NOT RECCOMENDED" next to uninstall edge will be gone and then it will work

**Comment by og-mrk** [comment]
Hello @AstridC42 , thanks for reporting this issue.

The edge removal tweak has been refactored recently and will be available in the upcoming week(s).

**Comment by AstridC42** [comment]
Thank you.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
