### ISSUE TITLE
Display Problem.

### ISSUE THREAD

**Issue by Kanishq10** [ChrisTitusTech/winutil#2550]
After using the tool , some times display starts to stutter and also one time it was flickering. I tried to reinstall the intel graphic drivers , but it failed.
I only used tool for disabling the services.

**Comment by Kanishq10** [comment]
![Uploading Screenshot 2024-08-10 205240.png…]()

**Comment by Kanishq10** [comment]
![Screenshot 2024-08-10 205240](https://github.com/user-attachments/assets/9bd3e345-89e9-401f-ab88-de9143085e7e)

**Comment by MyDrift-user** [comment]
Hey @Kanishq10, thanks for reporting.

I suggest selecting the tweak you ran and click on "undo selected", to revert the changes and test it out again.

**Comment by Kanishq10** [comment]
well it worked after restart.
