### ISSUE TITLE
ERROR: boot sector data could not be processed

### ISSUE THREAD

**Issue by dinocaminos44** [ChrisTitusTech/winutil#2557]
now this :(

ERROR: boot sector data could not be processed
OSCDIMG Error Level : 1
Copying target ISO to the USB drive
VERBOSE: Performing the operation "Copy File" on target "Item: D:\windows 11\windows 11 optimizado.iso Destination: H:\windows 11 optimizado.iso".
File copied to Ventoy drive H
Done Copying target ISO to USB drive!
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)
ISO creation failed. The  C:\Users\DINO TRABAJO\AppData\Local\Temp\Microwin_20240812_225935_8715  directory has not been removed.
Reason: Incorrect function

**Comment by johnbarney** [comment]
I hit the same problem. I used C:/tmp for scratch and ISO output on my second try and had no issues. I recommend using a simple and short path until this issue is fixed. I do not know enough PowerShell to make a PR but I'm sure it's an easy fix for somebody who does.

**Comment by CodingWonders** [comment]
Issue closed due to inactivity. /close
