### ISSUE TITLE
Should I work on a a UI redesign? With Electron, Perhaps .net windows forms

### ISSUE THREAD

**Issue by shahriar0247** [ChrisTitusTech/winutil#2570]
I can make really nice UI. I am a Frontend Dev. I can use electron with React and some random framework to make a UI. I can use chatgpt to copy paste the UI code of what is there and tell chatgpt to convert it to react.js, and i modify a little, it is not a big app, i think i can get the first page done within a day. I just donno if people are interested.

**Comment by MyDrift-user** [comment]
Hello @shahriar0247 
Unlike WPF, which is specifically for Windows and can be invoked via PowerShell scripts that is in this case invoked using a short command, Electron apps  need to be compiled from multiple files and distributed as executables with an installer. As far as my experience with electron goes there is not really a portable way like we currently have in WinUtil. What could be possible is downloading a portable packaged application into a temp folder, run it from there and delete it on close, but idk if this is a fitting Idea for this project.
I am not in a position that could make a decision about this, just wanted to give my thoughts.

**Comment by ChrisTitusTech** [comment]
The main issue is this isn't a program, but a script. 

Everything is built live in xaml. I pull a massive string that contains all the GUI elements on run and the interface is created on run. There is no compilation. 

I've had people send me stuff in figma and other design programs, but can't really do anything with it.

**Comment by billytwotone** [comment]
If it can be done, then I think that shahriar0247 has a good idea.
I can not do this sort of coding, though.
Maybe, a branch version is the answer, which could exist along site the script version.
Is there anyone interested in working with User shahriar0247 to make a branch with a new UI?

**Comment by psyirius** [comment]
> I can make really nice UI. I am a Frontend Dev. I can use electron with React and some random framework to make a UI. I can use chatgpt to copy paste the UI code of what is there and tell chatgpt to convert it to react.js, and i modify a little, it is not a big app, i think i can get the first page done within a day. I just donno if people are interested.

Don't take this as an offence, but here are some things that winutil is focused on
- It's a standalone script with no external dependencies.
- It just runs with powershell with some little cs compatible with the powershell clr.
- Powershell only supports windows forms and Xaml (in modern windows) out of the box.
- Frameworks like electron make winutil huge to download and it creates extra complexity to the project.
- The script must be reasonably smaller that an user can download from a PowerShell one-liner and doesn't wait-for long.
- It's most probably ran in a fresh windows install. 

PS: @ChrisTitusTech correct me if i'm wrong and lmk if I missed anything!

**Comment by Marterich** [comment]
I think @psyirius pretty much summed everything up. 
Therefore I'll close this issue as there isn't anything to add and no further action is required 
/close
