### ISSUE TITLE
LICENSE has disappeared from the repository.

### ISSUE THREAD

**Issue by TwilitWave** [ChrisTitusTech/winutil#2571]
## Describe the bug
It's possible I'm mistaken, but I'm pretty certain the LICENSE page used to contain the MIT license, however it now just presents a 404 error.

## To Reproduce
1. Go to 'https://github.com/ChrisTitusTech/winutil/blob/main/LICENSE'
2. See error

## Expected behavior
License for the script should appear.

## Screenshots
![image](https://github.com/user-attachments/assets/d02ab7ed-c9c0-4611-a692-e5a001c0f46b)

## Additional context
Thanks for your time.

**Comment by Real-MullaC** [comment]
It has moved to here - https://github.com/ChrisTitusTech/winutil/blob/main/.github/LICENSE

**Comment by TwilitWave** [comment]
Ahhh excellent, embarrassing for me! In my defense, that About section on most github's link to the license but I found this dead link via googling for the winutil license.
