### ISSUE TITLE
MicroWin don't remove bloatware from Windows 10 Pro

### ISSUE THREAD

**Issue by FacundoMolina04** [ChrisTitusTech/winutil#2572]
MicroWin don't remove bloatware from Windows 10 Pro ISO, only works on win11?

**Comment by ChrisTitusTech** [comment]
> MicroWin don't remove bloatware from Windows 10 Pro ISO, only works on win11?

Yes it is designed for Windows 11. It will still work on Win10 but the start menu will have the normal bloat. I'm not sure it is worth modifying the script for Win10 since it goes End of Life next year.
