### ISSUE TITLE
The writing in the new progress bar needs better contrast for visibility

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#2591]
The writing in the new progress bar needs better contrast for visibility.

Consider a changing the colour of the progress bar when the task is finished. 
This is to be able to see it easily from a distance, and for people with poor eyesight.

**Comment by Marterich** [comment]
This is as simple as changing the following options inside the themes.json file for the different winutil color schemes.

ProgressBarForegroundColor, ProgressBarBackgroundColor, ProgressBarTextColor

Everyone is welcome to suggest new colors for this keeping in mind the overall theme so it doesn't become an eyesore

**Comment by Marterich** [comment]
There have been some UI modifications since this issue was opened and the colors have been modified /close
