### ISSUE TITLE
Feature Request: ControlD and Windscribe

### ISSUE THREAD

**Issue by Bazza-63** [ChrisTitusTech/winutil#2595]
Consider adding both Windscribe and Controld.

Windscribe is a VPN that has an open source app. It has built in ad blocking, malware blocking, porn blocking, etc. It has a free tier which comes with 10GB a month (can get an additional 5GB if you post about Windscribe on Twitter/X. It has a no logging policy and has been audited. It uses ramdisk servers. There exists a paid tier too with unlimited data. It supports port forwarding too. You can sign up to the paid version without an email and can pay in Monero. It also has a configuration generator, meaning you can export Wireguard, Ikev2 and OpenVPN profiles to use in 3rd party apps such as the official Wireguard app and Strongswan.

Controld is a secure DNS that supports DoT, DoQ and DoH. It has multiple DNS filters that can block malware, ads, social media, porn and more. There is a paid version that has even more features. Privacy Guide recommends it too.

**Comment by Real-MullaC** [comment]
No apps are being added to WinUtil as it is super bloated currently. 

/close
