### ISSUE TITLE
Using the "Remove Edge" Feature Gets Blocked by Bitdefender

### ISSUE THREAD

**Issue by ThisNekoGuy** [ChrisTitusTech/winutil#260]
**Describe the bug**
The issue here is, Bitdefender can't be disabled after it's installed, even if you try to force close it via the task manager...
So I'm not exactly sure how to run this specifically since it gets blocked no matter what I seem to do to mitigate it (I even tried setting Powershell as an exception).

**To Reproduce**
1. Install Bitdefender
2. Run the script via admin Powershell
3. Select Uninstall Edge
4. See Error / Get notified that the action was blocked

**Expected behavior**
The action would run as intended without interruption

**Additional context**
N/A

**Comment by mtorressahli** [comment]
I'm not sure whether my solution is optimal, but I just disable Bitdefender ("Advanced" settings in _Antivirus_ and _Advanced Threat Defemce_) while I run the tool, and others similar to it that I trust, since I would expect Bitdefender to block the type of system modification we're intending with these tweaks. Again, no expert here – just another Bitdefender user

**Comment by ThisNekoGuy** [comment]
I managed to fight Bitdefender to do it; I told it to stop for a few minutes (via the above instruction) but it still quarantined both the script _**and**_ PowerShell itself.
Had to un-quarantine them for it to finally work

**Comment by ChrisTitusTech** [comment]
This will happen with most antiviruses... they don't like you messing with system files.

Which, I understand. If you don't know how to disable your AV to run these things, then you probably shouldn't run them. 

Edge removal is extremely aggressive and once its done edge will NEVER come back. You simply won't be able to install it and Microsoft won't either. 

I'm closing this issue as I can't control external antivirus programs, unless I target them for removal.
