### ISSUE TITLE
MicroWin - Advanced Indexing Options Not Functioning

### ISSUE THREAD

**Issue by v6stXN46WdLBtp** [ChrisTitusTech/winutil#2602]
## Describe the bug
When attempting to open "Advanced Indexing Options" an error occurs. The error message says windows cannot find "{87D66A43-7B11-4A28-9811-C86EE395ACF7}". This is the GUID for the indexing options as seen here https://www.tenforums.com/tutorials/3123-clsid-key-guid-shortcuts-list-windows-10-a.html . 

This happens on a fresh MicroWin install from a 23H2 Windows 11 ISO.

## To Reproduce
Step 1: Create MicroWin ISO
Step 2: Install MicroWin ISO
Step 3: Attempt to open Advanced Indexing Options

## Expected behavior
Indexing options being able to be opened.

## Screenshots
![ApplicationFrameHost_UMfu8Vb82E](https://github.com/user-attachments/assets/104062ce-57df-400e-8a1e-94bd8b6fe466)

![control_kA83y0idI8](https://github.com/user-attachments/assets/d8609e34-5b78-43d4-9972-a92a23405845)

## Additional context
This is kind of concerning for MicroWin since this is basic functionality that is missing. I could not find anything online about fixing the issue meaning it requires a re-install without MicroWin.

EDIT: Reinstalled a microwin ISO and ran into the same issue immediately after install.

**Comment by v6stXN46WdLBtp** [comment]
Is there any other information or reproduction steps that need to be added?

**Comment by zmileski** [comment]
Windows search  need to be enabled. I had same problem.

![1](https://github.com/user-attachments/assets/1b60a064-3204-4f0a-8472-c8057848379c)
![2](https://github.com/user-attachments/assets/26b85642-d613-4bb5-ab37-5c829c6f8323)

**Comment by v6stXN46WdLBtp** [comment]
Is there any way to turn this back on without NTLite?

It is not in this menu which seems to be the only place that it could be.

![OptionalFeatures_jR7azOVlZ0](https://github.com/user-attachments/assets/65331853-61f9-4a08-972d-10caa3db5491)

**Comment by zmileski** [comment]
Not sure
u can try this command in cmd running with administrator
Dism /online /Enable-Feature /FeatureName:"SearchEngine-Client-Package" -All

Visit this site for more info 
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/enable-or-disable-windows-features-using-dism?view=windows-11

**Comment by v6stXN46WdLBtp** [comment]
I've been trying to figure out what in MicroWin is causing this and can't. It has to be some combination of things that I am not knowledgeable enough. 

Could someone with a bit more experience take a look at this?

**Comment by zmileski** [comment]
Not sure, i am not knowledgeable also but i think that need to be exluded here
![2](https://github.com/user-attachments/assets/070465e0-217b-4563-902a-6496fffff855)
maybe someone can do PR in microwin and also i think it will be good idea to be added fix with command "Dism /online /Enable-Feature /FeatureName:"SearchEngine-Client-Package" -All" in winutil under config features

**Comment by v6stXN46WdLBtp** [comment]
Ok! That is 100% the issue. I just ran MicroWin on an ISO and watched the terminal output and "SearchEngine-Client-Package" gets disabled. Huge thanks to zmileski for the help. @CodingWonders If you want to fix this it seems simple.

**Comment by CodingWonders** [comment]
That is the beauty of MicroWin. It lets you customize it afterward.

More info on the feature:

![BRMczVmL3d](https://github.com/user-attachments/assets/b3114cfa-cba1-4105-b89e-ecdde22b1212)

Much like you stated, @v6stXN46WdLBtp, it's a simple fix
