### ISSUE TITLE
MicroWin - Add custom script to run once after setup / cloudinit

### ISSUE THREAD

**Issue by ne0YT** [ChrisTitusTech/winutil#2604]
**Is your feature request related to a problem? Please describe.**
Instead of starting out to install some basic software after setup I would like to have it already installed automatically.

**Describe the solution you'd like**
The possibility to add a powershell script which runs automatically once after the setup

**Describe alternatives you've considered**
doing it manually

**Comment by MyDrift-user** [comment]
I think an appropriate solution would be to add the built in winutil automation feature with it, meaning on ISO creation, the user can attach his exported config with apps/tweaks ... to the ISO which will start winutil with it after first boot. that way we kind of make up the removal of in depth customisation. @CodingWonders what would u think about it?

**Comment by CodingWonders** [comment]
@MyDrift-user, I have an idea as to how we can do this.

With the JSON file exported:

1. Add an option that lets the user specify these files
2. Copy the JSON to the root of `install.wim`
3. Add another step to the unattended answer file once the user logs in that runs WinUtil with that JSON configuration

What do you think?

**Comment by MyDrift-user** [comment]
yeah just about what I had in Mind, Think that would be great

**Comment by MyDrift-user** [comment]
the PR that would have addid this was closed down. So I'm gonna close this aswell.

This does not mean that this is never going to be added, just not now.

/close
