### ISSUE TITLE
Errors while making Microwin

### ISSUE THREAD

**Issue by tecworks-dev** [ChrisTitusTech/winutil#2605]
## Describe the bug
Errors while making iso
3775 |          "WPFMicrowin" {Invoke-WPFMicrowin}
     |                         ~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred: The volume of the specified mount path does not support reparse points.  Please
     | mount to a volume that supports reparse points.
Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.

## To Reproduce
1. Go to 'Microwin'
2. Click on 'select scratch folder'
3. Click on 'select iso Win11_23H2_EnglishInternational_x64v2.iso'
4. Click on 'Import drivers from current system'
5. Click on 'Start Process'
6. See error

## Error```
Getting image information f:\Downloads\winutl-scratch\micro\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '6 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************
Check the UI for further steps!!!
Target ISO location: f:\Downloads\windows_11_23h2_winutils.iso
Index chosen: '6' from 6 : Windows 11 Pro
Mounting Windows image. This may take a while.
Invoke-WPFMicrowin: F:\downloads\winutil.ps1:3775
Line |
3775 |          "WPFMicrowin" {Invoke-WPFMicrowin}
     |                         ~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred: The volume of the specified mount path does not support reparse points.  Please
     | mount to a volume that supports reparse points.
Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.
Unmounting image...
Dismount-WindowsImage: F:\downloads\winutil.ps1:4949
Line |
4949 |          Dismount-WindowsImage -Path "$scratchDir" -Save
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The request is not supported.
Exporting image into f:\Downloads\winutl-scratch\micro\sources\install2.wim
Remove old 'f:\Downloads\winutl-scratch\micro\sources\install.wim' and rename f:\Downloads\winutl-scratch\micro\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image f:\Downloads\winutl-scratch\micro\sources\boot.wim into f:\Downloads\winutl-scratch\Scrach
Invoke-WPFMicrowin: F:\downloads\winutil.ps1:3775
Line |
3775 |          "WPFMicrowin" {Invoke-WPFMicrowin}
     |                         ~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred: The volume of the specified mount path does not support reparse points.  Please
     | mount to a volume that supports reparse points.
Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Unmounting image...
Dismount-WindowsImage: F:\downloads\winutil.ps1:5011
Line |
5011 |          Dismount-WindowsImage -Path "$scratchDir" -Save
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The request is not supported.
Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\m_a_s\AppData\Local\Temp\oscdimg.exe

OSCDIMG 2.56 CD-ROM and DVD-ROM Premastering Utility
Copyright (C) Microsoft, 1993-2012. All rights reserved.
Licensed only for producing Microsoft authorized content.

Scanning source tree (500 files in 43 directories)
Scanning source tree complete (945 files in 86 directories)

Computing directory information complete

Image file is 6306136064 bytes (before optimization)

Writing 945 files in 86 directories to f:\Downloads\windows_11_23h2_winutils.iso

100% complete

Storage optimization saved 4 files, 24576 bytes (0% of image)

After optimization, image file is 6308212736 bytes
Space saved because of embedding, sparseness or optimization = 24576

Done.
OSCDIMG Error Level : 0
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)

Performing Cleanup...
Done. ISO image is located here: f:\Downloads\windows_11_23h2_winutils.iso
Bye bye!```
## Additional context
no error if dont select scratch folder

**Comment by SHR1SHAK** [comment]
The new release 24.08.22. He fixed it yesterday

**Comment by MyDrift-user** [comment]
According to @SHR1SHAK the issue is fixed now, so I'm gonna close this out.
If the issue is still there for you fell free to reopen the issue :)
