### ISSUE TITLE
Cant play overwatch since teredo is disabled. Cant reenable it

### ISSUE THREAD

**Issue by Kibasmoothie** [ChrisTitusTech/winutil#2614]
I cant enable teredo anymore and the restore point created doesnt enable it anymore

**Comment by Kibasmoothie** [comment]
Yep it was teredo 100%. Actually a lot of games need teredo. Dont have a clear list but ive heard that X Box Gamepass Apss need it as Microsoft uses teredo for the online services. Cant guarentee it. But Forza Horizon 4 uses it and Overwatch. Thats confirmed

**Comment by Marterich** [comment]
@stuckydev you're right I think we should indeed move the tweak to the advanced section. Nevertheless i think it probably would be smart to add a new tweak to the essential tweaks that configures windows to prefer ipv4 over ipv6. That way you can still have the security and latency improvements in local networks without ipv6 enabled but keep all the features that teredo provides if needed. 

https://learn.microsoft.com/de-de/troubleshoot/windows-server/networking/configure-ipv6-in-windows

**Comment by stuckydev** [comment]
Great idea, sounds nice, sadly can't help you here with a commit :)

**Comment by Marterich** [comment]
> Great idea, sounds nice, sadly can't help you here with a commit :)

Will take a look at this later
