### ISSUE TITLE
MicroWin Package Remove Errors

### ISSUE THREAD

**Issue by AlexMayne5** [ChrisTitusTech/winutil#2622]
## Describe the bug
Getting errors in terminal window while microwin is running.

## To Reproduce
1. download Windows 11 23H2 Engish International
2. serlect Windows 11 pro
3. serlect "Import Drivers" and "Copy to Ventory"
4. look in terminal to see that it is showing errors as seen in picture 

## Expected behavior
not to see the errors

## Screenshots
![Screenshot 2024-08-25 132803](https://github.com/user-attachments/assets/7b99909d-38b5-4727-a310-99c09fe29a7c)

## Additional context
there looks like some other errors here too but dont know what they are.

**Comment by CodingWonders** [comment]
Those packages are either permanent (like the foundation package) or have been superseded by newer packages. There isn't anything to worry about, and your MicroWin image will still work.

**Comment by CodingWonders** [comment]
@korgano, don't worry about the package removal failures. We are working on reducing them. Also, your ISO is 4.58 GB in size, according to math

**Comment by CodingWonders** [comment]
Issue closed due to inactivity. /close
