### ISSUE TITLE
WinGet puts some apps in weird location.

### ISSUE THREAD

**Issue by skele6** [ChrisTitusTech/winutil#2628]
Winget install puts apps like Rufus and Godot Engine inside of AppData/Local/Microsoft/WinGet/Packages
       
Because of this windows doesn't recognize them. Hence they don't show up in the Windows Start Menu or on the desktop. A simpleton like me who thinks he cool because he uses Winutil and watches Titus has to type it in the Terminal or File Explorer and manually make shortcuts or move it to the desktop.

How I would do it if i could.
When Winget gets installed change the .json file to path somewhere so that you know the app is their. Then the user can move it wherever their heart desires. This is done by adding. 
 "installBehavior": {
        "defaultInstallRoot": "C:/installRoot"
    },Except changing the path to desktop this should only affect apps that require a install location
[https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#default-install-root](url)

You could go through the apps and change the script, Winget install app-id --location

**Comment by Marterich** [comment]
Last time I checked, only a fraction of apps supported the custom install path. 
See the following issue/comment for more info

https://github.com/ChrisTitusTech/winutil/issues/2503#issuecomment-2267499672
