### ISSUE TITLE
Jargon on the MinWin page - What is ScratchDir?

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#2632]
Jargon on the MinWin page - What is ScratchDir?

**Comment by CodingWonders** [comment]
Think of a ScratchDir as a temporary directory for management tasks. It's basically where temporary stuff for drivers, packages, and more is stored

**Comment by CodingWonders** [comment]
@billytwotone, don't download that. It's an infostealer. @ChrisTitusTech, are we starting to see an influx of these messages or what?

**Comment by billytwotone** [comment]
What are you asking me not to download? What is an infostealer?.

**Comment by CodingWonders** [comment]
> What are you asking me not to download? What is an infostealer?.

You don't have to worry about that. Basically, some account (perhaps a scam or a hacked account) was promoting a "fix" which involved downloading something from MediaFire. I've seen that yesterday as well, and it was a Google Chrome infostealer. Thankfully it was taken down, but expect more trouble regarding these comments.

If you want to know more about infostealers, check out [this Wikipedia article](https://en.wikipedia.org/wiki/Infostealer)

**Comment by SHR1SHAK** [comment]
This ghost guy is spamming it in #2635.

**Comment by billytwotone** [comment]
I am worried about some of the comments.
Is MinWin safe to use?

**Comment by CodingWonders** [comment]
@billytwotone, yes, it's safe to use. You start with a base Microsoft image and then use it to debloat it. It doesn't introduce malware - it only debloats the image.

There's no need to worry

**Comment by billytwotone** [comment]
I pleased the spammers have gone away. They tend to spoils things.
What if they return?

**Comment by CodingWonders** [comment]
This is fixed by #3066. /close
