### ISSUE TITLE
iwr : The remote name could not be resolved: 'raw.githubusercontent.com'

### ISSUE THREAD

**Issue by CatXander** [ChrisTitusTech/winutil#264]
iwr : The remote name could not be resolved: 'raw.githubusercontent.com'
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
![Screenshot (14)](https://user-images.githubusercontent.com/95142461/195364476-fb151dd0-ff58-4e5a-a2b8-1d6cc5e7e873.png)

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by 7thripr** [comment]
Try using a VPN.

**Comment by 7thripr** [comment]
did it work

**Comment by ChrisTitusTech** [comment]
Use the TLS line in the readme file.
