### ISSUE TITLE
Remove The Auto Closing Issues GitHub Worflow

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#2641]
Currently WinUtil has quite a lot of un-reviewed issues, that gets **closed as Not planed**.. even though it's in the works, or there's a solution around the corner.

I suggest removing this GitHub Workflow all together, as it's solving a problem that shouldn't exist anymore, which's the repo being inactive, or hard to maintain, this was fixed in PR #2380 by giving certain individuals the power to manage some aspect of the repo on behave of @ChrisTitusTech.

Plus I'd argue that it's introducing more problems along the way.. like, what developer wants to just rug some valuable user feedback under the carpet? It only makes seeing reported issues harder as times moves on, and Issues gets closed in an "unfair" way, at least this's what it seems like to the user who reported the issue.

**Comment by ChrisTitusTech** [comment]
@og-mrk I agree with you. I changed it from 7 days to stale to 90 days
It will auto close issues past 365 days unless they are marked with Keep Issue Open. 

I feel this should give ample time to address any outstanding issues and also prune anything that is really old and won't be addressed.

**Comment by og-mrk** [comment]
Thanks @ChrisTitusTech for addressing this, I'll close this issue as complete.
