### ISSUE TITLE
Where are the checkboxes to remove Defender?

### ISSUE THREAD

**Issue by Rohamgames** [ChrisTitusTech/winutil#2651]
## Describe the bug
Unable to selectively remove Defender and provisional packages (checkboxes are gone!)

## To Reproduce
1. Run the script
2. Pick the ISO while checking the checkboxes
3. Checkboxes to keep/remove defender and some other packages are gone! 

## Expected behavior
User used to be able to choose to keep Appx/Defender/provisional packages
## Screenshots
![image](https://github.com/user-attachments/assets/5922cdf7-2f03-4838-a5ea-5e92c0e42213)

Also, I have grabbed the following shot from YouTube and as you can see old version lets the user do a lot more (look at the features and compare to the above)

![image](https://github.com/user-attachments/assets/27afb859-f93e-4629-9810-c74951fe4611)

## Additional context
Tried on different machines with several different ISOs and the same happens everywhere look like the good features are gone :(

**Comment by CodingWonders** [comment]
Those checkboxes have been removed to streamline the experience. When Chris removed these things, he wanted a base image where everything would just work. You can use other tools to customize your image further

**Comment by Rohamgames** [comment]
I wish it was available, so it could remove the Defender
Or maybe some checkbox like do at your own risk, it may break the image kinda thing
I have used it countless times in the past and the only issues were the windows taking so long at "Getting things ready" part but after some waiting and then a reboot it worked fine every time

**Comment by MyDrift-user** [comment]
As @CodingWonders stated, these features were removed to streamline the ISO and just make a "sane" version of Windows.
I don't think this is going to be added back, The Advanced Tweaks do also get seen as the essential ones for most people, so that would probs not help..

For those reasons I'm going to close this issue out.

/close
