### ISSUE TITLE
Can no longer import

### ISSUE THREAD

**Issue by AerumT** [ChrisTitusTech/winutil#2657]
## Describe the bug
Can no longer import the porgram list from an exported list, worked yesterday(30.Aug.2024), tried to freshly export import today as well- no bueno

## To Reproduce
1. Go to 'winutil window'
2. Click on 'the gear icon'
3. Click on "import" option
4. Choose the exported json
5. Go to 'Powershell window'
6. See error

## Expected behavior
I expected to have the exported list to be imported again

## Screenshots
![pilt](https://github.com/user-attachments/assets/c345dd96-0cd6-4e62-9d39-539e15c7e0c7)

## Additional context
Might or might not be connected to the change of "Improve \Invoke-WPFPresets\ Public Function - Made applying tweaks presets go blazingly fast - Made Clearing Selection work properly @og-mrk (https://github.com/ChrisTitusTech/winutil/pull/2608)"

## Error Code:
```plaintext
====Chris Titus Tech=====
=====Windows Toolbox=====
Invoke-WPFPresets : Cannot process argument transformation on parameter 'preset'. Cannot convert value to type
System.String.
At line:4398 char:35
+         Invoke-WPFPresets -preset $flattenedJson -imported $true
+                                   ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WPFPresets], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Invoke-WPFPresets
```

**Comment by Ahmey1400** [comment]
same here
