### ISSUE TITLE
Microwin -- Hangs when 'Unmounting image'

### ISSUE THREAD

**Issue by uses0ap** [ChrisTitusTech/winutil#2667]
## Describe the bug
Microwin ISO creation hangs when completing build:
"Unmounting image..."

## To Reproduce
1. Go to 'microwin'
2. Click on 'start the process'
3. Scroll down to 
'Unmounting Registry...
Cleaning up image...
Cleanup complete.
Unmounting image...'

## Expected behavior
should complete the iso build

## Screenshots
![image](https://github.com/user-attachments/assets/37af4ecc-8b60-4001-bb5c-04a7df394d71)

## Additional context
Tried 2 runs, same issue
`
    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T                              CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T                             C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T                            C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT                           C:::::C                     T:::::T                T:::::T                                   C:::::C                     T:::::T                T:::::T                                   C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
No ISO is chosen+  C:\scratch
Invoking WPFGetIso
         _                     __    __  _                                                     /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __                                              /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \                                            / /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |                                           \/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|                                           oscdimg.exe on system: True                                                                  File path C:\Users\nponti\Downloads\Windows_ISO_Files\Win11_23H2_English_x64v2.iso           You have enough space for this operation.                                                    Mounting Iso. Please wait.
Done mounting Iso MSFT_DiskImage (ImagePath = "C:\Users\nponti\Downloads\Windows_ISO_F..., StorageType = 1)                                                                               Iso mounted to 'H'                                                                           Setting up mount dir and scratch dirs                                                        Mounting Iso. Please wait.                                                                   Done setting up mount dir and scratch dirs                                                   Scratch dir is C:\scratch\Scrach                                                             Image dir is C:\scratch\micro                                                                Copying Windows image. This will take awhile, please don't use UI or cancel this step!       Copy 1031(s) from H: to C:\scratch\micro                                                     Copy complete! Total Time: 0m39s                                                             Getting image information C:\scratch\micro\sources\install.wim                               Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.                                              Selected value '6 : Windows 11 Pro'.....                                                     Done reading and unpacking ISO                                                                                                                                                            *********************************                                                            Check the UI for further steps!!!                                                            No file name for the target image was specified                                              Target ISO location: C:\Users\nponti\Desktop\Microwin_11.iso                                 Index chosen: '1' from 1 : Windows 11 Home                                                   Mounting Windows image. This may take a while.                                               Mounting complete! Performing removal of applications...                                     Remove Features from the image                                                               You can re-enable the disabled features at any time, using either Windows Update or the SxS folder in <installation media>\Sources.                                                       Removing features complete!                                                                  Removing OS packages                                                                         Could not remove OS package Microsoft-Windows-FodMetadata-Package~31bf3856ad364e35~amd64~~10.0.22621.1                                                                                    Could not remove OS package Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.22621.1                                                                                     Could not remove OS package Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~en-US~11.0.22621.1                                                                 Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.2792                                                                            Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1                                                                               Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~wow64~~10.0.22621.2861                                                                                 Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1                                                                        Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1                                                                        Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~wow64~~10.0.22621.2861                                                                          Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1                                                                             Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1                                                                             Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~wow64~~10.0.22621.2861                                                                               Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1                                                                               Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Package_for_DotNetRollup_481~31bf3856ad364e35~amd64~~10.0.9206.1
Could not remove OS package Package_for_KB5027397~31bf3856ad364e35~amd64~~22621.2355.1.1
Could not remove OS package Package_for_RollupFix~31bf3856ad364e35~amd64~~22621.2861.1.6
Some packages could not be removed. Do not worry: your image will still work fine. This can happen if the package is permanent or has been superseded by a newer one.
Removing Appx Bloat
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
C:\scratch\Scrach\Windows\System32\WebThreatDefSvc\*: Access is denied.
C:\scratch\Scrach\Windows\System32\WebThreatDefSvc\*: Access is denied.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
C:\scratch\Scrach\Windows\System32\WebThreatDefSvc\*: Access is denied.
C:\scratch\Scrach\Windows\System32\WebThreatDefSvc\*: Access is denied.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
C:\scratch\Scrach\Windows\System32\WebThreatDefSvc\*: Access is denied.
C:\scratch\Scrach\Windows\System32\WebThreatDefSvc\*: Access is denied.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
[INFO] In Your local takeown expects 'Y' as a Yes answer.
Removal complete!
Create unattend.xml
Done Create unattend.xml
Copy unattend.xml file into the ISO
Done Copy unattend.xml
Create FirstRun
Done create FirstRun
Copy FirstRun.ps1 into the ISO
Done copy FirstRun.ps1
Copy link to winutil.ps1 into the ISO
Copy checkinstall.cmd into the ISO
                                                                                              Dismount-WindowsImage                                                                           Running                                                                                      [oooooooo                                                                         ]                                                                                                   Bypassing system requirements (system image)
Removing Windows Expedited App: EdgeUpdate
Removing Windows Expedited App: DevHomeUpdate
Removing Windows Expedited App: OutlookUpdate
Removing Windows Expedited App: CrossDeviceUpdate
ERROR: The system was unable to find the specified registry key or value.
Setting all services to start manually
Enabling Local Accounts on OOBE
Disabling Sponsored Apps
Done removing Sponsored Apps
Disabling Reserved Storage
Changing theme to dark. This only works on Activated Windows
Unmounting Registry...
Cleaning up image...
Cleanup complete.
Unmounting image...`

**Comment by CodingWonders** [comment]
The image is still being saved. How much time did you give it? I think you may need to give it some more time.

Perhaps you should look at your system resources to see what is using your disk and CPU

**Comment by uses0ap** [comment]
I've waited for 20min each run.

System seems idle
Disk usage: 3%
CPU usage: 19%

**Comment by uses0ap** [comment]
I jumped the gun here. I am seeing progress now.
(~30min about halfway completed)

Closing ticket
