### ISSUE TITLE
Importing config file still not working as of 24.08.30

### ISSUE THREAD

**Issue by FinalDemise** [ChrisTitusTech/winutil#2676]
## Describe the bug
Still getting "Invoke-WPFPresets" error when trying to import a config file

## To Reproduce
1. Go to import freshly exported config file.

## Screenshots
[Screenshot 2024-09-04 133734](https://github.com/user-attachments/assets/19ff2946-da36-480c-beec-ae6a10800824)
[Screenshot 2024-09-04 133838](https://github.com/user-attachments/assets/a6d27b93-200f-4fb8-9389-63aab025c2a6)
[Screenshot 2024-09-04 134049](https://github.com/user-attachments/assets/4213dd49-90dc-47a5-bfa3-2dfed29753ec)
Is working in 24.08.16

## Additional context
I use the .exe version of the program but I tested it with the powershell script as well. Same results.

**Comment by og-mrk** [comment]
Hello @FinalDemise and thanks for reporting this issue
This was reported in #2657 issue and fixed in #2658 PR, the fix will be available in the next release of WinUtil.

as there's no further discussion to be made on this topic, I'll be closing this issue...
/close
