### ISSUE TITLE
Feature Request: Clear "Top Apps" Section in Search

### ISSUE THREAD

**Issue by UltraCakeBakery** [ChrisTitusTech/winutil#2677]
**Is your feature request related to a problem? Please describe.**  
On many machines, the "Top Apps" section in search becomes cluttered with entries that shouldn't be there. For instance, on this cleaned-up PC:

![image](https://github.com/user-attachments/assets/b6efa482-8728-43b3-9f2c-96354f56fd37)

The "Kontakt" entry doesn't exist, and the default app icons open the installed apps page in the settings app. However, since these apps are already uninstalled, selecting them does nothing.

**Describe the solution you'd like**  
A button to clear the history in the "Top Apps" section would be extremely useful.

**Describe alternatives you've considered**  
Is there an existing button or method that can also clear this data?

**Additional context**  
I'm relatively new to winutil and may have missed something...

**Comment by MyDrift-user** [comment]
Found this, look at Anandika Nevada's last comment:
https://answers.microsoft.com/en-us/windows/forum/all/how-to-remove-change-top-apps-in-windows-11/98d6dd12-ae83-4080-8f2e-f59427ad84d7

that might be a way bc there is not an easlily editable reg key starting windows 11 anymore, but it is janky ..

**Comment by MyDrift-user** [comment]
There is no good way to do this, if you want to customize your start menu to this extend I'd suggest using a third party one.

So I'm sadly closing this out for now, thanks for the request tho :)

/close
