### ISSUE TITLE
[Microwin] WinUtil Shortcut on desktop not working

### ISSUE THREAD

**Issue by MyDrift-user** [ChrisTitusTech/winutil#2681]
## To Reproduce
(using latest Full-Release)
1. Go to 'make Microwin ISO'
2. Click on 'Install Windows using Microwin ISO'
3. Scroll down to 'winutil.lnk'

## Expected behavior

- should open winutil without issues

don't have any more to tell bc the Issue is not on one of my machines, but I don't have time to test it today

**Comment by CodingWonders** [comment]
I'll investigate it and come back with the results

**Comment by CodingWonders** [comment]
@MyDrift-user, I can't reproduce this issue on my end

![image](https://github.com/user-attachments/assets/bd59e6c0-6335-4215-a5c4-4025d493b1ec)

What is the error? Come back with it once you have it

**Comment by MyDrift-user** [comment]
It apparently just closes instanty, will try to get more information on it

**Comment by MyDrift-user** [comment]
after some questioning I was able to find out that he had no internet connectin...
sorry for wasting your time ._.
