### ISSUE TITLE
Can't import settings.json

### ISSUE THREAD

**Issue by hebval** [ChrisTitusTech/winutil#2682]
## Describe the bug
I just use the script for the first time and exported the settings to try importing them on another PC. I get the following Powershell output : 

Invoke-WPFPresets : Unable to process argument transformation on parameter 'preset'. Impossible to
convert the value to type System.String.
Au caractère Ligne:4398 : 35
+         Invoke-WPFPresets -preset $flattenedJson -imported $true
+                                   ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData : (:) [Invoke-WPFPresets], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Invoke-WPFPresets

## To Reproduce
1. Start the script
2. Make some settings and export them
3. Close the script window
4. Open the script again
5. Import the .json file

## Expected behavior
I was expecting that all the choices I made would be imported automatically

## Additional context
Here is my JSON exported file :

{
    "WPFTweaks":  [
                      "WPFTweaksRestorePoint",
                      "WPFTweaksWifi",
                      "WPFTweaksDisableipsix",
                      "WPFTweaksHome",
                      "WPFTweaksTeredo",
                      "WPFTweaksRemoveHomeGallery",
                      "WPFTweaksDisableLMS1",
                      "WPFTweaksStorage",
                      "WPFTweaksHiber",
                      "WPFTweaksDebloatAdobe",
                      "WPFTweaksConsumerFeatures",
                      "WPFTweaksDisableNotifications",
                      "WPFTweaksDVR",
                      "WPFTweaksTele",
                      "WPFTweaksDisplay",
                      "WPFTweaksAH",
                      "WPFTweaksRightClickMenu",
                      "WPFTweaksEndTaskOnTaskbar",
                      "WPFTweaksBlockAdobeNet",
                      "WPFTweaksEdgeDebloat",
                      "WPFTweaksRemoveCopilot",
                      "WPFTweaksLoc",
                      "WPFTweaksRemoveOnedrive",
                      "WPFTweaksServices",
                      "WPFTweaksDisableFSO",
                      "WPFTweaksPowershell7Tele",
                      "WPFTweaksDeleteTempFiles",
                      "WPFTweaksDisableBGapps",
                      "WPFTweaksPowershell7"
                  ],
    "Install":  [
                    {
                        "winget":  "7zip.7zip",
                        "choco":  "7zip"
                    },
                    {
                        "winget":  "WinSCP.WinSCP",
                        "choco":  "winscp"
                    },
                    {
                        "winget":  "Gyan.FFmpeg",
                        "choco":  "ffmpeg-full"
                    },
                    {
                        "winget":  "CPUID.HWMonitor",
                        "choco":  "hwmonitor"
                    },
                    {
                        "winget":  "CrystalDewWorld.CrystalDiskInfo",
                        "choco":  "crystaldiskinfo"
                    },
                    {
                        "winget":  "Notepad++.Notepad++",
                        "choco":  "notepadplusplus"
                    },
                    {
                        "winget":  "GIMP.GIMP",
                        "choco":  "gimp"
                    },
                    {
                        "winget":  "Valve.Steam",
                        "choco":  "steam-client"
                    },
                    {
                        "winget":  "OBSProject.OBSStudio",
                        "choco":  "obs-studio"
                    },
                    {
                        "winget":  "Google.Chrome",
                        "choco":  "googlechrome"
                    },
                    {
                        "winget":  "VideoLAN.VLC",
                        "choco":  "vlc"
                    },
                    {
                        "winget":  "JAMSoftware.TreeSize.Free",
                        "choco":  "treesizefree"
                    },
                    {
                        "winget":  "ddu",
                        "choco":  "ddu"
                    },
                    {
                        "winget":  "PlayStation.PSRemotePlay",
                        "choco":  "ps-remote-play"
                    },
                    {
                        "winget":  "ElectronicArts.EADesktop",
                        "choco":  "ea-app"
                    },
                    {
                        "winget":  "Plex.Plex",
                        "choco":  "plex"
                    },
                    {
                        "winget":  "Discord.Discord",
                        "choco":  "discord"
                    },
                    {
                        "winget":  "Ubisoft.Connect",
                        "choco":  "ubisoft-connect"
                    },
                    {
                        "winget":  "EpicGames.EpicGamesLauncher",
                        "choco":  "epicgameslauncher"
                    },
                    {
                        "winget":  "PuTTY.PuTTY",
                        "choco":  "putty"
                    },
                    {
                        "winget":  "Nikse.SubtitleEdit",
                        "choco":  "na"
                    },
                    {
                        "winget":  "Aegisub.Aegisub",
                        "choco":  "aegisub"
                    }
                ],
    "WPFInstall":  [
                       "WPFInstall7zip",
                       "WPFInstallwinscp",
                       "WPFInstallffmpeg",
                       "WPFInstallhwmonitor",
                       "WPFInstallcrystaldiskinfo",
                       "WPFInstallnotepadplus",
                       "WPFInstallgimp",
                       "WPFInstallsteam",
                       "WPFInstallobs",
                       "WPFInstallchrome",
                       "WPFInstallvlc",
                       "WPFInstalltreesize",
                       "WPFInstallddu",
                       "WPFInstallpsremoteplay",
                       "WPFInstalleaapp",
                       "WPFInstallplexdesktop",
                       "WPFInstalldiscord",
                       "WPFInstallubisoft",
                       "WPFInstallepicgames",
                       "WPFInstallputty",
                       "WPFInstallSubtitleEdit",
                       "WPFInstallAegisub"
                   ],
    "WPFFeature":  [
                       "WPFFeatureDisableSearchSuggestions",
                       "WPFFeatureEnableLegacyRecovery",
                       "WPFFeaturesdotnet"
                   ]
}

**Comment by NavSethi2006** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by MyDrift-user** [comment]
Hey @hebval 
Thanks for reporting the Issue, this was already fixed in #2658 and you will be able to use that functionality again starting the next full-release.
Since this is fixed and seems to be the only issue, I am going to close this
/close

**Comment by hebval** [comment]
Woops, sorry for the duplicate then! :)

**Comment by MyDrift-user** [comment]
No Issues, the PR and the Issue were both closed so a bit hard to know what is already fixed :)
