### ISSUE TITLE
CREATE A HOSTS FILE FOR BLOCKING MALWARE DOMAINS

### ISSUE THREAD

**Issue by GamerKing122** [ChrisTitusTech/winutil#2684]
**Is your feature request related to a problem? Please describe.**

CREATE A HOSTS FILE FOR BLOCKING MALWARE DOMAINS
**Describe the solution you'd like**

CREATE A HOSTS FILE FOR BLOCKING MALWARE DOMAINS
**Describe alternatives you've considered**

**Additional context**

**Comment by Marterich** [comment]
It's a losing battle if we try modifying the hosts file to this extent, as there are tens of thousands of malicious domains and they are constantly changing. 
Also modifying the Hosts file, only blackholes the DNS Names and nothing more. 

If you want to use meaningful and up to date DNS Filtering of malicious domains, you should take a look at a DNS Provider like Quad9 (also available as a setting in winutil tweaks), a VPN Solution (most of which support DNS Blacklisting of malicious domains) or something like PiHole to Host your own DNS Server at home.
