### ISSUE TITLE
Restore point option filled as default

### ISSUE THREAD

**Issue by mews-se** [ChrisTitusTech/winutil#2689]
![image](https://github.com/user-attachments/assets/ecb0745b-5657-44db-8264-afa40a3095e2)

Don't know if this is a feature or a bug, but the checkmark for "create restore point" is filled as standard

**Comment by Marterich** [comment]
@mews-se good catch. I've never really taken a look at this and always thought "maybe someone changed the preset" but in the end, it actually was a bug in the way the UI Elements are loaded :)
