### ISSUE TITLE
Hangs on Microsoft Teams removal.

### ISSUE THREAD

**Issue by Uhahguru** [ChrisTitusTech/winutil#269]
**Describe the bug**
Latest debloat version hangs on the Microsoft Teams removal step. 

**To Reproduce**
1. Install fresh Window 10 22H2
2. Run all updates
3. Run all store updates
4. Run debloat on Desktop plus Visual Performance plus Remove All MS Store Aps.
5. Hangs on "Team installation not found"

**Expected behavior**
Expected debloat to remove MS Store Aps.

**Screenshots**
![messages_0](https://user-images.githubusercontent.com/65801126/195905895-293ab008-2c60-4646-b6b5-05c2b169d123.jpeg)

**Additional context**
RED TEXT: 
You cannot call a method on a null-valued expression.
At line:1315 char:13
$MachineWide.Uninstall()
~~~~~~~~~~~~~~~~~~~~
CategoryInfo			:InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrerId	:InvokeMethodOnNull

YELLOW TEXT"
WARNIG: Teams installation not found
Process user: Public
WARNIG: Teams installation not found for user Public
Process user: Owner
WARNIG: Teams installation not found for user Owner

**Comment by ChrisTitusTech** [comment]
Just pushed a big conversion with extra checks so this doesn't happen.
