### ISSUE TITLE
System Registry Cleaning feature

### ISSUE THREAD

**Issue by tGstep** [ChrisTitusTech/winutil#2692]
**Describe the solution you'd like**

I would like to let winutil become my ultimate debloating and empowering windows tool. I think a dead/unused registry keys cleaner included could be nice.

**Describe alternatives you've considered**

In the meantime i use wise registry cleaner for that.

**Comment by CodingWonders** [comment]
Registry cleaners are unnecessary these days. Most commercial ones typically scan your computer, give an absurd figure of registry entries (even on clean installations) that you "fix" by paying for a higher tier.

It's highly unlikely that something like this will be added. We are no longer living in the Windows XP days when registry cleaners actually worked.

**Comment by CodingWonders** [comment]
Same thing. CTT even made a video about those: https://www.youtube.com/watch?v=21VMQyQzRJw
