### ISSUE TITLE
MicroWin changes explorer look.

### ISSUE THREAD

**Issue by InvisibleRasta** [ChrisTitusTech/winutil#2697]
Hello I created an iso of windows pro 24h2 with microwin and I notused that it changed the look of explorer . How do i revert it back to the default windows 11 explorer look?

**Comment by ruxunderscore** [comment]
Do you have a screenshot of the Explorer?

**Comment by InvisibleRasta** [comment]
![Screenshot 2024-09-08 215203](https://github.com/user-attachments/assets/7509b4f6-b0e1-4f4d-8a89-6abcc23ab670)
Its the widnows 7 explorer i think.

**Comment by zmileski** [comment]
Can u screenshot winver of your windows?

**Comment by InvisibleRasta** [comment]
![Screenshot 2024-09-22 153806](https://github.com/user-attachments/assets/f88b11d9-d40b-45b6-a221-a32b4a1a40cc)

**Comment by zmileski** [comment]
Where did you get the iso?

**Comment by InvisibleRasta** [comment]
it is an official iso

**Comment by zmileski** [comment]
Components: Copilot (User Experience Aix) removal is breaking new explorer tabs

**Comment by zmileski** [comment]
Microsoft released 24h2 so more people will have this issue @CodingWonders
This fixed the issue
Dism /online /Enable-Feature /FeatureName:"Recall"
After reboot its ok to disable again.

**Comment by CodingWonders** [comment]
@zmileski, this feature is already excluded in the draft PR

**Comment by CodingWonders** [comment]
@zmileski, @InvisibleRasta, the latest commit to the draft PR now does the following. It leaves Recall enabled, but then it disables it on the first run

![vmware_1iJhKd0DBK](https://github.com/user-attachments/assets/619c2b85-6ffc-4085-b7a2-098a62f13ac5)
![vmware_wlYJ6nmITW](https://github.com/user-attachments/assets/e98406cb-9492-43df-8f9a-950484fdbf41)

**Comment by Savitarax** [comment]
There are 3 settings you can use to practically disable copilot/recall completely. These will do the following things
1: Remove the package so it doesn't even appear in search or app lists
2: Remove the package so it doesn't activate if you hit the new copilot key on keyboards
3: Remove the package so it doesn't even show up as an app that was installed in apps and features

In group policy there are 2 settings

"turn off windows copilot"
(UserConfig\AdministrativeTemplates\WindowsComponents\Windows Copilot)

"turn off saving snapshots to windows"
(UserConfig\AdministrativeTemplates\WindowsComponents\Windows Ai)


These 2 group policy options enter 2 registry keys located here

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot
HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\WindowsCopilot
"TurnOffWindowsCopilot" 
Dword (1)

HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\WindowsAI
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot
"DisableAIDataAnalysis"
Dword (1)


If you also use an app called "AppXPackagesManager"
https://github.com/Savitarax/File-Resources
(I am NOT the original creator of said app, I am merely providing the software to use)

Copilot is an option that you can remove listed in user packages

After doing these steps.
I can't get copilot to activate in any way, nor can I find recall. 

Figured i'd list this to anyone that was looking for a pretty solid solution if they were looking for the template to do so.

**Comment by WitherOrNot** [comment]
To those that arrive here from any Youtube or Twitter posts, please know that disabling Recall via DISM works fine, and preserves the modern File Explorer (though some might consider this an anti-feature). CBS correctly disables it, and the disablement is preserved through reboots, just like with any other feature.

No Minority Report-esque conspiracy here folks.

![image](https://github.com/user-attachments/assets/f1aafc87-d01a-4729-8194-b9a37fe504ce)

![image](https://github.com/user-attachments/assets/eff22d24-d862-4a07-8e53-0c636cabd74d)

**Comment by thecatontheceiling** [comment]
Chris can you delete my reply too when you delete Wither's :3 I would be honored

**Comment by infradragon** [comment]
what's winutil

**Comment by NotINeverMe** [comment]
This is a major problem. For those that are attempting to downplay this as a feature that can be disabled I ask you: what would you do if you found a piece of code that is designed to send all data on the device outside of your network, but it was behind a conditional that could be set $true at some point in the future? Would you leave it in the code base? What a ridiculous argument. My colleagues and I have contacted Richard Wakeman to get a handle on this. This can not be allowed to continue when such critical systems rely on Windows. Let alone any privacy concerns for consumers.

**Comment by mnlnlks** [comment]
> [...] please know that disabling Recall via DISM works fine, and preserves the modern File Explorer [...]

@WitherOrNot Did you miss [this comment](https://github.com/ChrisTitusTech/winutil/issues/2697#issuecomment-2395203955) from [CodingWonders](https://github.com/CodingWonders) 5 days ago or did you intentionally ignore it to make your "Minority Report-esque conspiracy" comment?

> the latest commit to the draft PR now does the following. It leaves Recall enabled, but then it disables it on the first run. During my testing, it kept the explorer look intact

This was also explained on the video you reference.

**Comment by thecatontheceiling** [comment]
The video titled "Recall is MANDATORY"?

**Comment by DeprecatedLuke** [comment]
> This is a major problem. For those that are attempting to downplay this as a feature that can be disabled I ask you: what would you do if you found a piece of code that is designed to send all data on the device outside of your network, but it was behind a conditional that could be set $true at some point in the future? Would you leave it in the code base? What a ridiculous argument. My colleagues and I have contacted Richard Wakeman to get a handle on this. This can not be allowed to continue when such critical systems rely on Windows. Let alone any privacy concerns for consumers.

Recall is local, you're thinking of Copilot.

**Comment by WitherOrNot** [comment]
> > [...] please know that disabling Recall via DISM works fine, and preserves the modern File Explorer [...]
> 
> @WitherOrNot Did you miss [this comment](https://github.com/ChrisTitusTech/winutil/issues/2697#issuecomment-2395203955) from [CodingWonders](https://github.com/CodingWonders) 5 days ago or did you intentionally ignore it to make your "Minority Report-esque conspiracy" comment?
> 
> > the latest commit to the draft PR now does the following. It leaves Recall enabled, but then it disables it on the first run. During my testing, it kept the explorer look intact
> 
> This was also explained on the video you reference.

Firstly, I bring your attention to this comment on the video in question, which has not been amended since posting.

![image](https://github.com/user-attachments/assets/f3003f71-ad42-409e-b4d0-732b2fa50268)

Secondly, running this command in Audit Mode prior to OOBE also disables Recall without affecting explorer. This disablement works for all users, so not even a "first-run" is necessary, you can simply Sysprep an image with this feature disabled.

Finally, as for why I refer to this whole thing as a "Minority Report-esque conspiracy", this is the general attitude I have observed from the community as a response to this video. I do not aim to defend Windows 11 or the unnecessary Recall feature here, but we should try to avoid spreading inflammatory claims without proper analysis.

**Comment by mnlnlks** [comment]
> Firstly, I bring your attention to this comment on the video in question

So the answer is yes, you ignored CodingWonders comment completely to argue about something outside this github issue and make an unnecesary point, understood.

**Comment by thecatontheceiling** [comment]
Chris is intentionally misrepresenting what is actually going on here in order to alienate people and in turn gain a bigger following. No clue how else to put this in order for you to understand WitherOrNot's point. 

A comment on a GitHub issue doesn't matter here because the general consensus has now become "Recall is MANDATORY" and that "it's a dependency of Explorer" etc. etc. as a result of Chris making a video AND a twitter post massively misrepresenting a **bug** and blatantly lying about it as well.

**Comment by whytf** [comment]
> Chris is intentionally misrepresenting what is actually going on here in order to alienate people and in turn gain a bigger following. No clue how else to put this in order for you to understand WitherOrNot's point.
> 
> A comment on a GitHub issue doesn't matter here because the general consensus has now become "Recall is MANDATORY" and that "it's a dependency of Explorer" etc. etc. as a result of Chris making a video AND a twitter post massively misrepresenting a **bug** and blatantly lying about it as well.

Do you keep spywares quarantined? Pretty sure not, most AV delete them automatically :) and recall is not even quarantined :)

**Comment by whytf** [comment]
> Chris is intentionally misrepresenting what is actually going on here in order to alienate people and in turn gain a bigger following. No clue how else to put this in order for you to understand WitherOrNot's point.
> 
> A comment on a GitHub issue doesn't matter here because the general consensus has now become "Recall is MANDATORY" and that "it's a dependency of Explorer" etc. etc. as a result of Chris making a video AND a twitter post massively misrepresenting a **bug** and blatantly lying about it as well.

Do you keep spywares quarantined? Pretty sure not, most AV delete them automatically after a while :) and recall is not even quarantined :)

> misrepresenting a bug

Also, to put recall, something completely unrelated to explorer since it's existance, as a dependency, in an OS from a company notoriously known for data hoarding user data to sell them, that definitely must be a "bug" and not a motive.

**Comment by amirulshukry** [comment]
One curious thing. When I  created micro with 24H2 release, file explorer was borked with ribbon menu. However when I created a new user, I got the tabbed file explorer. Spent some time looking at registry entries to no avail until discovery of the recall issue. & fix
Dism /online /Enable-Feature /FeatureName:"Recall"
Dism /online /Disable-Feature /FeatureName:"Recall"

After the fix there are 2 new registry entries
HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\WindowsAI DWORD DisableAIDataAnalysis = 1
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsAI DWORD DisableAIDataAnalysis = 1

**Comment by thecatontheceiling** [comment]
@whytf It's remarkable how every single one of you are so willing to shove your head deep into the sand in order to maintain your biases instead of trying to get another opinion on an issue.

I guess it's nice when you're in an echo-chamber where nobody disagrees with you but you should really look at the bigger picture rather than saying "microsoft collects data so it's done on purpose!" without any sort of proof being presented or really any effort to even understand my reply.

Thumbs down me all you want but this isn't Reddit and people who have basic comprehension skills will understand that this bug only occurs when you try disabling Recall _offline_ which means that it is in fact NOT an explorer dependency. 

You can even disable it during audit mode, sysprep & capture like you're supposed to and explorer is fully in-tact.

I am not going to make any more replies if I keep getting braindead comments, as I'm looking for some sort of real discussions here and not conspiracy theories.

**Comment by joe8755** [comment]
> Thumbs down me all you want but this isn't Reddit and people who have basic comprehension skills will understand that this bug only occurs when you try disabling Recall _offline_ which means that it is in fact NOT an explorer dependency.
> 
> You can even disable it during audit mode, sysprep & capture like you're supposed to and explorer is fully in-tact.

@thecatontheceiling

I agree that this could be a bug, this bug will happen during the microwin removal process

not trying to downplay what chris overreacted in his youtube video, but maybe users don't want an extra step to disable it offline after microwin modified the ISO

and it's just youtuber does youtuber thing, you overreact here won't change anything right?

**Comment by thecatontheceiling** [comment]
He's not "just" a YouTuber (that wouldn't be an excuse either). His name is attached to the most starred PowerShell project on GitHub, that's a lot more than just being a YouTuber.

When you attach your name to the largest PowerShell project on GitHub, you will gain a following, a reputation and people will trust you immediately no matter what you say. Chris knows this extremely well and he's abusing that fact to blatantly lie. This crap is on hackernews now even though it's a blatant lie.

He's made this statement on Twitter as well and people are **taking it for granted**. 

I knew he was incompetent but I really didn't think he was this petty for views, money, whatever he's trying to get from lying about this. Maybe to push WinUtil's popularity even more, I don't know and I won't act like I do.

**Comment by thecatontheceiling** [comment]
He's not "just" a YouTuber (that wouldn't be an excuse either). His name is attached to the most starred PowerShell project on GitHub, that's a lot more than just being a YouTuber.

When you attach your name to the largest PowerShell project on GitHub, you will gain a following, a reputation and people will trust you immediately no matter what you say. Chris knows this extremely well and he's abusing that fact to blatantly lie. This crap is on hackernews now even though it's a blatant lie.

He's made this statement on Twitter as well and people are **taking it for granted**. 

I knew he was incompetent but I really didn't think he was this petty for views, money, whatever he's trying to get from lying about this. Maybe to push WinUtil's popularity even more, I don't know and I won't act like I do.

**Comment by whytf** [comment]
> @whytf It's remarkable how every single one of you are so willing to shove your head deep into the sand in order to maintain your biases instead of trying to get another opinion on an issue.

> I guess it's nice when you're in an echo-chamber where nobody disagrees with you but you should really look at the bigger picture rather than saying "microsoft collects data so it's done on purpose!" without any sort of proof being presented or really any effort to even understand my reply.

I don't care about your silly multibillion spyware OS, just stating facts that they have to survive somehow by selling something other than licenses, otherwise it would be a lot harder to crack it, not my problem you believe in an ideal world where every company is ethical and honest, my arch doesn't sell anything to me or from me :)

**Comment by mnlnlks** [comment]
@WitherOrNot there's an update video that should clarify your misconceptions.

**Comment by amirulshukry** [comment]
> One curious thing. When I created micro with 24H2 release, file explorer was borked with ribbon menu. However when I created a new user, I got the tabbed file explorer. Spent some time looking at registry entries to no avail until discovery of the recall issue. & fix Dism /online /Enable-Feature /FeatureName:"Recall" Dism /online /Disable-Feature /FeatureName:"Recall"
> 
> After the fix there are 2 new registry entries HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\WindowsAI DWORD DisableAIDataAnalysis = 1 HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsAI DWORD DisableAIDataAnalysis = 1

Further digging I found that if I create new user using net user command and log in as that user at the console, I get the old explorer. However if after creating the new user then log in using remote desktop, I get the tabbed explorer. Go figure

**Comment by amirulshukry** [comment]
> > One curious thing. When I created micro with 24H2 release, file explorer was borked with ribbon menu. However when I created a new user, I got the tabbed file explorer. Spent some time looking at registry entries to no avail until discovery of the recall issue. & fix Dism /online /Enable-Feature /FeatureName:"Recall" Dism /online /Disable-Feature /FeatureName:"Recall"
> > After the fix there are 2 new registry entries HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\WindowsAI DWORD DisableAIDataAnalysis = 1 HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsAI DWORD DisableAIDataAnalysis = 1
> 
> Further digging I found that if I create new user using net user command and log in as that user at the console, I get the old explorer. However if after creating the new user then log in using remote desktop, I get the tabbed explorer. Go figure

It's getting weirder folks. The user I previously created getting the old explorer I got fixed by adding these 2 folders
C:\Users\userwitholdexplorer\AppData\Local\Packages\Microsoft.UI.Xaml.2.7_8wekyb3d8bbwe
C:\Users\userwitholdexplorer\AppData\Local\Packages\Microsoft.UI.Xaml.2.8_8wekyb3d8bbwe

Then I tried to create another new user so that I could recreate the fix. But no, now the new user comes with the tabbed explorer. 
Also adding those 2 folders to the initial admin user does not seem to work.

**Comment by DavidXanatos** [comment]
> @zmileski, @InvisibleRasta, the latest commit to the draft PR now does the following. It leaves Recall enabled, but then it disables it on the first run. During my testing, it kept the explorer look intact
> 
> ![vmware_1iJhKd0DBK](https://private-user-images.githubusercontent.com/101426328/373909167-619c2b85-6ffc-4085-b7a2-098a62f13ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTgxODEsIm5iZiI6MTcyOTA5Nzg4MSwicGF0aCI6Ii8xMDE0MjYzMjgvMzczOTA5MTY3LTYxOWMyYjg1LTZmZmMtNDA4NS1iN2EyLTA5OGE2MmYxM2FjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNjU4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWY2N2U5ZWMxMGRiNDE3NDk4YzM3M2I2ZWQ5N2EwMjgxYTNiMWUyNTMyYjUzNDMxYjA2ZWYzZDhjMjI0NzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xomM1Ceq1gG1pX_r75ROkGNnrzjvVNOJiOptnyNmbWU) ![vmware_wlYJ6nmITW](https://private-user-images.githubusercontent.com/101426328/373909166-e98406cb-9492-43df-8f9a-950484fdbf41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTgxODEsIm5iZiI6MTcyOTA5Nzg4MSwicGF0aCI6Ii8xMDE0MjYzMjgvMzczOTA5MTY2LWU5ODQwNmNiLTk0OTItNDNkZi04ZjlhLTk1MDQ4NGZkYmY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNjU4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjI4MzI3ZmVlNWIxNmI4ZDUzMjEyYjFmMTMyNGU0YmRlODZkYTAxZmIxNGIwMjc0ZGI4MWEzMjMwYmM3NmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xJ87U5xwm9aNgdH3IlUOjDC_Dnck9e_0urwXu_JdeIk)

which tool are you using here to list the features?

**Comment by ViciousSquid** [comment]
I actually find the "old" Explorer desirable and if anyone could tell me what I need to do to deliberately invoke it permanently I'd be very grateful.

**Comment by zmileski** [comment]
Run this 
[Restore_classic_File_Explorer_with_ribbon.zip](https://github.com/user-attachments/files/17428941/Restore_classic_File_Explorer_with_ribbon.zip)
then restart **Windows Explorer**
