### ISSUE TITLE
MicroWin - Add mstsc (rdp-client)

### ISSUE THREAD

**Issue by ne0YT** [ChrisTitusTech/winutil#2705]
**Is your feature request related to a problem? Please describe.**
RDP works as a server but not as the client.

**Describe the solution you'd like**
keep all mstsc-functionality on microwin

**Describe alternatives you've considered**
copying mstsc.exe to system32 works.. but it lacks some features. please just keep this part of windows in microwin.

**Comment by CodingWonders** [comment]
@ne0YT, in my testing, I was able to connect via RDP to an old system. `mstsc` is already there

**Comment by CodingWonders** [comment]
@ne0YT, to reinstate Remote Desktop Connection, you will need to enable the `Microsoft-RemoteDesktopConnection` feature. This will reinstall the Remote Desktop Connection application

**Comment by ne0YT** [comment]
@CodingWonders thank you.
would be great if it worked out of the box.

**Comment by ne0YT** [comment]
> @ne0YT, to reinstate Remote Desktop Connection, you will need to enable the `Microsoft-RemoteDesktopConnection` feature. This will reinstall the Remote Desktop Connection application

can you give me the whole command to do so? smh I'm not getting it.

**Comment by CodingWonders** [comment]
@ne0YT, the command is `dism /online /enable-feature /featurename=Microsoft-RemoteDesktopConnection /all`

**Comment by welchdigital** [comment]
Also having this issue. MicroWin on Windows 11 Pro 23H2. Neither Remote Desktop from the Microsoft Store nor Remote Desktop Connection (mstsc.exe) work. RDC Server works fine, just the client that seems to not work. mstsc.exe was restored using the above DISM command, processed without error and restored mstsc.exe, but does not seem to work. Old install of 23H2 (non MicroWin) works fine. Event viewer shows no errors that I can see

**Comment by jzetterman** [comment]
It would be really nice to have this either added back to the MicroWin image or to have it added in the WinUtil app to install as an option.

**Comment by CodingWonders** [comment]
@jzetterman, #2853 fixes the issue
