### ISSUE TITLE
MicroWIN generating corrupted ISO for VM

### ISSUE THREAD

**Issue by FedeP14** [ChrisTitusTech/winutil#2706]
## Describe the bug
MicroWIN generate an ISO that make VM (VMWare Workstation 17) goes on BSOD during installing

## To Reproduce
1. Create a virtual machine with any settings
2. Install ISO on the VM
3. proceed with the installation until you get to the final download and install view (before the restart)
4. Wait until the the BSOD appear (it should appear after it finishes the download)

## Expected behavior
The ISO should be installed successfully

## Additional context
Using the default windows 11 ISO works

**Comment by CodingWonders** [comment]
@FedeP14, I can't reproduce this issue. The image is generated and installed successfully. Try checking the integrity of your original image

**Comment by FedeP14** [comment]
Ok the issue it's that the iso provided by microsoft goes in blue screen, only that one time boot correctly.
I close the issue because is not a winutil probelm like I wrongfully tought, but i don't know what to do now..
