### ISSUE TITLE
download count per release not working

### ISSUE THREAD

**Issue by MyDrift-user** [ChrisTitusTech/winutil#2708]
## Describe the bug

Since Release-Drafter was added it removed the counter from the releases.
idk if it is possible to include this into the release drafter's "template" of how the readdition of the feature would work..

new:
![image](https://github.com/user-attachments/assets/186b2a6c-5700-4ed2-954b-60a9ae054e78)
old:
![image](https://github.com/user-attachments/assets/88f596d5-ca66-46ec-b431-bffc5c08dabb)

**Comment by Real-MullaC** [comment]
@MyDrift-user Ask Chris first as it is easy to add back but he removed it.

**Comment by ChrisTitusTech** [comment]
Yeah I been working on getting release-drafter setup right. Been a thorn in my side, but the next release should be good.

**Comment by MyDrift-user** [comment]
Latest release seems to fix the Issue, thanks :)

Will close this Issue now.
