### ISSUE TITLE
Latest update won't apply tweaks

### ISSUE THREAD

**Issue by mserdardogan** [ChrisTitusTech/winutil#2711]
## Describe the bug
Latest update doesn't apply any tweaks. Command line prints *tweaks are finished* without applying any tweaks at all.

## To Reproduce
1. Open WinUtil
2. Select one or more tweaks
3. Hit "Run tweaks"
4. See the "tweaks finished" message immediatly without any tweaks applied

## Expected behavior
Applying tweaks.

## Screenshots
![Ekran Görüntüsü (2)](https://github.com/user-attachments/assets/057b2258-8541-4b41-a69c-e2f19ec775b8)

**Comment by AksharDP** [comment]
Experiencing the same issue.

**Comment by JsRoadYT** [comment]
Workaround until it gets fixed
[24.08.22](https://github.com/ChrisTitusTech/winutil/releases/tag/24.08.22)
[about_Execution_Policies](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4#long-description)

**Comment by Cryostrixx** [comment]
I'm also experiencing this issue. For anyone who wants to revert to the last working release, here's how to run it:

1. Open the Start menu.
2. Search for **Terminal** or **PowerShell** (whichever you prefer).
3. Right-click on it and select **Run as administrator**.
4. Copy and paste the following commands into your console:
```powershell
Invoke-RestMethod -Uri https://github.com/ChrisTitusTech/winutil/releases/download/24.08.22/winutil.ps1 -OutFile "$env:USERPROFILE\Downloads\winutil-24.08.22.ps1"
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
Invoke-Expression "$env:USERPROFILE\Downloads\winutil-24.08.22.ps1"
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
```
5. Press **Enter** to execute the commands.
6. If you receive a warning about the script being from an untrusted publisher, type `R` and press **Enter** to proceed. The script comes directly from this repository and is safe to use.

**Comment by BNSoul** [comment]
Experiencing the exact same issue here, Windows 11 Pro 23H2 build 22631.4169

**Comment by chrisnitro2000** [comment]
I state that I have the same issue with windows 11 pro 23H2 latest build , to be honest glad is an issue with utility , I formatted with different os versions 3 times :)

**Comment by Marterich** [comment]
Issue got fixed in the meantime /close
