### ISSUE TITLE
Cannot Install Any Program

### ISSUE THREAD

**Issue by LeventKaanOguz** [ChrisTitusTech/winutil#2724]
## Describe the bug

Cannot install any of the chocolatey packages except for pyenv

## To Reproduce
Try to install any application

## Expected behavior

Installing all apps

## Screenshots

![image](https://github.com/user-attachments/assets/7b398fb7-8fd8-4b0b-ae68-6186e082ad60)

## Additional context

My export: 
[deneme.json](https://github.com/user-attachments/files/16983769/deneme.json)

**Comment by Real-MullaC** [comment]
Please try with the following command - 

`irm christitus.com/windev | iex`

As there could be an issue with the main release.

**Comment by LeventKaanOguz** [comment]
> `irm christitus.com/windev | iex`

sadly i have the same issue with the dev version.
