### ISSUE TITLE
Auto Label PRs

### ISSUE THREAD

**Issue by MyDrift-user** [ChrisTitusTech/winutil#2730]
**Is your feature request related to a problem? Please describe.**

@ChrisTitusTech manually has to set labels on PRs which can be time consuming.

**Describe the solution you'd like**

A GitHub workflow that runs like the Compile & Check / Compile-and-Check for PRs.

It could use RegEx to look throught the body of the PR. It looks for markdown checkboxes and checks if specific ones with specific text after them are checked. With that Info it then labels the PR correctly. Due to the check running often the labeling should also get modified after you modify the body.

Example:

```
## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement
```

- "Bug fix", "Security patches" & "Hotfix" get the label "bug"
- "New feature" gets the label "enhancement"
- "Documentation update" gets the label "documentation"
- refractor looks to technical for a normal user to care about, not adding a label will just put those under the unlabeled ones.
- idk about UI/UX improvements, maybe none or add a custom label

**Comment by Real-MullaC** [comment]
Thats sounds like a good idea.

**Comment by MyDrift-user** [comment]
This is getting closed due to Chris rejecting the Idea on linutil.
/close
