### ISSUE TITLE
[MicroWin] Screenshotting Broken Without Snipping Tool

### ISSUE THREAD

**Issue by Samq64** [ChrisTitusTech/winutil#2736]
## Describe the bug

By default MicroWin strips out Snipping Tool which, at least on WIndows 11 23H2 is required for screenshotting. The older overlay still appears but there is no notification and the screenshot is never saved. Turning off the setting to use snipping tool when pressing print screen doesn't seem to help.

## To Reproduce
1. Install WIndows 11 23H2 using MicroWin
2. Try to take a sreenshot
3. Open the Pictures folder
4. Install Snipping Tool from the Microsoft Store
5. Take another screenshot

## Expected behavior

Screenshotting should work out of the box when using MicroWin.

## Additional context

The advanced debloat tweak also removes it. Maybe that should be reconsidered too?

**Comment by CodingWonders** [comment]
@Samq64, a fix is on its way

![image](https://github.com/user-attachments/assets/cdbffe86-4d2a-495f-8037-56798f2a2c1c)
