### ISSUE TITLE
Micro win for my new laptop 

### ISSUE THREAD

**Issue by basitsheikhabdul** [ChrisTitusTech/winutil#2740]
I have just got a new laptop and it came with lots of crap. Should I re install windows by making a new microwin  iso from winutil. Please help me with this.

**Comment by back-lacking** [comment]
i mean, you can

**Comment by SHR1SHAK** [comment]
if your laptop comes with Windows try to reinstall windows with iso. do not just reset and call it a day as it will not remove the preinstalled bloat and antivirus like mcafee, norton or others. if you are 100% sure and have some knowledge in working of microwin or join the discord for help. And even while reinstalling with windows with USB modern laptop sometimes have driver issue that will led to not showing your SSD on the disk page. So make sure you can do this.

conclusion: Reinstall with iso. Set to world for 0 bloat. then use winutil for tweaks. use 23h2. Dont use latest windows builds.
