### ISSUE TITLE
show seconds in taskbar clock - registry tweak/hack

### ISSUE THREAD

**Issue by 0000xFFFF** [ChrisTitusTech/winutil#2743]
I think it would be nice to add a tweak to show seconds in the taskbar's clock.

![seconds_in_taskbar_clock](https://github.com/user-attachments/assets/a540ec5f-ea61-4f1f-a749-c0e190e9d328)

registry hack:
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowSecondsInSystemClock"=dword:00000001
```

**Comment by Marterich** [comment]
Although you can enable the feature like you described, i think for most people this wouldn't be relevant. 
Also theres a Blogpost by Microsoft why enabling seconds on the Taskbar might not be a smart decision. 
TLDR: It has to do with performance and CPU Powerstates (Energy Saving)
https://devblogs.microsoft.com/oldnewthing/20220411-00/?p=106456
