### ISSUE TITLE
Online Accounts Option and some more Unattended Stuff

### ISSUE THREAD

**Issue by LeventKaanOguz** [ChrisTitusTech/winutil#2744]
**Is your feature request related to a problem? Please describe.**

Well, there is no actual problems but local account can be an option rather then a must. All gamepass players must login and it seems like a good option. (Not necessary though, since windows 11 s- at usernames it can be a better choice to enter some kind of leventkaanoguz rather than leven (win 11 takes first 5 letters as username as you know)). And also, since most programs dont like it, user name can be forced to no space, no-non-english letters.

Also we can enter the key at the microwin rather than on setup, this can make installation _more_ unattended.

If microwin is going to install on the same PC or laptop, etc, there can be option for disk partitioning like how microwin can automatically injects drivers from current win11 install.

Maybe iso-creation-stage program install and tweaks

**Describe the solution you'd like**

1- Option to use local accounts
2- Licence key on microwin iso creation
3- iso-creation stage disk partition and settings
4- iso-creation-stage program install and tweaks

**Describe alternatives you've considered**

**Additional context**

**Comment by CodingWonders** [comment]
1. Duh...
2. You can run `slui` to go to the activation settings, from which you can change your product key
3. It's best to let the user decide right before the installation
4. Someone else had asked that before. I made that request possible with a PR, but it got closed because it added bloat to MicroWin

**Comment by LeventKaanOguz** [comment]
> 1. Duh...
> 
>     2. You can run `slui` to go to the activation settings, from which you can change your product key
> 
>     3. It's best to let the user decide right before the installation
> 
>     4. Someone else had asked that before. I made that request possible with a PR, but it got closed because it added bloat to MicroWin

Tysm for all the replies, and i totally agree with the duh part
