### ISSUE TITLE
Enable Numlock Tweek is not working.

### ISSUE THREAD

**Issue by Ravi-Kishor** [ChrisTitusTech/winutil#276]
I am using a laptop..so I apply laptop tweeks, but Enable Numlock Tweek is not working. It is very handy for people with Numpad to type  login passcode.

Plz look into this.

Btw love this. U are Amazing

**Comment by ChrisTitusTech** [comment]
Unable to replicate. The enable and disable are done via registry key. There is other spots this can be disabled or enabled on a hardware level. Closing issue.
