### ISSUE TITLE
167 processes fresh install 

### ISSUE THREAD

**Issue by rgfx** [ChrisTitusTech/winutil#2764]
Is this normal? Running 32gbs of memory maybe that why in the latest video on 60 processes showed.

**Comment by zdziejowski** [comment]
It is normal. 60 each processes you can get after add all tweaks from winutil after install.

**Comment by rgfx** [comment]
> It is normal. 60 each processes you can get after add all tweaks from winutil after install.

I see, I thought it was all built into the ISO, I ran standard and am down to 100 processes.

Thanks
