### ISSUE TITLE
Not loading Dev

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#2765]
## To Reproduce
![ScreenShot_20240918122110](https://github.com/user-attachments/assets/930c2ff0-a4c3-4b6a-b0bb-dca12a889174)

**Comment by Cryostrixx** [comment]
Hello, @FatBastard0!

I'm currently working on a fix for this issue, along with some other updates in `windev.ps1`. The changes are still in-development, but I plan to create a PR for them within the next couple of days. Thanks for your patience!

**Comment by FatBastard0** [comment]
Thanks for looking at the issue

**Comment by Cryostrixx** [comment]
> Thanks for looking at the issue

No problem! I've actually been working on this for five days now, I experienced a similar problem, here's the error I get when trying to run it as a normal user:
```
Unable to determine latest pre-release version.
Using latest Full Release
Winutil needs to be run as Administrator. Attempting to relaunch.
Start-Process:
Line |
  68 |      Start-Process $processCmd -ArgumentList "$powershellcmd -Executio …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: An error occurred trying to start process 'C:\Users\#####\AppData\Local\Microsoft\WindowsApps\wt.exe' with working directory 'C:\Users\#####'. The parameter is incorrect.
Winutil needs to be run as Administrator. Attempting to relaunch.
```

In my local copy of `windev.ps1`, the version I am developing, it now launches as an administrator with no issues, as shown below.
![Screenshot_1](https://github.com/user-attachments/assets/314ac9b1-291e-44db-8909-6b9e80ed6a6a)

**Comment by FatBastard0** [comment]
You tthe man, I am not good at given the right information, but I want to help, Thank you and Mr. WinUtil.

**Comment by FatBastard0** [comment]
Thanks, I'll look into it.
I would like to thank you in advance for any assistance that you can
provide in this matter. Please feel free to contact me at the below listed
address, Telephone and/or email.




Richard K. L'Italien
Disable Veteran of the US Army
The Fat Bastard
5637 Monte Corita Circle
Citrus Heights California 95621
(916) 915-3883 <http://voice.google.com/calls?a=nc,%2B19169153883>
<http://voice.google.com/calls?a=nc,%2B19169153883> Voice
(916) 943 4967 <http://voice.google.com/calls?a=nc,%2B19169434967>
<http://voice.google.com/calls?a=nc,%2B19167453437>

******************************************************************************
This communication (including any attachments) may contain privileged or
confidential information intended for a specific individual and purpose,
and is protected by law.  If you are not the intended recipient, you should
delete this communication and/or shred the materials and any attachments and
are hereby notified that any disclosure, copying, or distribution of this
communication, or the taking of any action based on it, is strictly
prohibited.

Thank you.

**Comment by Cryostrixx** [comment]
> Thanks, I'll look into it. I would like to thank you in advance for any assistance that you can provide in this matter. Please feel free to contact me at the below listed address, Telephone and/or email. Richard K. L'Italien Disable Veteran of the US Army The Fat Bastard 5637 Monte Corita Circle Citrus Heights California 95621 (916) 915-3883 <http://voice.google.com/calls?a=nc,%2B19169153883> <http://voice.google.com/calls?a=nc,%2B19169153883> Voice (916) 943 4967 <http://voice.google.com/calls?a=nc,%2B19169434967> <http://voice.google.com/calls?a=nc,%2B19167453437> ****************************************************************************** This communication (including any attachments) may contain privileged or confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this communication and/or shred the materials and any attachments and are hereby notified that any disclosure, copying, or distribution of this communication, or the taking of any action based on it, is strictly prohibited. Thank you.
> […](#)

Hey @FatBastard0! I’m not sure if you meant to send this here, but if it contains any personal information, I strongly suggest deleting the message immediately. It’s not safe to share personal details publicly on the internet.
