### ISSUE TITLE
Tweaks export/import bug.

### ISSUE THREAD

**Issue by Garou7** [ChrisTitusTech/winutil#2772]
## Describe the bug
If you select the standard tweaks then export it & import it, everything is same except `Change Windows Terminal default` is automatically selected.

## Expected behavior
Exported config should be the same as per user choice.

## Screenshots
Export:
![B](https://github.com/user-attachments/assets/42fcab4b-a5d8-484e-b9e5-0adbb898e745)
Import:
![A](https://github.com/user-attachments/assets/83dedc43-80c1-4e8f-a186-1b5fdadb8a50)

**Comment by Cryostrixx** [comment]
Hello, @Garou7! Thanks for the report!
I just tested this and I wasn't able to replicate the issue you showed in your first screenshot, I used a config with `WPFTweaksPowershell7Tele` as the only feature enabled, and `Change Windows Terminal default: PowerShell 5 -> PowerShell 7` is appropriately checked alongside `Disable PowerShell 7 tele`, as PowerShell 7 telemetry can't be disabled if PowerShell 7 is not installed:
![image](https://github.com/user-attachments/assets/03959515-1d54-4e76-9f1f-cce30d79934d)

Can you upload your configuration file here so I can take a look at it and see if you have `WPFTweaksPowershell7Tele` enabled?

**Comment by Garou7** [comment]
@Cryostrixx I think i found the culprit `Disable Powershell 7 Telemetry`, if you select ANY checkbox in tweaks with `Disable Powershell 7 Telemetry` & ignore the `Change Windows Terminal default` then import & export it will automatically select the `Change Windows Terminal default` even tho you didnt choose it.

## Another example:
Export:
![t2](https://github.com/user-attachments/assets/55ee33e9-4de5-4b1e-a1a7-8b619d98bebb)

Import:
![t3](https://github.com/user-attachments/assets/37d67ffa-c01f-49ec-a698-6910cda970b8)

**Comment by Cryostrixx** [comment]
> @Cryostrixx I think i found the culprit `Disable Powershell 7 Telemetry`, if you select ANY checkbox in tweaks with `Disable Powershell 7 Telemetry` & ignore the `Change Windows Terminal default` then import & export it will automatically select the `Change Windows Terminal default` even tho you didnt choose it.
> 
> ## Another example:
> Export: ![t2](https://private-user-images.githubusercontent.com/113905482/369434073-55ee33e9-4de5-4b1e-a1a7-8b619d98bebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDE4NzMsIm5iZiI6MTcyNjg0MTU3MywicGF0aCI6Ii8xMTM5MDU0ODIvMzY5NDM0MDczLTU1ZWUzM2U5LTRkZTUtNGIxZS1hMWE3LThiNjE5ZDk4YmViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNDEyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjYwN2Y3NDliZTk0ZjI0OWQ2MjdjZTQ4OWYxNDg1OGE5YjYxNzZiZDIxZGQ1ZWRkMWU3ZDRmN2UwZDU4ZTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3UqOhTlkvmawiXX1gILYAFFhYlSG8wxrXB4sB9ec9EA)
> 
> Import: ![t3](https://private-user-images.githubusercontent.com/113905482/369434149-37d67ffa-c01f-49ec-a698-6910cda970b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDE4NzMsIm5iZiI6MTcyNjg0MTU3MywicGF0aCI6Ii8xMTM5MDU0ODIvMzY5NDM0MTQ5LTM3ZDY3ZmZhLWMwMWYtNDllYy1hNjk4LTY5MTBjZGE5NzBiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNDEyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODA0Mzc3NjJkMDEwOTUwZDFiZWE2MGM2MWNjZThlMTAyM2MwNTdmY2M2N2NhZGFmODljZjJhNjdhMjUxMjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pepzffTDn1mugvFrgFUtNn3ZF8RLdpK9GzMWkDOJ9l8)

I understand where you are coming from but this is intended behavior, PowerShell 7 telemetry is specific to PowerShell 7, here's my config:
```
{
  "WPFFeature": [
    "WPFFeatureEnableLegacyRecovery",
    "WPFFeaturesdotnet",
    "WPFFeatureslegacymedia",
    "WPFFeatureDisableSearchSuggestions"
  ],
  "WPFInstall": [],
  "WPFTweaks": [
    "WPFTweaksRestorePoint",
    "WPFTweaksAH",
    "WPFTweaksDebloatAdobe",
    "WPFTweaksHome",
    "WPFTweaksHiber",
    "WPFTweaksPowershell7Tele",
    "WPFTweaksDisableLMS1",
    "WPFTweaksBlockAdobeNet",
    "WPFTweaksLaptopHibernation",
    "WPFTweaksEdgeDebloat",
    "WPFTweaksDVR",
    "WPFTweaksRemoveHomeGallery",
    "WPFTweaksStorage",
    "WPFTweaksRightClickMenu",
    "WPFTweaksServices",
    "WPFTweaksTele",
    "WPFTweaksEndTaskOnTaskbar",
    "WPFTweaksLoc",
    "WPFTweaksDiskCleanup",
    "WPFTweaksWifi",
    "WPFTweaksRemoveCopilot",
    "WPFTweaksConsumerFeatures",
    "WPFTweaksRemoveOnedrive",
    "WPFTweaksRemoveEdge",
    "WPFTweaksDeleteTempFiles"
  ],
  "Install": []
}
```

I don't have `WPFTweaksPowerShell7` in my config but I do have `WPFTweaksPowerShell7Tele`, one feature cannot be enabled without the other, if you don't have PowerShell 7 its telemetry cannot be disabled, so the option to replace PowerShell 5 with PowerShell 7 is checked, as the tooltip for `Change Windows Terminal default: PowerShell 5 -> PowerShell 7` says: `This will edit the config file of the Windows Terminal replacing PowerShell 5 with PowerShell 7 and installing PS7 if necessary`.
You can test this for yourself by downloading this config: [winutil-test.json](https://github.com/user-attachments/files/17076441/winutil-test.json), it only has `Disable PowerShell 7 Telemetry` enabled, import it and you'll see that `Change Windows Terminal default: PowerShell 5 -> PowerShell 7` is checked as a dependency for `Disable PowerShell 7 Telemetry`.

**Comment by Cryostrixx** [comment]
@Garou7 Update: I just checked the code for WPFTweaksPowerShell7Tele and I don't see anything that would enable WPFTweaksPowerShell7.
I'll dig through the code and see if I can determine what is causing this issue.

**Comment by Cryostrixx** [comment]
@Garou7 I looked through all the code, and I couldn't find anything that enables `Change Windows Terminal default: PowerShell 5 -> PowerShell 7` when `Disable PowerShell 7 Telemetry` is enabled, for now, what I'd suggest you do is manually uncheck `Change Windows Terminal Default: PowerShell 5 -> PowerShell 7` each time you import your config. It isn't ideal but it'll only take a few seconds to do each time, in the meantime, you should provide a few things in this issue:
1. Your operating system version (you can get to this by opening your start menu, typing `winver.exe`, and hitting Enter).
2. Your Windows Terminal version, you can get this by opening Windows Terminal, typing `wt --version`, and hitting Enter.
3. Your Windows PowerShell version information, you can get this by opening PowerShell, typing `$PSVersionTable`, and hitting Enter.
4. Your WinUtil version, you can access this by clicking the settings cog on the top right, and clicking on `About`.
5. The tweaks and features you use with WinUtil, for this the easiest way to share that is to upload your WinUtil configuration file here.

Copy and paste all of this information and send it in the comments, it will make it as easy as possible for contributors to replicate your environment as closely as possible and perform further testing.

**Comment by Cryostrixx** [comment]
@Garou7 That's a known issue i think, another contributor would have to confirm that for me, I'll test the issue you reported initially with the information you provided when I get back to my device that has WinUtil on it.

**Comment by Cryostrixx** [comment]
> Where I can find the WinUtil configuration file?

@Garou7 Oh, I didn't see that part, sorry! If you have a WinUtil configuration file it should be in your Documents folder: `C:\Users\<your-username-here>\Documents`, if it isn't in your `Documents` folder the other common path to save config files is in `C:\Users\<your-username-here>\Desktop`.
If you don't know where it is stored you can navigate to the `C:\` drive in File Explorer and search for the name of your config file, Right-click, and select `Open file location`.
