### ISSUE TITLE
Sound mixer settings keeps resetting

### ISSUE THREAD

**Issue by Mystream90** [ChrisTitusTech/winutil#2776]
## Describe the bug
I used MicroWin to install a debloated version of Windows 11. With this version, my sound mixer does not save the changes when I adjust the volume (e.g., system sounds, Discord, etc.). I've seen others with the same issue using MicroWin. Applying the fix mentioned in issue #2747 helps save the volume adjustments after closing the sound window or restarting the PC. However, if I receive a notification from any application, the sound settings reset.
 

## To Reproduce
1. Debloat Windows 11 with MicroWin.
2. Install the debloated Windows 11.
3. Let Windows download and install all updates.
4. Restart your PC as many times as needed for the updates.
5. Adjust the system sound in the sound mixer.
6. Close the window.
7. Open the sound mixer window again (at this point, the settings should already be reset because the fix hasn't been applied yet).
8. Apply the fix mentioned (this should work after closing the sound window and restarting the PC).
9. Trigger any notification from Windows (the sound settings should reset again).
10. Open the sound mixer and check that all changes have been reset.

## Expected behavior
Sound adjustments should been saved.

## Screenshots
-

## Additional context
-

**Comment by Mystream90** [comment]
I did some more research on this bug. It only occurs with notifications from third-party applications. Turning off the notification sound "fixes" it, but this is not a proper solution. It’s important to note that this issue is not specific to MicroWin, as I tested it on a fresh, untouched Windows installation and encountered the same problem.

**Comment by Mihuy1** [comment]
I also have this after installing Windows 11 with MicroWin... Really annyoing

**Comment by CodingWonders** [comment]
Fixed with #2853. /close
