### ISSUE TITLE
Stuck in removing Microsoft Teams

### ISSUE THREAD

**Issue by TigercatVIP** [ChrisTitusTech/winutil#278]
**Describe the bug**
When selecting and using the option to remove all Microsoft store apps in the Tweaks section of the W/Utility, it get stuck on trying to remove Microsoft Teams, saying the Teams installation hasn't been found

**To Reproduce**
The Utility, go to Tweaks section, select only Remove All Microsoft Store Apps, and then click on Run Tweaks

 Run Tweaks

WARNING: Teams installation not found
Process user: Angel
WARNING: Teams installation not found for user Angel
Process user: defaultuser0
WARNING: Teams installation not found for user defaultuser0
Process user: Public
WARNING: Teams installation not found for user Public

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/97904746/196250210-d66abe70-a3fa-4513-9aa6-f1d07672a5e4.png)

**Additional context**

**Comment by ChrisTitusTech** [comment]
Just pushed a massive conversion with extra checks so this doesn't happen.
