### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Bhooty** [ChrisTitusTech/winutil#279]
I recently reinstalled windows 10 21h2 on my laptop and desktop and found that if I use the tool to enforce only security updates then driver and update policy don’t apply though delivery optimisation was turned off via policy 

But upon upgrading to windows 10 pro, the security policies came to effect

so the update policy isn’t working on windows 10 home for some reason

**Comment by ChrisTitusTech** [comment]
Home doesn't allow GPOs and the newer version do not respond to the registry values. I used to bypass this, but I'm sure Microsoft will shutdown this as it is why people buy and use pro.

**Comment by Bhooty** [comment]
> Home doesn't allow GPOs and the newer version do not respond to the registry values. I used to bypass this, but I'm sure Microsoft will shutdown this as it is why people buy and use pro.

Thanks for replying and closing it 
Forgot to close it 😅
Yeah ended up just installing pro cause of that
