### ISSUE TITLE
Feature Request: Add Tools and Emulators to Winutil

### ISSUE THREAD

**Issue by SnabbSpelare** [ChrisTitusTech/winutil#2796]
**Is your feature request related to a problem? Please describe.**  
I'm often frustrated by the lack of certain useful tools and emulators in the current "winutil" package, which limits options for users who need these utilities for gaming and content creation.

**Describe the solution you'd like**  
Please add the following programs to the "winutil" repository:
- **Installer**: 
  - **ATLauncher**: A Minecraft launcher similar to Prism Launcher, developed by NodeCraft.
  - **Clownfish Voice Changer**: Voice changer software.
  
- **Portable**:  
  - **Crowbar**: A tool for Source Engine game models, maps, and Steam Workshop content. Crowbar is portable and not an installable program.

- **Emulators**:
  - **RPCS3**: A PlayStation 3 emulator.
  - **Xenia**: An Xbox 360 emulator.

- **Additional Tools**:
  - **Free Download Manager**: A powerful and free download accelerator and manager.
  - **Vortex**: A mod manager developed by Nexus Mods for various games.

Additionally, I suggest adding a feature to allow users to hide currently installed programs with a checkbox option in the GUI.

**Describe alternatives you've considered**  
Currently, users might download these tools from separate sources, which can be inconvenient and might lead to outdated versions being used.

**Additional context**  
These tools are widely used in the gaming community and could enhance the functionality of "winutil." Integrating them would provide users with a more comprehensive utility package.

**Comment by Cryostrixx** [comment]
Hello, @SnabbSpelare! Thanks for the report, but to give you a quick heads-up new applications currently aren't being added to WinUtil as the applications screen is very bloated.

**Comment by SnabbSpelare** [comment]
> Hello, @SnabbSpelare! Thanks for the report, but to give you a quick heads-up new applications currently aren't being added to WinUtil as the applications screen is very bloated.

Thanks for letting me know! Sad to hear that! Hopefully they'll add some categories to cleanup the interface, such as "Browsers" etc. Anyway I'll continue to add more to a offline list in case they accept any in the future!

**Comment by Cryostrixx** [comment]
> > Hello, @SnabbSpelare! Thanks for the report, but to give you a quick heads-up new applications currently aren't being added to WinUtil as the applications screen is very bloated.
> 
> Thanks for letting me know! Sad to hear that! Hopefully they'll add some categories to cleanup the interface, such as "Browsers" etc. Anyway I'll continue to add more to a offline list in case they accept any in the future!

I actually tried to do that at one point, it's a nice idea but it doesn't work very well, the headers get shifted to the wrong places as a result of how many applications are in the install tab.
Just keep any applications you want to add around and hopefully, they can be added in the future.
