### ISSUE TITLE
Enable Clipboard history

### ISSUE THREAD

**Issue by IdoPort** [ChrisTitusTech/winutil#2804]
**Is your feature request related to a problem? Please describe.**
After running the tweaks stage Windows blocks the option to use "Clipboard history"
<img width="770" alt="image" src="https://github.com/user-attachments/assets/c9404f36-278a-4171-8edc-e4bf36d320ff">

**Describe the solution you'd like**
Another checkbox or toggle in "Essential Tweaks" or "Customize Preferences"

**Comment by Marterich** [comment]
This is set by a tweak of O&O Shutup and not by winutil itself as far as I know. 
To enable it again, please start OO Shutup (under advanced tweaks), search for clipboard and enable the history again.

Most likely we will add a toggle for this in the future, but first we need to think of a way of grouping and displaying the tweaks so it doesn't become overwhelming (like the install tab)

**Comment by IdoPort** [comment]
Oh ok, thanks for the fast reply!

**Comment by tikacrabill** [comment]
You have 5 minutes to give me back my access to my computer, iPhone and all
my files. Remove everything off of my system. All my emails,data etc... DHS
will be involved after 5 minutes, 12/23/2024 @12:27am
