### ISSUE TITLE
PC that's very slow to restart and to turn off

### ISSUE THREAD

**Issue by Kyoshim** [ChrisTitusTech/winutil#283]
Hello,

I encountered a weird behavior after doing the Desktop Tweaks option.
My PC is right now really slow when i restart it or turn it off.
Before the Tweaks, it was a mater of seconds to restart or stop it.
Now, it's like 4 to 5 minutes.

Is there a backup somewhere to redo the process backward ?

Thanks

**Screenshots**
Here the option i used with the Desktop option :

![image](https://user-images.githubusercontent.com/5623682/196527411-f33bf099-de50-4bd2-a4de-c78eca049bc0.png)

**Additional context**
I am running on Windows 10.

**Comment by ChrisTitusTech** [comment]
Rerun the tweaks in 5 minutes from this message. 

Fixes have been implemented to fix this

**Comment by Kyoshim** [comment]
Hey Chris, 

Thanks for your repply.
I just noticed that i never got the windows that said that's the Tweaks are done, i waited for like 15 to 20 min and nothing.
So i just closed the PowerShell.
Maybe there is a bug that didn't end well the script ?

Here are all the logs from the Powershells :

> ====Chris Titus Tech=====
=====Windows Toolbox=====
COMMENTAIRES : 10/18/2022 22:48:00 | INFO | Gathering required modifications
COMMENTAIRES : 10/18/2022 22:48:00 | INFO | Starting Registry Modification
COMMENTAIRES : 10/18/2022 22:48:01 | INFO | Setting
HKLM:\Software\Microsoft\PolicyManager\default\WiFi\AllowWiFiHotSpotReporting\Value to 0
COMMENTAIRES : 10/18/2022 22:48:01 | INFO | Setting
HKLM:\Software\Microsoft\PolicyManager\default\WiFi\AllowAutoConnectToWiFiSenseHotspots\Value to 0
COMMENTAIRES : 10/18/2022 22:48:01 | INFO | Setting
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection\AllowTelemetry to 0
COMMENTAIRES : 10/18/2022 22:48:01 | INFO | Setting
HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection\AllowTelemetry to 0
COMMENTAIRES : 10/18/2022 22:48:02 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\ContentDeliveryAllowed to 0
COMMENTAIRES : 10/18/2022 22:48:02 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\OemPreInstalledAppsEnabled to 0
COMMENTAIRES : 10/18/2022 22:48:02 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\PreInstalledAppsEnabled to 0
COMMENTAIRES : 10/18/2022 22:48:03 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\PreInstalledAppsEverEnabled to 0
COMMENTAIRES : 10/18/2022 22:48:03 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SilentInstalledAppsEnabled to 0
COMMENTAIRES : 10/18/2022 22:48:03 | INFO | Setting
HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-338387Enabled to 0
COMMENTAIRES : 10/18/2022 22:48:03 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-338388Enabled to 0
COMMENTAIRES : 10/18/2022 22:48:04 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-338389Enabled to 0
COMMENTAIRES : 10/18/2022 22:48:04 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-353698Enabled to 0
COMMENTAIRES : 10/18/2022 22:48:04 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SystemPaneSuggestionsEnabled to 0
COMMENTAIRES : 10/18/2022 22:48:04 | INFO | Setting
HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent\DisableWindowsConsumerFeatures to 1
COMMENTAIRES : 10/18/2022 22:48:05 | INFO | Setting HKCU:\SOFTWARE\Microsoft\Siuf\Rules\NumberOfSIUFInPeriod to 0
COMMENTAIRES : 10/18/2022 22:48:05 | INFO | Setting
HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection\DoNotShowFeedbackNotifications to 1
COMMENTAIRES : 10/18/2022 22:48:05 | INFO | Setting
HKCU:\SOFTWARE\Policies\Microsoft\Windows\CloudContent\DisableTailoredExperiencesWithDiagnosticData to 1
COMMENTAIRES : 10/18/2022 22:48:05 | INFO | Setting
HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo\DisabledByGroupPolicy to 1
COMMENTAIRES : 10/18/2022 22:48:06 | INFO | Setting HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\Disabled
to 1
COMMENTAIRES : 10/18/2022 22:48:06 | INFO | Setting
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config\DODownloadMode to 1
COMMENTAIRES : 10/18/2022 22:48:06 | INFO | Setting HKLM:\SYSTEM\CurrentControlSet\Control\Remote
Assistance\fAllowToGetHelp to 0
COMMENTAIRES : 10/18/2022 22:48:06 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager\EnthusiastMode to 1
COMMENTAIRES : 10/18/2022 22:48:07 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\ShowTaskViewButton to 0
COMMENTAIRES : 10/18/2022 22:48:07 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People\PeopleBand to 0
COMMENTAIRES : 10/18/2022 22:48:07 | INFO | Setting
HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\LaunchTo to 1
COMMENTAIRES : 10/18/2022 22:48:08 | INFO | Setting
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching\SearchOrderConfig to 00000000
COMMENTAIRES : 10/18/2022 22:48:08 | INFO | Setting HKLM:\SOFTWARE\Microsoft\Windows
NT\CurrentVersion\Multimedia\SystemProfile\SystemResponsiveness to 0000000a
COMMENTAIRES : 10/18/2022 22:48:08 | INFO | Setting HKLM:\SOFTWARE\Microsoft\Windows
NT\CurrentVersion\Multimedia\SystemProfile\NetworkThrottlingIndex to 0000000a
COMMENTAIRES : 10/18/2022 22:48:08 | INFO | Setting HKLM:\SYSTEM\CurrentControlSet\Control\WaitToKillServiceTimeout to
2000
COMMENTAIRES : 10/18/2022 22:48:09 | INFO | HKLM:\Control Panel\Desktop did not exist. Creating
COMMENTAIRES : 10/18/2022 22:48:09 | INFO | Setting HKLM:\Control Panel\Desktop\MenuShowDelay to 0
COMMENTAIRES : 10/18/2022 22:48:09 | INFO | HKLM:\Control Panel\Desktop did not exist. Creating
COMMENTAIRES : 10/18/2022 22:48:09 | INFO | Setting HKLM:\Control Panel\Desktop\WaitToKillAppTimeout to 5000
COMMENTAIRES : 10/18/2022 22:48:10 | INFO | HKLM:\Control Panel\Desktop did not exist. Creating
COMMENTAIRES : 10/18/2022 22:48:10 | INFO | Setting HKLM:\Control Panel\Desktop\AutoEndTasks to 1
COMMENTAIRES : 10/18/2022 22:48:10 | INFO | HKLM:\Control Panel\Desktop did not exist. Creating
COMMENTAIRES : 10/18/2022 22:48:10 | INFO | Setting HKLM:\Control Panel\Desktop\LowLevelHooksTimeout to 00001000
COMMENTAIRES : 10/18/2022 22:48:11 | INFO | HKLM:\Control Panel\Desktop did not exist. Creating
COMMENTAIRES : 10/18/2022 22:48:11 | INFO | Setting HKLM:\Control Panel\Desktop\WaitToKillServiceTimeout to 00002000
COMMENTAIRES : 10/18/2022 22:48:11 | INFO | Setting HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory
Management\ClearPageFileAtShutdown to 00000000
COMMENTAIRES : 10/18/2022 22:48:11 | INFO | Setting HKLM:\SYSTEM\ControlSet001\Services\Ndu\Start to 00000004
COMMENTAIRES : 10/18/2022 22:48:12 | INFO | HKLM:\Control Panel\Mouse did not exist. Creating
COMMENTAIRES : 10/18/2022 22:48:12 | INFO | Setting HKLM:\Control Panel\Mouse\MouseHoverTime to 00000010
COMMENTAIRES : 10/18/2022 22:48:12 | INFO | Setting
HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\IRPStackSize to 20
COMMENTAIRES : 10/18/2022 22:48:12 | INFO | Setting HKCU:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds\EnableFeeds
 to 0
COMMENTAIRES : 10/18/2022 22:48:13 | INFO | Setting
HKCU:\Software\Microsoft\Windows\CurrentVersion\Feeds\ShellFeedsTaskbarViewMode to 2
COMMENTAIRES : 10/18/2022 22:48:13 | INFO | Setting
HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\HideSCAMeetNow to 1
COMMENTAIRES : 10/18/2022 22:48:13 | INFO | Setting HKLM:\SOFTWARE\Policies\Microsoft\Windows\System\EnableActivityFeed
 to 0
COMMENTAIRES : 10/18/2022 22:48:14 | INFO | Setting
HKLM:\SOFTWARE\Policies\Microsoft\Windows\System\PublishUserActivities to 0
COMMENTAIRES : 10/18/2022 22:48:14 | INFO | Setting
HKLM:\SOFTWARE\Policies\Microsoft\Windows\System\UploadUserActivities to 0
COMMENTAIRES : 10/18/2022 22:48:14 | INFO | Setting \ to
COMMENTAIRES : 10/18/2022 22:48:14 | INFO | Setting
HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling\PowerThrottlingOff to 00000001
COMMENTAIRES : 10/18/2022 22:48:15 | INFO | Setting HKLM:\SYSTEM\CurrentControlSet\Control\Session
Manager\Power\HiberbootEnabled to 0000000
COMMENTAIRES : 10/18/2022 22:48:15 | INFO | Setting \ to
COMMENTAIRES : 10/18/2022 22:48:15 | INFO | Setting \ to
COMMENTAIRES : 10/18/2022 22:48:15 | INFO | Setting
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location\Value to Deny
COMMENTAIRES : 10/18/2022 22:48:16 | INFO | Setting HKLM:\SOFTWARE\Microsoft\Windows
NT\CurrentVersion\Sensor\Overrides\{BFA794E4-F964-4FDB-90F6-51056BFE4B44}\SensorPermissionState to 0
COMMENTAIRES : 10/18/2022 22:48:16 | INFO | Setting
HKLM:\SYSTEM\CurrentControlSet\Services\lfsvc\Service\Configuration\Status to 0
COMMENTAIRES : 10/18/2022 22:48:16 | INFO | Setting HKLM:\SYSTEM\Maps\AutoUpdateEnabled to 0
COMMENTAIRES : 10/18/2022 22:48:16 | INFO | Setting HKLM:\System\CurrentControlSet\Control\Session
Manager\Power\GameDVR_DXGIHonorFSEWindowsCompatible to 0
COMMENTAIRES : 10/18/2022 22:48:17 | INFO | Setting
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings\GameDVR_HonorUserFSEBehaviorMode to 0
COMMENTAIRES : 10/18/2022 22:48:17 | INFO | Setting \ to
COMMENTAIRES : 10/18/2022 22:48:17 | INFO | Setting \ to
COMMENTAIRES : 10/18/2022 22:48:17 | INFO | Setting \ to
COMMENTAIRES : 10/18/2022 22:48:18 | INFO | Setting HKLM:\System\GameConfigStore\GameDVR_DXGIHonorFSEWindowsCompatible
to 00000000
COMMENTAIRES : 10/18/2022 22:48:18 | INFO | Setting HKLM:\System\GameConfigStore\GameDVR_HonorUserFSEBehaviorMode to
00000000
COMMENTAIRES : 10/18/2022 22:48:18 | INFO | Setting HKLM:\System\GameConfigStore\GameDVR_EFSEFeatureFlags to 00000000
COMMENTAIRES : 10/18/2022 22:48:19 | INFO | Setting HKLM:\System\GameConfigStore\GameDVR_Enabled to 00000000
COMMENTAIRES : 10/18/2022 22:48:19 | INFO | Finished setting registry
COMMENTAIRES : 10/18/2022 22:48:19 | INFO | Starting Services Modification
COMMENTAIRES : 10/18/2022 22:48:19 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:20 | INFO | Service DiagTrack set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:20 | INFO | Service dmwappushservice set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:20 | INFO | Service SysMain set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:20 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:21 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:21 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:21 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:21 | INFO | Service HomeGroupListener set to  Manual
COMMENTAIRES : 10/18/2022 22:48:22 | INFO | Service HomeGroupProvider set to  Manual
COMMENTAIRES : 10/18/2022 22:48:22 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:22 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:22 | INFO | Service diagnosticshub.standardcollector.service set to  Manual
COMMENTAIRES : 10/18/2022 22:48:23 | INFO | Service DiagTrack set to  Manual
COMMENTAIRES : 10/18/2022 22:48:23 | INFO | Service DPS set to  Manual
COMMENTAIRES : 10/18/2022 22:48:23 | INFO | Service dmwappushservice set to  Manual
COMMENTAIRES : 10/18/2022 22:48:23 | INFO | Service lfsvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:24 | INFO | Service MapsBroker set to  Manual
COMMENTAIRES : 10/18/2022 22:48:24 | INFO | Service NetTcpPortSharing set to  Manual
COMMENTAIRES : 10/18/2022 22:48:24 | INFO | Service RemoteAccess set to  Manual
COMMENTAIRES : 10/18/2022 22:48:25 | INFO | Service RemoteRegistry set to  Manual
COMMENTAIRES : 10/18/2022 22:48:25 | INFO | Service SharedAccess set to  Manual
COMMENTAIRES : 10/18/2022 22:48:25 | INFO | Service TrkWks set to  Manual
COMMENTAIRES : 10/18/2022 22:48:25 | INFO | Service WMPNetworkSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:27 | INFO | Service WSearch set to  Manual
COMMENTAIRES : 10/18/2022 22:48:27 | INFO | Service XblAuthManager set to  Manual
COMMENTAIRES : 10/18/2022 22:48:27 | INFO | Service XblGameSave set to  Manual
COMMENTAIRES : 10/18/2022 22:48:27 | INFO | Service XboxNetApiSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:28 | INFO | Service XboxGipSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:28 | INFO | Service ndu set to  Manual
COMMENTAIRES : 10/18/2022 22:48:28 | INFO | Service WerSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:29 | INFO | Service Fax set to  Manual
COMMENTAIRES : 10/18/2022 22:48:29 | INFO | Service fhsvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:29 | INFO | Service gupdate set to  Manual
COMMENTAIRES : 10/18/2022 22:48:29 | INFO | Service gupdatem set to  Manual
COMMENTAIRES : 10/18/2022 22:48:30 | INFO | Service stisvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:30 | INFO | Service AJRouter set to  Manual
COMMENTAIRES : 10/18/2022 22:48:30 | INFO | Service MSDTC set to  Manual
COMMENTAIRES : 10/18/2022 22:48:30 | INFO | Service WpcMonSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:31 | INFO | Service PhoneSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:31 | INFO | Service PrintNotify set to  Manual
COMMENTAIRES : 10/18/2022 22:48:32 | INFO | Service PcaSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:32 | INFO | Service WPDBusEnum set to  Manual
COMMENTAIRES : 10/18/2022 22:48:32 | INFO | Service seclogon set to  Manual
COMMENTAIRES : 10/18/2022 22:48:33 | INFO | Service SysMain set to  Manual
COMMENTAIRES : 10/18/2022 22:48:33 | INFO | Service lmhosts set to  Manual
COMMENTAIRES : 10/18/2022 22:48:33 | INFO | Service wisvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:34 | INFO | Service FontCache set to  Manual
COMMENTAIRES : 10/18/2022 22:48:34 | INFO | Service RetailDemo set to  Manual
COMMENTAIRES : 10/18/2022 22:48:34 | INFO | Service ALG set to  Manual
COMMENTAIRES : 10/18/2022 22:48:35 | INFO | Service SCardSvr set to  Manual
COMMENTAIRES : 10/18/2022 22:48:35 | INFO | Service EntAppSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:35 | INFO | Service BthAvctpSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:36 | INFO | Service Browser set to  Manual
COMMENTAIRES : 10/18/2022 22:48:36 | INFO | Service BthAvctpSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:36 | INFO | Service iphlpsvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:36 | INFO | Service edgeupdate set to  Manual
COMMENTAIRES : 10/18/2022 22:48:37 | INFO | Service MicrosoftEdgeElevationService set to  Manual
COMMENTAIRES : 10/18/2022 22:48:37 | INFO | Service edgeupdatem set to  Manual
COMMENTAIRES : 10/18/2022 22:48:37 | INFO | Service SEMgrSvc set to  Manual
COMMENTAIRES : 10/18/2022 22:48:37 | INFO | Service PerfHost set to  Manual
COMMENTAIRES : 10/18/2022 22:48:38 | INFO | Service BcastDVRUserService_48486de set to  Manual
COMMENTAIRES : 10/18/2022 22:48:38 | INFO | Service CaptureService_48486de set to  Manual
COMMENTAIRES : 10/18/2022 22:48:38 | INFO | Service cbdhsvc_48486de set to  Manual
COMMENTAIRES : 10/18/2022 22:48:38 | INFO | Service WpnService set to  Manual
COMMENTAIRES : 10/18/2022 22:48:39 | INFO | Service RtkBtManServ set to  Manual
COMMENTAIRES : 10/18/2022 22:48:39 | INFO | Service QWAVE set to  Manual
COMMENTAIRES : 10/18/2022 22:48:39 | INFO | Service HPAppHelperCap set to  Manual
COMMENTAIRES : 10/18/2022 22:48:39 | INFO | Service HPDiagsCap set to  Manual
COMMENTAIRES : 10/18/2022 22:48:40 | INFO | Service HPNetworkCap set to  Manual
COMMENTAIRES : 10/18/2022 22:48:40 | INFO | Service HPSysInfoCap set to  Manual
COMMENTAIRES : 10/18/2022 22:48:40 | INFO | Service HpTouchpointAnalyticsService set to  Manual
COMMENTAIRES : 10/18/2022 22:48:41 | INFO | Service HvHost set to  Manual
COMMENTAIRES : 10/18/2022 22:48:41 | INFO | Service vmickvpexchange set to  Manual
COMMENTAIRES : 10/18/2022 22:48:41 | INFO | Service vmicguestinterface set to  Manual
COMMENTAIRES : 10/18/2022 22:48:41 | INFO | Service vmicshutdown set to  Manual
COMMENTAIRES : 10/18/2022 22:48:42 | INFO | Service vmicheartbeat set to  Manual
COMMENTAIRES : 10/18/2022 22:48:42 | INFO | Service vmicvmsession set to  Manual
COMMENTAIRES : 10/18/2022 22:48:42 | INFO | Service vmicrdv set to  Manual
COMMENTAIRES : 10/18/2022 22:48:42 | INFO | Service vmictimesync set to  Manual
COMMENTAIRES : 10/18/2022 22:48:43 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:43 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:43 | INFO | Service  set to
COMMENTAIRES : 10/18/2022 22:48:43 | INFO | Finished setting Services
COMMENTAIRES : 10/18/2022 22:48:44 | INFO | Starting ScheduledTask Modification
COMMENTAIRES : 10/18/2022 22:48:44 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:44 | INFO | Scheduled Task Microsoft\Windows\Application Experience\Microsoft
Compatibility Appraiser set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:45 | INFO | Scheduled Task Microsoft\Windows\Application Experience\ProgramDataUpdater
set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:45 | INFO | Scheduled Task Microsoft\Windows\Autochk\Proxy set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:45 | INFO | Scheduled Task Microsoft\Windows\Customer Experience Improvement
Program\Consolidator set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:46 | INFO | Scheduled Task Microsoft\Windows\Customer Experience Improvement
Program\UsbCeip set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:46 | INFO | Scheduled Task
Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:46 | INFO | Scheduled Task Microsoft\Windows\Feedback\Siuf\DmClient set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:46 | INFO | Scheduled Task Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload
set to  Disabled
COMMENTAIRES : 10/18/2022 22:48:47 | INFO | Scheduled Task Microsoft\Windows\Windows Error Reporting\QueueReporting set
 to  Disabled
COMMENTAIRES : 10/18/2022 22:48:47 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:47 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:47 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:48 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:48 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:48 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:48 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:49 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:49 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:49 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:50 | INFO | Scheduled Task  set to
COMMENTAIRES : 10/18/2022 22:48:50 | INFO | Finished setting ScheduledTasks
COMMENTAIRES : 10/18/2022 22:48:50 | INFO | Starting Appx Modification

**Comment by Kyoshim** [comment]
I add a new comment to say that i made the tweak again and it's work this time !
No slow restart, Thanks Chris ! 👍 

But, i still don't have a Windows showing that the Tweaks are done.

**Comment by ChrisTitusTech** [comment]
Yeah working through some issues with a new implementation

**Comment by Kyoshim** [comment]
Ok, thanks for your reply.
Le met know if you want for me to try again.
I will be happy to help.

**Comment by archead** [comment]
Can confirm the undo task does not complete all the way through.

**Comment by ChrisTitusTech** [comment]
Did a full revert all these issues are now cleared.
