### ISSUE TITLE
WinUtil fails to remove Gallery, OneDrive, and Home tabs.

### ISSUE THREAD

**Issue by MagmaBro123** [ChrisTitusTech/winutil#2840]
## Describe the bug
Title.

## To Reproduce
Use the options that remove these.

## Expected behavior
These tabs to be gone.

## Screenshots
![image](https://github.com/user-attachments/assets/9da05f8d-204b-45f2-a007-435cb4c5ddff)
![IMG_0485](https://github.com/user-attachments/assets/4a80f0be-0eca-4f29-b827-a0e79d90cc66)

System Info
![image](https://github.com/user-attachments/assets/c05c9cff-120a-4f7a-8537-7cd97da0a428)

## Additional context
I've posted this onto the WinUtil discord, and have yet to see a response there too.

**Comment by CodingWonders** [comment]
@MagmaBro123, I could not replicate this issue on 23H2, 24H2, and Selenium build 27695:

![2hMqibTEuV](https://github.com/user-attachments/assets/cdcee39d-8365-4b53-8d57-56046bcfaf75)
![vmware_UUZeA3PygK](https://github.com/user-attachments/assets/42dea42b-04a8-4d50-aee7-6432fe96a708)
![vmware_0ZaMGckL4Y](https://github.com/user-attachments/assets/c0f9c48f-d554-4e70-bd57-91e7729e994c)
