### ISSUE TITLE
24H2 Microwin and AMD chipset drivers

### ISSUE THREAD

**Issue by noxiuslt** [ChrisTitusTech/winutil#2848]
Hello, I cant install AMD chipset drivers when 24H2 ISO is done with microwin. Error message pops up "This program is meant for an AMD system. The program will be terminated because of system requirements not met"
If I take original ISO, install works OK.

## To Reproduce
0. Must have AMD chipset
1. make 24H2 ISO with microwin 
2. install AMD chipset drivers from amd.com

## Expected behavior
Error  "This program is meant for an AMD system. The program will be terminated because of system requirements not met"

**Comment by mawi5276** [comment]
Hey @noxiuslt,

same here...

Try to enable VBSCRIPT under optional features.
This worked for me.

**Comment by mawi5276** [comment]
with Powershell

Add-WindowsCapability -Online -Name VBSCRIPT~~~~

and later

Remove-WindowsCapability -Online -Name VBSCRIPT~~~~

**Comment by noxiuslt** [comment]
Thanks. I tried adding a lot features, but this definitely solved the problem ;)
