### ISSUE TITLE
Update docs: include Ad-Guard in DNS options

### ISSUE THREAD

**Issue by marblewraith** [ChrisTitusTech/winutil#2854]
Google is hell bent on moving to manifest V3. Intentional or not this will have catastrophic effects on reliable ad blockers such as uBlock Origin.

A quick and dirty solution is to use the [DNS of ad-guard](https://adguard-dns.io/en/public-dns.html), and i am requesting this be added as an option to the list of DNS providers.

It's not quite as good as having a native browser extension, as it will leave great honkin' gaps of whitespace on a page where the ad was supposed to be. But that's still better than having an epileptic seizure from whatever flashing trash is going to be loaded in otherwise. 

The only other alternatives will be to move to a different browser such as Firefox (staying on manifest V2 for now) or Brave (independently supporting uBlock Origin at a lower level than the extension API), which are valid options but not always a possibility for some people.

**Comment by pooley182** [comment]
This appears to have been done back in July in #2303

**Comment by marblewraith** [comment]
Indeed you're right. My bad.

User docs still need updating tho'.

https://christitustech.github.io/winutil/userguide/#dns
