### ISSUE TITLE
Disable Microsoft Defender Antivirus

### ISSUE THREAD

**Issue by Ji993** [ChrisTitusTech/winutil#2857]
**Describe the solution you'd like**
I don't want Windows to do any periodic scans on my drives. I don't want to use an Antivirus.
I didn't find an option to permanently disable the antivirus aspect of Microsoft Defender.
From what I know, Microsoft Defender includes other security aspects like a Firewall. I think keeping the Firewall enabled is a good idea, but I don't want to use the Antivirus aspect.

**Issues I experience**
At the moment I disable some of these settings by clicking around in the Privacy Settings menus, but I doubt that's enough to disable the antivirus completely. One issue I encountered is I disable "Virus & Threat protection / Real-time protection" and after I restart my system the setting is enabled again.

**Comment by trnahuman** [comment]
Yes, I think it should be, but now we can do it in our own hands if you need it badly https://christitus.com/disable-win-defender/

**Comment by ChrisTitusTech** [comment]
Yeah, I can't put this in the utility because it will flag all Antiviruses.

**Comment by Ji993** [comment]
Thanks for sharing. Great utility btw, thanks for your hard work.
