### ISSUE TITLE
Tweak: Disable fast boot for dual boot systems - Allows Safe Mode on Startup

### ISSUE THREAD

**Issue by joser93** [ChrisTitusTech/winutil#286]
Hello.

On systems using dual boot and linux, Windows locks the drives (even if it's a secondary drive with data only) and sometimes it's an problem to deal with this. The current solution it's to disable fast boot following this steps: https://askubuntu.com/questions/917695/read-only-partition-dual-boot-win10

The tool can implement something like this: https://superuser.com/questions/1277170/disable-windows-10-fast-boot-via-cmd-powershell to disable fast startup instead of going manually to the GUI. 

Also i must say that disabling ths option, doesn't avoid it when you want to restart, because, to avoid this situation, you must hold ctrl and click the restart button, maybe isn't a simple solution for this, idk, but i leave it here just in case someone can find a solution for this or have it documented here as a known issue if someone will consider have a dual boot setup.

Thanks for this awesome tool. :D

**Comment by ChrisTitusTech** [comment]
Love this idea, I don't dual boot anymore, but just having safe mode on startup is huge for troubleshooting.

**Comment by smartekIT** [comment]
I already use the following to bring back the legacy F8 startup menu which has the safe mode and others like last known good configurations:
<pre>
<code>
  "WPFFeatureEnableLegacyRecovery": {
    "feature": [
    ],
    "InvokeScript": [
      "
      If (!(Test-Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager\\LastKnownGood'')) {
            New-Item -Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager\\LastKnownGood'' -Force | Out-Null
      }
      New-ItemProperty -Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager\\LastKnownGood'' -Name ''Enabled'' -Type DWord -Value 1 -Force
      Start-Process -FilePath cmd.exe -ArgumentList ''/c bcdedit /Set {Current} BootMenuPolicy Legacy'' -Wait
      "
    ]
  },
  "WPFFeatureDisableLegacyRecovery": {
    "feature": [
    ],
    "InvokeScript": [
      "
      If (!(Test-Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager\\LastKnownGood'')) {
            New-Item -Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager\\LastKnownGood'' -Force | Out-Null
      }
      New-ItemProperty -Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager\\LastKnownGood'' -Name ''Enabled'' -Type DWord -Value 0 -Force
      Start-Process -FilePath cmd.exe -ArgumentList ''/c bcdedit /Set {Current} BootMenuPolicy Standard'' -Wait
      "
    ]
  }
</code>
</pre>

**Comment by smartekIT** [comment]
also the following which enables system registry backup and also set schedule for it (disabled by default in Win10 , Win11):
<pre>
<code>
  "WPFFeatureRegBackup": {
    "feature": [
    ],
    "InvokeScript": [
      "
      New-ItemProperty -Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager'' -Name ''EnablePeriodicBackup'' -Type DWord -Value 1 -Force
      New-ItemProperty -Path ''HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Configuration Manager'' -Name ''BackupCount'' -Type DWord -Value 2 -Force
      $action = New-ScheduledTaskAction -Execute ''schtasks'' -Argument ''/run /i /tn \"\\Microsoft\\Windows\\Registry\\RegIdleBackup\"''
      $trigger = New-ScheduledTaskTrigger -Daily -At 00:30
      Register-ScheduledTask -Action $action -Trigger $trigger -TaskName ''AutoRegBackup'' -Description ''Create System Registry Backups'' -User ''System''
      "
    ]
  }
</code>
</pre>

**Comment by smartekIT** [comment]
just did a PR for this #1389
