### ISSUE TITLE
Yet another compilation bug on PowerShell 5

### ISSUE THREAD

**Issue by CodingWonders** [ChrisTitusTech/winutil#2864]
## Describe the bug
This one is less serious, but it makes compilation fail on PowerShell 5. Now, it detects an invalid primitive in the JSON content

![image](https://github.com/user-attachments/assets/724be7dc-3463-43db-aebc-ed94bdf1a121)

## To Reproduce
1. Compile WinUtil

## Expected behavior
(You already know)

## Screenshots
Attached above

## Additional context
None

**Comment by ruxunderscore** [comment]
*sigh*
Let me look...

**Comment by ruxunderscore** [comment]
There is an issue on line 324 in the feature.json file. That last comma is throwing the error. JSON handling in Powershell 7 is better than 5, and I guess part of that is the ability to ignore stray commas like that one. 
I'll push a fix in a moment.
