### ISSUE TITLE
Bug: 24H2 Explorer UI not working as it should...

### ISSUE THREAD

**Issue by byFynn** [ChrisTitusTech/winutil#2880]
## Describe the bug
I wanted to make a clean install of Windows 11 24H2 with MicroWin. Everything was working correctly exept the Explorer UI. Firstly the foreward and backward buttons didn´t do anything and also some other simple UI funktions like going back in the path opens another window with no changed settings in explorer. (So its the Windows 10 Explorer UI i think thats nice because of all the funktions ... but its not that funktional yet xD)

## To Reproduce
1. Go to MicroWin in WinUtil
2. Download the newest Windows 11 (24H2) iso from the official website
3. Don´t change any options exept: "Username, Password & Copy to Ventoy" in MicroWin
4. Let MicroWin run without Error
5. Boot up image 
6. See Explorer UI isn´t working correctly

## Expected behavior
The UI should be working fine with foreward and backward button, also going back in path shouldn´t open in new window with default & unchanged settings.

## Screenshots
N/A

## Additional context
N/A

**Comment by CodingWonders** [comment]
Explorer issues will be fixed with PR #2853

**Comment by byFynn** [comment]
Nice!
