### ISSUE TITLE
File Explorer Issues on 24H2

### ISSUE THREAD

**Issue by tomfrost435** [ChrisTitusTech/winutil#2885]
## Describe the bug
Windows File Explorer misbehaving on a fresh install of MicroWin Windows 11 Pro 24H2 image
-Unable to use tabs feature
-Clicking on breadcrumbs creates new instance instead of changing directory (conditional, might be hard to reproduce)

## To Reproduce
1. Install MicroWin W11P 24H2 image
2. Open File Explorer
3. Try and open a new tab
4. Try clicking on breadcrumbs

## Additional context
Possibly might be related to certain tweaks (Setting services to manual perhaps)
Can't get the breadcrumbs issue to work reliably

**Comment by CodingWonders** [comment]
@tomfrost435, this is fixed in #2853
