### ISSUE TITLE
Winget out of date

### ISSUE THREAD

**Issue by zmileski** [ChrisTitusTech/winutil#2889]
## Describe the bug
Updating winget with winutil when using install takes forever
Updating "app installer" with microsoft store or with "winget upgrade microsoft.appinstaller" if it is posible is so much faster for me
So maybe this is fix for everyone
@CodingWonders 

## Expected behavior
Updating appinstaller with microsoft store or winget upgrade command

**Comment by zmileski** [comment]
Sorry i wanted to mention you on another issue

**Comment by CodingWonders** [comment]
Your suggestion implies that you want to use WinGet to update the App Installer. That causes a problem, and it's that, if the WinGet version is out of date, it may not be able to grab the sources necessary for finding the packages, therefore presenting this same issue

**Comment by zmileski** [comment]
What i was trying to say is when using install tab and winget is out of date winutil trying to update winget takes so my time 
![1](https://github.com/user-attachments/assets/e749e1ce-5a13-45c2-94b1-b83253bfdb40)
for me this takes 5 min
but if i upgrade first app.installer with winget upgrade uprades only xaml then when launch winutil and try to install something winget is updated
![2](https://github.com/user-attachments/assets/9855c49c-b654-4578-8e78-75806cb32631)
![3](https://github.com/user-attachments/assets/b27af920-89e9-42a1-a375-c4d9dd5fdede)
this takes for me 1 min

**Comment by GameBoyJunkie** [comment]
Same no issues with winget.

**Comment by ruxunderscore** [comment]
In newer versions of Winget, doing an upgrade of Winget using Winget, is handled somewhat okay. However, if we implemented this and someone tried to upgrade Winget with an older version of Winget, it may not handle it well and cause some issues. So the way we handle it currently is the best way at the moment. I am hoping that they find a better way to handle updates in the future that is more retroactive.

**Comment by CodingWonders** [comment]
> In newer versions of Winget, doing an upgrade of Winget using Winget, is handled somewhat okay. However, if we implemented this and someone tried to upgrade Winget with an older version of Winget, it may not handle it well and cause some issues. So the way we handle it currently is the best way at the moment. I am hoping that they find a better way to handle updates in the future that is more retroactive. 

Yeah. Add the fact that Microsoft had distributed ISO files of Windows 11 that had a broken WinGet implementation
