### ISSUE TITLE
Microwin cannot download iso

### ISSUE THREAD

**Issue by OfficiallySp** [ChrisTitusTech/winutil#2896]
## Describe the bug
When using the latest development version of winutil. trying to download the 24H2 iso fails.

## To Reproduce
1. launch the latest dev build of winget
2. go to microwin tab
3. check get newest iso automatically and select 24H2
4. click get windows iso
5. See error

```
Invoking WPFGetIso
         _                     __    __  _
  /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __
 /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \
/ /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |
\/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|
oscdimg.exe on system: False
[INFO] oscdimg.exe SHA-256 Hash: AB9E161049D293B544961BFDF2D61244ADE79376D6423DF4F60BF9B147D3C78D
Hashes match. File is verified.
oscdimg.exe was successfully downloaded from github
Error: The requested name is valid, but no data of the requested type was found. (vlscppe.microsoft.com:443)
Could not download the ISO file. Look at the output of the console for more information.
```

## Expected behavior
The ISO should start downloading

## Additional context
both download oscdimg.exe from CTT github and use ISO directory for scratch are checked.

**Comment by CodingWonders** [comment]
This is an error from Fido. Please report these problems on the [Fido repository](https://github.com/pbatard/Fido)

**Comment by CodingWonders** [comment]
@FatBastard0, this is a different issue. You should make a separate issue

**Comment by FatBastard0** [comment]
Ok, I will do that.
I would like to thank you in advance for any assistance that you can
provide in this matter. Please feel free to contact me at the below listed
address, Telephone and/or email.




Richard K. L'Italien
Disable Veteran of the US Army
The Fat Bastard
5637 Monte Corita Circle
Citrus Heights California 95621
(916) 915-3883 <http://voice.google.com/calls?a=nc,%2B19169153883>
<http://voice.google.com/calls?a=nc,%2B19169153883> Voice
(916) 943 4967 <http://voice.google.com/calls?a=nc,%2B19169434967>
<http://voice.google.com/calls?a=nc,%2B19167453437>

******************************************************************************
This communication (including any attachments) may contain privileged or
confidential information intended for a specific individual and purpose,
and is protected by law.  If you are not the intended recipient, you should
delete this communication and/or shred the materials and any attachments and
are hereby notified that any disclosure, copying, or distribution of this
communication, or the taking of any action based on it, is strictly
prohibited.

Thank you.

**Comment by CodingWonders** [comment]
Issue closed due to inactivity, and due to the fact that it's not a MicroWin issue. /close
