### ISSUE TITLE
Not working ISO with MicroWIn

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#2900]
I am getting this when I tryed to run after I make an ISO with MicroWIn 
![ScreenShot_20241009062322](https://github.com/user-attachments/assets/6d854d59-6c8d-4cf8-bfef-ca9a80fe9704)

_Originally posted by @FatBastard0 in https://github.com/ChrisTitusTech/winutil/issues/2896#issuecomment-2402712270_

**Comment by FatBastard0** [comment]
one note is that I am using that irm "https://christitus.com/windev" | iex" to get in to MicroWin

**Comment by mawi5276** [comment]
The ISO with the latest dev is running flawlessly.

You've startet the setup.exe in Windows?

**Comment by FatBastard0** [comment]
Yes and no, I had the normal removel programs not working. I would put on USB (Rufus) and them I would ask for a key I would then "dont have key" and then it would say install stop" So I tried entering a Key because I have one, The installer would stop, but I ran the MicroWin from the irm "https://christitus.com/win" | iex" and made ISO but this time MS Installer asked if IT should previous install informaation and I said yes and everything worked.

By the thanks for all of your hard work!!

**Comment by ChrisTitusTech** [comment]
You can't use Rufus customizations with Microwin. Microwin already does all the setup and TPM bypass stuff.

**Comment by FatBastard0** [comment]
Not like you do Mr. ChrisTitusTech, I do not use the customiztion (Rufus), I just use it to make the USB, Because I am newbie at this. So I make the MicroWin ISO, I then use (Rufus all costomiztion off) This the only way I know to put the ISO on a USB.
