### ISSUE TITLE
MicroWin Windows 10 Snip & Sketch Bug

### ISSUE THREAD

**Issue by ooFVenomous** [ChrisTitusTech/winutil#2903]
## Describe the bug
After using MicroWin on a windows 10 ISO, and installing, trying to use the Snip & Sketch tool fails. You are unable to use the "Win+Shift+S" method and clicking "New" with the app open brings up a prompt (See below). It should be noted that it was not installed originally and I installed it from the Microsoft store.

## To Reproduce
1. Open Snip & Sketch
2. Click on New
3. Result

## Expected behavior
Snip & Sketch region select tool to appear

## Screenshots
![EKOexJg](https://github.com/user-attachments/assets/2fef55a7-92d6-4a07-822b-4bc4adba5b27)

## Additional context
Used MicroWin to debloat a win10 ISO and added no drivers of my own. Used Rufus in creation as well. 
I have tried restarting after installing, resetting S&S, uninstalling and reinstalling but nothing worked.

**Comment by ooFVenomous** [comment]
A fix I have found for this is running a DISM command. I am unsure as to why MicroWin would affect the snipping tool.

**Comment by ChrisTitusTech** [comment]
Fixed in latest release. PR #2737
