### ISSUE TITLE
VBScript.dll 2738 error while installing apps with an executable

### ISSUE THREAD

**Issue by rogerjv28** [ChrisTitusTech/winutil#2910]
I did a Microwin installation of Windows 11 Home version 24H2 this monday (7/10/24) on my laptop. After installation I applied some tweaks of the windows utility. Then I wanted to install Dell Power Manager downloading the .exe from dell's website but when running the process of installation I run into error 2738: "Could not access VBScript run time for custom action.".

![{9C4935D6-CC06-45C0-81F8-0802C167CD42}](https://github.com/user-attachments/assets/274855f5-9727-4214-972d-94598d7026c2)

I don't know if this has to do with some tweak or the modified iso, but I think it might since I only configured this installation through this windows utility. I don't know if it has something to do with registers or this vbscript being erased. I tried some fixes ChatGPT recommended like:
- sfc /scannow
- Using DISM /Online /Cleanup-Image /ScanHealth and DISM /Online /Cleanup-Image /RestoreHealth
- Downloaded vbscript.dll copied in the folder C:\Windows\SysWOW64\ and used the command regsvr32 vbscript.dll

And none of the above solutions worked. I hope someone maybe has run into this problem and fixed it before so they can help me.

Thank you in advance for any help or tips on how to resolve this.

**Comment by mawi5276** [comment]
Hey,

Try to install VBSCRIPT under optional features in the windows settings.

The lack of VBSCRIPT has been fixed with the last release of winutil.

**Comment by rogerjv28** [comment]
That worked perfectly, thanks a lot! Just out of curiosity, what does VBScript do?

**Comment by mawi5276** [comment]
You´re welcome.

VBScript is a scripting language. Some installers needs it.

**Comment by melfi01** [comment]
hey, i can't find how and where to install vbscript :(

**Comment by mawi5276** [comment]
Open Powershell as administrator

Then

Add-WindowsCapability -Online -Name VBSCRIPT~~~~
