### ISSUE TITLE
Regarding To Microwin iso Creator

### ISSUE THREAD

**Issue by DarkSideAm** [ChrisTitusTech/winutil#2914]
**Is your feature request related to a problem? Please describe.**
No Its not a problem 

**Describe the solution you'd like**
I was just curious if there is a possibility to get microwin to create a all in one windows iso file and optional windows 7 8 added as a compatible to microwin

**Comment by zmileski** [comment]
Since 7 and 8 are deprecated, I don't think so.

**Comment by blusewill** [comment]
No. Microwin just strip down Windows ISO.
If you're looking for recovery Windows PE options then Winutil is not for you.

**Comment by CodingWonders** [comment]
While you can add a Windows 7 or Windows 8 image to a WIM file, do you **really** want to use them, and do you really need them, @DarkSideAm?

You can append the Windows 7/8 image to the MicroWin image after it's done manually. Look at the `append-image` flag of DISM for more information: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/append-a-volume-image-to-an-existing-image-using-dism--s14?view=windows-11

This issue can be safely closed. /close

**Comment by DarkSideAm** [comment]
> While you can add a Windows 7 or Windows 8 image to a WIM file, do you **really** want to use them, and do you really need them, @DarkSideAm?
> 
> You can append the Windows 7/8 image to the MicroWin image after it's done manually. Look at the `append-image` flag of DISM for more information: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/append-a-volume-image-to-an-existing-image-using-dism--s14?view=windows-11
> 
> This issue can be safely closed. /close

i was able to do it myself thanks anyways :)
