### ISSUE TITLE
MicroWin prepared ISO is incompatible with AMD chipset drivers

### ISSUE THREAD

**Issue by korgano** [ChrisTitusTech/winutil#2917]
## Describe the bug
Utilized MicroWin to prepare a Windows 11 24H2 Home ISO to upgrade various systems. Installed ISO on an AMD 5800H + 6600M laptop and an AMD 7800X3D + 7900 XTX system and got the same error with two different drivers:
```
AMD Chipset Software

This Installer is intended to be deployed only on an AMD system. Exiting installation as the requirement is not satisfied.
```

## To Reproduce
1. Create Windows 11 24H2 ISO with MicroWin.
2. Install on storage media directly connected to AMD motherboard.
3. Obtain chipset drivers from AMD.com or other source.
4. Attempt to install driver.
5. See error/image below.

## Expected behavior
AMD chipset driver interface to appear, allowing for selection of AMD drivers for installation.

## Screenshots
![winutil-amd-chipset-driver-issue](https://github.com/user-attachments/assets/abeff2e7-7ddc-44a9-80f5-7226a435f260)

## Additional context
AMD driver installer is not affected.

**Comment by mawi5276** [comment]
Did you use the latest release of microwin?

Check under the optionally features under settings if VBSCRIPT is installed.

**Comment by korgano** [comment]
I used Release 24.09.12, because I created the ISO on 10/4/24, and didn't get around to installing until yesterday due to IRL circumstances.

**Comment by mawi5276** [comment]
In this older release you have to install VBSCRIPT manually.

**Comment by korgano** [comment]
> In this older release you have to install VBSCRIPT manually.

Got any recommended links? First time I've run into this kind of thing.

**Comment by mawi5276** [comment]
It's build in.

Open windows settings. Optional features. Add feature. VBSCRIPT

**Comment by korgano** [comment]
That worked, thanks.

Might want to put a warning or something into MicroWin's UI/the documentation.

**Comment by mawi5276** [comment]
Not needed.

The newest release fixed it.
