### ISSUE TITLE
vbscript 2738 error

### ISSUE THREAD

**Issue by melfi01** [ChrisTitusTech/winutil#2919]
Hello, i just installed windows with winutil, applied all the recommended tweaks, nothing more and now i'm trying to install epic games launcher and i'm getting this: 
![{F14CD342-C8CC-42B0-B296-BE5011099243}](https://github.com/user-attachments/assets/4521ac76-0f06-4dfe-bd22-4213ac00d6e1)
i read on a closed issue that you can install vbscript under some windows optional features but i'm either blind or i don't have it. 
Could you please guide me (maybe with some screenshots :D ) to getting vbscript back so i can install EG launcher?

**Comment by mawi5276** [comment]
Open Powershell as administrator

Add-WindowsCapability -Online -Name VBSCRIPT~~~~

**Comment by melfi01** [comment]
you are an absolute saint. god bless you. solved it!

**Comment by mawi5276** [comment]
> you are an absolute saint. god bless you. solved it!

You're welcome 😊
