### ISSUE TITLE
Misprint

### ISSUE THREAD

**Issue by tertaco** [ChrisTitusTech/winutil#292]
In Tweaks, Disable Storage sense's better description has a small misprint. Not a big deal, yet it someone might be annoyed by it.
![изображение](https://user-images.githubusercontent.com/76095170/196623196-ed4073fc-b3fa-4405-b2e0-4e88a36e6764.png)

**Comment by ChrisTitusTech** [comment]
Bad spelling is my achilleas heel. My XAML program doesn't have spell check and this is going to pop up again lol. 

I'm working on fixing this by coding everything in a custom neovim with a linter as I type. Probably next month I'll be able to cut down on these. 

submitted commit 5bfab63f4f621fb5d21586da0e9c4224f7e3ce14 to test fixing this
