### ISSUE TITLE
Avast detects a trojan when debloating an ISO with Microwin

### ISSUE THREAD

**Issue by themainheadcase** [ChrisTitusTech/winutil#2920]
The detection happens after you select an ISO and then click on "start the process." It happens immediately after clicking on "start the process."

I repeated the procedure twice exactly the same way and got the same result. Both times I used the Windows 10 IoT Enterprise LTSC 2021 ISO downloaded off MAS. I left both the drivers related options unchecked, as well as the Ventoy option, the custom user settings I left blank.

Avast detected these two files
![more info](https://github.com/user-attachments/assets/5ee249e5-97e6-4d15-9820-c8c7ffcae065)
![more info 2](https://github.com/user-attachments/assets/1a5199e8-9315-4294-8081-7c58122a8a64)

This is what Powershell said
![trojan bez ltsc](https://github.com/user-attachments/assets/f62f589d-7703-40ec-88a2-7e7b59bd89bf)

**Comment by blusewill** [comment]
Easiest way. Just Disable it Temporarily. Since Winutil does get flagged too often by the AntiVirus.
Especially when it comes to the part like Tweaks Sections.
