### ISSUE TITLE
kohls.com does not load cart

### ISSUE THREAD

**Issue by ChaseKnowlden** [ChrisTitusTech/winutil#2922]
## Describe the bug

When WinUtil Standard tweaks are applied, the kohl's cart does not load.

## To Reproduce
1. Open WinUtil
2. Use Standard Tweaks
3. Open Chrome
4. Go to kohls.com
5. Click cart
6. Cart page just hangs

## Expected behavior
The Cart page should show items.

**Comment by maxwellem** [comment]
i was not able to replicate this.
