### ISSUE TITLE
Still getting stuck when trying to remove all MS Apps

### ISSUE THREAD

**Issue by TigercatVIP** [ChrisTitusTech/winutil#293]
**Describe the bug**
In the Tweaks section just checking the option to remove all MS Apps and run it, will make it getting stuck on removing Microsoft Teams forever, the bug got resolve once, but it's back again

**To Reproduce**
1. Go to the Tweaks section in the W/Utility
2. Check the box for only removing all MS Apps
3. Then click on run Tweaks
4. And then:
WARNING: Teams installation not found
Process user: Angel
WARNING: Teams installation not found for user Angel
Process user: defaultuser0
WARNING: Teams installation not found for user defaultuser0
Process user: Public
WARNING: Teams installation not found for user Public

**Expected behavior**
It should remove all Microsoft Store Apps including MS Teams

**Comment by ChrisTitusTech** [comment]
Fixed in latest PR #318
