### ISSUE TITLE
Microsoft Store log in problem

### ISSUE THREAD

**Issue by DreamEag1e** [ChrisTitusTech/winutil#2937]
After enabling tweaks from "Essential Tweaks" section unable to log in into MS Store (I did not touched anything alse).
Authorisation screen just pops in and disappear immediately.

I'm pretty sure some essential services has been turned off. Is there any way to fix that?
I tryed to undo tweakes but in doesn't helped.

Did this on Windows 11 Pro 24H2.

**Comment by MyDrift-user** [comment]
Hello @DreamEag1e 
Did you do an Install with region set to "English International" ? 
In that case this would be the reason, you'd have to change your region afterwards to make it work.

**Comment by DreamEag1e** [comment]
> Hello @DreamEag1e Did you do an Install with region set to "English International" ? In that case this would be the reason and not winutil, you'd have to change your region afterwards to something else (best your actual location) to make it work.

I know this trick with “English International” and in my case it wasn't a problem.  I guess it was just some of the authorization related services going down, because I later noticed that I couldn't log into my Xbox account either. I never figured out exactly what the problem was, so I just reinstalled Windows.
