### ISSUE TITLE
Zoxide? and Oh My Posh?

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#2942]
I don't understand why U install Zoxide and Oh My Posh

After I uninstall Zoxide and Oh MY Posh U reinstall it?

Is need for winutil to run right?

Can winutil run  independently of the programs?

**Comment by blusewill** [comment]
???

**Comment by MyDrift-user** [comment]
U probably installed the CTT powershell profile, didn't you?
The powershell profile installs those apps because oh my posh is used to make iz look like that and zoxide is for better navigation in the shell.

You can delete the profile, then it will not install those apps anymore.

**Comment by FatBastard0** [comment]
Thanks for the information, yes I did install profile. I like it so because of your recommendation I keep it.
By the way THANKS for all your hard work.

**Comment by og-mrk** [comment]
@FatBastard0 
Looking at this Issue Ticket conversation, it seems like the main question/issue have been answered/resolved. If you've any questions related to this topic, feel free to send them here, and if you don't, then consider closing this issue as completed, thanks in advance and have a nice day 😄
