### ISSUE TITLE
Why is now asking for username and PASSWORD

### ISSUE THREAD

**Issue by workdowg** [ChrisTitusTech/winutil#2944]
I would like to know why it started opening an elevated Windows dialog box asking for my PC username and password?  It already has permission when I first launch it. Great tool and I think you could even bump the price to $15 or $20... :-)

**Comment by MyDrift-user** [comment]
Hello there @workdowg 

This is probably during the install. Some applications do not like to be installed as admin (spotify for example). In that case it will fail and ask you for credentials, so it can install without elevation.

I understand that it is a bit confusing, and a bit more info would be helpfull at that point I think.

**Comment by workdowg** [comment]
Thanks Chris! I don't have a problem but other would get scared....lol As they should actually!

**Comment by bsides** [comment]
Hi @MyDrift-user, what would be useful to send for this to not happen? My desktop workstation is passwordless and if I change the password in that screen, all my apps get logged off and my browser can't recover. I'm using Atlas OS (a modified Windows version without the bloat) and I don't know if it interferes or not but to find the user password and change back to passwordless is a PAIN. Please let me know how could I help for it not to happen. Thank you!
