### ISSUE TITLE
Latest pre-release version

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#2946]
## Describe the bug
[](![PXL_20241017_233754921](https://github.com/user-attachments/assets/8017f06f-02e0-43fa-bc81-3de353d003bc))

1.When I use irm "https://christitus.com/windev" | iex
2. I get the above notice

3. Am I not getting the lassst pre-release?
4. Or is it me just not likeing RED text
5.
![PXL_20241017_233754921](https://github.com/user-attachments/assets/2bd66138-559c-4c8b-92e6-42a37ad3e038)

**Comment by MyDrift-user** [comment]
If the newest Release is a Full release, meaning there is no newer release as the current Full release it will fail to get the newest pre-release bc there isn't one. This is the reason why it redirects to the full release.

Hope that helps :)
