### ISSUE TITLE
Please consider adding Customized installations of most common suites. Like Office 365, Adobe Suite etc

### ISSUE THREAD

**Issue by dimkasta** [ChrisTitusTech/winutil#2952]
**Is your feature request related to a problem? Please describe.**

The most common issue when doing a new install is adding your common software. In most cases, this includes MS Word, Excel, Outlook and maybe Powerpoint. And then maybe Lightroom and Photoshop. And even in some cases, things like PHPStorm or Goland, virtualbox etc.

The main issue is that modern practices of software companies dictate one or several central applications that call home and put the installation process on rails. For example 

- Jetbrains is rather straightforward with this. Their app just installs other apps on demand, checks your license and checks for updates. And they allow specific application installations.
- Adobe is kinda worse in that their app is more convoluted, but it still allows custom installations.
- Office 365 is the worse, it's either all or nothing. And even worse, it forces windows integration with One Drive and messes with your home directories. There are options for custom deployments, but it's not something most people want to get involved with.

**Describe the solution you'd like**

Ideally, I would like to be able to install specific apps, like just Word, Excel, Outlook, PHPStorm on an hoc basis. But also maybe bake this in Microwin. This would help a lot to make installations easily disposable if something goes wrong.

I understand this has two parts. Including custom apps into microwin. And then defining customized installations for suites.

**Describe alternatives you've considered**

For now I have a few simple scripts that download the official executables in my applications folder in my NAS, this helps me not forget anything, and I don't waste time googling things every time.

**Additional context**

Here are some useful tools I have checked but I don't have the required expertise to setup into a comprehensive script or something
This is the office deployment tool
https://learn.microsoft.com/en-us/microsoft-365-apps/deploy/office-deployment-tool-configuration-options
And this is the Adobe methodology that can be used
https://helpx.adobe.com/enterprise/using/deploy-packages.html
Choco also has a nice deployment package that unfortunately is a bit outdated
https://community.chocolatey.org/packages/microsoft-office-deployment#install

**Comment by thecatontheceiling** [comment]
"Office 365 is the worse, it's either all or nothing."

This is false. There are different editions of office with different apps included. You can also make your own configuration by going to config.office.com.

OneDrive isn't forced on you either. You can uninstall it literally seconds after Office is installed.

**Comment by dimkasta** [comment]
> "Office 365 is the worse, it's either all or nothing."
> 
> This is false. There are different editions of office with different apps included. 

Different editions that are installed all or nothing by the standard installer. No custom installation options

> You can also make your own configuration by going to config.office.com but you skipped over that because according to you people won't want to do that

I did not skip it. I rejected it because yes "according to me" the average person, or even power users, won't touch such tools even with a 10 feet pole if they had a choice. Why do you think we are using Chris' Utility? 
You are saying that according to you, it's preferable having to deal with polcies and configurations than having the option for 4-5 clicks on Chris' Utility? 

> OneDrive isn't forced on you either. You can uninstall it literally seconds after Office is installed.
That's what MicroWin and the debloaters try to help us avoid having to do

**Comment by dimkasta** [comment]
I fiddled a bit with the office deployment tool. I hope this helps the team save some time if they decide to include this in the tool

https://config.office.com/ that thecatontheceiling mentioned is helpfull to find about cryptic options like how to preconfigure the apps to use the open XML format.

Here is a working sample

1. First download the office deployment from microsoft - https://www.microsoft.com/en-us/download/details.aspx?id=49117
2. Run the exe into a folder. This gives you a setup.exe and a sample configuration
3. Create a configuration.xml file in the same folder
4. Open a powershell as admin and go to the folder
5. Run ./setup /download configuration.xml to download the define packages
6. Run ./setup /configure configuration.xml to install the apps

And here are the configuration xml and a ps1 that you can use directly to call everything in sequence

This uninstalls all existing MSI installations, installs only Word, Excel, One Drive and Outlook on the en-US language, and includes Profiling Tools for Greek, enables updates, auto accepts the EULA, selects the Open XML format that is fully compatible with all MS Office functionlity, and finally hides all installation progress from the user.

``` xml
<Configuration ID="dc42251a-e556-4809-8114-461c84eb1d4a">
  <Add OfficeClientEdition="64" Channel="Current">
    <Product ID="O365BusinessRetail">
      <Language ID="en-us" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Teams" />
    </Product>
    <Product ID="ProofingTools">
      <Language ID="el-gr" />
    </Product>
  </Add>
  <Updates Enabled="TRUE" />
  <RemoveMSI />
  <AppSettings>
    <User Key="software\microsoft\office\16.0\excel\options" Name="defaultformat" Value="51" Type="REG_DWORD" App="excel16" Id="L_SaveExcelfilesas" />
    <User Key="software\microsoft\office\16.0\powerpoint\options" Name="defaultformat" Value="27" Type="REG_DWORD" App="ppt16" Id="L_SavePowerPointfilesas" />
    <User Key="software\microsoft\office\16.0\word\options" Name="defaultformat" Value="" Type="REG_SZ" App="word16" Id="L_SaveWordfilesas" />
  </AppSettings>
  <!--Display Level="Full" AcceptEULA="TRUE" /-->
  <Display Level="None" AcceptEULA="TRUE" />
</Configuration>
```

And here is a sample ps1 file that calls all of these in sequence

``` ps1
#Requires -RunAsAdministrator

echo "Unziping the setup application"
./officedeploymenttool_18129-20030.exe | Out-String

echo "Downloading the installation files"
./setup.exe /download configuration.xml | Out-String

echo "Installing Office"
./setup.exe /configure configuration.xml | Out-String

echo "Installation Done"
```



I will try to do something similar for Adobe as well

**Comment by blusewill** [comment]
Adobe Suite is locked down into the Creative Cloud Paywall. And though there is a way to bypass it. The Creative Cloud is forced to install after any Adobe Program is installed.

**Comment by CodingWonders** [comment]
@dimkasta, we want an image that's simple. We don't want to include additional software that end-users may not want to use.

There are places in the MicroWin images in which you can achieve this result, like the first run script.

For the reason I explained above, we are not adding additional applications. /close
