### ISSUE TITLE
Does MicroWin support Windows 10?

### ISSUE THREAD

**Issue by h1toru** [ChrisTitusTech/winutil#2954]
I'm just wondering if MicroWin still supports Windows 10, or is it completely focuses on Windows 11.

**Comment by celeron550** [comment]
It works. However, microwin's focus is on win 11 so it might not work as intended on win 10 ISOs

**Comment by gabinodga** [comment]
Works great with LTSC 2021.

**Comment by CodingWonders** [comment]
@h1toru, MicroWin does work with Windows 10. However, like @celeron550 states, it's more focused on Windows 11, and it might not work as you would expect with Windows 10 ISOs.

I hope this answers your question. Regarding this issue though, it can be closed. /close
