### ISSUE TITLE
Completed with errors (MicroWin)

### ISSUE THREAD

**Issue by Louis047** [ChrisTitusTech/winutil#2956]
## Describe the bug
Today, I tried to minimize/debloat my Windows installation using MicroWin (heard a lot of good reviews about it through videos/comments).Everything was going well until I encountered a warning/error in terminal log(screenshot provided below) which kind of got me curious for what's the real problem. Hope I get my answers here :)
ISO used: `Windows 11 24H2` (Downloaded from Official Microsoft)

## To Reproduce
Try using the ISO provided in official Microsoft website and use MicroWin.

## Expected behavior
Expected to be working error-free, but odds are against me.

## Screenshots
![image](https://github.com/user-attachments/assets/2a82a5c6-ae26-474c-9e00-db7ccdb086ba)

## Additional context
I either doubt it to be a corrupted ISO or MicroWin just doesn't work well with the latest ISO build. (Zero possibility that official Windows ISOs from Microsoft is corrupted)

**Comment by AndreyGasik** [comment]
I use it for 26100.1742, not have any errors. Check your version windows iso.

**Comment by light-weaver** [comment]
I faced the same issue today. I downloaded the ISO using MicroWin itself. The original ISO seems fine.

**Comment by Louis047** [comment]
Already moved on with Windows 10, so closing this for now. In case anybody got the same error are free to refer this issue.
