### ISSUE TITLE
Bare windows

### ISSUE THREAD

**Issue by coeki** [ChrisTitusTech/winutil#2957]
**Is your feature request related to a problem? Please describe.**

idk where to post this
**Describe the solution you'd like**

mmm, wim tech
**Describe alternatives you've considered**

images come pre defined
**Additional context**

you can destroy that, and use the tools to redo, stiil all microsoft tools, welll...mostly
Biggest problem I have, is this with microwin, everry wim comes with a preisnatlled base, which is where you need to foxcus, you don't
I love the work you do  :)

ps mostly linux, private clouds in incus ;)

**Comment by blusewill** [comment]
Alright. Let answer some of your questions.
First. This should be put in Discussion form.
Second. We're not doing extreme debloat for MicroWin.
That is going to cause some system stability issues.

**Comment by Marterich** [comment]
iho answered and inactive 
/close
