### ISSUE TITLE
Disabling Defender with a utility after tweaks causes performance issues

### ISSUE THREAD

**Issue by Alikrnc** [ChrisTitusTech/winutil#2958]
.
.
.
# _SOLVED!_
The issue was all about Defender Control and the issue has been around for more than a year. Disabling Smart App Control on Windows Settings should [fix](https://www.reddit.com/r/Windows11/comments/15ed10t/comment/juhq7xz/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) (check the comment) this issue.
.
.
.

## Describe the bug
I just discovered winutil and oo shutup tweaks and wanted a clean installation with these tweaks. Normally I was using "Defender Control v2.1 ([this](https://www.sordum.org/9480/defender-control-v2-1/)) or Winaerotweak" to disable Windows Defender and there were no problems at all.  After doing a clean install of Windows 11 24H2, winutil, oo shutup tweaks, I disabled the defender with Defender Control v2.1 and everything looked fine until I tried to download some drivers, vcredist, etc. Installing vcredist normally doesn't take much time (or any program) on my Laptop but whenever I disable Defender with a utility It causes performance issues. However, disabling defender without a utility is not causing problems.

If you need any [system info](https://www.msi.com/Laptop/Katana-A17-AI-B8VX/Specification) I am writing that below:
Laptop Model: MSI Katana A17B8VG
CPU: AMD Ryzen 9 8945HS w/ Radeon 780M Graphics, 4001 Mhz, 8 Cores, 16 Threads
GPU: NVIDIA® GeForce RTX™ 4070 Laptop GPU 8GB GDDR6
Memory: 32 GB DDR5-5600
Storage: 1 TB NVMe (Read / Write 4,481 / 3,345 Western Digital SN560)

And some videos to make it more clear.

1) Defender enabled (or disabled manually from settings and gpedit.msc)
https://github.com/user-attachments/assets/9f9ac10f-706a-43a6-81c9-5c83e2caf1ce

2) Defender disabled with utility.
https://github.com/user-attachments/assets/b256437b-22d0-41a5-98d9-ed0c07bb5c2f

## To Reproduce
1. Do some "winutil" and "oo shutup 10" tweaks.
2. Disable the defender with a utility.
3. Try to do some program installations.
4. See the bad performance.

## Additional context
In the videos above, I have only tried to install vcredist 2012, but the situation is the same with other installers, and even the system response and idle performance are significantly lower.

Now my defender is disabled with gpedit.msc and there are no performance problems.

**Comment by zmileski** [comment]
This has nothing to do with Winutil 
This is Defender Control issue, you are using outdated software.
I tested on official 24h2 and defender control caused this issue
![1](https://github.com/user-attachments/assets/0c00229f-258d-4eb2-b76f-0b4c0fcf78be)
just don't cancel wait and will install after that issue will be fixed.

**Comment by Alikrnc** [comment]
Oh, thank you! Couldn't think to test the Defender Control without winutil so I got it wrong. By your comment I did further research and found that Smart App Control caused this issue, I have added the fix to the issue post so other people can have a solution.
