### ISSUE TITLE
Snip & Sketch not working on Windows 10

### ISSUE THREAD

**Issue by Burcrep** [ChrisTitusTech/winutil#2959]
## Describe the bug
I'm trying to use the Snip & Sketch app on Windows 10 Pro (22H2) after using MicroWin, but it happens that it doesn't work at all, I tried running the System and Corrupt Scan and rebooting several times but nothing happens.

## To Reproduce
1. Open Snip & Sketch
2. Click on New
3. No ms-screenclip app

## Expected behavior
Snip & Sketch region select tool to appear.

## Screenshots
![image](https://github.com/user-attachments/assets/bf0fc85a-c965-47ea-896d-8d2dab778ad5)

## Additional context
I installed Windows yesterday. Also, I’ve already checked this: https://github.com/ChrisTitusTech/winutil/issues/2903.

**Comment by CodingWonders** [comment]
@Burcrep, can you try running this command as an administrator and see what it returns?

`dism /online /get-capabilityinfo /capabilityname=Windows.Client.ShellComponents~~~~0.0.1.0"`

More info [here](https://superuser.com/questions/1561188/snip-sketch-tool-not-working-missing-ms-screenclip-protocol-handler)

**Comment by MyDrift-user** [comment]
> `dism /online /get-capabilityinfo /capabilityname=Windows.Client.ShellComponents~~~~0.0.1.0"`

you accidentally added a ", here the command to copy & paste:
```

DISM /Online /Add-Capability /CapabilityName:Windows.Client.ShellComponents~~~~0.0.1.0

```

**Comment by CodingWonders** [comment]
@MyDrift-user, I've edited the command. Thanks for pointing out

**Comment by Burcrep** [comment]
> @Burcrep, can you try running this command as an administrator and see what it returns?
> 
> `dism /online /get-capabilityinfo /capabilityname=Windows.Client.ShellComponents~~~~0.0.1.0`
> 
> More info [here](https://superuser.com/questions/1561188/snip-sketch-tool-not-working-missing-ms-screenclip-protocol-handler)

This worked, now I can use Snip & Sketch. Thank you so much!
![image](https://github.com/user-attachments/assets/88c0e548-d4a6-4ce8-9dd9-81f770f83dea)
