### ISSUE TITLE
Is there any way to bring back Windows 10 style music flyout?

### ISSUE THREAD

**Issue by phibersoft** [ChrisTitusTech/winutil#2961]
**Describe the solution you'd like**
An option on Tweaks tab just like "Bring back old Right Click menu".

**Describe alternatives you've considered**
Some popular applications from MS Store but didn't liked. Most basic features missing on that applications.

![image](https://github.com/user-attachments/assets/1e3eeca2-c51a-42aa-a24c-369c820cba49)

**Comment by MyDrift-user** [comment]
The old Flyout was apparently stripped out entirely, meaning without 3rd party tool there isn't really a way to do it.

I'd suggest:
- open the action center, there you'll see a flyout with the media buttons
- use [ModernFlyouts](https://modernflyouts-community.github.io/), I think you can pretty much configure it to be like the one in Win10.
