### ISSUE TITLE
Install/Update fails if Discord is already installed and is selected

### ISSUE THREAD

**Issue by WrayOfSunshine** [ChrisTitusTech/winutil#2964]
## Describe the bug
If Discord is already installed (even if installed via WinUtil) and then is selected when choosing "Install/Upgrade Selected", the script does not fail over to the next install/upgrade when it should.

## To Reproduce
1. Click on Install tab.
2. Select Discord
3. Click on "Install/Upgrade Selected"
4. After install, click on "Install/Upgrade Selected" again (replicates error generated if you use "Get Installed" and then do an Install/Upgrade).
5. Script hangs at "Attempt installation of Discord.Discord with user scope"

## Expected behavior
The script should get the error report from winget that it cannot upgrade this package and move on to the next package or finish, as appropriate. This happens with other packages.

## Additional context
Notable - if I ctrl+c on the powershell window, I then get a popup asking for user credentials to be utilized to install Discord (this does not appear for me until I attempt to fail out of the install). Canceling that credential window gives an error about not being provided credentials, but still does not fail out of the install attempt sufficiently to allow working with the GUI.

**Comment by WrayOfSunshine** [comment]
I would personally prefer to see Discord installed on an all-users basis rather than per-user, in any case, but that's not relevant to this particular issue.

**Comment by ChrisTitusTech** [comment]
The Discord app auto updates. I'd recommend not having it checked when updating. I'll look into omiting if it detects it already installed.
