### ISSUE TITLE
The “WinUtil.Ink” shortcut is detected as “Trojan:Script/Phonzy.B!ml”

### ISSUE THREAD

**Issue by FoxyLoon** [ChrisTitusTech/winutil#2965]
## Describe the bug
**Today, Windows Defender said that the shortcut “WinUtil.Ink” was a trojan.**

I've had this shortcut for a long time. To create the shortcut, I ran the tool from the “Launch Command - Stable Branch (Recommended)” on the homepage and then clicked the button to create the shortcut on the desktop.

## To Reproduce
I haven't reproduced the bug. In fact, I haven't even opened the tool for a long time. 

I suppose the closest thing to getting the same result is:
1. Run the command “`irm ‘https://christitus.com/win’ | iex`” from the home page;
2. Go to the “Config” category;
3. Create the shortcut;
4. Wait for Windows Defender to detect it as a virus? Or check with Windows Defender? I don't know...

## Expected behavior
Not being caught as a Trojan and just existing in the desktop

## Screenshots
(Note: The language below is Portuguese)

Quarantined:
![imagem](https://github.com/user-attachments/assets/362abb28-ae34-46d4-b494-580c55e3db55)

Immediately after quarantine, it was deleted or blocked:
![imagem](https://github.com/user-attachments/assets/0c292f9c-16cf-4008-b03b-51edb7d54404)

## Additional context
I just opened the computer on a normal day and today it decided that the shortcut is a trojan. I didn't do anything special, it just happened. I didn't even open the shortcut.

**Comment by nikola-godzilla** [comment]
I can confirm too.
After run the tool I've clicked the "create shortcut" button.
Result - win defender immediately detected it as trojan and move it to quarantine.

**Comment by ii-46** [comment]
Last week i created short cut, but win defender doesn't detected it as trojan.
It only detected after windows security update
![image](https://github.com/user-attachments/assets/322823ad-24a5-48cb-84cd-9426691f9b63)

![image](https://github.com/user-attachments/assets/0fe8436d-c600-450b-bfa4-9253ba8f043e)

**Comment by AndreyGasik** [comment]
If you will be use defender, you will never can use powershell scripts without signature. Just switch off realtime defend if you want use normal software. Defender is your boss now, he say what you can use what not.

**Comment by FatBastard0** [comment]
I can't have the same issue with Bitdefander. So what I do is I go in turn bit defender off when I'm running the application script whatever

**Comment by FoxyLoon** [comment]
@FatBastard0 
> I can't have the same issue with Bitdefander. So what I do is I go in turn bit defender off when I'm running the application script whatever
This is not about BitDefender, but about Windows Defender

**Comment by xpl01ter** [comment]
I can confirm too, but with a different type of threat (Map/DownLink-D). When i try to run the command, the powershell window closes itself almost instantaneously. I only have time to create the shortcut.

![image](https://github.com/user-attachments/assets/fc693078-6ecf-47c3-9b29-4ac9366a4358)

**Comment by AndreyGasik** [comment]
and what? This tread for calculating people who cant stop his antivirus. Need denied that people use freeware soft.

**Comment by ChrisTitusTech** [comment]
I'll remove the shortcut creation and that will fix this flag.

**Comment by ChrisTitusTech** [comment]
Fixed in latest commit, will go live at the next release.

**Comment by NotYourAverageGamer** [comment]
I have created a discussion with a step-by-step tutorial on adding the Winutil shortcut manually, in a way that replicates the previous _(now removed)_ shortcut.
See: https://github.com/ChrisTitusTech/winutil/discussions/3127

**Comment by ham1tcagdas** [comment]
Simply Microsoft dont want you to disable their settings with this program and Microsoft wants to steal your data and collect it and sell it to make more money. You are not a valued person for Microsoft you are just a number or money in Wallet. If you want to be valued person try to use Linux thats why all hackers are using Linux. They know their value.

**Comment by FoxyLoon** [comment]
I'm on Linux now :3
I've had enough.
I am very grateful for this repository and for the people involved. Windows is unusable without it.
