### ISSUE TITLE
Win11 24H2 Edge Not Uninstalling

### ISSUE THREAD

**Issue by technub1** [ChrisTitusTech/winutil#2969]
## Describe the bug
The WinUtil isn't removing Edge as part of the Tweaks section to remove Edge

## To Reproduce
1. I started with a fresh install of Windows 11 24H2 from Microsoft's website.
2. I followed the instructions from the "The Perfect Windows 11 Install" video up until running the tweaks and changes in the WinUtil.
3. From the Tweaks section of the WinUtil, I selected "Remove Microsoft Edge" and ran that by itself. It didn't give any errors or say anything that it failed
4. I restarted my laptop and when i logged back in, I see that the Microsoft Edge shortcut is still on the desktop, as well as pinned in the taskbar.
5. I tried running the tweak again to remove Edge, and the prompt just says an Edge registry key isn't found and that it can't find uninstall methods for Edge. Which i'm assuming means it thinks Edge is gone. But Edge is still there and opens.

## Expected behavior
I was expecting to see the desktop icon and taskbar icon to be gone after restart. Let alone have the browser start when clicked on again

**Comment by Jeff-WuYo** [comment]
There's a repo [Remove-MS-Edge](https://github.com/ShadowWhisperer/Remove-MS-Edge), it's working for me as I wrote. Tested on 24h2 26100.2033

**Comment by technub1** [comment]
I actually downgraded back to 23H2 from 24H2 due to Recall being integrated into Explorer. It looks like winutil can still remove Edge in 23H2, but not 24H2. But Chris mentioned that Edge couldn't be uninstalled in 24H2 in one of his videos that I hadn't seen yet.

Now considering things, i'm not really too worried about Edge as long as it doesn't present any security or privacy issues, which I haven't heard of any yet.

> i am useing rove uninstaller to do that, That is my work around
Didn't realize Revo could uninstall Edge. Going to have to test that in a VM.

> Microsoft close that way with change region and delete edge, need use other way.
Yeah, i saw that Chris mentioned that in one of his videos that I hadn't watched yet.

**Comment by AndreyGasik** [comment]
Better use UUP dump website, download script, change settings and install clean OS, without edge and other things what you choose. After install use winutil for install what you need. Now is the best way for 24h2.

**Comment by technub1** [comment]
> Better use UUP dump website, download script, change settings and install clean OS, without edge and other things what you choose. After install use winutil for install what you need. Now is the best way for 24h2.

I'm not sure how to edit the UUP dump script settings to remove Edge. But i found a video on youtube of someone using something called Wise Program Uninstaller to do it. Albeit, you have to pick an option to "Force Uninstall", but it gets the job done. Heck, it seems even better than Revo.

**Comment by AndreyGasik** [comment]
### This file allows you to customize which Microsoft Store Apps are installed
### during the UUP to ISO conversion process.
###
### For changes done to this file to be applied, the CustomList option in the
### ConvertConfig.ini file needs to be set to 1.
### 
### This customization is supported only in builds 22563 and later.

### Choose the wanted apps from below by removing # prefix

### Common Apps / Client editions all
Microsoft.WindowsStore_8wekyb3d8bbwe
Microsoft.StorePurchaseApp_8wekyb3d8bbwe
Microsoft.SecHealthUI_8wekyb3d8bbwe
Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
# Microsoft.Windows.Photos_8wekyb3d8bbwe
# Microsoft.WindowsCamera_8wekyb3d8bbwe
# Microsoft.WindowsNotepad_8wekyb3d8bbwe
# Microsoft.Paint_8wekyb3d8bbwe
# Microsoft.WindowsTerminal_8wekyb3d8bbwe
# MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
# Microsoft.WindowsAlarms_8wekyb3d8bbwe
# Microsoft.WindowsCalculator_8wekyb3d8bbwe
# Microsoft.WindowsMaps_8wekyb3d8bbwe
# Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe
# Microsoft.ScreenSketch_8wekyb3d8bbwe
# microsoft.windowscommunicationsapps_8wekyb3d8bbwe
# Microsoft.People_8wekyb3d8bbwe
# Microsoft.BingNews_8wekyb3d8bbwe
# Microsoft.BingWeather_8wekyb3d8bbwe
# Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe
# Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe
# Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe
# Microsoft.GetHelp_8wekyb3d8bbwe
# Microsoft.Getstarted_8wekyb3d8bbwe
# Microsoft.Todos_8wekyb3d8bbwe
# Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe
# Microsoft.XboxGameOverlay_8wekyb3d8bbwe
# Microsoft.XboxIdentityProvider_8wekyb3d8bbwe
# Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe
# Microsoft.549981C3F5F10_8wekyb3d8bbwe
# MicrosoftCorporationII.QuickAssist_8wekyb3d8bbwe
# MicrosoftCorporationII.MicrosoftFamily_8wekyb3d8bbwe
# Clipchamp.Clipchamp_yxz26nhyzhsrt
# Microsoft.OutlookForWindows_8wekyb3d8bbwe
# MicrosoftTeams_8wekyb3d8bbwe
# Microsoft.Windows.DevHome_8wekyb3d8bbwe
# Microsoft.BingSearch_8wekyb3d8bbwe
# Microsoft.ApplicationCompatibilityEnhancements_8wekyb3d8bbwe
# MicrosoftWindows.CrossDevice_cw5n1h2txyewy
# MSTeams_8wekyb3d8bbwe
# Microsoft.MicrosoftPCManager_8wekyb3d8bbwe
# Microsoft.StartExperiencesApp_8wekyb3d8bbwe

### Media Apps / Client non-N editions
# Microsoft.ZuneMusic_8wekyb3d8bbwe
# Microsoft.ZuneVideo_8wekyb3d8bbwe
# Microsoft.YourPhone_8wekyb3d8bbwe
# Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe
# Microsoft.GamingApp_8wekyb3d8bbwe
# Microsoft.XboxGamingOverlay_8wekyb3d8bbwe
# Microsoft.Xbox.TCUI_8wekyb3d8bbwe

### Media Codecs / Client non-N editions, Team edition
# Microsoft.WebMediaExtensions_8wekyb3d8bbwe
# Microsoft.RawImageExtension_8wekyb3d8bbwe
# Microsoft.HEIFImageExtension_8wekyb3d8bbwe
# Microsoft.HEVCVideoExtension_8wekyb3d8bbwe
# Microsoft.VP9VideoExtensions_8wekyb3d8bbwe
# Microsoft.WebpImageExtension_8wekyb3d8bbwe
# Microsoft.DolbyAudioExtensions_8wekyb3d8bbwe
# Microsoft.AVCEncoderVideoExtension_8wekyb3d8bbwe
# Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe
# Microsoft.AV1VideoExtension_8wekyb3d8bbwe

### Surface Hub Apps / Team edition
# Microsoft.Whiteboard_8wekyb3d8bbwe
# microsoft.microsoftskydrive_8wekyb3d8bbwe
# Microsoft.MicrosoftTeamsforSurfaceHub_8wekyb3d8bbwe
# MicrosoftCorporationII.MailforSurfaceHub_8wekyb3d8bbwe
# Microsoft.MicrosoftPowerBIForWindows_8wekyb3d8bbwe
# Microsoft.SkypeApp_kzf8qxf38zg5c
# Microsoft.Office.Excel_8wekyb3d8bbwe
# Microsoft.Office.PowerPoint_8wekyb3d8bbwe
# Microsoft.Office.Word_8wekyb3d8bbwe


Other file:

[convert-UUP]
AutoStart    =1
AddUpdates   =1
Cleanup      =0
ResetBase    =0
NetFx3       =0
StartVirtual =0
wim2esd      =0
wim2swm      =0
SkipISO      =0
SkipWinRE    =0
LCUwinre     =0
UpdtBootFiles=0
ForceDism    =0
RefESD       =0
SkipLCUmsu   =0
SkipEdge     =0
AutoExit     =0
DisableUpdatingUpgrade=0
AddDrivers   =0
Drv_Source   =\Drivers

[Store_Apps]
SkipApps     =0
AppsLevel    =0
StubAppsFull =0
CustomList   =0

[create_virtual_editions]
vUseDism     =1
vAutoStart   =1
vDeleteSource=0
vPreserve    =0
vwim2esd     =0
vwim2swm     =0
vSkipISO     =0
vAutoEditions=


All so clear, and really work, in script folder have this 2 files, just choose what you want and you will recieve iso without mant garbages. I use it for myself, it reall clean and fast. Just try if you want.

**Comment by AndreyGasik** [comment]
For ununstall edge i use geek uninstaller , just 1 file, no need install, work good and fast. i use it before start make iso for myself.

**Comment by AndreyGasik** [comment]
Really. after uninstall Edge or something, sfc /scannow command return all files back. and after uninstall component storage will be marked like broken, need restore. So for me uup iso is the way for have clean system without component storage damage.

**Comment by technub1** [comment]
I like and do grab windows ISOs from UUP Dump, but i prefer just using Wise Uninstaller to uninstall Edge since it has that capability. And the utility includes the option to install Wise which makes it more convenient. So overall, it sounds like it's a known issue but has easy enough workarounds. Does this issue need to be closed now @AndreyGasik ?

**Comment by AndreyGasik** [comment]
For me it not a problem. Sure you can close.

**Comment by Jeff-WuYo** [comment]
@technub1 Are you able to install cumulative update after edge is removed? I haven't tested UUP method, but, I've tested remove edge from winutil against 23h2 and [Remove-MS-Edge](https://github.com/ShadowWhisperer/Remove-MS-Edge) against 24h2, both scenarios work. After remove edge, I can't install cumulative update, it will get in install fail loop.

**Comment by technub1** [comment]
@Jeff-WuYo Not sure. Haven't dealt with removing Edge long term. I was able to remove Edge with an uninstaller called Wise Program Uninstaller.

I'd say just try reinstalling Edge standalone and see if the cumulative update will install again. Then remove Edge again afterwards if you want. Best thing I could suggest.

**Comment by Jeff-WuYo** [comment]
Well, I've done my initial test. I used UUP dump to create an compressed iso without Edge, without update bundled, skip every windows app except winget. I was able to install cumulative update just fine. I still need to test it more, long term test I should say. By feeding created iso to microwin, I can create a very minimal windows iso.

**Comment by Brad-git-man** [comment]
Bump, Bump. Can anyone say if the exclude Edge setting is in the CustomList file and if so, which one is it? I thoroughly believe that Firefox is the way forward, especially now with MV3 in Chromium based browsers.
