### ISSUE TITLE
Christitus winutil errors

### ISSUE THREAD

**Issue by wntrhwk** [ChrisTitusTech/winutil#2975]
Hello, new to the forum so pls be aware. I have been using this utility on various machine's with no issues. Just bought a new Win11 laptop, ran the program, loaded fine. Ran some "tweaks", again no problem. When I try to run "00 Shutup" I get this msg in the terminal screen, "Error downloading and running 00 Shutup 10". Any help would be appreciated.

**Comment by ChrisTitusTech** [comment]
I think their site must have been down. I am unable to replicate this and it launches for me.

**Comment by wntrhwk** [comment]
Thx Chris, I think it was my fault. It looks like I may have run the program twice which caused the error. I was able to get in and run it later. 

Mike
