### ISSUE TITLE
WTH???

### ISSUE THREAD

**Issue by Fattcracker2u** [ChrisTitusTech/winutil#2983]
I want it Off my computer... Some Updates are managed by your Organization now? WTF?... I didn't sign up for THAT...  How do I get you Out of My Pocket Mini Bill Gates... WIndows Utility that is....

**Comment by MyDrift-user** [comment]
May I ask if you set one of the options in the "Updates" tab?

**Comment by AndreyGasik** [comment]
Windows Utility is amazing, for people with brain.
