### ISSUE TITLE
Windows update stop work after run standard tweaks

### ISSUE THREAD

**Issue by qwerty59b** [ChrisTitusTech/winutil#2984]
hello i am noob i found doing a search on the internet this script to optimize windows i ran it in powershell and i went to the tweaks option i checked standard and run tweaks after i finished windows update it stopped working as i show in the picture below

![Captura de pantalla (1)](https://github.com/user-attachments/assets/cd577eb1-4a40-4c88-8adb-0e5aea56ba0b)

![Captura de pantalla (2)](https://github.com/user-attachments/assets/c5104470-b49c-4f7a-88d7-d885f3431a79)

**Comment by ChrisTitusTech** [comment]
You don't have a network connection...

**Comment by qwerty59b** [comment]
@ChrisTitusTech 

Let me explain when the script finished running standard tweaks I had a connection and I checked for updates with Windows update and it gave that error of the picture 1 then I restarted the PC and when it started I took that capture without connection and I reconnected to the internet because in my country the internet is by captive portal and I ran the script again from powershell and then I took the capture 2.

In the end I ended up restoring the system with the restore point that creates the script and ran the script again but without the services checkbox to manual and everything fine
