### ISSUE TITLE
Disable Vmware

### ISSUE THREAD

**Issue by MathieuT1508** [ChrisTitusTech/winutil#2985]
Disable all VMware services whether it is a program at start-up or service that starts

**Comment by Marterich** [comment]
Most likely we won't add an option for this as VMWare Services (and programs) have to be deliberately installed and are legitimate tools that depend on their components. 

What do you hope to accomplish with this addition and why do you think it is necessary to automate this?

**Comment by Marterich** [comment]
Closed due to inactivity /close
