### ISSUE TITLE
Teams installation not found

### ISSUE THREAD

**Issue by CrowVL** [ChrisTitusTech/winutil#299]
**Describe the bug**
While trying to remove all the windows apps i get this error

**To Reproduce**
1. Go to tweaks tab
2. Click on remove all ms store apps
3. See error

**Screenshots**
https://streamable.com/8qfxxj

**Additional context**
Im on a fresh w10 22H2 install if it could be helpful

**Comment by simplerethink** [comment]
Same issue, but Win11

Edition	Windows 11 Pro
Version	22H2
OS build	22621.525
Experience	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by ChrisTitusTech** [comment]
Fixed in latest PR #317
