### ISSUE TITLE
Clipboard History Missing on W10

### ISSUE THREAD

**Issue by adnval** [ChrisTitusTech/winutil#2995]
## Describe the bug
Clipboard history window does not show up after pressing WinKey + V despite having it enabled in settings. This is after running the tweaks. I have looked at the provided solutions in previously posted issues revolving around changing the settings in OO ShutUp, however they did not work. Is there perhaps a different solution for people still on W10?

## Steps to reproduce
1. Install W10 iso and port it through MicroWin and create a W10 Pro drive through Rufus.
2. Run the default set of tweaks on WinUtil.
3. Opened OO ShutUp and re-enabled the settings involving clipboard history.
4. Enabled clipboard history in Settings app.
5. Restarted Windows
6. WinKey + V, not a single window pops up.

## Expected behavior
A clipboard window should show up after re-enabling history in OO ShutUp and the settings app and pressing WinKey + V.

## Screenshots
![image](https://github.com/user-attachments/assets/2d697f29-5b96-4ed3-ae9e-54e0dcdff98d)
![image](https://github.com/user-attachments/assets/4c8a263a-3f32-48e0-9bac-3590e12254c7)
![image](https://github.com/user-attachments/assets/837e9770-e2ff-453d-86a9-c8851898565c)

**Comment by zmileski** [comment]
Works for me
![clipboard](https://github.com/user-attachments/assets/57742764-0d9b-42d7-82aa-8fefa69190f7)

**Comment by MyDrift-user** [comment]
since this was not reproducable, I'm going to close this out.
I recommend using the undo all changes (factory reset) option under O&O Shutup, that helped me.

/close

**Comment by Landy005** [comment]
have the exact same problem right now

i disabled storage of clipboard history *to whole machine*, after restart winkey + v doesnt work anymore. Even when enabled in regedit and settings. 

storage of clipboard history is still enabled

So yep, this is a bug.

**Comment by MyDrift-user** [comment]
So if you activate it again it does not work?
Also this is a policy, for it to take effect you either wait for a long time, do a `gpupdate /force` or reboot your machine.
