### ISSUE TITLE
Explorer Patcher

### ISSUE THREAD

**Issue by Livealoha808** [ChrisTitusTech/winutil#2996]
## Describe the bug
when installing Explorer Patcher, the "right" click on the start button does not generate the menu.  Installed latest version 22621.3880.66.6

## To Reproduce
1. Go to 'right click start menu'
2. Click on 'right click start menu'

## Expected behavior
<does not generate menu

## Additional context
Everything else appears to work with Explorer Patcher.

**Comment by MyDrift-user** [comment]
Hey there @Livealoha808 
This is the WinUtil Repository. If you have an Issue with this application, I'd suggest making an Issue in the official [ExplorerPatcher Repository](https://github.com/valinet/ExplorerPatcher).

/close

**Comment by Livealoha808** [comment]
if i install Win11 without using microwin, Explorer Patcher installs fine with no issue.

**Comment by MyDrift-user** [comment]
/reopen
Maybe @CodingWonders knows something about this.

**Comment by CodingWonders** [comment]
@Livealoha808, can you show the error with Explorer Patcher?

**Comment by Livealoha808** [comment]
hmm thanks for responding, actually nothing to show..when I "Right" click on the start button, it should bring up the context menu, unfortunately, nothing happens.  No error message.  When i uninstall Explorer Patcher, then "right" click on the start button, brings back the context menu, so i know the file(s), shortcuts are there (appdata\local\microsoft\windows\winx)  all 3 groups 1-3 have the shortcuts...

**Comment by CodingWonders** [comment]
Could you report the problem on the ExplorerPatcher repository?

**Comment by Livealoha808** [comment]
Okay, thanks..just thought it had something to do with Microwin, since it does work using the same iso without using microwin.

**Comment by MyDrift-user** [comment]
We (atleast I) do not know the exact issue bc we are not experienced with errorhandling explorerpatcher. Meaning theyr support will be better at identifying the issue. If we know the exact issue and that it is because of microwin we may be able to "fix" it if it is an actual issue.

Explorerpatcher is known for its issues, one week you have some and others it works fine. On some devices it work fine on other not so great.
