### ISSUE TITLE
Add Android Studio to WinUtil for Enhanced Development Support

### ISSUE THREAD

**Issue by catsmoker** [ChrisTitusTech/winutil#3006]
**Is your feature request related to a problem? Please describe.**
I’d like to see WinUtil support Android development setups, particularly with Android Studio, as currently, setting up an Android development environment on Windows can be time-consuming and requires multiple configurations.

**Describe the solution you'd like**
Integrate Android Studio into WinUtil, providing a streamlined installation and setup process. This feature could automate installing Android Studio, configuring necessary SDKs, and setting up the Android Virtual Device (AVD) Manager to save developers time.

**Describe alternatives you've considered**
Alternatives include using Android Studio's official installer or third-party scripts, but these options lack the convenience and integration that a WinUtil feature would provide for a cohesive setup experience.

**Additional context**
Adding this feature would make WinUtil more appealing for Android developers using Windows, potentially increasing its user base.

**Comment by CodingWonders** [comment]
We are not accepting any application requests for now, given that the Install section is quite bloated
