### ISSUE TITLE
Please add disable automatic drivers install 

### ISSUE THREAD

**Issue by Ja2kub** [ChrisTitusTech/winutil#3007]
in some laptops and maybe computers this is needed because windows update does not see some drivers despite installing them through it or through another source

**Comment by zmileski** [comment]
If you use "Security (Recommended) Settings" under Updates on winutil will disable driver offering through Windows Update.

**Comment by SlimJim192** [comment]
I would like to see this as a checkbox on Microwin so we can have it from first boot.

Although it can be done on winutil, by the time i got it open windows update already done its thing..

Would also be nice to have a seperate toggle in winutil, so I could have security settings but choose to turn on driver updates in some use cases.

**Comment by zmileski** [comment]
It is good idea to have it on Microwin, i always install windows offline then on first boot pause updates then use Security (Recommended) Settings from winutil.
@SlimJim192 Add Microwin in the tittle of the issue

**Comment by SlimJim192** [comment]
Not my ticket so dont think I cant

**Comment by zmileski** [comment]
Sorry my bad

**Comment by Ja2kub** [comment]
I think it's a good idea to have it as a separate option
