### ISSUE TITLE
Taskbar/Startmenu unresponsive

### ISSUE THREAD

**Issue by RW-INC** [ChrisTitusTech/winutil#3009]
## Describe the bug
Using the standard tweaks caused the taskbar doesn't work. Windows key doesn't work -> forces signout and relog. 

## To Reproduce
Used standard tweaks in the GUI

## Expected behavior
to still be able to use taskbar and search

**Comment by RW-INC** [comment]
Can confirm this is occurring went through and thought I resolved it however this appears to persist

**Comment by RW-INC** [comment]
![image](https://github.com/user-attachments/assets/d0d616af-ae77-4303-8ea8-e54f457522b6)
attached is a screenshot of what occurs when I press the super (windows in my case) key

**Comment by RW-INC** [comment]
![image](https://github.com/user-attachments/assets/aa75a8e4-38ff-4f7f-98e5-02a9e1cb5ce3)
attached is a screenshot of what occurs when the windows key is pressed

**Comment by zmileski** [comment]
Can you provide info which windows version you are using

**Comment by RW-INC** [comment]
@zmileski it's win 11 Version 10.0.22631 Build 22631

**Comment by zmileski** [comment]
Can't replicate the issue ,don't think winutil caused this, seems like bad windows update or corupt system files.

**Comment by RW-INC** [comment]
Gotcha the interesting part is the issue only presented after running winutil. I also ran the corruption check and afterwards I restarted still the issue persisted. I fixed it by restoring a previous recovery point. Not sure what happened but i'm going to try again but do sfc first.

**Comment by MyDrift-user** [comment]
Hey there @RW-INC 

It has been two weeks now and u did not report any further issues.
So I'd like to think that your system is working now :) 
I am going to close this issue out, if the issue persists after running the tweaks, you may reopen this.

/close
