### ISSUE TITLE
WinUtil Fails to removed Home & Gallery from Windows Explorer.

### ISSUE THREAD

**Issue by anthonyrpitts** [ChrisTitusTech/winutil#3011]
## To Reproduce
1. Use WinUtil shortcut created with WinUtil
2. Navigate to Twekaks, Advanced Tweaks
3. Select Remove Home and Gallery from explorer
4. Click on "Run Tweaks"
5. Confirmation of Selected Script has been executed
6. Close WinUtil
7. Log out of User Account
8. Login into Windows
9. Open Windows Explorer
10. Home and Gallery are still in the menu top left hand side

Edition			Windows 11 Pro
Version			23H2
Installed on	‎5/‎11/‎2024
OS build		22631.2861
Experience		Windows Feature Experience Pack 1000.22681.1000.0

## Expected behavior
Home and Gallery should be removed from Windows Explorer

## Screenshots

![Screenshot 2024-11-05 235313](https://github.com/user-attachments/assets/f60df9e3-839f-4e86-a864-a0b022b3c84e)

**Comment by zmileski** [comment]
Works on 24h2
![4](https://github.com/user-attachments/assets/1c02a990-1623-4cb9-96ff-cfc780282968)
![5](https://github.com/user-attachments/assets/59597f5d-67fc-4620-8d73-f483c23de57e)

i had the same issue on 23h2 on old build
try update to latest 22631.4391 and try winutil again
or try this
[Remove Home and Gallery.zip](https://github.com/user-attachments/files/17646257/Remove.Home.and.Gallery.zip)
