### ISSUE TITLE
24h2 oct 2024 - WinUtil Installation process not working - similar to "winget #2986"

### ISSUE THREAD

**Issue by Juanc179** [ChrisTitusTech/winutil#3013]
Hi, i tried to install programs with the utility as usual with a new windows 24h2 installation and it does a similar thing as it did with 23h2. it just doesn't install programs, and it does set configs properly. 

to recreate: 
(clean win 11 24h2 install) 

- Run the utility from shortcut or from powershell. 
- Select programs to install (no tweaks or any other config changed).
- terminal says, "Getting installed tweaks" and "Getting Install programs", then "done". but no tweaks were changed and no programs get installed.
- tried to use choco and Winget Reinstall. 
- 2 packets failed (something about the word "module" not being recognized.
- tried to install again, same issue.
- Winget Reinstall Again.... same issue. 
- unclick the "prefer choco" box. 
- tried again, and same issue. 

Terminal output.
`
====Chris Titus Tech=====
=====Windows Toolbox=====
Getting Installed Programs...
Getting Installed Tweaks...
Done...
Getting Installed Programs...
Getting Installed Tweaks...
Done...
Checking if Chocolatey is Installed...
===========================================
---    Chocolatey is not installed      ---
===========================================
Seems Chocolatey is not installed, installing now.
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/2.3.0.
Downloading https://community.chocolatey.org/api/v2/package/chocolatey/2.3.0 to C:\Users\jcpis\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Extracting C:\Users\jcpis\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\jcpis\AppData\Local\Temp\chocolatey\chocoInstall
Installing Chocolatey on the local machine
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\jcpis\OneDrive\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Ensuring Chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
Chocolatey v2.3.0
Installing the following packages:
winget
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-ui-xaml-2-7 2.7.3... 100%

microsoft-ui-xaml-2-7 v2.7.3 (forced) [Approved]
microsoft-ui-xaml-2-7 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-ui-xaml-2-7 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-vclibs-140-00 14.0.33321... 100%

microsoft-vclibs-140-00 v14.0.33321 (forced)
microsoft-vclibs-140-00 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-vclibs-140-00 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading winget-cli 1.9.25180... 100%

winget-cli v1.9.25180 (forced) [Approved]
winget-cli package files install completed. Performing other installation steps.
WARNING: The installed version of the app package, 2024.1025.2351.0, is the same vesion that this Chocolatey package installs, 2024.1025.2351.0.
WARNING: The '--force' option has been used so we will attempt to install the app package version 2024.1025.2351.0.
Downloading winget-cli
  from 'https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\winget-cli\tools\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle (225.88 MB).
Download of Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle (225.88 MB) completed.
Hashes match.
C:\ProgramData\chocolatey\lib\winget-cli\tools\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Downloading winget-cli
  from 'https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/0a769c4da0ae4747ba4ab2f173709ced_License1.xml'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\winget-cli\tools\License.xml (2.63 KB).
Download of License.xml (2.63 KB) completed.
Hashes match.
C:\ProgramData\chocolatey\lib\winget-cli\tools\License.xml
WARNING: Note that the Microsoft may collect data when the WinGet-CLI software is installed.
WARNING: Please see https://github.com/microsoft/winget-cli#datatelemetry for more information on how to opt-out.
 The install of winget-cli was successful.
  Software install location not explicitly set, it could be in package or
  default install location of installer.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading winget 1.9.25180... 100%

winget v1.9.25180 (forced) [Approved]
winget package files install completed. Performing other installation steps.
 The install of winget was successful.
  Deployed to 'C:\ProgramData\chocolatey\lib\winget'

Chocolatey installed 2/4 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-ui-xaml-2-7 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
 - microsoft-vclibs-140-00 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Getting Installed Programs...
Getting Installed Tweaks...
Done...
===========================================
---        Winget is installed          ---
===========================================
Version: v1.9.25180
    - Winget is a release version.
    - Winget is Up to Date
Getting Installed Programs...
Done...
Checking if Chocolatey is Installed...
===========================================
---      Chocolatey is installed        ---
===========================================
Version: v2.3.0
Chocolatey v2.3.0
Installing the following packages:
winget
By installing, you accept licenses for the packages.
winget v1.9.25180 already installed. Forcing reinstall of version '1.9.25180'.
 Please use upgrade if you meant to upgrade to a new version.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-ui-xaml-2-7 2.7.3... 100%

microsoft-ui-xaml-2-7 v2.7.3 (forced) [Approved]
microsoft-ui-xaml-2-7 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-ui-xaml-2-7 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-vclibs-140-00 14.0.33321... 100%

microsoft-vclibs-140-00 v14.0.33321 (forced)
microsoft-vclibs-140-00 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-vclibs-140-00 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading winget 1.9.25180... 100%

winget v1.9.25180 (forced) [Approved]
winget package files install completed. Performing other installation steps.
 The install of winget was successful.
  Deployed to 'C:\ProgramData\chocolatey\lib\winget'

Chocolatey installed 1/3 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-ui-xaml-2-7 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
 - microsoft-vclibs-140-00 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
`

**Comment by Juanc179** [comment]
i tried to use WinGet dirrectly and it works, i tried to install PowerToys manually with 

'
 winget install Microsoft.PowerToys
Encontrado PowerToys [Microsoft.PowerToys] Versión 0.86.0
El propietario de esta aplicación le concede una licencia.
Microsoft no es responsable, ni tampoco concede ninguna licencia de paquetes de terceros.
Descargando https://github.com/microsoft/PowerToys/releases/download/v0.86.0/PowerToysUserSetup-0.86.0-x64.exe
  ████████████████████             181 MB /  271 MB
'

it seems to be working...

**Comment by zmileski** [comment]
winget works fine
![1](https://github.com/user-attachments/assets/7498a2a2-b9b5-45f1-abd0-b50ae3484b57)

**Comment by zmileski** [comment]
Also winget reinstall works regardless of errors for upgrade of xaml and vlibs
![1](https://github.com/user-attachments/assets/505b7a81-6957-4f8e-a55f-be2240e42b67)
![2](https://github.com/user-attachments/assets/28b96933-6d5b-4bea-8e8d-1abd879a83ab)
![3](https://github.com/user-attachments/assets/fe0f4e01-feb8-44eb-b899-fe2212388969)

**Comment by DarkWolf0057** [comment]
I have a similar problem,  when trying to install anything after fresh windows installation it says "system does not have access to the file"

**Comment by Juanc179** [comment]
@zmileski in my case the install option doesn't work.... But winget commands outside the utility work.. What can I do?

I tried by updating Winget, App installer and windows in general. It doesn't work...

Is there any info I can give you four troubleshooting?

**Comment by zmileski** [comment]
Try install with prefer choco
But first delete folders of chocolatey in C/ProgramData

**Comment by Juanc179** [comment]
> Try install with prefer choco
> But first delete folders of chocolatey in C/ProgramData

Same behavior, doesn't event try to reinstall choco. I deleted two folders in program data but the terminal output at install process is the same. What is surprising is that doesn't detect that the choco folders are missing.... Either way, they didn't appeared after I deleted them and executed the utillity.

**Comment by zmileski** [comment]
That's strange, can't replicate the issue
can you provide screen of terminal output error

**Comment by Juanc179** [comment]
steps: 
- run the utility. 
- install programs without choco.
- install programs with choco. (doesnt do anything)
- Winget Reinstall, installs choco.
- Install programs with choco, same behavior.

`
====Chris Titus Tech=====                                                                                               =====Windows Toolbox=====                                                                                               ===========================================                                                                             ---        Winget is installed          ---                                                                             ===========================================                                                                             Version: v1.9.25180                                                                                                         - Winget is a release version.
    - Winget is Up to Date
Getting Installed Programs...   ---whitout choco checkbox----
Done...
Getting Installed Programs... .----with choco checkbox, after deleting folder on /programdata---
Getting Installed Tweaks...
Done...
Checking if Chocolatey is Installed...  ---Winget Reinstall---
===========================================
---    Chocolatey is not installed      ---
===========================================
Seems Chocolatey is not installed, installing now.
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/2.3.0.
Downloading https://community.chocolatey.org/api/v2/package/chocolatey/2.3.0 to C:\Users\jcpis\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Extracting C:\Users\jcpis\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\jcpis\AppData\Local\Temp\chocolatey\chocoInstall
Installing Chocolatey on the local machine
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\jcpis\OneDrive\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Ensuring Chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder
Chocolatey v2.3.0
Installing the following packages:
winget
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-ui-xaml-2-7 2.7.3... 100%

microsoft-ui-xaml-2-7 v2.7.3 (forced) [Approved]
microsoft-ui-xaml-2-7 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-ui-xaml-2-7 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-vclibs-140-00 14.0.33321... 100%

microsoft-vclibs-140-00 v14.0.33321 (forced)
microsoft-vclibs-140-00 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-vclibs-140-00 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading winget-cli 1.9.25180... 100%

winget-cli v1.9.25180 (forced) [Approved]
winget-cli package files install completed. Performing other installation steps.
WARNING: The installed version of the app package, 2024.1025.2351.0, is the same vesion that this Chocolatey package installs, 2024.1025.2351.0.
WARNING: The '--force' option has been used so we will attempt to install the app package version 2024.1025.2351.0.
Downloading winget-cli
  from 'https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\winget-cli\tools\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle (225.88 MB).
Download of Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle (225.88 MB) completed.
Hashes match.
C:\ProgramData\chocolatey\lib\winget-cli\tools\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Downloading winget-cli
  from 'https://github.com/microsoft/winget-cli/releases/download/v1.9.25180/0a769c4da0ae4747ba4ab2f173709ced_License1.xml'
Progress: 100% - Completed download of C:\ProgramData\chocolatey\lib\winget-cli\tools\License.xml (2.63 KB).
Download of License.xml (2.63 KB) completed.
Hashes match.
C:\ProgramData\chocolatey\lib\winget-cli\tools\License.xml
WARNING: Note that the Microsoft may collect data when the WinGet-CLI software is installed.
WARNING: Please see https://github.com/microsoft/winget-cli#datatelemetry for more information on how to opt-out.
 The install of winget-cli was successful.
  Software install location not explicitly set, it could be in package or
  default install location of installer.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading winget 1.9.25180... 100%

winget v1.9.25180 (forced) [Approved]
winget package files install completed. Performing other installation steps.
 The install of winget was successful.
  Deployed to 'C:\ProgramData\chocolatey\lib\winget'

Chocolatey installed 2/4 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-ui-xaml-2-7 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
 - microsoft-vclibs-140-00 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
Getting Installed Programs...
Getting Installed Tweaks...
Done...
`

i tried to restart de utility and nothing changed on the functionality. im using powershell as an administrator.
here is the log of the last use:


Windows PowerShell transcript start
Start time: 20241108153237
Username: PC79-W000\jcpis
RunAs User: PC79-W000\jcpis
Configuration Name: 
Machine: PC79-W000 (Microsoft Windows NT 10.0.26100.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 1324
PSVersion: 5.1.26100.1882
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.26100.1882
BuildVersion: 10.0.26100.1882
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

**Comment by zmileski** [comment]
Did you press "Get Installed" button ?

**Comment by Juanc179** [comment]
Its working, i was erroneously using the "get installed" option. i remembered badly how to use the utility apparently. sorry for your time...

**Comment by TheBigBear** [comment]
@ChrisTitusTech what can I do or how can I overcome both the choco install a choco reinstall commands failing under win11 24H2? Regardless of whether I use it inside your tools or from the ps cmd line? I get this: 

```errors
choco install winget -y
Chocolatey v2.4.2
Installing the following packages:
winget
By installing, you accept licenses for the packages.
Downloading package from source 'https://chocolatey.org/api/v2/'
Progress: Downloading microsoft-vclibs-140-00 14.0.33321... 100%

microsoft-vclibs-140-00 v14.0.33321
microsoft-vclibs-140-00 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-vclibs-140-00 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Failed to install winget-cli because a previous dependency failed.
Failed to install winget because a previous dependency failed.

Chocolatey installed 0/3 packages. 3 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-vclibs-140-00 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
 - winget - Failed to install winget because a previous dependency failed.
 - winget-cli - Failed to install winget-cli because a previous dependency failed.
```

I opened an issue here https://github.com/ChrisTitusTech/winutil/issues/3193 but not sure it is 'your' problem or issue? Seems to me it is a chocolatey issue, right? I also created an issue on their repo here
