### ISSUE TITLE
Add tweaks/preference to disable amination and fade on windows 11

### ISSUE THREAD

**Issue by lucamosca1** [ChrisTitusTech/winutil#3020]
An additional step I have to do to speedup a little my Windows 11 installation (in particular on old computers) apart running tweaks from the script is to disable all animations, fades and shades from System properties - Advenced system configuration.

Could be useful to add this feature as 1 click option: disable animation or everything is fine, maybe with some context or suggestion, in tweaks section, Essential tweaks or Preferences I don't know where it fits better.

This could help older Computer to run faster, Windows 11 debloated isn't light anyway for some machines.

**Comment by zmileski** [comment]
Already exsists in Essential-Tweaks "Set Display for Performance"

**Comment by lucamosca1** [comment]
Got it, closed.
Thanks
