### ISSUE TITLE
Winutil breaks Windows Security

### ISSUE THREAD

**Issue by asdhashdh** [ChrisTitusTech/winutil#3028]
## Describe the bug
When using Winutil Windows Security now shows "Your IT administrator has limited access to some areas of this app" when trying to go to some pages such as Ransomware Protection using the start menu and if you go directly to Windows Security there are no options at all.
## To Reproduce
Used standard tweaks.

## Expected behavior
Windows Security to work normally.

## Screenshots
![image](https://github.com/user-attachments/assets/bc75a912-f835-4e82-acac-4bbd08ced0b0)
![image](https://github.com/user-attachments/assets/93044754-95b0-496f-88f2-5a41b265d978)

**Comment by asdhashdh** [comment]
@ChrisTitusTech please help, thanks in advance.

**Comment by zmileski** [comment]
did you used other tool besides winutil?

**Comment by asdhashdh** [comment]
> did you used other tool besides winutil?

No, only Einutil. I know for sure it's Winutil as it is on my 2nd pc also and the only thing they have in common is that I used Winutil on both of them,

**Comment by zmileski** [comment]
You have malwarebytes installed...

**Comment by asdhashdh** [comment]
> You have malwarebytes installed...

Yes but it shouldn't cause any issue because I never had this until i used Winutil and I have been using Malwarebytes for years.

**Comment by zmileski** [comment]
Well i am 100% sure Malwarebyte caused this. Not winutil.
You can close this issue.

**Comment by asdhashdh** [comment]
> Well i am 100% sure Malwarebytes caused this. Not winutil.
> 
> You can close this issue.

How would you know? I have used Malwarebytes for 3 computers and 5 years and I have never gotten this before using Winutil and I still have a computer that I didn't use Winutil on and it doesn't have the issue.

**Comment by zmileski** [comment]
Without Malwarebytes
![1](https://github.com/user-attachments/assets/f4dcfce8-2e8d-4cc9-8915-e62eff33ec4b)
![2](https://github.com/user-attachments/assets/0db1aad0-be46-48fc-8e2e-ff2780f9d5c4)

With Malwarebytes
![3](https://github.com/user-attachments/assets/09c55dbb-31ac-455a-b38c-ce7cd46de5df)
![4](https://github.com/user-attachments/assets/ae13ac50-fd6d-4081-9817-00e7772541c1)

**Comment by asdhashdh** [comment]
> Without Malwarebytes
> 
> ![1](https://github.com/user-attachments/assets/f4dcfce8-2e8d-4cc9-8915-e62eff33ec4b)
> 
> ![2](https://github.com/user-attachments/assets/0db1aad0-be46-48fc-8e2e-ff2780f9d5c4)
> 
> 
> 
> With Malwarebytes
> 
> ![3](https://github.com/user-attachments/assets/09c55dbb-31ac-455a-b38c-ce7cd46de5df)
> 
> ![4](https://github.com/user-attachments/assets/ae13ac50-fd6d-4081-9817-00e7772541c1)

Thank you! I realized there was a settings in Malwarebytes app for it, I will know close the issue.
