### ISSUE TITLE
transmission app firewall rules set improperly and make it tough to port forward?

### ISSUE THREAD

**Issue by jbaylies** [ChrisTitusTech/winutil#3034]
Not sure if this was due to winutil or something else but I'm just leaving this here in case someone else encounters it.

If you install Transmission via winutil and aren't sure why port forwarding isn't working, be sure to go to Windows Settings > Network > Windows Firewall > Advanced Settings > Inbound Rules > Transmission Qt Client > Allow the Connection > Apply.

**Comment by MyDrift-user** [comment]
we do not offer support for applications in the utility as we have no control over the actual packages being released.
If you'd like this to be fixed I suggest reporting this to the team of that transmission app.

closing this out now :)

/close
