### ISSUE TITLE
Stop automatic restart after windows update

### ISSUE THREAD

**Issue by eslam5464** [ChrisTitusTech/winutil#3042]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great if there is an option in the tweaks tab or something like a checkbox to disable automatic restart after updates.

**Describe alternatives you've considered**
None

**Additional context**
The solution I found in this community post: [Microsoft Answers](https://answers.microsoft.com/en-us/windows/forum/all/disable-windows-10-automatic-restart-after-updates/16f1826d-a796-4de8-ac99-1d625420d265)

Image for the answer:
![image](https://github.com/user-attachments/assets/f35f431e-8aa4-4f09-99d0-e69165df4466)

**Comment by zmileski** [comment]
Use "**Security (Recommended) Settings**" from **Updates**  tab in winutil

![1](https://github.com/user-attachments/assets/7debd20c-8c13-41ce-85d3-5124c1ae327b)

**Comment by eslam5464** [comment]
hmm... i already did before maybe after an update it got reset to its default value, well thanks for the assist
