### ISSUE TITLE
Confing not working

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#3046]
When I run
irm "https://christitus.com/windev" | iex

I get to into Config
and mark NFS

I get this

![ScreenShot_20241117142208](https://github.com/user-attachments/assets/54092961-2417-4b0d-8883-276ad9e58a74)

All virus programs are set to off

## Expected behavior
I do not know. Should it show the above

**Comment by zmileski** [comment]
Works fine for me

![Untitled](https://github.com/user-attachments/assets/b0bdc9b4-1fe0-4d66-89c2-cb99902529e3)
