### ISSUE TITLE
tweaks lockup

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#3050]
Note: virus protection turn off

load irm "https://christitus.com/windev" | iex

goto Tweaks
Run Delete Temporary flies
I let it run for 2 mins
it dose nothing just sit there 
I do a control C
nothing
I hit the esc
and get this
![ScreenShot_20241119081818](https://github.com/user-attachments/assets/278f1ebb-8df2-4750-ac47-97ce59e77996)

**Comment by FatBastard0** [comment]
that all I have

**Comment by zmileski** [comment]
Works fine for me
![temp](https://github.com/user-attachments/assets/38ca4fa9-a4d7-40bb-a9c5-657b2522cf94)

**Comment by FatBastard0** [comment]
ok, must be me
