### ISSUE TITLE
Classic Right-Click context menu enabled by MicroWin - Unable to revert

### ISSUE THREAD

**Issue by wwc-trevor** [ChrisTitusTech/winutil#3055]
## Describe the bug
I am unable to revert the classic right-click context menu back to the new.

## To Reproduce
I did not use the util to set the classic menu, it was just enable after running MicroWin on the latest 24H2 ISO from MS (as of 11/20/2024). 

I tried using the util to _Undo Tweak_ for the _Set Classic Right-Click Menu_ but it did not work.

## Expected behavior
To have the new windows 11 context menu when I right click on items in File Explorer and Desktop.

## Screenshots
![image](https://github.com/user-attachments/assets/10f1e782-8595-4d03-bb22-96b2d7c9ef6c)

## Additional context
I did not enable this through any other methods. This is just using MicroWin and the util.
I am in a domain environment and using UAC. The admin account is not the account I am working out of. I am the admin user.

**Comment by CodingWonders** [comment]
@wwc-trevor, I can't replicate this issue. Here's what happens after undoing the old context menu tweak:

![vmware_8aYDbw5njn](https://github.com/user-attachments/assets/2f8e6a16-0d6c-413e-bd96-8541166d4238)

**Comment by wwc-trevor** [comment]
I just ran the undo tweak option for the Classic Menu again and still have the classic. I even restarted my computer to make sure it was taking.


**Note: I did not use the Utility to enable the classic menu. I did nothing to enable it. It was on by default after installing the system from the resulting ISO.**

**Comment by wwc-trevor** [comment]
I spent some time looking into this. It appears the UNDO TWEAK option did not work. I checked the registry and found the setting was still set:

<details>
<summary>Registry</summary>
<img src="https://github.com/user-attachments/assets/35ef0edd-80a0-4787-b0d8-573b0fa08d7d">
</details>

I manually deleted the entry as specified [in the documentation](https://christitustech.github.io/winutil/dev/tweaks/z--Advanced-Tweaks---CAUTION/RightClickMenu/) and it now works how I want.
