### ISSUE TITLE
Unable to pin items to start menu - context menu entry missing

### ISSUE THREAD

**Issue by wwc-trevor** [ChrisTitusTech/winutil#3056]
## Describe the bug
When I am trying to pin programs to my start menu, the option to do so is missing from all context menus.

## To Reproduce
1. Run MicroWin on the latest 24H2 ISO from Microsoft (as of 11/20/24).
2. Select Windows 11 Pro (default selection).
3. Choose no other options.
4. Install resulting ISO.
5. Try to Pin items to Start Menu.
6. Option is missing.

## Expected behavior
For me to have an option to Pin programs to Start Menu that is the default option for Windows 11.

## Screenshots
![image](https://github.com/user-attachments/assets/207d54af-ab99-4a34-a2bb-51964b281fb4)
![image](https://github.com/user-attachments/assets/fecd91db-e259-48f0-9f91-e1166419adc9)
![image](https://github.com/user-attachments/assets/fbd478df-070b-4b53-b24d-b1eec2a52e2f)

## Additional context
This was done by MicroWin. The util does not have options to disable this.
I am in a domain environment. We do not have any GPOs affecting this. I am working under a non-admin user and have admin rights using UAC.

**Comment by CodingWonders** [comment]
@wwc-trevor, I can't replicate this:


https://github.com/user-attachments/assets/65f7e667-dc1f-4395-b8ff-9e0c64bf1164

**Comment by wwc-trevor** [comment]
I am not sure how this happened either. I am just trying to avoid another reformat. Is that my next option or is there anything else to check?

<details>
<summary>Video Example</summary>
https://github.com/user-attachments/assets/eb043789-0711-4b22-a378-1486f51bb577
</details>

**Comment by CodingWonders** [comment]
@wwc-trevor, could you follow [this guide](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-pin-to-start-menu-disappeared-from/723a476e-6dca-4465-8868-ed8002488411)? It could be because of how you configured your GPOs

**Comment by wwc-trevor** [comment]
The GPO section did not work. Even after a reboot. Going all the way to page 3 of the linked article it talked about a registry key. That appears to have worked. I am not sure how it was set. 

I will put instructions below for anyone looking for the potential solution in the future if they run into this.

_Note_: All commands must be run as Admin.

1. See if the registry property for LockedStartLayout is set to 1.
<details>
<summary>PowerShell Query</summary>

`Get-Item -Path "registry::HKey_Local_Machine\SOFTWARE\Policies\Microsoft\Windows\Explorer\"`

![image](https://github.com/user-attachments/assets/e5fc38b6-dbca-4507-a8d6-e77d52fb2b17)

</details>

2. Set the property to 0
<details>
<summary>PowerShell Change Registry</summary>

`Set-ItemProperty -Path "registry::HKey_Local_Machine\SOFTWARE\Policies\Microsoft\Windows\Explorer\" -name LockedStartLayout -Value 0`

`Get-ItemProperty -Path "registry::HKey_Local_Machine\SOFTWARE\Policies\Microsoft\Windows\Explorer\"`

![image](https://github.com/user-attachments/assets/d07e0513-2e26-4a5d-ae72-33a41752c493)

</details>

Now you can pin items to the Start Menu.

<details>
<summary>Pin to Start Menu Restored</summary>

![image](https://github.com/user-attachments/assets/db02b5e2-095e-4235-84c7-7f8cb7ec306c)

</details>

**Comment by wwc-trevor** [comment]
Since we solved this specific issue, I will now close this bug. Thank you @CodingWonders for your assistance.
