### ISSUE TITLE
Weird Explorer Scaling after Tweaks

### ISSUE THREAD

**Issue by Thorodrim** [ChrisTitusTech/winutil#3057]
## Describe the bug
After running Tweaks, Updates and Software Installation from WinUtil something broke the scaling of my Explorer.
I can't seem to find any option to undo this.

## To Reproduce
1. Fresh Install of Win 11 Pro 24H2
2. started WinUtil with Admin Terminal
3. Tweaks -> Standard + Disable Copilot, Remove MS Store Apps, Remove OneDrive
4. O+O Shutup recommended settings
5. Updates -> Security Settings
6. Installation of Software 
7. Restart (was good till restart

## Expected behavior
not to do weird scaling

## Screenshots

![Screenshot 2024-11-21 194223](https://github.com/user-attachments/assets/cf93fd1d-d190-460e-b8cf-31b4e228b1da)

**Comment by blusewill** [comment]
Hello! This issues might be the program you installed. Or depends on the monitor you are using and Windows decided to scaled up through Monitor Settings?

**Comment by Thorodrim** [comment]
Ok, after checking again my text size in Settings -> Ease of Access, it was on the default minimum setting, but increasing and then decreasing again fixed it for some reason..
