### ISSUE TITLE
MicroWin not downloading MS Windows ISO

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#3058]
## Describe the bug
Microwin can not download IOS

## To Reproduce
1. load irm "https://christitus.com/windev" | iex
2. Microwin tad
3. Mark tab "Get newest ISO automatically"
4. then use tab "Get Windows ISO
5. get 

## Screenshots

![ScreenShot_
![ScreenShot_20241121111810](https://github.com/user-attachments/assets/545a2fef-8c3d-4970-8179-bdee7841bbb2)
20241121111003](https://github.com/user-attachments/assets/8cd72779-8f69-4827-bf68-2d2727118287)

## Additional context
went to MS web site and tried to download ISO get the same reply

**Comment by FatBastard0** [comment]
tried changing IP address with cmd renew IP did not work
 
![ScreenShot_20241121111810](https://github.com/user-attachments/assets/71f9ab69-4330-4cb2-8c4f-3ae47f9ac735)

**Comment by CodingWonders** [comment]
https://github.com/pbatard/rufus/wiki/FAQ#user-content-Code_715123130_unable_to_complete_your_request_at_this_time_when_trying_to_download_a_Windows_ISO

Refer to this issue for more information

**Comment by FatBastard0** [comment]
I don't understand the referral. I was not using Rufus. I only use Rufus after it makes the ISO and with Rufus. All I do is just use the basic feature of copying the iso over to a USB

**Comment by CodingWonders** [comment]
This, like Rufus, uses Fido for the ISO download capabilities.

What you're experiencing here is the error returned by Fido.

**Comment by FatBastard0** [comment]
I'm a newbie and a complete plebe and I know that this is not the right area but could you tell me how to fix it please?
