### ISSUE TITLE
OneDrive Removal Not Working - It Says: 'Onedrive doesn't seem to be installed anymore'.

### ISSUE THREAD

**Issue by RealTorbinatoR** [ChrisTitusTech/winutil#3063]
Hi everyone (I hope Chris himself responds here),

I'm making this thread today because WinUtil OneDrive Uninstallation Tweak doesn't work.

When I select the 'Remove OneDrive' Tweak and then select 'Run Tweaks', it says this, even though it is still installed (in the powershell logs):

```
====Chris Titus Tech=====
=====Windows Toolbox=====
Running Script for WPFTweaksRemoveOnedrive
Removing OneDrive
Onedrive dosn't seem to be installed anymore
=================================
--     Tweaks are Finished    ---
=================================
```

I have looked at this thread and the solution hasn't worked for me.
https://github.com/ChrisTitusTech/winutil/issues/1154

I'd appreciate some assistance regarding my problem.

Thanks.

Kind regards,
RealTorbinatoR.

Update:
I figured out that it works when I first install windows 11, but afterwards I install Microsoft Office 365, which comes included with OneDrive, and I need PowerPoint, Word, etc. But I don't want OneDrive, so I run the script again, and then it doesn't work and comes up with that Error above (with the screenshot attached to the message above).

Someone please help me ASAP, I need this computer for school, I don't have any other computer.

![CTT Tool OneDrive Not Uninstalling Error Screenshot](https://github.com/user-attachments/assets/67008e74-9c17-49d6-bf6d-d1acf22bb1d3)

**Comment by ChrisTitusTech** [comment]
Fixed in commit: d49b21f88105b867530a8232e7cab312170f0cf7
