### ISSUE TITLE
Missing items in runspace.ps1

### ISSUE THREAD

**Issue by DeveloperDurp** [ChrisTitusTech/winutil#307]
The following items have been found to not be migrated over to the runspace.ps1 script

let me know if any others are found

Thank you,

-----
Will be merged in with #308 
- [x] Setup Autologin
- [x] Reset Windows Update
- [x] Set Dark mode
- [x] System Corruption Scan

**Comment by padsalatushal** [comment]
system corruption scan

**Comment by DeveloperDurp** [comment]
@padsalatushal feel free to take a look at the PR, the existing config files wouldn't work in these cases.
