### ISSUE TITLE
Windows security keeps deleting my desktop winutil shortcut

### ISSUE THREAD

**Issue by reldnasa** [ChrisTitusTech/winutil#3070]

**Comment by cavacuz** [comment]
Sophos End Point do it too

**Comment by zmileski** [comment]
Add winutil to exclusion

**Comment by MyDrift-user** [comment]
This feature was removed from winutil due to antiviruses flagging it.
Due to that reason, I'm gonna close this out :)

/close

**Comment by NotYourAverageGamer** [comment]
I have created a discussion with a step-by-step tutorial on adding the Winutil shortcut manually, in a way that replicates the previous _(now removed)_ shortcut. See: https://github.com/ChrisTitusTech/winutil/discussions/3127
