### ISSUE TITLE
winutil shortcut add option missing

### ISSUE THREAD

**Issue by icarus747** [ChrisTitusTech/winutil#3074]
## Describe the bug
The new GUI does not have the option to add a shortcut to the desktop like before.  

## To Reproduce
Run new GUI, click on tweaks. Shortcut option missing under performance plan.  

## Expected behavior
Be able to add winutil shortcut to desktop

## Screenshots
![nTibmzv 1](https://github.com/user-attachments/assets/6ffa0d5d-0504-454e-a68c-449cb0939fe8)

**Comment by zmileski** [comment]
Removed due to it being falsely flagged but antiviruses
https://github.com/ChrisTitusTech/winutil/issues/2965#issuecomment-2445367972

**Comment by icarus747** [comment]
Thank you for the reply. Thanfully it the target was still there from a microwin iso.  

For those that wish to recreate the shortcut here is the target:
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -Command "Start-Process powershell.exe -verb runas -ArgumentList '-Command "irm https://github.com/ChrisTitusTech/winutil/releases/latest/download/winutil.ps1 | iex"'`

The Icon, if still there, is located under: `%USERPROFILE%\AppData\Local\winutil\cttlogo.ico`

**Comment by MyDrift-user** [comment]
closing this out due to it being intentionally removed.

/close

**Comment by NotYourAverageGamer** [comment]
I have created a discussion with a step-by-step tutorial on adding the Winutil shortcut manually, in a way that replicates the previous _(now removed)_ shortcut. See https://github.com/ChrisTitusTech/winutil/discussions/3127
