### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by Kilgorio2** [ChrisTitusTech/winutil#3078]
![image](https://github.com/user-attachments/assets/57a5288b-9e4f-4103-9e2e-654b775768ca)
it says I need credentials but no matter what I do it fails
what I do:
1. Click on install
2. The credentials thing pops up
3. error

**Comment by Kilgorio2** [comment]
to quote a great meme video
"Wha whu... What am I supposed to do? AAAGGHH"

**Comment by SHR1SHAK** [comment]
Select No
