### ISSUE TITLE
New Bypass Windows 11 24H2

### ISSUE THREAD

**Issue by MathieuT1508** [ChrisTitusTech/winutil#3082]
Script batch version:

set "App=HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags"
set "Config=SQ_SSE2ProcessorSupport=TRUE,SQ_SSE4_2ProcessorSupport=TRUE,SQ_NXProcessorSupport=TRUE,SQ_CompareExchange128=TRUE,SQ_LahfSahfSupport=TRUE,SQ_PrefetchWSupport=TRUE,SQ_PopCntInstructionSupport=TRUE,SQ_SecureBootCapable=TRUE,SQ_SecureBootEnabled=TRUE,SQ_TpmVersion=2,SQ_RamMB=9999,SQ_SystemDiskSizeMB=99999,SQ_CpuCoreCount=9,SQ_CpuModel=99,SQ_CpuFamily=99,SQ_CpuMhz=9999,"

reg delete "%App%\CompatMarkers" /f
reg delete "%App%\Shared" /f
reg delete "%App%\TargetVersionUpgradeExperienceIndicators" /f
reg add "%App%\HwReqChk" /v HwReqChkVars /t REG_MULTI_SZ /s , /d "%Config%" /f

**Comment by CodingWonders** [comment]
I don't know why you want to bypass Setup requirements by assuming every CPU feature is supported, even POPCNT, which is enforced by 24H2.

This version will not boot on systems with CPUs that don't have SSE4.2, which introduces POPCNT.

Because of this, this issue will be closed. /close
