### ISSUE TITLE
Microwin with the c: volume inside a virtual hard disk.

### ISSUE THREAD

**Issue by pearcep6517** [ChrisTitusTech/winutil#3086]
## Describe the bug
It seems that PS Get-Volume has problems with the c: volume inside a vhd. Please see screenshots.
The d: volume is the containing ntfs partition. I'm afraid I cannot offer any solution, I'm a Linux guy.

## Steps to reproduce
Try running microwin with the c: drive in a vhd.

## Expected behavior
Microwin operational with no errors.

## Screenshots
<img width="867" alt="Screenshot 2024-12-04 173149" src="https://github.com/user-attachments/assets/256e2abd-5d7b-478a-805a-dc5698158529">
<img width="440" alt="Screenshot 2024-12-04 172432" src="https://github.com/user-attachments/assets/84762654-ba7b-4716-815b-2cab4562124b">

## Issue validation
- [ x] I checked for duplicate issues.
- [ x] I checked for already existing discussions.
- [ x] I checked for an already existing pull request addressing the issue.

**Comment by CodingWonders** [comment]
Can you run `Get-Volume` on PowerShell?

**Comment by pearcep6517** [comment]
No...
<img width="830" alt="Screenshot 2024-12-05 082442" src="https://github.com/user-attachments/assets/c884b3ca-375d-4996-bb3c-80ce6ac2b0bd">

**Comment by CodingWonders** [comment]
@pearcep6517, a simple `Get-Volume`, without any additional parameters

**Comment by pearcep6517** [comment]
<img width="683" alt="Screenshot 2024-12-05 103532" src="https://github.com/user-attachments/assets/8f60412d-4039-4405-80e1-8656455f3cdd">

**Comment by pearcep6517** [comment]
Just installed 24H2 in a vhd and get-volume outputs something useful. The above is 22H2.

Thanks a lot.
