### ISSUE TITLE
Add tweak to bypass the 260 character file path limit

### ISSUE THREAD

**Issue by stamminator** [ChrisTitusTech/winutil#3095]
## Is your feature request related to a problem? Please describe
On new development machines, it usually isn't long before I run into an issue related to the 260 character file path length limit. It would be nice if CTT exposed the Windows setting to increase the limit.

## Describe the solution you'd like
Provide an option in the Tweaks section to enable the policy located at Computer Configuration > Administrative Templates > System > Filesystem > Enable Win32 long paths

## Issue validation
- [x] I checked for duplicate issues.
- [x] I checked for already existing discussions.
- [x] I checked for an already existing pull request addressing the issue.

**Comment by ChrisTitusTech** [comment]
` {
        "Path": "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\FileSystem",
        "OriginalValue": "0",
        "Name": "LongPathsEnabled",
        "Value": "1",
        "Type": "DWord"
      },`

This is in the base telemetry tweaks. No need to do a policy I enable it through registry.
