### ISSUE TITLE
Shortcut creation is gone on 24.11.25 (windows 10)

### ISSUE THREAD

**Issue by MatthewFerrell** [ChrisTitusTech/winutil#3100]
## Describe the bug
The option to add a Winutil shortcut isn't seen in the tweaks menu.
There seems to be no mention of this in the releases and the docs show that it is in the tweaks section
## Steps to reproduce
1. Go to 'Winutil'
2. Click on 'tweaks'
3. Scroll down to bottom
4. See that there is no option to create shortcut

## Expected behavior
There should be an option there to create a shortcut as the docs show

## Screenshots
![image](https://github.com/user-attachments/assets/0990280e-aead-4890-ba86-7db90e7bd2a6)

## Issue validation
- [y ] I checked for duplicate issues.
- [y ] I checked for already existing discussions.
- [y ] I checked for an already existing pull request addressing the issue.

**Comment by CodingWonders** [comment]
Antivirus solutions were incorrectly flagging the shortcut. To avoid issues related to an antivirus flagging it, it was removed from both WinUtil and MicroWin.

/close

**Comment by NotYourAverageGamer** [comment]
I have created a discussion with a step-by-step tutorial on adding the Winutil shortcut manually, in a way that replicates the previous _(now removed)_ shortcut https://github.com/ChrisTitusTech/winutil/discussions/3127
