### ISSUE TITLE
Feature Request: RustDesk

### ISSUE THREAD

**Issue by HunterShanks** [ChrisTitusTech/winutil#311]
**Is your feature request related to a problem? Please describe.**
At the moment the WinUtil has AnyDesk and TeamViewer available as remote desktop viewer utilities however both are closed source and heavy applications. 

**Describe the solution you'd like**
I'd like to suggest adding an option to install [RustDesk](https://rustdesk.com/). It's a FOSS alternative to the above applications with the same features and in my experience, performs better than the competition [I've used both AnyDesk and TeamViewer in the past]. It's written in Rust and supports the 3 major OS's [Linux, Mac, Windows] as well as the 2 major mobile OS's [Android and iOS]. 

**Additional context**
If you'd like a direct link to their GitHub, here is the [link](https://github.com/rustdesk/rustdesk) and here is the the overarching [architecture](https://github.com/rustdesk/rustdesk/wiki/How-does-RustDesk-work%3F) for anyone interested.

**Comment by Nishant561994** [comment]
Please add DocFetcher along side Everything Search.

**Comment by ChrisTitusTech** [comment]
Rust desk is already there. 
![pwsh_nnu2hqcgWL](https://user-images.githubusercontent.com/7896101/197375264-d7621aad-200b-4b01-ba59-15bd50db2c83.png)
