### ISSUE TITLE
Reset Windows Update not work

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#3110]
When I hit the tab  of Reset Wondow Update tab nothing happened

I launch Winutil "irm "https://christitus.com/windev" | iex
I go to Config tab
then I click the tab "Reset Windows Update" nothing happens

It works on irm "https://christitus.com/win" | iex

**Comment by hyprrt** [comment]
So, you run a dev build of winutil, then expect it to work, and when you run the stable build it works fine.

What's the issue here?
