### ISSUE TITLE
Running Tweaks removes the thumbnail of "People" app 

### ISSUE THREAD

**Issue by sai-vineeth-pasunuru** [ChrisTitusTech/winutil#312]
The powershell script shows `Hiding People icon...` but the app still shows in the start menu (without an icon). I would prefer to retain the thumbnail or not have the app as a whole, as the current blank look is unsettling.
![Screenshot (382)](https://user-images.githubusercontent.com/90463585/197261989-491464ab-700e-4e9b-9871-166ce8b81014.png)

**Comment by ChrisTitusTech** [comment]
Good point, will change this tweak. In the past it hid the entire program, but Microsoft changing things again...
