### ISSUE TITLE
Profile not working fight

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#3137]
I thing this says it all

![ScreenShot_20241229133337](https://github.com/user-attachments/assets/34057dab-c5b1-490f-9c26-edf4bbface9f)

**Comment by MyDrift-user** [comment]
Can you please test if zoxide is installed on your system?

**Comment by FatBastard0** [comment]
I just used UniGetU and installed this
![ScreenShot_20241229134617](https://github.com/user-attachments/assets/8b3012e0-d882-49df-9e73-160841b5bd8a)
and reinstall it.

**Comment by FatBastard0** [comment]
It is working now
