### ISSUE TITLE
Lates update 22H2

### ISSUE THREAD

**Issue by klisza1993** [ChrisTitusTech/winutil#314]
**Describe the bug**

"Remove Edge" - doesnt work anymore ;)
"
Cannot index into a null array.
At line:1 char:4
+ & {iex((gp 'Registry::HKEY_Users\S-1-5-21*\Volatile*' Edge_Removal -e ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
"

**To Reproduce**

**Comment by ChrisTitusTech** [comment]
Oh Microsoft Shenanigans...

We will fix it... once a again.

**Comment by Akczht** [comment]
the issue I get is that when I uninstalled edge via winutil , and went to the Add Or Remove Program settings page in windows settings , and searched for edge , it still showed 3 edge packages which were empty , like edge update , webview2 update . any way to remove them ?
