### ISSUE TITLE
Winget problem

### ISSUE THREAD

**Issue by Throgm** [ChrisTitusTech/winutil#319]
I launched iwr -useb https://christitus.com/win | iex
The utility opened to the install software page
I selected Notepad++ and clicked Start Install
I saw it check for winget and it said winget is already installed
then it continued to "install Notepad++" and reported Installed Programs Notepad++.Notepad++
I clicked OK. The script seems frozen just after ---  Installs are Finished  ---
Notepad++ is not installed on my computer
Nor can powershell or DOS recognize winget as anything usable
The script is seemingly still running with just a blinking cursor for the last 15 minutes or so.
![Screenshot 2022-10-23 000317](https://user-images.githubusercontent.com/11205796/197378838-d8a86536-915e-4d27-b1ab-570546f3b0ca.png)

**Comment by DeveloperDurp** [comment]
@ChrisTitusTech I feel like Winget has a lot of weird quirks, should we migrate over to Chocolatey?

**Comment by dennyamarojr** [comment]
Try to update Microsoft Desktop App Installer to the latest version in Microsoft Store. After update to the latest version, run powershell as admin and type winget and them accept the terms, and try again

**Comment by ChrisTitusTech** [comment]
I'm just going to switch from the microsoft store and push to using nuget with all the fixings. This will prevent winget from not working.

**Comment by Hahubel1** [comment]
The nuget version will install in the windows 10 sandbox too. After installing VCLibs 14 and Microsoft.UI.Xaml.2.7.  
In a fresh sandbox Add-AppxProvisionedPackage doesn't work though but Add-AppxPackage is fine.

**Comment by Nico038** [comment]
Hi, 

I had the same issue.
To solve it, I've added the missing environnement variable : %userprofile%\AppData\Local\Microsoft\WindowsApps

You could try that.
Regards

**Comment by ChrisTitusTech** [comment]
> @ChrisTitusTech I feel like Winget has a lot of weird quirks, should we migrate over to Chocolatey?

Yes, I think between choco and scoop it should cover most things. winget is becoming more and more problematic.

**Comment by GokhanTurk** [comment]
I found a powershell script for silent winget installation can you check it @ChrisTitusTech 

https://gist.github.com/jedieaston/0e64dd0ea27ba34d72e38538fee46c20

**Comment by ChrisTitusTech** [comment]
I'm going to streamline this and remove the ms-appinstaller portion and directly install the appx without ms store needing to be present.

**Comment by ChrisTitusTech** [comment]
implemented in commit b229e08e37d25f12265fc584c52132c981227e05

**Comment by Throgm** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
