### ISSUE TITLE
MS Edge

### ISSUE THREAD

**Issue by Bhooty** [ChrisTitusTech/winutil#322]
This setting in edge should be set to basic instead of editor as this sends data to microsoft
![image](https://user-images.githubusercontent.com/46019727/197402278-d67c1d60-c25f-4952-806a-edf9765409dc.png)

Also can you please remove this policy
![image](https://user-images.githubusercontent.com/46019727/197402317-81cb91d5-25ed-4b21-b76b-2196c80777cd.png)
having suggestions when typing in search is a must I think

**Comment by sl4x0** [comment]
How can i restore edge if i removed it?

**Comment by Bhooty** [comment]
> How can i restore edge if i removed it?

its comes back after updates so useless to remove XD

**Comment by padsalatushal** [comment]
@Bhooty i am working on it

**Comment by Bhooty** [comment]
> @Bhooty i am working on it

Closed the issue since in the latest video christitus said he’s not gonna allow the changes jn edge cause most of it is tracking
