### ISSUE TITLE
features from old win10script

### ISSUE THREAD

**Issue by conkerts** [ChrisTitusTech/winutil#324]
**Is your feature request related to a problem? Please describe.**
Not sure where to put it, but I went through this video https://youtu.be/Tfd7BXCo9Xk?t=266
which is about the old script I guess
https://github.com/ChrisTitusTech/win10script/tree/master

I think I went through everything, but I just haven't found them, so I think some of the features from that old script are missing.

**Describe the solution you'd like**

- disabling the meltdown flag
- f8 boot menu enable

- a separate section, with a general way/list  to quickly select what to debloat, like remove candy crush, netflix, etc ...

- missing chocolatey in the install programs section ...

**Describe alternatives you've considered**
I guess i could use the outdated script, but I don't think it's a good idea, as it's not maintained anymore

**Additional context**
-

**Comment by ChrisTitusTech** [comment]
Thanks for pointing these out, I'll get them added in for the next update!
