### ISSUE TITLE
"Upgrade Installs" doesn't update MSYS2

### ISSUE THREAD

**Issue by Merio64** [ChrisTitusTech/winutil#331]
As the title says, everytime i click to update every program in my PC, it doesn't update MSYS2.
![Screenshot_1](https://user-images.githubusercontent.com/70110044/197598382-06bf01c2-0f6d-4482-a355-a702875c1f45.png)

**Comment by Hahubel1** [comment]
That's normal, winget can install MSYS2 but doesn't update it (for reasons). You have to do that with pacman in a MSYS2 environment.

![image](https://user-images.githubusercontent.com/116456572/197759761-2ec599f7-31bd-4dc7-aa03-c5d455cd9a92.png)

![image](https://user-images.githubusercontent.com/116456572/197759963-da93e8c0-2355-44cc-abce-2b966f8354f8.png)

The windows registry is unchanged though.
![image](https://user-images.githubusercontent.com/116456572/197762874-a08d66b1-adfa-4144-986d-690d33f7b30e.png)
And winget keeps reading that version
![image](https://user-images.githubusercontent.com/116456572/197763714-2341b2d4-df20-4d01-8c4e-d3b75f9d32a6.png)

**Comment by Merio64** [comment]
> That's normal, winget can install MSYS2 but doesn't update it (for reasons). You have to do that with pacman in a MSYS2 environment.
> 
> ![image](https://user-images.githubusercontent.com/116456572/197759761-2ec599f7-31bd-4dc7-aa03-c5d455cd9a92.png)
> 
> ![image](https://user-images.githubusercontent.com/116456572/197759963-da93e8c0-2355-44cc-abce-2b966f8354f8.png)
> 
> The windows registry is unchanged though. ![image](https://user-images.githubusercontent.com/116456572/197762874-a08d66b1-adfa-4144-986d-690d33f7b30e.png) And winget keeps reading that version ![image](https://user-images.githubusercontent.com/116456572/197763714-2341b2d4-df20-4d01-8c4e-d3b75f9d32a6.png)

Thanks man, i try to remember that from now on.
