### ISSUE TITLE
RetroArch update wipes out my configs

### ISSUE THREAD

**Issue by slackerdc** [ChrisTitusTech/winutil#333]
**Describe the bug**
When running the Winutil script it will do an update to RetroArch. Unfortunately it looks like it runs the installer on silent mode with the defaults which will set all the configs to the defaults. This is no good if you run Retroarch with any level of customization which most users do.

**To Reproduce**
1. Install an older version of RetroArch
2. Do a few customizations
3. Run the Winutil script and run the update installed programs
4. Come back to all defaults in RetroArch

**Expected behavior**
Ideally no update to RetroArch. I don't mind manually updating this one from time to time to avoid this kind of issue.

**Comment by Carterpersall** [comment]
There isn't much we can do to prevent this from occurring due to this being a bug with RetroArch's installer. I would recommend submitting a bug report to RetroArch's devs, so they can fix it.
