### ISSUE TITLE
Tweak Request - Task manager in Taskbar (Windows11)

### ISSUE THREAD

**Issue by charettepa** [ChrisTitusTech/winutil#335]
**Is your feature request related to a problem? Please describe.**
Windows 11 Taskbar does not have Task Manager in the context menu like in Windows 10

**Describe the solution you'd like**
Have the Task Manager in the Taskbar like in Windows 10

**Describe alternatives you've considered**
The addition to the registry returnsthis functionality

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\4\1887869580]
"EnabledState"=dword:00000002
"EnabledStateOptions"=dword:00000000

**Additional context**
Would be nice to have this as an available tweak in the CTT tool

**Comment by C0Nd3Mnd** [comment]
Not exactly what you want but FYI there's a Task Manager entry when you right click the Windows/Start button.

**Comment by charettepa** [comment]
I know about Tasman on the start menu
I prefer it in the task bar

its a simple addition to the registry
I am using it
I just figured others would like it and it would be simle to add to the tool

**Comment by ChrisTitusTech** [comment]
Microsoft added this back in with 22H2. Closing issue.
