### ISSUE TITLE
When creating a system restore point it either gets stuck on 99% or 50%

### ISSUE THREAD

**Issue by 006-uuuu** [ChrisTitusTech/winutil#336]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yianni54** [comment]
Im having same issue did you ever resolve?

**Comment by 006-uuuu** [comment]
i think i did but this was a long time ago. but ill tell you this, its not an issue with the tool its an issue with windows. try to make a restore point using system restore and it should spit out an error. look that up on the internet and that should be your fix for it

**Comment by yianni54** [comment]
So thanks for getting back to me. The tool was working fine for a while then all of a sudden this started happening. If I go to system restore through windows to create a point it makes it no problem. That’s the wierd part. On Nov 5, 2023, at 1:28 AM, 006 ***@***.***> wrote:﻿
i think i did but this was a long time ago. but ill tell you this, its not an issue with the tool its an issue with windows. try to make a restore point using system restore and it should spit out an error. look that up on the internet and that should be your fix for it

**Comment by 006-uuuu** [comment]
then you should be ok to use the program as long as you make a restore point manually and uncheck the restore point option in the program.
