### ISSUE TITLE
Install Error (PowerShell)

### ISSUE THREAD

**Issue by Kxlme** [ChrisTitusTech/winutil#339]
**Describe the bug**
When I put the command to install the program, Windows PS gives me an error.

**To Reproduce**
1. Go to Windows PowerShell
2. Paste iwr -useb https://christitus.com/win | iex
3. Execute the command

**Expected behavior**
No install error

**Screenshots**
![Install Error](https://user-images.githubusercontent.com/116840372/198408603-9102ab2e-7a3f-4dde-be31-355d881608ba.png)

**Additional context**
I executed PS as administrator and It still doesnt work.

**Comment by Kxlme** [comment]
Help?

**Comment by DeveloperDurp** [comment]
try using this for the URL

https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1

**Comment by benjaminbenito** [comment]
You can see your solution in read.me line 22.

If you are having TLS 1.2 Issues or You cannot find or resolve `christitus.com/win` then run with the following command:
```
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')
```

**Comment by Kxlme** [comment]
Thank you so much for the help! It finally worked :D
