### ISSUE TITLE
Can't reinstall Microsoft Edge - Solution Here

### ISSUE THREAD

**Issue by tradengport** [ChrisTitusTech/winutil#340]
I uninstalled Edge by mistake (wanted to check Cortana but checked Edge instead), and now I can't seem to get it back.
Otherwise, I only applied the recommended tweaks.

**To Reproduce**
1. Apply recommended tweaks
2. Click on uninstall Edge and apply successfully
3. Try to reinstall Edge through Microsoft Store
4. Try to reinstall Edge through downloading the installer on the website
5. Try to repair Edge through Settings - Programs
6. The shortcut appears but does nothing.

Thank you for your great work, Chris!

**Comment by Akczht** [comment]
same issue, any solution you found yet ?

**Comment by laric** [comment]
Same problem so watching for solution.

**Comment by Akczht** [comment]
idk broken for me too

**Comment by AminGholizad** [comment]
same here

**Comment by dromsak** [comment]
Having the same issue. Unfortunately need edge to log into stupid quest app...

**Comment by sl4x0** [comment]
@SudoWolfy , You Saved My life! <3
I promise will not be in chris channel again!

**Comment by TameemS** [comment]
I found a permanent solution

The Edge_Removal script adds a registry key that specifically blocks `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`

Open regedit and delete `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe\0`

**Comment by Akczht** [comment]
@TameemS Thanks! so much, I was thinking about doing a reinstall, this saved me a lot of time.

**Comment by lucassbod** [comment]
@TameemS It worked great. Thank you so much for the advice.

**Comment by RafeeDaBoy** [comment]
What kinda rubbed me the wrong way is the only modification done to the .bat file from [the original one](https://github.com/AveYo/fox/blob/main/Edge_Removal.bat) is the removal of credits. 
![image](https://user-images.githubusercontent.com/69535896/226168063-361b0ea4-1273-447a-8e9d-a45f306cf523.png)

**Comment by crian** [comment]
I pushed a pr to the testing branch with the newest version of the edgeremoval script by AveYo which now supports reinstall of edge and webview.

**Comment by jok3rsgr1n** [comment]
After restoring edge than going into edge checking for updates errors out any idea on how to fix that ?

**Comment by lucianofullstack** [comment]
Just delete the registry key and download Edge for Business, works for me.

**Comment by 616-com** [comment]
thanks for letting me know the real problem, since i want to use microsoft edge for microsoft rewards

**Comment by nitzcard** [comment]
I got here and it worked, this bug still exist.

**Comment by popy2k14** [comment]
> I found a permanent solution
> 
> The Edge_Removal script adds a registry key that specifically blocks `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`
> 
> Open regedit and delete `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe\0`

Thank you so much.
That issue has driven me crazy!
