### ISSUE TITLE
Win11 App install does not work until manual winget run to accept agreement

### ISSUE THREAD

**Issue by cto-mike** [ChrisTitusTech/winutil#347]
**Describe the bug**
New laptop with Windows 21H2 with App Install starts with pop-up "Update ms-resoruce:appDisplayName?", update results in "Cannot open app package", "This app package is not support for installation by App Installer because it uses certain restricted capabilities" script proceeds with multiple empty powershell pop-ups and reports apps as installed but are not installed.

**To Reproduce**

New laptop with Windows 21H2, ran "irm christitus.com/win | iex" after Laptop tweaks.
Install -> Select app -> Start install
"Update ms-resoruce:appDisplayName?"
-> Update
"Cannot open app package"
->	This app package is not support for installation by App Installer because it uses certain restricted capabilities
Blank powershell Pop-ups result, pop-up with list of installed apps, but not software is installed.

**Workaround**
1. Update Winget from Microsoft Store
2.  In Admin Powershell, run "winget search Chrome", can replace with any software
3.  Prompt for microsoft store agreement: Y
4.  Retry with script, now installs apps, pop-ups report software found and progress shown.

**Comment by KonstaVilkman** [comment]
Thank you! Resolved my problem.

**Comment by ChrisTitusTech** [comment]
https://gist.github.com/jedieaston/0e64dd0ea27ba34d72e38538fee46c20 Is the new script to implement also dupe issues in #319 and #360

**Comment by ChrisTitusTech** [comment]
Done commited with #917
