### ISSUE TITLE
Tool tips appears too fast

### ISSUE THREAD

**Issue by Skizo222** [ChrisTitusTech/winutil#350]
**Describe the bug**
After running the script, tool tips appear instantly when you hover over something, instead of appearing after a few seconds.
I've tried to redo the tweaks from the script itself, but this problem persists.

**To Reproduce**
1. Go to Windows PowerShell
2. Execute iwr -useb https://christitus.com/win | iex
3. Click on Tweaks > Desktop > Run Tweaks

**Expected behavior**
The script should not modify the time at which the tool tips appear.

**Screenshots**
https://www.reddit.com/r/Windows11/comments/y2ymjv/is_this_a_bug_or_does_it_work_like_this_due_to/

**Additional context**
I've tried with a clean virtual machine with W10 and another one with W11, and after executing the script the same problem occurs.

**Comment by ChrisTitusTech** [comment]
Gotcha, here is the default setting. 

I'm commiting this to test branch fdcca808ab261327141eb9540532b4fdd36ff171

`Set-ItemProperty -Path "HKCU:\Control Panel\Mouse" -Name "MouseHoverTime" -Type DWord -Value 400`
