### ISSUE TITLE
BitDefender keeps blocking access.

### ISSUE THREAD

**Issue by DannyDarth** [ChrisTitusTech/winutil#351]
**Describe the bug**
When i go to install an app such as greenshot, not matter if i add an exception for this bitdefender blocks it.

**To Reproduce**
1. use ctt as admin or normal
2. try to install any program
3. gets blocked by bitdefender.

**Expected behavior**

**Screenshots**
Cant get a screenshot it closes to quick to get the error.

**Additional context**

**Comment by ChrisTitusTech** [comment]
You have to disable antivirus. They do not like powershell scripts like this.

**Comment by DannyDarth** [comment]
I know this is an old issue. But i figured out how to allow this "script" to go through bitdefender.

Going to protection -> Antivirus -> advanced -> Scan scripts and disable this.

**Comment by ajmer** [comment]
I ran into this issue and an alternative to a blanket ban on scanning scripts would be to exclude the dbatools folder via Protection > Settings > Add an Exception:

![image](https://user-images.githubusercontent.com/2014204/216835722-1ed8f04b-d3dc-4da7-837b-5e3a387d767c.png)

**Comment by AutumnOnFire** [comment]
Hey, I've been having this issue too and both the solutions to disable script scanning, and bitdefender in its entirety, don't seem to work. I also tried looking for that directory under C:\ and I couldn't find dbatools at all. Seems to be the only solution is to uninstall bitdefender entirely.
