### ISSUE TITLE
Quiet Mode

### ISSUE THREAD

**Issue by AlessandroFasse** [ChrisTitusTech/winutil#352]
Would it be possible to implement a `quiet mode` for the tool? 

So that for example you could define a list of components you want to have/apply using a `.yaml` file or similar and then call the tool with the corresponding arguments like `--quiet --config config.yaml` ? That would be very nice because I would like to use the tool on a couple of servers I don't want to click trough the tool 30 times by hand :)

**Comment by 0nelight** [comment]
This is a duplicate of #130.
