### ISSUE TITLE
Remove all bloatwares Tiktok, Prime Video, Instagram, Messenger, Spotify.

### ISSUE THREAD

**Issue by rifton007** [ChrisTitusTech/winutil#361]
**Describe the solution you'd like**
Remove bloatwares Tiktok, Prime Video, Instagram, Messenger, Spotify ....

**Additional context**
Mcrosoft Windows Version 22H2 (build19045.2130)

![image](https://user-images.githubusercontent.com/2601347/200916825-15f67a5c-7013-4d9c-b4b9-ad82b3501e90.png)

**Comment by jlagden** [comment]
I just spent a few hours try to work out how to remove these but haven't had any luck.

I found some reg keys under `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SuggestedApps`

However setting these to 0 or deleting the keys has no effect.

I hope someone can find what's required to remove these automatically

**Comment by ChrisTitusTech** [comment]
Going to have to manually create a new removal process as just doing a RemoveAppx from powershell doesn't cut it. Closing for now.
