### ISSUE TITLE
Can't disable "Essential Tweaks"

### ISSUE THREAD

**Issue by Zkagit** [ChrisTitusTech/winutil#365]
**Describe the bug**
When trying to disable or enable Essential tweaks only Dark Theme is affected.

Enabling Dark Mode
Enabled
Disabling Dark Mode
Disabled

**Screenshots**
![Tweaker broken](https://user-images.githubusercontent.com/95741317/200575131-00f8a0f2-dfb1-4976-a77c-733ed0ecbed8.png)

**Additional context**
Tried both on W11 and W10, same result

Cheers

**Comment by yookirox** [comment]
duh. obviously it's a button to enable or disable dark theme only, not to check/uncheck all other functionnalities.

**Comment by Zkagit** [comment]
> duh. obviously it's a button to enable or disable dark theme only, not to check/uncheck all other functionnalities.

Today I found out I'm an idiot, thanks lol
