### ISSUE TITLE
Get Started app

### ISSUE THREAD

**Issue by p1-p1** [ChrisTitusTech/winutil#368]
Hi,
Can we delete Get Started in Win 11? And add to the tool?
I never use it and It take some resources in my system.
![Screenshot 2022-11-09 193700](https://user-images.githubusercontent.com/98798504/200994943-14505eb7-cd99-4d67-888a-9e595af57d63.png)

**Comment by ChrisTitusTech** [comment]
Sadly, I've looked a bunch of different ways and its best to just leave it. By forcibly removing it... the windows install gets corrupted.
