### ISSUE TITLE
O&O Shutup10 error

### ISSUE THREAD

**Issue by Simonak222** [ChrisTitusTech/winutil#369]
**Describe the bug**
Running win10 22h2 with latest run of the script I get error from O&O shutup10
saying at least one parameter is wrong during application invocation.

![oos](https://user-images.githubusercontent.com/117887099/201005242-8afba2e0-b500-4425-9dbb-5c847f8a43c3.png)

**Comment by C00kiekiller** [comment]
me have this issue to...

**Comment by ChrisTitusTech** [comment]
This was fixed in #637
