### ISSUE TITLE
Game Bar

### ISSUE THREAD

**Issue by Cameron6897** [ChrisTitusTech/winutil#371]
**Describe the bug**
Running the desktop tweaks disables game bar, not allowing me to press Windows + G to open it. I have used this tool for the tweaks and many fresh windows installs and game bar has always worked after. For some reason now it doesn't. I tried reinstalling windows 10 home, game bar works before running the tweaks. It does not work after running the tweaks. I can open it from the search bar but not Windows + G. I go to enable it in windows settings but everytime I come back, it is disabled. I tried changing registry and group policy values. I tried to use the undo all tweaks button, but that did not work either.

**Comment by thamudi** [comment]
I am facing the same issue, going through the script shows that it will be removed by default if [WEPFssDebloat is enabled](https://github.com/ChrisTitusTech/winutil/blob/main/winutil.ps1#L871)

I am trying to use [this](https://answers.microsoft.com/en-us/insider/forum/all/help-i-lost-my-game-bar/95dadd76-227b-4ed6-aaef-24a78fab6e1d) solutio. Will update if it works.

**Comment by ChrisTitusTech** [comment]
Fixed in #692
