### ISSUE TITLE
Program Additions for next update

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/winutil#374]
- [x] SuperF4 - https://stefansundin.github.io/superf4/
- [x] Choco
- [x] Scoop
- [x] Ventoy
- [x] dotnet 7
- [x] dotnet 4.8
- [x] directx
- [x] winget install --id=KDE.Okular -e
- [x] winget install --id=KDE.Kate -e
- [x] winget install --id=KDE.Kdenlive -e
- [x] winget install --id=KDE.KDEConnect -e
- [ ] winget install --id=KDE.digikam -e
- [ ] winget install --id=KDE.Krita -e
- [ ] winget install -e --id Docker.DockerDesktop
- [x] winget install HeroicGamesLauncher.HeroicGamesLauncher
- [ ] yt-dlp.yt-dlp
- [ ] FxSoundLLC.FxSound
- [ ] Automattic.Simplenote
- [ ] winget install Flow-Launcher.Flow-Launcher
- [ ] winget install Kitware.Cmake
- [ ] winget install gerardog.gsudo
- [ ] winget install MuseScore.MuseScore
- [ ] JPEGView 
- [x] MusicBee
- [x] ModernFlyouts 
- [ ] Oracle.VirtualBox
- [x] Safing.Portmaster
- [ ] Giorgiotani.Peazip
- [ ] valinet.ExplorerPatcher
- [ ] CoreyButler.NVMforWindows Node version manager
- [ ] scrcpy

Expanding Tool to include other CLI installers. Winget is being unpredictable in 22H2 and I want to start diversifying the installs, while expanding its capabilities.

**Comment by ChrisTitusTech** [comment]
Request per a comment from - Stefan W:
Lockhunter: https://lockhunter.com/
Rename Bulk Utility: https://www.bulkrenameutility.co.uk/ (PowerToys has a similar, harder-to-use tool)
Philips Hue Sync app: https://www.philips-hue.com/en-sg/explore-hue/propositions/entertainment/hue-sync
Start10/Start11 (but that's a paid program), don't know if you'd want that.
AutoHideMouseCursor: https://www.softwareok.com/?seite=Microsoft/AutoHideMouseCursor
Disable Nvidia Telemetry (don't know if this is what your toolbox already does, but this is a program to disable, but I have also used PowerShell to remove the nvidia one, as it takes up a lot of space.): https://github.com/NateShoffner/Disable-Nvidia-Telemetry
Rainmeter: https://www.rainmeter.net/

Would also be nice to see (personally don't use right now):
Mouse Without Borders (I know Synergy is better, since it's cross OS, but also paid)
VistaSwitcher: https://www.ntwind.com/software/alttabter/old-vistaswitcher.html (as an alternative to alt-tab)

SpaceSniffer: http://www.uderzo.it/main_products/space_sniffer/

**Comment by DeveloperDurp** [comment]
@ChrisTitusTech Sure glad I thought of multiple repos for the applications.json file lol. Should only need to add the additional values to each button and boom. You could probably do a dropdown similar to the DNS tweak and that would make it fairly simple to modify the existing code to get the new commands.

**Comment by Arnab11** [comment]
@ChrisTitusTech My suggestion will be to add the completely onedrive removal script. It will be really helpful

**Comment by d0x360** [comment]
A online gaming perf enhancement suggestion i have is a toggle to disable Nagle's Algorithm.  Ive ffound there to be less sync issue in racing games and the last couple COD's, especially in warzone.  Id say placebo except the teleporting issue with cars in racing titles (fh4/5, AC, ACC, NFS Heat/Payback) was rare when it was disabled as were kills in some FPS games where i died and the killcam didnt match where i really was.

[Disable the Nagle](https://mantenimientobios.com/en/how-to-enable-and-disable-the-nagle-algorithm-in-windows-10/#:~:text=Disable%20the%20Nagle%20algorithm%20in%20Windows%2010%201,registry%20editor%20address%20bar%20and%20hit%20Enter%20- )

**Comment by nerdorican** [comment]
@ChrisTitusTech I would love to see mpv [https://mpv.io/](url) in your toolbox. It is such a versatile and lightweight media player with lua script plugin support.

**Comment by Akrista** [comment]
@ChrisTitusTech I saw that you added simplewall in the toolbox, maybe you could add portmaster too?

https://winget.run/pkg/Safing

**Comment by lightking813** [comment]
Put this under issues but finally found this location so gonna put it in the right place this time....
dotnet runtime 7.0 (since some applications requiring it, for connivence sake)
Ubisoft Connect (for games that are only available there)
intelliJ comunnity edition (for those that find that handy)

all of these are available through Chocolatey

**Comment by FanieVenter** [comment]
add clear dns cache feature

**Comment by Candyxxy** [comment]
add thunderbird and opera please :)

**Comment by Sytec28** [comment]
I would like to see BitviseSSH as well :)

**Comment by RedDot-3ND7355** [comment]
I made a ticket for it (MPO related) Feel free to check it out!

**Comment by matrixik** [comment]
https://github.com/debauchee/barrier - open source fork of Synergy (I'm using it for Win <=> Linux)

**Comment by EndangeredNayla** [comment]
> opera

opera lol. u mean the browser that literally hacks its userbase

**Comment by padsalatushal** [comment]
chatterino

**Comment by Ducco** [comment]
Im missing uplay

**Comment by gt2416** [comment]
It would be nice to have PDFGear. Its the only free PDF software I found that has editing capabilities similar to Adobe Acrobat Pro. They don't even have a paid tier/app. Its completely free. 
https://www.pdfgear.com/

**Comment by d0x360** [comment]
> add clear dns cache feature

I wouldn't mind having an option to clear temp, superfetch, prefetch etc and possibly shader cache files.

I've found that clearing temp directories after a new driver install or game update can improve hitching (I assume shader comp or traversal stutters are what's effected) it doesn't work for everything, especially super broken games like everything from 2023 but it's been beneficial for well made titles that suddenly run poorly.

It wouldn't be bad to merge tiki one steam cleaner (like functions) into the app since tiki one is deprecated and while it works to an extent it doesn't seem to grab everything from every launcher locally installing the same files for every game.  Anything that can free up space used by gaming related things without effecting game performance negatively would be excellent and shouldn't be difficult to implement into a "gaming" section that has on/off toggles along with file cleaners etc.  Just a nice set of quick tweaks that make me feel good 😊 and also help teach users some basic system maintenance just by observation.

Disable Nagle and his algorithm for mp gaming too lol.  Get out of here Nagle!  I definitely get lower latency in online gaming with it disabled and leaving it disabled has never caused me issues anywhere.

I'd also love a way to enable rebar on a game without nvprofileinspector but that one is beyond the scope of the app and probably a bad idea considering if you don't understand what it is and games crash then figuring out why would be difficult.

**Comment by tdcook** [comment]
I'd suggest adding [NanaZip](https://github.com/M2Team/NanaZip). It's a fork of 7-zip with a (slightly) more modern UI, better Win11 integration, some additional format support and more security features. Personally I'd replace 7-zip with Nanazip completely but even just having it as an alternative would be great.

**Comment by Alexciao** [comment]
Hello! I'd suggest adding a few programs. All these are FOSS and I've linked their GitHub repos.

- [M2Team.NanaZip](https://github.com/M2Team/NanaZip), a fork of 7zip that's integrated with the new context menu in W11, - [Playnite.Playnite](https://github.com/JosefNemec/Playnite/), a really cool program designed to be a game launcher for all libraries (for ex. Steam, Ubisoft, Battle.net and more). It supports community made plugins and themes.
- [Unigram](https://github.com/unigramdev/unigram), a Telegram client that follows W11's design guidelines. It's available on WinGet as an MS Store app, and its ID is `9N97ZCKPD60Q`.

**Comment by ChrisTitusTech** [comment]
Add These programs per #227 

```
winget install --id=KDE.Okular -e
winget install --id=KDE.Kate -e
winget install --id=KDE.Kdenlive -e
winget install --id=KDE.KDEConnect -e
winget install --id=KDE.digikam -e
winget install --id=KDE.Krita -e
```

**Comment by abo3skr2019** [comment]
as a java dev i would like to see more version for the jdk maybe 11 and 17
winget install -e --id AdoptOpenJDK.OpenJDK.11 

choco install openjdk11

winget install -e --id EclipseAdoptium.Temurin.17.JDK

choco install temurin17

**Comment by Crusader-Boss** [comment]
Hey chris can u please add these apps to app sections

vs code insiders ( winget id : Microsoft.VisualStudioCode.Insiders )
mem reduct ( winget id : Henry++.MemReduct )
notion ( winget id : notion.notion )
spotify ( winget id: spotify.spotify )

Thank you for the hard work.

**Comment by YusufKhalifa1** [comment]
can you add transmission torrent ?

**Comment by Theoldnation** [comment]
i would suggest to add emulationstation DE as frontend for retro games

**Comment by sinistergrin26** [comment]
kindly add mpv player

**Comment by FanieVenter** [comment]
could you consider adding the extra stuff to install winget on a barebones system using one of your old articles https://christitus.com/setting-up-the-ultimate-windows-11/

**Comment by Appmeurtre** [comment]
I don't want to be that one weirdo who is paranoid about piravcy but I could not found any source about FxSound or creators of them. Their website does not show legal company adress or registery. I have no idea why even this project is closed-source and free at the same time? I don't know, when I saw it will be added to tool, i just got curious.

**Comment by FanieVenter** [comment]
it would be nice to see blender on there

**Comment by aaronkorn** [comment]
Rainmeter allows you to display customizable skins on your desktop, from hardware usage meters to fully functional audio visualizers.
You are only limited by your imagination and creativity.

Rainmeter is [open source software](https://github.com/rainmeter/) distributed free of charge under the terms of the [GNU GPL v2](http://www.gnu.org/licenses/gpl-2.0) license.



winget install -e --id Rainmeter.Rainmeter

**Comment by Caio-Rtnn** [comment]
I don't know if someone else already suggested this, but I'll share it anyway.
I think FFmpeg would be a nice addition to the Install section, I use it all the time (through Stacher [GUI for yt-dlp] and Zotify). Both regular and shared versions are available on winget. Below, I'll provide their IDs:
Gyan.FFmpeg
Gyan.FFmpeg.Shared
It'd also be very convenient if the tool could automatically add the bin folder of FFmpeg to the system's path.

**Comment by Noriaela** [comment]
This has probably already been requested, but just in case:

24-hour time would be a useful addition.

**Comment by fynks** [comment]
@ChrisTitusTech please add [peazip](https://github.com/peazip/PeaZip/) as an alternative to 7-zip and winrar

**Comment by Nyxiad** [comment]
It would be great to see [FanControl](https://github.com/rem0o/fancontrol.releases) in here. It's drastically better than any other PC cooling utility.

**Comment by MrDisguised** [comment]
> @ChrisTitusTech can you add these too? battle net launcher discord canary (discord has a 3 release channels: stable ptb canary) mongodb ida decompiler valorant

Valorant is a rootkit malware. Also it is useless in adding a "game". It is better to add game stores rather than adding a game.



@ChrisTitusTech Please add these applications - 

Shotcut Video editor 
mpv video player 
olive video editor
openshot video editor
mariadb
mysql

**Comment by mrwillbarnz** [comment]
#1063 & #1064 Sent for review to add SuperF4 to be added to the Utilities List.

**Comment by mrwillbarnz** [comment]
#1065 added for .NET Core Desktop Runtime

**Comment by mrwillbarnz** [comment]
#1066 added for both Ventoy (Chocolatey Only package) & .NET Core Runtime 7.0.11

**Comment by joser93** [comment]
Hello, 
There's a program that I use to avoid certain games does not support dual monitor properly, example: Astroneer, Sea of Thieves.

The program is called Dual Monitor Tools, allows to lock the cursor to a specific screen and so much more.

For that I found it on winget 

` winget install --id=GNE.DualMonitorTools  -e `

If more people find it useful, can you add it to the toolkit? thanks :D

**Comment by PilaScat** [comment]
parsec and tailscale would be perfect!

**Comment by OMRI973** [comment]
pls add **total commander**

**Comment by YusufKhalifadev** [comment]
it'd be great to add github-cli too it's in winget

**Comment by mews-se** [comment]
Would love to see winget install HermannSchinagl.LinkShellExtension - a small but easy way to create symlinks (im a bad coder so i dont want to screw anything up by using a PR)

**Comment by exciar** [comment]
WizFile

**Comment by Theoldnation** [comment]
Flow launcher

**Comment by BritishSpuds** [comment]
Tixati is a really neat Torrenting program i use quite often, it would be amazing if you could add it to the programs list :)

**Comment by RedDot-3ND7355** [comment]
Feel free to add these! Full source disclosed in my git project :)
https://github.com/RedDot-3ND7355/MPO-GPU-FIX
https://github.com/ChrisTitusTech/winutil/issues/1552

Very simple toggles tbh :3

**Comment by rollopack** [comment]
Please add [XnView Classic](https://www.xnview.com/en/xnview/)

**Comment by justgivemefile** [comment]
Please add a way to remove the MS Game Bar from windows! I remove the store everytime I run the utility, but I am always left wanting more removal powers! 

I have been using linux for 2 years now (currently on Nobara), but, as you are aware, there are many games that can't be played on Linux. I wish I could ditch windows altogether, and probably will given what they are doing with Windows 11, But I still like my games..

**Comment by botflakes** [comment]
Hey, I think Tabby.sh would be a great addition too!

**Comment by botflakes** [comment]
Hey there,

Would like to see Tabby.sh (https://github.com/eugeny/tabby) added. Tabby is a modern interpretation of PuTTY and integrates some features of WinSCP. I use it for over a year now and its awesome in my opinion

**Comment by ModernTTY** [comment]
I have started making a PR for adding all of these expect the PR soon.

**Comment by og-mrk** [comment]
@jaug1337
Tracking program additions have been moved to #1782 Tracking Issue, will track this request of yours over there.

Also for anyone who's interested in requesting programs to be added to WinUtil, please do so over on #1782 Issue, Thanks in advance 😄

**Comment by og-mrk** [comment]
@jaug1337
I've looked into H2TestW Program, but couldn't download it using the Available link on their website, could it be Region Locked?

for now, _and as far as I know_, H2TestW can't be added to WinUtil, because there's no WinGet Package for it, and I couldn't add it to winget-pkgs repo (_so you we can add it to WinUtil_), because there's no Official Download Link for it.

**Comment by aut0-m8** [comment]
> @ChrisTitusTech I would love to see mpv [https://mpv.io/](url) in your toolbox. It is such a versatile and lightweight open-source media player with lua script plugin support.

![image](https://github.com/ChrisTitusTech/winutil/assets/144866024/989001fa-60a7-4e2a-85aa-d4c7a9a63915)
https://community.chocolatey.org/packages/mpv

why is mpv still not added?
