### ISSUE TITLE
Fix Edge being managed by organization

### ISSUE THREAD

**Issue by xRyul** [ChrisTitusTech/winutil#377]
No restore point created and unable to revert all tweaks.

Please add massive warning to manually create restore point.

**Comment by sl4x0** [comment]
Same here! My edge browser says it maneged by some bla bla organisation
How can i restore it??

**Comment by ChrisTitusTech** [comment]
--How to Remove Managed by your organization from Microsoft Edge--
1. Launch the Windows Registry Editor. Press Win + R on the keyboard and type regedit in the Run box.
2. Go to the following key: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft.
3. Locate the Edge folder and right-click it.
4. Select Delete from the menu.
5. Alternatively, you can delete all the parameters inside this folder.
6. Now, open the following key: HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Edge
7. Delete its contents as well.
8. Restart the browser. The message should be gone now.

> Same here! My edge browser says it maneged by some bla bla organisation How can i restore it??

**Comment by ChrisTitusTech** [comment]
Fixed in commit 1da72a2

**Comment by ntdlll** [comment]
how to do the same for firefox/brave? cant use socks5 proxy and cannot enable secure DNS for brave
