### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by 80-svg** [ChrisTitusTech/winutil#379]
Describe the bug
I set the DNS to cloudflare and the log had this error
Setting DNS to Cloud Flare for all connections...
InvalidOperation:
Line |
 474 |              $Interface.SetDNSServerSearchOrder($dns)  | Out-Null
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [Deserialized.System.Management.ManagementObject#root\cimv2\Win32_NetworkAdapterConfiguration] does not contain a method named 'SetDNSServerSearchOrder'.

To Reproduce
Go to powershell 7.3.0
Run the script
2Go on the tweak section
3run the minimal tweaks but uncheck the homegroup and set the dns to cloudflare
The Error

Screenshots
![image](https://user-images.githubusercontent.com/77842228/201839188-df03c451-03c2-484d-8073-e69312cc5016.png)

Additional context
Windows 11

**Comment by DeveloperDurp** [comment]
Looks like this is not available in powershell core, 
![image](https://user-images.githubusercontent.com/74198206/202051906-12707902-4329-48d6-acae-930f41185f3f.png)
![image](https://user-images.githubusercontent.com/74198206/202051934-13a93928-9646-4115-9288-f00b5ee89772.png)

**Comment by 80-svg** [comment]
that worked

**Comment by DeveloperDurp** [comment]
You can leave this issue open, we should have the tool compatible with both Windows powershell and powershell core.
