### ISSUE TITLE
Add a Video Editor

### ISSUE THREAD

**Issue by HarshPatel5940** [ChrisTitusTech/winutil#38]
![image](https://user-images.githubusercontent.com/83941233/168955373-f497bf16-8d0a-4b9b-bbbd-ae54cd830488.png)

Can we have a video editor like KdenLive or something cause it can be useful many times?

The Image says KDE.KdenLive, but i think it's the windows version only...

**Comment by ChrisTitusTech** [comment]
Added in #240 - Closing Issue

**Comment by HarshPatel5940** [comment]
It's good to see that you are still maintaining this repo :D
