### ISSUE TITLE
Remove onedrive and revert libraries to local directories

### ISSUE THREAD

**Issue by lavavex** [ChrisTitusTech/winutil#385]
If during windows 11 setup, you login to a microsoft account, onedrive is setup and local libraries are coverted to OneDrive libraries (Pictures, Documents, Desktop). If you uninstall onedrive without changing libraries, it can screw up the libraries as well as user home directory.

**Describe the solution you'd like**
Add an option in tweaks to "remove onedrive and fix local libraries"

**Describe alternatives you've considered**
i've tried doing it manually and unlinking the system from onedrive by reinstalling onedrive, but nothing has worked, just gives an error about folder already existing and not having permissions

**Comment by ChrisTitusTech** [comment]
Script for mapping onedrive folder https://raw.githubusercontent.com/SteavenToolBox/Windows/main/Scripts/onedrive-uninstaller.cmd

**Comment by ChrisTitusTech** [comment]
Fixed in d6a68b0
