### ISSUE TITLE
Keyboard input lag after doing tweaks and removing bloatware.

### ISSUE THREAD

**Issue by ZebastianJV** [ChrisTitusTech/winutil#387]
Well, this is pretty self-explanatory. There is a massive 1-5 second input lag on my keyboard after I used this program. (it's lagging rn as I'm typing this issue in.) Is it a bug? This was a fresh install of Windows 10 21H1 and I used winutil on day 1 for some reason. There is massive input lag and it really screws me up on typing and on playing games. Does anyone have a fix?

**Comment by ChrisTitusTech** [comment]
Unable to replicate, remember to stick to only the recommended settings and do NOT tick every box.
