### ISSUE TITLE
Add Docker Desktop

### ISSUE THREAD

**Issue by omar-njie** [ChrisTitusTech/winutil#389]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
* Docker Desktop install via winget:
```
winget install -e --id Docker.DockerDesktop
```
**Describe alternatives you've considered**
* Download from official website:
  -- [Docker Desktop Download](https://www.docker.com/products/docker-desktop/)

**Comment by ChrisTitusTech** [comment]
Added to #374
