### ISSUE TITLE
Add .NET Framework , .NET Desktop Runtime etc.

### ISSUE THREAD

**Issue by KOX599** [ChrisTitusTech/winutil#393]
Chris add this to Windows Debloat Project   ( ALL ) .NET Framework , ( ALL ) .NET Desktop Runtime , ( ALL ) Microsoft Visual C++ and DirectX to Tweaks tab automatic install. 
And add to tweaks tab extreme tab to Disable ALL windows options , delete all ms store app , cortana etc. delete all services to only work (( web and games )) to get 0 latency like FR33THY Pack and much more

**Comment by PrincessAkira** [comment]
FR33THY just redumps his, lets say it nice, Mediocre Shit on every video.
Its just clickbait.

**Comment by KOX599** [comment]
Ok good know about FR33THY bat other things can be added like Framework , Desktop Runtime , Microsoft Visual C++and DirectX ?
I want to get 0 latency and max fps you know 1 boot for games 2 boot for work etc.

**Comment by ChrisTitusTech** [comment]
Expanding dotnet and other microsoft tools in next update. Closing issue as it is added to #374
