### ISSUE TITLE
Discord Upgrade Bug

### ISSUE THREAD

**Issue by HarshPatel5940** [ChrisTitusTech/winutil#4]
[FIXED AFTER SYSTEM RESTART]

### I am getting a bug when I try  "upgrade all". I have noticed that the bug is happening during the upgrading of discord.

- Even Though It's working fine after the restart, I thought of reporting the log files here which might be useful for you..

[SquirrelSetup.log](https://github.com/ChrisTitusTech/winutil/files/8693036/SquirrelSetup.log)

Thanks for looking into this issue,
Harsh Patel

**Comment by Carterpersall** [comment]
Was Discord running when you attempted the upgrade? That is what the log file seems to be pointing to:
```
11500> 2022-05-14 19:13:34> Program: Install path C:\Users\HARSH N PATEL\AppData\Local\Discord already exists, burning it to the ground
11500> 2022-05-14 19:13:35> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: Access to the path 'C:\Users\HARSH N PATEL\AppData\Local\Discord' is denied.
```

**Comment by Carterpersall** [comment]
@HarshPatel5940 Just saw that it was fixed after a system restart. If the issue is resolved, please close the issue to prevent clutter in the issues tab.

**Comment by HarshPatel5940** [comment]
Umm yes the discord was running in background...

Will it be a good suggestion
-  If we close programs before upgrading?
- This can reduce these type of errors which we might run into...

Or Alternatively
- we can have a pop up warning that the app is still running and we need to close that app to upgrade it..

**Comment by Carterpersall** [comment]
Sounds like a good idea but it might be something that the devs of the program itself should implement into the installer as checking for each and every program would be an absolute hassle on our end

**Comment by HarshPatel5940** [comment]
Hmm ok, so shall I close this issue?

And shall I create a suggestion for this or it's fine?

**Comment by Carterpersall** [comment]
I would recommend this issue be closed as implementing the suggested feature will likely be too difficult to maintain long term.

**Comment by HarshPatel5940** [comment]
Hmm ok 👍
