### ISSUE TITLE
Tweak setting services replace already disabled services 

### ISSUE THREAD

**Issue by alex3xelax** [ChrisTitusTech/winutil#400]
hi

If i setting some services as "disabled" not included in the "optimization tweak" before running the optimization PS script, these services change to "manual" start.

Is possible add an option to leave the already disabled services alone ?

thanks

**Comment by ChrisTitusTech** [comment]
The short answer is no.

The long answer is there are many configurations and often people run too many things and my script is intended to fix any incorrect configurations.
