### ISSUE TITLE
Tool installs Git instead of selected program(s)

### ISSUE THREAD

**Issue by teacher-svb** [ChrisTitusTech/winutil#401]
**Describe the bug**

When I select VS Code, Github Desktop or Unity to be installed through the install section, Git is installed instead.

**To Reproduce**
1. Go to 'Install'
2. Click on the checkbox for 'Github Desktop'
3. Click on 'Start Install'
4. Git is installed instead
5. The tool reports that Github Desktop is installed, allthough it isn't

**Expected behavior**

The selected programs are installed.

**Screenshots**

![image](https://user-images.githubusercontent.com/39157063/203595956-bf177a26-e975-4ecc-afd1-8a7f0ece6409.png)

![image](https://user-images.githubusercontent.com/39157063/203596172-e1437cd0-eb76-4475-b876-9819ba87d9a5.png)

![image](https://user-images.githubusercontent.com/39157063/203596230-40ac5869-868c-4ce6-a1f1-8df8ed491e7a.png)

**Additional context**

**Comment by DeveloperDurp** [comment]
I know exactly what's wrong, hotfix should be available soon.
