### ISSUE TITLE
Monitor turns off and on intermittently

### ISSUE THREAD

**Issue by henkisdabro** [ChrisTitusTech/winutil#402]
**Describe the bug**
After quite a number of hours of general computer usage (no gaming), the monitor blacks out and comes back on again. Once this behaviour starts, it keeps doing this intermittently, allowing me to work for a few minutes, then it happens again, sometime keeping the screen black for 15-30seconds. Sometimes when it comes back on, there is some vibrating ghosting of text, making it blurry. The only way to mitigate the behaviour is to reboot the computer. There has been a feeling that Google Meet video calls with screen sharing encourages this issue to appear sooner than normal.

**To Reproduce**
1. Use the winutil script to "run all tweaks" for the "DESKTOP" profile
2. General Windows Usage for a couple of hours

**Expected behavior**
Should be no issues with the monitor.

**Screenshots**
None available

**Additional context**
Note that I'm **unsure** whether my issue is related to this tool or not, I only have a sample size of my own machine, and also my friend's machine, which _just_ started using your debloat script last week and for the first time started experiencing the same symptoms, which drew me to believe it might be this script.

**Comment by lincolntan36** [comment]
Have you tried updating your graphics drivers? or uninstalling graphics drivers and reinstalling them?

**Comment by ChrisTitusTech** [comment]
Unable to replicate, going to close it.
