### ISSUE TITLE
Can't install programs

### ISSUE THREAD

**Issue by GokhanTurk** [ChrisTitusTech/winutil#403]
I can't install any program. When I select the program checkbox and click the "Start Install" button. It says it is installed but the program is not installed.

1. Go to 'Install tab'
2. Select any program
3. Hit Start Install

Expected behavior:
Installing the selected programs.

![image](https://user-images.githubusercontent.com/26171558/203717383-b9b9a986-0bd2-4c2f-8de8-9ca46993587d.png)

As you can see on the left side there is no Brave on the programs list.

**Comment by DeveloperDurp** [comment]
You might need to reboot your computer and try again. Winget can be very temperamental at times.

**Comment by k-rku** [comment]
I'm seeing the same behaviour on 3 systems.  2 Win11 and 1 Win10.
The Wintool says that it installed the chosen application(s)... but they aren't really.
At one point I was able to capture this screenshot.
<img width="672" alt="winget" src="https://user-images.githubusercontent.com/119048964/204049184-38b98c01-1137-4175-a84b-7d6babe56b71.png">

This disappears quite quickly without showing any installation progress and it ends with a popup saying that the application was installed... while it wasn't.

To me it seems like there are more general WinGet issues perhaps?

**Comment by DeveloperDurp** [comment]
Yeah it's something with winget, could be how it's installed through the script (IE not through the windows store) or something else entirely. Winget is nice but it doesn't seem like it was built to be part of a CLI tool, I tried getting error handling at one point and it wasn't cooperating very nicely.

**Comment by k-rku** [comment]
Looks like I was ignoring the Chocolatey error upon starting the WinTool.
After installing Chocolatey, the installation of applications is working for me.

**Comment by DeveloperDurp** [comment]
Completely unrelated, chocolatey hasn't been fully implemented yet 🙃
