### ISSUE TITLE
Adding of game launchers 

### ISSUE THREAD

**Issue by Kashinto** [ChrisTitusTech/winutil#409]
Hi Chris,

First of all I want to thank you greatly for all your effort and your educational vids! It's really awesome to see and learn on things from someone else's perspective on certain things. I can't wait for your next video with regards to this all in one tool!
I don't know if I'm asking a lot but please could you add Rockstar & Battle.net launchers to your Games install features? The more the merroir they say hahahaha
Anyways, thanks again and hope you have a wonderful day\weekend!

**Comment by ChrisTitusTech** [comment]
Not in winget or chocolatey.
