### ISSUE TITLE
Suggestion: Separate Section for tweaks that can't be un done

### ISSUE THREAD

**Issue by MrErrorSan** [ChrisTitusTech/winutil#410]
After watching latest video...
I realized that not many users will read the caution prompt and then register new issues....
So make another section under "non reverse able tweaks ".
Make this section separate after the undo tweaks button for better understanding....

**Comment by DeveloperDurp** [comment]
ideally all tweaks should be reversible, I did attempt to solve this in the runspace version. Perhaps I could tackle integrating it into the main script. I am not sure all that has been changed however so that would need a lot of testing/checks to make sure everything is up to date.

**Comment by MrErrorSan** [comment]
Thanks for the reply...
In this I am mentioning removal of edge, defender, Cortana, etc.
In video, it was mentioned that if these tweaks are done then it means no going back....
So, I just want a separate Section for such tweaks.

**Comment by lincolntan36** [comment]
> ideally all tweaks should be reversible, I did attempt to solve this in the runspace version. Perhaps I could tackle integrating it into the main script. I am not sure all that has been changed however so that would need a lot of testing/checks to make sure everything is up to date.

Maybe it should still temporarily be added, since as you said not all tweaks are reversible yet

**Comment by MrErrorSan** [comment]
Thanks

**Comment by DeveloperDurp** [comment]
> Thanks for the reply... In this I am mentioning removal of edge, defender, Cortana, etc. In video, it was mentioned that if these tweaks are done then it means no going back.... So, I just want a separate Section for such tweaks.

Ah yes, that makes sense. Yeah, perhaps a separated section of "dangerous" tweaks or perhaps a warning if you check it.
