### ISSUE TITLE
Drivers Installs/Updates

### ISSUE THREAD

**Issue by pmorg83** [ChrisTitusTech/winutil#412]
Would love to have an option to install/update all the drivers either with an app or something else like we can update apps?? 

I know that windows can update drivers for you but heard it is not always recommended. 

I heard of driver booster, but I am never sure if they install drivers rightly if thats a way of describing it. as when my older system would be using this Driver booster an would say oh new update but when I check the manufacture website its like last update was 2 years ago an driver booster is saying just released a few days ago. 

So i dont know if there is a better option on updating drivers??  I know coding can do alot of things but this one might prove tricky??

Would love to hear your thoughts on this subject

 **Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Carterpersall** [comment]
Snappy Driver Installer Origin is the only good driver installer program out there that I know of. I'm not sure if we can integrate it into the script though as it is a portable app.

**Comment by adamshumpisxxx** [comment]
+1 for SDIO. You can not only scan for and get new drivers for your system but you can preload a huge database of drivers for other systems and save them to storage. It's open source, free and portable. IOBit's Driver Booster is almost malware AFAIC.

**Comment by ChrisTitusTech** [comment]
Working on it #642 - Closing this.
