### ISSUE TITLE
Additional DNS Options - Quad9

### ISSUE THREAD

**Issue by TOGLK** [ChrisTitusTech/winutil#416]
**Is your feature request related to a problem? Please describe.**
This is a feature request for an additional commonly used Pro-Privacy DNS service to be added to the "DNS" option of the "Tweaks" section of the application.

**Describe the solution you'd like**
I would like to request that the Free & Open-Source, Pro-Privacy DNS Service known as "Quad9" is added as a selectable option to the "DNS" drop-down menu in the "Tweaks" section of the application.

As Quad9 offers many different DNS Server options based on what type of configuration you would like to have it would be nice if a secondary "pop-out" or "drop-down" section could be added to the existing DNS "drop-down" menu that then lists all of the primary options that Quad9 offers to it's users.

BUT.... It isn't a requirement of this feature request that all options should be added and I would personally just ask that at least the primary "recommenced" service option is added.

The details for the "Recommended" service option are listed below:
IPV4 Address 1 - 9.9.9.9
IPV4 Address 2 - 149.112.112.112
IPV6 Address 1 - 2620:fe::fe
IPV6 Address 2 - 2620:fe::9

**Describe alternatives you've considered**
I'll be honest and state the rather obvious (to me anyway) fact that I have not considered any alternatives because their isn't really any other Free & Open-Source DNS service that can compete with Quad 9 on either feature set, or, overall usability.

Also, Quad 9 offers up a level of Bandwidth that only the much larger DNS providers can compete with and it therefore dwarths any potential competitors that might have otherwise of been able to provide a Pro-Privacy DNS solution for free to the public with "No User Activity Logs" & "No User Tracking".

**Additional context**
You can find further details on the multiple available DNS servers that Quad9 host listed on the following official "Quad9" website page:
https://www.quad9.net/service/service-addresses-and-features#ip

If you want to learn more about Quad 9 as a service and the people behind it then the YouTube Content Creator & Pro-Privacy Advocate "Techlore" has now done at least two interviews with the GM of Quad 9 in which they discuss in-depth how Quad 9 works, but also, how most other DNS providers operate and the differences taken by Quad 9 to ensure user anonymity to as extreme an extent as is possible while still providing the end user with a working DNS service.

Here is a link to one of the two "Techlore & Quad 9" interview style videos that I am aware of:
https://www.youtube.com/watch?v=pl615h44QQ8

I am NOT affiliated in ANY WAY with Quad 9 or ANY other DNS Provider, I am NOT affiliated with "Techlore" or any of it's partners or affiliates!

I am a 100% wholly independent individual that is just very "Pro-Privacy" and I want to enable my Windows OS brethren to be able to access the internet in a secure & private manner for free without risk of persecution from others to the best extent within my ability.
I hope to do that by suggesting that this feature is added to your application.

I am not always active on GitHub, I usually check my account every 3-5 days, so my response to any updates my not be as swift as you might be used to and I apologize for that, I am simply just not a very active GitHub user.

Peace to all that read this, and, Have a Wonderful day wherever you are in the World!

**P.S.**
Thanks for the Awesome Software & Incredible Videos Chris, You are a good egg!

**Comment by natri23** [comment]
I also would love to see Adguard DNS to be added:
https://adguard-dns.io/en/public-dns.html

**Comment by TOGLK** [comment]
> I also would love to see Adguard DNS to be added: https://adguard-dns.io/en/public-dns.html

Could you please list out in detail the exact details of the "AdGuard" DNS instance that you are referring too.

I ask this to ensure that no confusion occurs, and, to ensure that the link you have provided contains all the relevant information that may be needed in regards to this request.

**Comment by TOGLK** [comment]
I plan to try and put together my first "Pull Request" in regards to this particular "Feature Request" (both Quad9 DNS & AdGuard DNS).

But, as I have no experience of doing this before I cannot guarantee it will be a success, wish me luck!

**Comment by kAMENkitA** [comment]
I would like to comment under this opened Issue..

Well, considering the DNS challenge, since Chris introduced the Drop/down menu for DNS, I got the idea to test those different DNS configurations in order to find how those affect on Teredo server which is closely related with playing famous games like Forza Horizon franchise (and some other UWP games). 
I intended to measure latency & packet loss using Microsoft utility Xbox Console Companion.
I started to apply different DNS's via Chris Win Utility Tool, and I didn't manage to change any server Address. After changing each DNS, I restarted IP Helper service, and nothing changed in Ethernet properties Window, then I also used command : ipconfig /flushdns to see if something will be changed concerning dns address, but still no result.

Hence, I kindly ask You Chris, and other contributors, do we really have an issue with DNS tweak, or does the fact that My PC has Static IP address, relates to the 'issue' ??  

Looking forward from hearing you soon :)

**Comment by natri23** [comment]
> 
It's the Default servers: AdGuard DNS will block ads and trackers.
IPV4:
94.140.14.14
94.140.15.15
IPv6: 
2a10:50c0::ad1:ff
2a10:50c0::ad2:ff

**Comment by n8x0b7T** [comment]
Yes, this would be a great addition.

**Comment by BurhanBudak** [comment]
Can we also get Mullvad DNS?

doh.mullvad.net has address 194.242.2.2
doh.mullvad.net has IPv6 address 2a07:e340::2

adblock.doh.mullvad.net has address 194.242.2.3
adblock.doh.mullvad.net has IPv6 address 2a07:e340::3
