### ISSUE TITLE
S2rver 2019

### ISSUE THREAD

**Issue by sbabcock61** [ChrisTitusTech/winutil#418]
I've had good success with this tool on Win 10 and then tried it on Server 2019

Installed Choclatey
Then ran the Script

Selected CPU-Z as a test install
The install looks like it goes ok and comes back with a dialog box as Installed
Below is PowerShell screen

I've tried this on 2 servers - same results
If you need any further details, please let me know

Thanks for all you work on this

Steve

###################################
# Downloading Xaml nupkg file... (19000000ish bytes)

 Deployment operation progress: https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx
    Processing
    [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]
 Deployment operation progress: C:\Users\sbabcock\Microsoft.UI.Xaml.2.7.1.nupkg\tools\AppX\x64\Release\Microsoft.UI.Xaml
    Processing
    [ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo     ]
 Writing web request
    Writing request stream... (Number of bytes written: 3532560)

###################################
# Installing x64 XAML...
###################################
###################################
# Downloading winget... (21000000ish bytes)
###################################

Checking if Winget is Installed...
Running Alternative Installer for LTSC/Server Editions
CPUID.CPU-Z

=================================
---  Installs are Finished    ---
=================================

**Comment by sbabcock61** [comment]
I’ve rebooted and tried again – Here are the logs.
This seems to happen on All server 2019 systems

During the install, I do get a quick PowerShell screen that pops up – See attached PDF

Thanks,

Steve

**Comment by sbabcock61** [comment]
Were you ever able to figure out what's going on ?

I tried again on a number of Server 2019 systems and no apps ever get installed

Steve



I've rebooted and tried again - Here are the logs.
This seems to happen on All server 2019 systems

During the install, I do get a quick PowerShell screen that pops up - See attached PDF

Thanks,

Steve

**Comment by mignochrono** [comment]
so I'm not a programmer, but i was able to search the inside of the files for the string "Running Alternative Installer for LTSC/Server Editions" Apparently the script checks if you have an LTSC or a server edition, and if you do. it will....do something? the file is "ChrisTitusTech/winutil/tree/main/functions/private)/Install-WinUtilWinget.ps1" so either its deliberately preventing them to be installed OR more likely... that section has an error, not allowing the app to run the alternative way of installing the apps.... again, i can't figure it out

**Comment by ChrisTitusTech** [comment]
Working on a new script install for winget using #347

**Comment by sbabcock61** [comment]
Thanks very much

Steve

**Comment by asheroto** [comment]
@ChrisTitusTech I've updated the winget-install script with (1) fixed licensing for Server 2022 installs and (2) alternate download URL in case the primary URL fails:
https://github.com/asheroto/winget-install

Thought I'd let you know so you could update [winget.ps1](https://github.com/ChrisTitusTech/winutil/blob/main/winget.ps1). Thanks for your help!
