### ISSUE TITLE
Check if a program is already installed and display a flag

### ISSUE THREAD

**Issue by ioannedelea** [ChrisTitusTech/winutil#419]
So if your script is able to read the following registry keys:
```
SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
```
I suggest adding a flag for each installed program, such as "(Already installed)" and the checkbox set to checked and readonly.

**Comment by Carterpersall** [comment]
It might be better to run a "list" command for every package manager the script uses, and search their outputs for every installable program.
