### ISSUE TITLE
Feature Suggestion: WizTree as an alternative to WinDirStat

### ISSUE THREAD

**Issue by Jack-Punter** [ChrisTitusTech/winutil#42]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like suggest WizTree an an alternative to WinDirStat as a disk usage analyzer utility.
In my experience it is **_much_** faster to scan and generate visualizations of disk usage compared to WinDirStat,
this is especially noticeable on large disks (I have a 1TB Nvme  SSD, a 2TB Hard-drive. WizTree is much faster at analyzing both).
WizTree is available on winget as: `AntibodySoftware.WizTree`

**Describe alternatives you've considered**
N/A

**Additional context**
I would like to note that I haven't used TreeSize which i believe to be another alternative already on this utility. Hence no comparisons to this have been made.

**Comment by Firecul** [comment]
I'd definitely second this request. As you say WizTree is much much faster.
Even if it's not replacing WinDirStat, having it as an alternative would be a good thing especially as WinDirStat hasn't been updated since 2007 iirc.

**Comment by ChrisTitusTech** [comment]
Added in #240 - Closing Issue
