### ISSUE TITLE
Option to enable/disable Hyper-V

### ISSUE THREAD

**Issue by Mrman1093** [ChrisTitusTech/winutil#421]
**Is your feature request related to a problem? Please describe.**
Hyper-V is not available out of the box on windows 10 home machines and across all machines, can be annoying to enable/disable.

**Describe the solution you'd like**
Add an option to the Config page to enable or disable Hyper-V. When enabling Hyper-V it will check if Hyper-V is installed. If installed it will enable it, if not it will download it using the option already available on the Config page and then enable it. When selecting the option to disable Hyper-V it will disable it.

**Comment by ChrisTitusTech** [comment]
HyperV is currently on life support and will be sunset towards the end of the 2020s. I'd recommend moving on to VMWare or using QEMU in Linux.
