### ISSUE TITLE
Listview for Install apps tab

### ISSUE THREAD

**Issue by Ryo501** [ChrisTitusTech/winutil#422]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but a UI design that might be a better solution.

**Describe the solution you'd like**
Consider using a list view control with checkboxes for the application install tab. This might be better option and fix layout and scaling issues as the apps list grows. List items can have fields like: app name, category, version, and install / update status. Also you can add a filter drop drown for categories and a search field for finding apps by name.

**Comment by ChrisTitusTech** [comment]
On the roadmap, but it is hard to do with XAML driven powershell menus. 

I am learning C# and can do this with WinUI3, but that will be a binary and not the same project.
