### ISSUE TITLE
Suggestion for a new software to be included

### ISSUE THREAD

**Issue by fnfontana** [ChrisTitusTech/winutil#423]
Hello,

I would like to suggest a new software to be included on the list.
Here is the link: [FxSound](https://www.fxsound.com/)

It's a pretty decent equalizer for PCs that used to be freemium, but now is completely free.

The winget command to install it:
`winget install --id=FxSoundLLC.FxSound  -e`

**Comment by ChrisTitusTech** [comment]
Added to #374
