### ISSUE TITLE
Chocolatey is not installing

### ISSUE THREAD

**Issue by SteavenGamerYT** [ChrisTitusTech/winutil#424]
**Describe the bug**
Chocolatey Version choco : The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check  the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + choco -v + ~~~~~     + CategoryInfo          : ObjectNotFound: (choco:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException   is already installed
**To Reproduce**
1. Run the Script '
2. error happens

**Expected behavior**
Chocolatey Installs
**Screenshots**
![image](https://user-images.githubusercontent.com/62666559/204066654-b34fcc0d-bc9b-421b-8c24-6948bace82fa.png)

**Comment by natri23** [comment]
I also have this problem on a Debloated Windows11 22h2

**Comment by DeveloperDurp** [comment]
please close and follow #426
