### ISSUE TITLE
Simplenote - Google Keep Killer

### ISSUE THREAD

**Issue by adamshumpisxxx** [ChrisTitusTech/winutil#425]
How about Simplenote? It's the only free cloud synced notes app that's available on ALL devices (Windows, Linux, Mac, Android & IOS) that I'm aware of. It's a real Google Keep killer. Joplin almost gets you there (for a price) but not quite. Thanks!

**Comment by ChrisTitusTech** [comment]
Looks cool adding it! Put on the list @ #374
