### ISSUE TITLE
Please add registry cleanup option

### ISSUE THREAD

**Issue by anuragoasis** [ChrisTitusTech/winutil#427]
Yes, whenever I try new software, after installing it creates some registry keys (you know) and on uninstallation it might not remove it. 
So, it leaves footprint of old programs. 

** on Github there is a repo of little-apps named Little Registry Cleaner, have a look you can get the idea. ** 
I use that to clean my registry, but I want your tool contain the feature,
which can be used by a single click. 

Maybe a button on tweak option would do great : )

Thanks Chris
You're cool dude in this ; )

**Comment by Carterpersall** [comment]
Registry Cleaners aren't really needed anymore. The _extremely_ small performance increase you might gain from using them comes with an uncomfortably large risk of accidentally breaking something.

**Comment by ChrisTitusTech** [comment]
Never use registry cleaners... https://www.youtube.com/watch?v=21VMQyQzRJw
