### ISSUE TITLE
Tool not showing properly on 1080p 125%+ scale

### ISSUE THREAD

**Issue by DominikPetrTech** [ChrisTitusTech/winutil#433]
I run the tool on 1080p monitor with 125% or 150% scale and it just scales weird
![image](https://user-images.githubusercontent.com/118555353/204093146-0420cb22-14a3-42fa-bf17-02956d8e23e8.png)

**Comment by hwalker928** [comment]
Can replicate this issue.

**Comment by ChrisTitusTech** [comment]
Might look at a XAML redesign at some point, but drawing the GUI from powershell is a bit limiting. 

I want to swap over to WinUI3 using C# instead of the powershell jank, but I do like everything being open right now.

**Comment by ajmalbuv** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/77728850/cb010cb8-849f-4ca0-b56e-38aee6e439cb)
This is How it Looks at 1366X768 @ 100% scale
