### ISSUE TITLE
running this as Admin Powershell - irm christitus.com/win | iex

### ISSUE THREAD

**Issue by WilsonBradley** [ChrisTitusTech/winutil#436]
Had previous version installed.

**Describe the bug**
running either ;
iwr -useb https://christitus.com/win | iex 
or 
>  irm christitus.com/win | iex
Chocolatey Version choco : The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check  the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + choco -v + ~~~~~     + CategoryInfo          : ObjectNotFound: (choco:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException   is already installed

    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T
C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
MethodInvocationException:
Line |
1537 |  $Form.ShowDialog() | out-null
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "ShowDialog" with "0" argument(s): "Unable to load DLL 'PenIMC_cor3.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)"

**Comment by DeveloperDurp** [comment]
Seems like you are missing parts of dotnet core framework. Windows 10 or 11? Fresh install? 

Installing the desktop runtime might resolve the issue.
https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Comment by RoboJunior** [comment]
I am getting ![Uploading 292741893...]
