### ISSUE TITLE
FEATURE REQUEST: GAMING TWEAKS

### ISSUE THREAD

**Issue by efyandro** [ChrisTitusTech/winutil#438]
### Discussed in https://github.com/ChrisTitusTech/winutil/discussions/437

<div type='discussions-op-text'>

<sup>Originally posted by **efyandro** November 27, 2022</sup>
It would be super cool if this tool can do a gaming tweak such as CPU Optimization, RAM Optimization, Latency Tweak, Network Optimization, or maybe Win32 Priority Separation. 
Adding MemReduct, Park Control and Process Lasso in application list

![firefox_Gi1UOlMefd](https://user-images.githubusercontent.com/5464033/204117621-b65100c7-9ffd-4b38-9e59-d4a480eeb115.jpg)
</div>

**Comment by ChrisTitusTech** [comment]
Working on something like this in #167
