### ISSUE TITLE
Problem with the "Remove all MS Store Apps" option 

### ISSUE THREAD

**Issue by TwistedVision518** [ChrisTitusTech/winutil#440]
After upgrading to the new 22H2 build of windows 11 the specified option does not seem to be working correctly as it is not detecting the files for the apps I presume when i first ran this tweak on 21H2 build of windows 11 everything worked perfectly out-of-the-box but after the upgrade windows just reinstalled all of the apps I removed so when I tried to remove it again it dint work keep getting the same set of errors everytime i try it even the autologin button of the tool does not do anything no error messages or not completed prompts . As i understand it winget has also been a issue for the winget users in the 22H2 build. For me personally no other tab other then the "Install" tab of the tweak is working. Thanks for your cooperation and Good work :)

Errors Are as follows 

Line |
 617 |              Disable-ScheduledTask -TaskName "Microsoft\Windows\Applic …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The system cannot find the file specified.
Disabling Application suggestions...
Disabling Feedback...
Disabling Tailored Experiences...
Disabling Advertising ID...
Disabling Error reporting...
Restricting Windows Update P2P only to local network...
Stopping and disabling Diagnostics Tracking Service...
Stopping and disabling WAP Push Service...
Enabling F8 boot menu options...
Disabling Remote Assistance...
Stopping and disabling Superfetch service...
Task Manager patch not run in builds 22557+ due to bug
Showing file operations details...
Hiding Task View button...
Hiding People icon...
Changing default Explorer view to This PC...
Hiding 3D Objects icon from This PC...
Disable News and Interests
Removing AutoLogger file and restricting directory...
Stopping and disabling Diagnostics Tracking Service...
Doing Security checks for Administrator Account and Group Policy
Disabling Wi-Fi Sense...
Disabling NumLock after startup...
Removing Cortana...
Removing Bloatware
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove 3DBuilder.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Microsoft3DViewer.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove AppConnector.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingFinance.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingNews.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingSports.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingTranslator.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingWeather.
                                                                                                                        Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingFoodAndDrink.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingHealthAndFitness.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove BingTravel.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove MinecraftUWP.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove GamingServices.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove GetHelp.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Getstarted.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Messaging.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Microsoft3DViewer.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove MicrosoftSolitaireCollection.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove NetworkSpeedTest.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove News.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Lens.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Sway.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove OneNote.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove OneConnect.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove People.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Print3D.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove SkypeApp.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Todos.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Wallet.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove Whiteboard.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove WindowsAlarms.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove windowscommunicationsapps.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove WindowsFeedbackHub.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove WindowsMaps.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove WindowsPhone.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove WindowsSoundRecorder.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove XboxApp.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove ConnectivityStore.
Get-AppxProvisionedPackage:
Line |
1017 |                  Get-AppxProvisionedPackage -Online | Where-Object Dis …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Class not registered
Trying to remove CommsPhone.
Deployment operation progress: Microsoft.549981C3F5F10_4.220. [Processing                                            ]
Deployment operation progress: Microsoft.GetHelp_10.2208.255. [Processing                                            ]
Deployment operation progress: Microsoft.Getstarted_10.2210.. [Processing                                            ]
Deployment operation progress: Microsoft.MicrosoftSolitaireC. [Completed                                             ]
Deployment operation progress: Microsoft.People_10.2105.4.0_. [Processing                                            ]
Deployment operation progress: Microsoft.Windows.PeopleExper. [Processing                                            ]

**Comment by DeveloperDurp** [comment]
https://github.com/PowerShell/PowerShell/issues/17232#issuecomment-1119052773

Wasn't aware you could install powershell through the store. Can you confirm if this is the case for you?

**Comment by TwistedVision518** [comment]
Yeah i have it through the store is thats what causing the issue?

**Comment by DeveloperDurp** [comment]
From what the comment is saying yes, you can try using "Windows Powershell" that's installed with Windows itself. 

Should look like this 
![image](https://user-images.githubusercontent.com/74198206/204526982-b306ab47-df12-4f14-866d-8801ec25de5a.png)

**Comment by DeveloperDurp** [comment]
Not quite a bug, more of a feature of Windows Apps. Apps installed through the store are typically sandboxed and have limited access to the whole system, which is good for security but bad for tools like this.

**Comment by DeveloperDurp** [comment]
Yeah, I don't think there is much we can do to resolve the sandboxed powershell session.

**Comment by TwistedVision518** [comment]
> Yeah, I don't think there is much we can do to resolve the sandboxed powershell session.

True but as i was saying the autologin button still does not work for me

**Comment by DeveloperDurp** [comment]
Apologies I completely missed that. What happens if you run this manually

`curl.exe -ss "https://live.sysinternals.com/Autologon.exe" -o autologin.exe`
