### ISSUE TITLE
Tweaks - Recommended Selection - Desktop

### ISSUE THREAD

**Issue by K1LL3RDragon** [ChrisTitusTech/winutil#443]
Run Powershell 7 and start your Winutil

Go to Tweaks > Recommended Selection > select <Desktop>
Then > Run Tweaks

This is result:
![image](https://user-images.githubusercontent.com/96773003/204161570-9dc7cc2a-5491-40ee-b6c2-99474e89b2e3.png)

Doing the same with build in PowerShell, then the result is this:
![image](https://user-images.githubusercontent.com/96773003/204161892-5e83801c-6fcb-418f-b46b-8ea36ff8915d.png)

**Comment by DeveloperDurp** [comment]
It's likely Microsoft is starting to remove compatibility with WMI Objects in powershell core.

**Comment by Carterpersall** [comment]
I've intended to replace the WMI calls with the CIM equivalents for a while now, I'll add a pull request shortly.

**Comment by Carterpersall** [comment]
During testing, I encountered a different issue where it seems that the method `SetDNSServerSearchOrder()` does not exist on PowerShell 7 with the current implementation. This is also solved with my solution.

**Comment by DeveloperDurp** [comment]
Been meaning to look into that, was related to #379 

Thanks Carter!
