### ISSUE TITLE
Add MPV to Multimedia Tools

### ISSUE THREAD

**Issue by FilipAndersson245** [ChrisTitusTech/winutil#449]
**Is your feature request related to a problem? Please describe.**
MPV is a high-quality, lightweight, cross-platform alternative to VLC.

**Describe the solution you'd like**
I would like us to add the option to install MPV inside winutil, It currently support Sccop, Chocolatey package managers (according to its install page)

**Describe alternatives you've considered**
We do not add MPV

**Additional context**
I think it would be good to have an alternative media player other than VLC, Media Player Classic.
[mpv homepage](https://mpv.io/)

**Comment by blobrush** [comment]
Why was MPV removed? Can't find it in the utility.
