### ISSUE TITLE
W11 can't restart or shut down anymore after running essential tweaks.

### ISSUE THREAD

**Issue by JRMBelgium** [ChrisTitusTech/winutil#45]
**Describe the bug**
The current version has a bug. I ran the essential tweaks and the result was that my W11 didn't shut down or restart anymore. I used the restore point to undo the changes and it worked fine again. I am willing to help you debug it. Just let me know what logs you want.

**To Reproduce**
Run Essential tweaks.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JRMBelgium** [comment]
Issue still isn't fixed. Just tried again.

**Comment by JRMBelgium** [comment]
I am not the only one. This comes from your frontpage:


Unknown
7 days ago
I've always been a big fan of your scripts but the older one from july 2021 was much better, this one just makes me pc take too long to restart or even to shutdown


fara
12 days ago
esential tweak make restart stuck so i dont use esensial tweak now, iam use win10 21h1


J
26 days ago
I am on windows 11 and once i ran essential tweak i get infinite waiting restart. I have to manually hit the reset button on the pc.

**Comment by dipanjan1992** [comment]
Same here just ran the essential tweaks and now it takes forever to restart or even boot the system. It takes almost 10 minutes to start when it took only 30 sec before running this.
