### ISSUE TITLE
Loss of selected checkboxes using utility.

### ISSUE THREAD

**Issue by darkwavepunk** [ChrisTitusTech/winutil#451]
**Describe the bug**
When using the utility I lose all of the ticks for "install" and "tweaks"
**To Reproduce**
1. Go to utility after restart or relaunch
2. Click on either "install" or "tweaks"
3. Scroll down to  N/A
4. See error N/A - just all checkboxes are blank.

**Expected behaviour**
Going back into the software after successfully installing tweaks and install should show what I've installed/configured but but given a blank slate every time even though they seem to work on the first pass.
**Screenshots**
N/A - it's just the default screen as if starting from scratch.
**Additional context**
Using the PowerShell as Admin and "irm christitus.com/win | iex"
My machine is personal but I am using policies for logging into work which may be an issue. Only use Windows because of work.
Sad old pre-System V UNIX guy who knows nothing about Windows.

**Comment by DeveloperDurp** [comment]
That feature has not been implemented, it is expected that all the check boxes are unchecked every time you start the application.

**Comment by Carterpersall** [comment]
> That feature has not been implemented, it is expected that all the check boxes are unchecked every time you start the application.

What is being said is that the checkboxes are deselected after executing the task, like installing the selected programs or applying the selected tweaks. Maybe a checkbox could be created to allow the user to specify whether they should be automatically deselected?

**Comment by DeveloperDurp** [comment]
Ah yes, that too. Current state all checkboxes are cleared after clicking the button to install applications or perform tweaks

**Comment by darkwavepunk** [comment]
Honestly can't believe anyone responded so quickly. I was just confused by the default behaviour and thought something was broken. I know you can't make things moron-proof (as we idiots evolve quickly), but much appreciated information.

**Comment by DeveloperDurp** [comment]
I usually comb through and respond if I am able to stay on top of things.

No worries on the confusion, the world of Windows is very confusing even for those that work with it all the time lol.
