### ISSUE TITLE
Slow internet issues after using script

### ISSUE THREAD

**Issue by brammie15** [ChrisTitusTech/winutil#453]
**Discription**
So, after running the deboater script with just the "laptop" preset i've noticed that some apps that use internet are waaay slower
like for example. Firefox now takes for every reload/load a good 5-10seconds, same with discord images load extremly slow.
my internet hasn't changed nor did i change anything else about my setup.
The only reason i suspect this script to be the cause is because it started happening right after i ran it.

**To Reproduce**
Run the script with the "laptop" preset

**Screenshots**
![image](https://user-images.githubusercontent.com/15068262/204390378-b01eab7e-1c56-4b27-a612-eb101af86102.png)

**Comment by DeveloperDurp** [comment]
Can you try running undo Tweaks?

**Comment by Ricsikakas3** [comment]
i'm having the same issue, ran it yesterday and undo Tweaks doesnt help at all
