### ISSUE TITLE
One liner command to upgrade all installs

### ISSUE THREAD

**Issue by mother2110** [ChrisTitusTech/winutil#456]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A one-liner to launch on remote workstations to upgrade installs, "irm christitus.com/win | iex | upgrade all"

**Describe alternatives you've considered**

**Additional context**

**Comment by Carterpersall** [comment]
Duplicate of #51, #130, and #352

**Comment by mother2110** [comment]
Thank you. Missed those
