### ISSUE TITLE
iwr : Unable  to connect to remote server

### ISSUE THREAD

**Issue by Lwolf-max** [ChrisTitusTech/winutil#464]
![123](https://user-images.githubusercontent.com/58010470/204669976-82dcd856-9ab6-446d-bb0c-e08f9294a0c0.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ChrisTitusTech** [comment]
Try `irm https://christitus.com/win | iex`

**Comment by Lwolf-max** [comment]
no same issue well debloat worked the first time i used then after restart started happening 
![image](https://user-images.githubusercontent.com/58010470/204682546-a78e777e-3f8c-4960-b27b-8bcceb2e4601.JPG)

**Comment by Carterpersall** [comment]
Can you connect to https://christitus.com and git.io using a web browser?

**Comment by K1NG527** [comment]
yes man same problem

**Comment by ChrisTitusTech** [comment]
sounds like a DNS issue. 

Try this
```
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')
```

**Comment by K1NG527** [comment]
its working after conneting to dns 1.1.1.1

**Comment by Lwolf-max** [comment]
can you help me King527

**Comment by K1NG527** [comment]
just download 1.1.1.1 dns from google
and connect to it then it will work

**Comment by NicciZar** [comment]
If its a dns issue:

![image](https://user-images.githubusercontent.com/43537611/205069383-f66c5e91-4e4d-45a9-b775-98e54aaac81f.png)
![image](https://user-images.githubusercontent.com/43537611/205069418-636348d8-af67-465a-8c46-190bcc62dd13.png)
![image](https://user-images.githubusercontent.com/43537611/205069448-aa148345-2a86-4fa3-8bc0-d42c63ea4abd.png)
![image](https://user-images.githubusercontent.com/43537611/205069464-3e890f61-4e3d-4bbe-bbd5-ed3eefbe17e5.png)
![image](https://user-images.githubusercontent.com/43537611/205069504-1cdd8198-282c-4093-bd35-48fdec0d1676.png)

**Comment by Lwolf-max** [comment]
it tried but same issue

**Comment by Lwolf-max** [comment]
i dont know what to do i will just reset the computer now

**Comment by NicciZar** [comment]
Did you run the windows troubleshooter for network connectivity? It usually resets the network connection to default settings which might work

![image](https://user-images.githubusercontent.com/43537611/205281095-b33e1dd7-ad22-4b9b-ab60-72b5e60b7237.png)
![image](https://user-images.githubusercontent.com/43537611/205281110-b82fd57a-af6f-4ef2-a7b0-4a2bf06c3d67.png)

let it run and maybe it works. 

Did you reach the internet at any time before?

**Comment by Lwolf-max** [comment]
Yeah it was a dns issue i have a windows11 so after reseting the networks setting i just again change dns to 1.1.1.1 and 1.0.0.1 and turn on DNS over HTTPs and Fall back to plain text and it worked thanks you for the support i would have formated but i believed in the community

**Comment by NicciZar** [comment]
Great to hear its working again :)

**Comment by Gameman360** [comment]
It is still not working for me. Even after changing the DNS severs.
![image](https://user-images.githubusercontent.com/57745636/215160889-32de9e1d-bc49-454d-a673-ddf52abbf44e.png)

**Comment by NicciZar** [comment]
Can you open the address in your normal browser?

**Comment by Gameman360** [comment]
> Can you open the address in your normal browser?

which address?

**Comment by NicciZar** [comment]
Thhe one mentioned in the screenshot

![image](https://user-images.githubusercontent.com/43537611/215324419-a47a667a-2ca7-4bff-aa92-3acbab73f554.png)

**Comment by NicciZar** [comment]
Did you run the script as admin?

**Comment by Deva-Agarwal** [comment]
> Did you run the script as admin?

Yes I did.

**Comment by bunny1-1** [comment]
Tried all the solution mentioned above i'm still getting the issue anyone please help

**Comment by lucid-codr** [comment]
Worked for me when I changed my IPv6 DNS as well as IPv4.
2606:4700:4700::1111
2606:4700:4700::1001

**Comment by Richard9526** [comment]
bro  help me out here.. anyone.... im still having the problem

**Comment by bunny1-1** [comment]
Hey buddy,

It's nothing but DNS issues just change DNS as stated on website you might
also find on comments also I actually not remember right now.

You might need to restart your device once connect to network.
Try once or twice.

**Comment by Richard9526** [comment]
THE THING IS... i installed  a tweaks for the notification pop up to stop and it did...but thn i realised i needed it back so i had to recheck it again on the christitustool page...but thn now its just showing...
Unable to connect to the server,,,
i changed DNS, restarted, tried the other links..still the same  damnn problem

**Comment by bunny1-1** [comment]
Trust me bro  try different ways of changing DNS or change whole network (
your wifi to mobile hotspot or something)

It's really a DNS issue and nothing else

Try again you will figure it out

**Comment by Obnomus** [comment]
> THE THING IS... i installed a tweaks for the notification pop up to stop and it did...but thn i realised i needed it back so i had to recheck it again on the christitustool page...but thn now its just showing... Unable to connect to the server,,, i changed DNS, restarted, tried the other links..still the same damnn problem

Use vpn and it'll work

**Comment by nikkdrive18** [comment]
I found whats causing this problem. Its IPv6. Changing DNS didnt make any difference.
Disable IPv6 to fix it before running the script.
![Untick-IPv6](https://github.com/ChrisTitusTech/winutil/assets/131444909/82ccb3a5-8d35-4472-90fe-fcb6caa54f51)

**Comment by lucid-codr** [comment]
On any system which i face this issue i just go onto the google dns website and change my IPv4 and IPv6 dns address by going into the network adapter settings as shown earlier by some.

**IPv4**:
```
8.8.8.8
8.8.4.4
```

**IPv6**:
```
2001:4860:4860::8888
2001:4860:4860::8844
```

Some older devices may even use:
```
2001:4860:4860:0:0:0:0:8888
2001:4860:4860:0:0:0:0:8844
```

As a plus it even helps resolving of domains faster ( loading websites faster )
