### ISSUE TITLE
Issue Starting App After Undoing Tweaks

### ISSUE THREAD

**Issue by ThatNerdPanda** [ChrisTitusTech/winutil#466]
**Describe the bug**
Hello, I'm having an issue getting the service/app to start up after I used the undo tweaks button and then restarted my system.

**To Reproduce**
1. Open the App
2. Run the Undo Tweaks
3. Restart the System
4. Try Running The Service Again
5. Error

**Expected behavior**
The app/service should open and allow me to interact with a UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/65537271/204673881-e894cc81-4677-468b-ad52-310be9366879.png)

**Additional context**
N/A

**Comment by ChrisTitusTech** [comment]
One sec doing an update should be fixed in the next couple minutes. 5 minutes at max!

**Comment by ChrisTitusTech** [comment]
Ok should be fixed now.
