### ISSUE TITLE
Add Potplayer to the Multimedia Tools

### ISSUE THREAD

**Issue by Ash2001green** [ChrisTitusTech/winutil#469]
Could Please add Potplayer to the Multimedia Tools

**Comment by tunzer68** [comment]
am i going crazy - cause i dont see it - thx

Could Please add Potplayer to the Multimedia Tools

**Comment by SUFahad007** [comment]
add Potplayer please

**Comment by DRYN07** [comment]
Any news about this? I would love to see this in the apps.
