### ISSUE TITLE
Add install path

### ISSUE THREAD

**Issue by Temepest74** [ChrisTitusTech/winutil#470]
I would just love to be able to install all my apps inside a specific folder, each app creating its own subfolder

**Comment by DeveloperDurp** [comment]
That is currently out of scope of this tool

https://github.com/ChrisTitusTech/winutil/issues/190#issuecomment-1272410087

**Comment by Temepest74** [comment]
Ok, i understant if we are talking about each app, but what about selecting it one for all apps? This is usefull when the main ssd is small

**Comment by DeveloperDurp** [comment]
It will still add a layer of complexity, even more say as we are working to introduce alternative package managers to alleviate winget issues.
