### ISSUE TITLE
ADD Franz

### ISSUE THREAD

**Issue by Avatarsia** [ChrisTitusTech/winutil#477]
i would recommend to add FRANZ as a Communication Programm, this includes the most of the other Programms so you just need to maintain 1 programm instead of a lot others
https://meetfranz.com/

**Comment by lightr4in** [comment]
As a fork of Ferdi which is a cancelled Fork of Franz, I'd recommend adding [Ferdium](https://ferdium.org/) ([github](https://github.com/ferdium/ferdium-app)) at this place.

**Comment by Avatarsia** [comment]
> As a fork of Ferdi which is a cancelled Fork of Franz, I'd recommend adding [Ferdium](https://ferdium.org/) ([github](https://github.com/ferdium/ferdium-app)) at this place.

whats the difference between these forks ?
