### ISSUE TITLE
Add Files file manager to Utilities

### ISSUE THREAD

**Issue by Somdobomk** [ChrisTitusTech/winutil#480]
**Is your feature request related to a problem? Please describe.**
Files.community app is an open source modern file explorer to replace the default windows explorer that includes split panes, tabs, cloud integrations, file previews, tagged files and folders.

**Describe the solution you'd like**
I would like us to add the option to install Files using winget. 

**Describe alternatives you've considered**
We don't add it.

**Additional context**
I think it would be good to have an alternative files app just like we have an alternative to the right click menu.
[Files Homepage](https://files.community/)
<img width="784" alt="Screenshot_20221201_115745" src="https://user-images.githubusercontent.com/3749153/205225490-89e061a3-41b0-4320-a592-841900bcdb77.png">

**Comment by ChrisTitusTech** [comment]
Not in Winget Library.
