### ISSUE TITLE
Power Controls for USB Controllers

### ISSUE THREAD

**Issue by JimPetko** [ChrisTitusTech/winutil#481]
I was previously a software engineer for a USB device(Cameras and Sensors) manufacturer. I've used your very useful utility a few times now and wanted to contribute. 
Disable USB Selective Suspend & Power Management on USB Controllers.
Either integrating into the Ultimate Power profile or adding as a different function.
I've written  an application to do this with WMI and C#, its a Winform application on my github page if you want to take a peek. I'm sure doing the same in power shell or with a call to powercfg.exe 
[USBDevice_PowerManagement](https://github.com/JimPetko/USBDevice_PowerManagement)

Selective suspend can cause issues with some High USB Bandwidth devices so it might be a benefit to easily disable it in the power profile. The Power management setting for individual USB Controllers however is not effected by the selective suspend option. Disabling this needs to be done within Device Manager and in my experience, manually across all controllers and sub-controllers.   

Let me know if you'd like to discuss.
Thank You.

**Comment by JimPetko** [comment]
Maybe adding a 'Take Ownership' option to the right click menu would be a nice to have as well. Saved me once or twice. Just need to do these Registry edits:

[HKEY_CLASSES_ROOT\*\shell\runas]
@="Take Ownership"
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\*\shell\runas\command]
@="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"
"IsolatedCommand"="cmd.exe /c takeown /f \"%1\" && icacls \"%1\" /grant administrators:F"

[HKEY_CLASSES_ROOT\Directory\shell\runas]
@="Take Ownership"
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Directory\shell\runas\command]
@="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"
"IsolatedCommand"="cmd.exe /c takeown /f \"%1\" /r /d y && icacls \"%1\" /grant administrators:F /t"

**Comment by ChrisTitusTech** [comment]
I use Shell program for the ownership. Works great and is in the utility
