### ISSUE TITLE
powershell not opening tool

### ISSUE THREAD

**Issue by chahuhanjayc** [ChrisTitusTech/winutil#482]
PS C:\WINDOWS\system32> iwr -useb https://christitus.com/win | iex
iwr : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by chahuhanjayc** [comment]
PS C:\WINDOWS\system32> [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')
Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
At line:1 char:79
+ ... ype]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by systemcoding** [comment]
Same thing happening to me as well.

![image](https://user-images.githubusercontent.com/68456596/206852308-0744cb11-b381-40c5-a8d8-b425e2206dfc.png)

**Comment by davidmorales0722** [comment]
I have the same issue. Did anyone find how to solve this?

```
iwr -useb https://christitus.com/win | iex
iwr : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

**Comment by chahuhanjayc** [comment]
i feel this error is version specific and i recently switched back to
stable win 11 and its working fine now.
