### ISSUE TITLE
Undo tweak doesn't reset everything.

### ISSUE THREAD

**Issue by thamudi** [ChrisTitusTech/winutil#487]
**Is your feature request related to a problem? Please describe.**
After I found out that I cannot use xbox overlay at all, I tried to undo the tweaks, a lot of things came back except the Xbox overlay was one of them, I tried repair and resetting the app, even reinstalling it from the power shell but nothing worked. 

I also noticed that the xbox Accessory management service is stuck on starting
`XboxGipSvc` in particular. 

**Describe the solution you'd like**
I'd like for the undo tweaks to work properly and actually undo all of the tweaks.

**Comment by realityuk** [comment]
Three whole years later, this issue is still prevalent lol
