### ISSUE TITLE
Hey Chris - This was the only way I knew to contact you that you'd see it

### ISSUE THREAD

**Issue by putaindordinateurs** [ChrisTitusTech/winutil#49]
Hey Chris,
Hi,
I hope this message finds you well, healthy, and most importantly ... Happy!!!
I didn't want to leave this on your Tube channel, as I wasn't sure you'd see it, and it's the only way I saw here to leave you a note. I've been working on your GUI for the winutil as I said I would. I DID in fact find my through the "code" to come up with a little better "look" and I started working on a more "updated" logo for you. Yours looks great, I just thought I'd throw it in the "paying Chris back" pile, and if ya dig it, cool. If not, cool too! My question for you however, is, "Can a vector graphic, that would expand and collapse proportionally with that cool new feature I was stoked about, be added as opposed, or in addition to the hexadecimal value for the background color? If so, I think I have a pretty tight new look for the whole thing, that'll work with your current logo, or one of the iterations of a new I'll come up with eventually. I can show what I've done, but I dunno where to try to upload it here, or if you'd want the file in some other way. I still send files via ericstevencook@hotmail.com like I have since ... well, since hotmail existed or thereabouts, so if ya wanna do that, that's cool. I guess I maybe shoulda prefaced this with, "This is Mr.E from your YouTube Channel." Dunno if ya ever even saw my comment there after you posted the video, and since I suck at everything BUT art, which is debatable at times😊, I figured I'd pitch in, as you've helped me a TON!!! Anyway, if you did read that comment, I haven't flaked on ya, I am, in fact, "on it". Let me know if that's even doable, but I got the idea, and just made the image while I "saw" it, so no biggie. I just assumed, as HTML and JavaScript are about the only "codes" I know, and on a webpage, using HTML, you could have a color value, i.e. #777777, as well as an image set as a background. That used to be important when you had to wait a bit for a BG image to load, but that was somewhere between 56k and DSL and this ISN'T HTML, but trying to help a friend is never a waste of time. I'd at least like you to see where I was thinking about taking the GUI esthetic, even if it work. If it will, an image for the BG, I'd assume would mean I could make images for all the buttons as well, which I thought would give it the "pro" look it deserves ... it deserves A LOT. I know there were a few "bugs" with the update, but when aren't there. I have a good buddy who said he'd take a look at your code as well on the 4 thingys you'd asked about, i forget what they were now, but he knew what you were talking about, so hopefully he'll get a chance to help out as well ¯\_(ツ)_/¯ (His Dad helped invent the "gold stuff" on Nasa space vehicles, where he worked, and he's been "programming" literally since the 80's when we had a couple Korg's and a 4 track, so unlike me, he'd be an asset for ya, IF he can) Hopefully you get this. It didn't seem like the thing that fell under "pull request" from the little I understood it, so this seemed the best place, unless I waited for your next vid to come out on the Tube, and chucked this on it immediately ... so yeah ... hopefully you get this.
Please let me know at your earliest convenience. I sincerely appreciate your valuable time.
Much love!!! ✌
       ϻя.ƹ

**Comment by ssrahul96** [comment]
Hey @putaindordinateurs , If you could provide those as `svg`. we could add that to `xaml`
