### ISSUE TITLE
Please add back the option to remove OneDrive

### ISSUE THREAD

**Issue by CilekciGs** [ChrisTitusTech/winutil#490]
The old script (https://github.com/ChrisTitusTech/win10script) used to have it, but is has since been removed. Please add it back. I think it is very useful.

**Comment by Rekko12** [comment]
You can disinstall it on your own at this point,I think there is no need to introduce it back

**Comment by Gh0stBustr** [comment]
+1 YES please add this option, very useful!

@Rekko12 the point of this app is to be a "one stop shop" so I don't think your comment is valid. 
Plus it would be nice if all underlying services and extra garbage belonging to OneDrive could be eradicated as well.

**Comment by CilekciGs** [comment]
@Rekko12 Well you can launch control panel yourself or download anything yourself too. This is a toolbox which makes day to day jobs of sysadmins easier.

**Comment by Gh0stBustr** [comment]
Haha then why not delete this "toolbox" altogether.. I can do all of this on my own anyway, so why bother making this in the first place..... ;)

If you want to keep missing features go ahead.. but don't expect me to believe your false argument about why it's the right thing to do.

**Comment by Gh0stBustr** [comment]
Exactly.
One could do all this manually if they wanted to, but the point of this toolbox is to have everything in one place and carry out these tasks with a single click, making life super easy.

**Comment by kat26** [comment]
Im with Gh0stBustr bring the OneDrive removeal back you have OneDrive under Microsoft Tools for install so why not have the reversal were we can uninstall OneDrive.

**Comment by ChrisTitusTech** [comment]
Working on this in #385 - the big thing is changing the default folders back from a onedrive implementation and making sure it doesn't delete local files in the proecess.
