### ISSUE TITLE
Please add an option to tweak modern standby or sleep settings

### ISSUE THREAD

**Issue by lincolntan36** [ChrisTitusTech/winutil#491]
**Is your feature request related to a problem? Please describe.**
Modern standby is a feature that is really badly implemented.
Linus recently made a vid on it.
https://www.youtube.com/watch?v=OHKKcd3sx2c

**Describe the solution you'd like**
An option to disable modern standby or at least disable the network connected mode.

**Additional context**
Some cmd commands grabbed from https://www.tenforums.com/tutorials/146593-enable-disable-network-connectivity-modern-standby-windows-10-a.html
On battery

(Enable)
`powercfg /setdcvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 1`
(Disable)
`powercfg /setdcvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 0`
(Managed by Windows - Default)
`powercfg /setdcvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 2`

 Plugged in
(Enable - Default)
`powercfg /setacvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 1`
(Disable)
`powercfg /setacvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 0`
(Managed by Windows)
`powercfg /setacvalueindex scheme_current sub_none F15576E8-98B7-4186-B944-EAFA664402D9 2`

**Comment by github-account1111** [comment]
> Closed due to inactivity

Amazing.
