### ISSUE TITLE
Not install Chocolatey by default / as dependency.

### ISSUE THREAD

**Issue by LawrenceMz** [ChrisTitusTech/winutil#492]
Hello,
First I want to thank you for the development of this great utility, it significantly improves the use of Windows resources.

**Is your feature request related to a problem? Please describe.**
I think that many users are only interested in the tweak section and not necessarily in installing programs automatically.

At the beginning of winutil.ps1, it verifies the existence of Chocolatey and if it cannot find it, it proceeds to install it.

In my case I use Chocolatey on a regular basis but, home users or gamers don't need it. I know it's a small dependency but it's still an unnecessary installation in a program trying to minimize process usage and reduce bloatware. Furthermore, if a user wants to just run the program out of curiosity, without making any changes to his system, he cannot do so without installing Chocolatey first.

**Describe the solution you'd like**
Chocolatey should only be installed when the user press “Start Install” button and have checked some program.

**Comment by jstok84** [comment]
I created pull request for this issue.

https://github.com/ChrisTitusTech/winutil/pull/519

**Comment by ChrisTitusTech** [comment]
Merged #519
