### ISSUE TITLE
Tool don't work in domain environment

### ISSUE THREAD

**Issue by omnomnomnomww** [ChrisTitusTech/winutil#493]
I try to use this tool to configure devices with windows 10 and 11 for users in windows domain environment but when im log in to user account nothing work in tool. Can't install anthing, or do any tweeks. I try open power shell as local admin, domain admin and user, results are the same when im on user account. But when i relog to local admin, or user with domain admin right everything in tool works fine. Powershell 
This tool don't work in domain or i just do something wrong?

**Comment by ChrisTitusTech** [comment]
It wouldn't as a user, and I wouldn't recommend it in that environment. You can copy these settings into your Group Policy Management on your Domain Controller.
