### ISSUE TITLE
The power scheme, subgroup or setting specified does not exist.

### ISSUE THREAD

**Issue by Liidd** [ChrisTitusTech/winutil#497]
Trying to add the ultimate performance profile I get the error, "The power scheme, subgroup or setting specified does not exist." Is there any way to fix this? thank you.

**Comment by AminGholizad** [comment]
I first ran adding the profile it did not show up on the profiles which I only have balanced. then I clicked on remove and add again now I get the error. the first time the only prompt was `Adding Ultimate Performance Profile` and now it is `Adding Ultimate Performance Profile
The power scheme, subgroup or setting specified does not exist.`

**Comment by ChrisTitusTech** [comment]
Fixed in a recent commit
