### ISSUE TITLE
Just a few feature requests

### ISSUE THREAD

**Issue by techguy16** [ChrisTitusTech/winutil#505]
## Here is a few features I would like to see in your Windows Utility:
- A textbox so the user can input a package and install that package which is not on your Software list
- Windows 8.1 support (Yes, I know, Windows 8.1 ends support in about a month.t)
- FIX - Windows Subsystem for Linux on Windows 10/11 Home not working (Yes, I am a Linux user)

Also I have revived ArchTitus. New link - [https://github.com/techguy16/OpenArchTitus](https://github.com/techguy16/OpenArchTitus)

**Comment by eabase** [comment]
I don't agree to provide any Win 8.1 support. That OS is over a decade old! I was one of the last to migrate from W8 to W10, and although my W8.1 was super tuned, there were always shit-loads of compatibility issues ,that required a lot of hacking to get around. One day my HD crashed and I was was forced to go W10, thanks for that I could finally be dev productive again!
**Let's stay away from bloated legacy support. Please!**

About the WSL issue, please post a separate and detailed issue report.

**Comment by techguy16** [comment]
> I don't agree to provide any Win 8.1 support. That OS is over a decade old! I was one of the last to migrate from W8 to W10, and although my W8.1 was super tuned, there were always shit-loads of compatibility issues ,that required a lot of hacking to get around. One day my HD crashed and I was was forced to go W10, thanks for that I could finally be dev productive again! **Let's stay away from bloated legacy support. Please!**
> 
> About the WSL issue, please post a separate and detailed issue report.

I'll fork it then and add Win8.1 support then.
