### ISSUE TITLE
issue when confirming license agreements

### ISSUE THREAD

**Issue by Sander470** [ChrisTitusTech/winutil#506]
**Describe the bug**
When upgrading, the script asks for accepting all license agreements. However, I didnt know how to accept them other than an educated guess, as the "[Y/N]" only popped up AFTER i entered a Y.

**To Reproduce**
upgrade something with license agreements to accept

**Expected behavior**
i expected the "[Y/N]" to be before entering input, otherwise it's hardly a useful hint.

**Screenshots**
sorry, i had to restart immediately, so dont have screenies.

**Comment by ChrisTitusTech** [comment]
this was fixed
