### ISSUE TITLE
Packages do not install in util, and afterwards, winget is hosed

### ISSUE THREAD

**Issue by MarkMedici** [ChrisTitusTech/winutil#508]
Still trying to reproduce this reliably.

So far, in some but not all of the Win11 VM's on which I've used WinUtil, winget has been broken afterwards.  It seems the winget repos are unavailable.  I haven't figured out how to fix.  It doesn't happen all the time.  I really don't have time to chase this down.  But this isn't the first time winutil has broken Windows -- I've tried several iterations since you first released it.  Overall impression: this is an interesting toy that might be worth studying & harvesting the code, but it's not ready for production use.

**Comment by ChrisTitusTech** [comment]
Just had a new PR #543 that looks to make this more reliable. I'm also going to add some redundancy to chocolatey for when winget is not available.
