### ISSUE TITLE
Error while running the utility code - irm christitus.com/win | iex  

### ISSUE THREAD

**Issue by SAHILPANCHOLI** [ChrisTitusTech/winutil#511]
**Describe the bug**
When I enter the code in PowerShell as admin it shows the following error (Check Screenshot Below)

**To Reproduce**
I don't think that this is reproducible as it is just a system error(I suppose)

**Expected behavior**
I expected the utility to launch 

**Screenshots**
![giterror](https://user-images.githubusercontent.com/116631295/206923739-81684c0e-fe21-4529-9f70-d91ae0a09a57.jpg)

**Additional context**
I have a windows 11 laptop Ryzen 5 gtx 1650ti running 21h2 win11

**Comment by nbodhi** [comment]
I am getting exactly this error message[](url)
![Capture](https://user-images.githubusercontent.com/30353371/207576741-eefb0b80-5243-4250-921c-c6aa9eb851c1.PNG)

**Comment by nbodhi** [comment]
Solution here. https://github.com/ChrisTitusTech/winutil/issues/464

I had the same issue

**Comment by SAHILPANCHOLI** [comment]
I still couldn't figure out the solution but just changing the internet worked for me so would consider this issue solved thanks for the help:}
