### ISSUE TITLE
Invoke-RestMethod : established connection failed

### ISSUE THREAD

**Issue by leelasaiprasanth** [ChrisTitusTech/winutil#512]
**Expected behavior**
Invoke-RestMethod: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Screenshots**
![image](https://user-images.githubusercontent.com/59244101/207026449-b9bb974b-b965-4f0c-a0d8-bf92fad9b4f9.png)

**Comment by kalwani** [comment]
Create an Inbound Rule in WIndows Defender Firewall, TCP port 9418.

**Comment by leelasaiprasanth** [comment]
Thanks for the info, Seems the issue was fixed after the update.

![image](https://github.com/ChrisTitusTech/winutil/assets/59244101/daaca7c4-66d5-42df-b432-d0b1b2bb7dcf)

able to invoke the utility.
