### ISSUE TITLE
Screen capture in Xbox Game bar not working

### ISSUE THREAD

**Issue by l0udsil3nc3** [ChrisTitusTech/winutil#521]
**Describe the bug**
I ran the "laptop" tweaks and now the screen recording in xbox game bar doesn't work, the shortcut does nothing and the option to start recording is faded out. (see screenshot)

**To Reproduce**
1. Press "Win+G" and try to click on the record button.

**Expected behavior**
The capture tool worked as expected before running the script i.e. the default "Win+alt+R" shortcut triggered/stopped the recording.

**Screenshots**
![image](https://user-images.githubusercontent.com/61064155/208255396-641d5661-a668-4691-97f6-721535a12077.png)

**Additional context**

**Comment by UIJohnson** [comment]
I have this same issue, any fix for this?

**Comment by l0udsil3nc3** [comment]
Yes I did!
it's the "disable GameDVR" option that mucked things up

I looked up how to enable it manually via registry changes and everything
works as expected now.

Merry Christmas
