### ISSUE TITLE
Add Support For Installing NVM Instead of latest node versions

### ISSUE THREAD

**Issue by adisonmasih** [ChrisTitusTech/winutil#522]
most of the devs I know don't use a static NodeJS version but use a version manager like [`NVM (NODE VERSION MANAGER)`](https://github.com/nvm-sh/nvm) which is for linux. but for windows, luckily we have a port [`"NVM For Windows"`](https://github.com/coreybutler/nvm-windows).

It would be much better to add a option in the `install` section for this.

Thanks!

**Comment by ChrisTitusTech** [comment]
Dig it, was running into nodejs errors with neovim in windows due to version issues. This is perfect, I'll get this added in #374
