### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by shljsl75891** [ChrisTitusTech/winutil#523]
Dragging a file and dropping in multiple instance of any app on their thumbnail previews brokes.
Their thumbnail hides when I try to drop the dragged file in it. This happens only in Win11. Please fix this issue, as this drag and drop is very needed feature.

**Comment by shljsl75891** [comment]
![image](https://user-images.githubusercontent.com/56100355/208284762-cebda48e-d387-45eb-afb3-c461c6a9654c.png)

**Comment by lightr4in** [comment]
What feature(s) did you use/enable so that the Windows file dragging feature broke?

**Comment by shljsl75891** [comment]
The tooltips hide after I drop a file on any one of the 2 thumbnail previews. I think it changes the delay of showing those previews only in windows 11

**Comment by shljsl75891** [comment]
You can verify it by running tweaks on windows 11 machine and then open two different windows of file explorer and try to drag a file from one window to another window of explorer using taskbar only.
