### ISSUE TITLE
Windows 10 - Snipping tool not working after undoing changes

### ISSUE THREAD

**Issue by nsanchez1980** [ChrisTitusTech/winutil#524]
**Describe the bug**
After undoing the changes, after capturing a portion of the screen (or all, it does not matter) does not open the app that modifies or saves the image

**To Reproduce**
1. Run the script
2. Undo the changes by restoring the configuration
3. Press shift+win+s
4. Capture the screen
5. Nothing happens

**Expected behavior**
Exactly the same as above but 5. Opens the app

**Additional context**
I already tried uninstalling the app and reinstalling it from the windows store, but it still does not work

**Comment by RathX** [comment]
Hey can you help me here? I've got the same issue

**Comment by nsanchez1980** [comment]
Sorry that I didn't leave a comment after closing the issue. In my case, the notifications were disabled (Settings->System), reenabling them restored functionality.
