### ISSUE TITLE
[Feature] Verbose status messages toggle in config

### ISSUE THREAD

**Issue by joser93** [ChrisTitusTech/winutil#526]
Hello.

I just saw a video talking about this topic that allows users to know what is going on when Windows is shutting down, not too verbose like Linux can be, but considerably useful for troubleshoot a system or services that takes too much to stop.

https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/enable-verbose-startup-shutdown-logon-logoff-status-messages

As far as I found in this post from Microsoft, can be enable using a registry key and will be handy to have it in the tool just in case that we need it.

**Comment by Nicholas-R-Sheriff** [comment]
I was about to post the same but fortunately recalled to search before opening a new thread.

Agreed! Having that feature integrated would be awesome!

**Comment by DeveloperDurp** [comment]
#773

**Comment by ChrisTitusTech** [comment]
Merged
