### ISSUE TITLE
Remove all Tiles from Start Menu

### ISSUE THREAD

**Issue by Gh0stBustr** [ChrisTitusTech/winutil#527]
I am a fan of the standard classic start menu that had no tiles at all.

It would be great to have an option in this app to remove all start menu tiles with just one click.

**Comment by devren-y** [comment]
I second this feature request. There is an unpin tiles script in the old [Sycnex Debloater](https://github.com/Sycnex/Windows10Debloater) which has not been maintained in a few years... I just tried to run it in the latest Windows 10, and it does not seem to work any more.  I am not savvy enough in powershell to have any idea why.
