### ISSUE TITLE
Remove Folders from This PC

### ISSUE THREAD

**Issue by Gh0stBustr** [ChrisTitusTech/winutil#528]
I never found any use for the additional folders in This PC.
I go there to access my drives and partitions only.

These can all be removed with the following registry magic.
I have to keep this in a separate script for myself but it would be great to have it part of this "one stop shop" app:

Windows 10: Remove folders from ThisPC: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\<FOLDER-GUID>\PropertyBag
		Desktop: {B4BFCC3A-DB2C-424C-B029-7FE99A87C641}
		Documents: {f42ee2d3-909f-4907-8871-4c22fc0bf756}
		Downloads: {7d83ee9b-2244-4e70-b1f5-5393042af1e4}
		Music: {a0c69a99-21c8-4671-8703-7934162fcf1d}
		Pictures: {0ddd015d-b06c-45d5-8c4c-f59713854639}
		Videos: {35286a68-3c57-41a1-bbb1-0eae73d76c95}
Under each one’s "PropertyBag" key, you’ll see a string value named "ThisPCPolicy". Change its value to "Hide"

**Comment by ChrisTitusTech** [comment]
I agree, but the main issue is it will freak normal users out when their documents or desktop quick access links disappear. Can't add this for everyone sadly.
