### ISSUE TITLE
Disable Animations

### ISSUE THREAD

**Issue by Gh0stBustr** [ChrisTitusTech/winutil#529]
In order to make Windows feel more snappy I always disable animations.

This app aiming to be a "one stop shop" for doing all good tweaks to Windows it would be nice to have this as one of the checkboxes under tweaks.

**Comment by DeveloperDurp** [comment]
I believe "Set Display for Performance" does this

**Comment by Gh0stBustr** [comment]
It didn't do it for me on a full clean USB install of the latest Windows 10. 
I had to change it manually by hand.

**Comment by DeveloperDurp** [comment]
Perhaps I am thinking of a different option, can you post a screen shot of what you do manually?

**Comment by Gh0stBustr** [comment]
Please find a photo of this setting attached here:

![show-animations-in-windows](https://user-images.githubusercontent.com/74185358/209691079-5e76bd62-856d-48e5-835d-fb0865036b7d.png)

**Comment by LouKordos** [comment]
Hi, has this been fixed?
