### ISSUE TITLE
Feature Request: Multiple Things

### ISSUE THREAD

**Issue by Carterpersall** [ChrisTitusTech/winutil#53]
**Context**
This is where I will be keeping track of the transfer of my pull requests from ChrisTitusTech/win10script to here along with other features I'm working on. Feel free to comment with input or recommendations or even an idea for another feature.

**Checklist**
- [ ] More work on improving Formatting and Grammar
- [x] Fix Network Data Usage/Task Manager network usage bug 
   - ChrisTitusTech/win10script#319
   - The ndu service has something to do with it, but there is something else causing issues as well that I need to track down
- [x] Allow custom OOShutup10 configs
   - ChrisTitusTech/win10script#321
   - Add if-statement that checks if ooshutup10.cfg exists, if it does then does nothing, if it doesn't then it downloads it. This allows users to put their own preset into the script root directory and not be overridden.
   - #298
- [x] Fix bug on non-default system drives
   - ChrisTitusTech/win10script#322
   - Replace any reference to C:\ with `$env:SystemDrive` to prevent issues on non-default system drives
- [x] More work on winget manual install
   - Add check if DesktopAppInstaller is installed at all, and perform manual install if it isn't as the modern method does not work when it doesn't exist
- [x] Fix Test-Path Bug in `$undotweaks`
   - ChrisTitusTech/win10script#327
   - It seems that when `$undotweaks` was initially written, the Test-Paths in the if-statements didn't have the `!` removed from them, making it that the items were removed if the command found that it didn't exist, which is not the intended behavior.
- ~Bring back restore power plan~
   - ChrisTitusTech/win10script#328
   - ~Bring back the restore power plan section with some changes to prevent duplication of power plans~
   - Power plan section of the script was removed
- [x] Create Known Issues Page
   - ChrisTitusTech/win10script#332
   - Will contain a compilation of known possible issues and their fixes
   - Hopefully would reduce the number of issues posted
   - Need to update issue links as they are from the previous script
     - #297 
- [x] Fix Xbox Live Bug
   - ChrisTitusTech/win10script#336
   - Removing Xbox Identity Provider breaks Xbox Live games like Minecraft UWP
- [x] Disable built-in admin account
   - ChrisTitusTech/win10script#338
   - Will need to check to make sure the current user isn't the built-in admin account
- [x] Install gpedit.msc on Windows Home using DISM
   - ChrisTitusTech/win10script#338
- [ ] Use gained knowledge from optimizing [winfetch](https://github.com/kiedtl/winfetch) to improve some speed throughout the script
   - No need to go super in-depth as speed isn't a major concern in this script
- [ ] Maybe: ~Reverse engineer WingetUI~ and reimplement in Winforms
   - Found another thing that converts Winget's output to an array of objects, so I grabbed it and fixed a bunch of bugs
     - Should work for what I want
     - [Carterpersall/Experiments/Powershell/winget/Winget to object.ps1](https://github.com/Carterpersall/Experiments/blob/main/PowerShell/winget/Winget%20to%20object.ps1)

**Comment by ChrisTitusTech** [comment]
Thanks for this, I'm working through these issues now.

**Comment by Carterpersall** [comment]
No problem, I've been mostly waiting for things to clear up regarding the major restructure of the script before I implemented many of these.

**Comment by DeveloperDurp** [comment]
@Carterpersall feel free to implement, runspaces need a lot more stability improvements so I will find a way to port over any changes as it gets more stable.

**Comment by padsalatushal** [comment]
@DeveloperDurp i am working on many features. should I make change in old script without runspace or I make change in runspace script ?

**Comment by DeveloperDurp** [comment]
@padsalatushal Keep working on the old script, i'll figure out a way to port over any changes as the runspaces get more stable

**Comment by drcfilho** [comment]
Hi,

Would you have the option of creating translations for your script? and we can use a switch to call the specific version of the language? example: -ptbr would call the Brazilian Portuguese version. -ru, Russian version? and so on.

**Comment by Carterpersall** [comment]
It seems that the task manager network bug was fixed when I did an in-place upgrade to 22H2 on my laptop (which nuked a lot of my registry modifications), which has allowed me to test if the script is still causing the issue in a VM. After testing, I have concluded that the script no longer causes the task manager network monitoring bug.

**Comment by ChrisTitusTech** [comment]
> It seems that the task manager network bug was fixed when I did an in-place upgrade to 22H2 on my laptop (which nuked a lot of my registry modifications), which has allowed me to test if the script is still causing the issue in a VM. After testing, I have concluded that the script no longer causes the task manager network monitoring bug.

Thanks for testing Carter!
