### ISSUE TITLE
Bug: Ultimate Performance shows  twice on list. Cannot remove it

### ISSUE THREAD

**Issue by wsbrock1953** [ChrisTitusTech/winutil#534]
**Describe the bug**
Windows 10 on an HP Laptop.
I turned on Ultimate Performance before I re-watched the video and found out I don't want to use it on my laptop.
My laptop is docked but I get your point about power consumption.
I may have run the install on this feature a second time? not sure.
I tried to remove Ultimate Performance option but I is still there.
See attached.
**To Reproduce**
1.  Ran the tool
2. Clicked on Remove Ultimate Performance Profile.
3. shell window shows:
=====Windows Toolbox=====
Removing Ultimate Performance Profile
The power scheme, subgroup or setting specified does not exist.
Profile Removed
4. Rebooted system

**Expected behavior**
I should no longer see the Ultimate Power option.

**Screenshots**
see attached

**Additional context**
![UltimatePerformance](https://user-images.githubusercontent.com/69096363/209218631-e773102a-9a80-41e7-bd61-442b94520be5.JPG)

**Comment by ChrisTitusTech** [comment]
This was fixed
