### ISSUE TITLE
Windows Appinstaller not found

### ISSUE THREAD

**Issue by mrg9999** [ChrisTitusTech/winutil#535]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

Checking if Winget is Installed...TT            TTTTTTTTTTT
Winget not found, installing it now.
Get-Process : Cannot find a process with the name "AppInstaller". Verify the process name and call the
cmdlet again.Toolbox=====
At line:236 char:25
+                 $nid = (Get-Process AppInstaller).Id
+                         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppInstaller:String) [Get-Process], ProcessCommandExcepti
   on
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand

Wait-Process : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At line:237 char:34
+                 Wait-Process -Id $nid
+                                  ~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WaitProcess
   Command

Winget Installed

**Comment by ChrisTitusTech** [comment]
Just had a new PR #543 that looks to make this more reliable. I'm also going to add some redundancy to chocolatey for when winget is not available.
