### ISSUE TITLE
Bug: Power Throttling Issues on Laptop - Remove Option

### ISSUE THREAD

**Issue by Ricsikakas3** [ChrisTitusTech/winutil#536]
**Describe the bug**
I ran the recommended tweaks for laptops + disabling throttling because i wanted my laptops full capacity and since i ran the script my internet has been sluggish, connecting to sites slow, download speed and latency didnt change though. 
Undo Tweaks didn't help fix the problem

**To Reproduce**
1. Go to the tweaks section
2. Click on laptop tweaks, disable power throttling
3. Run the script
4. Enjoy your weird and slow internet

**Expected behavior**
I expected my laptop to be debloated and nothing to get worse.

**Additional context**
My laptop is the Asus Strix G15 Advantage Edition.

**Comment by ChrisTitusTech** [comment]
I highly recommend NOT to disable throttling on a laptop. Just use Ultimate performance via power plan if that is your intent. 

I'm going to remove the power throttling option as it has some funky side effects.
