### ISSUE TITLE
Full Screen games/programs Screen Blikning / Turns Off / Freezing when Alt+Tab

### ISSUE THREAD

**Issue by Oskicz** [ChrisTitusTech/winutil#539]
**Describe the bug**
When i click Alt + Tab My screen blinks (Like Turn Off Screen) Not black screen, and freezing for like 10 seconds and sometimes even crashing game

My Monitor is 1920x1080 60hz In game this same settings 1920x1080 60hz (In windows 60hz no 59hz)

I was trying to uninstall tweaks i click on undo tweaks because it not created the restore point even that i selected "Create Restore Point" Undo not repair anything

I use everythink from https://github.com/ChrisTitusTech/winutil/issues/122 But still nothing changed

I cant reinstall windows so please help..

**To Reproduce**
1. Go to 'Any FullScreen game like LoL, Valorant'
2. Go to settings in game and set "FullScreen"
3. Click on 'Alt - Tab'

**Expected behavior**
Fast normall alt + tab and no crashes

**Screenshots**
I cant record / screenshot screen just turns off for like 10 secounds xD

**Additional context**
I was trying on other monitor im getting this same Before tweaks working!

**Comment by ChrisTitusTech** [comment]
The last time I saw this was from a bad commit back in the fall of 2022. I added this snippet that resolved it. If you haven't re-run the tweaks you might check to make sure these these commands are run:
```
## Timeout Tweaks cause flickering on Windows now
            Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "WaitToKillAppTimeout" -ErrorAction SilentlyContinue
            Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "HungAppTimeout" -ErrorAction SilentlyContinue
            Remove-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control" -Name "WaitToKillServiceTimeout" -ErrorAction SilentlyContinue
            Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "LowLevelHooksTimeout" -ErrorAction SilentlyContinue
            Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "WaitToKillServiceTimeout" -ErrorAction SilentlyContinue
```
