### ISSUE TITLE
Saved Configuration

### ISSUE THREAD

**Issue by w8n41** [ChrisTitusTech/winutil#541]
The application does not record the settings for configurations and software installed that can be recalled on the next run. As far as software selection goes it could do a scan of the computer to determine which applications are present.

**Comment by ChrisTitusTech** [comment]
Sadly this is a limitation of winget at this time. As soon as we can I'll implement this though!

**Comment by jhgorse** [comment]
Chris,

How so? What is needed to build the manifest for all of the capability of the tool that has been used? Could we not take the actions of the user and record it as it is executed, transactionally?

Cheers,
Joe

**Comment by ChrisTitusTech** [comment]
> Chris,
> 
> How so? What is needed to build the manifest for all of the capability of the tool that has been used? Could we not take the actions of the user and record it as it is executed, transactionally?
> 
> Cheers,
> Joe

Yes we can and do, but winget doesn't have a function to detect what is installed already.
