### ISSUE TITLE
Bug: Exclude vgc service from being set to Manual - Valorant Anti-Cheat

### ISSUE THREAD

**Issue by thesuperbob49** [ChrisTitusTech/winutil#545]
On my PC, I run Valorant. That software depends on the vgc service (also known as Vanguard, an anti-cheat service ). Without this service running in the background, I cannot play Valorant. After running the command to set services to Manual startup type, it put that service to manual startup. Can it be set so the routine does not mess with the vgc service? It needs to bet set to automatic so the application can run correctly.

Thanks!

**Comment by ChrisTitusTech** [comment]
Thanks for the report, I'll get this switched in the next update!

**Comment by ChrisTitusTech** [comment]
The tweaks won't touch the vgc service and not included in the toolbox.
