### ISSUE TITLE
Feature Request: Cleaner SilentlyContinue via PowerShell

### ISSUE THREAD

**Issue by ghost** [ChrisTitusTech/winutil#546]
this is my first time using github, so this is probably the wrong way to do this, but by adding:

$ProgressPreference = "SilentlyContinue"

...to the top of the .ps1 scripts, will remove the blue-highlighted progress text during execution of scripts. makes it look cleaner imo, and allows more readability for the output text you want the user to see.

**Comment by ChrisTitusTech** [comment]
Awesome Thanks for the comment. I'll get this added in the next update!
