### ISSUE TITLE
Unable to start the script

### ISSUE THREAD

**Issue by Anexgohan** [ChrisTitusTech/winutil#547]
**Unable to start the script**
on a fresh windows 10 install

**Issue and error**
I ran this:
```
PS C:\WINDOWS\system32> iwr -useb https://christitus.com/win | iex
```
and got this result
```
iwr : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

**How should I resolve this**
I tried also but it did not help
```
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')
```
![powershell_csG0EjM5TG](https://user-images.githubusercontent.com/38262052/210129799-b3b9e0cd-ba54-452a-91dc-45f8c6bc4427.png)

[**Screenshots**](https://i.imgur.com/VkhpViO.png)

**Comment by ChrisTitusTech** [comment]
These are always DNS issues, don't know why, but some users can't resolve raw github URLs. Changing the DNS to 1.1.1.1 or 8.8.8.8 solves this.

**Comment by Anexgohan** [comment]
Ok it turns out raw.githubusercontent.com is banned just a week back in my country, due to a legal issue, si the ISP here is routing the IP of raw.githubusercontent.com to some non-functioning address,
I changed the windows "hosts" file located in 
C:\Windows\System32\drivers\etc
and added 
185.199.108.133 raw.githubusercontent.com

used the tool again, no reboot was needed and it worked perfectly
