### ISSUE TITLE
Winget still fails. Script needs more checking

### ISSUE THREAD

**Issue by mrg9999** [ChrisTitusTech/winutil#548]
Windows 11 version  - Fairly fresh install on a new computer
Version 22H2 (0S Build 22621.963)

I invoke the script using Powershell (Terminal) admin as recommended  using (from README.MD)
iwr -useb https://christitus.com/win | iex

Toolbox tries to install winget says it has but clearly hasn't

=====Windows Toolbox=====
Checking if Winget is Installed...
Winget not found, installing it now.
Get-Process : Cannot find a process with the name "AppInstaller". Verify the
process name and call the cmdlet again.
At line:236 char:25
+                 $nid = (Get-Process AppInstaller).Id
+                         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppInstaller:String) [Get-Proce
   ss], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.
   Commands.GetProcessCommand

Wait-Process : Cannot validate argument on parameter 'Id'. The argument is
null or empty. Provide an argument that is not null or empty, and then try the
command again.
At line:237 char:34
+                 Wait-Process -Id $nid
+                                  ~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-Process], ParameterBindin
   gValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Power
   Shell.Commands.WaitProcessCommand

Winget Installed

^^^^^^^^^^^
NO IT ISN'T 
////

**Comment by ChrisTitusTech** [comment]
Just had a new PR #543 that looks to make this more reliable. I'm also going to add some redundancy to chocolatey for when winget is not available.
