### ISSUE TITLE
Feature Request: chocolatey switch when installing programs

### ISSUE THREAD

**Issue by Git-North** [ChrisTitusTech/winutil#549]
As far as I can tell Chocolatey is used when WinGet does not work or just not available,,

However it would be really nice if we had a little switch for when we wanna use winget or chocolatey

I personally prefer chocolatey because it is more of a package manager then Winget I also like keeping all my programs in one place

**Comment by DeveloperDurp** [comment]
it's pure winget currently, choco is in the works and the idea is having the ability to switch between the package managers.

**Comment by Git-North** [comment]
Exactly what I was thinking of
