### ISSUE TITLE
Feature Request: Add Block Razor script

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/winutil#550]
Add script from https://christitus.com/block-razer-bloatware/

**Comment by DeveloperDurp** [comment]
Make sure to use [System.Net.WebClient] instead of Invoke-RestMethod or @Carterpersall will be disappointed in the performance lol.

![image](https://user-images.githubusercontent.com/74198206/210468146-1c73ea90-433b-4515-b71e-a98900303703.png)
