### ISSUE TITLE
Tweaks Section - Disable Windows 11 Widgets or Windows 10 NewsAndInterests

### ISSUE THREAD

**Issue by mxzgithub** [ChrisTitusTech/winutil#555]
Enable / Disable the Widgets and News in Windows 10 and 11.

**Describe the solution you'd like**
To disable Widgets use the following Powershell commands:
Set-ItemProperty -Path HKCU:SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name TaskbarDA -Value 0
Set-ItemProperty -Path HKLM:SOFTWARE\Policies\Microsoft\Dsh -Name AllowNewsAndInterests -Value 0
To enable switch value to 1.

**Describe alternatives you've considered**
The easiest way to disable widgets permanently is via gpedit.msc but as far as i know there is no way to do edit local GPO via powershell.
Maybe a professional knows more.

**Additional context**
Widgets has at least 6 Processes running at all times, so better disable it if you do not use it.

**Comment by n8x0b7T** [comment]
I believe this can be uninstalled with winget. 

```
winget uninstall "windows web experience pack"  --accept-source-agreements
```
I have not fully tested this, but it seems to be a good approach in a addition to the registry key change.
This would be a nice addition under the tweaks tab.
