### ISSUE TITLE
Just had a new PR #543 that looks to make this more reliable. I'm also going to add some redundancy to chocolatey for when winget is not available.

### ISSUE THREAD

**Issue by mrg9999** [ChrisTitusTech/winutil#557]
Just had a new PR #543 that looks to make this more reliable. I'm also going to add some redundancy to chocolatey for when winget is not available.

_Originally posted by @ChrisTitusTech in https://github.com/ChrisTitusTech/winutil/issues/535#issuecomment-1368985860_

Admittedly, I'm 99% a *nix guy and   I either use a package manager or install a .deb file. Why is this so hard on Windows? Can't I have say an MSI installer of Winget so I can keep it and install it at will?

again today I tried this. It would help if you could tell me why it fails. How about "choco install winget"??

iwr -useb https://christitus.com/win | iex
Chocolatey Version 1.2.1 is already installed

    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T
C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====

Winget
PS>winget
winget : The term 'winget' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFo
   undException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DeveloperDurp** [comment]
winget doesn't behave like a package manager in Linux which is the reason we have a lot of weird issues. Ultimately it's pulling either an exe or msi installer from a location and running the necessary arguments to install it. 

As for why you are unable to run winget manually even is curious. What OS version are you on? You might be able to fix it by manually installing winget through the Microsoft Store.
