### ISSUE TITLE
Add PeaZip as alternative to 7-Zip

### ISSUE THREAD

**Issue by S4IVin** [ChrisTitusTech/winutil#559]
**Is your feature request related to a problem? Please describe.**
7-Zip is great, but the UI is really deprecated and doesn't match the Windows UI anymore.

**Describe the solution you'd like**
There is a great alternative called PeaZip, a 7-Zip fork with a renewed UI and other cool things. I hope you could add that, since it's avaible on WinGet.

**Comment by ChrisTitusTech** [comment]
Peazip is amazing, put it in #374 to get added next update
