### ISSUE TITLE
simplewall

### ISSUE THREAD

**Issue by Vildis** [ChrisTitusTech/winutil#56]
[Simplewall](https://github.com/henrypp/simplewall) is an open source firewall program that uses the Windows Filtering Platform to block internet access for applications.

I'd like for simplewall to be added into the install menu

**Alternatives**
[Portmaster](https://github.com/safing/portmaster/) could be an alternative to simplewall, but it is in the alpha phase.
[Tinywall](https://tinywall.pados.hu/) is another alternative which isn't open source. I also consider the UI to be a bit cluttered and outdated.

**Comment by Rasinzz** [comment]
Probably better to post this in the **Discussions** section as this is not an issue.

**Comment by Carterpersall** [comment]
@Rasinzz Personally this is the right place as it is a feature request for the script itself. I think discussions are better suited for requests and discussions on things not in the script (Branches, Workflow, General Discussions). That is also supported by the Feature Request issue template provided when one creates an issue.

**Comment by Rasinzz** [comment]
> @Rasinzz Personally this is the right place as it is a feature request for the script itself. I think discussions are better suited for requests and discussions on things not in the script (Branches, Workflow, General Discussions). That is also supported by the Feature Request issue template provided when one creates an issue.

Yeah I see where you're cumming from just saw some suggestions already posted in Discussions.

**Comment by ChrisTitusTech** [comment]
Added in #240 - Closing Issue
