### ISSUE TITLE
question and add features

### ISSUE THREAD

**Issue by GHOSTS15** [ChrisTitusTech/winutil#561]
add that you can set multiple languages (translations please do them with " deepl" not google translator which sucks).

if I download the "everything" tool from the script is it installed without bloatware, without trelemetry , with marketing purpose disabled and then just the program without things that can compromise privacy or anything else?

**Comment by ChrisTitusTech** [comment]
I'll see about adding languages in the future, but I want to get it to a less active development state before doing so.

As far as everything this is installed with default settings from winget. I'd assume telemetry is enabled.
