### ISSUE TITLE
Error when Disabling Telemetry in Windows 11 (Latest Win 11 Pro ISO from January 2022)

### ISSUE THREAD

**Issue by johntdavis84** [ChrisTitusTech/winutil#562]
**Describe the bug**
After selecting "Desktop" mode and applying the tweaks, the script threw an error (show below) on "Disabling Telemetry," but otherwise completed without issue.

> Disabling Telemetry...
> Disable-ScheduledTask : The system cannot find the file specified.
> At line:577 char:13
> +             Disable-ScheduledTask -TaskName "Microsoft\Windows\Applic ...
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Disable-ScheduledT
>    ask], CimException
>     + FullyQualifiedErrorId : HRESULT 0x80070002,Disable-ScheduledTask

The ellipsis was there in the original. I'm not exactly sure what it was trying to remove there...

**To Reproduce**
1. Run script in admin mode;
2. Select "Desktop" mode (ensure Disable Telemetry is selected).
3. Apply Tweaks.

**Expected behavior**
I assume there should have been no feedback at all here. All the other "Disable..." statements succeed quietly.

**Screenshots**
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/26333538/211174662-ae30cf73-5f9f-4604-88dd-be99ee333778.png">

**Comment by ChrisTitusTech** [comment]
Addition checks are made so you won't see these messages
