### ISSUE TITLE
Error on: "Restricting Windows Update P2P only to local network..."

### ISSUE THREAD

**Issue by johntdavis84** [ChrisTitusTech/winutil#563]
**Describe the bug**
When executing this part of the script under Desktop mode, error received complaining of missing registry key.

**To Reproduce**
1. Select "Desktop" Tweaks.
2. Apply Tweaks.
3. Check console log for errors.

**Expected behavior**
Setting to succeed without any feedback.

**Screenshots**
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/26333538/211174735-d9df5df1-793e-4104-ae91-6b2d476a74d3.png">

**Additional context**
Please let me know what additional information might be helpful.

This is an Odroid H3+ SBC with a Pentinum Silver N6005, running Windows 11 Pro based on the current latest ISO image installer.

**Comment by ChrisTitusTech** [comment]
Added more error checks so this won't happen
