### ISSUE TITLE
Applications not appearing in Start Menu search results after "Run OO Shutup" tweak

### ISSUE THREAD

**Issue by cinaeco** [ChrisTitusTech/winutil#569]
After running the abovementioned tweak, newly installed applications do not show up in the start menu search, even though Start menu entries exist.

**To Reproduce**
1. Perform clean install of Windows 10 22H2
2. Install 7zip from downloaded installer. Install Spotify from MS Store.
3. Open Start menu and search. 7zip/Spotify appear in search results as expected.
4. Uninstall 7-zip/Spotify.
5. Download winutil.
6. Run "Run OO Shutup" tweak.
7. Install applications again.
8. Open Start menu and search. 7zip/Spotify do NOT appear in search results.

**Expected behavior**
Apps installed after winutil tweaks should appear in Start Menu search results.
The configured shutup tweak either needs to not break the Start menu searching for local apps, or there should be an explicit warning stating that it does (like the warnings on the other tweaks).

**Comment by oliverhoerberg** [comment]
The same thing happens for me. Undoing the tweaks doesn't seem to make the apps appear in the search again either.

**Comment by leo-jolibois** [comment]
I'm having the same issue, it would be good to know which option can be changed in O&O Shutup to fix it.

**Comment by RehanPlayz** [comment]
I'm also having the exact same issue

**Comment by RehanPlayz** [comment]
> i was able to use the search function again by installing the O&O ShutUp10++ app, then undo all changes ("factory settings"), and then Apply only recommended settings.

This seems to work for me too

**Comment by Aquitano** [comment]
> i was able to use the search function again by installing the O&O ShutUp10++ app, then undo all changes ("factory settings"), and then Apply only recommended settings.

That worked for me as well.

**Comment by dreamsyntax** [comment]
Also adding this. I can reproduce this most times.
Interestingly, does not always happen though.

**Comment by dreamsyntax** [comment]
Just tested the 23.07.2020 version, and this issue still persists on a clean Win 10 22H2 install.

Running OOShutup manually and turn off "Prohibit apps from running in the background" under Current User > App Privacy
Then rebooting restores proper installed app search functionality.

Note you may want to go to Windows Settings > Privacy > Background apps and uncheck individual apps. 'Settings' seems to control if Search can properly index app installations.

**Comment by ChrisTitusTech** [comment]
Thanks for double checking, I added a new commit cd586b3
that updates the o&o cfg to leave app background enabled
