### ISSUE TITLE
Remove all Microsoft Store Apps is Not working

### ISSUE THREAD

**Issue by rafay99-epic** [ChrisTitusTech/winutil#57]
**Describe the bug**
hen you click the config button and then select the Remove all MS store apps then It will start for a min but the complete stuck for a while and then when you look at the PowerShell terminal there are multiple error:

**To Reproduce**
1. Go to 'congif Button '
2. Click on 'Remove all MS Apps and Set time for Dual Boot'
3. Click Run Tweaks
4. See error: Error in the Screenshots

**Expected behavior**

**Screenshots**
1. Select Option

![Screenshot (6)](https://user-images.githubusercontent.com/82662797/170111019-87c6ed09-1058-4add-91db-46fa7b524dca.png)

2. Errors: 
 
![Screenshot (1)](https://user-images.githubusercontent.com/82662797/170111030-90263958-5420-403d-b7ff-b2068a7c28a6.png)

![Screenshot (2)](https://user-images.githubusercontent.com/82662797/170111036-dd400e51-c7cc-414d-abb0-0bccdd1de3fb.png)

![Screenshot (3)](https://user-images.githubusercontent.com/82662797/170111042-af3cc02b-888f-4c87-9e38-ef4d7eca7abd.png)

![Screenshot (4)](https://user-images.githubusercontent.com/82662797/170111048-7c9fbb75-4352-4b76-b12a-63fffb0e970f.png)

![Screenshot (5)](https://user-images.githubusercontent.com/82662797/170111055-911ab134-393d-4b74-82b5-04a5b2b6ccd3.png)

**Additional context**
I stopped the program from task master but I think the program have disturbed the time setting on my system. I am using window 11.

**Comment by Kushal-Chandar** [comment]
Try running in "**Windows Powershell**" as administrator

**Comment by rafay99-epic** [comment]
I have....I was running PowerShell as administrator. But still the issue is not solved.

**Comment by Kushal-Chandar** [comment]
You are running in Powershell 7 (cross-platform)
![programs](https://user-images.githubusercontent.com/83660514/173554755-c76cbac3-251a-47c3-8768-cde3cad6f9a6.png)


I encountered this when trying to write my own script, Import Appx-Module not supported on powershell 7 (cross platform version)


Powershell 7 (cross-platfrom)
![image](https://user-images.githubusercontent.com/83660514/173556445-1855e7c3-3a30-4ef8-a584-365cc3042871.png)

Windows Powershell (native windows)
![image](https://user-images.githubusercontent.com/83660514/173557305-6ffe8066-083f-4c71-ab48-160d2518e461.png)

**Comment by rafay99-epic** [comment]
Okay, I got it now. I will run applications using the PowerShell Window component.
