### ISSUE TITLE
Can you add it ?

### ISSUE THREAD

**Issue by KOX599** [ChrisTitusTech/winutil#572]
Add 
DirectX 
https://www.microsoft.com/en-us/download/details.aspx?id=8109
Desktop Runtime .NET 7.0
https://dotnet.microsoft.com/en-us/download/dotnet
Autoruns
https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns
MSI_util_v3
https://forums.guru3d.com/threads/windows-line-based-vs-message-signaled-based-interrupts-msi-tool.378044/
gpedit

@echo off 
pushd "%~dp0" 
dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientExtensions-Package~3*.mum >%TEMP%\temp.txt 
dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientTools-Package~3*.mum >>%TEMP%\temp.txt 
for /f %%i in ('findstr /i . %TEMP%\temp.txt 2^>nul') do dism /online /norestart /add-package:"%SystemRoot%\servicing\Packages\%%i" 
pause

nvidia profile inspector 
https://nvidiaprofileinspector.com/download-nvidia-profile-inspector/

Power plan
[_Power Plans.zip](https://github.com/ChrisTitusTech/winutil/files/10411625/_Power.Plans.zip)

sorry he wants to add so many things

**Comment by ChrisTitusTech** [comment]
Adding #374
