### ISSUE TITLE
"Upgrade Installs" Updates VLC to nightly build 4.0

### ISSUE THREAD

**Issue by Garou7** [ChrisTitusTech/winutil#573]
I really like "Upgrade Installs" but bcoz of VLC, I have to downgrade VLC to stable 3.0.18 every time when I use this feature.
![JpyjaqsCJV](https://user-images.githubusercontent.com/113905482/212477998-1add8d73-9c70-470f-b507-e4ced9bda529.png)
![VBFRQgunPz](https://user-images.githubusercontent.com/113905482/212478001-f4105846-fbd0-4d78-8e19-27c7f463c8f6.png)

**Comment by ChrisTitusTech** [comment]
This was a bug with microsoft's winget, but has been patched by them. It won't do this anymore.
