### ISSUE TITLE
Windows Services Processes

### ISSUE THREAD

**Issue by PikaZone** [ChrisTitusTech/winutil#574]
I would like to see a button or something i can click to stop or remove the services on my computer that i don't need. for example someone who doesn't know what is ok to stop and leave on and running to get those process down without breaking windows completely but to get down to a minimal process and still keep the security aspect. Basically make it idiot proof lol.

**Comment by ChrisTitusTech** [comment]
This is added and have been tweaking it for a normal user. 

![image](https://github.com/ChrisTitusTech/winutil/assets/7896101/512d1214-306a-45da-9304-58c6100cf212)
