### ISSUE TITLE
Unable to connect to the address.

### ISSUE THREAD

**Issue by systemcoding** [ChrisTitusTech/winutil#579]
I ran the command to open winutil tool as described in the **[Blog](https://christitus.com/debloat-windows-10-2020/#april-2022-update)**. I waited for the command to connect and I see this error:

```
iwr : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

I've never seen this issue before and seems like other computers that I tested also showed the same issue. What is the problem? It's been bugging me and seems like there is no fix for this

**Comment by AISLVE** [comment]
Set up a proxy and then try again(I recommend 1.1.1.1) after restarting

**Comment by cmwg71** [comment]
previously working fine, but since today URL not found (checked manually https://christitus.com/win and get 404, also from two completely different internet connections)

**Comment by cmwg71** [comment]
works again for me

**Comment by Gameman360** [comment]
> Set up a proxy and then try again(I recommend 1.1.1.1) after restarting

how do you do that?

**Comment by AISLVE** [comment]
Install cloudfare warp on your pc and u will be good to go

**Comment by AISLVE** [comment]
Search for it on ur browser
