### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Goten87** [ChrisTitusTech/winutil#58]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
in the first tool there was a button dark mode and light mode can we get it back please

**Describe alternatives you've considered**
Using the old tool

**Additional context**
when you dont activate windows i dont think you can change the dark or light mode so its locked on light mode
so i use the tool in my VM to set it to darkmode will be nice if the new tool can do that to

**Comment by ChrisTitusTech** [comment]
Didn't think about that. I'll add it back

**Comment by ChrisTitusTech** [comment]
Added in #240 - Closing Issue
