### ISSUE TITLE
You need a newer app to install this program

### ISSUE THREAD

**Issue by mrg9999** [ChrisTitusTech/winutil#581]
System
Windows 11 professional  10.0.22621
22H2

**Describe the bug**
irm christitus.com/win | iex
Select edge 
click Install

**To Reproduce**
run script from PS multiple times

**Expected behavior**
I expect edge to be installed

**Screenshots**
Winget Installed
Microsoft.Edge

=================================
---  Installs are Finished    ---
=================================
Transcript stopped, output file is C:\Users\gerald-l\AppData\Local\Temp\Winutil.log                                                                             PS C:\Users\gerald-l\Documents\binw> irm christitus.com/win | iex               Transcript started, output file is C:\Users\gerald-l\AppData\Local\Temp\Winutil.log
Chocolatey Version 1.2.1 is already installed

    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T
C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
Checking if Winget is Installed...
Winget not found, installing it now.
Get-Process : Cannot find a process with the name "AppInstaller". Verify the
process name and call the cmdlet again.
At line:236 char:25
+                 $nid = (Get-Process AppInstaller).Id
+                         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppInstaller:String) [Get-Proce
   ss], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.
   Commands.GetProcessCommand

Wait-Process : Cannot validate argument on parameter 'Id'. The argument is
null or empty. Provide an argument that is not null or empty, and then try the
command again.
At line:237 char:34
+                 Wait-Process -Id $nid
+                                  ~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-Process], ParameterBindin
   gValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Power
   Shell.Commands.WaitProcessCommand

Winget Installed
Microsoft.Edge

=================================
---  Installs are Finished    ---
=================================

**Comment by dennyamarojr** [comment]
It seems. you're having a problem with Winget which is not installed in the system. Watch this video from chris: https://www.youtube.com/watch?v=__2_41pVHcQ

**Comment by dennyamarojr** [comment]
When you install winget, just back to winutil and try again install Edge.

**Comment by mrg9999** [comment]
Winget install gives the same message. Chocolatey works fine, but no installation of edge for Chocolatey .

**Comment by dennyamarojr** [comment]
Oh I see, check if the winget is on the environment variables in windows, if is not there, you will need to add it.

Go to Settings>System>About>Advanced system settings>Environment Variables
Check if the "Path" has %userprofile%\AppData\Local\Microsoft\WindowsApps in User and System variables. If not, add this to the path
![image](https://user-images.githubusercontent.com/36896116/213572130-d11e1332-76bf-4b63-85b7-b32cb6657b2f.png)
![image](https://user-images.githubusercontent.com/36896116/213572467-3e8cf078-e1aa-44c1-9874-96e00187f70b.png)

Add %USERPROFILE%\AppData\Local\Microsoft\WindowsApps to Path variable.

**Comment by dennyamarojr** [comment]
Source: https://github.com/microsoft/winget-cli/discussions/1738

**Comment by mrg9999** [comment]
I didn't think %userprofile% worked I thought it had to be expanded to c:\users\<name>\...
This is what mine currently are

![2023-01-20 - System env](https://user-images.githubusercontent.com/7822877/213602226-fe827d52-5144-415c-8138-4d6109a02a7d.jpg)
![2023-01-20 - User env](https://user-images.githubusercontent.com/7822877/213602229-67f1bc28-cbbb-46cb-8265-ac48507040f7.jpg)

**Comment by dennyamarojr** [comment]
> I didn't think %userprofile% worked I thought it had to be expanded to c:\users<name>... This is what mine currently are
> 
> ![2023-01-20 - System env](https://user-images.githubusercontent.com/7822877/213602226-fe827d52-5144-415c-8138-4d6109a02a7d.jpg) ![2023-01-20 - User env](https://user-images.githubusercontent.com/7822877/213602229-67f1bc28-cbbb-46cb-8265-ac48507040f7.jpg)

It seems that is everything fine, did you update App Installer in Microsoft Store?

**Comment by mrg9999** [comment]
It's working again

$PS>.\winget.ps1 : File winget.ps1 cannot be loaded because    running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170. 
At line:1 char:1 + .\winget.ps1 + ~~~~~~~~~~~~
+ CategoryInfo: SecurityError: (:) [], PSSecurityException + FullyQualifiedErrorId : UnauthorizedAccess                                
 
# I entered this 
$PS> ### Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
# invoke script again
$PS>\temp\winutil-main> .\winget.ps1 

NuGet provider is required to continue PowerShellGet requires NuGet provider version '2.8.5.201' 
or newer to interact  with NuGet-based repositories. The NuGet provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or C:\users\scripts\AppData\Local\PackageManagement\ProviderAssemblies'. 
You can  also install the NuGet provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. 
Do you want PowerShellGet to install and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y                      ###################################                                             
# Downloading Xaml nupkg file... (19000000ish bytes)                            ###################################                                             ###################################                                             
# Extracting appx file from nupkg file...                                       ###################################                                             ###################################                                             
# 64-bit OS detected                                                            ###################################                                             ###################################                                             
# Downloading & installing x64 VCLibs... (21000000ish bytes)                    ###################################                                             ###################################                                             
# Installing x64 XAML...                                                        ###################################                                             ###################################                                             
# Downloading winget... (21000000ish bytes)                                     ###################################                                             ###################################                                             
# Installing winget...                                                          ###################################                                                                                                                             
Path          :
Online        : True
RestartNeeded : False

###################################
# Adding WindowsApps directory to PATH variable for current user...
###################################
###################################
# Cleaning up...
###################################
###################################
# Installation complete!
###################################
###################################
# Please restart your computer to complete the installation.
###################################

$PS>winget

Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

The winget command line utility enables installing applications and other packages from the command line.

usage: winget [<command>] [<options>]

The following commands are available:
  install    Installs the given package
  show       Shows information about a package
  source     Manage sources of packages
  search     Find and show basic info of packages
  list       Display installed packages
  upgrade    Shows and performs available upgrades
  uninstall  Uninstalls the given package
  hash       Helper to hash installer files
  validate   Validates a manifest file
  settings   Open settings or set administrator settings
  features   Shows the status of experimental features
  export     Exports a list of the installed packages
  import     Installs all the packages in a file

For more details on a specific command, pass it the help argument. [-?]

The following options are available:
  -v,--version  Display the version of the tool
  --info        Display general info of the tool

More help can be found at: https://aka.ms/winget-command-help
