### ISSUE TITLE
[Package request] EverythingToolbar

### ISSUE THREAD

**Issue by ThePython10110** [ChrisTitusTech/winutil#582]
You made a video about it... why not add it to this tool?

**Comment by kedniko** [comment]
I would add `winget install "Flow Launcher"` instead. See https://www.flowlauncher.com/

**Comment by ThePython10110** [comment]
What do you mean, "instead?" Just add both!

**Comment by dmitriy1980** [comment]
I use http://www.launchy.net/ for years. Never used "Flow Launcher", so can't compare but based on screenshots they are similar in the functionality they provide.

**Comment by ThePython10110** [comment]
Flow Launcher seems to have more features, but they are very similar.
