### ISSUE TITLE
[Software Request] Music Production

### ISSUE THREAD

**Issue by eye-wave** [ChrisTitusTech/winutil#583]
There are already some apps for video editing and graphical design.
How about some music software next?

some DAWs for example
- FL Studio 21
- Ableton Live 11
- Bitwig
- Reaper

and Free VST Plugins
- Vital by Matt Tytel
- OTT, Dimension expander by Xfer Records

just to name a few

**Comment by KonTy** [comment]
@eye-wave we mostly like to only support Open Source application. Yes there are some that are not Open Source on the list but the number of those apps is pretty small.
