### ISSUE TITLE
Add StartAllBack and MSEdgeRedirect to Install

### ISSUE THREAD

**Issue by cwallace** [ChrisTitusTech/winutil#585]
Would it be possible to add the following two applications to the install section? Both are install immediately applications for me. StartAllBack allows the configuration of the start menu and taskbar in Windows 11 to something more like Windows 7/10 (your choice). MSEdgeRedirect is a fantastic utility to automatically redirect URLs sent to Microsoft Edge to your default browser. Microsoft seems to utilize this a lot in Windows 11, especially in the widgets menu.

StartAllBack: [https://www.startallback.com/](https://www.startallback.com/)
winget install startallback

MSEdgeRedirect: [https://github.com/rcmaehl/MSEdgeRedirect](https://github.com/rcmaehl/MSEdgeRedirect)
winget install MSEdgeRedirect

**Comment by rpgdev** [comment]
StartAllBack isn't free. Open Shell could be an alternative. I also get rid of that godawful "start" menu whenever I happen to install Windows somewhere. https://github.com/Open-Shell/Open-Shell-Menu

**Comment by ChrisTitusTech** [comment]
OpenShell is already in the tool. I'm cutting down on freemium additions and I don't like startallback. 

MsEdgeRedirect automatically happens when removing edge in the commit I did last week. So no extra program is needed.
