### ISSUE TITLE
iwr : The request was aborted: The connection was closed unexpectedly.

### ISSUE THREAD

**Issue by Lynchas** [ChrisTitusTech/winutil#586]
Any idea how to fix this? While trying to install Windows tool
![image](https://user-images.githubusercontent.com/112245215/213916529-56c933d2-086c-4c69-b53a-1679a3f241b4.png)

**Comment by ainable** [comment]
> 

Use the other command listed : [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')
