### ISSUE TITLE
DNS does not comeback to normal when set to default

### ISSUE THREAD

**Issue by heismauri** [ChrisTitusTech/winutil#587]
**Describe the bug**
I don't want the DNS set by the program anymore and I can't seem to be able to delete them

**To Reproduce**
Set your DNS to a server (ex: Cloudflare)
It applies
Set to default
It is still Cloudflare

**Expected behavior**
It should let you go back to having no DNS or a custom one

**Comment by DeveloperDurp** [comment]
The fix will be part of the following PR  #576

**Comment by ChrisTitusTech** [comment]
Merged
