### ISSUE TITLE
LICENSE - Declare Script License with SPDX License Identifier

### ISSUE THREAD

**Issue by svet-am** [ChrisTitusTech/winutil#590]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to see a SPDX License Identifier for the script in the header comments.  https://spdx.dev/ids/

**Describe alternatives you've considered**
N/A

**Additional context**
While the license on the repo is good, having a SPDX identifier in the source code is helpful for automated license compliance tooling

**Comment by ChrisTitusTech** [comment]
Great idea, added in commit https://github.com/ChrisTitusTech/winutil/commit/edc26265e1ca72769cd83b18191c3d507ec02082
