### ISSUE TITLE
Windows 11 (on VirtualBox) Bugs!

### ISSUE THREAD

**Issue by digitalsparky** [ChrisTitusTech/winutil#591]
**Describe the bug**
A couple of bugs come across whilst running this on a fresh Windows 11 Pro instance running on VirtualBox.
Edge fails to uninstall, and there are 2 other silent (in terms of GUI output) errors as well re scheduled tasks and update delivery.
Please see screenshots for more information.

**To Reproduce**
1. Fresh Windows 11 Pro instance running on VirtualBox (not sure if this is reproducable otherwise, though I'd assume so, just how I produced it)
2. Run "irm christitus.com/win | iex" via admin powershell
3. Select all essential tweaks, add ultimate performance, Remove edge

**Expected behavior**
Process to complete successfully without errors

**Screenshots**
Scheduled Tasks & update delivery
![ctt-bug](https://user-images.githubusercontent.com/3377029/215082046-f72ec2ad-df10-482c-9708-1ec97319ad26.jpg)

Edge removal
![ctt-bug-edge-removal](https://user-images.githubusercontent.com/3377029/215082056-c152f4c1-0d20-4609-83a7-ec4405a49561.jpg)

(I'd also suggest adding a 'please reboot your computer' at the end....)

**Comment by ChrisTitusTech** [comment]
Thanks @digitalsparky got all these fixed this past week.
