### ISSUE TITLE
Unable to connect to the remote sever

### ISSUE THREAD

**Issue by Deva-Agarwal** [ChrisTitusTech/winutil#593]
This is a DNS error, but even after changing my DNS it is still not working. I can access the link through the web.
![image](https://user-images.githubusercontent.com/57745636/215273971-db70b273-2cc0-4d97-9fde-6f8006430b86.png)

**Comment by nikkdevic** [comment]
same here
![CTDBerror](https://user-images.githubusercontent.com/97282126/215306163-b47919e4-a64f-45be-954a-a0501cb76de5.png)

**Comment by Deva-Agarwal** [comment]
> same here ![CTDBerror](https://user-images.githubusercontent.com/97282126/215306163-b47919e4-a64f-45be-954a-a0501cb76de5.png)

Hey, I got it fixed.
Just download Cloudflare Wrap https://1.1.1.1 
Then start it.
Then run the script again.
