### ISSUE TITLE
The script tries to install choco even tough its already installed

### ISSUE THREAD

**Issue by RehanPlayz** [ChrisTitusTech/winutil#596]
**Describe the bug**
The script tries to install choco even tough its already installed

**To Reproduce**
Run `iwr -useb https://christitus.com/win | iex`

**Expected behavior**
Not try to install choco 

**Screenshots**
![image](https://user-images.githubusercontent.com/63925635/216042975-be9a0985-4b85-4f11-bc40-89c1ebe858fd.png)

**Comment by ChrisTitusTech** [comment]
bug was fixed in a past commit
