### ISSUE TITLE
High Disk usage fix for tweak and windows 10 it self

### ISSUE THREAD

**Issue by rinalds211** [ChrisTitusTech/winutil#600]
hello cris titus tech today i upgraded some old computer from windows 8 not the 8.1 to windows 10 i had issues with high disk usage and after researching i found what it was cousing and if you would be kind enought to add this feature it would be appriciated and were talking about service called  Connected device platform service it causes high disk usage on old hardware. to fix this issue i advise you to  add in every tweak settings for laptops or pcs to disable  Connected device platform service.

**Comment by ChrisTitusTech** [comment]
I'd love to add this service to disabled but Xbox Live and bluetooth devices rely on it.
