### ISSUE TITLE
Disable Storage Sense Tweak Not Disabling Storage Sense

### ISSUE THREAD

**Issue by GR4NDIVI4ST3R** [ChrisTitusTech/winutil#604]
1. Opened an admin Powershell instance
2. Ran irm christitus.com/win | iex
3. Set desktop recommended desktop default tweaks which included "Disable Storage Sense"
4. Clicked "Run Tweaks"
5. No errors in Powershell and success message appeared
6. Went to Windows Settings → System → Storage
7. Storage Sense was still enabled
8. Reset PC and ran the winutil again, but just selected the storage sense option, and ran tweaks
9. Storage Sense was still enabled
10. Most of the other tweaks seemed to have worked. I'll post separately for the ones that didn't seem to work.
- Prior to tweaks, I was running a fresh install of Windows 11 which I installed the latest Windows and driver updates and reset. Used stock settings other than fast boot turned off.
- Not signed in to Microsoft
- OS Build: 22621.1194
- Windows Feature Experience Pack 1000.22638.1000.0
- Intel i7 12700K, AMD 7900 XT with Adrenalin drivers installed

Edit 2/8/23:
It may be related that Disk Cleanup is not deleting the files in my %appdata%\Local\Temp folder. Unfortunately, I do not know if Disk Cleanup was working prior to the tweaks, but it may still be useful information.

**Comment by ChrisTitusTech** [comment]
This looks to be resolved. I turned it on and then ran tweaks and it cleaned out everything in disk cleaned up and disabled storage sense.
