### ISSUE TITLE
When I use essential tweaks for laptops. When I boot again it loses my password.

### ISSUE THREAD

**Issue by ealvan** [ChrisTitusTech/winutil#606]
**My laptop didn't remember my password when I turn on**
Hello.
I am using a windows Version 22h2(19045.2486 compilation)
When I use essential tweaks for laptops. At the beginning it works perfectly.
But when I did turn off my computer, and turn on again my computer somehow didn't remember my password.

I had to get in safe mode to recover the old state of my computer.

I use predefined tweaks only.

**To Reproduce**
1. Execute in poweshell with admin privileges 'iwr -useb https://christitus.com/win | iex'
2. Click on 'tweaks'
3. Go to 'Laptop' tab
4. Run the script.
5. Restart your computer.
6. Write your password (doesn't recognize).

I use a local account.
I use a password and not a pin.
Fortunately, a restore point was established.

**Comment by ChrisTitusTech** [comment]
There was some tweaks to autologin in the past commit, let me know if this happens again.
