### ISSUE TITLE
Add search bar for programs

### ISSUE THREAD

**Issue by non-descriptive** [ChrisTitusTech/winutil#607]
It's pretty obvious that with time the amount of programs in the list will grow and at some point you will need to somehow find them. So  either it should be some kind searchbar or maybe pop-up explorer, . Fuzzy finder, if possible. Image as reference from packer manger in sublime text. 
![image](https://user-images.githubusercontent.com/5757533/217910025-adda65ce-fda8-44c0-ab8b-6477d2404e2e.png)

**Comment by ChrisTitusTech** [comment]
Dig the idea, I'll think of a way of adding a search in the future.
