### ISSUE TITLE
Oracle VM

### ISSUE THREAD

**Issue by shvrdavid** [ChrisTitusTech/winutil#608]
Hi Chris, 

I used your script to do the software updates, and found an issue. It removes Oracle VM fine, then tries to install it again and fails. Afterwards has to be uninstalled with the installer that failed, then re install it again. No idea why this was the case, and only took a few clicks to correct.

Not a huge issue, but worth mentioning.

Thank you for creating such a huge time saver. I recently replaced the guts of a Win 10 system with a 13600k system and upgraded it to Windows 11. Your script was a huge time saver after installing Windows 11. 

Thanks for what you do,
Scott

**Comment by ChrisTitusTech** [comment]
I'll add Orcale VirtualBox to #374
