### ISSUE TITLE
Disable GameDVR not undone by "undo tweaks"

### ISSUE THREAD

**Issue by Whitetigerswt** [ChrisTitusTech/winutil#609]
**Describe the bug**
The disable GameDVR is not undone by this tool when you click "undo tweaks". You have to manually change these registry entries:
https://github.com/ChrisTitusTech/winutil/blob/5c8c2f34425eef95c6474ec391e9c9cd6cd52304/winutil.ps1#L347-L355

I would expect the code to undo these changes to be somewhere in this function: https://github.com/ChrisTitusTech/winutil/blob/5c8c2f34425eef95c6474ec391e9c9cd6cd52304/winutil.ps1#L1059

**To Reproduce**
1. Press Win + Alt + R ( start/stop recording with GameDVR).
2. Notice it does start and stop recording.
3. Run this tool and check the "Disable GameDVR tweak
4. Press Win + Alt + R 
5. Notice it doesn't work, expected behavior so far.
6. Run the undo tweaks from this tool
7. Press Win + Alt + R
8. No recording will start as game DVR is still disabled.

**Expected behavior**
GameDVR should be enabled when I click undo tweaks.

**Screenshots**

**Additional context**
This may disable other Xbox-related features. I do not care specifically about GameDVR, but I'm trying to resolve an issue where my game activity isn't reported to Xbox live and I think something in this tweak disabled that functionality.

**Comment by d0x360** [comment]
what game activity were you seeing reported to MS?  Were they games that ran on xbox live or are you talking steam games and the such that have nothing to fo with ms?

**Comment by ChrisTitusTech** [comment]
Fixed in c34186e
