### ISSUE TITLE
Right click stops working

### ISSUE THREAD

**Issue by FeedTheChunk** [ChrisTitusTech/winutil#610]
**Describe the bug**
Right clicking is not working on; the desktop, shortcuts and taskbar, maybe other locations too. System is Windows 10 22H2 desktop.

**Additional context**
Right clicking can be restore by CTRL+SHIFT+Esc and killing Windows Explorer.  I thought that the issue may be related to Nilesoft Shell but uninstalling did not correct the issue.  It seems to happen most often when waking the computer from sleep but not always.

I checked a second test box and ensured that right clicking was behaving normally then I ran winutil script on that second test box.  The right clicking stopped working almost immediately and I had to kill windows explorer to get it back.

Not much to go on I get it.  I will continue to monitor and see if I can make some correlations as to what might be going on.

**Comment by FeedTheChunk** [comment]
Correction.  I loose Right Click after restarting the PC not waking it from sleep.

**Comment by Kylezzz101** [comment]
same issue here setting right click to classic right click after booting up pc atm i need to kill windows explorer to get right click back

**Comment by FeedTheChunk** [comment]
After a very long time with this problem I finally was able to fix the issue.  If you used the utility to install Shell, look in the chocolaty install directory.  You may find it installed there.  I uninstalled that instance by using the uninstall supplied in that directory, the windows program and files from the control panel didn't / wouldn't uninstall it.  Once it uninstalled if fixed the problem.  I fought the issue for so long that I never tried using Shell again as it just seems way to problematic for my taste.

**Comment by Kylezzz101** [comment]
thank you very much this fixed it for me thankyou for your time

**Comment by Kylezzz101** [comment]
potential fix:
https://www.reddit.com/r/nilesoft/comments/s6q2lo/shell_not_appear_in_windows_11/

**Comment by nohart** [comment]
WingetUI updated it for me and the menu on the taskbar broke. I uninstalled and reinstalled it and now its fixed.
