### ISSUE TITLE
"The script contains malicious code and has been blocked by antivirus software"

### ISSUE THREAD

**Issue by cshock23** [ChrisTitusTech/winutil#612]
PS C:\WINDOWS\system32> iwr -useb https://christitus.com/win | iex                                                      iex : At line:1 char:1
+ #for CI/CD
+ ~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
At line:1 char:40
+ iwr -useb https://christitus.com/win | iex
+                                        ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by Arkblemish** [comment]
sorry i dont understand i am a beginner

**Comment by ChrisTitusTech** [comment]
This is changing many system functions, it being flagged as malicious would happen on almost any antivirus.
