### ISSUE TITLE
None of the commands are working

### ISSUE THREAD

**Issue by schinichi** [ChrisTitusTech/winutil#615]
None of the commands are able to run the GUI tool

I've used PowerShell and Terminal as admin, still not able to get the tool

Could this be an issue at my end?

![Screenshot (2)](https://user-images.githubusercontent.com/125759679/219881199-e4c48e26-554a-4a60-8c5d-02faf3861f52.png)

**Comment by DeveloperDurp** [comment]
Try hitting the script directly 
`irm https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1 | iex`

**Comment by schinichi** [comment]
> Try hitting the script directly `irm https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1 | iex`

Nope. Not working.
![Screenshot (3)](https://user-images.githubusercontent.com/125759679/219931853-be9a596f-7ea3-49b5-9e4e-b9529a26e474.png)

**Comment by DeveloperDurp** [comment]
Try changing your DNS provider

https://github.com/ChrisTitusTech/winutil/issues/547#issuecomment-1368995308
