### ISSUE TITLE
Issue with enabling NFS

### ISSUE THREAD

**Issue by Se3ek** [ChrisTitusTech/winutil#623]
Hi Chris, hi everyone!
I switched my NAS to Sharing via NFS and wanted to use it. It's no Problem on my Linux and Mac devices and for enabling it on Windows I wanted to use your toolkit. However, when I do it it just throws a bunch of errors and reports it being done. It doesn't really succeed though and I can't mount any NFS Shares. I tried it on two of my Windows 10 machines and it happens on both. I also have a Windows 11 machine where it works.
I've attached the log.
[Winutil.log](https://github.com/ChrisTitusTech/winutil/files/10841462/Winutil.log)

Thanks for looking into it!

**Comment by FunctionDJ** [comment]
Having the same issues here, same errors.

**Comment by BoudewijnPopkema** [comment]
Are you using Windows 10 Home edition? It seems the Windows build in NFS Client is a feature that's only available for Pro or Enterprise edition.

**Comment by Se3ek** [comment]
I am indeed using Home Edition, thanks for the info. In that case, maybe a descriptive Error message in the toolkit might be considered to let people know why it can't do it.
Thanks!

**Comment by ChrisTitusTech** [comment]
Going to let home users know via tooltip, thanks for pointing this out.
