### ISSUE TITLE
Cleanup the \Windows\WinSxS component folder

### ISSUE THREAD

**Issue by Mikesco3** [ChrisTitusTech/winutil#624]
Often the Windows\WinSxS gets really bloated with what I understand to be prior installers. <br>
Microsoft suggests a command to clean up the prior left-overs, <br>
 See [Clean Up the WinSxS Folder](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/clean-up-the-winsxs-folder?view=windows-11) <br>
So the idea would be that if the user checked the Disk Cleanup box under tweaks you could also run:
`Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase` <br>
or if you want a less aggressive version: <br>
`Dism.exe /online /Cleanup-Image /StartComponentCleanup ` 

this could go in the area currently around line 391 
``` ps
  If ( $WPFEssTweaksDiskCleanup.IsChecked -eq $true ) {
            Write-Host "Running Disk Cleanup on Drive C:..."
            cmd /c cleanmgr.exe /d C: /VERYLOWDISK
            $WPFEssTweaksDiskCleanup.IsChecked = $false
```

or add another check box for it... <be>

Anyways, thank you sooo much for this tool, I use the heck out of it...

**Comment by ozayturay** [comment]
Or we could just integrate the DSSU script: https://blog.techygeekshome.info/wpdm-package/disk-space-saver-utility/#Download

**Comment by meechgalhuquot** [comment]
I was coming to suggest this same thing. As far as the DSSU script, each individual function could be incorporated separately, but I would not incorporate the whole script as is

**Comment by ChrisTitusTech** [comment]
Brilliant idea, forgot all about using DISM for component cleanup. 
Commit 3ad120c
Should be live in the next week or so.
