### ISSUE TITLE
Disabling Hibernation not working

### ISSUE THREAD

**Issue by dbalcar** [ChrisTitusTech/winutil#625]
When running the Tweaks and have Disabling Hibernation it does not turn off Hibernation.  

**To Reproduce**
1. Go to 'Tweaks'
2. Click on 'Desktop'
3. Check root of c:\ for hiberfil.sys

**Expected behavior**
hiberfil.sys should be deleted

**Additional context**
Also tried rebooting and the hiberfil.sys is still there.   if you run powercfg /HIBERNATE it does turn it off and remove the hiberfil.sys file

**Comment by ChrisTitusTech** [comment]
Fixed in c4b3c9f
Will be commited to main soon.
