### ISSUE TITLE
Running Tweaks Everytime Turns Off Notifications & Hides Search

### ISSUE THREAD

**Issue by loveleshkalonia** [ChrisTitusTech/winutil#629]
**Describe the bug**
Even in the minimal preset, the tool disables notifications (like safe to remove usb and others) and hides search from taskbar.

**To Reproduce**
1. Open the utility
2. Click on Tweaks tab
3. Select Minimal or any preset or even customized options. Hit Run Tweaks
4. Notifications will turn off.
5. Apart from that, Search bar or icon also gets disappeared.

This issues happens in both Windows 10 and 11.

**Comment by dennyamarojr** [comment]
Could you provide more informations? Attaching screenshots, the customized options and which build of Windows 10 & Windows 11 did you use for apply winutil tweaks

**Comment by loveleshkalonia** [comment]
Hi Denny, Thank you for responding.
I'm daily driving Win 10 21H2 Build 19044.2604
I was experimenting on Win 11 22H2 Build 22621.1265

Notifications turn off after restart. Search disappears immediately.
I have made a screen recording to show you the issue. Please have a look - 
https://drive.google.com/file/d/1zborcbhDXBGYBGrkHiV8R2hcMUBde0RP/view?usp=sharing

Apologies, couldn't upload here because the file size was 50MB and I didn't want to encode this short recording.

**Comment by dennyamarojr** [comment]
I take a look at your video, and it seems something that I suspect earlier, is the settings that is been applied in O&O ShutUp10.

The two options is on the current user section in O&O ShutUp10

1 - Disable app notifications, that is located on the privacy category
![image](https://user-images.githubusercontent.com/36896116/223128452-fb465192-ed96-44cf-967d-c84ea5d6c259.png)

2 - In the Miscellaneous section, Disable search box in task bar
![image](https://user-images.githubusercontent.com/36896116/223128920-88411684-9492-4699-9013-1e73baf86504.png)

3 - I check the settings of notifications and it seems that applied some setting that could disable the notification for the current user, in my case didn't apply immediately as you show in the video. But I use RegFromAppby Nirsoft to inspect what is the tweaks that I mention apply in the regedit

Disable app notifications do the following changes on windows registry:
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PushNotifications]
"ToastEnabled"=dword:00000000

And disable search box in task bar do the following changes on windows registry
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
"SearchboxTaskbarMode"=dword:00000000

And here some sources for both of tweaks
App notifications: https://www.tenforums.com/tutorials/4111-turn-off-notifications-apps-senders-windows-10-a.html#option2
Search box: https://www.tenforums.com/tutorials/2854-hide-show-search-box-search-icon-taskbar-windows-10-a.html#option3

And before I reach which cause was making these changes, I check winutil code, and I could see that notifications was in a individual section, you can see in the following lines 
![image](https://user-images.githubusercontent.com/36896116/223132086-04738e06-5bbb-4554-9ea9-291b25009f41.png)

SearchboxTaskbarMode is not present in the winutil code, so we can guess that is been changed the search settings in the O&O ShutUp10 section.

**Comment by loveleshkalonia** [comment]
Hi Denny, Thank you for the detailed explanation. Do you think this will be taken care of in the upcoming releases?

**Comment by dennyamarojr** [comment]
I believe that yes, Chris will take a look at this issue and decide what is the changes that will be made for the upcoming releases. 
Since this problem is not really something that will prevent any users to re-enable the features, is possible to add a little information box after the changes has been made by winutil. 

I will fork the project and update the ooshutup10 setting, so Chris could see pull request and the issue at the same time.

**Comment by loveleshkalonia** [comment]
Awesome!

**Comment by ChrisTitusTech** [comment]
This was commited and if you run into notifications not working tick the disable and click undo. like this screenshot:
![image](https://github.com/ChrisTitusTech/winutil/assets/7896101/2c7adbc5-8d0f-4a2c-94ed-3c7842a092ff)

**Comment by tsullyman** [comment]
Hi Chris, even after undoing this, it seems that notification config is still 'managed by system administrator' and it breaks snipping tool with windows key shift S. Quite annoying, trying to remediate with no luck so far even reinstalling snipping tool etc.
