### ISSUE TITLE
Doesn't install Apps

### ISSUE THREAD

**Issue by DemonWolfFang** [ChrisTitusTech/winutil#63]
Unsure if I should report this as a bug; I just freshly reinstalled windows 10 and upon using the tool, I've attempted to download multiple apps at the same time, and also try tweaks and they don't work. Even upon restarting, they won't install/change.

Forgot to mention:

Running Windows 10 Home

Vers 10.019044

(Also found out there's another issue open of the same exact one: my mistake)

**Comment by Grimignton** [comment]
same stuff, new instalation it doesn't  install programs.
Running win 10 Pro
Wersja	21H2
istall	‎30.‎05.‎2022
19044.1706

**Comment by DemonWolfFang** [comment]
Yeah I didn't do that. I just ran the old script then the new one. Works fine after that, sorry for not trying to find an open issue about it before hand haha.
