### ISSUE TITLE
the scripts are not running

### ISSUE THREAD

**Issue by Arindam905** [ChrisTitusTech/winutil#631]
**Describe the bug**
it was working fine but suddenly it started showing this error :-

 irm christitus.com/win | iex
irm : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ irm christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by ongkiii** [comment]
Having the same issues:
`irm : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ irm christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by mananhiteshkataria** [comment]
similar story for a lot of scripts after using a debloated windows install

**Comment by kalwani** [comment]
Create an Inbound Rule in Windows Defender Firewall, TCP port 9418.

**Comment by ongkiii** [comment]
> 

Created an inbound rule, but the problem is prevailing.

**Comment by mananhiteshkataria** [comment]
> Create an Inbound Rule in Windows Defender Firewall, TCP port 9418.

i think the issue is with github and sometimes the raw.... links dont work sometimes i downloaded the script and then ran it and it worked fine.

**Comment by ChrisTitusTech** [comment]
You can also use `iwr -useb https://christitus.com/win | iex`

However, I know some countries like India block github raw files. Kinda weird, but happens all the time.
