### ISSUE TITLE
i want to restore my action center

### ISSUE THREAD

**Issue by jimmyak845** [ChrisTitusTech/winutil#633]
i recently debloat my win 10 unfortunately my action center greyed out & unable to enable it.
Need help to restore it.
Thanks in Advance
Regards 
Jimmy

**Comment by DeveloperDurp** [comment]
You should be able to restore this by doing the following

1. Open WinUtil
2. Go to the tweaks section
3. Check "Disable Notification"
4. Click Undo Tweaks
5. Reboot

**Comment by jimmyak845** [comment]
not working still 
![image](https://user-images.githubusercontent.com/121643208/226159513-f2eace85-61dd-4118-937e-538a3acd70b5.png)

**Comment by DeveloperDurp** [comment]
I tested this on Win 10 21H2 and undoing the notifications tweak restored the action center. Can you confirm what version of windows you are on?

**Comment by dennyamarojr** [comment]
Could you provide more information about the version of windows you're using and could you print the powershell screen to see if we could a find a error or something. So we could help you and also help others by providing additional information to fix the same issue in the future.

**Comment by jimmyak845** [comment]
![image](https://user-images.githubusercontent.com/121643208/227765092-f1a0b923-9f35-4235-afd0-45dbd1e3f1ca.png)


> I tested this on Win 10 21H2 and undoing the notifications tweak restored the action center. Can you confirm what version of windows you are on?

**Comment by dennyamarojr** [comment]
Try to run the following commands in powershell as admin
Remove-Item -Path "HKCU:\Software\Policies\Microsoft\Windows\Explorer" -Name "DisableNotificationCenter"
Remove-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\PushNotifications" -Name "ToastEnabled"

**Comment by jimmyak845** [comment]
![image](https://user-images.githubusercontent.com/121643208/228163159-e6f6d055-60a7-4dc5-bb08-edca895749d4.png)
after what?

**Comment by jimmyak845** [comment]
> Try to run the following commands in powershell as admin Remove-ItemProperty -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\Explorer" -Name "DisableNotificationCenter" -ErrorAction SilentlyContinue Remove-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications" -Name "ToastEnabled" -ErrorAction SilentlyContinue

![image](https://user-images.githubusercontent.com/121643208/228163258-cc2a5547-40d8-48c3-b54f-f50da9d01af3.png)

**Comment by DeveloperDurp** [comment]
I am having a hard time replicating the issue. Is there any other modifications you have done to your PC?

**Comment by dennyamarojr** [comment]
Hi @jimmyak845 please run the following command, and attach to the post, so we can investigate
(List all running and stopped services to .txt file)
Get-Service | Select StartType, Status, Name, DisplayName | Format-Table -AutoSize | Out-File -filepath "$Env:userprofile\Desktop\All_Services.txt"

Source: https://www.tenforums.com/tutorials/126607-export-list-running-stopped-services-windows.html#option2

You make any modifications to the system? If yes could you tell us which modifications is, because on yesterday stream on twitch @ChrisTitusTech test the script and easily recover action center.

**Comment by jimmyak845** [comment]
> I am having a hard time replicating the issue. Is there any other modifications you have done to your PC?

[TweakUIX-018.0.zip](https://github.com/ChrisTitusTech/winutil/files/11100291/TweakUIX-018.0.zip)
i think i used this also but not confirmed

**Comment by jimmyak845** [comment]
> .\bckp_windows_services.ps1
![image](https://user-images.githubusercontent.com/121643208/228523074-53087f5f-db06-4df5-84c8-659b1f1946f6.png)

i unrestricted all but here the error

**Comment by dennyamarojr** [comment]
Tested here and the same issue, probably is the UTF option enable in intl.cpl that is region settings
![image](https://user-images.githubusercontent.com/36896116/228586672-33cd7bf8-9bc8-4c9e-9683-23d2a50ac7fb.png)

**Comment by dennyamarojr** [comment]
I take a look at the error and fixed, you can check it on #673  and download the properly file which is the second one and try again @jimmyak845

**Comment by jimmyak845** [comment]
all of you guyz thank you for your support.
i don`t know but today when i login my computer my action center has been restored.

Regard,
GX UNKNOWN

**Comment by jimmyak845** [comment]
i did`t try the last 

> Tested here and the same issue, probably is the UTF option enable in intl.cpl that is region settings ![image](https://user-images.githubusercontent.com/36896116/228586672-33cd7bf8-9bc8-4c9e-9683-23d2a50ac7fb.png)
> 
> I will be investigating some solution for the fix, will update the file as soon as possible.

i did`t try this but the commands i used yesterday thats worked after system restore
