### ISSUE TITLE
'iwr' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by DonManoloCelete** [ChrisTitusTech/winutil#634]
When I run Terminal as Administrator on Windows 11 I always get the following respons: ''iwr' is not recognized as an internal or external command, operable program or batch file.'.

Could you help me to solve this problem?

**Comment by dennyamarojr** [comment]
Hi @DonManoloCelete 
Please provide more information about the issue by providing information's like your operating system, which version of windows if is 10 or 11.

**Comment by DonManoloCelete** [comment]
Hi @dennyamarojr 
Below the requested information:

Edition    Windows 11 Pro Education
Version   22H2
Install date             ‎7/‎12/‎2022
Build      22621.1265
Experience             Windows Feature Experience Pack 1000.22638.1000.0

Attached you can find a screenshot of the error as well.
![Naamloos](https://user-images.githubusercontent.com/127191945/223452477-3d8fbd8b-47f0-4acd-bf53-03811e7780ad.jpg)

**Comment by elint** [comment]
Use Powershell, not Command Prompt. IWR or Invoke-WebRequest is a PowerShell utility.

**Comment by DonManoloCelete** [comment]
Thank you so much, I thought 'Terminal' was the new 'Powershell' in Windows 11. Evidently not, works like a charm!

**Comment by Anuvansh-0** [comment]
I keep getting error when is run this script can someone tell me what i am doind wrong here.
![Screenshot 2023-09-21 081028](https://github.com/ChrisTitusTech/winutil/assets/145693561/4061353d-13a3-4c42-a3f7-0b67e57bfabc)
