### ISSUE TITLE
Visual C++ 2015-2022 Redistributables Not Installing

### ISSUE THREAD

**Issue by ElectricRockets** [ChrisTitusTech/winutil#636]
I was using this tool to add these two programs but they don't show up in the control panel programs menu, and searching for 2015-2022 in file explorer brings up nothing. Currently using Windows 11 Home 22H2 build 22621.1344. The other tweaks seem to work. I both tried installing with some previous visual c++ redistributables installed and then removed them but it made no difference. There was no error messages, the secondary powershell windows closed automatically and the initial admin powershell window displays that installs are finished and winget is installed. Not super high priority, just wanted to mention it here.

**Comment by ChrisTitusTech** [comment]
Fixed in last commit
