### ISSUE TITLE
Xbox Controller Xbox Button won't open Game Bar

### ISSUE THREAD

**Issue by Tommy2tone1982** [ChrisTitusTech/winutil#638]
**Describe the bug**
After running recommended tweaks even unchecking gamedvr the 
xbox button on xbox controller no longer will open xbox game bar. It will still open with windows+G but for some reason it is breaking the buttons link to open it from the controller
**To Reproduce**
1. Run Reccomended Tweaks
2. Click on Xbox Controller XBOX button
3. Nothing Happens

**Expected behavior**
Xbox Controller Button should open game bar or controller bar, works fine before tweaks, and after undoing
**Screenshots**

**Additional context**

**Comment by dennyamarojr** [comment]
Please open powershell as admin and use the following command
Get-AppxPackage | Select Name, PackageFullName >"$env:userprofile\Desktop\Apps_List.txt"

After you get the file Apps_list.txt attach in the issue so we can check your apps, to see if Xbox Game Bar app is installed.

**Comment by dreamsyntax** [comment]
Hijacking this as I've reproduced this issue on 3 different computers.
[Apps_List.txt](https://github.com/ChrisTitusTech/winutil/files/11237190/Apps_List.txt)

The app itself still exists, and can be launched in Start with "Xbox Game Bar" app manually.

![image](https://user-images.githubusercontent.com/14857235/232157082-91b84c56-c823-4fce-b571-e4470ceb8998.png)

I suspect this setting - which always turns itself off once you re-navigate to the page is the issue.

So likely the DVR disable is also preventing the hotkeys for gamebar, despite gamebar still being installed.

**Comment by dreamsyntax** [comment]
I've confirmed this is the issue.

I reverted the following:

```
"WPFEssTweaksDVR": {
    "registry": [
      {
        "Path": "HKCU:\\System\\GameConfigStore",
        "Name": "GameDVR_FSEBehavior",
        "Value": "2",
        "OriginalValue": "1",
        "Type": "DWord"
      },
      {
        "Path": "HKCU:\\System\\GameConfigStore",
        "Name": "GameDVR_Enabled",
        "Value": "0",
        "OriginalValue": "1",
        "Type": "DWord"
      },
      {
        "Path": "HKCU:\\System\\GameConfigStore",
        "Name": "GameDVR_DXGIHonorFSEWindowsCompatible",
        "Value": "1",
        "OriginalValue": "0",
        "Type": "DWord"
      },
      {
        "Path": "HKCU:\\System\\GameConfigStore",
        "Name": "GameDVR_HonorUserFSEBehaviorMode",
        "Value": "1",
        "OriginalValue": "0",
        "Type": "DWord"
      },
      {
        "Path": "HKCU:\\System\\GameConfigStore",
        "Name": "GameDVR_EFSEFeatureFlags",
        "Value": "0",
        "OriginalValue": "1",
        "Type": "DWord"
      },
      {
        "Path": "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR",
        "Name": "AllowGameDVR",
        "Value": "0",
        "OriginalValue": "1",
        "Type": "DWord"
      }
    ]
  },
```


Revert above RegKeys to the OriginalValue.
Reboot PC.
After I go to settings and turn on Xbox Game Bar.
![image](https://user-images.githubusercontent.com/14857235/232159483-8d03daa3-01ce-43ca-a816-b4556afc1f5f.png)

Now the hotkeys work as expected.

I will check next if we can keep everything disabled except the 
HKLM value.

**Comment by dreamsyntax** [comment]
Update:
I have confirmed only:
` Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR" -Name "AllowGameDVR" -Type DWord -Value 0 `

Is necessary to change back to '1'.
The rest can be kept.
This enabled Xbox Game Bar but prevents captures, which is likely the intended use case.
