### ISSUE TITLE
"help wanted" The target machine actively refused it

### ISSUE THREAD

**Issue by solomonrajan** [ChrisTitusTech/winutil#645]
Showing error while using code `iwr -useb https://christitus.com/win | iex` in Windows 11 Terminal with Administrator privilege.

**_Error:_** `Invoke-WebRequest: No connection could be made because the target machine actively refused it.`

**Comment by DeveloperDurp** [comment]
You might have better luck hitting the file directly. My guess is your IP is blocked somewhere in the chain. 

https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1
