### ISSUE TITLE
Upgrade installs not working

### ISSUE THREAD

**Issue by nannycodes** [ChrisTitusTech/winutil#651]
When running this tool on Windows 11 latest install as of 3/14, I am running into the following issue when clicking the  upgrade installs button. I am running this thru PowerShell with Admin privileges 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/126896708/225772235-3f275122-a3ec-4198-ba1e-6a4301e6183b.png">

The tool just hangs after this message, no updates are installed

**Comment by anonyao** [comment]
Hello first i wanna say thx good . Your debloater is the only one who really dont broken windows totaly and guys i know u know this but exactly almost debloat names/files/ if u have seen the malware for windows who eset found who have been on win10/11 pc for almost year . Anyway that maleware focus boot for secure boots/vbs secure launch, and it make same commands like debloaters doo filechange names igot it few days ago . Yesterday my pc went crazy nothibg worked att all. But Chris something is wrong with your debloater. Msstore/apps wont leave me. Onedtre too like 5 times before it gone. And many minor errors. But thx for your tool for this years. I have trash pc but it saves me in games. And all users who bot proDeluxe it nerds, doo boot scan/or online scan with eset . And throw your AV with the msbloats :)
