### ISSUE TITLE
Win Bandwidth fix

### ISSUE THREAD

**Issue by stuckydev** [ChrisTitusTech/winutil#654]
Hey Chris

Are you interested in impelmenting your tweaks from your YT video: "Windows is Taking Your Bandwidth | Let's Fix It!"?

**Comment by ChrisTitusTech** [comment]
I've added some of the tweaks, but other tweaks aren't wanted in bigger environments. The idea is to have tweaks applied to 100% of all systems. 
I am looking at adding a gaming option that might include this tweak though.
