### ISSUE TITLE
Utility interferes with ability to properly connect phone.

### ISSUE THREAD

**Issue by pureventrue** [ChrisTitusTech/winutil#655]
Strange issue with iphone that has not been told to "trust this computer" no longer gives the option 'to' trust this computer after running utility.

This is actually a problem I experienced with the old version as well, but undoing the changes used to return everything to normal so I never worried about it.

Disabling telemetry in tweaks would also stop my pc from being able to properly talk to my iphone. If the device didn't already 'trust' my pc, I would no longer even get the option to do so. I could only "allow" windows to access photos from it, & I would have to "allow" it every single time I plugged the phone in.

However, now undoing the changes no longer gives me back that functionality. I've recently had to clean install my system which is what made this crop up in the first place.

Installing itunes first, then running the utility, I applied some tweaks that I felt would be fairly non disruptive. Disable hibernation, enable numlock, disable mouse acceleration. Run. Plug my phone in, normal system detecting new device process. Get the popup on my phone to allow access, which I do. I should then get a 2nd popup to "trust" the machine, but that doesn't happen.

I started over with another clean install & this time, I ran the utility first using the same settings, THEN installed itunes & connected my phone. This time it behaved exactly as expected with giving a 2nd popup to trust.

I've probably done about 20 fresh installs in the process of trying to figure this out. Every test I've done, if I run the utility _after_ installing itunes but _before_ connecting my phone, I lose the ability to tell it to trust my pc regardless of what tweak settings I apply.
If I run the utility first, everything works as I would expect it to as long as I don't disable telemetry. I tested by doing everything _except_ disable telemetry & all was ok. I then tested by _only_ disabling telemetry & my phone no longer worked.

**Comment by ChrisTitusTech** [comment]
Good to know, its a bit worrying that disabling the telemetry would effect the connection. Telemetry is used to report data back to Microsoft why it would block a connection in iTunes is troubling.

**Comment by pureventrue** [comment]
Well I did post this a while ago. Since then you've done an update video talking about some bad commits & I've run the util again on a fresh install with no such issues so... might have been part of that batch.

I was more concerned with the fact that undoing was not actually undoing than anything else.

Sadly I don't have a spare machine to use for testing & I wasn't prepared to go through all that effort again to make absolutely sure. Just saw that it worked this time & got on with it! But since that update you released, disabling telemetry no longer seems to have an affect so... yay!
