### ISSUE TITLE
Cant run the program command

### ISSUE THREAD

**Issue by 2000031465-SaketRama** [ChrisTitusTech/winutil#657]
iwr : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by ChrisTitusTech** [comment]
Some countries block raw github files and requires you to download and run it manually.
