### ISSUE TITLE
Add 4 individual shortcuts for ONLYOffice Editors install (Word, Excel, Forms and Powerpoint)

### ISSUE THREAD

**Issue by IgorKerstges** [ChrisTitusTech/winutil#661]
**Describe the bug**
When installing ONLYOffice Desktop with the Install-Option, the package gets installed with a single shortcut- / start-option: "ONLYOFFICE Editors" ("C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe"). This can be improved by adding 4 individual shortcuts for the respective ONLYOffice Programs: "Word", "Excel", "Forms", "Powerpoint".

**To Reproduce**
1. Go to Shortcut 'ONLYOFFICE Editors'
2. Click and open
3. Here you will find the ONLYOffive 'dashboard' where the user then can choose the desired program to open.

**Expected behavior**
In addition, the user could be presented with individual shortcuts, either on desktop, taskbar or in the Startmenu:

**"Word"**
Shortcut Target with argument: `"C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe" --new=doc`

**"Excel"**
Shortcut Target with argument: `"C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe"  --new=cell`

**"Forms"**
Shortcut Target with argument: `"C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe" --new=form`

**"Powerpoint"**
Shortcut Target with argument: `"C:\Program Files\ONLYOFFICE\DesktopEditors\DesktopEditors.exe" --new=slide`

**Screenshots**
n/a

**Additional context**
Of course, this solution requires some meaningful icons. I chose icons from [iconarchive](https://www.iconarchive.com/show/mega-pack-1-icons-by-ncrow.html) myself. These are available with license: [CC Attribution-Noncommercial-No Derivate 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/). Not sure if this could be considered for this application, but I would assume you'd be able to find suitable icons otherwise....

Cheers! Igor.

**Comment by ChrisTitusTech** [comment]
Thanks for the report, but I'm sure they will revamp their product to add these icons sometime in the future. I don't personally use onlyoffice, but those that do on a regular basis will just pin the icons for these programs.
