### ISSUE TITLE
The tool not working after recent wondows 11 update on powershell.

### ISSUE THREAD

**Issue by shrijanv** [ChrisTitusTech/winutil#664]
While running the command for the tool in powershell as admin, there is this output.

iwr : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by dennyamarojr** [comment]
Did you try with the following command?
irm christitus.com/win | iex
