### ISSUE TITLE
No connection to Uni Campus WiFi (eduroam) after using the tool

### ISSUE THREAD

**Issue by lcvalves** [ChrisTitusTech/winutil#670]
**Describe the bug**
Connectivity to campus wifi network (eduroam) not working after using the tool.

**To Reproduce**
Used to tool to debloat and make some minor tweaks to the laptop. Honestly, I can't totally remember every single tweak I had made, but I do remember watching your latest video on it and took notice not to do anything critical to the system.

**Expected behavior**
Just debloat the machine and improve performance.

**Screenshots**
A couple of months before using the tool, I had logged in my uni credentials to connect to the WiFi 
![image](https://user-images.githubusercontent.com/43750743/227664106-eba4455f-5703-4f9c-ab21-85cc455ef7c1.png)

It worked as expected. After using the tool, I can still connect to the network but it doesn't have access to the internet.
![image](https://user-images.githubusercontent.com/43750743/227664466-d3011b71-ebed-4ec5-a566-5820a4519722.png)

**Additional context**
After using the tool, the uni network did not prompt me to insert my credentials again.

**Comment by DeveloperDurp** [comment]
The only thing that could have an impact from the tool is if you changed DNS to something other than "Default" and that WiFi network actively blocks the DNS provider you picked.
