### ISSUE TITLE
Hello, im getting this error...  WARNING: Files from a previous installation of Chocolatey were found at 'C:\ProgramData\chocolatey'. WARNING: An existing Chocolatey installation was detected. Installation will not continue. For security reasons, this script will not overwrite existing installations.  Please use choco upgrade chocolatey to handle upgrades of Chocolatey itself. If the existing installation is not functional or a prior installation did not complete, follow these steps:  - Backup the files at the path listed above so you can restore your previous installation if needed  - Remove the existing installation manually  - Rerun this installation script  - Reinstall any packages previously installed, if needed (refer to the lib folder in the backup)  Once installation is completed, the backup folder is no longer needed and can be deleted. choco : The term 'choco' is not recognized as the name of a cmdlet, function, script file, ....  After trying to use you tool after going back to a restore point 

### ISSUE THREAD

**Issue by trooper86** [ChrisTitusTech/winutil#671]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dennyamarojr** [comment]
Hi @trooper86 ,

First of all your title should be Chocolatey not be recognized error, and the title actually is the description of the bug you're facing.

What I suggest you, is to reinstall chocolatey using winutil and them try again to use it. If the error persists, provide more information like:

Your Operating system
Version and Build of OS
And if possible check the "Paths" in environment variables to see if chocolatey is configured to be used in cmd or powershell.

**Comment by trooper86** [comment]
It was the path thank you.

**Comment by trooper86** [comment]
thank you again. im enjoying using the ctt tool but also choco..

**Comment by XianMatth** [comment]
I am getting the same error please help me in resolving it. I get the below error.

WARNING: Files from a previous installation of Chocolatey were found at 'C:\ProgramData\chocolatey'. WARNING: An existing Chocolatey installation was detected. Installation will not continue. This script will not overwrite existing installations. If there is no Chocolatey installation at '', delete the folder and attempt the installation again. Please use choco upgrade chocolatey to handle upgrades of Chocolatey itself. If the existing installation is not functional or a prior installation did not complete, follow these steps: - Backup the files at the path listed above so you can restore your previous installation if needed. - Remove the existing installation manually. - Rerun this installation script. - Reinstall any packages previously installed, if needed (refer to the lib folder in the backup). Once installation is completed, the backup folder is no longer needed and can be deleted. choco : The term 'choco' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:176 + ... .DownloadString('https://chocolatey.org/install.ps1')); choco upgrade ... + ~~~~~ + CategoryInfo : ObjectNotFound: (choco:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException
