### ISSUE TITLE
Add Function to backup windows services and drivers current configuration

### ISSUE THREAD

**Issue by dennyamarojr** [ChrisTitusTech/winutil#673]
**Is your feature request related to a problem? Please describe.**
Probably a lot users use multiple scripts to optimize windows and sometimes those script could disable a service of windows or even a driver that is crucial to windows work properly and users maybe not have access to the previous state of windows services and drivers services

**Describe the solution you'd like**
This script will backup the current configuration for Windows Services and Windows Drivers, so users can restore the previous state of the services and drivers of windows before apply any optimization script and avoid any problems in the future.

**Describe alternatives you've considered**
An alternative that I have been considering is to create a PDF file with all the services of windows and describe in a table what program, app or part of windows require which service to run properly. Example: Services for MS store: wuauserv, InstallService and etc....

**Additional context**
The source for this script that I convert to powershell is from AtlasOS script, here's the link for the source: https://github.com/Atlas-OS/Atlas/blob/main/src/AtlasModules/atlas-config.cmd#L697

Here's the script that I convert to powershell
[bckp_windows_services-drivers_current_state.zip](https://github.com/ChrisTitusTech/winutil/files/11103003/bckp_windows_services-drivers_current_state.zip)

Steps to run the script
1. Extract the files to a location and them open powershell and type Set-ExecutionPolicy Unrestricted
2. Run this command .\bckp_windows_drivers.ps1 ; .\bckp_windows_services.ps1
3. Check desktop for Default Windows drivers.reg and Default Windows services.reg

**Comment by ChrisTitusTech** [comment]
Really love this addition. I'm going to put this.
