### ISSUE TITLE
winget installer

### ISSUE THREAD

**Issue by YusufKhalifa1** [ChrisTitusTech/winutil#676]
can you add a function to install winget with the winget script you show in one of your videos if winget isn't installed this gonna make it easy for anybody to start using your utility as easy as possible 
thanks for your work !

**Comment by YusufKhalifa1** [comment]
> Hi @YusufKhalifa1 the winutil already makes a check in the system to see if winget is installed and if not make the installation process, what we can do is change the process and instead of just installing winget, also update the Desktop App Installer to make sure that is in the latest version.
> 
> You can check the function in the script in the following link
> https://github.com/ChrisTitusTech/winutil/blob/main/winutil.ps1#L171

Hi @dennyamarojr installing winget on systems that doesn't have msstore justike windows enterprise, the script I mean here is the script that was mentioned in one of his articles here:
https://christitus.com/installing-appx-without-msstore/
I hope you understand

**Comment by dennyamarojr** [comment]
I completely understand and did you check the reference in the script I post a time ago?
![image](https://user-images.githubusercontent.com/36896116/230993151-6ab95237-1f05-4b39-928e-c66689f9400e.png)

In the image you can see that the verification already checks if the winget is present and if is too old, and make the use of the winget-install.ps1 script that @ChrisTitusTech show in the video.

Maybe needs to change the code to just verify if winget is installed and the if not installed run the command including
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
Install-Script -Name winget-install -Force

which is not been used, just winget-install.ps1 and is not using the above command.

**Comment by ChrisTitusTech** [comment]
Just updated the standalone winget installer and working on implementing this into the script original issue is #347 
Closing this.
