### ISSUE TITLE
Unity Game Engine Installation is not working

### ISSUE THREAD

**Issue by tarunchhabriya06** [ChrisTitusTech/winutil#687]
**Describe the bug**
When you try to install the Unity game engine the tool exits with the message "No package found matching input criteria." and the program ends up being not installed

**To Reproduce**
1. Go to the Install section
2. Select the Unity game engine from Development
3. Click on start install and wait a few seconds
4. The installation fails and the tool return with the message "No package found matching input criteria."

**Expected behavior**
The unity game engine should get installed correctly after clicking on start install

**Screenshots**
![image](https://user-images.githubusercontent.com/66588897/230760314-01535dce-53d7-494e-b4e3-6297c36468e7.png)

**Comment by SebastianWozniczka** [comment]
Good morning, 
I have the same, but I have already installed unity in version 2021.3.19f1 via the website earlier and I do not know how it is different
