### ISSUE TITLE
winget not installed error

### ISSUE THREAD

**Issue by hs6666** [ChrisTitusTech/winutil#693]
if running utility in an elevated powershell command prompt.......

1) for non admin user, get message saying "winget is not installed" even though it is

2) works fine if running utility when logged in as a admin user

?

Thanks

**Comment by martin-braun** [comment]
You mean: 

```
Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing
```

? Happens for me as well on clean Windows 11.

**Comment by ChrisTitusTech** [comment]
working on implementing a new install #347 is original closing this dupe.
