### ISSUE TITLE
Option for WSL2

### ISSUE THREAD

**Issue by Raybo58** [ChrisTitusTech/winutil#694]
I saw your utility supports installing WSL. I just wanted to suggest also offering the option to install WSL2. This is the updated version and it's more efficient and robust. It mounts both your Linux subsystem AND your Windows OS on the same hypervisor.
https://pureinfotech.com/install-windows-subsystem-linux-2-windows-10/

**Comment by DeveloperDurp** [comment]
The install process is the same, it's how you setup your Linux instance inside WSL that determines if it's WSL1 or 2
