### ISSUE TITLE
Ping and internet monitor

### ISSUE THREAD

**Issue by nanophlex** [ChrisTitusTech/winutil#697]
a ping and upload download feature that you can pin to any place in task bar or keep it always on top of apps games...

this will be so usefull for gamers that start games and finding them selfs lagging.

I always want to know my internet usage so that usefull too there's already apps for that but none that have ping option included or staying always on top

something like that with ping indicator too :
![image](https://user-images.githubusercontent.com/53929142/233243693-b95c155b-7b47-4c12-a4ff-ebaa8e2258f3.png)

**Comment by XPSYDEUS** [comment]
it says it's closed where i can find the app ?
