### ISSUE TITLE
Taskbar Calendar doesn't show up after running tweak

### ISSUE THREAD

**Issue by serouin** [ChrisTitusTech/winutil#699]
**Describe the bug**
Taskbar Calendar doesn't show up after running tweak

After running the tweak, when I click the Calendar at the taskbar, it doesn't show. Also I tried to tick **Disable Notification** and then Undo Tweak but it doesn't work.

**Comment by DeveloperDurp** [comment]
You will either need to reboot or restart explorer.exe for the changes to take effect. If you already tried the undo tweak for Disable Notification than it's likely something else that might be causing the issue.

**Comment by serouin** [comment]
> You will either need to reboot or restart explorer.exe for the changes to take effect. If you already tried the undo tweak for Disable Notification than it's likely something else that might be causing the issue.

I tried everything ask you said but it didn't work. When I clicked to the taskbar calendar before tweaking, it was normal and no issue. After running the tweak, when click it doesn't show anymore.

**Comment by DeveloperDurp** [comment]
Have you run any other tweaks from different tools? I have tested this and running undo restores the calendar functionality. 

you can also change the registry directly to ensure they are set correctly

HKCU:\Software\Policies\Microsoft\Windows\Explorer\DisableNotificationCenter should be 0
HKCU:\Software\Microsoft\Windows\CurrentVersion\PushNotifications\ToastEnabled should be 1

**Comment by serouin** [comment]
> Have you run any other tweaks from different tools? I have tested this and running undo restores the calendar functionality.
> 
> you can also change the registry directly to ensure they are set correctly
> 
> HKCU:\Software\Policies\Microsoft\Windows\Explorer\DisableNotificationCenter should be 0 HKCU:\Software\Microsoft\Windows\CurrentVersion\PushNotifications\ToastEnabled should be 1

No I haven't use any other tweaks.
But currently everything is fine. I tried to reinstall Windows and tweaked twice times. One with default Desktop profile, and one without Disable Location, Activity History and Wifi-Sense. Of course I made sure that Disable Notification is unticked. And yes, the Taskbar Calendar with the Desktop profile without 3 options above is ok. So I'm not sure if there is any bug or not...

**Comment by ChrisTitusTech** [comment]
Added an Enable Calendar/Notification tweak
