### ISSUE TITLE
Will not install applications

### ISSUE THREAD

**Issue by myxxmikeyxx** [ChrisTitusTech/winutil#70]
I tried running this script after doing a fresh windows install. I ran it to install these software's:
Google.Chrome
Discord.Discord
Notepad++.Notepad++
PuTTY.PuTTY
7zip.7zip
VideoLAN.VLC
Bitwarden.Bitwarden
Rufus.Rufus
Spotify.Spotify
WinDirStat.WinDirStat 

It said these were installed but they were not installed. 
Any tips or where's the download location so I can just manually install them?

**Comment by myxxmikeyxx** [comment]
to get by I have just used ninite to get a mass installer

**Comment by kyspyridon** [comment]
I also encountered the same issues with the apps above.

**Comment by shainegordon** [comment]
you need to manually install "App Installer" from the Windows Store

**Comment by GPoutine** [comment]
> you need to manually install "App Installer" from the Windows Store

Thanks shaine, this fixed me for me. I had to update my App Installer after a fresh w11 install but worked after that.
