### ISSUE TITLE
Network Issues - Ethernet restarting NetworkStateChangeTask

### ISSUE THREAD

**Issue by BlueFray** [ChrisTitusTech/winutil#702]
This started after I used the Tweaks, every night between 2-4AM, my ethernet will restart while Im gaming... once or a few times and it's rather infuriating. I did a lot of troubleshooting, went through my Event Viewer, and repaired whatever I could to no avail.
Finally dug through my Task Scheduler and noticed this particular task failing at the same time. 

Find the error here;
1. Go to Windows Task Scheduler
2. Find this folder in the left sidebar - "Task Schedular Library" > "Microsoft" > "Windows" > "Setting Sync"
3. In "Setting Sync", you will see NetworkStateChangeTask 
This should be different for everyone but for me, the "Last Run Result" is "The operator or administrator has refused to request. (0x800710E0)"

![image](https://user-images.githubusercontent.com/82735490/234339109-8307584f-6507-429f-9cac-639f07a3b9b7.png)
![image](https://user-images.githubusercontent.com/82735490/234341385-b7119843-9c71-4f88-9a37-67bbe83f51b4.png)
(I have since disabled it, otherwise Status is "Running". Will find out tonight if disabling worked)

I am aware that certain Windows modifiers/tweaks can remove elements that affect certain files and cause corruption indirectly, or .dlls to go missing. I could be wrong, flagging in case the cause was here.

**Comment by Coldblackice** [comment]
I know this is old, but is there an explanation as to what got completed/fixed here? Or what the problem was, how it was fixed? TIA
