### ISSUE TITLE
add suport for servers

### ISSUE THREAD

**Issue by jmcd1987** [ChrisTitusTech/winutil#703]
**Describe the solution you'd like**
do you think you can add support for server 2016 and up to the tools

**Additional context**
if you try to run it now you get this..

![image](https://user-images.githubusercontent.com/131842406/234469424-33cfa36e-4aa1-4caa-9d19-b5091cddb3dc.png)

also

**Describe the solution you'd like**
do you think you can add a way to make a .bat that will auto run selected installs and tweaks we select that can be saved to run on more then one pc without picking every thing each time?

Also thank you for all your hard work in making tools that make our life so much easier..

**Comment by ChrisTitusTech** [comment]
I wouldn't recommend running this on server, but it can. 

Change command to:
`irm https://christitus.com/win | iex`

**Comment by jmcd1987** [comment]
It does not work I get this

 



 



 

Any help you can give me past that

**Comment by ChrisTitusTech** [comment]
I'd download the winutil.ps1 file from the project and just run it locally. There are some nations that block raw github files.
