### ISSUE TITLE
Chose which updates?

### ISSUE THREAD

**Issue by iznawh** [ChrisTitusTech/winutil#705]
Would if be possible after clicking "upgrade installs" we get to choose which upgrades we want? For instance I use NordVPN and the newest versions don't allow me to auto connect to 1 specific server so I have to use an older version, but every time I use your tool it will auto update it. So I have to uninstall and then reinstall the old version.

Thank you!

**Comment by DeveloperDurp** [comment]
One option is if you check the applications you want to update and then click install winget will detect that it's already installed and then update them if available. With the latest update there is a "get installed" button and an import/export function to make this easier.
