### ISSUE TITLE
Cannot start CTT

### ISSUE THREAD

**Issue by AryaPPatil** [ChrisTitusTech/winutil#707]
Hello 
I have been facing issues in starting CTT
its just showing me 'irm : unable to connect to the remote server'
i cant add attachments but ill just paste what i saw
irm : Unable to connect to the remote server
At line:1 char:1
+ irm christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by TharTeen** [comment]
I am also getting the same error.

irm : Unable to connect to the remote server
At line:1 char:1
+ irm christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by TakiShiwa** [comment]
> Hello I have been facing issues in starting CTT its just showing me 'irm : unable to connect to the remote server' i cant add attachments but ill just paste what i saw irm : Unable to connect to the remote server At line:1 char:1
> 
>     * irm christitus.com/win | iex
> 
>     * ```
>         + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
>        eption
>         + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
>       ```

Try with VPN cause in countries like India, raw file access from GitHub is banned by gov. Try with VPN.
this will work and yeah also include https
- irm https://christitus.com/win | iex

**Comment by TakiShiwa** [comment]
## Here is the proof!
![Screenshot_2023-07-21-01-09-50-38](https://github.com/ChrisTitusTech/winutil/assets/137756384/35aebae8-4ffd-422f-a3af-c9d9c1560fa1)
