### ISSUE TITLE
Bricked my whole device until restart

### ISSUE THREAD

**Issue by Hxku1337** [ChrisTitusTech/winutil#71]
This bug occurred when i did the recommended settings in the tweaks page. I used laptop settings because i have laptop.. well, did restart, everything seemed right and nothing was off, well until i tried to search something in the windows search bar, or trying to open settings. 2 minutes after this discovery, the windows GUI [ start menu ] started flashing on and off, could not click anything, it was constantly highlighting random windows [ like steam, spotify, etc] so i tried to restart the explorer.exe. That didn't work either, because i got an error [ PICTURE ].

1. Go to 'Tweaks Page'
2. Click on 'Laptop'
3. Apply your tweaks
4. Restart the system

**Expected behavior**
To be fair, i just expected the system to be more snappy and a little bit faster.

**Screenshots**
![IMG_20220628_003536](https://user-images.githubusercontent.com/108307331/176050116-bd1a67aa-4307-4aa3-86ec-c77625d3b04e.jpg)

**Additional context**
Its not hard to fix it back.. just open the power-shell app again and unload [ revert ] the changes and restart.

**Comment by ChrisTitusTech** [comment]
Unable to replicate error
