### ISSUE TITLE
addition of software to the list

### ISSUE THREAD

**Issue by Crusader-Boss** [ChrisTitusTech/winutil#710]
Hey chris can u add these apps to app sections 

1. vs code insiders ( winget id : Microsoft.VisualStudioCode.Insiders )
2. mem reduct ( winget id : Henry++.MemReduct )
3. notion ( winget id : notion.notion )
4. spotify ( winget id: spotify.spotify )

**Thank you for the hard work.**

**Comment by ChrisTitusTech** [comment]
Programs go in #374
