### ISSUE TITLE
Setup Autologin Not working

### ISSUE THREAD

**Issue by iznawh** [ChrisTitusTech/winutil#712]
Don't know if its just a me problem with autologin, but:

1. Go to Config tab
2. Click on "Set up Autologin" button
3. Nothing happens

Tried restarting the the program/computer multiple times and ran the system corruption scan (everything was good)

[youtube video showing bug](https://youtu.be/5deIP3fJItE)

**Comment by padsalatushal** [comment]
it's working in my setup 
I test autologin features in Windows 10 and Windows 11.
Works fine for me.

**Comment by iznawh** [comment]
> it's working in my setup I test autologin features in Windows 10 and Windows 11. Works fine for me.

i guess it just a mee problem then?

**Comment by padsalatushal** [comment]
I tested autologin features on different systems. it's working fine.

**Comment by Elvara26** [comment]
Just got a new computer, I made a windows 11 iso using tookit to remove some bloatware, I'm using this tool for the first time it works for everything but the auto login, when I click on it nothing happens at all. It's windows 11 pro not sure if that changes anything and it's not activated yet.
