### ISSUE TITLE
App installer Update fails.

### ISSUE THREAD

**Issue by github59173** [ChrisTitusTech/winutil#714]
**Describe the bug**
When running the utility to install programs winget is used but if winget doesn't exist or is outdated the utility tries to install it. It fails to do so.

**To Reproduce**
Run utility program installer. 
app installer window pops up with "This app package is not supported for installation by App Installer because it uses certain restricted capabilities."

**Expected behavior**
Installs/Updates winget and proceeds with install of subsequent applications selected. 

**Screenshots**
N/A (already updates the app installer from the windows store before making this report)

**Additional context**
This is not a new issue; I have seen this time and time again using this script over the past year and find it frustrating having to go update the app installer manually through the Microsoft store.

**Comment by ChrisTitusTech** [comment]
I'm going to look into adding a --unknown version that should update it, but winget is imperfect for grabbing everything.
