### ISSUE TITLE
Use scoop as alternative software/package manager for winget, if winget is not available 

### ISSUE THREAD

**Issue by skygunner** [ChrisTitusTech/winutil#715]
**Is your feature request related to a problem? Please describe.**
On some system, or some situation winget is not avaialble (revision os) or installing is always error out (msstore/windows itself breaks a lot).

**Describe alternatives you've considered**
 It would be nice to have scoop as alternative to install package / softwares, as most of the softwares can be installed via winget can also be done via scoop. (Though it is a bit slow to download and install compared to winget, maybe due to cdn issue)

Plus winget is microsoft thing, can not be manually installed from github. And microsoft break things a lot.

**Comment by ChrisTitusTech** [comment]
currently we are working as choco as the backup, but will add scoop in a future version for the more obscure stuff that winget/choco can't get.
