### ISSUE TITLE
For the project's future maybe some sort of offline persistence would be nice to have

### ISSUE THREAD

**Issue by skygunner** [ChrisTitusTech/winutil#716]
**Is your feature request related to a problem? Please describe.**
A lot of time, windows's network is broken, or not  available.
Windows breaks a lot with it's network/adapter/firewall.

**Describe the solution you'd like**
If the project can have a bit of offline persistence it would be nice to have

**Comment by ChrisTitusTech** [comment]
There is an offline exe, but you can always download the ps1 script here and run it in your powershell with an unrestricted execution policy.
