### ISSUE TITLE
Task managger 

### ISSUE THREAD

**Issue by lejifps** [ChrisTitusTech/winutil#717]
**Describe the bug**
Task managger takes ages to actually close

**To Reproduce**
Just did the desktop checkbox without oo and backup

**Expected behavior**
Task manager should close insatnt like before O.o

**Comment by lejifps** [comment]
Seems like a issue of the "Disable Services" Tweak.

**Comment by the1919** [comment]
[Copied from ](https://linustechtips.com/topic/1489326-windows-10-task-manager-takes-about-5-seconds-to-close/)

Hello, i was looking all over the internet trying to find a solution for this and found nothing, so I took action on the matter. The thing is, when you do the "Set Services To Manual" tweak, between those tasks there's one called "NDU" which stands for "Windows Network Data Usage Monitoring Driver". I looked in the powershell to see which services were being set to manual start. Then i began to start each service one by one, until i found the root of the problem.

All you have to do is:

1- Do the "Set Services To Manual" tweak.

2- Open registry editor and go into HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Ndu

3- Inside Ndu there is a dword named "Start"

4- Change "Start" value to 2. (3 and 4 is for disabling it i think)

5- Restart and done.

**Comment by lejifps** [comment]
@ChrisTitusTech if that fixes it maybe remove the services from the manual list :3

**Comment by ChrisTitusTech** [comment]
Thanks commited this 4a9cdda
