### ISSUE TITLE
Choco failed to install

### ISSUE THREAD

**Issue by roguekira** [ChrisTitusTech/winutil#718]
**To Reproduce**
Run irm christitus.com/win in powershell and it fails to do the setup at all. Almost all processes fail, never had the issue before when using this I know a little about computer usage but nothing about these things so Idk what else to do

**Comment by Velosofy** [comment]
Such problem isn't easy to reproduce as it has so many variables to look for.
Please attach any screenshot or error logs to narrow it down.

**Comment by roguekira** [comment]
![Screenshot (3)](https://github.com/ChrisTitusTech/winutil/assets/101777038/972a59ba-d127-45a6-86ea-70ed5b8f48de)
![Screenshot (1)](https://github.com/ChrisTitusTech/winutil/assets/101777038/f03e00b6-c999-482c-854f-d546fbb3ae2f)

**Comment by Velosofy** [comment]
What we're looking at is the actual script codes.
What exactly did you enter in your powershell?

**Comment by roguekira** [comment]
irm christitus.com/win

this is what I ran as I always have, it used to work for me before idk if anything changed or what

**Comment by Velosofy** [comment]
You need to execute the script, `irm christitus.com/win` alone will only fetch it.
You need to run `irm christitus.com/win | iex` per README

**Comment by padsalatushal** [comment]
@roguekira  you should close this issue now.

**Comment by roguekira** [comment]
@padsalatushal how? This is my first time ever really using github..
