### ISSUE TITLE
More Applications to add

### ISSUE THREAD

**Issue by gunner990** [ChrisTitusTech/winutil#720]
Following applications:
1. GNU Octave (FOSS, Scientific programming language, cross platform): https://octave.org/
2. FreeCAD (FOSS, 3D CAD application, cross platform): https://www.freecad.org/
3. LibreCAD (FOSS, lightweight 2D CAD application, cross platform): https://librecad.org/

**Comment by ChrisTitusTech** [comment]
Wrong place to add software #374
