### ISSUE TITLE
Could there be an option not to upgrade graphics drivers when installs are upgraded?

### ISSUE THREAD

**Issue by DJMoffinz** [ChrisTitusTech/winutil#723]
I use NVCleanstall for my Nvidia drivers and It'd be nice to be able to use winutil's upgrade installs feature without having to worry about it trying to install the latest PhysX or whatever.
It would be nice to have a simple toggle/checkbox to tell winutil to exclude any driver components when upgrading.
I would gladly do this myself, but I don't feel sufficiently at home in Powershell as of yet.

**Comment by DeveloperDurp** [comment]
One option is if you check the applications you want to update and then click install winget will detect that it's already installed and then update them if available. With the latest update there is a "get installed" button and an import/export function to make this easier.

**Comment by DJMoffinz** [comment]
oh cheers! i reckon that’ll be fine then.

**Comment by DJMoffinz** [comment]
should i close this issue then?

**Comment by padsalatushal** [comment]
> should i close this issue?

yes
