### ISSUE TITLE
Ultimate Performance installed twice..

### ISSUE THREAD

**Issue by tato0715** [ChrisTitusTech/winutil#728]
Accidentally clicked twice on "Add Ultimate Performance Profile" & now it shows up twice. Tried to use "Remove Ultimate Performance Profile" but get "The power scheme, subgroup or setting specified does not exist." in PowerShell. (Even after restarting)

any fix for this?

**Comment by YusufKhalifa1** [comment]
In this case you need to do it manually as explained here 👎🏽 
You can remove it from the power options page by following these steps :
1- Open power option menu by pressing 'WindowsKey + r' to open run command window, then a window will popup type in the box "powercfg.cpl"  then press enter.
2- The power options menu will appear now , on ultimate performance power plan choose 'change plan settings' 
3- You'll see option says 'delete this plan' press it and you will be done.

**Comment by ChrisTitusTech** [comment]
Just made a new commit #766 that fixes duplicate power profile and the remove button now works properly
