### ISSUE TITLE
Will the tweaks be applied to every existing user or just the admin?

### ISSUE THREAD

**Issue by theRoboxx** [ChrisTitusTech/winutil#73]
**Question:**
The question from the title.
I created a new user for testing purposes and the apps were not listed, so there it worked.
It seems like the changes got applied to new users but not existing users?
Does it matter, if I apply the tweaks before or after the creation of new users?
Thanks in advance for your help.

**To Reproduce**
1. install windows
2. create another user account
3. switch to admin
4. run "Remove ALL MS Store Apps"
5. log out and login to new user
6. MS Store Apps are still there 

**Expected behavior**
Run "Remove ALL MS Store Apps" and these Apps will be uninstalled for every user account on the PC.

**Comment by ChrisTitusTech** [comment]
Most tweaks are applied at a global level, but when it comes to microsoft store, that is isolated to each user.
