### ISSUE TITLE
Cannnot see wifi networks

### ISSUE THREAD

**Issue by Crusader-Boss** [ChrisTitusTech/winutil#734]
**Describe the bug**
whenever u run the run the tweak " set services to manual " it make the wifi networks undiscoverable. you wifi will be on but u wont see any networks on the flyout.

**To Reproduce**
1. Go to tweaks tab
2. Click on set services to manual
3. click run tweaks
4. reboot
5. see error

**Expected behavior**
set unnecessary services to manual and reduce the number of processes on startup without affecting anything else.

**Additional context** 
I found the problem. The script sets the " wlan autoconfig" service to manual.
![image](https://github.com/ChrisTitusTech/winutil/assets/96982315/6c20ea49-3034-4e96-be43-d805f1905670)
as you can see here. Setting that to automatic and starting the service fixed the issue.

os : windows 10 Pro 22H2 ( os build 19045.2006 )

**Comment by fixem2** [comment]
Same issue I have been having.  Ran the Desktop script and lost wifi, reloaded windows and tracked it down to the Desktop script.  Thanks for figuring out which service is having issues.   Will implement this reversal until the software is fixed.

**Comment by sadjesse** [comment]
I've also had this issue with the latest versions of Windows 10 and 11 Enterprise N. 
Somehow Windows always thought that there was something wrong with the drivers. But I'm going to try this. Thank you!

**Comment by ChrisTitusTech** [comment]
Fixed in #749
