### ISSUE TITLE
Script Disables Windows Management Instrument (WMI) in services

### ISSUE THREAD

**Issue by KinsleyLYY1212** [ChrisTitusTech/winutil#735]
**Describe the bug**
Running the script with desktop preset would disable Windows Management Instrument (WMI) in services

**To Reproduce**
1. Go to services and locate Windows Management Instrument (WMI). 
2. Click on Windows Management Instrument (WMI)
3. Select "Disable" in the "Startup Type"
4. Select "Stop" under the "Services Status"
5. Click Apply
6. Run any VBS file to replicate the issue, 

**Expected behavior**
It should not have disable it, instead set it to "Manual"

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/133179661/d7b35379-4d14-40c8-adf0-0d7dba325518)

**Comment by SinisterSpatula** [comment]
I think this service being set to 'disabled' is what caused my windows 11 to be unable to complete the most recent cumulative update for windows 11.  After I set it to manual and started it, and tried the cumulative update again, it succeeded.

**Comment by ChrisTitusTech** [comment]
Fixed in #760
