### ISSUE TITLE
Windows Defender Broken

### ISSUE THREAD

**Issue by BiRaitBec** [ChrisTitusTech/winutil#737]
**Describe the bug**
Windows defender doesn't work anymore, i click the scan button but nothing happens and tpm verifying sections do not detect properly anymore. Before i run the only line for making processes manual tpm was considered active and i could use the scan feature. After the tweak with only the processes line active it both do not work anymore, maybe a process related to windows defender has been disabled, there is one i have in mind but it says i cannot reset it.

To reproduce just tweak the only line for the processes.

**Expected behavior**
Processes triggered on activation means if i scan it has to work.

**Screenshots**

**Additional context**

**Comment by anonyao** [comment]
Its perfect now download eset internet security best antivirus for game , no impact at pc very effective

**Comment by BiRaitBec** [comment]
The expected behavior is to make defender work, then if you want to give the option to remove it ok, but separate from manual processes. 

I just want to know which service is responsible to it, so that the program removes it from the list.

**Comment by exostalker** [comment]
There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.
