### ISSUE TITLE
Powershell Errors When Running Tweaks

### ISSUE THREAD

**Issue by xxxLepreChAUnSxxx** [ChrisTitusTech/winutil#74]
I get a bunch of errors when running tweaks. This is a Windows 10 fresh install. 

Errors:
[Powershell_Errors.txt](https://github.com/ChrisTitusTech/winutil/files/9022521/Powershell_Errors.txt)

**Comment by xxxLepreChAUnSxxx** [comment]
> maybe the locations are only accessed by SYSTEM

how would I go about fixing that?

**Comment by ChrisTitusTech** [comment]
Should self elevate in recent version using PR #94 merge
