### ISSUE TITLE
OpenVPN 2.6.3 Client will not install

### ISSUE THREAD

**Issue by Pleusch** [ChrisTitusTech/winutil#741]
Describe the bug
Can't install OpenVPN 2.6.3 after running the "Set Service to Manual" Script

To Reproduce
Install Windows 11 Pro, Update Full, Run the script.

![image](https://github.com/ChrisTitusTech/winutil/assets/129837690/1f0288b1-87f8-4baf-a197-5a6c53deffde)

OpenVPN.MSI Setup Log:

[OpenVPN.log](https://github.com/ChrisTitusTech/winutil/files/11451015/OpenVPN.log)

**Comment by exostalker** [comment]
There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.

**Comment by Pleusch** [comment]
> There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.
> 
> #735 Basically just do the same steps but set it to manual (instead of disabled) and start it.

Start the WMI-Service does not solve this problem!

**Comment by ChrisTitusTech** [comment]
Resolved in #760
