### ISSUE TITLE
Add Emulators to WinUtil. Please.

### ISSUE THREAD

**Issue by HackersinSpace** [ChrisTitusTech/winutil#742]
**Is your feature request related to a problem? Please describe.**
This is mainly a feature I wanna see implemented to those that do a little Emulation. Plus to also update Emulators with this tool.

**Describe the solution you'd like**
The solution I'd love to see is this Util being the all-in-one stop for grabbing the best Emulators from the NES to the Nintendo Switch. JUST THE EMULATORS, I do NOT condone piracy. I just want this to be added so it'll make downloading Emulators less tedious.

**Describe alternatives you've considered**

**Additional context**

These are the Emulator GitHubs for their respective Console/Handheld:

NES Emulator: https://github.com/SourMesen/Mesen2/
SNES Emulator: https://github.com/snes9xgit/snes9x
PlayStation 2 Emulator: https://github.com/PCSX2/pcsx2
GBA Emulator: https://github.com/mgba-emu/mgba
Nintendo DS Emulator: https://github.com/melonDS-emu/melonDS
PSP Emulator: https://github.com/hrydgard/ppsspp
Wii/GameCube Emulator: https://github.com/dolphin-emu/dolphin
Wii U Emulator: https://github.com/cemu-project/Cemu
Nintendo Switch Emulator Ryujinx: https://github.com/Ryujinx/Ryujinx
Nintendo Switch Emulator Yuzu: https://github.com/yuzu-emu/yuzu
PlayStation 1 Emulator: https://github.com/stenzek/duckstation
PlayStation 3 Emulator: https://github.com/RPCS3/rpcs3
Xbox 360 Emulator: https://github.com/xenia-project/xenia
PlayStation Vita Emulator: https://github.com/Vita3K/Vita3K
Xbox Emulator: https://github.com/xemu-project/xemu
Nintendo 64 Emulator Project 64: https://github.com/project64/project64
Nintendo 64 Emulator Simple 64: https://github.com/simple64/simple64
Nintendo 3DS Emulator Citra: https://github.com/citra-emu/citra
Sega DreamCast Emulator: https://github.com/flyinghead/flycast
RetroArch: https://github.com/libretro/RetroArch

**Comment by BiRaitBec** [comment]
I would say RetroArch and Launchbox is already a good start.

**Comment by miqumi** [comment]
RetroArch and LaunchBox are enough,

**Comment by HackersinSpace** [comment]
> RetroArch and LaunchBox are enough,

Added RetroArch's GitHub. LaunchBox is just a frontend to load games not an emulator.

**Comment by HackersinSpace** [comment]
RetroArch GitHub Source added. For those that actually like that software. I personally prefer standalone emulators but that's just me. Hope these all get added so it'll please everyone.

**Comment by BiRaitBec** [comment]
Retroarch is more versatile with Retroarch shaders and RetroAchievements, so  i think it's preferred, and also because if you start doing standalone emulators, you would really add a loong list of them even of the same system multiple ones.

Through Launchbox you actually can automatically install retroarch that's why is preferred to just solo retroarch.

**Comment by HackersinSpace** [comment]
> I personally think RetroArch is too clunky and complicated to setup. Just my opinion but I still added it anyways :)

**Comment by miqumi** [comment]
meh

**Comment by ChrisTitusTech** [comment]
Probably add Retroarch to Games in a future update on #374
