### ISSUE TITLE
Samsung Magician Software WMI Error

### ISSUE THREAD

**Issue by Pleusch** [ChrisTitusTech/winutil#743]
Samsung Magician Software Error Massage after "Set Service To Manual"

Fresh Windows 11 Pro Install with full Updates.

![image](https://github.com/ChrisTitusTech/winutil/assets/129837690/b5038a7f-80cf-4836-b8c6-391ab1c5f97a)

**Comment by CameronM0717** [comment]
Havint the same problem.

**Comment by exostalker** [comment]
Bug that disables Windows Management Instrument (WMI) instead of making it manual, same thing exactly happened here, to fix it:

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.

**Comment by Pleusch** [comment]
> Bug that disables Windows Management Instrument (WMI) instead of making it manual, same thing exactly happened here, to fix it:
> 
> #735 Basically just do the same steps but set it to manual (instead of disabled) and start it.

Start the WMI-Service does not solve this problem!

**Comment by exostalker** [comment]
> > Bug that disables Windows Management Instrument (WMI) instead of making it manual, same thing exactly happened here, to fix it:
> > #735 Basically just do the same steps but set it to manual (instead of disabled) and start it.
> 
> Start the WMI-Service does not solve this problem!

Had the same exact error (in English only) in Magician, worked for me to fix everything. The error itself literally states the name of this exact service that's causing the problem, so really can't be any other culprit either, I'd make sure that you actually enabled it: 

![wwwmmmiii](https://github.com/ChrisTitusTech/winutil/assets/18196930/100eb20d-894d-4a08-af1d-58af8a68a85e)

**Comment by ChrisTitusTech** [comment]
Fixed in #764
