### ISSUE TITLE
Bitlocker ist not Working

### ISSUE THREAD

**Issue by Pleusch** [ChrisTitusTech/winutil#744]
Fresh Win 11 Pro install after Set Service to Manual script.

![image](https://github.com/ChrisTitusTech/winutil/assets/129837690/e7b8a7e6-bc87-4b2e-90b4-76c142d48c87)

**Comment by exostalker** [comment]
There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.

**Comment by Pleusch** [comment]
> There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.
> 
> #735 Basically just do the same steps but set it to manual (instead of disabled) and start it.

Start the WMI-Service does not solve this problem!

**Comment by padsalatushal** [comment]
@Pleusch  try to start BDESVC service
