### ISSUE TITLE
Tweaks > Recommended Selections not working

### ISSUE THREAD

**Issue by Banva23** [ChrisTitusTech/winutil#745]
**Describe the bug**
After opening the CTT Windows Utility usually in the "Tweaks" section it would auto select the required tweaks based on the selection "Desktop or Laptop" and we would click on "Run Tweaks" from few days the recommended selection is not working as intended.

**To Reproduce**
1. Run Directly from PowerShell with Admin.
2. Click on Tweaks > Recommended Selections > Desktop / Laptop.
3. Tweaks are not being auto selected based on recommended selection.

**Expected behavior**
Auto selection of required tweaks based on recommended selection.

**Additional context**
Current OS - Win 11 Ver - 22h2

**Comment by Manifold2** [comment]
+1

**Comment by Manifold2** [comment]
Thanks, it worked

**Comment by Banva23** [comment]
@imluwi Thank you so much!

**Comment by DeveloperDurp** [comment]
Bug has been resolved

**Comment by Banva23** [comment]
@DeveloperDurp Thanks for the update! just checked it's working perfectly fine now.
