### ISSUE TITLE
WLAN Autoconfig Set to Manual Causing WiFi to get Disabled

### ISSUE THREAD

**Issue by JCXAB** [ChrisTitusTech/winutil#751]
Description:
WLAN Autoconfig Set to Manual Causing WiFi to get Disabled

**To Reproduce**
1. Run the WinUtil
2. Check Services to Manual
3. Run the Tweaks
4. Verify WLAN Autoconfig in Services

**Expected behavior**
Wifi Should not get Affected, or WLAN Autoconfig should not get set to Manual

**Comment by padsalatushal** [comment]
#754 
Bug has been resolved. if you are still facing this issue then once run set the service to manual.

**Comment by JCXAB** [comment]
Closing the defect
