### ISSUE TITLE
WlanAutoconfig issue and Windows security Services are disabled in newer version. 

### ISSUE THREAD

**Issue by Hasnain1385** [ChrisTitusTech/winutil#752]
**Describe the bug**
I used the newer version of winutil on win 11 pro insider(joined) on my laptop through laptop preset in tweka section and it disabled the "Wlansvc" and "windows security service".
The wifi option from taskbar was removed and I wasn't able to join any wifi network. 
Not know about the Security service as it just show up in the notifications and I'm not able to make it as automatic started. 

**To Reproduce**
1. Run winutil using powershell or terminal. 
2. Click on 'tweaks'. 
3. Click on 'laptop' preset. 
4. Run the tweaks. 
5. Restart the laptop. 
6. See error

**Expected behavior**
1. Not able to join any wifi automatically other then manually run the wlansvc service from services.
2. Not know the consequences of the security service.. but seems to deal with security. 

**Screenshots**
1. 
![IMG_20230513_170533](https://github.com/ChrisTitusTech/winutil/assets/98284742/3faad5ec-6e42-42aa-ac55-2936b6f5e4be)

2. 
![IMG_20230513_170549](https://github.com/ChrisTitusTech/winutil/assets/98284742/56631733-8975-47cf-92c9-f2c734b74339)

**Comment by padsalatushal** [comment]
Bug has been resolved. if you are still facing this issue then once run set the service to manual.

**Comment by Hasnain1385** [comment]
Yup...Thanks a lot for your time for such wonderfull effort.
I've recently seen the changes made.

I also skimmed the script and found that current version is not performing as much better as the older one.
as the "Sysmain" service is not disabled anymore after tunning the tweaks and also the process count is not as much lowered this time... 

Is there a way to attain the older version of script to run through powershell offline as there are no version rollback options or releases in github sub menu
