### ISSUE TITLE
CTT-Windows Utility.exe

### ISSUE THREAD

**Issue by cHrONicaLLYcURaTiV** [ChrisTitusTech/winutil#753]
Dear ChrisTitusTech,

I decided to purchase the **CTT-Windows Utility.exe** to support your efforts in bringing this, seemingly incredibly useful program to the world of Windows users. Upon payment & successful download of the .zip file, I immediately set to re-visiting your YouTube video about it and proper use. I will now list, in chronological order of the actions being performed, the totality of the actions I took after running the program:

Starting out in the 'Install' tab... after reviewing the lists I decided that I wasn't in need of any further installs, I already had everything installed that I needed from the available install lists.

Next tab, Tweaks - I read through all the available tweaks and tooltips, again referred to your YT video, then ultimately settled on selecting 'Laptop' from the 'Recommended Selections' predetermined option categories, albeit making four total changes to the selections, those were as follows:

**_Essential Tweaks_**
1 Ticked "Run Disk Cleanup"
**_Misc Tweaks_**
2 Ticked "Disable Power Throttling" 
3 Unticked "Enable Power Throttling" 
4 Unticked "Disable NumLock on Startup

Then "Run Tweaks" was clicked & it executed the selections without issue.

Config tab was then selected. The singular thing done in this tab was the selecting of "Windows Subsystem for Linux" followed by the clicking of "Install Features", which installed without issue.

Then the final tab, "Updates" was selected... and this is where, I believe, resulted in the issue that took me many hours to rectify (I will provide more details regarding what ultimately transpired regarding this shortly). Again, referring to your YT video as well as the helpful text below the three available options in this tab, I clicked the "Security (Recommended) Settings"... all seemed to be well thus far and so I went back to the "Install" tab to run the Winget: "Upgrade All" function. This resulted in 26 total updates, of which 25 updated without issue and only one seemed to not want to update, even after a couple of repeat attempts at running "Upgrade All". I was happy with what had been done as so I closed everything down and restarted the system.

Upon logging back in to Windows after rebooting there appeared to be multiple issues with the OS, issues that I was entirely unable to figure out what was causing / had caused them and nor could I make any headway whatsoever insofar as rectifying the problems with many attempts made over various hours. I had lost all networking functionality even though the wifi network adapter was functional and not reporting any problems. The entire list of quadrants that appears at the very bottom of the notifications pane accessible from the taskbar next to the system tray icon in Windows 10, they were all gone along with notifications too, the only time I could get one of the boxes to appear was the "Flight Mode" one which appeared when I tried accessing various different networking screens via the settings screen and all that would happen is a single box containing flight mode available to activate (flight mode was not active fyi). Needless to say this hampered my abilities to properly diagnose the issue due to my device not having connectivity.

Other issues appeared too, such as the text within windows explorer being incredibly faded and aliased, it was barely legible and in certain cases not at all legible. 

After giving up trying to fix the issues I ended up resorting to restoring Windows from earlier restore points. I also ran into quite a bit of difficulty with this because while it was taking a good 15+ minutes when selecting a restore point to restore to, the restore points were persistently failing to restore, even when restoring the various auto-generated restore points by the system and by the CTT Win Utility program. Ultimately the solution that worked was disabling Bitlocker encryption, booting into safe mode without networking, selecting a restore point that was slightly further back than I would have liked but it at least worked, and then eventually I was able to boot back into Windows 10 with everything once again working.

My apologies for not being able to provide more data to enable you to better understand what went wrong, also for my lack of brevity in writing this issue to be reported to you. In hindsight I definitely should have saved the log files to a USB drive prior to restoring back to a functioning restore point, I really dropped the ball with that one! In fairness though, it had eaten up so much of my time and I was running into bad luck at what seemed to be every point along the way that I was, in a small way, considering using the reset function of Windows that effectively maintains your files and reinstalls the OS... so thin my patience was wearing with it all ;)

I must admit that I am now more than a slight bit apprehensive about using the CTT Windows Utility again! While I am pretty confident that this was a case of user error and not the fault of the utility - probably my clicking of the 'Updates' > 'Security (Recommended) Settings' function? I am assuming that because I cannot really see how the updating of applications / installation of Windows Subsystem for Linux could have caused this issue. Also, while I am far from certain, I am assuming that the "Recommended Selections" > "Laptop" tweaks would more than likely be known to be stable and safe to use, therefore also highly unlikely to be the cause too? That being said and now that I am looking at it again, after selecting "Run Disk Cleanup" on top of having selected "Laptop", that effectively left only the "Delete Temporary Files" & "Disable Hibernation" check-boxes UN-ticked in the "Essential Tweaks" section. This situation combined with the application of "Updates" > "Security (Recommended) Settings" perhaps ended up resulting in the situation I found my OS in?

Just to add a bit more information (that may or may not be valuable), my laptop is an Asus Strix SCAR 17", AMD Ryzen 9 5900HX, NVIDIA RTX 3080, and running two Samsung 980 Pro 2TB NVMe SSD's. It is usually helpful to know the hardware on which issues occur but also I just wanted to make clear the fact that the laptop I am using is a fairly high end creator tier laptop so my unticking of "Disable Power Throttling" shouldn't, at least in my estimation, be cause for concern!

Hopefully you can understand that I am not able to provide exact steps to follow in order to reproduce this situation. I provided every setting that I enabled / changed / applied and even if the information provided is entirely useless to you for the purposes of anything to do with the further development of the utility, maybe at least you may be able to fire a sentence or two my way letting me know which of the things I did within the utility, as outlined above, that are totally safe to do without having to concern myself with potentially reliving the same scenario again. If you're able to find the time to respond sometime in the future then that would be greatly appreciated, also please do not feel pressured in any way to respond, I understand that there is likely little more you could add by replying that you haven't already said either in a YT video or more likely on the CTT Windows Utility github page itself.

Thank you for your efforts bringing this utility to life, and the many others too. As I finish typing out this issue to you I am heading to download Pretty PowerShell, if it is even half as good / capable as its description claims, then it's for sure going to be a thing of beauty! 

All the best,

Greg James

**Comment by exostalker** [comment]
There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.

**Comment by ChrisTitusTech** [comment]
Fixed in #764
