### ISSUE TITLE
The Mysterious Case of the Vanishing Wi-Fi and Rebellious Notepad

### ISSUE THREAD

**Issue by tombrau** [ChrisTitusTech/winutil#755]
**Bug Report:** 
The Mysterious Case of the Vanishing Wi-Fi and Rebellious Notepad

**Describe the bug** 
Oh boy, have we got a bug tale for you! So, picture this: you're all excited to load up the latest version of the Windows tool on your trusty Surface Book 2, ready to conquer the digital world. But alas! As soon as the installation completes, things go haywire faster than a caffeinated squirrel on a power line. Notepad refuses to open text files, and just when you thought it couldn't get worse, your Wi-Fi network mysteriously vanishes into thin air. Poof! Just like that, it's gone.

**To Reproduce** 
Now, let's retrace our steps through this techno-maze and try to recreate the chaos:

1.  The adventure begins with the installation of various programs, including Obsidian, Gmail, Chrome, GDrive, and VeraCrypt.
2.  Next, visit the mystical land of Github to download the current version of the Windows tool. Trust us, it's an adventure in itself.
    -   Oh, by the way, be sure to consult the GitHub page for the Windows tool for the download quest.
3.  Armed with the command, dive headfirst into the process, choosing the default options like a brave warrior.
4.  When prompted, select the "Laptop" option because we all know your Surface Book 2 is your trusty steed.
5.  Now, take a deep breath, and prepare for the inevitable. Reboot your system and witness the chaos unfold.
6.  As the dust settles, observe the wretched state of affairs: Notepad refuses to play nice with text files the only file it can load, and your beloved Wi-Fi network has pulled a disappearing act worthy of a Houdini impersonator.

**Expected behavior** 
In a perfect world, my dear troubleshooter, this is how things should have gone down: The Windows tool should have danced smoothly with your Surface Book 2, causing no disruptions to the harmonious functioning of my laptop. Notepad should have eagerly opened text files, and the Wi-Fi network should have remained as reliable as your grandma's secret cookie recipe.

**Additional context** Alas, no screenshots were provided to document this wild journey. However, I have stumble upon an intriguing CMD output I don't possess any secret knowledge that might shed light on this confounding issue, but if you do please share it with me. I am all ears and ready to delve deeper into this mystical realm of glitches and mayhem.

On a serious note, I'm happy to test it, if you figure out what's happening, I know there are not a lot of surface books out there.

cheers
tom

[cmd output.txt](https://github.com/ChrisTitusTech/winutil/files/11469824/cmd.output.txt)

**Comment by master4367** [comment]
Same happened with me. Did not check anything else, but wifi stopped working. Driver could not be installed. I did everything the same on other laptop and everything OK.

**Comment by exostalker** [comment]
There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.

**Comment by tombrau** [comment]
Thanks exostalker, will try that
