### ISSUE TITLE
Alwats removes WiFi and network connections after rebooting after applying tweaks and now it does not even reduce the process count as much

### ISSUE THREAD

**Issue by TwistedVision518** [ChrisTitusTech/winutil#756]
Before when i always used to use this util in a stock windows 10 install after the tweaks it used t get the process count all the way to 40-45 but now its reduced none the less but its in the mid 70s now which i found quite sad also in Windows 11 everytime i ran this weak in this week the network service used to get stopped completly and then you wouuld have to go to the services app and restart is manually everytime i think it is because of the "Set services to manual" tweak and also a minor thing is on scree resolutions with 1366x768 the window size is maxed out as in you can see the title bar unless you resize it and then you can which causes a little bit of time loss

**Comment by JarfJarfBinks** [comment]
same issue, clean install, just setting services to manual, removes WiFi and network connections after rebooting.

tried multiple times with restore points. windows pro 11

**Comment by exostalker** [comment]
There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual, given the timing quite likely culprit.

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.
