### ISSUE TITLE
Blue Screen Errors (BSOD) on Fresh Windows Install after Using Tool

### ISSUE THREAD

**Issue by LorandMarton** [ChrisTitusTech/winutil#757]
**Summary:**
Upon using the tool on a fresh Windows install, my system became unstable and unresponsive, leading to multiple occurrences of the Blue Screen of Death. The BSOD errors were predominantly "IRQL_NOT_LESS_OR_EQUAL". I had to reinstall the operating system twice.

**Detailed Error Reports:**
I experienced the following blue screen errors:

1. IRQL_NOT_LESS_OR_EQUAL 
    - Stop Code: 0x0000000a 
    - Parameters: 00000000`00000008, 00000000`00000002, 00000000`00000000, fffff803`35219942
    - Caused by: ntoskrnl.exe (ntoskrnl.exe+3fbca0)

2. IRQL_NOT_LESS_OR_EQUAL 
    - Stop Code: 0x0000000a 
    - Parameters: 00000000`00000008, 00000000`00000002, 00000000`00000000, fffff802`4c819942
    - Caused by: ntoskrnl.exe (ntoskrnl.exe+3fbca0)

3. IRQL_NOT_LESS_OR_EQUAL 
    - Stop Code: 0x0000000a 
    - Parameters: 00000000`00000008, 00000000`00000002, 00000000`00000000, fffff804`3668bc9d
    - Caused by: intelppm.sys (intelppm.sys+11be)

**Steps to Reproduce:**
1. Install and open the tool.
2. Navigate to the "Tweaks" section.
3. Enable the "Set Services to Manual" option.
4. Run the "Tweaks".

**Expected Behavior:**
The system should continue to operate smoothly with the chosen tweaks (recommended for laptop) applied.

**Observed Behavior:**
The system becomes unstable and unresponsive, leading to multiple blue screen errors.

**Workaround:**
Upon reinstalling the operating system for the third time, I avoided enabling the "Set Services to Manual" option within the tool, which led to stable system performance.

Windows 10 Pro N, 22H2, os build: 19045.2965

**Comment by YusufKhalifa1** [comment]
Did installed the latest updates ?

**Comment by YusufKhalifa1** [comment]
Did you install the latest updates of windows ?

**Comment by LorandMarton** [comment]
Yes

**Comment by exostalker** [comment]
There's a bug now that disables Windows Management Instrument (WMI) instead of making it manual - while your exact issue is quite different, I'd still try this out as even if you didn't get blue screen errors, you'd have to apply this for windows and quite a few programs to work correctly:

https://github.com/ChrisTitusTech/winutil/issues/735
Basically just do the same steps but set it to manual (instead of disabled) and start it.

**Comment by ChrisTitusTech** [comment]
Fixed in patch #764
