### ISSUE TITLE
Ultimate Perfomance Profile don't shows up.

### ISSUE THREAD

**Issue by Pleusch** [ChrisTitusTech/winutil#759]
**Describe the bug**
Ultimate Perfomance does not show up.

**To Reproduce**
Fresh Windows 11 Setup, FullUpdate, Run Script

**Expected behavior**
Ultimate Perfomance Plan shows up.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/129837690/5937bc6f-fd32-4024-a2b9-0fa7c2d8132e)

**Additional context**
Manual Setting doesn't work either.

![image](https://github.com/ChrisTitusTech/winutil/assets/129837690/a7b0971f-9a08-49fe-9e77-256c5212d180)

**Comment by ChrisTitusTech** [comment]
Should show up after rebooting. Does it not?
