### ISSUE TITLE
Better readme and repo description

### ISSUE THREAD

**Issue by ofersadan85** [ChrisTitusTech/winutil#76]
Sorry if this has been stated before or if this is on purpose, but IMO this repo could really use more description as to what it intends to do.

I came across this repo just exploring on GitHub and had no idea what it's supposed to be, but it does have stars and issues so it must be relevant to something, right? It was only after that I realized who the repo belongs to and I know your YouTube channel.

If I hadn't recognized the repo owner from YouTube I would have just moved on. A description (and a few screenshots perhaps?) would really help users just stumbling in here.

**Comment by Firecul** [comment]
Yeah, something similar to https://christitus.com/windows-tool/ would be good

**Comment by ChrisTitusTech** [comment]
Thanks added some quick explainers and a screenshot.
