### ISSUE TITLE
Services are broken after using latest version

### ISSUE THREAD

**Issue by jedenzet** [ChrisTitusTech/winutil#762]
**Describe the bug**
Latest version of this utility literally breaks windows services. I'm unable to start Security Center service and i can't even use a "taskkill" command. I'm also having problems with installing programs for example "elgato wavelink" that "terminates prematurely because of error".

**To Reproduce**
Just use the utility

**Screenshots**
https://i.ibb.co/XVqrC3q/ct1.jpg

https://i.ibb.co/KWwZBbY/ct2.png

Also there is no WMI service in my services panel.

**Comment by jedenzet** [comment]
OK my bad - there was a problem with translation. I've found the WMI service and it works now.

Feel free to delete this.

**Comment by ChrisTitusTech** [comment]
Just patched so this doesn't happen #764
