### ISSUE TITLE
Post-Tweak Issues:

### ISSUE THREAD

**Issue by miqumi** [ChrisTitusTech/winutil#763]
**Describe the bug**
I decided to perform the 'laptop' tweaks preset, 
which has the tweak enable manual services,
which stops a LOT of services and increases file operation times for me
also I use tasklist and taskkill VERY frequently, so this is really annoying.
I want to revert but because CIM is now a manual service, it cant undo the tweaks
**To Reproduce**
Already explained

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/80510430/3bfd9b01-7472-47e1-9225-34c2adcefb47)
![image](https://github.com/ChrisTitusTech/winutil/assets/80510430/bf46caa8-daa3-4e8d-a10a-77b762752920)

**Comment by ChrisTitusTech** [comment]
Resolved in #883
