### ISSUE TITLE
Right Taskbar

### ISSUE THREAD

**Issue by rachampo** [ChrisTitusTech/winutil#770]
As a Windows 10 user, I liked being able to move my taskbar to the right side of the screen so that I can see all of the windows I have opened without them collapsing into one icon, but Windows 11 does not allow me move the taskbar.

**Describe the solution you'd like**
I would like to have the ability to move the taskbar to the left or right of my screen, like in Windows 10, and not have the windows collapse into an icon.

**Describe alternatives you've considered**
There appears to be a fix with Explorer Patcher App but I am unsure of this app.

**Comment by ChrisTitusTech** [comment]
I won't patch explorer, but the https://github.com/valinet/ExplorerPatcher looks legit to me. If you really want this functionality I don't see an issue with using it.
