### ISSUE TITLE
Remove ALL MS Store Apps - unable to uninstall due to Security setting

### ISSUE THREAD

**Issue by GPTDesign** [ChrisTitusTech/winutil#771]
Installed a fresh download of Win10 Pro 64bit to a Dell Optiplex 9010 desktop.   Installed Chris Titus Windows Toolbox.   On Config window selected "Remove ALL MS Store Apps".   Ran utility but get messages on each of the Win Store apps that Toolbox was "unable to uninstall due to security setting".     On the new Win10 install I did not set up a new user account, thus I have an Administrator account and a Public Account.    I am running Windows Toolbox in the Administrator mode.   Basically a clean Win10 install then only thing installed was Windows Toolbox.    Tried to reboot machine and run Win Toolbox again but same result.  Attached a screen copy of the Windows Tool Box screen display hereto which shows the failed results.   Anyone have any suggestions on why what security setting I need to change.    Would have thought it would already be correct as it was a 100% clean Win10 install with only Windows Toolbox installed and used.
  
![Screen Copy CTT Windows Toolbox - failed Remove MS Store Apps](https://github.com/ChrisTitusTech/winutil/assets/117490520/6f78df59-e98b-4fb7-8969-d88ba1188562)

**Comment by DeveloperDurp** [comment]
Even though you are running the script on your admin account Windows still requires you to launch powershell "As Admin" to get elevated privileges

**Comment by GPTDesign** [comment]
I had the Titus Toolbox shortcut on the desktop of the Administrator.   Apparently that does not give you full administrator permission when you double click and open the Titus Toolbox as per your suggestion I right clicked the Titus Toolbox on the Administrator desktop and selected "Open As Administrator" and when it opened and I clicked to "Remove Windows Store Apps" it proceeded and very quickly uninstalled those MS Store apps.     Thanks for assistance.  Problem solved.
