### ISSUE TITLE
Add more applications

### ISSUE THREAD

**Issue by KOX599** [ChrisTitusTech/winutil#772]
**Thanks for adding this applications**

.NET 7.0
https://dotnet.microsoft.com/en-us/download/dotnet/7.0

.NET 8.0
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

DirectX End-User Runtimes (June 2010)
https://www.microsoft.com/en-us/download/details.aspx?id=8109

Nvidia Profile Inspector
https://nvidiaprofileinspector.com/download-nvidia-profile-inspector/

 MSI mode utility v3
https://forums.guru3d.com/threads/windows-line-based-vs-message-signaled-based-interrupts-msi-tool.378044/

MSI Afterburner
https://www.guru3d.com/files-details/msi-afterburner-beta-download.html

RTSS
https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html

ThrottleStop
https://www.techpowerup.com/download/techpowerup-throttlestop/

Logitech G HUB
https://www.logitechg.com/en-us/innovation/g-hub.html

Display Driver Uninstaller
https://www.guru3d.com/files-details/display-driver-uninstaller-download.html

**Comment by ChrisTitusTech** [comment]
Adding to #374
