### ISSUE TITLE
Can not update winget

### ISSUE THREAD

**Issue by DiscusZ** [ChrisTitusTech/winutil#780]
**Describe the bug**
I just grabbed the lastest winutl and went into the installs section to do upgrade all and it fails

**To Reproduce**
go to tweaks
click on upgrade all

**Expected behavior**
upgrade  should upgrade files

**Additional context**

Failed in attempting to update the source: winget
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
Press Enter to continue...:

**Comment by d0x360** [comment]
Did you happen to verify if the url being used is correct?  Like put it in a browser and see if it downloads?  

The app is wrong or the repo doesn't have the file for some reason I'm just curious which and whether anyone else has run into this?

If you use Adguard for Windows id disable it anytime you're using Winget to install or update.  It shouldn't ever cause an issue but sometimes a freak glitch will have it cause an issue lol.  Super rare like 1:100k but it happens.

**Comment by ChrisTitusTech** [comment]
working on implementing a new install method using #347
