### ISSUE TITLE
Allow a selection of software to upgrade and not just all of it.

### ISSUE THREAD

**Issue by OceanBlade95** [ChrisTitusTech/winutil#781]
**Is your feature request related to a problem? Please describe.**
There only appears to be a way to upgrade everything at once, and not just a select few applications. It feels counterintuitive to remove Edge with tweaks just to upgrade it on accident with the Update All button.

**Describe the solution you'd like**
A button that only upgrades the selected applications.

**Comment by d0x360** [comment]
+1

**Comment by Stibax** [comment]
+1
