### ISSUE TITLE
Security Updates Only are not being set properly

### ISSUE THREAD

**Issue by dennyamarojr** [ChrisTitusTech/winutil#784]
**Describe the bug**
The bug is when you click to set Updates to security only, the regedit keys are not create and the powershell command fail to apply the tweak

**To Reproduce**
1. Go to 'Updates'
2. Click on 'Security (Recommended) Settings'
3. And take a look at the powershell window to see the error messages

**Expected behavior**
Apply the Security Updates Only

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/36896116/a4e7393e-caf7-4141-b61b-0bc4236f94c2)

**Additional context**
Here's the line where need to be fixed
https://github.com/ChrisTitusTech/winutil/blob/main/winutil.ps1#L1927

Currently are using Set-ItemProperty, maybe it's better to use New-ItemProperty or add a If Test-Path

**Comment by ChrisTitusTech** [comment]
Thanks, I made a check to create the path if it doesn't exist. 

Commit ad06812
