### ISSUE TITLE
Updates tools are NOT properly working

### ISSUE THREAD

**Issue by farshadt3** [ChrisTitusTech/winutil#79]
Updates tools are NOT  properly working . if you choose |Security (Recommended) Settings| option and then you decide to make the Default settings it will gives you an error . Windows update reset tool also doing nothing at all. I'm using Windows 10 21H2 build 19044.1806
![Capture](https://user-images.githubusercontent.com/100499239/178252388-b3ab76f9-fa2b-4c66-9fa4-cd2ba455c757.PNG)

**Comment by ramjavi** [comment]
Hi Chris, thanks for your great work!!

Same problem here, in adition, in "config", "reset windows update" button does not respond.

Tested on a Ryzen 5 2600, with 16gb of memory, Windows 11 Pro 21H2 build 22000.795

Setting BITS StartupType to Automatic
Setting wuauserv StartupType to Automatic
Enabling driver offering through Windows Update...
Enabling Windows Update automatic restart...
Enabled driver offering through Windows Update
1. Stopping Windows Update Services...
2. Remove QMGR Data file...
3. Renaming the Software Distribution and CatRoot Folder...
4. Removing old Windows Update log...
5. Resetting the Windows Update Services to defualt settings...
6. Registering some DLLs...
7) Removing WSUS client settings...
ERROR: El sistema no ha podido encontrar la clave o el valor del Registro
especificados.
ERROR: El sistema no ha podido encontrar la clave o el valor del Registro
especificados.
ERROR: El sistema no ha podido encontrar la clave o el valor del Registro
especificados.
8) Resetting the WinSock...
9) Delete all BITS jobs...
10) Attempting to install the Windows Update Agent...

ERROR: La variable '$arch' no se puede recuperar porque no se ha establecido.
ERROR: en <ScriptBlock>, <sin archivo>: línea 1342 ERROR: en <ScriptBlock>, <sin archivo>: línea 1489 ERROR: en <ScriptBlock>, <sin archivo>: línea 1
ERROR EXCEPTION: System.Management.Automation.RuntimeException: La variable '$arch' no se puede recuperar porque no se ha establecido. ERROR EXCEPTION:    en System.Management.Automation.VariableOps.GetVariableValue(VariablePath variablePath, ExecutionContext executionContext, VariableExpressionAst varAst) ERROR EXCEPTION:    en System.Management.Automation.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame) ERROR EXCEPTION:    en System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Sleeping for 60m to give you time to look around the virtual machine before self-destruction...

**Comment by YeetusBaboon** [comment]
Amazing work, but I have a similar issue:

It's the exact same except for a couple of things
![image](https://user-images.githubusercontent.com/83467783/179645327-9b862c00-d3be-44d1-9723-ee1becbefb37.png)

ie. the variable $arch cannot be found, and `ERROR: The system was unable to find the specified registry key or value.` during step 7

**Comment by janleigh** [comment]
Bump. Having the same issue too.

**Comment by Kaleidosium** [comment]
Same problem sadly :/

**Comment by Greninja9559** [comment]
I have the same issue on my Ryzen 7 4700U system

**Comment by ChrisTitusTech** [comment]
Fixed in latest PR #94 merge
