### ISSUE TITLE
Microsoft PowerToys

### ISSUE THREAD

**Issue by martin-braun** [ChrisTitusTech/winutil#790]
**Is your feature request related to a problem? Please describe.**
I want to remap some keys on many machines, it would be nice to have the Keyboard Manager from the PowerToys available via this utility.

**Describe the solution you'd like**
One-Click installation of https://github.com/microsoft/PowerToys

**Describe alternatives you've considered**
Running winget myself, but this tool could incoorperate it.

**Comment by TakenMC** [comment]
Powertoys is already in the install tab under Microsoft tools

**Comment by martin-braun** [comment]
@TakenMC I'm blind, thanks!!
