### ISSUE TITLE
Visual Studio and maybe other programs won't get detected

### ISSUE THREAD

**Issue by nyaruku** [ChrisTitusTech/winutil#794]
I clicked "Get Installed" but visual studio is not ticked thought it is installed but not on my C: drive but on my D:
![image](https://github.com/ChrisTitusTech/winutil/assets/38096703/5212c84b-993c-4f1e-8ab2-4a74d4bbe5ac)

**Comment by jonasaugust** [comment]
I had winutil install vscode for me to C: drive, but it wasn't detected with "Get Installed".  "Github Desktop" wasn't detected the same way either.

**Comment by jonasaugust** [comment]
Thanks. I just tried the latest version, and now "VS Code" is detected as expected.  Unfortunately, now "VS Codium" is detected, but I never installed it manually nor from winutil.
