### ISSUE TITLE
Bug: Leftover BullseyeCoverageError artifact left on system

### ISSUE THREAD

**Issue by dreamsyntax** [ChrisTitusTech/winutil#797]
**Describe the bug**
There will be a file `BullseyeCoverageError.txt` in your user folder.
with:
```
2023-05-18 16:47:03 BullseyeCoverage 8.25.21 error 15: Cannot find C:\Windows\Temp\450f2cb794f852902387d866d5a40b76cea449/test.cov, errno=2 "The system cannot find the file specified. ". COVFILE is not set. Program=c:/Users/gjayap/HaraHaraMahDev/ibt_core-win-hsw/ibt_win_src/06-host_sw/win/bin/setupres/Release/Win32/setupenu.dll
```

**To Reproduce**
1. Run the tool. Use recommended option for laptop. Also remove all MS Store, and remove Edge.
2. Check your User folder

ex:
`C:\Users\user\`

**Expected behavior**
No log artifacts leftover that are not explicitly stored in the expected resulting logs

**Comment by ChrisTitusTech** [comment]
Unable to replicate error.

**Comment by dreamsyntax** [comment]
Confirmed in the 07.23.20 version this is no longer reproducible.

**Comment by shreyas-malhotra** [comment]
A quick google search brings up that the artifact file left on the system in related to an Intel driver installation, and not winutil.

https://community[.]intel[.]com/t5/Wireless/BullseyeCoverageError-txt-text-file-in-Windows-user-directory/td-p/1471436
