### ISSUE TITLE
Widgets pannel on Win11 gets hidden as soon as they Appear

### ISSUE THREAD

**Issue by GDM-Music** [ChrisTitusTech/winutil#799]
So, after running this script on several windows 11 machines, i can assure that all of them had the same issue
So, basically when you press Win+W to get widgets pannel, it disappreas

![er7LrEuGJB](https://github.com/ChrisTitusTech/winutil/assets/95571677/760bc180-908e-4a49-be64-9717b9939c81)

**Comment by ChrisTitusTech** [comment]
Unable to  replicate. I just did a fresh tweaks installs and this did not happen. 
I'd recommend doing an undo all tweak and then just doing the desktop recommended tweaks.
