### ISSUE TITLE
one liner command on readme

### ISSUE THREAD

**Issue by sabaasa** [ChrisTitusTech/winutil#802]
**Is your feature request related to a problem? Please describe.**
yes, the issue is that the launching commands mentioned in the readme page of this tool always uses http to connect which can cause security issues. (irm christitus.com/get | iex)

**Describe the solution you'd like**
To fix this, replace the command with `irm https://christitus.com/win | iex`

**Comment by ChrisTitusTech** [comment]
Thanks, I changed the command as I have gotten a TON of issues due to the secure channel not being used.

Funny enough I can run mine without the https:// and it works, but it makes sense that many can not. 

New commit done 63adbdb

**Comment by sabaasa** [comment]
nice! thought this issue went unnoticed lmao
