### ISSUE TITLE
Location Settings don't Work.

### ISSUE THREAD

**Issue by Pleusch** [ChrisTitusTech/winutil#803]
**Describe the bug**
I can't und disabling the location settings. I want to activate them because i want to track my notebook if it gets stolen.

**To Reproduce**
Do and undo the "Disable Location Settings"

![image](https://github.com/ChrisTitusTech/winutil/assets/129837690/5346ebaf-bbfb-4f42-aa6a-c237dc8a9196)

**Comment by TorMechia** [comment]
Having the same issue. I was unable to change this via registry, either.
A good reminder to make backups…

**Comment by ChrisTitusTech** [comment]
You can also just undo tweaks as this is considered privacy setting that the script would disable.

**Comment by keiz-7** [comment]
> You can also just undo tweaks as this is considered privacy setting that the script would disable.

This is still an issue, undoing the tweak didn't fix the error, and it still says setting is managed by organization

**Comment by TorMechia** [comment]
To add on to keiz, I believe I had a similar issue, where "undoing" the change would still result in location settings being locked behind organization rules. I didn't mention it as I had assumed I had simply done something wrong, and tried to fix it manually via registry edit.
