### ISSUE TITLE
Add Granular Privacy Tweaking / W10Privacy

### ISSUE THREAD

**Issue by TCB13** [ChrisTitusTech/winutil#807]
Hello,

This is a nice tool, however I've noticed it lacks a more detailed/granular approach to removing Window's built-in features and apps that can be considered spyware by some.

It would be nice to have settings like the ones https://www.w10privacy.de/english-home/ provides. That application include dozens of group policy / registry tweaks:

![Screenshot 2023-05-29 233037](https://github.com/ChrisTitusTech/winutil/assets/6315832/baab8519-6511-4b5d-a685-473cf991d6b7)

Thank you.

**Comment by ChrisTitusTech** [comment]
Most of these are done by default in the Tweaks setting and when O&O shutup is run with recommended settings. 
Too redundant to make it worth running.
