### ISSUE TITLE
Git for Windows SDK (build-extra)

### ISSUE THREAD

**Issue by martin-braun** [ChrisTitusTech/winutil#808]
**Is your feature request related to a problem? Please describe.**
Contrary to Git for Windows, the Git for Windows SDK also comes with `pacman` which allows to install additional tools such as `tmux`.

**Describe the solution you'd like**
One-Click installation of [Git for Windows SDK](https://gitforwindows.org) (scroll all the way down)
Releases are listed here: https://github.com/git-for-windows/build-extra/releases

**Describe alternatives you've considered**
It's not even available on `winget`, I opened an issue about it: https://github.com/microsoft/winget-pkgs/issues/108378

I just installed it manually, but it would be exceptionally great to have it available with a simple click.

**Comment by ChrisTitusTech** [comment]
I'll look at replacing Git when this becomes available through winget or chocolately. Closing this issue for now.

**Comment by martin-braun** [comment]
@ChrisTitusTech Alright, just keep in mind "Git for Windows" != "Git for Windows SDK". I don't think everybody who needs `git` inherently needs its Windows SDK.
