### ISSUE TITLE
The "some features are managed by your organisation" thing is keeping me from making changes to my system.

### ISSUE THREAD

**Issue by pinngguu** [ChrisTitusTech/winutil#81]
Apparently, the tweaks are managed using the gpedit, I guess and the windows 10 Home edition doesn't have the group policy editor in it. I used the Tweaks section in the tool after I reset my Laptop and I also wanted to use the "Find My Device" function of Windows 10 which uses location services. But now, the OS thinks that my PC is a part of a WORKGROUP and I can't make any changes I want within the settings. Some settings are also greyed out because of this. (check screenshots)

I tried to Undo the tweaks but it didn't change anything. Either I will have to live this way or I should again reset my PC which is frustrating at this point. I installed gpedit and followed some steps from the Net to take control but nothing's helping now.

Please suggest any fix for this.

![SystemPropertiesAdvanced_qUTjEiLO1F](https://user-images.githubusercontent.com/42733592/178715977-f49400fc-6939-4b7b-9e34-876f43425ba3.png)
![ApplicationFrameHost_Zk2evQy4rT](https://user-images.githubusercontent.com/42733592/178715988-d77033a0-9c52-4585-a91d-8138254d71ef.png)
![ApplicationFrameHost_EjzOMPc56E](https://user-images.githubusercontent.com/42733592/178715993-e3ebe6bc-fdd5-4e0e-a333-9de907b30f60.png)

**Comment by Carterpersall** [comment]
https://winaero.com/enable-gpedit-msc-group-policy-in-windows-10-home/amp/
This'll run you through how to enable gpedit in Windows Home and show a third party app that also does the same thing as gpedit

**Comment by joaomrcarvalho** [comment]
I'm on Windows 11 Pro, but can't also get rid of the "Managed by your organization" on some stuff (for example, on Microsoft Edge). 

Is there any way to revert the scripts? I already tried the "Undo all tweaks", but to no success. Even if I choose a network ID as "home", it reverts to a business network as soon as I reboot.

Thanks in advance for any help.

**Comment by joaomrcarvalho** [comment]
To give an example:
![Screenshot 2022-08-04 214513](https://user-images.githubusercontent.com/16350247/182949312-217e5834-f444-4e51-8fca-acd4351aaaf1.png)

**Comment by djust270** [comment]
> To give an example: ![Screenshot 2022-08-04 214513](https://user-images.githubusercontent.com/16350247/182949312-217e5834-f444-4e51-8fca-acd4351aaaf1.png)

This is simply because the script sets policy registry keys. Find the offending registry value and delete it https://github.com/ChrisTitusTech/winutil/blob/main/winutil.ps1

In your example, remove the value "SearchSuggestEnabled" from the registry key HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Edge. Or just delete teh entire Edge policy key if you want to control settings through the browser.

**Comment by joaomrcarvalho** [comment]
> 

Thanks! That solved it for me :)

**Comment by GraveyardPete** [comment]
I also have this problem on Windows 10 Pro, The Virus and Threat Protection and Ransomware Protection is also missing on missing on Windows Security. If I try to open it from the search bar it says this message
![image](https://user-images.githubusercontent.com/111437308/185166819-7e36a84c-dd42-4e80-b110-374d62170b11.png)

Undo tweaks also didn't fix it , I don't want to reinstall Windows if possible

**Comment by ChrisTitusTech** [comment]
Closing this as I don't do modifications to Edge or Defender.
