### ISSUE TITLE
Applications Hang, when not in full screen mode

### ISSUE THREAD

**Issue by joshthebossxl** [ChrisTitusTech/winutil#811]
**Describe the bug**
Basically Any GPU application I have that is using the Nvidia Graphics card, RTX 3070M, basically Hangs the application for a split second every few seconds, which disables my keyboard and mouse input entirely for a split second, but no frame drops

What does it do?
- Hangs the application
- Causes not Responding to show for 0.1 seconds
- Happens every few seconds
- Opening task manager makes this worse
- Happens when not on full screen
What happens?
- No frame drops on the actual game itself
- No GPU throttling
- I have uninstalled reinstalled driver, wiped driver, downgraded, still the same thing
And yes I have recently refreshed Windows and Reinstalled it, like 5 times

This happened after I ticked these options and restarted my computer on the windows 10 debloater, now, I have used the older version of this before, and it did not have this issue, something got changed and removed, that broke it. 
here is 

**To Reproduce**
1. Go to Windows 10 debloater and select these options in the picture found below
2. Click on these options
3. then restart the computer, then your applications will begin to micro freeze

**Expected behavior**
I expected things to run as normal, the last time I runned this application a few times, but this new update, seemed to break the PC itself, I have narrowed down the issues to,
It's not the GPU hardware because the game frames are not dropping, but the application itself hangs.
The GPU was working before I ran the debloater, but it messed up my application
When I run an application Full screen it does not freeze, but only when I have it windowed mode it starts to bug.
Also sometimes when I minimize the application it refuses to click back into it. 

<img width="853" alt="Windows 10 debloater options" src="https://github.com/ChrisTitusTech/winutil/assets/46633032/7952678b-88a9-4503-9217-117e28587bc3">

https://github.com/ChrisTitusTech/winutil/assets/46633032/85521d3f-3161-4098-988b-6cdf23d0a225

**Comment by ChrisTitusTech** [comment]
This could be power throttling or a service that was disabled the your GPU is depending on. Hard to to tell, but I'd undo the service and power throttling tweaks.
