### ISSUE TITLE
Single thread high usage on AM5 system

### ISSUE THREAD

**Issue by neoset404** [ChrisTitusTech/winutil#812]
**Describe the bug**
Great tool. Though these seems to be a problem with AM5 systems. After running the recommended tweaks for Desktop and restart - had the first thread of the CPU constantly at 80-90% utilisation. After reverting the changes it's back to normal. Didn't have such problem on the old AM4, but this is a new AM5 system - 7800X3D, MSI B650 EDGE. https://i.imgur.com/w9BoREG.jpg
**To Reproduce**
1. Go to 'tweaks'
2. Click on 'Desktop and apply'
3. Restart PC
4. See high utilisation on thread 1 : https://i.imgur.com/w9BoREG.jpg

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://i.imgur.com/w9BoREG.jpg)

**Additional context**
Revert changes, restart PC - all threads are normal utilisation again

**Comment by ChrisTitusTech** [comment]
I'm betting this is also in connection to svchost tweaks also referenced in #864
almost all my systems are AM5, so I can test this extensively. I'm not noticing it on the 5600X systems, so it might be something with the newer AM5 chips. I'm going to revert the svchost tweaks in the next update that should resolve this.

**Comment by neoset404** [comment]
Hello,
Thanks for the update.
I think I did a wrong assumption in this case. The problem seems related to
the bios. It happens only after a restart from bios, then after sleep or a
normal restart the thread usage is back to normal. Sorry about that.
