### ISSUE TITLE
Windows, takes more time to boot after running tweaks

### ISSUE THREAD

**Issue by ostarch** [ChrisTitusTech/winutil#813]
### Clarifications Needed

- Windows takes near about 10-15 seconds to boot after running tweaks, before tweaks it was 3-4 seconds.
- Animation is laggy (kinda without display drivers) especially window borders.
    - This thing happens even after checking a single tweak in tweaks section ( I think with the initial script running before tweaks)

**Comment by ostarch** [comment]
Windows 11 pro Version: 22H2, build 22621.1778
Device Model: HP Elitebook 840 G3
Annexed is the screenshot of tweaks applied and the other one is what is
happening when I play with windows, like resizing, moving etc.
Using SSD, WD Blue SN570 500GB

**Comment by dennyamarojr** [comment]
Hi @ostarch I couldn't see any screenshot, I will investigate what is the cause of the issue and return as soon as possible

**Comment by ostarch** [comment]
Let me try and update you

**Comment by ostarch** [comment]
Undoing previously applied tweaks fixed the animation problem, boot time is somehow still effected.

**Comment by ChrisTitusTech** [comment]
Changed all the service tweaks that should fix this in the latest pr #883
