### ISSUE TITLE
Incorrect installation of Winget instead of WinRAR

### ISSUE THREAD

**Issue by Banva23** [ChrisTitusTech/winutil#814]
**Describe the bug**
After choosing WinRAR from the "Install" section and clicking on "Install Selected," the expected installation process encounters an issue in the background. Rather than initiating the installation of WinRAR, PowerShell mistakenly attempts to install Winget once more.

**Expected behavior**
WinRAR to be installed.

**Additional context**
OS: Win 10

**Comment by ChrisTitusTech** [comment]
#815 has been merged.
