### ISSUE TITLE
Unattended sleep timer

### ISSUE THREAD

**Issue by Danderlion** [ChrisTitusTech/winutil#819]
**Is your feature request related to a problem? Please describe.**
Even with Ultimate performance power setting the computer goes to sleep. 

**Describe the solution you'd like**
Windows has a hidden unattended sleep timer that by default is 2 minutes. Disabling this all together would be best but changing it to for example 10080 minutes (1 week) would be a workaround. 

**Additional context**
The hidden menu item can be found with the following command: 

-----------------
powercfg -attributes SUB_SLEEP 7bc4a2f9-d8fc-4469-b07b-33eb785aaca0 -ATTRIB_HIDE
-----------------
it will then show up under power settings, advanced and Sleep drop down.

**Comment by ChrisTitusTech** [comment]
Thanks adding this to ultimate performance script in commit cdb394b
