### ISSUE TITLE
Error Set-ItemProperty HKLM: (3D Objects/News and Interests)

### ISSUE THREAD

**Issue by andrerfcsantos** [ChrisTitusTech/winutil#82]
**Describe the bug**
When I run the tool on a Windows 11 machine and I choose the "Desktop" tweaks to be applied, I get a message saying that the tweaks were applied, however I see some errors on the console.

**To Reproduce**
1. I open PowerShell 7 in Administrator Mode
2. I run `iwr -useb https://christitus.com/win | iex`
3. Click on the Tweaks on the left bar
4. I select and apply the "Desktop" tweaks
5. I get a message saying that tweaks are finished, but there are some errors in PowerShell (see [win-tweaks.txt](https://github.com/ChrisTitusTech/winutil/files/9102867/win-tweaks.txt) for the full PowerShell output).

**Expected behavior**
The command to not run with any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/6928620/178751676-9486a205-f36f-4ae7-b0df-d8644fb9145a.png)

**Additional context**
**OS**: Windows 11
**Terminal**: Windows Terminal (Version: 1.13.11432.0)
**Shell**: PowerShell 7.2.5 (in Admin Mode)

I was also able to reproduce the bug just opening PowerShell in Admin Mode without Windows Terminal.

**Comment by xxxLepreChAUnSxxx** [comment]
I have t he same issue too, but on windows 10

**Comment by ChrisTitusTech** [comment]
You can ignore these errors for now, but I will address this in my next update as they are harmless.

**Comment by ChrisTitusTech** [comment]
Fixed in latest update
