### ISSUE TITLE
Remove Edge doesn't remove Edge

### ISSUE THREAD

**Issue by r1spekt1** [ChrisTitusTech/winutil#822]
**Describe the bug**
The 'Remove Edge' feature doesn't remove edge at all.

**To Reproduce**
Just checking the box in the 'Tweaks' section
**Expected behavior**
Maybe I didn't understand it correctly, but I expected it to remove Edge completly. Maybe it just stops it from running in the background. If you could elaborate that would be great.

**Screenshots**

**Additional context**

**Comment by JR1994** [comment]
I am reporting the same issue. I just performed a fresh install of Windows 10 in Virtualbox. I have ran the tweak tool to remove edge then performed reboot. Edge is still installed.

**Comment by drlaserdev** [comment]
I have the same issue with my Windows 10 desktop (AMD CPU, NVIDIA GPU), but not with my QEMU/KVM windows 10 vm that runs on my laptop (Intel CPU). When I ran the script on my desktop, it did not remove edge, but when I ran it on my vm, it seemingly removed it (Doesn't launch, icon is empty).

**Comment by devbytemehedi** [comment]
does anyone know how to remove this:
![061110-11062023](https://github.com/ChrisTitusTech/winutil/assets/89072438/3ddf774f-9261-420c-9f72-14d7a52100c2)

**Comment by ChrisTitusTech** [comment]
Fixed in commit https://github.com/ChrisTitusTech/winutil/commit/b2e3def5116c391d84b47f6c38f108290ae833bd
