### ISSUE TITLE
Some services still running after excecuting tweaks

### ISSUE THREAD

**Issue by bindoet** [ChrisTitusTech/winutil#824]
**Describe the bug**
Distributed link tracking client,sysmain/superfetch still running after check disable service to manual and restart

**To Reproduce**
1. Go to tweaks
2. Click on disable service to manual
3. and run tweak and restart
4.It should stop services like distributed link tracking clients, and it clearly states stopping sysmain

**Expected behavior**
Stopping those 2 services

**Additional context**
I'll try with a bunch of different laptops, but it's still not stopping. BUT the process in Task Manager reduce like always after executing the commands.

**Comment by ChrisTitusTech** [comment]
Resolved in #883
