### ISSUE TITLE
Edge script

### ISSUE THREAD

**Issue by Adameczu** [ChrisTitusTech/winutil#829]
script that reverse deleting edge script? 

cuz a kinda wanna to test that chat gpt-4 implementation

**Comment by Sureshgorai25** [comment]
Just install edge again using script, it will work for sure.
But when you reinstall edge make sure you delete the edge icon from desktop and add it again bcz the default one which you will get after reinstalling edge won't work.
I hope this will help.

**Comment by Adameczu** [comment]
like i used script to install edge, it doesn't work, i downloaded it from ms store, same result. ( I'm tried running it through win search )

**Comment by ChrisTitusTech** [comment]
Use User Agent Switcher to test gpt on bing. I'm working on changing the script for easy reversal.
