### ISSUE TITLE
error when entering the 'iwr -useb https://christitus.com/win | iex' command in an elevated powershell in windows 7

### ISSUE THREAD

**Issue by komradstalinium** [ChrisTitusTech/winutil#83]
![bandicam 2022-07-14 14-10-36-937](https://user-images.githubusercontent.com/109290825/178990327-214784f2-0854-4999-bae9-58714070d16f.jpg)

as the image shows, everytime i try executing the command to run the program that red error shows up.
anyone knows how to fix it?

**Comment by ChrisTitusTech** [comment]
This is not compatible with Windows 7.
