### ISSUE TITLE
Nvidia GTX 1080 Led Light stopped working

### ISSUE THREAD

**Issue by S4Howie** [ChrisTitusTech/winutil#832]
Hey i used this tool to debloate my Windows10,its a great performance boost. Thank you very much. But i have one small problem. I think since i used the tool i cant control the Leds of my Nvidia 1080 anymore. If i restart my PC i can see the Leds working until Windows10 is loaded,then the Leds shutdown. In the manufacturer software i dont have buttons anymore to control the Leds.
I think its only a service that has been shutdown by the tool. Anybody has a hint for me what service i need to restart to control my Leds again?

**Comment by KonTy** [comment]
Did you use an option to start services manually, your service is probably is not starting?

**Comment by S4Howie** [comment]
Yes i used the option to start services manually, i had the same idea its just a service but i dont know what services it is.

But anyway thank for your help the problem is solved now. Honestly i cannot say if it was related to the tool or to the nvidia drivers. i used the tool and updated nvidia drivers around the same time,some days later i realized my Leds not working anymore. Some days ago there was again an update of the newest nvidia driver and since then the Leds work again and the Buttons in the manufucture software are back and i can control the Leds again. I had this on 2 different computers and both work fine since the last nvidia driver update, nothing changed in the tool or started any service. So i pretty much think it was related to the nvidia drivers but they fixed it already in the last update.
