### ISSUE TITLE
A connection cannot be established since the destination computer expressly denied such a connection.

### ISSUE THREAD

**Issue by csjdeacon** [ChrisTitusTech/winutil#833]
I leave a screenshot of the error that I get when trying to use winutil.
![Screenshot_13](https://github.com/ChrisTitusTech/winutil/assets/136196527/7c793b90-eba4-4ff2-9ee6-9de8a0d694ec)

**Comment by dennyamarojr** [comment]
Hi @csjdeacon did you read the README , there is alternative commands to run, you only try one command and report an issue
Please try the commands as showed in the screenshot, that can be found in the README of the project
![image](https://github.com/ChrisTitusTech/winutil/assets/36896116/e924ddc0-5040-4ab9-9c83-217058b182ba)

**Comment by csjdeacon** [comment]
Of course I have tried all the possible solutions as you can see in the following screenshot.
I have also used the *.exe of ctt that I bought this weekend and it also gives me an error. I also leave another capture for your assessment.
![Screenshot_16](https://github.com/ChrisTitusTech/winutil/assets/136196527/d853f9fe-0597-49f3-8ed6-f21fca1a44f9)
![Screenshot_15](https://github.com/ChrisTitusTech/winutil/assets/136196527/c5716f3f-c429-4d24-85b2-44393b00bc37)
![Screenshot_14](https://github.com/ChrisTitusTech/winutil/assets/136196527/a0068871-8cd1-4983-9767-3d266b130c5c)

**Comment by ChrisTitusTech** [comment]
looked to be an ISP block on raw github files. You will have to manually download the winutil.ps1 file to run. This happens a lot to india users as well.
