### ISSUE TITLE
discord wont run or reinstall after using upgrade all tool

### ISSUE THREAD

**Issue by killedjuso** [ChrisTitusTech/winutil#838]
** Discord wont run or reinstall after using “upgrade all” tool**

**To Reproduce**
1. Go to 'CTT TOOL'
2. Click on 'Upgrade all while on outdated discord version'
3. 
4.

**Expected behavior**
expect to see discord not be installable of able to run in any way coming up with constant errors

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/136670863/716b77c5-954a-40cd-a858-b3616e00a073)

**Additional context**
i have tried trouble shooting by uninstalling through control panel and also CTT windows utility but once uninstalled still dont allow me to reinstall even if i delete files by going in discord file directory and %temp% files, issue still is not solved and persistently shows the picture error when running discord setup file.
Trying to install discord through CTT Windows Tool seeming installs it but application wont run and shows an error 

i think while attempting to upgrade my discord the ctt tool uninstalled it but not fully and now discord wont run at all or reinstall 

PLEASE HELP ME I CANT USE DISCORD ON MY PC NOW :(

**Comment by KonTy** [comment]
What is in the setup log? Is there a better error, it is impossible to tell why it fails from your description above.

**Comment by killedjuso** [comment]
ill attach the setup error log file so you can see it 
[SquirrelSetup.log](https://github.com/ChrisTitusTech/winutil/files/11782726/SquirrelSetup.log)

**Comment by killedjuso** [comment]
when i uninstall discord it seemingly does it fine and then when i reinstall discord reinstalls fine seemingly saying in powershell that the installation was successful but then when i run discord it shows this error 
![image](https://github.com/ChrisTitusTech/winutil/assets/136670863/c7983c2c-78d9-4e62-9a7b-5eb01da6b5b6)


 (if i use actual discord setup doesnt work at all

in addition heres another error setup log file 

 
[SquirrelSetup.log](https://github.com/ChrisTitusTech/winutil/files/11782729/SquirrelSetup.log)

**Comment by KonTy** [comment]
from the log file it seems that the setup doesn't have access to Discord directory. It seems that something is holding it hostage. Maybe an opened handle to that directory. Have you tried rebooting your system before reinstalling Discord? 

try this from the terminal
ren "C:\Users\BBY\AppData\Local\Discord" "C:\Users\BBY\AppData\Local\Discordcrap"
rd /s /q "C:\Users\BBY\AppData\Local\Discordcrap"


Here is interesting entry in your log file:
`
10752> 2023-06-14 18:08:58> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'C:\Users\BBY\AppData\Local\Discord' is denied.
`

You also seem to have problems with installing Teams, it seems that you have messed access to your home directory somehow.
`
2020-06-16 11:35:27> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\BBY\AppData\Local\Microsoft\Teams\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, 
`
