### ISSUE TITLE
windows update features does not work properly.

### ISSUE THREAD

**Issue by abeSMeter97** [ChrisTitusTech/winutil#839]
**Describe the bug**
i tried in win 10 and 11 and every one of my systems updated automatically even if the setting for only security update was on, and it seems I cannot apply any of those 3 settings anymore

**To Reproduce**
1. set update to security only or stop them by clicking one of the box in the update section
2. confirmation box should appear
3.  go to windows update to verify the change
4. the pc will automatically search and download updates normally like nothing happend

**Expected behavior**
windows update working with the settings chosen in the utility

**Comment by ChrisTitusTech** [comment]
These are done with registry settings and seems to be working correctly. 
However, Windows Home might ignore some of these settings. I'll try to document this better.

**Comment by abeSMeter97** [comment]
Ty very much for the info, i will document myself.
Have a nice day!
Sebastiano

Il sab 15 lug 2023, 16:36 Chris Titus ***@***.***> ha scritto:
