### ISSUE TITLE
Run Dialogue One Line command with Admin Permission

### ISSUE THREAD

**Issue by myxxmikeyxx** [ChrisTitusTech/winutil#84]
I would like to see the read me also mention that you can use the run dialogue and type:
`powershell iwr -useb https://christitus.com/win | iex`
Then do CTRL + SHIFT + ENTER to execute the PowerShell command as administrator.

**Comment by ChrisTitusTech** [comment]
Never used this for elevation, but is interesting. I added a routine at the beginning to auto elevate so this isn't needed.
