### ISSUE TITLE
Update "Selected" option

### ISSUE THREAD

**Issue by KaiserDMC** [ChrisTitusTech/winutil#845]
**Context**

Quite often I would find myself wanting to update just a subset of the installed applications.
The reasons for this vary a lot, but for example I could give the Shell (Expanded Context Menu) app.
In said app I have made my configuration the way I use daily for version 1.7. Newer versions (1.8+) changed 
the layout of the commands and .shl file to a significant degree, resulting in me potentially having to redo 
everything after weeks of adjustments. In said context the app developer also pulls down every old version
of the software from multiple websites which makes installing an older version needlessly hard and "shady".

**Workflow of the solution I have imagined**

I think it would be great to be able to follow something similar to:
"Get Installed" -> after which user manually removes the check-marks for the app that they do not want to update ->
"Update Selected" -> all selected apps are updated

**Alternatives I've considered**

I have considered manually using "winget pin" from the Powershell experimental branch, but this is not a great solution 
as of now as I would need to manually do it and not from the winutil itself. Other option is to manually go through the 
winget update list and type the updates for each app individually.

**Summary**

All in all, I think it would be amazing if this feature is possible to implement and it would be beneficial for quite a few people.
I appreciate all the good work y'all are putting in this tool. Keep it up!

**Comment by KonTy** [comment]
Hmm but that feature already exists, it seems right? Am I missing something?

![image](https://github.com/ChrisTitusTech/winutil/assets/9524513/18777e04-9d8c-4994-a115-aeaa7d92dc3f)

**Comment by YTBuzzles** [comment]
I was going to post the same issue, I have some issues where apps wont update because of different hash's and some that I don't wish to update. The update all button is a very helpful feature and would be enhanced with an "Updated Selected" as KaiserDMC said or even a whitelist that the user could provide. Thanks for your amazing work on the winutil tool!

**Comment by akintelligentmedia** [comment]
Same here!

Also thanks Chris for this lovely tool!
