### ISSUE TITLE
Issues hygiene

### ISSUE THREAD

**Issue by KonTy** [ChrisTitusTech/winutil#849]
I've noticed that there are a lot of issues that have been resolved but have not been marked as resolved/fixed whatever. This makes it hard to search and triage real issues. Chris tisk, tisk, tisk! This has to be fixed.

**Comment by ChrisTitusTech** [comment]
Agreed, I'm spending the next month on this and have already removed over 100 issues this week.
Way to pile on another issue! AHHHHHHGgasdfgasghlkjj;at;ouhagsdf;olihasge;oihags;ioj.
