### ISSUE TITLE
Windows 11 home edition : nothing works

### ISSUE THREAD

**Issue by jediafr** [ChrisTitusTech/winutil#85]
Description : 
The utility doesnt do installations or tweaks from a local account (user not adminin).

**To Reproduce**
1. Powershell with elevated administrator (since the account is user)
2. Click Install
3. The box display the status as installed 
4. The app isnt not in the windows launcher nor is ticked in the winutil's gui 

**Expected behavior**
An actual installation of the chosen app (or feature)

**Additional context**
When winutil is opened through a powershell , there is no message indicating an error.

**Comment by ChrisTitusTech** [comment]
This should be fixed with latest PR #94 merge
