### ISSUE TITLE
INSTALLATION ERROR AFTER TWEAKS

### ISSUE THREAD

**Issue by Krinkau** [ChrisTitusTech/winutil#850]
Uploading 2023-06-20 16-22-59.mp4…

SO since i did the tweaks, i am having this error, it shows this error in many installations and uninstallations, pls help****

**Comment by KonTy** [comment]
fix the video? maybe post the log file? log file for winutil is located here "notepad %temp%\winutil.log"

**Comment by Krinkau** [comment]
ok i reset my pc, installed (atlas os) now this error is happening with me, (after running laptop tweaks in chris tweaks), my taskbar not functoing properly

**Comment by Krinkau** [comment]
i reset my pc

**Comment by KonTy** [comment]
well do you realize that Atlas PC removes pretty much everything, Including Windows defender? Who knows what kind of mods you have on your computer. It might not be WinUtil at all. Or it might be the combination of the two. And with the data you provided it will be impossible to troubleshoot the issue. It's like saying: "My car doesn't work, what do I need to do to fix it?" You can't possibly know it without looking, debugging, triaging first. :)
