### ISSUE TITLE
Unable to install Malwarebytes

### ISSUE THREAD

**Issue by Finale8713** [ChrisTitusTech/winutil#853]
**Describe the bug**
When I attempt to install Malwarebytes I get the error "Installer hash does not match; this cannot be overridden when running as admin"

**To Reproduce**
I have tried this on multiple machines and I still get the same error. 

**Expected behavior**
Would like it to install Malwarebytes.
 
**Screenshots**
<img width="617" alt="Capture" src="https://github.com/ChrisTitusTech/winutil/assets/128086451/308d416b-d438-4059-af53-937a792821fb">

**Comment by ChrisTitusTech** [comment]
This is currently a bug in winget (https://github.com/microsoft/winget-cli/issues/1812)
Should be resolved soon, but we are also working on using chocolatey when this happens in the future.
