### ISSUE TITLE
Remove "internet printing client"

### ISSUE THREAD

**Issue by githubtar** [ChrisTitusTech/winutil#857]
Turn windows features on or off:
Need to disable "internet printing client" see https://www.digitalcitizen.life/what-are-those-windows-features-you-can-add-or-remove/
also remove other unneeded features, see https://www.digitalcitizen.life/what-are-those-windows-features-you-can-add-or-remove/

**Describe the solution you'd like**
Add an option to remove these: https://www.digitalcitizen.life/what-are-those-windows-features-you-can-add-or-remove/

**Comment by Davidgithub1** [comment]
See: https://www.makeuseof.com/which-windows-11-services-disable/

**Comment by ChrisTitusTech** [comment]
I added a few tweaks (AJRouter and the Kiosk Service being disabled), but internet printing and biometrics are used by many. Not something I'd put in the general tweaks. 
Added commit 4ec3099
