### ISSUE TITLE
Offline version won't run

### ISSUE THREAD

**Issue by WirelessSwitcher** [ChrisTitusTech/winutil#859]
I confirmed the digital signature is there and I am running as admin, but it won't run.

Steps:
1. Purchased and downloaded the file "winutil-offline-encrypted.7z";
2. Transferred to a completely offline VM;
3. Extracted the file on C:\Installs;
4. Right-click and selected "run as admin";
5. I see some errors, but terminal auto-closes before I'm able to check what are they.

**Comment by ChrisTitusTech** [comment]
This is typically from an Antivirus interacting with it. I'm working on releasing a new offline version that will bypass this limitation, so you don't have to disable all antiviruses.
