### ISSUE TITLE
JPEGView as screenshot tool option

### ISSUE THREAD

**Issue by ong-yinggao98** [ChrisTitusTech/winutil#862]
**Is your feature request related to a problem? Please describe.**
[JPEGView](https://github.com/sylikc/jpegview) is a fast and minimalist image viewer that would be great as an alternative option to ImageGlass.

**Describe the solution you'd like**
JPEGView as an option for installation/uninstallation.

**Describe alternatives you've considered**
ImageGlass is the other option and has had a controversial history with Spider integration which made me switch back to JPEGView since I had used it on my previous machine.

**Additional context**
NIL

**Comment by ChrisTitusTech** [comment]
Added to #374
