### ISSUE TITLE
restoring windows updates does not work

### ISSUE THREAD

**Issue by nyydynasty** [ChrisTitusTech/winutil#868]
**Describe the bug**
I initially ran the "recommended" settings for windows updates but decided I want to roll them back to default.  Now, I get this error during windows updates:

**Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.391.3926.0)
Install error - 0x80070643**

**To Reproduce**
1. Run windows updates

**Expected behavior**
that antivirus update should install

**Additional context**
I ran the windows troubleshooter and it claims to find missing registry entries and it says it put it back but i dont think that works either.  Every time I run it, it says it found missing entries but never actually fixes the issue.

**Comment by ChrisTitusTech** [comment]
Unable to replicate. Switched between both recommended and default... also restored windows update via config tab. Everything still works.

**Comment by YSKNM** [comment]
I've encountered the same issue as well, only pops up with security updates

even startup repairs don't function, saying that they couldn't fix my pc

do i just reinstall windows or just switch to linux at this point

(currently using win 10 pro)
