### ISSUE TITLE
Windows 10 Home edition Error as included

### ISSUE THREAD

**Issue by Eagle99** [ChrisTitusTech/winutil#87]
![erroriwr](https://user-images.githubusercontent.com/3813185/180575493-90147d53-7bd7-44f6-9b3f-60cfa279fabf.JPG)

with out the powershell the command alone in your website just shutdown the powershell window and nothing happens afterwards

**Comment by ChrisTitusTech** [comment]
don't use powershell command you are already in it.
The command should work now just using the 
`iwr -useb https://christitus.com/win | iex`
There was a bug I fixed that caused the instant close action.
