### ISSUE TITLE
Winget error 0x8a15000f when trying to upgrade or install programs.

### ISSUE THREAD

**Issue by QugaX** [ChrisTitusTech/winutil#872]
**Describe the bug**
The bug occurs when trying to upgrade or install programs from the utility. A seperate PowerShell window opens to show the upgrade/install progress, and then checks for whether Winget is installed. After the checks, it produces "0x8a15000f : Data required by the source is missing". A quick search online suggests to try 'winget source update' or 'winget source reset' but it unfortunately didn't fix the error.

**To Reproduce**
1. Go to 'PowerShell' and run as administrator
2. Click on 'Upgrade All' inside the utility
3. Alternatively check an application to install and click 'Install Selection'
4. Error is displayed

**Expected behavior**

**Screenshots**
[https://imgur.com/a/6EaxINc](url)

**Comment by ChrisTitusTech** [comment]
I'm changing the way winget is installed and used via #347 and also updating some calls that should work with other versions of powershell. 

Sometimes newer version of powershell core don't work properly with the script. It also could be winget being out of date on your machine.
