### ISSUE TITLE
Brave Browser can't be updated if installed via winutil.

### ISSUE THREAD

**Issue by SinisterSpatula** [ChrisTitusTech/winutil#873]
**Describe the bug**

**To Reproduce**
1. Install Brave via winutil.
2. Wait until new brave version becomes available.
3. Brave tells you it can't update.
4. You have to uninstall brave and install using their installer instead.
5. more information is [here](https://support.brave.com/hc/en-us/articles/360042816611-Why-isn-t-Brave-updating-automatically-on-Windows-)

**Expected behavior**
Brave should be able to update itself after installation via winutil (ideally).  Or support for it should be removed perhaps.

If this isn't caused by the way winutil installs brave then my apologies for wasting your time.  Please forgive me.

**Comment by ChrisTitusTech** [comment]
This is an issue that is with Winget. They should fix this in the next update, but there is nothing I can do to remedy this.
