### ISSUE TITLE
how to reinstall cortana and fix search

### ISSUE THREAD

**Issue by yossefaymen00** [ChrisTitusTech/winutil#874]
i made remove cortana tweak with no restore point , my search is broken now how to reisntall cortana and fix my search

**Comment by ChrisTitusTech** [comment]
You'll need to do a DISM /RestoreHealth with sources from a Windows Install Disc. 

Here is a link on how to repair this: <https://christitus.com/fix-corrupt-windows-install/>

I'm going to move these options into an ADVANCED USER ONLY section as they permanently modify windows. You could also upgrade your Windows verison if its not already on the latest version and it will fix the issue as well.
