### ISSUE TITLE
some features do not work

### ISSUE THREAD

**Issue by DigitalNXZ** [ChrisTitusTech/winutil#877]
**Describe the bug**
i clean reinstalled windows.
when i try to remove edge and all ms store apps the tool just gives me simply a "done" message.
i tried poweshell and powershell 7 as admin, another tool had the same, some things didn't work like open the admin console for "winget".. while the non-admin version opened the console?! this sounds to me like windows did change something or it already broke while doin' a reinstall? 

i did it on a Admin Profile with Admin and without and the same with a User Profile.

**To Reproduce**
- no error in the console

**Expected behavior**

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/53005759/02e4d720-09bc-4683-aac3-d2aa537a435c)

**Additional context**

**Comment by ChrisTitusTech** [comment]
I'm going to revamp Misc. Tweaks to work better in an upcoming update.
