### ISSUE TITLE
MY WINDOWS BROKE

### ISSUE THREAD

**Issue by dazozelm23oz** [ChrisTitusTech/winutil#879]
**Describe the bug**
so like you know when u are installing something and it asks u to select a location for example u select a drive it freezes for a minute before doing that same when i open my laptop it takes 10x the time it used to take

**To Reproduce**
1. Go to 'powershell admin.'
2. Click on 'paste the script'
3. Scroll down to '.i dont remember what i clicked on in the these '

**Expected behavior**
it should work normally

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/139470555/ef555f61-0133-400f-8323-9a4925775c34)

**Additional context**

**Comment by dazozelm23oz** [comment]
https://youtu.be/T-04Z2hN-E0

**Comment by ChrisTitusTech** [comment]
This is probably the BitLocker Encryption service being disabled. Check it in your services.msc and make sure its set to automatic.
![image](https://github.com/ChrisTitusTech/winutil/assets/7896101/73a0509e-0f2c-4260-87c2-971d3ca78407)
