### ISSUE TITLE
it just can't run

### ISSUE THREAD

**Issue by Manueliv** [ChrisTitusTech/winutil#88]
![captura01](https://user-images.githubusercontent.com/109868949/180615615-c95a0aec-e759-481a-ae0e-5899da485edb.PNG) the error says: iwr : Request aborted: Unable to create SSL/TLS secure channel. I have tried it on 3 computers and only on one did it run correctly, on two others I have the same error.

**Comment by mrpraveen401** [comment]
I am having same issue

**Comment by SamSirry** [comment]
The same here, on Windows Version 10.0.19043.1826

**Comment by mrpraveen401** [comment]
Ok I just checked that I had installed a firewall app which wasn't allowing powershell to download to tool and now I have uninstalled the application and it works fine.

**Comment by SamSirry** [comment]
True, @mrpraveen401, but also github is not allowing connections from Syria. Politics are dumb.

**Comment by Firecul** [comment]
> Politics are dumb.

Yeah 😢

**Comment by Manueliv** [comment]
After searching for solutions and trying many ways for several days, I found the solution to this specific problem,
To avoid the error use the following code, before executing the script: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by ChrisTitusTech** [comment]
Fixed in PR #94
