### ISSUE TITLE
rest network

### ISSUE THREAD

**Issue by Krisdion** [ChrisTitusTech/winutil#882]
I tried your new update with network reset, and it seems like it's not working on my end. In the PowerShell, it says "resetting network with netsh," but nothing happens, and I have no clue why it doesn't work

**Comment by ChrisTitusTech** [comment]
Just found the issue, Thanks for reporting it I'll get this in the next update!

**Comment by ChrisTitusTech** [comment]
Fix pushed to test branch 92e302d
