### ISSUE TITLE
Kaspersky Interference 

### ISSUE THREAD

**Issue by Coldtrain320** [ChrisTitusTech/winutil#887]
Event: Visit to a website was prevented
User: 
User type: Initiator
Application name: powershell.exe
Application path: C:\Windows\System32\WindowsPowerShell\v1.0
Component: Safe Browsing
Result description: Blocked
Type: Malicious link
Name: https://christitus.com/images/logo-full.png
Precision: Exactly
Threat level: High
Object type: Web page
Object name: logo-full.png
Object path: https://christitus.com/images
Reason: Cloud Protection

How to let my anti-virus to allow it

**Comment by ChrisTitusTech** [comment]
Kaspersky hates me... they block my website. 
You can bypass it by referencing the raw file from the example in the README on the homepage of winutil
