### ISSUE TITLE
typo under hover information for "disable storage sense" option

### ISSUE THREAD

**Issue by rgndxzzk** [ChrisTitusTech/winutil#889]
1. click on the tweaks tab
2. hover over storage sense
3. "[...] but often runs at **wierd** times [...]

![image](https://github.com/ChrisTitusTech/winutil/assets/81023378/8e086464-8529-4b3d-a11d-48d526757799)

**Comment by ChrisTitusTech** [comment]
Fixed in next commit a23e442
