### ISSUE TITLE
Adding button to delete protection history

### ISSUE THREAD

**Issue by Aman1337g** [ChrisTitusTech/winutil#89]
Could you please add a button to delete all the **ANNOYING** *windows security protection history*
![Screenshot (68)](https://user-images.githubusercontent.com/97891757/184687570-6be1645a-8ca0-46cb-8ee6-b815613e830d.png)
.

**Comment by ChrisTitusTech** [comment]
I'll look at adding a remove feature for defender, but by doing anything that interacts with defender the program will be flagged as malicious.
