### ISSUE TITLE
I can't use Windows Voice Typing after running CTT Script

### ISSUE THREAD

**Issue by isharax9** [ChrisTitusTech/winutil#892]
**I can't use Windows Voice Typing after running CTT Script**
Windows Voice Typing Input Experience Voice typing is not available after running I undo everything I do past and it still says,
Speech services are managed by your organization and it's faded out and I can't tick the online speech recognition section in the settings

**Expected behavior**
refer the link plz [https://support.microsoft.com/en-us/windows/use-voice-recognition-in-windows-83ff75bd-63eb-0b6c-18d4-6fae94050571](url)
**Error msg :-**
![image](https://github.com/ChrisTitusTech/winutil/assets/123813453/5df8508f-79c0-4ef5-9c4a-0bdf1158df9d)

**Problem is here:-**
![image](https://github.com/ChrisTitusTech/winutil/assets/123813453/19c3782e-faba-4000-9a99-423c4c5cc793)

**Additional context**
Please  I really want this service back and i tried ChatGPT too to fix it nothing helps 
 [you can find chat gpt link here](https://chat.openai.com/share/622e943a-bd49-40cb-9196-dac36228b851)

**Comment by isharax9** [comment]
hey, I found what registries occur this error. here is how to fix it.
<h3> First you need to open the reg editor. after going to the below path. you can find it below too<h3/>
> Computer\HKEY_CURRENT_USER\Software\Microsoft\Speech_OneCore

![image](https://github.com/ChrisTitusTech/winutil/assets/123813453/ffcedec4-fe06-43e8-94cd-b7b578f0e651)


### Add this regi key and make it value to 1 and use 32-bit DWORD type 

![image](https://github.com/ChrisTitusTech/winutil/assets/123813453/e8814ef9-09ac-4a78-a78d-f26dfdbd8006)

### If you find this some regi values are 0. 0 means false and 1 means true. So you know what to do now like this one 👇
![image](https://github.com/ChrisTitusTech/winutil/assets/123813453/25b4faa8-9960-4dd4-b361-c08f05532271)

finally, Add this regi to your Voice Activation tab and set the value to "1" Boom you're Done restart the pc. Now you can use Microsoft voice typing services calmly

![image](https://github.com/ChrisTitusTech/winutil/assets/123813453/db52ae99-9705-4073-aa48-98c4588ca255)

**Comment by PritishParihar** [comment]
@isharax9 I don't have option of Settings at all, have you created that by yourself? 

![Image](https://github.com/user-attachments/assets/67f7ac6d-3441-4f05-bc03-82e15e3e2396)

**Comment by isharax9** [comment]
> [@isharax9](https://github.com/isharax9) I don't have option of Settings at all, have you created that by yourself?
> 
> ![Image](https://github.com/user-attachments/assets/67f7ac6d-3441-4f05-bc03-82e15e3e2396)

I think as i remember that i created it by myself. try by your end

**Comment by PritishParihar** [comment]
> > [@isharax9](https://github.com/isharax9) I don't have option of Settings at all, have you created that by yourself?
> > ![Image](https://github.com/user-attachments/assets/67f7ac6d-3441-4f05-bc03-82e15e3e2396)
> 
> I think as i remember that i created it by myself. try by your end

I tried myself with default values inside Settings folder key, i guess there are other folder as well can share more derails of the setting key folder from your windows so that i can try
