### ISSUE TITLE
StevenBlack's Unified Hosts File

### ISSUE THREAD

**Issue by zr0fve** [ChrisTitusTech/winutil#893]
https://github.com/StevenBlack/hosts#updating-hosts-file-on-windows
I use this on every windows machine I have. The default I think is the Unified hosts = (adware + malware) variant

**Comment by ChrisTitusTech** [comment]
I'm not going to change everyones host file. A more elegant solution is a DNS server you manage that makes these changes. 
Changing hosts file is frowned upon.
