### ISSUE TITLE
Tweaks-Selection "Desktop" disables SCardSvr

### ISSUE THREAD

**Issue by litLizard69** [ChrisTitusTech/winutil#894]
**Describe the bug**
When going to the Tweaks-Section of winutil, choosing the 'Desktop' recommended selection and running the selected tweaks, after rebooting, the Smartcard-Service (SCardSvr) in Services (Run -> services.msc) gets disabled.

**To Reproduce**
1. Go to 'Tweaks'
2. Click on 'Desktop' (Recommended selection)
3. Click on 'Run Tweaks'
4. Reboot
5. Check Smartcard-Service (SCardSvr) in Services (Run -> services.msc)
6. (You will see that the service has been disabled)

**Expected behavior**
The Smartcard-Service (SCardSvr) remains untouched and activated.

**Additional context**
This Smartcard-Service (SCardSvr) in Windows is used for devices like YubiKeys and without it features of it don't work (e. g. the program Yubico Authenticator doesn't recognize the plugged in Yubikey, because the Smartcard-Service is disabled).

**Comment by ChrisTitusTech** [comment]
Thanks for the report, this will be changed to manual in the next update.
It is commited to test and should be pushed live next week 
f2982e3

**Comment by litLizard69** [comment]
Thank you very much!
