### ISSUE TITLE
HKLM Disable Privacy Experience

### ISSUE THREAD

**Issue by LoopTJ** [ChrisTitusTech/winutil#896]
**Is your feature request related to a problem? Please describe.**
After going through the Windows OOBE "Hi" screen and clicking through all of the telemetry options I found a regkey that disables this for future user accounts.

**Describe the solution you'd like**
Add an option to update the registry which disables the OOBE privacy experience

**Describe alternatives you've considered**
Save the reg key as a .reg file and add it manually.

**Additional context**
Example of the command to use:
```
Write-Host "Disabling Privacy Experience..."
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\OOBE" -Name "DisablePrivacyExperience" -Type DWord -Value 1
```

Example of the reg key:
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\OOBE]
"DisablePrivacyExperience"=dword:00000001

**Comment by YusufKhalifa1** [comment]
Sorry bro, but this issue page is only for the winutil issue not for windows you can look for help any where else
