### ISSUE TITLE
Hiding 3D Objects Icon Error

### ISSUE THREAD

**Issue by tkiral** [ChrisTitusTech/winutil#90]
Util errors out at "Hiding 3D Objects icon" when running "Laptop" tweak. See attached screenshots for more error info.
![issue_pg1](https://user-images.githubusercontent.com/20247751/180861291-4c2dfaca-a582-4d6f-bcc3-dd0e8d8394bb.PNG)
![issue_pg2](https://user-images.githubusercontent.com/20247751/180861294-4bf5c089-8a04-4a2f-9d78-50d8702e5779.PNG)

**Comment by ChrisTitusTech** [comment]
Refenced in #82 - Closing this as duplicate.
