### ISSUE TITLE
Installing WinGet does not work on Windows Server 2022 20348.1850

### ISSUE THREAD

**Issue by jdpatdiscord** [ChrisTitusTech/winutil#903]
**Describe the bug**
Installing programs do not work at least on Windows Server 2022

**To Reproduce**
(This is as administrator, as required)
On Windows Server 2022 with July 2023 patches, up to date (20348.1850)
Run the script, 
say N to installing Chocolatey, (I reran the script with Y to let it install just to see, still did not function with chocolatey.)
select some programs (VC++x86,x64, .NET 3.1, 5, 6 Runtimes are what I selected),
click Install Selection,
Observe it attempting to install winget using the "Alternative Installer" and 
Observe "Winget failed to install"

**Expected behavior**
For it to work

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/42700985/ab88382a-e273-4a76-924d-2d7fc5405d6f)

**Additional context**
This server is a domain controller. Not in production (to ease your nerves.)
P.S. I watched your video about fixing bugs most recently and it occurred to me I have never tried your tool and always ripped out pieces of Windows myself. Figured I would try it on a untouched VM like this one. Immediately bumped into this.

**Comment by YusufKhalifa1** [comment]
titus will fix the script soon but for now you can use atheroto winget install script it works every time 
https://github.com/asheroto/winget-installer

**Comment by ChrisTitusTech** [comment]
Fixed in commit #917 today
Revamped Winget installation to not use microsoft store at all
