### ISSUE TITLE
[Tool Request] Add scrcpy

### ISSUE THREAD

**Issue by ssuvamm** [ChrisTitusTech/winutil#906]
scrcpy utility to mirror android mobile

add scrcpy from winget or chocolatey
https://github.com/Genymobile/scrcpy/blob/master/doc/windows.md

Direct install or download from release 

Very useful free tool for android mirroring over USB or Wifi. Has many options for mirroring.

**Comment by ChrisTitusTech** [comment]
Adding to #374 I use scrcpy all the time.
