### ISSUE TITLE
Update Settings Description false

### ISSUE THREAD

**Issue by litLizard69** [ChrisTitusTech/winutil#907]
**Describe the bug**
Comparing the Update tweaks description on your GitHub-Page and the description in the winutil itself, they are not the same and I think the one on GitHub here is the correct one and the one in the winutil is outdated.
That's because I still get cumulative updates in Windows Update even with 'Security (Recommended) Settings' applied.

**To Reproduce**
1. Go to 'Updates'
2. Read the 'Security (Recommended) Settings' description

**Comment by YusufKhalifa1** [comment]
chris waits until he make a huge change then he update the website version so you should use the github one,

**Comment by litLizard69** [comment]
Reminder, that this issue is still present.
