### ISSUE TITLE
Program search not working after selecting recommended tweaks

### ISSUE THREAD

**Issue by mormislaw** [ChrisTitusTech/winutil#909]
**Describe the bug**
Start menu search on Windows 10 does not find installed programs after selecting recommended tweaks for desktop or laptop.

Undoing "set services to manual" does not make a difference. It's a fresh windows install, indexing is turned on and (supposedly) working. I did not remove cortana.

**To Reproduce**
1. Apply recommended tweaks for desktop or laptop
2. Install programs
3. Try finding them in start menu search

**Expected behavior**
I should be able to find my installed programs and apps in built-in search.

This happened on two separate fresh Windows 10 Pro installations

I'd appreciate any help.

**Comment by Yan1k** [comment]
windows search is crap sometimes works fine sometimes it's just usless i suggest you to use some kind of search launcher like the one that comes with poweroys or flow launcher.

**Comment by dmitriy1980** [comment]
Look no further than Everything from https://www.voidtools.com/. It's extremely fast, useful and magnitude better than Windows built-in search. I've been using it for years.

**Comment by ChrisTitusTech** [comment]
Fixed in commit #917 today
There is a new tweak to bring back Bing search on bar
