### ISSUE TITLE
Black screen on tabbing out of fullscreen games

### ISSUE THREAD

**Issue by awayqn** [ChrisTitusTech/winutil#911]
After doing the "desktop" recommended selection tweak, i reboot and when i play Fortnite or RDR2, if i tab out or back in i get a 3 second black screen in which i can't see anything including my cursor, i checked other issues for this and tried to no avail, so i undid the tweaks and it was fixed. 
My pc is kind of crappy and when I was playing the tweaks helped a lot with performance but the black screen was very annoying.

**Comment by YusufKhalifa1** [comment]
maybe cpu throttling option try disabling it and try again ?

**Comment by antunnitraj** [comment]
I used to have that bug before winutil was a thing. Try reinstalling windows and if the bug is still there then that's not a problem with winutil sadly.

**Comment by Alexciao** [comment]
In the game, using Borderless Fullscreen instead of regular Fullscreen fixed it for me.

**Comment by awayqn** [comment]
> In the game, using Borderless Fullscreen instead of regular Fullscreen fixed it for me.

yea but then i get more input delay and less fps

**Comment by awayqn** [comment]
> I used to have that bug before winutil was a thing. Try reinstalling windows and if the bug is still there then that's not a problem with winutil sadly.

theres a setting called disable fullscreen optimiztions which if you have enabled it gives you the black screen, i had it disabled and with tweaks applied i still got the black screen. i undid the tweaks and kept FS opti disabled and the black screen was fixed
