### ISSUE TITLE
Failed when searching source: msstore

### ISSUE THREAD

**Issue by DtotheAtotheVtotheE** [ChrisTitusTech/winutil#920]
Hello Chris, 

I am runing irm https://christitus.com/win | iex  as admin and I am getting this when trying to install programs.  I'm using v23.07.27.

Checking if Winget is Installed...
Winget Already Installed

Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a15005e : The server certificate did not match any of the expected values.

**Comment by Brown-Boi-Nash** [comment]
@DtotheAtotheVtotheE Can you check the winget version (The command is: `winget --version`) that has been installed?

**Comment by DtotheAtotheVtotheE** [comment]
I'm on v1.5.1881.

**Comment by Brown-Boi-Nash** [comment]
@DtotheAtotheVtotheE Here are a few similar issues I found in github:

1. [https://github.com/microsoft/winget-cli/issues/3109](url)
2. [https://github.com/microsoft/winget-cli/issues/2879](url)
