### ISSUE TITLE
Twitter Install through MS Store Fails

### ISSUE THREAD

**Issue by ChaseKnowlden** [ChrisTitusTech/winutil#922]
**Describe the bug**
Getting Twitter through the MS Store will ask you for a Microsoft account when installing it, and ignoring it will not install Twitter.

**To Reproduce**
1. Open MS Store
2. Search for Twitter
3. Press Get
4. App will not install

**Expected behavior**
Twitter should install without problems.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/46290258/36612aa2-2311-4a1a-a686-95186c777edd)

**Additional context**

**Comment by ChrisTitusTech** [comment]
Probably something about it rebranding to X... damn it ELON! This isn't anything with the utility though.
