### ISSUE TITLE
WinUtil.exe even with Exceptions popup says Trojan:Win32AgentTesla!ml and Sig OK - What to DO??

### ISSUE THREAD

**Issue by adenawilder** [ChrisTitusTech/winutil#923]
### Discussed in https://github.com/ChrisTitusTech/winutil/discussions/891

<div type='discussions-op-text'>

<sup>Originally posted by **adenawilder** July 19, 2023</sup>
https://github.com/damienvanrobaeys/Windows_Sandbox_Editor/issues/1
![WinUtil Digital Signature Verified and still a problem](https://github.com/ChrisTitusTech/winutil/assets/53023792/10866824-5f78-4a64-8aed-8b41ca966186)

![image](https://github.com/ChrisTitusTech/winutil/assets/53023792/7372bf58-11d8-404f-91c7-db6e2d74c64a)

![winutil popup more info Trojan Win32 AgentTesla](https://github.com/ChrisTitusTech/winutil/assets/53023792/08933ddd-84a9-4719-9e23-d86ef0b330b4)
![winutil popup even with exceptions in Windows Security](https://github.com/ChrisTitusTech/winutil/assets/53023792/d9ea6d76-e27f-4370-83a7-689a34438033)
</div>

**Comment by ChrisTitusTech** [comment]
These are false positives as long as it is signed by me (CT Tech Group) I know there is no viruses or modifications. Any executable that uses powershell to modify the system in this way will be flagged as a virus.
