### ISSUE TITLE
Why does the "default settings" windows update option ADD policies instead of removing them?

### ISSUE THREAD

**Issue by thecatontheceiling** [ChrisTitusTech/winutil#925]
**Describe the bug**
I was expecting the default windows update button to remove all of the policies and actually reset them as the button implies it does however I was having issues with windows update even though CTT was claiming it had reset everything and then I found the issue.

**To Reproduce**
1. Click on Windows Update defaults button

**Expected behavior**
I expect everything to actually be reset instead of adding more policies

The 4 year delaying part also seems to not work at all and is a terrible idea as well, youre gonna be EOL before you get the feature update lmao

**Comment by T0m0rr0w** [comment]
Can confirm. Setting default WU options in CTT creates AU subkey under HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate with values:
AUOptions (value 3)
NoAutoUpdate (value 0)

WU itself shows these policies as:
Download the updates automatically and notify when they are ready to be installed.
Set Automatic Update options.

**Comment by sabaasa** [comment]
no response and issue isn't addressed, over 160 open issues all ignored :/

no effort put in, shit tool all in all.
