### ISSUE TITLE
Advanced Menu (Dots / Dashes / Burger or Standard Windows)

### ISSUE THREAD

**Issue by influential-eliot** [ChrisTitusTech/winutil#927]
# Description
A menu bar to house advanced options for winutil operations.

It can grow (of course) with the app, but from the off, it may be a good place to put options that are best not _immediately_ tapped by a user. Things like accessing Logs or halting an install.

## Design and UX/UI
In my head I looked at winutil and see that there is a chance it might cede to much Win10/11 design cues and combine the title bar eventually. So I figured that first version of the menu could aim directly at a '...' or '_burger_' style.

Those commonly associated with compressed Windows applications, mobile apps, or web sites/apps.

Operation would be:

1. Tap the menu dots/burger
2. Menu appears
3. Select advanced option

Once you feel like coming back to it, you could add '_full windows_' style menu structure, and suchlike.

Either that, or go classic Windows first, and add the '_File_', '_Edit_', etc, menu. Then progress to burger dots.

I almost suggested using the CTT icon for the menu (_**DOUBLE** HIDDEN_) because it is essentially for power options. This would be great for ensuring that someone accidentally pressing 'force quit' or something, but would not really be amaaaaazingly traditional UI work.

## Initial Menu Suggestions
Rather than splooge two additional suggestions that related to this probably dismissable one, I have listed three initial suggestions here:

1. Close Active PowerShell Session
2. Force Quit Current Install
3. Session Logs

### Close Active PowerShell Session
This relates to another suggestion that I am about to make relating to initiating a secondary PowerShell window or tab at whatever privilege level the first was launched at. 

Ref: #928

### Force Quit Current Install
This would act like a '_Break_' on a command that may have stalled for some reason.

This could also be set to break the current install, and skip to the next.

### Session Logs
I think this would be most useful for you, basically temp logs for whatever winutil is doing currently. Obviously these would not contain any sensitive data, but they could assist in logging issues, here.

# Incident Related?
No.

My feature request is not related to any specific problem, however troubleshooting tools (_that can aide you_) can be placed in this which will be more broadly aligned to general troubleshooting or whatever you like, I suppose.

## Additional Context
I don't have much more to add, really, I have mocked up some awful versions of what I mean, though.

![ChrisTitusTech-winutil--UX-UI--Menu-Suggestion-001](https://github.com/ChrisTitusTech/winutil/assets/112952958/d05d9395-982b-4aad-a124-ad1a702389e2)

![ChrisTitusTech-winutil--UX-UI--Menu-Suggestion-002](https://github.com/ChrisTitusTech/winutil/assets/112952958/ede98a0a-5c97-469f-a866-5b9d55766cbd)

**Comment by ChrisTitusTech** [comment]
The main issue with this is limitations of drawing everything in real time using powershell. This isn't a compiled program with libraries to call from. I'm working on a C# version with WinUI3 that will make a UI that is fantastic, but that one will look like a Windows 11 Setting menu from Microsoft. Much cleaner and sexier.

**Comment by influential-eliot** [comment]
A good point well made. 👏

I agree, too, definitely a good look. Perhaps some of that ancillary functionality that I mentioned might be useful, though. Session logs especially for you, and some ability to 'break' a currently (apparently) stalling/failing install. However I wouldn't want to suggest those without a more ... _hidey_ ... place for them to be.

**Comment by ChrisTitusTech** [comment]
Yeah there is definitely a place for both styles. I love the open nature of the program as it is now, but I wouldn't mind making a C# program for the people that donate that mirrors the tweaks from the this program in a sexy UI that runs from an EXE instead of a Powershell prompt.
