### ISSUE TITLE
Add Agent Ransack to Install Section

### ISSUE THREAD

**Issue by ThickPropheT** [ChrisTitusTech/winutil#93]
name | about | title | labels | assignees
-- | -- | -- | -- | --
Add Agent Ransack to Install Section | [Agent Ransack](https://www.mythicsoft.com/agentransack/) is a free file system search utility for both Commercial and Personal use that utilizes multi-threading to execute searches at particularly high speeds. It supports file/directory name searches as well as file content searches in boolean, wildcard, and regex formats. This utility is a must have for me and I think it deserves more praise and exposure, so it would be awesome if winutil had a checkbox for installing it under the Install tab. |   |   |

**Comment by ChrisTitusTech** [comment]
Can't add this program since it is not accessible from winget.
