### ISSUE TITLE
Utility seems to kill all Bluetooth related functionality of Windows 10

### ISSUE THREAD

**Issue by jbruell** [ChrisTitusTech/winutil#931]
**Describe the bug**
After using the utility on a fresh Windows 10 install with the recommended tweaks, I no longer have the option to connect to Bluetooth devices. When trying to add a device in the settings, an error pops up.
I can find no mention of Bluetooth anywhere else, the Quick Setting toggle in the notification center is gone and there is no Bluetooth section visible in the Device Manager.

Even starting the "Bluetooth Support Service" manually does not resolve the issue.

**To Reproduce**
1. Run the script on a clean Windows 10 install

**Expected behavior**
Running the script should either not disable Bluetooth at all, or make it clear beforehand.

**Screenshots**
Sorry for the German error, this is the window that pops up when trying to add a new Bluetooth device via the settings:
![image](https://github.com/ChrisTitusTech/winutil/assets/31685172/b7b52bfb-5fcd-4d83-bc57-b2de344bef32)
Bluetooth Services:
![image](https://github.com/ChrisTitusTech/winutil/assets/31685172/5a96098d-0eca-4de6-96f5-3839dca7a2a2)

**Additional context**
none

**Comment by ChrisTitusTech** [comment]
Thanks for the report, I just submitted a fix for the bluetooth services in c4bb1a6
