### ISSUE TITLE
What's the correct delay of feature updates?

### ISSUE THREAD

**Issue by AdamJedl** [ChrisTitusTech/winutil#938]
**Describe the bug**
### readme show 2 days
https://github.com/ChrisTitusTech/winutil/blob/2321c071ee220354f5f1649fc36d9d4ce284e398/README.md?plain=1#L63
### xml show 2 years
https://github.com/ChrisTitusTech/winutil/blob/2321c071ee220354f5f1649fc36d9d4ce284e398/xaml/inputXML.xaml#L564
### powershell script show 365 days
https://github.com/ChrisTitusTech/winutil/blob/ddc1fc9c1460ba39d1111798b6e4efdc511d6d35/functions/public/Invoke-WPFUpdatessecurity.ps1#L34

**Expected behavior**
Should be the same.

**Comment by ChrisTitusTech** [comment]
The security updates are delayed 2 days and feature updates 1 year. 

I'll update the readme and gui.

**Comment by AdamJedl** [comment]
Okay, I understand feature updates but all 3 files show a delay of security updates by 4 days.
