### ISSUE TITLE
Windows Server Winet Install

### ISSUE THREAD

**Issue by AshlynOrSomethin** [ChrisTitusTech/winutil#939]
Add Winget to WIndows Server - Likely in the Tweaks Section is where I'd recommend it.

Add something similar to this: https://gist.githubusercontent.com/likamrat/cae833a6e5b3461709f14c093c21c293/raw/ce5a3210262b9a82626b0553e1fcefd809f52ea6/WinGet_WinSrv.ps1
It works well, haven't encountered issues on 2019, 2022, or Preview versions.

It would be useful because by default, Windows Server doesn't support the same "Desktop Experience" that Windows Home/Pro or even LTSC do.

**Comment by ChrisTitusTech** [comment]
Dig the addition, My current script goes off of PS version 7 and this would be a good detection for switching how winget is installed. 

I will also be changing the following: Get-WmiObject is deprecated in powershell core and it should be replaced with Get-CimInstance in case user opened the utility/script from core.
