### ISSUE TITLE
Chocolatey-Only Installs

### ISSUE THREAD

**Issue by AshlynOrSomethin** [ChrisTitusTech/winutil#941]
I would like to see the ability to have chocolatey-only installs alongside the current install methods.

I was working on adding applications to the utility and was going to add Chatterino but it doesn't have a winget version. It does have a chocolatey version however, but adding only the chocolatey version causes the utility to say it worked even though it installs absolutely nothing.

**Comment by Velosofy** [comment]
This also can solve a lot of stuff Winget issue has.
For example, CLI tools doesn't get properly imported to PATH if installed using Winget but fine with Choco.

**Comment by ChrisTitusTech** [comment]
We are still working on the chocolatey fallback.
