### ISSUE TITLE
WARNING: Waiting for service 'Bluetooth Audio Gateway Service (BTAGService)' to stop...

### ISSUE THREAD

**Issue by ChiefSet** [ChrisTitusTech/winutil#945]
I've been constantly receiving this warning. I'm just curious as to what is happening, and if I can switch off my computer while it;s installing these tweaks.
![image](https://github.com/ChrisTitusTech/winutil/assets/141627664/5317ae2b-eeb9-4a13-aebd-50a0e47a4c20)

**Comment by FACS27** [comment]
Having the same problem, did you figured it out?
