### ISSUE TITLE
tool not detecting some applications

### ISSUE THREAD

**Issue by darkside3211** [ChrisTitusTech/winutil#946]
I've just moved from windows 10 to windows 11 and I have some applications that are already installed on a different drive.

whenever I press "get installed" it doesn't seem to get some of the applications that I have installed in the list. for example I already have VS code installed previously on a separate drive and previously it detects it but now it doesn't

this also goes for when I click on "upgrade all" it doesn't seem to fetch my other apps that I've already installed previously like GiMP, vs code. and others.
this wasn't really an issue before but now it just doesn't seem to be working right
see screenshots for examples. 

![Screenshot 2023-08-08 124130](https://github.com/ChrisTitusTech/winutil/assets/122371336/2f16fbd9-4267-482f-97b1-1a55b664f766)
![Screenshot 2023-08-08 124116](https://github.com/ChrisTitusTech/winutil/assets/122371336/e9131536-4197-48e0-a314-05bd3349e24a)
![Screenshot (5)](https://github.com/ChrisTitusTech/winutil/assets/122371336/3f2a3978-14ef-4f51-99c5-db1be97dfed3)
![Screenshot 2023-08-08 124021](https://github.com/ChrisTitusTech/winutil/assets/122371336/01274f0e-d280-4c9f-b08c-10b30597ccee)
![Screenshot (4)](https://github.com/ChrisTitusTech/winutil/assets/122371336/a3b2876c-941b-424c-b956-22f540ce2038)
![Screenshot 2023-08-08 123852](https://github.com/ChrisTitusTech/winutil/assets/122371336/59d063d9-2e26-4029-89eb-d2e749113ebe)
![Screenshot 2023-08-08 123726](https://github.com/ChrisTitusTech/winutil/assets/122371336/9d81018a-480a-4e88-9765-e0bd9b443c38)

**Comment by DeveloperDurp** [comment]
Did you install them through winget? It's using winget to see everything that's installed, if winget can't see it winutil won't pick it up either.
