### ISSUE TITLE
Running `Tweaks > Desktop` Breaks Start Menu Search

### ISSUE THREAD

**Issue by ThickPropheT** [ChrisTitusTech/winutil#95]
**Describe the bug**
Running `Tweaks > Desktop` breaks start menu search for apps installed/uninstalled after the tweak has been run. As an example, I'll describe the scenario as experienced on my clean install of Windows 10, which had the Windows Store version of Spotify installed. If you run the `Tweaks > Desktop` tweak, uninstall the Windows Store version of Spotify, install the normal Desktop version of Spotify, then attempt to search for Spotify using the start menu search feature, only the Windows Store version will be suggested, but the link will not function correctly (no app starts and there are no options to run as administrator, open file location, etc.). It seems that this action freezes the search functions view of applications installed to before the `Tweaks > Desktop` tweak is run, which is further supported by the start menu not finding Gimp, which I installed after having run the tweak.

**To Reproduce**
**NOTE** I attempted to reproduce this issue both by running the `Tweaks > Desktop` tweaks, installing ImgBurn, then running a start menu search and by uninstalling Agent Ransack then running a search, but ImgBurn does still show up in the search correctly for whatever reason. AgentRansack, however, exhibits the same behavior as described above. I'm not sure why ImgBurn still shows up in searches correctly. What I do know is that [setting the `Let apps run in the background` option to `true`](https://superuser.com/a/1208858/290051) resolved my problem and that running `Tweaks > Desktop` reset the `Let apps run in the background` toggle to `false`.

1. Follow instructions [here](https://www.youtube.com/watch?v=tPRv-ATUBe4&t=94s) until you get to `Tweak`
2. Select the `Desktop` option under `Recommended Selections`, then click `Run Tweaks`
3. Install a new application
4. Press the `Win` key and type the name of the newly installed application
5. `NOTICE` that windows cannot find the application, even if links to that application exist within the [search indexer's path](https://winbuzzer.com/2020/09/25/how-to-reset-and-rebuild-the-search-index-in-windows-10-xcxwbt/)
6. `NOTICE` that [re-enabling the `Settings > Background Apps > Let apps run in the background`](https://superuser.com/a/1208858/290051) setting fixes the issue.

**Expected behavior**
Using the start menu's search feature should continue to operate as it did before the tweak was run.

**Screenshots**

Tweak Run > Agent Ransack uninstalled:
![AgentRansackNotInstalled](https://user-images.githubusercontent.com/6137018/181445257-95f3039c-6fbd-435a-81a3-0dda5ad20045.PNG)

Search still reports Agent Ransack results:
![AgentRansackStillDetected](https://user-images.githubusercontent.com/6137018/181445444-2cfb9043-37dd-42d9-81a8-783566cbb062.PNG)

**Comment by ChrisTitusTech** [comment]
This was removed in PR #94
