### ISSUE TITLE
Add PolyMC To Application List

### ISSUE THREAD

**Issue by Snomwan** [ChrisTitusTech/winutil#951]
Can someone add PolyMC to the application menu. Because I like PolyMC more than any other minecraft launcher and there is a misinformation that PolyMC is a virus which it isn't. If anyone adds this to the pull requests that would be much appreciated.

**Comment by Uranite** [comment]
I'm not sure where you've heard that it's a virus, but ChrisTitusTech please don't add polymc, as the maintainer is malicious by doing a [hostile takeover](https://github.com/PolyMC/PolyMC/commit/ccf282593dcdbe189c99b81b8bc90cb203aed3ee) of the project.

**Comment by AshlynOrSomethin** [comment]
@Snomwan Prism Launcher was already added which is a fork of PolyMC just with less politics involved in the software.

**Comment by Snomwan** [comment]
I can see why. But I still prefer PolyMC. 
But thanks for replying!

> @Snomwan Prism Launcher was already added which is a fork of PolyMC just with less politics involved in the software.
