### ISSUE TITLE
AutoHotkey

### ISSUE THREAD

**Issue by hulknosmash** [ChrisTitusTech/winutil#954]
**Describe the bug**
Does not install autohotkey

No package found matching input criteria.

**Expected behavior**
Install autohotkey

**Additional context**
installed immediately after using choco

**Comment by aaronkorn** [comment]
cannot install autohotkey
using version 23.08.08

Checking if Chocolatey is Installed...
Chocolatey Already Installed
Checking if Winget is Installed...
Winget Already Installed
No package found matching input criteria.

**Comment by aaronkorn** [comment]
this might be the new command for version 2

winget install -e --id AutoHotkey.AutoHotkey

https://winget.run/pkg/AutoHotkey/AutoHotkey

**Comment by aaronkorn** [comment]
installed manually

PS C:\Users\famil> winget install -e --id AutoHotkey.AutoHotkey

Found AutoHotkey [AutoHotkey.AutoHotkey] Version 2.0.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.4/AutoHotkey_2.0.4_setup.exe
  ██████████████████████████████  2.79 MB / 2.79 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\famil>

**Comment by aaronkorn** [comment]
the current code doesnt work

PS C:\Users\famil> winget install -e --id Lexikos.AutoHotkey

No package found matching input criteria.
PS C:\Users\famil>
