### ISSUE TITLE
Add The Minecraft Launcher To The WinGet Install Tab Under Games

### ISSUE THREAD

**Issue by MrBignose5866** [ChrisTitusTech/winutil#957]
Can Someone add The Minecraft Launcher To The Winget Install Tab

Minecraft Launcher WinGet Id: **Mojang.MinecraftLauncher**

**Comment by v1mkss** [comment]
There is already a minecraft launcher, but it is not official, the name is "Prism Launcher", Section "Games".

**Comment by ThatPowerShellGuy1** [comment]
Add the official one
