### ISSUE TITLE
Add Image-Editor Paint.net

### ISSUE THREAD

**Issue by chloecdn** [ChrisTitusTech/winutil#959]
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
Add Paint.net to List of Multimedia-Tools

**Describe alternatives you've considered**
/

**Additional context**

Website: https://getpaint.net/
WinGet ID: `dotPDNLLC.paintdotnet`
choco id: `paint.net`

**Comment by chloecdn** [comment]
Closing this, has been added in #1143

**Comment by Inventhrice** [comment]
Wa hoo! Fellow paint.net user!!
