### ISSUE TITLE
Disable Sticky keys "shortcut key" pop-ups

### ISSUE THREAD

**Issue by Sokoloft** [ChrisTitusTech/winutil#963]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would love to have a check box tweak to disable the sticky keys pop-up. It happens when you press shift 5 times. I always forget to disable this on new installs. As well as the two other pop-ups for Toggle/Filter keys. I've never used or seen people use this feature.

**Describe alternatives you've considered**
I have considered writing a script. However it doesn't seem like its a simple registry edit. I found [this](https://stackoverflow.com/a/71860597/17266105) script on stackoverflow, however I don't understand it and cant get it to also disable the Toggle/Filter keys. I considered writing one based on key inputs, however that seems like a hacky solution and would require the user to not interact with the kb/mouse.

**Additional context**
These are the settings, they're always ticked on a new install.
![WindowsSandboxClient_1h9BK3RKy2](https://github.com/ChrisTitusTech/winutil/assets/49052130/8d803c50-e709-48f3-b704-701a7b22356b)

Thank you.

**Comment by Yuuh15** [comment]
A toggle to disable sticky keys has been added on commit #1556
