### ISSUE TITLE
can't open the utility

### ISSUE THREAD

**Issue by bugsbias** [ChrisTitusTech/winutil#967]
I can't open the utility. it shows me following two types of errors in 2 different commands. 

> irm https://christitus.com/win | iex

and 

>  [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')

```
irm : Unable to connect to the remote server
At line:1 char:1
+ irm https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
``` 
I COULD open it the first time.

**Comment by Velosofy** [comment]
Looks like an Internet problem, can you visit the URL in the browser just fine?

**Comment by 8mpty** [comment]
try running ```irm https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1 | iex``` instead if the above commands doesn't work

**Comment by ThatLadLegend** [comment]
Have you tried changing your DNS to cloudflare?
