### ISSUE TITLE
Winget Issue on Server 2022 using WinUtil

### ISSUE THREAD

**Issue by KALIXHOSTING** [ChrisTitusTech/winutil#973]
Winget is still having a issue showing it is not installed but it is installed as I installed it with this script https://gist.githubusercontent.com/likamrat/cae833a6e5b3461709f14c093c21c293/raw/ce5a3210262b9a82626b0553e1fcefd809f52ea6/WinGet_WinSrv.ps1

![winget](https://github.com/ChrisTitusTech/winutil/assets/93708739/69243dca-6ea9-4fa3-9751-6df070555493)

![winutil](https://github.com/ChrisTitusTech/winutil/assets/93708739/57d85955-df48-4ec3-a05b-c203f3ed5477)
I have already tried it on multi SV2022 and other Server Edition Works perfect on 2016, 2019, Windows 10 Windows 11 but for some reason it doesn't want to work on SV2022  

Thank you 

Keep Up The Great Work on This Tool Just Makes Our Life Easier 💯

**Comment by tkwj** [comment]
Your script run into the winget license issue, which is also currently affecting the winget script used internally here.
To make this more confusing, your script in screenshot 1 is reporting an incorrect success. (see the n"no applicable license " text)

This relates to the following issue discussed here: https://github.com/asheroto/winget-install/issues/17
This root issue should be resolved when the upstream winget-install v2.1.0 is pulled into winutil here.

The follow-on issue is that winutil tests for the presence of the symlink file (~\AppData\Local\Microsoft\WindowsApps\winget.exe) to determine if already installed. However, this is not accurate in the case of a missing license. Technically winget exists but it is not done being installed, at least for server 2022. This causes us to get into a loop where winutil thinks winget is installed and ready for use but then it can't actually be used.

**Comment by ChrisTitusTech** [comment]
You know I never thought of installing winget through chocolatey... that is actually a brilliant idea.

**Comment by rickychii** [comment]
I'm testing ur tool on Windows Server 2022, installing apps with winget it's working, but I'm not able to run tweaks:

![image](https://github.com/ChrisTitusTech/winutil/assets/129695864/9d9606f0-5394-4fd0-82ab-b9d8cf8f2186)

As you can see program is stuck trying to make a restore point. On Windows Server 2022 restore point are not present, they are moved to Windows Backup.

Thanks,
Ricky-

**Comment by rickychii** [comment]
Reporting the exact same problem on Windows Server 2019.

Ricky.
