### ISSUE TITLE
Winget Install fails on fresh Win 11 install, World

### ISSUE THREAD

**Issue by jnstockley** [ChrisTitusTech/winutil#974]
**Describe the bug**
On a fresh install of windows 11 22h2 build 22621.1702, using the World setting from the ThioJoe tweet Winget fails to install.

**To Reproduce**
1. Install windows 11 following the steps in ThioJoe's tweet to debloat windows 11.
2. Run some tweet
3. Install programs using Winget
4. Winget fails to install.

**Expected behavior**
Winget should install.

**Screenshots**
![PowerShell Screenshot](https://github.com/ChrisTitusTech/winutil/assets/34308937/31d7fd09-20df-4b34-af1e-b8952b14e1bb)
[powershell-output.log](https://github.com/ChrisTitusTech/winutil/files/12388860/powershell-output.log)
[Winutil.log](https://github.com/ChrisTitusTech/winutil/files/12388861/Winutil.log)

**Additional context**
I was in the process of installing windows updates but did not finish them. The install ISO file was downloaded today, 8/20/2023 around 1:00 PM

**Comment by jnstockley** [comment]
Installing updates to version 22521.2134 and restarting then trying to install with Winget, the win util was able to install the apps.

**Comment by ChrisTitusTech** [comment]
World installs require you to specify the region to get ms store functionality. That would fix it as well, sadly I can't support a blank World install with winget.
