### ISSUE TITLE
Windows Updates not working!

### ISSUE THREAD

**Issue by supertrio17** [ChrisTitusTech/winutil#976]
I ran winutil almost a year ago and didnt ran windows update ever since, and now I get error 0x80004002.
I already tried undoing all tweaks and ran windows update reset but with no luck. I even tried everything I found online like deleting windows update temp folder.

If anyone has any idea how to fix this behaviour cuz it will suck to reinstall windows 11 again.

Thanks.

![IMG_20230822_223204](https://github.com/ChrisTitusTech/winutil/assets/57882120/22dcbd10-ff0e-4920-95ec-4b99fafceca9)

**Comment by dmitriy1980** [comment]
Try these options and see which one works:

1. Run Windows Update Troubleshooter
2. Rename the Software Distribution folder and Catroot 2 folder
3. Reset Windows Update Components

NOTE: These options are outside of winutil software.

**Comment by supertrio17** [comment]
I already tried deleteing Software Distribution folder and running windows update troubleshooter, but troubleshooter just runs for hours without anything happening, just loading. Ill try doing this again when I get home and will keep you updated.

**Comment by dmitriy1980** [comment]
Try in a Safe Mode.

**Comment by supertrio17** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/57882120/e5d64bfd-8502-4d7d-bae7-7372a2813097)

**Comment by supertrio17** [comment]
Tried it, still doesn't work. Running troubleshooter now works, it said the problem was fixed, but still nothing. Downloading is on 0% and after 10 minutes it says retry. One thing that I should add is that microsoft store apps do not work as well, even tho i undid the tweak, so I'm thinking it has something to do with that. And for how I fixed the error with troubleshooter, somehow bits service wasnt starting, so I manually started it.

**Comment by supertrio17** [comment]
I resolved my problem. For anyone having similar issues with windows, what I did is I downloaded new windows 11 iso and updated my windows from that, like you would from 10 to 11, for some reason you can do that from 11 to 11, and then I Reset Windows Update Components. Updating just replaces windows files so you keep all apps and personal files.

For how to Reset Windows Update Components its preatty easy.

Open Terminal or Powershell as admin and type this commands one by one
`net stop bits
net stop wuauserv`

Then locate C:\Windows\SoftwareDistribution and delete the entire folder.
If you have trouble stopping bits and wuauserv services you can open task manager, services, locate them and remember their PID, then open Terminal or CMD as administrator and force kill the service process with the following command
`taskkill /f /pid 5332` 

_PS. 5332 is placeholder for your pid process._

As for resolving this issue I think I could have done something about it manually, because winutil probably changed behaviour of bunch of services from automatic to manual and vice versa, and probably deleted a lot of them as well, I think winutil functionality should be looked at because from bugs issued on github I can see that a lot of times undoing tweaks does nothing. 

Thanks for helping with this bug!
