### ISSUE TITLE
Unrecognized command : 'remove' and false positives in Get Installed

### ISSUE THREAD

**Issue by luiza177** [ChrisTitusTech/winutil#978]
Can't uninstall detected packages, also apparently unintended packages were also either installed or falsely detected.

I installed Git, VSCode. Later on I clicked `Get Installed`, and the three got checked, but also GitHub Desktop and VSCodium. When I attempt to uninstall VSCodium and GitHub Desktop, by checking their boxes and clicking `Uninstall Selection`, winget throws a `Unrecognized command : 'remove'` error. 

If I attempt to uninstall them 'manually' either via winget or via the Settings app, neither shows up.

**Comment by ChrisTitusTech** [comment]
Fixed remove error in commit d6a68b0

This will be merged to main in the coming weeks.
