### ISSUE TITLE
Create System Restore Point before applying any changes to the system

### ISSUE THREAD

**Issue by Barnacules** [ChrisTitusTech/winutil#983]
A great addition to this tool would be for it to create a System Restore Point like Windows Update does before installing any apps or applying any settings changes to the system. It would only require a simple PowerShell command to be added to the install/apply execution stack to give you the ability to recover if the computer doesn't reboot successfully after some changes are made (heaven forbid).

**Create restore point before installing applications: **
Checkpoint-Computer -Description "CTTWU Restore Point (Before Installing Apps)" -RestorePointType "APPLICATION_INSTALL"

**Create restore point before applying Tweaks:**
Checkpoint-Computer -Description "CTTWU Restore Point (Before Applying Tweaks)" -RestorePointType "MODIFY_SETTINGS:"

And for extra credit you could also add a restore point before doing uninstalls or removing tweaks using the "APPLICATION_UNINSTALL" RestorePointType and reusing the "MODIFY_SETTINGS" type respectively.

**Example:**
1. User selects 5 apps and clicks "Install Selection."
2. Run [Checkpoint-Computer -Description "Restore Point (Applying Tweaks)" -RestorePointType "APPLICATION_INSTALL"]
3. Install 5 Applications
4. If something goes wrong or doesn't install properly leaving the system in a limbo state ask user if they want to restore from before the installation.
5. Run [Restore-Computer -RestorePoint "Restore Point (Before Installing Apps)"]
- Do same for applying tweaks but use the different restore point name

**Possible Issues:**
1. You can only create a single system restore point in 24 hours unless you change the registry key [SystemRestorePointCreationFrequency' under the registry key 'HKLM\Software\Microsoft\Windows
NT\CurrentVersion\SystemRestore] to a value of 0 which means you can create as many restore points as you want as frequently as you want. But a single restore point is probably fine for most.
2. You could end up with a lot of restore points eating up disk space if user installs one app at a time over and over. But this could be worked around by only allowing the user to do a single restore point before using the utility and if anything goes wrong they just revert to the state before the utility was run by restoring the last "CTTWU Restore Point *" restore point if anything goes wrong and if it detects that restore point by that name already exists it just won't try to create another one. 

This would be a very easy feature to implement and would give the end user a lot more security against things that could potentially go wrong leaving the system in a limbo state or possibly not able to reboot requiring a restore point to be selected to get machine back to booting order if some Windows Update messes up one of the Tweaks or some application compatibility thing like Microsoft loves to do.

**Error that occurs if you try to create more than one restore point in 24 hours without reg hack.**
![image](https://github.com/ChrisTitusTech/winutil/assets/8484226/7f2fe62a-c4a6-4a6e-aec1-3cdfaee7aa63)

Thank you,
Jerry (aka. Barnacules)
![image](https://github.com/ChrisTitusTech/winutil/assets/8484226/06127a47-03b9-430d-b786-34f2d7734784)

**Comment by ChrisTitusTech** [comment]
Thanks for letting me know of this bypass. Tracked down the key I needed and added to commit [21fd81f](https://github.com/ChrisTitusTech/winutil/commit/21fd81f6a3420507366188fdc30c8c23388dc91f) should be merged to main next week.
