### ISSUE TITLE
CPU-Z appears twice under Utilities (Duplicate?)

### ISSUE THREAD

**Issue by Barnacules** [ChrisTitusTech/winutil#984]
Under the Utilities section it shows CPU-Z twice. My guess is that someone just accidentally added it twice to the backend file that keeps track of all the installer commands. But, if they are different in some way the name should differentiate so people don't get confused since right now they appear to be the same exact thing. 

![image](https://github.com/ChrisTitusTech/winutil/assets/8484226/7af25a45-51eb-4dfd-898b-82440e983264)

**Comment by Giann1s** [comment]
The second one is for [GPU-Z](https://www.techpowerup.com/gpuz/), not [CPU-Z](https://www.cpuid.com/softwares/cpu-z.html)
