### ISSUE TITLE
Some settings become managed by administrator after running WinUtil (Windows 11 Pro)

### ISSUE THREAD

**Issue by g-iori** [ChrisTitusTech/winutil#988]
Power Plan settings and Display sleep/turn off settings are all greyed out rendering user unable to alter them.
More settings may also be affected but I didn't detect them yet.

1. Run WinUtil on a Windows 11 install
2. Run Desktop Tweaks
3. Run "Add Ultimate Performance Profile"

I believe it was expected that these settings could be changed but not locked for the user.

![image](https://github.com/ChrisTitusTech/winutil/assets/44445709/878e0686-565b-46fa-89f7-081d13837c58)
![image](https://github.com/ChrisTitusTech/winutil/assets/44445709/c2b72dd0-4964-4e3e-aeeb-d9c1007ea8ee)
![image](https://github.com/ChrisTitusTech/winutil/assets/44445709/b7610e27-e944-4d8c-8eab-84877a70311f)

Am I doing something wrong? Are there any way to unlock settings that become managed by the system?

Thanks in advance

**Comment by jstack01** [comment]
Are you signed is as a local administrator? Are you in a domain environment that has a GPO power plan applied to this pc?
