### ISSUE TITLE
Windows Spotlight can't be run after running the tweak

### ISSUE THREAD

**Issue by ABAL1412** [ChrisTitusTech/winutil#989]
**Describe the bug**
I'm using Windows 10 on Microsoft Surface Laptop Studio. After running the laptop preset at the Tweak section, the Windows Spotlight doesn't work anymore. It stuck at only 1 image for a week. Beside that, the "Like what you see" button at the lock screen also disappear.

**To Reproduce**
1. Open Settings
2. Click on Personalization
3. Click on Lock screen
4. At the background section, change to Windows Spotlight
5. Run PowerShell with Admin privilege
6. Run the following code: irm christitus.com/win | iex
7. Click on Tweaks
8. Click on Laptop
9. Click on Run Tweaks
10. After running the tweaks, click Windows + L

**Expected behavior**
The Windows Spotlight keeps showing only 1 image, day by day.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/135466317/ba41a14b-d974-45c1-a3a8-bd45f8e59fe3)

Thank you for making this tool, as well as reading my report. After running the tweaks, my laptop runs a bit faster. That's what Microsoft must do, but they don't. Thank you so much! All the best wishes to you.

**Comment by ChrisTitusTech** [comment]
This is a huge backend that eats up system resources. I'd recommend switching it to a more controlled spotlight 3rd party app called "Dynamic Theme" from the MS Store. 
It can auto download and switch the lock screen and desktop to spotlight or bing image of the day.

**Comment by Bobsonot** [comment]
This isse has not been resolved yet, windows spotlight is gone, I mean the option is there, just not pulling images.

**Comment by GabiNun2** [comment]
> This isse has not been resolved yet, windows spotlight is gone, I mean the option is there, just not pulling images.

which tweaks did you run?

**Comment by Bobsonot** [comment]
> > This issue has not been resolved yet, Windows Spotlight is gone, I mean the option is there, just not pulling images.
> 
> which tweaks did you run?

the default selection when you open it.

**Comment by GabiNun2** [comment]
> > > This issue has not been resolved yet, Windows Spotlight is gone, I mean the option is there, just not pulling images.
> > 
> > 
> > which tweaks did you run?
> 
> the default selection when you open it.

i ran the tweaks and it works fine
