### ISSUE TITLE
Network Status shows no network connection

### ISSUE THREAD

**Issue by engr317** [ChrisTitusTech/winutil#990]
I am using Win 10 Pro 22H2 and after using the Windows Utility, my computer shows there is no network connection, however, I am still connected.  I have tried making the appropriate changes to the Registry, but it still fails to show that I am connected.  Please advise.
![Capture](https://github.com/ChrisTitusTech/winutil/assets/66848230/61988d03-1999-42f2-8248-ac95c15c2dfa)

**Comment by ChrisTitusTech** [comment]
I'd recommend resetting your network.

netsh int ip reset
netsh winsock reset

Run from an admin prompt
