### ISSUE TITLE
Bing Search in Start Menu Removal Issue

### ISSUE THREAD

**Issue by icariiax** [ChrisTitusTech/winutil#994]
**Describe the bug**
Winutil Seems to hang on Disabling Bing Search

**To Reproduce**
1. Go to 'Winutil>Tweaks tab'
2. Click on '"Bing Search in Start Menu slider'
3. Check Powershell (Admin Access)
4. See error:  "Deployment operation in progress: Microsoft.549981C3F5F10_4.2308.1005.0_X64_8wekyb3d8bbwe Processing [" on the top status. With "Disabling Bing Search " at the Prompt at the bottom for over an hour.
5. 

**Expected behavior**
The code runs until complete and notification pops up stating that Operation is finished.  Searching from the Start Menu no longer includes Bing.  
*The tweak does remove Bing from the Start menu of the User who runs app.  Only doesn't ever display it's completion in either Powershell or the Winutil program, and doesn't work for other users, though the sliding button is in the "Off" position.

**Screenshots**

**Additional context**

**Comment by CamoCatX** [comment]
I can verify that this happens to me too.
